### ISSUE TITLE
[Question] Why Nested observation spaces are not supported by Stable Baselines3?

### ISSUE THREAD

**Issue by Pw2333** [DLR-RM/stable-baselines3#1003]
### Question

Hello! 
I'm trying to use nested observations in my custom enviorment. But I got a UserWarning in env_checker.py: 
UserWarning: Nested observation spaces are not supported by Stable Baselines3 (Dict spaces inside Dict space). You should flatten it to have only one level of keys.

Why? Although it's easy to flatten the observations like the warning instructs, I still want's to use nested observations for code
explicity. I want to use a custom combined features extractor to preprocess my nested observations and concatenate them into a 1-D tensor.

### Additional context

None

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by qgallouedec** [comment]
To my knowledge, there is no reason for this, but I am waiting for confirmation from other maintainers.

Can you show us how you build your feature extractor in the case of a nested observation? If it works well, you could submit a PR for this feature to be supported.

**Comment by qgallouedec** [comment]
I'm also curious to see how you cope with the `DictReplayBuffer`. It probably doesn't work with nested observations.

**Comment by araffin** [comment]
Hello,

> Nested observation spaces are not supported by Stable Baselines3

This is both to keep code simple and for performance reasons: if we were to support any depth of dict, we would have recursive calls for preprocessing (particularly slow in python) and we would need to have more complex buffers (and slower ones).

That's why SB3 only allows one level of keys.
You can still used nested obs inside your env but then use a wrapper to convert obs for SB3. You can also replace the levels with a dot notation. For instance if you had `{"level1": {"level2": value}}`, you could flatten it to `{"level1.level2": value}`

**Comment by Pw2333** [comment]
> Hello,
> 
> > Nested observation spaces are not supported by Stable Baselines3
> 
> This is both to keep code simple and for performance reasons: if we were to support any depth of dict, we would have recursive calls for preprocessing (particularly slow in python) and we would need to have more complex buffers (and slower ones).
> 
> That's why SB3 only allows one level of keys. You can still used nested obs inside your env but then use a wrapper to convert obs for SB3. You can also replace the levels with a dot notation. For instance if you had `{"level1": {"level2": value}}`, you could flatten it to `{"level1.level2": value}`

C
