### ISSUE TITLE
Default Architecture in SB3

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1005]
What is the default neural network architecture used in SB3 algorithms? And where can these be retrieved from?

**Comment by araffin** [comment]
Hello,
to retrieve them, either look at the code or do as in https://github.com/DLR-RM/stable-baselines3/issues/329

the defaults depend on the algo and the observation space.
For 1d observation space, a 2 layers fully connected net  is used with:
- 64 units (per layer) for ppo/a2c/dqn
- 256 units for sac
- [400,300] units for td3/ddpg

For image observation space, the "Nature CNN" (cf. code for more details) is used for feature extraction and sac/td3 keep also the same fully connected net (the other algos have just a linear layer after the cnn).
The CNN is shared between actor and critic for a2c/ppo.

For mixed observations (dict obs), the two arch from before are used, so cnn for images and then 2 layers net (with a smaller output size for the cnn).

**Comment by anilkurkcu** [comment]
Thank you for the reply.

So as an example, if I am using A2C and I want to overwrite my architecture with this:

policy_kwargs = dict(net_arch=[dict(pi=[1024, 1024, 1024, 512, 512, 512], vf=[1024, 1024, 1024, 512, 512, 512])])
model = A2C('MlpPolicy', env, policy_kwargs=policy_kwargs, verbose=1, device="cuda:3")

In this case, I would obtain a [1024 x 1024 x 1024 x 512 x 512 x 512] instead of the default [64 x 64] architecture right?

**Comment by araffin** [comment]
yes, although i would not recommend to use such deep net in RL.

**Comment by anilkurkcu** [comment]
Could you elaborate why? Is this recommendation related to SB3 or RL itself?

**Comment by araffin** [comment]
> Could you elaborate why? Is this recommendation related to SB3 or RL itself?

This is a recommendation for RL itself.

For the why, you can try it yourself ;)
There are different reasons and the main one is that usually such deep nets are not needed to solve the tasks.
Another one is more an empirical one, try it yourself and you'll see, maybe you'll get better results, but by experience, you don't most of the time.

**Comment by anilkurkcu** [comment]
Thanks for the advice :)

For my current setup, instead of the Gym environments, I am using a custom environment with observation space of 1530 and action space of 24. Based on these space dimensions, I was considering to use larger networks.

**Comment by araffin** [comment]
Re-opening as we should add that to the documentation (the questions comes from time to time), @anilkurkcu I would be happy to receive such PR ;)

**Comment by anilkurkcu** [comment]
Would be more than happy if I can do anything about this :)
