### ISSUE TITLE
[Bug] _init_callback in base_class does not handle verbose parameter when creating EvalCallback

### ISSUE THREAD

**Issue by BurakDmb** [DLR-RM/stable-baselines3#1006]
### 🐛 Bug

Hi,

I just noticed that in the `_init_callback` method, the verbose parameter is not used when creating `EvalCallback`. Since the default verbose value is 1 in the EvalCallback, logging could not be disabled when only using the default verbose value.

Code reference: 
https://github.com/DLR-RM/stable-baselines3/blob/c4f54fcf047d7bf425fb6b88a3c8ed23fe375f9b/stable_baselines3/common/base_class.py#L389-L396

https://github.com/DLR-RM/stable-baselines3/blob/c4f54fcf047d7bf425fb6b88a3c8ed23fe375f9b/stable_baselines3/common/callbacks.py#L307

### To Reproduce
I would like to set verbose=0 in my studies, and therefore, when I enable evaluation, I cannot decide whether to print the evaluation results or not.

Below, you can see my example code:

```
model = PPO(..., verbose=0, ...)

model.learn(..., eval_env=eval_env,
            eval_freq=100,
            n_eval_episodes=5,
            eval_log_path="eval")
```

### Expected behavior

I think this problem could be solved easily by passing the `self.verbose` variable into the EvalCalback constructor.

I can volunteer for this PR.

```
if eval_env is not None:
    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path=log_path,
        log_path=log_path,
        eval_freq=eval_freq,
        n_eval_episodes=n_eval_episodes,
        verbose=self.verbose,
    )
    callback = CallbackList([callback, eval_callback])
```

### System Info

`({'OS': 'Linux-5.13.0-40-generic-x86_64-with-glibc2.17 #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022', 'Python': '3.8.13', 'Stable-Baselines3': '1.6.1a0', 'PyTorch': '1.11.0', 'GPU Enabled': 'True', 'Numpy': '1.22.3', 'Gym': '0.25.0'}, 'OS: Linux-5.13.0-40-generic-x86_64-with-glibc2.17 #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022\nPython: 3.8.13\nStable-Baselines3: 1.6.1a0\nPyTorch: 1.11.0\nGPU Enabled: True\nNumpy: 1.22.3\nGym: 0.25.0\n')`

### Checklist
 

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by qgallouedec** [comment]
I see your point. If we want to be rigorous, you are right, `verbose=0` should not permit to write anything to stdout.

However, I think many people like the format with evaluation log without training log (currently supported by `verbose=0`).

I need more feedback on this.

**Comment by araffin** [comment]
Hello,
good point, verbose value should be passed.
Also related: I was thinking about removing the `eval_env` parameter completely (https://github.com/DLR-RM/stable-baselines3/issues/925) as its usage is limited and bring complexity to the codebase.
A better alternative is to create the eval callback outside the model and pass it to the `learn()` method.

**Comment by qgallouedec** [comment]
> I can volunteer for this PR.

So yes, please go ahead.
