### ISSUE TITLE
[Question] Why is the default device `"auto"` everywhere except in buffers?

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/stable-baselines3#1007]
### Question

Is there a reason why the device default is `"auto"` everywhere except in the buffers?

#### DDPG

https://github.com/DLR-RM/stable-baselines3/blob/a6f5049a99a4c21a6f0bcce458ca3306cef310e0/stable_baselines3/ddpg/ddpg.py#L77

#### PPO

https://github.com/DLR-RM/stable-baselines3/blob/a6f5049a99a4c21a6f0bcce458ca3306cef310e0/stable_baselines3/ppo/ppo.py#L98

...

#### Base buffer

https://github.com/DLR-RM/stable-baselines3/blob/a6f5049a99a4c21a6f0bcce458ca3306cef310e0/stable_baselines3/common/buffers.py#L42

#### Replay buffer

https://github.com/DLR-RM/stable-baselines3/blob/a6f5049a99a4c21a6f0bcce458ca3306cef310e0/stable_baselines3/common/buffers.py#L177

....

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
> Is there a reason why the device default is "auto" everywhere except in the buffers?

I guess i did that to avoid calling `get_device()` once more.
They are anyway initialized correctly with `self.device` when creating the buffer inside each algorithm.

**Comment by qgallouedec** [comment]
> They are anyway initialized correctly with self.device when creating the buffer inside each algorithm.

Indeed, the implementation of the algorithms allows this not to be a source of bug.

However, features extractors and algorithms support `"auto"` as an argument for device but not buffers. I would find it more consistent that all SB3 objects take the same possible values for the `device` argument.  Even if `get_device` is called 4 times instead of 3 at initialization. What do you think about this?

**Comment by araffin** [comment]
>  I would find it more consistent that all SB3 objects take the same possible values for the device argument. 

fair enough ;)
