### ISSUE TITLE
[Question] Is it not possible to combine VecNormalize and VecMonitor so that rollout is normalized.

### ISSUE THREAD

**Issue by robvasistha** [DLR-RM/stable-baselines3#1008]
### Question
I was wondering if it was possible to normalize the ep_rew_mean from VecMonitor? If not how could I go about that. 

My current project is comparing PPO via a custom gym env to a symbolic method.

I think that the best way to do this would be to normalise the reward for both methods so they are comparable.

Can I also ask for an elaboration on `norm_obs`, to my understanding I want the PPO model to run as normal but want the results to be normalised so I can compare them. Does this mean that in my case I would want `norm_obs` to be false?

### My current solution:
![image](https://user-images.githubusercontent.com/78962360/184509564-5c75089d-938a-4204-93d5-dfdda28f6bcb.png)

### Checklist

- [ x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by robvasistha** [comment]
I am no longer in need of doing this as I just un-normalized the other method and it seems to be fairly valid.

I will leave this issue open as it does not seem possible and it could be another feature to add?

**Comment by araffin** [comment]
> project is comparing PPO via a custom gym env to a symbolic method.

Not sure to understand why using running statistics (that what `VecNormalize` does) would help you compare to the symbolic method... you usually want to save the un-normalized reward to be able to compare two methods.
