### ISSUE TITLE
[Question] How to correctly use 'CnnPolicy'?

### ISSUE THREAD

**Issue by Karol-G** [DLR-RM/stable-baselines3#101]
Hi,

my env returns an image observation of shape (40, 40) with low=0 and high=255 as uint8. So naturally I want to use the 'CnnPolicy' with my DQN. However, the following code throws the following error:

`
model = DQN('CnnPolicy', env, learning_starts=50, verbose=1, tensorboard_log="./logs/")
`

```
AssertionError: You should use NatureCNN only with images not with Box(40, 40) (you are probably using `CnnPolicy` instead of `MlpPolicy`)
```

I have defined this in my env:

`
self.observation_space = spaces.Box(low=0, high=255, shape=(target_size, target_size))
`

Best
Karol

**Comment by Miffyli** [comment]
You need to include the channel dimension in the end, which for gray-scale images would mean `shape=(target_size, target_size, 1)`.

**Comment by Karol-G** [comment]
This sadly does not work :/ I get the same error

**Comment by araffin** [comment]
Hello,
please fill the issue template completely and notably use the env checker ;)

**Comment by Karol-G** [comment]
Thanks I used the env checker. My error was to not specify the dtype like this:
`self.observation_space = spaces.Box(low=0, high=255, shape=(target_size, target_size), dtype=np.uint8)`

Best
Karol
