### ISSUE TITLE
[Question] Training and eval env are not of the same?

### ISSUE THREAD

**Issue by leo2r** [DLR-RM/stable-baselines3#1017]
### Question

Is there a way to wrap a single environment in a 'transpose image' wrapper? Do I need to use VecEnv with num_envs = 1 and then VecTransposeImage? Or should I just fix the channel ordering directly in my custom env (will affect my rendering code etc)?

### Additional context

I've made a custom env, and I am now preparing to train. For the training env, I use SubProcVecEnv and during runtime it gets wrapped in a VecTranposeImage. I think because of this, my eval_env (which is just done with gym.make(env_id)) doesn't match the training env so I get the "Training and eval env are not of the same" warning during runtime. 

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

>  Or should I just fix the channel ordering directly in my custom env

If you have access to the custom env, best is to fix it here.

> will affect my rendering code etc

you can just do the transformation before returning the observation (and you need to change the obs space shape), it doesn't have to affect the rest of your code.

> Is there a way to wrap a single environment in a 'transpose image' wrapper? Do I need to use VecEnv with num_envs = 1 and then VecTransposeImage?

You could write your own gym wrapper but best is to use a DummyVecEnv wth `num_envs=1` and then wrap it with `VecTransposeImage` (SB3 only works with VecEnv and will wrap it automatically anyway, you can take a look at `EvalCallback` code).

**Comment by leo2r** [comment]
Thanks for the quick reply! I will first try wrapping with a DummyVecEnv and VecTransposeImage, and then resort to fixing it in the custom env directly if that doesn't pan out! 🙏🏽 Keep up the great work 🎉
