### ISSUE TITLE
Is it possible to continue learning with num_envs>1 if the saved model was done with num_envs=1 ?

### ISSUE THREAD

**Issue by LutzFassl** [DLR-RM/stable-baselines3#1018]
### Question

Is it possible to continue learning with num_envs>1 if the saved model was done with num_envs=1 ?

### Additional context
I am normally learning with (standard):
```
model = MaskablePPO("MlpPolicy", env, ...) 
model.learn(total_timesteps=TIMESTEPS, callback=checkpoint_callback, eval_env = eval_env, eval_freq = 2_500_000, n_eval_episodes = 100)
```
Which is a DummyVecEnv with num_envs=1.
I have no problem saving, loading and continue learning with this:
```
model = MaskablePPO.load(...)
model.num_timesteps = chkpt_max #set timesteps
model.learn(total_timesteps=TIMESTEPS, reset_num_timesteps=False, ...)
```
However I realized the learning takes still too long after a certain hyperparameter-optimization.
I would like to learn with num_envs >1 (either DummyVecEnv or SubProcVecEnv depending which works better for my case).
_But also I would not like to learn completely from scratch as I would loose all the good progress._

As far as I understand, the n_env / num_env parameter is included in the saved zip file. Therefore when loading it will again load a DummyVecEnv with num_envs = 1. Is there a way to load my model and continue to learn it with num_envs>1 (DummyVecEnv or SubProcVecEnv)?

Thanks for your answer!
Lutz

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

>  Is there a way to load my model and continue to learn it with num_envs>1

`model.set_env(env)` should do the trick.

> As far as I understand, the n_env / num_env parameter is included in the saved zip file. 

where is it used in your case?

**Comment by LutzFassl** [comment]
Hello Antonin, thanks for your response. If I understand correctly, I can just load the model with PPO.load(..) and use the env argument of .load() to use the changed env (will then be a vectorized DummyVecEnv or SubProvEnv with more than one env) to see if there are no errors and learning continues as expected. That would be great, I will try that after holiday and otherwise check with the set_env approach and report back. Thanks!

**Comment by araffin** [comment]
> I can just load the model with PPO.load(..) and use the env argument of .load() to use the changed env

in theory yes but looking at the code, this part is buggy when using different number of envs, `set_env()` will work in that case (you will still need to call `_setup_model` to re-initialize the buffer).

I would be happy to receive a PR that fixes this issue ;)
(it currently works but not consistently)

```python
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env

model = PPO("MlpPolicy", "CartPole-v1", verbose=1)
model.learn(total_timesteps=2048)

model.save("ppo_cartpole")
del model

# Does not work as n_envs is not updated
# model = PPO.load("ppo_cartpole", env=make_vec_env("CartPole-v1", n_envs=2))
model = PPO.load("ppo_cartpole")

# Use 2 envs instead of 1
model.set_env(make_vec_env("CartPole-v1", n_envs=2))
# Reinitialize the buffer
model._setup_model()
model.learn(total_timesteps=2048)
```
