### ISSUE TITLE
Moving to Gym Vector Environments?

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/stable-baselines3#102]
Given that Gym has upstreamed vector environments, in an implementation arguably a little cleaner than ours, would it make sense to use that as the vector environment base class for SB3 instead of having it's own?

**Comment by PartiallyTyped** [comment]
Hi,
I think that it is unlikely until OpenAI solidifies it, doesn’t make breaking changes and documents it well. For example the recent Atari wrappers were bugged so we (well @araffin noticed and) reverted back.

**Comment by araffin** [comment]
Hello,
my full reply is already in the roadmap discussion ;)
https://github.com/DLR-RM/stable-baselines3/issues/1#issuecomment-627321747
