### ISSUE TITLE
[Feature Request] request title

### ISSUE THREAD

**Issue by Forbu** [DLR-RM/stable-baselines3#1021]
### 🚀 Feature

Making stb3 compatible with gym 0.24 version

### Motivation

Some software (pettingZoo / supersuit) are only compatible with gym 0.24 so we better make the transition now.

### Pitch

Well the plan is :
- check the problematic function and correct the issues :)

### Alternatives

Keep the same dependencies to gym 0.21 :(

**Comment by Forbu** [comment]
I will try to make the change

**Comment by araffin** [comment]
Duplicate of #780
