### ISSUE TITLE
[Question] Warning when using Callback funcion

### ISSUE THREAD

**Issue by hotpotking-lol** [DLR-RM/stable-baselines3#1024]
### Question

I am using SB3 Callbacks during training. I run my job on HPC through SLURM job scheduler from my institute. I always get below warning, and the job script will some time end earlier. This warning only occurs when I use callbacks function, otherwise no warning occurs : 

```python
/home/myacc/.local/lib/python3.9/site-packages/stable_baselines3/common/base_class.py:835: ResourceWarning: unclosed file <_io.BufferedWriter name='/home/myacc/ondemand/data/sys/myjobs/projects/default/31/rl_model_10000_steps.zip'>
  save_to_zip_file(path, data=data, params=params_to_save, pytorch_variables=pytorch_variables)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
### Additional context
Here is my whole code for running:
```python
import os
from stable_baselines3 import SAC
from stable_baselines3.common.callbacks import CheckpointCallback
# Save a checkpoint every 1000 steps
current_directory = os.getcwd()
log_dir = current_directory
os.makedirs(log_dir, exist_ok=True)
checkpoint_callback = CheckpointCallback(save_freq=10000, save_path=log_dir,
                                         name_prefix='rl_model')

model = SAC('MlpPolicy', 'Pendulum-v1')
model.learn(200000, callback=checkpoint_callback)
```
My version of package is :
Python 3.9
gym-0.21.0
stable-baselines3-1.6.0
torch-1.12.0

### Checklist

- [ ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html) 
- [ ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment]
Hello,

> This warning only occurs when I use callbacks function, otherwise no warning occurs :

do it happens if you call `model.save()` after training?
Did you ask for enough disk space when launching the SLURM job?

You could try enabling [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) as suggested in https://stackoverflow.com/questions/60945317/python-selenium-resourcewarning-enable-tracemalloc-to-get-the-object-allocati to have more debug info


>  I run my job on HPC through SLURM job scheduler from my institute. 

I guess it does not happen locally?

**Comment by hotpotking-lol** [comment]
> Hello,
> 
> > This warning only occurs when I use callbacks function, otherwise no warning occurs :
> 
> do it happens if you call `model.save()` after training? Did you ask for enough disk space when launching the SLURM job?
> 
> You could try enabling [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) as suggested in https://stackoverflow.com/questions/60945317/python-selenium-resourcewarning-enable-tracemalloc-to-get-the-object-allocati to have more debug info
> 
> > I run my job on HPC through SLURM job scheduler from my institute.
> 
> I guess it does not happen locally?

Thank you so much for the reply. My script run training process for 23 hours on SLURM and been terminated by SLURM. I feel like it is something about diskspace problem because I start a same job and run successfully 3 days. 
This problem do not occurs locally. Thanks a lot! closing this issue.

**Comment by ReHoss** [comment]
@hotpotking-lol , usually 23 hours is the duration for a job on a HPC, you could save the model and restart the job with loaded parameters...

**Comment by araffin** [comment]
See https://github.com/DLR-RM/stable-baselines3/issues/1729#issuecomment-1802210543 to have a minimal example to reproduce the bug, will try to push a fix soon.
