### ISSUE TITLE
TD3 issue on prediction

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1026]
I have been experimenting with TD3 using a callback function that does an evaluation of the model every thousand timesteps. It seems that when using TD3 the evaluation of the model gives always the same reward, no matter how long I train it.

I tried the same setup with A2C and there isn't any issue at all with it, so I suppose it has something to do with the TD3 implementation.

**Comment by qgallouedec** [comment]
Hi, please fill the issue template. Especially, provide a minimal code example so that I can reproduce this.

**Comment by anilkurkcu** [comment]
Thank you for your reply. I just switched my custom environment to the regular gym environments and it works fine. The issue is most probably about the custom environment I have designed in this case.
