### ISSUE TITLE
[Feature Request] Monitor class to append rows instead of overwriting an existing monitor CSV

### ISSUE THREAD

**Issue by sidney-tio** [DLR-RM/stable-baselines3#1035]
### 🚀 Feature

Propose to change `Monitor` class such that it appends new rows when there are existing monitor.csv files in the log directory. 

### Motivation

Most developers may not have access to infinite compute resource. In my case, my server admin allows jobs only for up to 24 hours. Re-running the job with `Monitor` as it is will override any previous logged results.  

### Pitch

Change `ResultsWriter` to initialise the `file_handler` with `"at"` instead of `"wt"`

https://github.com/DLR-RM/stable-baselines3/blob/2cc1477fa28e654caa4b7bf9b367febe726513e8/stable_baselines3/common/monitor.py#L182

### Alternatives

Write our own custom monitor to handle the above case. 

### Additional context

I'm running Bipedal Walker on PPO in addition to some algorithms, 0.1B timesteps (as per rl-baselines's suggestion) will take about 5 days. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
i would add a new parameter to Monitor for that (so behavior stay the same by default) and would welcome a PR that solves this issue ;)

**Comment by sidney-tio** [comment]
Yes, I think that sounds great. I'll raise the PR over the next few days
