### ISSUE TITLE
[Bug] Incorrect type annocation for replay_buffer_class in OffPolicyAlgorithm

### ISSUE THREAD

**Issue by Rocamonde** [DLR-RM/stable-baselines3#1039]
### 🐛 Bug

The type annotation for the `replay_buffer_class` argument in the `sb3.common.OffPolicyAlgorithm` class is incorrect.

Current type: 
```python
replay_buffer_class: Optional[ReplayBuffer]
```

Correct type:
```python
replay_buffer_class: Optional[Type[ReplayBuffer]]
```

### To Reproduce

Run a type checker on any usage of OffPolicyAlgorithm:
```python
OffPolicyAlgorithm(
    ...,
    replay_buffer_class=sb3.HerReplayBuffer
)
```

### Expected behavior

No type error should arise if the type annotation were correct.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by qgallouedec** [comment]
Good catch! Can you submit a PR to fix this?

**Comment by Rocamonde** [comment]
@qgallouedec see https://github.com/DLR-RM/stable-baselines3/pull/1042
