### ISSUE TITLE
[Feature Request] save multi best models in EvalCallback

### ISSUE THREAD

**Issue by xibeisiber** [DLR-RM/stable-baselines3#1045]
### 🚀 Feature

currently EvalCallback seems to only save one best_model. 
Add support for saving multiple best_models (say 5)

### Motivation

In my own environment, from the eval curves in tensorboard,  the training hits the best record many times(with different rewards), but sometimes I can't recover the optimal behavior from the saved best_model.zip (issue: https://github.com/DLR-RM/rl-baselines3-zoo/issues/282). Though I don't understand why, saving several best models may alleviate my problem.  

### Pitch

save several best models in EvalCallback (pass a paramter into the class)

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
have you considered using a Checkpoint callback or a custom callback ? ("alternatives" part in the issue template).

**Comment by xibeisiber** [comment]
> Hello, have you considered using a Checkpoint callback or a custom callback ? ("alternatives" part in the issue template).

checkpointCallback saves models every fixed steps and may save a bad model, if I understand correctly.

Yes, a custom callback is easy to implement by modifying current EvalCallback. But I think it would be an useful feature for sb3 itself. RLlib seems to supports this.

**Comment by araffin** [comment]
> checkpointCallback saves models every fixed steps and may save a bad model, if I understand correctly.

yes, but if you set the save freq to be the same as eval freq, it will save models for every evaluation.
You can then quickly look at the evaluation curve (using tensorboard/W&B or a script) to check the 5 best ones.

> but sometimes I can't recover the optimal behavior from the saved best_model.zip 

This sounds like you should evaluate the agent for more episodes, `--eval-episodes` in the zoo (you can also use multiple envs for evaluation to make it faster)

**Comment by xibeisiber** [comment]
> This sounds like you should evaluate the agent for more episodes, `--eval-episodes` in the zoo (you can also use multiple envs for evaluation to make it faster)

The default value for "deterministic_eval = not self.is_atari(env_id)" is true for my own custom env. So evaluating for more episodes will give the same result.

But if I set "deterministic_eval=False" manually,  evaluating for 5 episodes always gives the same results. I assume something is missing for my env....

**Comment by araffin** [comment]
Replying on the original issue: https://github.com/DLR-RM/rl-baselines3-zoo/issues/282
