### ISSUE TITLE
[Feature Request] Add type checking to tests

### ISSUE THREAD

**Issue by Rocamonde** [DLR-RM/stable-baselines3#1048]
### 🚀 Feature

This issue is to discuss the possibility of including tests in the type checking CI pipeline.

### Motivation

Currently, tests are not being type checked, which means that it's hard/impossible to detect bugs in the type annotations of the end-user API. An example of this is https://github.com/DLR-RM/stable-baselines3/issues/1039, which was being picked up by type checkers on the tests but was not detected for this reason.

### Pitch

Add pytype to tests.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by qgallouedec** [comment]
There is type checking no?

https://github.com/DLR-RM/stable-baselines3/blob/fdca786f0999ea402ad5da98e3d69aa68bcbf635/Makefile#L8

**Comment by Rocamonde** [comment]
That is running pytype with the config specified in setup.cfg which specifies the package only as the input (so not the tests)

https://github.com/DLR-RM/stable-baselines3/blob/fdca786f0999ea402ad5da98e3d69aa68bcbf635/setup.cfg#L22

**Comment by araffin** [comment]
Hello,
> tests are not being type checked,

yes, this is intentional, as @AdamGleave mentioned, we are doing something funky things to test the lib and I didn't to spend much time telling the type checker everything was alright.
If you manage to make it work, I'm happy to merge such PR ;) (just a bit afraid of how more time it will take when checking types, maybe we could add a flag to skip those checks when needed).

**Comment by Rocamonde** [comment]
IMO We should address this as part of the process described in #1121.

**Comment by araffin** [comment]
Done in https://github.com/DLR-RM/stable-baselines3/pull/1143 (for mypy)

**Comment by araffin** [comment]
I'm closing this one as we are now only relying on mypy.
I decided to not check the test for now because we are doing too many funky things (for testing purposes) and to keep the check time small.
