### ISSUE TITLE
[Feature Request] `evaluate_policy` to return episode_rewards sorted according which env produced the rewards 

### ISSUE THREAD

**Issue by sidney-tio** [DLR-RM/stable-baselines3#1051]
### 🚀 Feature

Current implementation of `evaluate_policy` returns a list of episode_rewards that is not ordered by env, but ordered by episodes that completes first. I was thinking if it could be organised environment first, then by completion order.

### Motivation
In my use case, each environment of the eval env are variants of `BipedalWalker`, and it would be useful to track which parameters  resulted in which episode rewards. 

### Pitch

Suggestion to organize the list as a nested list instead, then to append the rewards to the respective indexed-list instead

https://github.com/DLR-RM/stable-baselines3/blob/29f6687b9819dd11934234fb1ea4c3d778cbc51c/stable_baselines3/common/evaluation.py#L73

### Additional context

#925 may be effected by this and vice versa. 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
sounds like a very specific problem...
I would recommend having a custom version of SB3 that fits your need in that case., unless the fix is very simple (evaluation code is already pretty complex and the scope/usefulness for users of this proposed feature seems quite limited)

**Comment by sidney-tio** [comment]
Yeah, I'm currently running a workaround based on `evaluate_policy`. Yep, it's pretty specific, but I was thinking if anyone else would run into this as well. No worries, we can revisit this if someone think its useful.
