### ISSUE TITLE
[Question] Rename VecNormalize to VecStandardize?

### ISSUE THREAD

**Issue by tobirohrer** [DLR-RM/stable-baselines3#1052]
### Question

Would it make sense to rename the `VecNormalize` to `VecStandardize`? When I understand the [implementation](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/vec_env/vec_normalize.py) correctly, `VecNormalize` actually does standardization and not normalization. Renaming of the wrapper and update of the documentation could prevent confusion on this. 

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
what is the difference for you between standardization and normalization?

**Comment by tobirohrer** [comment]
I always thought:
- Normalization is usually used when rescaling values into a fixed interval, e.g. [0;1]. The formula for transformation would be: `(x-min(x))/(max(x)-min(x))`
- Standardization is the process of rescaling data to have mean 0 and standard deviation 1. This is done by substracting the mean and dividing by the standard deviation.

**Comment by araffin** [comment]
I see.
For me, "normalization" is a broader term that refers mostly to re-scaling data, standardization is also called "Z-score normalization", and you have other ways to normalize (for instance divide by the max only, see https://en.wikipedia.org/wiki/Normalization_(statistics) ).

It is true that we use standardization for observations in `VecNormalize`, but this is not the case for the reward normalization (only rescaling is applied, no shift by mean substraction).
