### ISSUE TITLE
[Question] Models I have trained and saved when loaded again don't work

### ISSUE THREAD

**Issue by Shivam310** [DLR-RM/stable-baselines3#1057]
### Question
Models I have trained and saved when loaded again don't work, the agent just doesn't move. Though the same model I trained and used just after training works flawlessly.

### Additional context

This is also happening with pretrained models I have installed.

**Here is my code:**
```
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
import os
env_name = 'CarRacing-v0'
env = gym.make(env_name)
env = gym.make(env_name)
env = DummyVecEnv([lambda: env])
log_path  = os.path.join('Training', 'Logs')
model = PPO('CnnPolicy', env, verbose = 1, tensorboard_log=log_path)
ppo_path = os.path.join('Training', 'Saved Models', 'PPO_280k_Driving_Model')
model.save(ppo_path)
del model
model = PPO.load(ppo_path, env)
evaluate_policy(model, env, n_eval_episodes=10, render=True)
```
Here is the zip file of my trained model I trained locally:

[PPO_280k_Driving_Model.zip](https://github.com/DLR-RM/stable-baselines3/files/9539962/PPO_280k_Driving_Model.zip)

I don't see how this can be a problem. I believe there is some issue when I load the model. Please help.

### Checklist

- [  Yes ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [  Yes ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by qgallouedec** [comment]
Your model is not trained. To train it you must call `model.learn(total_timesteps=280_000)`.

**Comment by Shivam310** [comment]
> Your model is not trained. To train it you must call `model.learn(total_timesteps=280_000)`.

Hi, I have actually trained the model but when I closed my file and opened it again I executed the cells which had the above code. Still its doesn't work.

**Comment by qgallouedec** [comment]
In your code, you first save an untrained model, and then you load it. So at the end, the model evaluated is not trained.

The generic code to train, save and load a model is [in the documentation](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html?basic-usage-training-saving-loading).

Thus, I suggest you to first train your model using the following code

```python
import gym

from stable_baselines3 import DQN

# Create environment
env = gym.make('LunarLander-v2')

# Instantiate the agent
model = DQN('MlpPolicy', env, verbose=1)

# Train the agent
model.learn(total_timesteps=int(2e5))

# Save the agent
model.save("dqn_lunar")
```

Once your agent is trained, you can evaluate it with the following code

```python
import gym

from stable_baselines3 import DQN

# Create environment
env = gym.make('LunarLander-v2')

# Load the model
model = DQN.load("dqn_lunar", env=env)

# Evaluate the model
mean_reward, std_reward = evaluate_policy(model, model.get_env(), n_eval_episodes=10)
```

**Comment by Shivam310** [comment]
> In your code, you first save an untrained model, and then you load it. So at the end, the model evaluated is not trained.
> 
> The generic code to train, save and load a model is [in the documentation](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html?basic-usage-training-saving-loading).
> 
> Thus, I suggest you to first train your model using the following code
> 
> ```python
> import gym
> 
> from stable_baselines3 import DQN
> 
> # Create environment
> env = gym.make('LunarLander-v2')
> 
> # Instantiate the agent
> model = DQN('MlpPolicy', env, verbose=1)
> 
> # Train the agent
> model.learn(total_timesteps=int(2e5))
> 
> # Save the agent
> model.save("dqn_lunar")
> ```
> 
> Once your agent is trained, you can evaluate it with the following code
> 
> ```python
> import gym
> 
> from stable_baselines3 import DQN
> 
> # Create environment
> env = gym.make('LunarLander-v2')
> 
> # Load the model
> model = DQN.load("dqn_lunar", env=env)
> 
> # Evaluate the model
> mean_reward, std_reward = evaluate_policy(model, model.get_env(), n_eval_episodes=10)
> ```

Thanks, it works now.
