### ISSUE TITLE
[Bug] ResultsWriter.filename parent directory MUST exist

### ISSUE THREAD

**Issue by dominicgkerr** [DLR-RM/stable-baselines3#1068]
### 🐛 Bug

When a `stable_baselines3.common.monitor.ResultsWriter` class (i.e. whenever a `stable_baselines3.common.monitor.Monitor` wrapper) is created, a file-handle to the provided `filename` is opened on [line:191](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/monitor.py#L191). If the `filename` contains any directories  (ether relative or absolute), all its parent directories MUST exists, otherwise a `FileNotFoundError` is raised. 

To avoid this, I (simply) have to create the parent directories of `filename` (using, say `os.makedirs(os.dirname(filename))`) first. However, this is often done automatically in other parts of `stable_baselines3` - i.e. `stable_baselines3.common.callbacks.CheckpointCallback._init_callback` and `stable_baselines3.common.env_util.make_vec_env` allow `self.save_path` and `monitor_path` (respectively) to contain missing directories. 

It'd be great if `Monitor`/`ResultsWriter` automatically created missing parent directories, matching the expected behaviour of other parts of `stable_baselines3`.

### To Reproduce

```python
import os
from stable_baselines3.common.monitor import ResultsWriter

assert os.path.exists("./missing/") == False  # when any filename parent does not exist
_ = ResultsWriter(filename="./missing/filename")
```

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./stable-baselines3/stable_baselines3/common/monitor.py", line 191, in __init__
    self.file_handler = open(filename, f"{mode}t", newline="\n")
FileNotFoundError: [Errno 2] No such file or directory: './missing/filename.monitor.csv'
```

### Expected behavior

Automatically create missing directories for `filename`s passed to `ResultsWriter` (and by extension, `Monitor`), allowing environment logging to be saved (easily) without having to worry about directory creation/management.

That is, the following runs without raising an exception (baring issues arising from OS file permissions):
```python
import os
from stable_baselines3.common.monitor import ResultsWriter

assert os.path.exists("./missing/") == False  # when any filename parent does not exist
_ = ResultsWriter(filename="./missing/filename")
assert os.path.exists("./missing/") == True  # automatically created by ResultsWriter
```

### System Info

OS: Linux-5.13.0-52-generic-x86_64-with-glibc2.34 #59-Ubuntu SMP Wed Jun 15 20:17:13 UTC 2022
Python: 3.9.7
Stable-Baselines3: 1.6.1a4
PyTorch: 1.12.1+cu102
GPU Enabled: True
Numpy: 1.23.3
Gym: 0.21.0

### Additional context
I believe this would be a one/two line change (plus, maybe a new unittest), which I'd be very happy to open! 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,
sounds like a reasonable feature (it is actually done automatically when using recommended `make_vec_env` helper) and I would welcome a PR that solves this issue ;) (take a look at what is done in `make_vec_env`)

**Comment by dominicgkerr** [comment]
Hi @araffin 

Thanks for getting back to me (and suggesting I look at ``make_vec_env``). I've just opened a (very small) [PR](https://github.com/DLR-RM/stable-baselines3/pull/1072) to fix this issue!

Thanks again
