### ISSUE TITLE
[Question] Policies with layer normalization

### ISSUE THREAD

**Issue by astrofinix** [DLR-RM/stable-baselines3#1069]
### Question

Will there be there be future plans to implement layer normalized policies (MlpLnLstmPolicy, CnnLnLstmPolicy)?

### Checklist

- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
Layer normalization was originally made for using parameter noise, so they were removed in SB3 (cf. docs).
However, recently, there have some works that do use LN and dropout, so I plan to add those as options in the building blocs: https://github.com/DLR-RM/stable-baselines3/pull/1036

In the meantime, you can always define custom policies (cf. doc again) and for LSTM policies, only `RecurrentPPO` from our contrib repo support them.
