### ISSUE TITLE
Transformer architecture

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1077]
Hello,

Are there any plans to integrate transformer architecture or the attention mechanism into the pre-built architectures within the library?

Thanks!

**Comment by qgallouedec** [comment]
Are you referring to [Decision Transformer: Reinforcement Learning via Sequence Modeling](https://arxiv.org/abs/2106.01345)?

**Comment by qgallouedec** [comment]
If you are, 
1. This paper deals with offline RL, which is out of the scope of sb3. 
2. It seems that a major update is needed, especially for the buffers. Currently, buffers can only store and sample transitions, not sequences (required for decision transformer).

**Comment by anilkurkcu** [comment]
Well not particularly. What I am interested is to simply replace a feedforward NN with a transformer-type architecture.

**Comment by anilkurkcu** [comment]
Is there any possibility for this with the current version of SB3?

**Comment by qgallouedec** [comment]
> Is there any possibility for this with the current version of SB3?

It depends on what you intend to do. To answer that, you would have to be more specific. 

> Are there any plans to integrate transformer architecture

To answer your initial question: no, there is no algorithm based on transformer whose implementation will be integrated in SB3 in the near future. Simply because none of them correspond to a widely used baseline. 

However, some works would have their place in the sb3-contrib repository. Here is a useful resource: #177

 https://github.com/DLR-RM/stable-baselines3/issues/177#issuecomment-703236089

**Comment by anilkurkcu** [comment]
My current problem is that I require a model that could accept variable-dimension state-space and variable-dimension action-space. For this purpose I thought that a transformer would suffice, but I am open to any other suggestions from your side as well.

And thank you for the repo you mentioned :)

**Comment by anilkurkcu** [comment]
Would there be any suggestions for this?

**Comment by qgallouedec** [comment]
Depending on your use, transformer can indeed be an interesting solution. You should discuss this on the [RL Discord](https://discord.com/invite/xhfNqQv), which is a more suitable place for this kind of discussion.
You may also find useful information in the following issues: #478, #144.

**Comment by qgallouedec** [comment]
Also note that for your environment to be integrable under gym (necessary condition to use sb3), you have to use a fixed observation and action size.
