### ISSUE TITLE
[Bug] HumanOutputFormat raises error on duplicate keys

### ISSUE THREAD

**Issue by Rocamonde** [DLR-RM/stable-baselines3#1078]
### 🐛 Bug

When using two keys that have different prefixes (tags) but the same key name, `HumanOutputFormat` will raise, complaining that the keys are duplicated.

### To Reproduce

```python
from stable_baselines3.common.logger import HumanOutputFormat
o = HumanOutputFormat(sys.stdout, max_length=50)
o.write({'key1/banana': 'value1', 'key2/banana': 'value2'}, {"key1/banana": None, "key2/banana": None})
```
Error:

```bash
Traceback (most recent call last):
  File "/Users/rocamonde/git/HumanCompatibleAI/imitation/venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-ff13417a6e34>", line 2, in <module>
    o.write({'key1/banana': 'value1', 'key2/banana': 'value2'}, {"key1/banana": None, "key2/banana": None})
  File "/Users/rocamonde/git/HumanCompatibleAI/imitation/venv/lib/python3.9/site-packages/stable_baselines3/common/logger.py", line 183, in write
    raise ValueError(
ValueError: Key '   banana' truncated to '   banana' that already exists. Consider increasing `max_length`.
```

### Expected behavior

No error should raise. There's no reason why e.g. `model-1/loss` and `model-2/loss` should be disallowed key names.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by qgallouedec** [comment]
Duplicate #256
