### ISSUE TITLE
[Question] Atari Pong / Breakout not learning with default A2C settings

### ISSUE THREAD

**Issue by shuishida** [DLR-RM/stable-baselines3#1083]
Hello - I have tried running the A2C model on the Atari environments with default settings, as indicated in the [colab notebook](https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/sb3/atari_games.ipynb#scrollTo=FtY8FhliLsGm). However, after training for 4e7 timesteps on the simple game of Pong, I am still getting no improvements (score of -20.5, where the minimal score is -21). Here is the code that I ran.

```from stable_baselines3 import A2C
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack

# There already exists an environment generator that will make and wrap atari environments correctly.
env = make_atari_env('PongNoFrameskip-v4', n_envs=4, seed=0)
# Stack 4 frames
env = VecFrameStack(env, n_stack=4)

model = A2C("CnnPolicy", env, verbose=1)
model.learn(total_timesteps=1e9)
```
Similarly, I wasn't able to get any decent improvements with Breakout. I also tried DQN and PPO, neither of which seemed to work.
I was wondering if I am making any trivial mistakes or if there has been some underlying changes to the algorithm / hyperparameters which made it stop working well on Atari.

**Comment by araffin** [comment]
Hello,
if you want to reproduce results, best is to use the RL Zoo (https://github.com/DLR-RM/rl-baselines3-zoo), you can take a look at the hyperparameters used in the yaml files or directly on the huggingface page of the model: https://huggingface.co/sb3/a2c-BreakoutNoFrameskip-v4

```python
OrderedDict([('ent_coef', 0.01),
             ('env_wrapper',
              ['stable_baselines3.common.atari_wrappers.AtariWrapper']),
             ('frame_stack', 4),
             ('n_envs', 16),
             ('n_timesteps', 10000000.0),
             ('policy', 'CnnPolicy'),
             ('policy_kwargs',
              'dict(optimizer_class=RMSpropTFLike, '
              'optimizer_kwargs=dict(eps=1e-5))'),
             ('vf_coef', 0.25),
             ('normalize', False)])
```

The main difference I see here is the entropy coefficient which should be 0.01, not zero (and more envs are used for training).
The default hyperparameters in SB3 were tuned for continuous control (compared to atari games in SB2).

The notebook is here to show the syntax and wrappers, for working hyperparameters, please take a look the zoo.

**Comment by araffin** [comment]
if you want to quickly reproduce results with the RL Zoo:
```
python train.py --algo a2c --env PongNoFrameskip-v4 --verbose 0 -P --vec-env subproc --eval-freq 100000
````

It should reach a score > 0 for Pong in 5e6 timesteps.

**Comment by shuishida** [comment]
Thank you very much! This indeed worked!
