### ISSUE TITLE
[Feature Request] Add progress bar using TQDM

### ISSUE THREAD

**Issue by araffin** [DLR-RM/stable-baselines3#1084]
### 🚀 Feature

bring the feature that is in the RL Zoo:

https://video.twimg.com/tweet_video/FdxJV3qWQAE35MQ.mp4

and make it available as a parameter to the learn method (`progress_bar=True`) and as a callback.

### Motivation

It's a nice to have feature so you know how much time is left, how fast is the algorithm and how much have been done in one glance.

### Alternatives

Keep it in the zoo.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

@Miffyli @qgallouedec @AdamGleave @ernestum what do you think?

**Comment by AdamGleave** [comment]
Seems useful to me, I've liked `tqdm` progress bars other places I've used them for ML.

**Comment by tobirohrer** [comment]
I would like to work on that one :)

For an overview: In RL Zoo it was implemented by [this pull request](https://github.com/DLR-RM/rl-baselines3-zoo/pull/287/files)
