### ISSUE TITLE
Allow for logger setup before calling BaseAlgorithm.learn()

### ISSUE THREAD

**Issue by qxcv** [DLR-RM/stable-baselines3#109]
**Describe the bug**

At present, SB3 algorithms automatically configure the logger on the first call to `{On,Off}PolicyAlgorithm.learn()`. Unfortunately, this prevents the logger from being configured manually beforehand—if the logger is already configured, then the first call to `.learn()` will overwrite that old configuration. This is a problem for code bases that wish to use the SB3 logger for both SB3 RL algorithms and for other non-SB code (for example, we use the SB logger for both discriminator training and RL in the GAIL implementation from [imitation](https://github.com/HumanCompatibleAI/imitation/)). Ideally, custom logger configuration should be moved out of the `.learn()` method, or the logger configuration update inside `.learn()` should be made optional via a keyword argument to `PPO`.

**Code example**

The following code demonstrates the issue I am trying to overcome:

```python
import gym
import stable_baselines3
from stable_baselines3.common import logger 

# show initial config
print("Logger outputs at startup:", logger.Logger.CURRENT.output_formats)

# set up logger
logger.configure("./path/to/my/logs", ["stdout", "tensorboard"])
print("Logger outputs before training:", logger.Logger.CURRENT.output_formats)

# now instantiate & train
env = gym.make("CartPole-v1")
algorithm = stable_baselines3.PPO("MlpPolicy", env)
algorithm.learn(32)
print("Logger outputs after training:", logger.Logger.CURRENT.output_formats)
```

Current output:

```
Logger outputs at startup: [<stable_baselines3.common.logger.HumanOutputFormat object at 0x7f553f7a3550>]
Logging to ./path/to/my/logs
Logger outputs before training: [<stable_baselines3.common.logger.HumanOutputFormat object at 0x7f553e938d10>, <stable_baselines3.common.logger.TensorBoardOutputFormat object at 0x7f55abd95f90>]
Logger outputs after training: []
```

Instantiating PPO and calling `.learn()` clears the logger configuration. The desired output is instead:

```
Logger outputs at startup: [<stable_baselines3.common.logger.HumanOutputFormat object at 0x7f553f7a3550>]
Logging to ./path/to/my/logs
Logger outputs before training: [<stable_baselines3.common.logger.HumanOutputFormat object at 0x7f553e938d10>, <stable_baselines3.common.logger.TensorBoardOutputFormat object at 0x7f55abd95f90>]
Logger outputs after training: [<stable_baselines3.common.logger.HumanOutputFormat object at 0x7f553e938d10>, <stable_baselines3.common.logger.TensorBoardOutputFormat object at 0x7f55abd95f90>]
```

**System Info**

I ran into this issue using SB3 version 0.8.0a3, installed via pip.

**Comment by araffin** [comment]
Hello,

Yes, I'm aware of that... the main reason was that the logger is mainly meant to be used by the algorithm only, but I understand your concern ;)

>custom logger configuration should be moved out of the .learn() method, or the logger configuration update inside .learn() should be made optional via a keyword argument to 

Maybe having a `self.logger` instead of `logger` as a module?
And allow a `self.set_logger()` or something similar?

**Comment by qxcv** [comment]
Yes, that would work too.
