### ISSUE TITLE
[Bug] Unable to install stable-baselines3: Failed to build AutoROM.accept-rom-license

### ISSUE THREAD

**Issue by Insomnia-y** [DLR-RM/stable-baselines3#1090]
### 🐛 Bug

I am trying to install `rl-baselines3-zoo` manully, when use `pip install stable_baselines3[extra]==1.6.1` it ends up with the error mentioned below.

```
Building wheels for collected packages: AutoROM.accept-rom-license
  Building wheel for AutoROM.accept-rom-license (pyproject.toml) ... done
  ERROR: Failed building wheel for AutoROM.accept-rom-license
Failed to build AutoROM.accept-rom-license
ERROR: Could not build wheels for AutoROM.accept-rom-license, which is required to install pyproject.toml-based projects
```

Environments: Ubuntu 18.04.6 LTS & windows 10 (both OS have the same issue), python 3.7.

Is there any idea to fix it? thanks!

### To Reproduce

```python
pip install stable_baselines3[extra]==1.6.1
```

**Comment by araffin** [comment]
Hello,

> Is there any idea to fix it? thanks!

this is apparently not a SB3 issue but a AutoROM issue, check their repo and that you have all the required dependencies.

Are you using a conda environment?
I assume you don't have the issue if you use Google colab?

Anyway, `stable_baselines3[extra]` is not required to use the RL Zoo, it will just prevents you from using Atari games.

**Comment by Insomnia-y** [comment]
> 

Thanks for your timely reply! I'm going to check it.
