### ISSUE TITLE
[Question] How to use vectorized envs for meta RL methods?

### ISSUE THREAD

**Issue by kbkartik** [DLR-RM/stable-baselines3#1091]
### Question

Meta RL methods require looping through multiple tasks and performing gradient update after learning one step of each task. I was wondering whether vec envs can be used to do the same i.e., each vec env represents a task?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by qgallouedec** [comment]
I am far from being an expert in Meta-RL. Do you mean that each environment contained in a vector environment is a different task? For example, num_env=3 means 3 different tasks?
If so, I would not recommend addressing the problem in this way. In SB3 vec envs, all envs are intended to be identical. I suggest you build your own "MetaEnv" containing your different tasks.
If you have some piece of code for using SB3 for Meta-RL, please share, this may be of interest to some people.
