### ISSUE TITLE
Documentation of output layer

### ISSUE THREAD

**Issue by drasros** [DLR-RM/stable-baselines3#1092]
### 📚 Documentation

Hi! I am using SB3 for the first time. A quick suggestion for the documentation on [using a custom policy network](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html)
On the doc page, the schematic showing the decomposition of the policy into feature_extractor + net_arch seems to suggest that the sub-nets specified by net_arch directly predict action or value. In fact this is not always the case, for example in ActorCriticPolicy the last layer (projection to action space / value space) is in the 'proba_distribution_net'
This is easy to see when looking at the code but maybe it should also be made clear from the doc page ?

**Comment by qgallouedec** [comment]
Thank you for noticing that. I agree, it could be clearer. What do you think would make the documentation clearer?

**Comment by wlxer** [comment]
Thanks for the question, bro. I have noticed that too. In fact I need more complete customization about policy net and value net, but it seems that this is not so easy to implement in the current framework. Hopefully, there will be more open interfaces for customizing the full policy net and value net later in SB3.

**Comment by AlexPasqua** [comment]
I think it would be a good idea to simply put a note in the [custom policy doc](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html) saying that, after the layers specified in `net_arch`, an action and a value net are added.
@qgallouedec I could do that in a PR if you agree

**Comment by qgallouedec** [comment]
Please go ahead @AlexPasqua 🙂

**Comment by AlexPasqua** [comment]
> Please go ahead @AlexPasqua 🙂

Done in #1196 :)
