### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by mo26-web** [DLR-RM/stable-baselines3#1097]
Hi
when I re-compile my code without any changes, I got this error:
ValueError: too many values to unpack (expected 2)

I think new changes in source and core my cause this problem. Please show me proper way to solve this.

**Comment by mo26-web** [comment]
**Here is related code:**

`from typing import Callable, Dict, List, Optional, Tuple, Type, Union

import gym
import torch as th
from torch import nn

from stable_baselines3 import PPO
from stable_baselines3.common.policies import ActorCriticPolicy


class CustomNetwork(nn.Module):
    """
    Custom network for policy and value function.
    It receives as input the features extracted by the feature extractor.

    :param feature_dim: dimension of the features extracted with the features_extractor (e.g. features from a CNN)
    :param last_layer_dim_pi: (int) number of units for the last layer of the policy network
    :param last_layer_dim_vf: (int) number of units for the last layer of the value network
    """

    def __init__(
        self,
        feature_dim: int,
        last_layer_dim_pi: int = 32,
        last_layer_dim_vf: int = 32,
    ):
        super(CustomNetwork, self).__init__()

        # IMPORTANT:
        # Save output dimensions, used to create the distributions
        self.latent_dim_pi = last_layer_dim_pi
        self.latent_dim_vf = last_layer_dim_vf

        # Policy network
        self.policy_net = nn.Sequential(
            nn.Linear(feature_dim, last_layer_dim_pi), nn.ReLU(),nn.Linear(last_layer_dim_pi, last_layer_dim_pi), nn.ReLU(),
            nn.Linear(last_layer_dim_pi, last_layer_dim_pi), nn.ReLU()
        )
        # Value network
        self.value_net = nn.Sequential(
            nn.Linear(feature_dim, last_layer_dim_vf), nn.Linear(last_layer_dim_vf, last_layer_dim_vf), nn.ReLU(),
            nn.Linear(last_layer_dim_vf, last_layer_dim_vf), nn.ReLU()
        )
    def forward(self, features: th.Tensor) -> Tuple[th.Tensor, th.Tensor]:
        """
        :return: (th.Tensor, th.Tensor) latent_policy, latent_value of the specified network.
            If all layers are shared, then ``latent_policy == latent_value``
        """
        return self.policy_net(features), self.value_net(features)

    def forward_actor(self, features: th.Tensor) -> th.Tensor:
        return self.policy_net(features)

    def forward_critic(self, features: th.Tensor) -> th.Tensor:
        return self.value_net(features)


class CustomActorCriticPolicy(ActorCriticPolicy):
    def __init__(
        self,
        observation_space: gym.spaces.Space,
        action_space: gym.spaces.Space,
        lr_schedule: Callable[[float], float],
        net_arch: Optional[List[Union[int, Dict[str, List[int]]]]] = None,
        activation_fn: Type[nn.Module] = nn.Tanh,
        *args,
        **kwargs,
    ):

        super(CustomActorCriticPolicy, self).__init__(
            observation_space,
            action_space,
            lr_schedule,
            net_arch,
            activation_fn,
            # Pass remaining arguments to base class
            *args,
            **kwargs,
        )
        # Disable orthogonal initialization
        self.ortho_init = False

    def _build_mlp_extractor(self) -> None:
        self.mlp_extractor = CustomNetwork(self.features_dim)`

`policy_kwargs = dict(activation_fn=th.nn.ReLU,
                     net_arch=[dict(pi=[32, 32], vf=[32, 32])])
model = PPO2(
    CustomActorCriticPolicy,
    env,
    #policy_kwargs=policy_kwargs,
    learning_rate=0.001,
      # progress decreases from 1 to 0 -> lr decreasesb from 0.0021 to 0
    n_steps=256, 
    batch_size=256, 
    n_epochs=100, 
    gamma=0.001,
    tensorboard_log="log_25",  # define the tensorboard log location    
)`

**the error:**
[https://freeimage.host/i/QquOdv](url)

**Comment by qgallouedec** [comment]
Please help us to help you be filling **entirely** the [issue template](https://raw.githubusercontent.com/DLR-RM/stable-baselines3/master/.github/ISSUE_TEMPLATE/bug_report.md).

Gives extra attention to the use of [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
you are probably using gym 26+, please read the doc to use sb3 with it, otherwise downgrade to gym 0.21.

**Comment by araffin** [comment]
PS: this is your first and last warning, @qgallouedec gently asked you two times to fill the issue template completely, if you do not follow those basic rules, we will close the issue.
