### ISSUE TITLE
[Feature Request] Set gamma and gae_lambda parameters as a function of the progress remaining 

### ISSUE THREAD

**Issue by dmteams** [DLR-RM/stable-baselines3#1100]
### 🚀 Feature

Using PPO implementation offered by SB3, I realized that the learning rate, and clipping range could be set as a function of the current progress remaining (from 1 to 0). I think it may be relevant to allow the parameters gamma and gae_lambda to be function of the time remaining too. 

### Motivation

Why? Setting a low gamma (e.g., 0) in the beginning makes your PPO learn a myopic policy where delayed rewards are not accounted for. This may be relevant in some cases, when the myopic policy is quite good (while not optimal), and is easily learned as a starter, before looking for more complex policies.

Similarly, a low GAE results in biased Advantage Estimator. However, in early phase of learning, this may not really be a problem, while it may results in a lower variance in the learning process. 

In my personal case, I intend to use reward shaping with PPO to fasten early stages of the learning process. However, this requires to have an adaptive gae_lambda.

### Pitch

I would like Stable-Baselines 3 to include a schedule for the parameters gamma and gae_lambda (and potentially others?), just like for the learning rate (and clip_range parameter in the PPO implementation). 

I think it would not be too difficult to implement (I may try to help), and may ease the learning process significantly.

### Additional context

Here is a screenshot from a PhD school in which I participated over the last summer. Credits to Vincent-François Lavet for the insightful presentation. 

![image](https://user-images.githubusercontent.com/75791502/194374416-19b656f1-2af3-45e7-b3de-d639a1ade2a5.png)

This illustration shows the benefits of using an adaptive discount factor (gamma). 

Many thanks in advance for your response (and thank you for all the great work you did with SB3).

Cheers!

**Comment by araffin** [comment]
Hello,
you forgot the "alternatives" section ;)
in your case, I'm pretty sure you can obtain the desired results using callbacks.

Similar to https://github.com/DLR-RM/stable-baselines3/issues/540, https://github.com/DLR-RM/stable-baselines3/issues/316 and https://github.com/DLR-RM/stable-baselines3/issues/628

**Comment by dmteams** [comment]
Thank you very much! I am quite new to the package, sorry for not having considered that option.
