### ISSUE TITLE
[Feature Request] New bug report issue template

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/stable-baselines3#1110]
### 🚀 Feature

A new bug report issue template (form actually)

### Motivation

I'm not a big fan of rigid forms where you can never properly express your problem. However, I notice that a good half of the solicitations just ignore the issue template, wasting everyone's time. So I propose to make the issue template a bit more rigid, by using an issue form instead of the issue template.

### Pitch

This is what it could look like: https://github.com/qgallouedec/fake_repo_for_issue_form/issues/new/choose
(Feel free to submit an issue to see the result)

Resulting issue: https://github.com/qgallouedec/fake_repo_for_issue_form/issues/1

### Alternatives

Keep the current template.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
That's nice =)
I didn't know that github had such feature now.
I'm definitely for it ;) (we need to update the feature request and custom gym env template too)

**Comment by qgallouedec** [comment]
> I didn't know that github had such feature now.

It's beta
