### ISSUE TITLE
[Optimization] Replay Buffers shouldn't use copy when using np.array

### ISSUE THREAD

**Issue by partiallytyped** [DLR-RM/stable-baselines3#112]
Related to #49

In 
https://github.com/DLR-RM/stable-baselines3/blob/23afedb254d06cae97064ca2aaba94b811d5c793/stable_baselines3/common/buffers.py#L198-L208

https://github.com/DLR-RM/stable-baselines3/blob/23afedb254d06cae97064ca2aaba94b811d5c793/stable_baselines3/common/buffers.py#L346-L349

We call `np.ndarray(x).copy()`. This is unnecessary because np.array has the argument "copy" which is True by default. 

https://numpy.org/doc/stable/reference/generated/numpy.array.html

```python
import numpy as np
x = [1,2,3,4,5]
x1 = np.array(x)
x is x1
# False
x2 = np.array(x1)
x2 is x1
# False
```

**Comment by Miffyli** [comment]
Good catch. Mind if I include this in a PR with credits to you (#110)?

**Comment by PartiallyTyped** [comment]
I can make a large one that deals with code optimisation/quirks and leave #110 for algorithm performance, it's up to you :)

**Comment by Miffyli** [comment]
Ok, lets make another PR for optimizations like this 👍 . Lets wait until agent performance has been matched so things do not crisscross to badly.

**Comment by PartiallyTyped** [comment]
I believe that we don't need to copy as the assignment is done on the original data, i.e. where the buffer is located, so 
```
x[indice] = np.array(data)
```
Copies the data twice, once from data to the temporary, and once more from the temporary to the data.

> Unlike some of the references (such as array and mask indices) assignments are always made to the original data in the array (indeed, nothing else would make sense!).

https://numpy.org/doc/stable/user/basics.indexing.html#assigning-values-to-indexed-arrays

**Comment by araffin** [comment]
>I believe that we don't need to copy as the assignment is done on the original data, i.e. where the buffer is located

We need to be extra careful with that one, I remember having weird issues that apparently came from changes by reference (hence the extra conservative copy that is currently in the code).

But if everything is copied, then perfect.

**Comment by PartiallyTyped** [comment]
> But if everything is copied, then perfect.
> 
I played a bit with it in a local implementation and there seemed to be some performance degradation when I removed the second copy so I suggest that we investigate both scenarios when the time comes.

**Comment by jarlva** [comment]
Another (general) optimization suggestion for numpy operations would be using numba or pytorch tensors.

**Comment by araffin** [comment]
>Another (general) optimization suggestion for numpy operations would be using numba or pytorch tensors.

Why would pytorch tensors be faster than numpy?
The replay buffer was originally with pytorch tensors for storage but then it required several transformations from numpy <-> pytorch (e.g. for normalization) whereas the current implementation only do one conversion.

**Comment by PartiallyTyped** [comment]
Using pytorch tensors doesn't necessarily improve performance mainly due to the need to perform the computations @araffin  mentioned, moreover, going cpu->gpu->cpu will probably degrade performance due to latency transfers. The data is usually rather small and fit in the cache so the transfers will probably dominate the runtime.

**Comment by jarlva** [comment]
Pardon, it was a general suggestion, not related specifically to this issue.
