### ISSUE TITLE
Custom Policy Network - Off-Policy Algorithm - Advanced Customization

### ISSUE THREAD

**Issue by Webbah** [DLR-RM/stable-baselines3#1126]
### 📚 Documentation

As stated in the documentation, for using a Custom Policy Network  for off-policy algorithms #425 is linked which shows an example of how to do this.
At the end `register_policy("CustomTD3Policy", CustomTD3Policy)` is used to use the Custom Policy e.g. for TD3/DDPG.
Since it looks like, that in the commit https://github.com/DLR-RM/stable-baselines3/commit/254bb10c42e8f892e43af9da25aefc7c604c317c the `register_policy`-function was deleted/replaced, how can this be handled with the current version of SB3?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

**Comment by qgallouedec** [comment]
Thank you for reporting. We will update the documentation.

Use the following syntax:

```python
from stable_baselines3 import TD3
from stable_baselines3.td3.policies import TD3Policy


class CustomTD3Policy(TD3Policy):
    ...


TD3(CustomTD3Policy, "MountainCarContinuous-v0").learn(5_000)
```

**Comment by Webbah** [comment]
Thank you for the quick answer, works for me!
I would close the issue, which e.g. could be linked in the documentation.

**Comment by qgallouedec** [comment]
Reopening to remember to change the documentation.

**Comment by Webbah** [comment]
Great, thank you!
