### ISSUE TITLE
1D Convolution for SAC

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1129]
### ❓ Question

Hello,

Is there a way to apply 1D convolutional operation for SAC? I am aware that there is the CNN policy class, but I suppose this should be used for 2D images, hence 2D convolution.

Thank you!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
To use a 1D convolutional, you must build a custom policy network. See the [Custom policy section] (https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html) of the doc for instructions on how to do this.

**Comment by qgallouedec** [comment]
Note that this can be applied to any algorithm, not just SAC.

**Comment by anilkurkcu** [comment]
Thank you for the reply.

Do I still need to use the base "CnnPolicy" class and build a 1D convolution on top of that?

**Comment by qgallouedec** [comment]
To be precise, you need to build your own feature extractor which inherits from the `BaseFeatureExtractor` class. 
The example in [this section](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-feature-extractor) is very close to what you want to do.

**Comment by anilkurkcu** [comment]
Great, thanks!

**Comment by anilkurkcu** [comment]
By the way, according to the same approach, can one apply an attention mechanism? Or is this approach just applicable for CNN-based approaches?

**Comment by qgallouedec** [comment]
You should be able to use an attention mechanism with a custom feature extractor. However, note that as input to the extractor, you have the observation at timestep t, and not the whole sequence of observations and actions. Which can be a problem depending of what you want to do.
If you have further question/remarks about the attention mechanism, I suggest you post/answer on #1077. (To keep one topic per issue.)

**Comment by araffin** [comment]
Related to https://github.com/DLR-RM/stable-baselines3/issues/556

You can find 1d conv example if you search on github: https://github.com/StanfordVL/iGibson/blob/783a38ef4962a8757a75c1ece76450163e2c7654/igibson/examples/learning/stable_baselines3_example.py
https://github.com/CRhapsody/2022-cog-cim2real/blob/8e0dcefe54b1b69efcd55d2c79c4cefa2f94850a/nav_model.py

https://github.com/ignc-research/arena-noise-modules/blob/806f8eb8ed5ee466cfd9a67185f3dfefa9fded3f/arena_navigation/arena_local_planner/learning_based/arena_local_planner_drl/scripts/custom_policy.py

https://github.com/mcx-lab/rl-baselines3-zoo/blob/4ed479de13c1f6a4b98b86b3810651b66c4cd20f/blind_walking/net/adapter.py

the search: https://github.com/search?q=stable_baselines3+Conv1d&type=code
