### ISSUE TITLE
[Feature Request] upgrade openai gym dependency

### ISSUE THREAD

**Issue by kalaracey** [DLR-RM/stable-baselines3#1136]
### 🚀 Feature

It appears that stable-baselines3 is using gym==0.21, which is more than a year old by now.

### Motivation

I was using gym.utils.play.play with the noop keyword, but then when I installed stable-baselines3, gym was downgraded and that keyword was no longer available to me.

### Pitch

Upgrade to a new version of gym.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment]
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

Please check harder next time ;)

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/871

**Comment by kalaracey** [comment]
My bad, sorry, I only checked open issues.

**Comment by araffin** [comment]
fair enough, i re-opened the issue now.
