### ISSUE TITLE
Issue with 1D Conv Testing

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1138]
### 🐛 Bug

I am currently working on a custom environment where the observation space is of size (1,68). I am also using a custom 1D convolutional neural network for training. I am performing some evaluations at every 10K time steps. The thing is that when performing these evaluations I am getting this error:

ValueError: Error: Unexpected observation shape (68,) for Box environment, please use (1, 68) or (n_env, 1, 68) for the observation shape.

I had to change the obs that I use for evaluation with obs = th.reshape(th.Tensor(obs), (1,68)). After this, everything seems to be working fine.

Just wanted to share this in case it is a bug or something, or maybe something just to do with my own implementation.

### To Reproduce

```python
from stable_baselines3 import ...

```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
>  I have provided a minimal working example to reproduce the bug


Could you try to provide a minimal working code example? It could be a minimal env that always returns an observation of shape (1,3), and your custom feature extractor. It would be easier for me to help.

**Comment by qgallouedec** [comment]
The error only appears at the time of the evaluation, is that right? Is the training parallelized on more than one environment?

**Comment by anilkurkcu** [comment]
Yes exactly, during evaluation, when I do a CallBack.

As far as I am aware of, no, it is just a single environment.
