### ISSUE TITLE
Difference CNNPolicy DDPG / PPO

### ISSUE THREAD

**Issue by arminvburren** [DLR-RM/stable-baselines3#1139]
### ❓ Question

So I had a working code with a basic environment:
```
class PaintGym(gym.Env):
    def __init__ (self):
        
        self.action_space = gym.spaces.box.Box(low=-np.ones((6,)) * np.inf,
                                               high=np.ones((6,)) * np.inf)
        self.observation_space = gym.spaces.Box(low=0, high=255,
                                                shape=(self.img_height, self.img_width, 4),
                                                dtype=np.uint8)
```

Which basically runs well and trains itself with:
```
model2 = PPO("CnnPolicy", envs, verbose=1)
```
which is using the "NatureCNN" in it.

Then I simply tried to used DDPG as follow, but it crashed.
```
model = DDPG("CnnPolicy", envs, verbose=1, buffer_size=100)
```
After investigation it seem the first values of predict for DDPG are nan:
```
(Pdb++) model2.predict(obs)
(array([-1.4707541 ,  0.39521313,  0.20286873,  0.5180225 , -0.1387833 ,
        1.1277325 ], dtype=float32), None)
(Pdb++) model.predict(obs)
(array([nan, nan, nan, nan, nan, nan], dtype=float32), None)
(Pdb++) 
```
Why is this ? It may be due to the type of the observation space "dtype=np.uint8" but if i change it to float it says ```AssertionError: You should use NatureCNN only with images not with Box```. How can use a basic CNN (in this case the NatureCNN) with DDPG if it crashes when I put the same input than with PPO ?

Also in general what part of the model deals with the input ? Whats the best practice for CNNs ? For example if I use a custom policy as in "https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html" it says to put channels first but in this NatureCNN cas channels are last...

Regards,

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Why is this ? 

It might be an hyperparameter issue, see https://github.com/DLR-RM/stable-baselines3/issues/1130

Have you tried with SAC or TD3? (for TD3, successor of DDPG, you can try with `train_freq=1`)
Did you try with a smaller learning rate?

**Comment by qgallouedec** [comment]
> custom policy as in "https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html" it says to put channels first but in this NatureCNN cas channels are last...

You should follow the documentation. SB3 handles transposition when needed.
What make you think that in NatureCNN, channels are last?
See https://github.com/DLR-RM/stable-baselines3/blob/0532a5719c2bb46fd96b61a7e03dd8cb180c00fc/stable_baselines3/common/torch_layers.py#L75
