### ISSUE TITLE
Unsupported observation space with Gym environments

### ISSUE THREAD

**Issue by corzani** [DLR-RM/stable-baselines3#1140]
### ❓ Question

Hi,
I was trying to use baselines3 with one of the environment of Gym, in this specific case the `Blackjack-v1` one. My answer is related to the object MultiDiscrete comparing to Tuple of Discrete structs.
The code that generates the problem is the following one:

```python
import gym
from stable_baselines3 import PPO

env = gym.make('Blackjack-v1')
model = PPO("MlpPolicy", env, verbose=1)
```

On `Bloackjack-v1` environment observation space is Tuple(Discrete(32), Discrete(11), Discrete(2)) and it's not supported.
The problem comes from `get_obs_shape` function that doesn't match the previous observation space with the following scenarios.

```python
def get_obs_shape(
    observation_space: spaces.Space,
) -> Union[Tuple[int, ...], Dict[str, Tuple[int, ...]]]:

    if isinstance(observation_space, spaces.Box):
        return observation_space.shape
    elif isinstance(observation_space, spaces.Discrete):
        # Observation is an int
        return (1,)
    elif isinstance(observation_space, spaces.MultiDiscrete):
        # Number of discrete features
        return (int(len(observation_space.nvec)),)
    elif isinstance(observation_space, spaces.MultiBinary):
        # Number of binary features
        return (int(observation_space.n),)
    elif isinstance(observation_space, spaces.Dict):
        return {key: get_obs_shape(subspace) for (key, subspace) in observation_space.spaces.items()}

    else:
        raise NotImplementedError(f"{observation_space} observation space is not supported")
```

This is the stacktrace:

```python
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/yak/projects/blackjack/main.py", line 17, in <module>
    model = PPO("MlpPolicy", env, verbose=1)
  File "/Users/yak/.local/share/virtualenvs/blackjack-Jah-5--q/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 167, in __init__
    self._setup_model()
  File "/Users/yak/.local/share/virtualenvs/blackjack-Jah-5--q/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 170, in _setup_model
    super()._setup_model()
  File "/Users/yak/.local/share/virtualenvs/blackjack-Jah-5--q/lib/python3.9/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 114, in _setup_model
    self.rollout_buffer = buffer_cls(
  File "/Users/yak/.local/share/virtualenvs/blackjack-Jah-5--q/lib/python3.9/site-packages/stable_baselines3/common/buffers.py", line 350, in __init__
    super().__init__(buffer_size, observation_space, action_space, device, n_envs=n_envs)
  File "/Users/yak/.local/share/virtualenvs/blackjack-Jah-5--q/lib/python3.9/site-packages/stable_baselines3/common/buffers.py", line 50, in __init__
    self.obs_shape = get_obs_shape(observation_space)
  File "/Users/yak/.local/share/virtualenvs/blackjack-Jah-5--q/lib/python3.9/site-packages/stable_baselines3/common/preprocessing.py", line 158, in get_obs_shape
    raise NotImplementedError(f"{observation_space} observation space is not supported")
NotImplementedError: Tuple(Discrete(32), Discrete(11), Discrete(2)) observation space is not supported
```

Can I consider Tuple of Discrete the same as MultiDiscrete obj?
Should `Tuple(Discrete(32), Discrete(11), Discrete(2))` be considered as `spaces.MultiDiscrete` in the Blackjack environment (Gym side)? 
Should baselines3 support a Tuple of Discrete structs?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Can I consider Tuple of Discrete the same as MultiDiscrete obj?

I would say so, not sure why it was implemented as tuple from the gym side... (`MultiDiscrete` probably didn't exist when it was created).

You could also convert it to a dict of discrete observation, which is also supported by SB3 (using multi input policy).

**Comment by araffin** [comment]
>  Should baselines3 support a Tuple of Discrete structs?

See doc: https://stable-baselines3.readthedocs.io/en/master/guide/algos.html

> Tuple observation spaces are not supported by any environment, however, single-level Dict spaces are

single-level Dict spaces are a super set of tuple spaces.

**Comment by corzani** [comment]
Thank you Anonin for your time. That is exactly what I wanted to know.
