### ISSUE TITLE
[Question] Callback on vectorized environment (multiprocessing) context

### ISSUE THREAD

**Issue by jgwak1** [DLR-RM/stable-baselines3#1144]
### ❓ Question

I'd appreciate it if I could get some help on the following case.

**I am planning on training a single agent with vectorized environments in parallel,
but callback after all the parallel environments have gone through a single step.
In other words,
if the current "_on_step" member-function of BaseCallback class is called after each step of one environment,
is there something like "_on_step_of_all_vectorized_environments" which is called after all vectorized environments have gone through one step?**

**[ More Explanation]**
The specific reason for trying to do this is related to the problem that I am trying to solve.
For further info, I am trying to make RL agent do curriculum-learning. RL environment is associated with a task-difficulty level (member-variable of gym-custom-env) that increments if some conditions are met (agent masters that task level).
For efficiency, I am trying to incorporate multiprocessing using SB3 vectorized-environments. 
However, naively incorporating multiprocessing in this context may result in contradictions with the curriculum-learning component. (i.e., If main idea of curriculum learning is having the agent master each task-difficulty-level from lower to higher, training the agent with multiple environments in parallel can result in situations where the agent is trying to learn task-difficulty level 5 and task-difficulty 10 at the same time. This may not be straightforward).
Thus, I am planning to force the task-difficulty levels of all parallel environments to be consistent, with callback.
To do that, I may need to be able to access the state when not only one but all parallel environments finished one step ( something like "_on_step_of_all_parallel_environments") to check if any one of them increased in task-difficulty.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
hello,

>  if the current "_on_step" member-function of BaseCallback class is called after each step of one environment,

what makes you think it is the case?

According to the documentation:
`This method will be called by the model after each call to env.step().`

but `env` in SB3 is always a `VecEnv`, so it is actually called after all envs have stepped.

**Comment by jgwak1** [comment]
Thanks for your clarification! I was unsure whether the steps were synchronized for vectorized environments.
