### ISSUE TITLE
Custom Policy Network ---Observation dimensions

### ISSUE THREAD

**Issue by shile1998** [DLR-RM/stable-baselines3#1153]
### ❓ Question

`  def forward(self, observations: th.Tensor) -> th.Tensor:

        print(observations.size())

        return self.linear(self.cnn(observations))`

When the program is running, the output is 'torch.Size([1, , ])''for one period of time, and the output is 'torch.Size([128, , ])' for another period of time, and the loop continues. （batch_size is 128）Why is this so？Is it possible to make the observation dimension constant?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
> When the program is running,

> * [x]  If code there is, it is minimal and working

What program? Please provide a minimal and working code.

I think you are confusing the batch size and the observation size. The input tensor in the network have a size `batch_size x obs_size`. During the evaluation, only one observation at a time is passed in the network. Consequently, first dimension is 1.

**Comment by shile1998** [comment]
```
import gym
import torch as th
import torch.nn as nn
import highway_env
from stable_baselines3 import PPO
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
class CustomCNN(BaseFeaturesExtractor):
    """

    :param observation_space: (gym.Space)
    :param features_dim: (int) Number of features extracted.
        This corresponds to the number of unit for the last layer.
    """
    def __init__(self, observation_space: gym.spaces.Box, features_dim: int = 256):
        super(CustomCNN, self).__init__(observation_space, features_dim)
        # We assume CxHxW images (channels first)
        # Re-ordering will be done by pre-preprocessing or wrapper
        n_input_channels = observation_space.shape[0]
        self.cnn = nn.Sequential(
            nn.Linear(5, 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Flatten(),
        )

        # Compute shape by doing one forward pass
        with th.no_grad():
            n_flatten = self.cnn(
                th.as_tensor(observation_space.sample()[None]).float()
            ).shape[1]

        self.linear = nn.Sequential(nn.Linear(n_flatten, features_dim), nn.ReLU())

    def forward(self, observations: th.Tensor) -> th.Tensor:
        print(observations.size())
        return self.linear(self.cnn(observations))
policy_kwargs = dict(
    features_extractor_class=CustomCNN,
    features_extractor_kwargs=dict(features_dim=128),
)
model = PPO("CnnPolicy", "highway-v0", policy_kwargs=policy_kwargs, n_steps=128, batch_size=64, verbose=1)
model.learn(10000)
```

Modify the environment and network in the document example, add 'print (observations. size())' to the forward function, and the result after running is' 1 * obs_ Size ', the number of times is' n _ steps', then the size becomes' 64 * obs_ Size ', i.e. batch_ size*obs_ size. I want to do other things with it, but as shown above, its size changes
![2022-11-03 22-39-44屏幕截图](https://user-images.githubusercontent.com/92363567/199755174-ee44c361-565c-487e-8f9f-cf9c15de7889.png)

**Comment by shile1998** [comment]
> > When the program is running,
> 
> > * [x]   If code there is, it is minimal and working
> 
> What program? Please provide a minimal and working code.
> 
> I think you are confusing the batch size and the observation size. The input tensor in the network have a size `batch_size x obs_size`. During the evaluation, only one observation is used as input of the network. Consequently, first dimension is 1.

**Comment by qgallouedec** [comment]
So that's what I thought. It's not the size of the observation that changes, but the size of the input batch.
It is 64 during training (`batch_size=64`), and 1 during the interaction phase.

**Comment by shile1998** [comment]
But whether it is the training or interaction stage, the data seems to go through the forward function, so before I want to do other more detailed processing, I must judge their size in advance before proceeding to the next step, right?

**Comment by qgallouedec** [comment]
Probably, that's why all torch functions are vectorized, i.e. they work for any batch size, which usually corresponds to the first dimension of the tensor. See for example the [Conv2d documentation](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html?highlight=conv2d#torch.nn.Conv2d)
