### ISSUE TITLE
[Feature Request] Pass all gym Environments in this repo through the env checkers during testing

### ISSUE THREAD

**Issue by tlpss** [DLR-RM/stable-baselines3#1156]
### 🚀 Feature

Both the Gym repo and this repo have an `env_checker` but currently the environments in this repo (most of them are for testing purposes) are not checked against these checkers. This would help catch faulty implementations of changes in the gym API (e.g. the new render API).

I realise this is actually a test on 'test code' but I think it would help maintaining the tests. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by qgallouedec** [comment]
I would tend to agree with you.
Have you tested these environments by the way? Are there any bad surprises?
Your contribution is welcome :)

**Comment by ReHoss** [comment]
Remarks:

- Version of gym used in sb3 is not the latest one.
- sb3 env_checker is more restrictive than the one from gym.

**Comment by araffin** [comment]
> Version of gym used in sb3 is not the latest one.
> This would help catch faulty implementations of changes in the gym API (e.g. the new render API).

I think it would make sense to include that in https://github.com/DLR-RM/stable-baselines3/pull/780
but not before (the gym env checker was derived from SB3 one).

**Comment by qgallouedec** [comment]
> I think it would make sense to include that in https://github.com/DLR-RM/stable-baselines3/pull/780

If you want to contribute, you can therefore create a PR on this branch https://github.com/carlosluis/stable-baselines3/tree/fix_tests.
I've added it to the check list
