### ISSUE TITLE
[Feature Request] Allow to pass `strict=False` when loading model

### ISSUE THREAD

**Issue by araffin** [DLR-RM/stable-baselines3#116]
In SB2, for `load_parameters`, we had a `exact_match` parameter to allow key mismatch when loading.
It would be nice to have that, we have to exclude `optimizers` state dict though.
This feature allows for instance to load models with same architecture but different names (recently there was a rename with #92 that broke previously saved policy, with `strict=False` we can still load the old models that are still valid). 

We also had a `custom_objects` parameter to replace parameters on the fly, not sure if it is still needed... @Miffyli could you comment on that?

**Comment by Miffyli** [comment]
I will include this in the part of reviewing over saving/loading code, currently playing around with A2C/PPO discrete performance. 

I need to check if still need `custom_objects` parameter. I had to use it couple of times in the past to lazily skip loading some only-training-related things that were not required during evaluation.
