### ISSUE TITLE
[Feature Request] Deprecate shared networks

### ISSUE THREAD

**Issue by araffin** [DLR-RM/stable-baselines3#1161]
### 🚀 Feature

See https://github.com/DLR-RM/stable-baselines3/pull/1148
"Looking at the code and thinking for the future, it would probably make sense to always separate the networks after the feature extractor (so deprecate and remove the shared network in the mlp)."

This is more a request for consistency and less flexibility for more readability.
Currently part of the mlp for PPO/A2C can be shared, that results in quite complex code for creating the mlp and not so simple code when creating a custom policy.
As a result, the type of `net_arch` is inconsistent between on-policy algorithms and off-policy algorithms.

In addition to that, for the mlp, by experience, separate networks always perform better, and you don't lose much in performance (wall clock).

### Motivation

That would allow to have a cleaner distinction between actor and critic and have consistent code with the off-policy algorithms.

This should also make creating custom policy more easily.

### Pitch

Deprecate and then remove that feature.

I'm happy to change my mind if the benefit of this feature is backed by experimental evidences.

### Alternatives

Do nothing, keep as is.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by AlexPasqua** [comment]
@araffin I was about to start working on the deprecation of the shared net (in accordance with [this](https://github.com/DLR-RM/stable-baselines3/pull/1148#issuecomment-1359429073)), but should I deprecate this feature only in the `mlp_extractor` part or also in the features extractor?

> In addition to that, for the mlp, by experience, separate networks always perform better, and you don't lose much in performance (wall clock).
>
> I'm happy to change my mind if the benefit of this feature is backed by experimental evidences.

I agree with the fact that usually the performance is better with separate networks, after all there are more trainable parameters. The only possible drawback that I see at the moment is that in many papers I read that the weights are shared between actor and critic for efficiency reasons. Now, even if separate networks don't hinder efficiency, if someone needs to replicate some paper's result, this might introduce a difference with the paper's implementation. It's not a substantial difference, so I'd agree to continue with the deprecation, but still I though about writing this consideration.

**Comment by araffin** [comment]
Hello,
only for the mlp part.
What i wrote is not true for CNN.

**Comment by araffin** [comment]
@AlexPasqua are you already working on the removal (couldn't find the discussion anymore...) or may i create a branch for it?

**Comment by AlexPasqua** [comment]
> @AlexPasqua are you already working on the removal (couldn't find the discussion anymore...) or may i create a branch for it?

I had already started, then I paused it because I had some deadlines. I was planning to re-start working on it this afternoon.
