### ISSUE TITLE
[Question] Custom Environment Image Input Clarification

### ISSUE THREAD

**Issue by ashleychung830** [DLR-RM/stable-baselines3#1162]
### ❓ Question

Hi, I just wanted to clarify the note on using Custom Environments. 

"If you are using images as input, the observation must be of type np.uint8 and be contained in [0, 255] is normalized (dividing by 255 to have values in [0, 1]) when using CNN policies. Images can be either channel-first or channel-last."

Does this mean images should be [0, 255] or [0, 1]? Also, when converting grayscale images to np.uint8, I noticed that my images turn from grayscale into black and white -- not sure if there is a workaround for this.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
It means that images values should be in [0, 255].

> Also, when converting grayscale images to np.uint8, I noticed that my images turn from grayscale into black and white

Can you provide an example?

Maybe you convert to unint8 before mapping to [0, 255]?:

```python
>>> a = np.linspace(0, 1, 11)
>>> a
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
>>> a.astype(np.uint8)*255
array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 255], dtype=uint8)
>>> (a*255).astype(np.uint8)
array([  0,  25,  51,  76, 102, 127, 153, 178, 204, 229, 255], dtype=uint8)
```
