### ISSUE TITLE
[Question] Deterministic action is the most probable action for PPO, but is the mean action for SAC?

### ISSUE THREAD

**Issue by lilin3336298** [DLR-RM/stable-baselines3#1166]
### ❓ Question

I checked the probability distribution of action from SAC and PPO with deterministic=True, but I feel a bit confused. 
It seems that for SAC, the deterministic action takes the mean of the probability distribution, while for PPO, the deterministic action takes the most probable action. Is this true? If so, is there a reason to make such a difference? Especially, I don't understand why SAC takes the mean action? 

see https://github.com/DLR-RM/stable-baselines3/blob/7e1db1aaaa0f486cceb79faf5a08a25c5fded670/stable_baselines3/common/distributions.py#L175

Thank you very much!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> It seems that for SAC, the deterministic action takes the mean of the probability distribution, while for PPO, the deterministic action takes the most probable action

The mean of the distribution is the most probable action for continuous actions.

For PPO with continuous action, we also take the mean:
https://github.com/DLR-RM/stable-baselines3/blob/c4f54fcf047d7bf425fb6b88a3c8ed23fe375f9b/stable_baselines3/common/distributions.py#L174-L175

Distribution to use is defined here:
https://github.com/DLR-RM/stable-baselines3/blob/7e1db1aaaa0f486cceb79faf5a08a25c5fded670/stable_baselines3/common/distributions.py#L660-L668


Note: SAC is using a squashed Gaussian distribution:
https://github.com/DLR-RM/stable-baselines3/blob/7e1db1aaaa0f486cceb79faf5a08a25c5fded670/stable_baselines3/common/distributions.py#L239-L242

But with discrete actions, we use another distribution (Categorical) so we don't take the mean.

**Comment by lilin3336298** [comment]
Thank you, Araffin! I understood.

**Comment by araffin** [comment]
>  I would think the "most probable action" is where the probability density function attains its maximum value. (It is also the definition of the "mode" of a distribution, right?)

> Is there any reason for choosing mean of the distribution as the most probable distribution? (e.g. it gives more stable results?)

most probable action, not most probable distribution, we are talking about Gaussian (aka Normal) distribution here: https://en.wikipedia.org/wiki/Normal_distribution

So the mean is the mode of that distribution.

**Comment by lilin3336298** [comment]
Araffin, thank you for the answer! It is very helpful to me.

This also answers my confusion about sampled action distribution: they do not look gaussian at all (see attached figure). Now I understand: for PPO, the large peaks at -1 and 1 are because of the clipping of actions, and the rest is gaussian. For SAC, the two peaks near the edges are because the tanh squeezes the probability in. 

<img width="871" alt="histogram of action" src="https://user-images.githubusercontent.com/9277720/201263617-117ede8c-f6fc-4b58-9faf-d687cb94d3e3.png">

Here I want to ask a technical question: how do I access the mean and log_std of the action distribution in PPO? I tried the following, but it does not work (the mean_actions and log_std are none):

distribution = model.policy.get_distribution(observation)
mean_actions = distribution.mean_actions
log_std = distribution.log_std

(Note that the observation has been converted to tensor.)

Thanks again!!

**Comment by ReHoss** [comment]
> > It seems that for SAC, the deterministic action takes the mean of the probability distribution, while for PPO, the deterministic action takes the most probable action
> 
> The mean of the distribution is the most probable action for continuous actions.
> 
> For PPO with continuous action, we also take the mean:
> 
> https://github.com/DLR-RM/stable-baselines3/blob/c4f54fcf047d7bf425fb6b88a3c8ed23fe375f9b/stable_baselines3/common/distributions.py#L174-L175
> 
> Distribution to use is defined here:
> 
> https://github.com/DLR-RM/stable-baselines3/blob/7e1db1aaaa0f486cceb79faf5a08a25c5fded670/stable_baselines3/common/distributions.py#L660-L668
> 
> Note: SAC is using a squashed Gaussian distribution:
> 
> https://github.com/DLR-RM/stable-baselines3/blob/7e1db1aaaa0f486cceb79faf5a08a25c5fded670/stable_baselines3/common/distributions.py#L239-L242
> 
> But with discrete actions, we use another distribution (Categorical) so we don't take the mean.



I think, as you precise later, the **mode** of the distribution is the most probable action for continuous actions.


(In fact, atoms all have zero probability for continuous density but set of actions around the point which achieve the maximal value of the continuous density (mode) have the highest probability).

In the special case of Gaussian, the mode is the mean.
