### ISSUE TITLE
[Question] Bad file descriptor 

### ISSUE THREAD

**Issue by Entongsu** [DLR-RM/stable-baselines3#1168]
### ❓ Question

When I trained the PPO recently, I always encountered the problem of a Bad file descriptor. This problem often occurs when I just run 300 to 400 epochs. It seems that I seldom encounter problems in the previous training. The number of workers I used is 10. I wonder whether the I/O limit causes it. Thank you.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Please use the bug template instead of the question template. The information you provide is not sufficient for us to understand what is going on.

**Comment by Entongsu** [comment]
Sorry about that. I have fixed it.
