### ISSUE TITLE
model.learn is outputting observations to the terminal

### ISSUE THREAD

**Issue by Conet1502** [DLR-RM/stable-baselines3#1170]
### ❓ Question

Is there a setting that I am missing when using model.learn()  that would cause it to output observations to the terminal? I have gone through my  model files and all prints are commented out.

model = PPO('MlpPolicy', env, verbose=1, tensorboard_log = logdir)
TIMESTEPS = 10000
for i in range(1,1000):
    model.learn(total_timesteps = TIMESTEPS, reset_num_timesteps=False, tb_log_name="PPO21")
    model.save(f"{models_dir}/{TIMESTEPS*i}")

![terminal](https://user-images.githubusercontent.com/25015389/201386069-02fbeebd-c441-44a5-8298-a50d7f1d93b1.png)
    

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
In order for us to help you, you must make a sufficient effort to ask your question. I therefore invite you to modify your question to fit the template, and to read the title before checking the corresponding check box.  E.g.: 

> * [x]  If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

If you have problems filling in the template, you can let us know.

**Comment by Conet1502** [comment]
how do you stop model.learn() from rendering to the terminal.

**Comment by qgallouedec** [comment]
Closing as template not filled despite the explicit request.
