### ISSUE TITLE
[Feature Request] Expose public modules with __all__

### ISSUE THREAD

**Issue by ZikangXiong** [DLR-RM/stable-baselines3#1171]
### 🚀 Feature

Lots of modules are exposed via the `__init__.py`s  (e.g., PPO, SAC are exposed in the namespace `stable_baselines3`). However, these imported modules are not explicitly exposed in the `__all__`, which makes the static analysis tools like pylance (default language server of vscode) 1) reports false positive, and 2) fail to add respective modules in its auto-complete list. 

![image](https://user-images.githubusercontent.com/73256697/201446008-44235220-3ade-47b1-91e6-5e53b368ffaf.png)  
![image](https://user-images.githubusercontent.com/73256697/201446047-a9a9b101-bb2f-461d-ae18-f78d0070ef79.png)
![image](https://user-images.githubusercontent.com/73256697/201446453-e3e4cbe6-1029-4eb3-94ba-3ada095975fe.png)

Exposing these modules in `__all__` to claim them as public will solve this problem. For example, adding below line to the `__init__.py` of `stable_baselines3` will solve the problem. 
![image](https://user-images.githubusercontent.com/73256697/201446224-eb4dfa80-490d-4aa2-9839-60d837cb6bb2.png)

### Motivation

Improve code quality. 

### Pitch

See feature. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment]
Hello,
i have mixed feelings about that.
I agree it is probably cleaner but according to python doc: "The [import](https://docs.python.org/3/reference/simple_stmts.html#import) statement uses the following convention: if a package’s __init__.py code defines a list named __all__, it is taken to be the list of module names that should be imported when from package import * is encountered. "

in other words: "Python __all__ is a list of public objects of that module, as interpreted by import *. The __all__  overrides the default of hiding everything that begins with an underscore "
https://sisyphus.gitbook.io/project/python-notes/python-__all__

So it should affect only the `from .. import *` behavior, it seems that pylance slightly abuse the initial design of __all__.

**Comment by araffin** [comment]
@ZikangXiong after thinking more about that one, I think I would be happy to receive a PR that adds `__all__` to the `__init__.py` ;)

**Comment by ZikangXiong** [comment]
I am happy to take this easy task. ;-)
