### ISSUE TITLE
[Question] continual learning

### ISSUE THREAD

**Issue by Lunatician** [DLR-RM/stable-baselines3#1172]
### ❓ Question

When I do continual learning like this:
```
  model = SAC.load("sac_test")
  model.set_env(env) 
  model.learn(total_timesteps=500000, log_interval=10)
  model.save("sac_test2")
```
It raise an error: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling 'cublasCreate(handle)'
How would this happen

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
sounds more like a PyTorch/cuda problem (usually OOM issue).

**Comment by Lunatician** [comment]
Yes, I have trained it for env1, but found this problem doing continual learning.

**Comment by qgallouedec** [comment]
Can you provide the needed information to reproduce this error? If necessary, use the bug report template https://github.com/DLR-RM/stable-baselines3/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D%3A+bug+title
