### ISSUE TITLE
How to stop observations from being printed to terminal during learning.

### ISSUE THREAD

**Issue by Conet1502** [DLR-RM/stable-baselines3#1175]
### ❓ Question

How do I stop the observations from being printed/displayed/rendered during training please see attached image?
``import gym 
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
import os

environment_name = "CartPole-v0"
env = gym.make(environment_name)
env.render('None')
env = DummyVecEnv([lambda: env])
model = PPO('MlpPolicy', env, verbose = 1)

model.learn(total_timesteps=5000) #learn 
ppo_path = os.path.join('Cartpole_model')
model.save(ppo_path)
``
![output](https://user-images.githubusercontent.com/25015389/201536816-70a10f83-eba4-45bf-acb7-59716ac4f794.png)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
The code you provide should not display the states. You probably modified gym or stable-baselines3. If you don't know where it came from and you agree to reinstall it, try
```shell
pip install --force-reinstall stable-baselines3
```

**Comment by Conet1502** [comment]
I did neither. Can question be answered by someone else. Reinstalling gym and stable-baselines3 produces the same output.

**Comment by qgallouedec** [comment]
> Can question be answered by someone else.

What is this supposed to mean?
