### ISSUE TITLE
[Question] Extension to hierarchical RL?

### ISSUE THREAD

**Issue by gunnxx** [DLR-RM/stable-baselines3#1176]
### ❓ Question

Hi, I am wondering whether there are any extensions from `stable-baselines3` for hierarchical RL setting?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
you might have a look at https://github.com/AboudyKreidieh/h-baselines (it uses SB2 not SB3).
Otherwise, you can also search on github but I'm not aware of others yet.
