### ISSUE TITLE
module 'gym' has no attribute 'spaces' 

### ISSUE THREAD

**Issue by Natmat626** [DLR-RM/stable-baselines3#1180]
### ❓ Question

Here is my code 

import gym

from stable_baselines3 import DQN
from stable_baselines3.common.vec_env.dummy_vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

env_name = "LunarLander-v2"
env = gym.make(env_name)
env = DummyVecEnv([lambda : env])
model = DQN(
    "MlpPolicy", 
    env=env,
    verbose=1
)

The error message:
\site-packages\stable_baselines3\common\vec_env\util.py:61 in obs_space_info
    if isinstance(obs_space, gym.spaces.Dict):

AttributeError: module 'gym' has no attribute 'spaces'

I really need some help to fix out it,I have no idea does it occur by gym or stable_baselines3 ,please help me！！
Version
Gym:0.21
Stable_baselines:1.6.2

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
I tried but couldn't reproduce the error with the provided code.

```python
import gym

from stable_baselines3 import DQN
from stable_baselines3.common.vec_env.dummy_vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

env_name = "LunarLander-v2"
env = gym.make(env_name)
env = DummyVecEnv([lambda : env])
model = DQN(
"MlpPolicy",
env=env,
verbose=1
)
```

I assume that it also work if you use a Google colab notebook?

I would suggest to double check your python / gym installation (and probably re-create a conda env).

**Comment by qgallouedec** [comment]
Could you run the following lines and tell us if it works?

```python
import gym
gym.spaces.Dict
```

**Comment by Natmat626** [comment]
@araffin @qgallouedec  Thanks bro,its a env problem。I have tried many times to install and uninstall,suddenly it works,but i still didn't know what occur this problem。Thanks all again。
