### ISSUE TITLE
[Question] Asymmetric Actor Critic 

### ISSUE THREAD

**Issue by eastskykang** [DLR-RM/stable-baselines3#1182]
### ❓ Question

For actor-critic algorithms (PPO for an instance), it is pretty common to use different observation spaces and architecture for actor and critic. For instance, one may leverages a simulation state for critic network instead of using image observation when training a visuomotor policy: https://arxiv.org/abs/1710.06542

Such training scheme may requires pretty significant customization on actor / critic networks, as the critic network could be just a simple MLP while the actor network needs a CNN-based feature extractor. 

I wonder if there's more straight-forward way to implement such settings using stable-baselines3 basic features. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> I wonder if there's more straight-forward way to implement such settings using stable-baselines3 basic features.

We don't really support different observations for actor/critic out of the box.
what you could do is use a dictionary observation and use custom policy (we have an example in the doc for custom PPO policy).

This should be easier to do with https://github.com/DLR-RM/stable-baselines3/pull/1148 although probably not straightforward (you will need to have your own SB3 fork).

**Comment by AlexPasqua** [comment]
> what you could do is use a dictionary observation and use custom policy (we have an example in the doc for custom PPO policy).
> 
> This should be easier to do with #1148 although probably not straightforward (you will need to have your own SB3 fork).

Hello @eastskykang, currently #1148 is planning to support non-shared features extractor between actor and critic, but the features extractor is the same type, just without weight sharing. If you need 2 different ones, I think you need to implement your own policy network.

[This code](https://github.com/DLR-RM/stable-baselines3/issues/1066#issuecomment-1246866844) might be useful, I wrote it before #1148 was opened and it is a small demo on how to create your policy network with non-shared features extractor. Still, you probably need to make some modifications to it, but it may help

**Comment by eastskykang** [comment]
@araffin @AlexPasqua Thank you so much for your quick responses! It definitely helps :D
