### ISSUE TITLE
Fine grain control over policy network

### ISSUE THREAD

**Issue by VSZM** [DLR-RM/stable-baselines3#119]
Hi,

Is it possible to control the policy network architecture in detail with Stable Baselines 3? The [documentation](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html) does not state it how to do this. How would I set the kernel size for example? With Stable Baselines 2 one could use the cnn_extractor, but how to do it with Stable Baselines 3?

For example how could one migrate the following architecture to Stable Baselines 3?

```
def modified_cnn(scaled_images, **kwargs):
    activ = tf.nn.relu
    layer_1 = activ(conv(scaled_images, 'c1', n_filters=32, filter_size=3, stride=1, 
                         init_scale=np.sqrt(2), **kwargs))
    layer_2 = activ(conv(layer_1, 'c2', n_filters=64, filter_size=3, stride=1, 
                         init_scale=np.sqrt(2), **kwargs))
    layer_2 = conv_to_fc(layer_2)
    return activ(linear(layer_2, 'fc1', n_hidden=512, init_scale=np.sqrt(2)))  

class CustomCnnPolicy(CnnPolicy):
    def __init__(self, *args, **kwargs):
        super(CustomCnnPolicy, self).__init__(*args, **kwargs, cnn_extractor=modified_cnn)
```

**Comment by Miffyli** [comment]
That's a good question, and should indeed be included in the docs. This part is now called "feature extractor", and you can change the class and parameters [here](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/policies.py#L637-L638).

**Comment by araffin** [comment]
This is now properly [documented](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-feature-extractor) ;) (and we have a migration guide too now)
