### ISSUE TITLE
[Bug]: Different action between model.predict and action_spaces.sample

### ISSUE THREAD

**Issue by thscowns** [DLR-RM/stable-baselines3#1197]
### 🐛 Bug

different action between model.predict and action_spaces.sample

I defined action space of my custom env by gym.spaces.Discrete(3, start=-1) which action is [-1, 0, 1]

I recognize different action between model(PPO).predict and action_spaces.sample

action_spces.sample -> [-1. 0, 1]
model.predict -> [0, 1, 2]

gym version == 0.26.2 

### To Reproduce

~~~
from stable_baselines3 import PPO
import gym

class CustomEnv(gym.Env):

  def __init__(self):
    super().__init__()
    self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(14,))
    self.action_space = gym.spaces.Discrete(3, start=-1)

  def reset(self):
    return self.observation_space.sample()

  def step(self, action):
    obs = self.observation_space.sample()
    reward = 1.0
    done = False
    info = {}

    return obs, reward, done, info

for i in range(10):
    print('action_space sample=', env.action_space.sample())
model = PPO('MlpPolicy', env, verbose=1)
obs = env.reset()
for i in range(10):
    action, _states = model.predict(obs)
    print('model-predict=', action)
    print(env.action_space.contains(action))
    obs, rewards, done, info = env.step(action)
~~~

### System Info

OS: Windows-10-10.0.22000-SP0 10.0.22000
Python: 3.7.13
Stable-Baselines3: 1.6.2
PyTorch: 1.13.0+cpu
GPU Enabled: False
Numpy: 1.21.5
Gym: 0.26.2

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [x] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
SB3 do not support a start index different from zero so this is expected.
You should also use the branch for gym 0.26 (see doc), SB3 master only supports gym 0.21 for now.

Note for myself : we need to update the env checker.

**Comment by thscowns** [comment]
Thanks for replying!
