### ISSUE TITLE
modify Recurrent PPO parameter

### ISSUE THREAD

**Issue by Gengshucheng** [DLR-RM/stable-baselines3#1198]
### ❓ Question

excuse me，I want to know how to define the hyper parameter such as lr、 lstm_layer and hidden_size in the Recurrent PPO？
And can I add LSTM layer in feature_extractor_class amony the linear layer? Any Tutorials about it？

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> excuse me，I want to know how to define the hyper parameter such as lr、 lstm_layer and hidden_size in the Recurrent PPO？

I guess you are looking for `policy_kwargs` argument, you have some examples in the RL Zoo: 
https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo_lstm.yml#L35-L41

>  And can I add LSTM layer in feature_extractor_class amony the linear layer? Any Tutorials about it？

not sure what you mean... but the answer is probably a custom policy and reading the code (PPO LSTM is not trivial though, make sure you really need it as simple frame-stacking is most of the time enough).
