### ISSUE TITLE
[Feature Request] Pass the rank to the vectorized environments

### ISSUE THREAD

**Issue by juhannc** [DLR-RM/stable-baselines3#1207]
### 🚀 Feature

Currently, the vectorized environment are not aware of their rank. The feature request is to add the `rank` to the `env_kwargs` such that this information may be available to the environments.

### Motivation

Sometimes, environments need a unique "id" to work, think of ports to communicate, files to access, etc.
Here, it would be good, if one could uniquely create such a "id" with the help of the rank, think something like:

```python
port = 1000 + rank
```

### Pitch

In [`make_vec_env`](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/env_util.py#L82-L85)

```diff
            if isinstance(env_id, str):
-               env = gym.make(env_id, **env_kwargs)
+               env = gym.make(env_id, **{**env_kwargs, "sb3_rank": rank})
            else:
-               env = env_id(**env_kwargs)
+               env = env_id(**{**env_kwargs, "sb3_rank": rank})
```

Obviously, the key for the rank in the dictionary is debatable. Although a too simple one, like just `"rank"` might collide with existing kwargs. This is also the biggest problem with this feature request. Maybe it would be better to check if the key already exist, whichever name is to be choosen, and only add it if it does not exist in the `env_kwargs`. Simply changing the order to `**{"sb3_rank": rank, **env_kwargs}` would overwrite the `"sb3_rank"`s value with the one given by `env_kwargs`. But then again, this is somewhat undefined behavior, as we do not know, it we successfully passed the rank to the environment.

### Alternatives

Currently, as an alternative, where needed, I randomly choose the "id" (in my case for ports).

### Additional context

The current implementation of `make_vec_env` [does not pass the `rank` to the environment](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/env_util.py#L82-L85).

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by juhannc** [comment]
> What about using the native `id`? Within your env: `id(self)`.

The `id` can be quite a big integer and is non-sequential for the environments.

**Comment by qgallouedec** [comment]
What do you mean by "big"? All Python int have the same size (32 bits).

By "non-sequential" you mean that the ordered ids don't match the ordered sb3 ranks?

**Comment by araffin** [comment]
> > Currently, as an alternative, where needed, I randomly choose the "id" (in my case for ports).

In your case, I think the best and simple alternative is writing a custom `make_vec_env` that is tailored to your needs.


> In [make_vec_env](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/env_util.py#L82-L85)

This will not work for most env as it's not part of gym api (so you would pass an unexpected parameter and it would crash).

**Comment by juhannc** [comment]
> What do you mean by "big"? All Python int have the same size (32 bits).

Well, maybe "big" wasn't the best description, but rather "long".

> By "non-sequential" you mean that the ordered ids don't match the ordered sb3 ranks?

Nope, in my case, the four envs got the ids: 140081067744944, 140081402503808, 140081402544720, 140081402532480.

To maybe explain a little bit better what I need/want to do, is assign a unique IPv4 per env. So with the rank it's as easy as `ip = f"127.0.0.{rank}"`. That's why short and sequential numbers, just like the rank, would be nice as a unique id, for me at least.

**Comment by juhannc** [comment]
> > In [make_vec_env](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/env_util.py?rgh-link-date=2022-12-08T12%3A10%3A47Z#L82-L85)
> 
> This will not work for most env as it's not part of gym api (so you would pass an unexpected parameter and it would crash).

I see, thanks for the explanation :)

Will close the issue then
