### ISSUE TITLE
How to access agent states using custom callbacks

### ISSUE THREAD

**Issue by muk465** [DLR-RM/stable-baselines3#1219]
### ❓ Question

1)I want to view how my agent is behaving so i am using matplotlib for the plotting ,i need states of the agent at each env.step(),
2)how do i get states of the agent in a call back? i have read the documentation there is a variable self.model do i use it to get the agent state? 

### System Info
My environment consists of a 3d numpy array which has obstacles and a target ,my plan is to make my agent which follows a action model to reach the target:

I am using colab
how the library was installed : !pip install stable-baselines3[extra]
Python: 3.7.14
*Stable-Baselines3: 1.6.1
*PyTorch: 1.12.1+cu113
*GPU Enabled: True
*Numpy: 1.21.6
*Gym: 0.21.0
### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Use https://github.com/DLR-RM/stable-baselines3/issues/1160#issuecomment-1305873903 but replace `self.locals["infos"][0]["prob"]` by `self.locals["observations"]`, but should do the trick.

**Comment by muk465** [comment]
Thanks @qgallouedec 1)i have multiple env ,so for example i have 4 env what does self.locals["observations"][0] signify here?
 2)my state vector is 7 dim ,of which first 3 are x,y,z .will self.locals["observations"][0] give me this?
3)if possible kindly point me to the source code of this variable locals["observations"]

**Comment by qgallouedec** [comment]
> i have 4 env what does self.locals["observations"][0] signify here?

I assumed you have a single env. So `[0]` means the first env. 

> 2)my state vector is 7 dim ,of which first 3 are x,y,z .will self.locals["observations"][0] give me this?

I give the full state of the first env.

> 3)if possible kindly point me to the source code of this variable locals["observations"]

`locals` actually contains all the local variables when the callback is called. Look here



https://github.com/DLR-RM/stable-baselines3/blob/0c1bc0b1da9b869104ab49aa3e9c80219c9176b8/stable_baselines3/common/off_policy_algorithm.py#L573

I admit that this is not the most intuitive and clean part of SB3.

> 4)Also you gave example for tensorboard callback ,this will work fine for customcallback?

I just named the callback `TensorboardCallback` but it is actually a custom callback that inherits from `BaseCallback`.

**Comment by muk465** [comment]
@qgallouedec its showing keyerror for observations instead its 'new_obs'

**Comment by muk465** [comment]
thanks for the help
