### ISSUE TITLE
[Question] Is there a way to set a callback when convergence is reached on the reward signal?

### ISSUE THREAD

**Issue by EloyAnguiano** [DLR-RM/stable-baselines3#1222]
### ❓ Question

I am currently developing an agent that tries to optimize a process. Currently, that process uses 1e5 steps to execute correctly, but it can be observed that in many of the cases the agent reaches a point of good performance early and in others later. In order to optimize the computation time I would like to use a callback that can see when an agent is already doing good actions and is not changing its policy too much. Is there an object that can do something similar?

I could see that there is a [StopTrainingOnRewardThreshold](https://stable-baselines.readthedocs.io/en/master/_modules/stable_baselines/common/callbacks.html#StopTrainingOnRewardThreshold) object, but it is quite complicated what will be the reward to reach in each of the cases that it is executed and on top of that it does not have the ability to evaluate if the agent is making aggressive changes in the policy or not.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Maybe you can try to modify a little `StopTrainingOnRewardThreshold` into a new `StopWhenNoMoreProgress` callback that stops training when there is no new best mean reward in the last n evluations.
