### ISSUE TITLE
[Question] Does SB3 support transfer learning for a different environment with different observation and actions spaces?

### ISSUE THREAD

**Issue by rllyryan** [DLR-RM/stable-baselines3#1223]
### ❓ Question

Dear Stable-Baselines3 community,

I am currently trying to find out if SB3 supports transfer learning for a different environment with different observation and actions spaces that the agent was initially trained on.

The reason why I am asking this is because I am working on a project that tries to reduce the need for retraining the agent in the same environment. The issue is that for different scenarios, the observation and action spaces are different from the initial training stage. For context, both the spaces are DISCRETE.

**Does anyone have any resources on this?**

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> I am currently trying to find out if SB3 supports transfer learning for a different environment with different observation and actions spaces that the agent was initially trained on.

so this is not supported out of the box, but `model.policy` is a `nn.Module`, so you could in theory do "model surgery" using the pytorch state dict.

You could also think about doing imitation learning/filling the replay buffer using the pre-trained agent.

> Does anyone have any resources on this?

I don't unfortunately.
