### ISSUE TITLE
[Question] How to make a custom network for action mapping?

### ISSUE THREAD

**Issue by cmoxiv** [DLR-RM/stable-baselines3#1228]
### ❓ Question

Hello, 

Thank you for the great efforts you put in this framework. It really helps a lot. 

I am trying to implement action mapping using parametrised/learnable Tanh like in the paper titled [Refined Continuous Control of DDPG Actors via Parametrised Activation](https://www.mdpi.com/1291942). I did implement this in pytorch on the side but the challenge I am facing with SB3 is that I cannot place action mapping network in the `policy_kwargs`. 

I went through the code and it seems that SB3 uses the `last_pi/vf_dim` to add another linear layer which maps whatever the `latent_pi` produces into the `action_dim`.

My questions are,
1. Is there a specific keyword in the `policy_kwargs` (like `net_arch`) to use a custom network for producing actions?
2. If not, and I implement this through a distribution, is there a way to pass a specific distribution to the policy?

I noticed that there is a squash option (typically `activation_fn=Tanh`) which suggests that I can pass the parameterised Tanh instead, however i faced 2 challenges here
	- the squash option is outside the training loop 
	- the parameterised Tanh needs access to the shared latent observation

My questions are specific to on-policy agents but hints about where to start with off-policy algorithms will save me a lot of time.

Thanks again for the great work.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
I don't know that paper but it seems you would need to re-define the `Actor` class to have the flexibility you need (and redefine `make_actor` then), `policy_kwargs` is meant for simple customization only (number of units per layer).

> If not, and I implement this through a distribution, is there a way to pass a specific distribution to the policy?

if you use DDPG/TD3, they don't use distributions.
if you want to use custom distribution (with PPO/SAC/...), you will need either to re-define the policy or a fork of SB3.

**Comment by cmoxiv** [comment]
Thx for the info. I will probably go with the distribution option.
