### ISSUE TITLE
[Bug]: PPO - n_updates is inaccurate when using target_kl and confusing breaking variable

### ISSUE THREAD

**Issue by Benjamin-Etheredge** [DLR-RM/stable-baselines3#1229]
### 🐛 Bug

In `stable_baselines3/ppo/ppo.py`, passing `target_kl` parameter causes early stopping to occur during the update loop. This is not reflected in the logged `train/n_updates` metric. 
Changing line 278 from `self._n_updates += self.n_epochs` to `self._n_updates += epoch` would fix it.

There also is an extra `continue_training` parameter used with this logic that is not needed. It already breaks in the `self.target_kl` check area of line 262. Removing `continue_training` and its usage shouldn't affect current functionality. But I'm unsure if that is the intended functionality. 

Due to the break statement in the `self.target_kl` check, it is possible to not update due to high `approx_kl_div`. Was the intended break supposed to be after the optimizer step (using `continue_training` ) or before (breaking after checking `target_kl`)? 

### To Reproduce

N/A

### Relevant log output / Error message

```shell
N/A
```

### System Info

N/A

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by Benjamin-Etheredge** [comment]
Due to `epoch` not going to `n_epochs` on the last loop, my suggested change won't work. Something more complicated would be needed.

**Comment by Benjamin-Etheredge** [comment]
During testing, I found that it breaks out of the rollout loop correctly using `continue_training`. I misunderstood the logic. Disregard that part. 

My suggestion of fixing `training/n_updates` metric still stands though.

**Comment by araffin** [comment]
Hello,
thanks for raising the issue.

> My suggestion of fixing training/n_updates metric still stands though.

yes, you are right, I would welcome a PR that fixes it =)

**Comment by adamfrly** [comment]
Hi @araffin,

I have opened a PR that I think fixes this bug #1311.
