### ISSUE TITLE
which noise to use with vectorized environment 

### ISSUE THREAD

**Issue by muk465** [DLR-RM/stable-baselines3#1230]
### ❓ Question

n_actions = env.action_space.shape[-1]
action_noise =  OrnsteinUhlenbeckActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions))
vec_action_noise=VectorizedActionNoise(action_noise,env.num_envs)

env=make_vec_env(NeuroRL4, env_kwargs=dict(label_name=label_name),n_envs=4)

model = DDPG("MlpPolicy", env,train_freq=(10,"step"),action_noise=vec_action_noise, verbose=1)
model.learn(total_timesteps=50)

I have a doubt regarding which noise to use? 
1)when i use simply   OrnsteinUhlenbeckActionNoise with ddpg it trains fine ,but i dont know if its the correct approach as i am using a vectorised env of 4 env.
2)when i use vectorised noise as shown in code above i have to make train_freq to update in some steps i.e its giving error for episodic update.
3)final question is do i use vectorised noise or will normal OU noise work fine with the vectorised env?
System Info
My environment consists of a 3d numpy array which has obstacles and a target ,my plan is to make my agent which follows a action model to reach the target:

I am using colab
how the library was installed : !pip install stable-baselines3[extra]
Python: 3.7.14
*Stable-Baselines3: 1.6.1
*PyTorch: 1.12.1+cu113
*GPU Enabled: True
*Numpy: 1.21.6
*Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

Please don't tick a box if you didn't do what is written...

> which noise to use with vectorized environment

same as usual when using Gaussian noise, SB3 handles it automatically:
https://github.com/DLR-RM/stable-baselines3/blob/e3b24829a57ece38f78436cfea38aaa62d059850/stable_baselines3/common/off_policy_algorithm.py#L548-L550

but for OU noise, best is to pass a vectorized version, there might a be a bug as we don't keep track of the state between rollouts.

> i have to make train_freq to update in some steps i.e its giving error for episodic update.

what is the error?

**Comment by muk465** [comment]
1)error was that vectorised environment episodic learning doesnt work i.e model = DDPG("MlpPolicy", env,train_freq=(10,"step"),action_noise=vec_action_noise, verbose=1) instead of train_freq=(10,step) i give 1,episode

2) my question is if i dont give any noise at all ,it still working fine?is ddpg using some default noise
eg model = DDPG("MlpPolicy", env, verbose=1)

3)from your ans 


> > which noise to use with vectorized environment
> 
> same as usual when using Gaussian noise, SB3 handles it automatically:
> 
> https://github.com/DLR-RM/stable-baselines3/blob/e3b24829a57ece38f78436cfea38aaa62d059850/stable_baselines3/common/off_policy_algorithm.py#L548-L550

i)it seems even if i dont vectorise it does it on its own,but with me doing it myself i have to shift learning to step wise instead of episodic 
ii)since 
model = DDPG("MlpPolicy", env,action_noise= OrnsteinUhlenbeckActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions)), verbose=1)
works fine so should i just go ahead with this as it will any way vectorise the noise?

**Comment by araffin** [comment]
> my question is if i dont give any noise at all ,it still working fine?is ddpg using some default noise

it is not (see doc and code for defaults)

**Comment by muk465** [comment]
thanks for clarification
last question 

model = DDPG("MlpPolicy", env,action_noise= OrnsteinUhlenbeckActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions)), verbose=1)
works fine so should i just go ahead with this as it will any way vectorise the noise?
@araffin

**Comment by muk465** [comment]
assert train_freq.unit == TrainFrequencyUnit.STEP, "You must use only one env when doing episodic training."

AssertionError: You must use only one env when doing episodic training.

This is the exact error if i use noise @araffin

**Comment by muk465** [comment]
> ii)since
> model = DDPG("MlpPolicy", env,action_noise= OrnsteinUhlenbeckActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions)), verbose=1)

I was wrong this also gives the error ,only by using no noise its working fine otherwise i have to change the train_freq to step based

**Comment by muk465** [comment]
@araffin  model = DDPG("MlpPolicy", env,action_noise= OrnsteinUhlenbeckActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions)),train_freq=1,gradient_steps=-1, verbose=1)
 if i do this its working fine ,is it updating every step because in documentation we have to give a tuple for train_freq
