### ISSUE TITLE
[Question] Custom made vectorized environment

### ISSUE THREAD

**Issue by thomashirtz** [DLR-RM/stable-baselines3#1235]
### ❓ Question

I manually did a vectorized environment, in my case I have a `gym.Env` where I can select the number of environments and it will return an array of size `(num_environments, *observation_shape)` for the `observation`, an array of `(num_environments, )` for the `reward` and `done`. 

All is done with linear algebra to make it as efficient as possible, no for loop or anything, currently it takes ~the same time to do one step in one environment and hundreds of environments.

Now I am struggling for doing several things:
* I would like to be able to use it as is (sequentially, not on another process), just telling stable_baselines that instead of one observation, it'll get `num_environments` observations.
* I would like to wrap it to make it only a single environment.
* Potentially, I would like to be able to use it on a subprocess (but this is very not the most important part)

I can't publish the detail, but all the important attributes and methods are like this:

```python
import random
from typing import Optional, Tuple

import numpy as np
from gym import Env
from gym.spaces import Box


class VectorizedEnvironment(Env):
    def __init__(
            self,
            num_environments: int,
            seed: Optional[int],
            **kwargs,
    ):
        self.num_envs = num_environments
        self.action_space = Box(low=0, high=1, shape=(action_shape, ))  # this shape does not include the `num_environments`
        self.observation_space = Box(low=0, high=1, shape=(observation_shape, ))  # this shape does not include the `num_environments`
        self._seed = seed if seed is not None else random.getrandbits(32)
    
    def seed(self, seed=None):
        s = seed if seed is not None else self._seed
        np.random.seed(s)
        
    def _reset(
            self,
            seed: Optional[int] = None,
            options: Optional[dict] = None,
    ) -> np.ndarray:
        # Reset computation
        return state
    
    def reset(
            self,
            seed: Optional[int] = None,
            options: Optional[dict] = None,
    ) -> np.ndarray:
        return self._reset(seed=seed, options=options)

    def _step(self, action: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray, dict]:
        # Step computation
        return next_state, reward, terminated, info

    def step(self, action: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray, dict]:
        return self.step(action=action)


class Environment(VectorizedEnvironment):
    def __init__(
            self,
            seed: Optional[int],
            **kwargs,
    ):
        super(Environment, self).__init__(
            num_environments=1,
            seed=seed,
            **kwargs
        )

    def reset(
            self,
            seed: Optional[int] = None,
            options: Optional[dict] = None,
    ) -> np.ndarray:
        return self._reset(seed=seed, options=options)[0]

    def step(self, action: np.ndarray) -> Tuple[np.ndarray, float, bool, dict]:
        next_state, reward, terminated, info = self._step(action=action)
        return next_state[0], reward[0], terminated[0], info

```

However I am struggling to wrap it so that stable_baselines know what I am doing
(Currently, only the `Environment` is working)

Thank you !!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
if your env is already vectorized, you should derive from `VecEnv` not `gym.Env`.
You can take a look at the wrappers we have for envpool/Isaac gym or directly look at the code for examples:
https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#sb3-with-envpool-or-isaac-gym

See https://github.com/DLR-RM/stable-baselines3/issues/772#issuecomment-1048657002

Code: https://github.com/sail-sg/envpool/blob/main/examples/sb3_examples/ppo.py or https://github.com/DLR-RM/rl-baselines3-zoo/blob/feat/envpool/rl_zoo3/vec_env_wrappers.py

**Comment by thomashirtz** [comment]
I have some questions after looking quite some time in the code

I am confused what is the usage of `VecEnvWrapper` since you take as input a `VecEnv` (the environment that is already vectorized)

For the required methods in `VecEnv`:

Also for the `env_is_wrapped`, should I give a list of one boolean or a list of `num_envrionments` boolean ? Since under the hood, there is actually only one environment that outputs `num_environments` outputs.

Since I am constructing my vectorized environment with numpy array (and all the environment will always start and finish at the same time), I am a little bit confused how I can I manage the `get_attr`, `set_attr` and `env_method` with the indices. And why those are needed. (I only found some usages into the HerReplayBuffer)
I guess I need to do something like `[getattr(self.venv, attr_name) for _ in self._get_indices(indices)]` for those methods.

(Curiosity question: Is it possible to have part of the environment finished but keep the longest environment(s) running, and wait that all the environments are finished to reset everything ? It would be so much simpler if in the future I decide to make variable length environments. I guess it might be possible by keep giving `done`s set to true, but I am not sure it would affect the learning.)

Thank you so much for your feedback

**Comment by araffin** [comment]
> I am confused what is the usage of VecEnvWrapper since you take as input a VecEnv (the environment that is already vectorized)

The main reason for `VecEnvWrapper` is to apply a transformation or log data using the whole batch.
It is also useful when the env is vectorized by default (envpool, isaac gym) and you cannot wrap single env.

> Also for the env_is_wrapped, should I give a list of one boolean or a list of num_envrionments boolean ? 

https://github.com/DLR-RM/stable-baselines3/blob/061841a314c361d342442d693af85f6abd838003/stable_baselines3/common/vec_env/base_vec_env.py#L142-L150

> I am a little bit confused how I can I manage the get_attr, set_attr and env_method with the indices. 

I don't think they are required. They are mainly here when users need to do something custom with single envs inside a VecEnv.

>  Is it possible to have part of the environment finished but keep the longest environment(s) running, and wait that all the environments are finished to reset everything ?

Currently that's not possible, we assume that if one env finishes, we can reset it independently from the others.
