### ISSUE TITLE
How to use Callbacklist ?

### ISSUE THREAD

**Issue by muk465** [DLR-RM/stable-baselines3#1236]
### ❓ Question

```python
class PlotCallback(BaseCallback):
    """
    A custom callback that derives from ``BaseCallback``.

    :param verbose: Verbosity level: 0 for no output, 1 for info messages, 2 for debug messages
    """
    def __init__(self, verbose=0):
        super(PlotCallback, self).__init__(verbose)
        # local and global variables
        # self.locals = None  # type: Dict[str, Any]
        # self.globals = None  # type: Dict[str, Any]
        # The logger object, used to report things in the terminal
        # self.logger = None  # stable_baselines3.common.logger
        # # to have access to the parent object
        # self.parent = None  # type: Optional[BaseCallback]


    def _on_step(self) -> bool:
      #print(self.locals.keys())
      #obs = self.locals["observations"][0]
      obs = self.locals["new_obs"][0]
      #print("observations in callbacks ",obs)
      #self.logger.record("prob", probs)
      x1=obs[0]
      y1=obs[1]
      z1=obs[2]
      
        #print(i,j,k)
      ax.scatter(x1, y1,z1,c='g')
      #fig.canvas.draw_idle()
      #time.sleep(0.01)
      plt.draw()
      plt.pause(0.000001)
      return True

class Plotclear(BaseCallback):
    def __init__(self, verbose=0):
        super(Plotclear, self).__init__(verbose)
        

    def _on_step(self) -> bool:
      plt.gca()

event_callback=EveryNTimesteps(n_steps=30,callback=Plotclear())

callbacks=CallbackList([PlotCallback,event_callback])
model.learn(total_timesteps=100,callback=callbacks)


```

I have 2 custom callbacks 
1)PlotCallback which i need every timestep and 2)Plotclear which i need every n timesteps
2)so i used EveryNTimesteps  function on  plotclear callback.
3)then i use callbacklist on the 2 callbacks .
4)i am getting error 
 **callback.init_callback(self.model)

TypeError: init_callback() missing 1 required positional argument: 'model'**

init_callback() of callbacklist is missing arg model 
5)i followed every step as mentioned in the examples given in the callback section so whats the error?

system info
My environment consists of a 3d numpy array which has obstacles and a target ,my plan is to make my agent which follows a action model to reach the target

how the library was installed : !pip install stable-baselines3
({'OS': 'Linux-5.13.0-41-generic-x86_64-with-glibc2.29 #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022',
  'Python': '3.8.10',
  'Stable-Baselines3': '1.6.2',
  'PyTorch': '1.13.1+cu117',
  'GPU Enabled': 'False',
  'Numpy': '1.21.2',
  'Gym': '0.21.0'},
 'OS: Linux-5.13.0-41-generic-x86_64-with-glibc2.29 46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022\nPython: 3.8.10\nStable-Baselines3: 1.6.2\nPyTorch: 1.13.1+cu117\nGPU Enabled: False\nNumpy: 1.21.2\nGym: 0.21.0\n')

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
you are not instantiating your callback... `PlotCallback()` vs `PlotCallback`...

> If code there is, it is minimal and working

please don't forget the import next time, otherwise I cannot run the code.

**Comment by muk465** [comment]
Thanks it worked
