### ISSUE TITLE
can't able to install stable-baselines3==1.6.2 to 1.5.0 releases

### ISSUE THREAD

**Issue by phijose** [DLR-RM/stable-baselines3#1237]
I tried to install gym, and stable-baslines3. got some installation failures

C:\Users\phijo\Documents\python>pip install stable-baselines3[extra]
Collecting stable-baselines3[extra]
  Using cached stable_baselines3-1.6.2-py3-none-any.whl (170 kB)
Requirement already satisfied: numpy in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from stable-baselines3[extra]) (1.24.0)
Collecting importlib-metadata~=4.13
  Using cached importlib_metadata-4.13.0-py3-none-any.whl (23 kB)
Collecting gym==0.21
  Using cached gym-0.21.0-py3-none-any.whl
Requirement already satisfied: pandas in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from stable-baselines3[extra]) (1.5.2)
Collecting torch>=1.11
  Using cached torch-1.13.1-cp38-cp38-win_amd64.whl (162.6 MB)
Requirement already satisfied: matplotlib in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from stable-baselines3[extra]) (3.6.2)
Requirement already satisfied: cloudpickle in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from stable-baselines3[extra]) (2.2.0)
Requirement already satisfied: pillow in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from stable-baselines3[extra]) (9.3.0)
Collecting psutil
  Using cached psutil-5.9.4-cp36-abi3-win_amd64.whl (252 kB)
Collecting ale-py==0.7.4
  Using cached ale_py-0.7.4-cp38-cp38-win_amd64.whl (904 kB)
Requirement already satisfied: opencv-python in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from stable-baselines3[extra]) (4.6.0.66)
Collecting autorom[accept-rom-license]~=0.4.2
  Using cached AutoROM-0.4.2-py3-none-any.whl (16 kB)
Collecting rich
  Using cached rich-12.6.0-py3-none-any.whl (237 kB)
Collecting tensorboard>=2.9.1
  Using cached tensorboard-2.11.0-py3-none-any.whl (6.0 MB)
Requirement already satisfied: tqdm in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from stable-baselines3[extra]) (4.64.1)
Requirement already satisfied: importlib-resources in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from ale-py==0.7.4->stable-baselines3[extra]) (5.10.1)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Requirement already satisfied: requests in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (2.28.1)
Collecting AutoROM.accept-rom-license
  Using cached AutoROM.accept-rom-license-0.5.0.tar.gz (10 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: zipp>=0.5 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from importlib-metadata~=4.13->stable-baselines3[extra]) (3.11.0)
Requirement already satisfied: wheel>=0.26 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (0.38.4)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting google-auth<3,>=1.6.3
  Using cached google_auth-2.15.0-py2.py3-none-any.whl (177 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting werkzeug>=1.0.1
  Using cached Werkzeug-2.2.2-py3-none-any.whl (232 kB)
Collecting grpcio>=1.24.3
  Using cached grpcio-1.51.1-cp38-cp38-win_amd64.whl (3.7 MB)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (65.6.3)
Requirement already satisfied: absl-py>=0.4 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.3.0)
Collecting markdown>=2.6.8
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Collecting protobuf<4,>=3.9.2
  Using cached protobuf-3.20.3-cp38-cp38-win_amd64.whl (904 kB)
Requirement already satisfied: typing-extensions in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from torch>=1.11->stable-baselines3[extra]) (4.4.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from matplotlib->stable-baselines3[extra]) (4.38.0)
Requirement already satisfied: cycler>=0.10 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from matplotlib->stable-baselines3[extra]) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from matplotlib->stable-baselines3[extra]) (22.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from matplotlib->stable-baselines3[extra]) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from matplotlib->stable-baselines3[extra]) (1.0.6)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from matplotlib->stable-baselines3[extra]) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from matplotlib->stable-baselines3[extra]) (1.4.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from pandas->stable-baselines3[extra]) (2022.7)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting pygments<3.0.0,>=2.6.0
  Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
Requirement already satisfied: colorama in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from tqdm->stable-baselines3[extra]) (0.4.6)
Requirement already satisfied: six>=1.9.0 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->stable-baselines3[extra]) (1.16.0)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (1.26.13)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (2022.12.7)
Collecting MarkupSafe>=2.1.1
  Using cached MarkupSafe-2.1.1-cp38-cp38-win_amd64.whl (17 kB)
Collecting libtorrent
  Using cached libtorrent-2.0.7-cp38-cp38-win_amd64.whl (1.9 MB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Building wheels for collected packages: AutoROM.accept-rom-license
  Building wheel for AutoROM.accept-rom-license (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for AutoROM.accept-rom-license (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      copying AutoROM.py -> build\lib
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      copying build\lib\AutoROM.py -> build\bdist.win-amd64\wheel\.
      running install_egg_info
      running egg_info
      writing AutoROM.accept_rom_license.egg-info\PKG-INFO
      writing dependency_links to AutoROM.accept_rom_license.egg-info\dependency_links.txt
      writing requirements to AutoROM.accept_rom_license.egg-info\requires.txt
      writing top-level names to AutoROM.accept_rom_license.egg-info\top_level.txt
      reading manifest file 'AutoROM.accept_rom_license.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file 'AutoROM.accept_rom_license.egg-info\SOURCES.txt'
      Copying AutoROM.accept_rom_license.egg-info to build\bdist.win-amd64\wheel\.\AutoROM.accept_rom_license-0.5.0-py3.8.egg-info
      running install_scripts
      C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\config\setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      Traceback (most recent call last):
        File "c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\phijo\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 360, in run
          self.run_command("install")
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\dist.py", line 1208, in run_command
          super().run_command(command)
        File "C:\Users\phijo\AppData\Local\Temp\pip-build-env-k1xliyno\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 11, in run
        File "C:\Users\phijo\AppData\Local\Temp\pip-install-3nth8akh\autorom-accept-rom-license_edcb31dbf1714dcd91f13669d2599f68\AutoROM.py", line 13, in <module>
          import libtorrent as lt
      ImportError: DLL load failed while importing libtorrent: The specified module could not be found.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for AutoROM.accept-rom-license
Failed to build AutoROM.accept-rom-license
ERROR: Could not build wheels for AutoROM.accept-rom-license, which is required to install pyproject.toml-based projects

**Comment by qgallouedec** [comment]
Please fill the issue template.

**Comment by Karlheinzniebuhr** [comment]
same issue on win10 python 3.9

```
pip install stable-baselines3[extra]
Requirement already satisfied: stable-baselines3[extra] in c:\programdata\mambaforge\lib\site-packages (1.7.0)
Requirement already satisfied: matplotlib in c:\users\karl\appdata\roaming\python\python39\site-packages (from stable-baselines3[extra]) (3.4.2)
Requirement already satisfied: cloudpickle in c:\users\karl\appdata\roaming\python\python39\site-packages (from stable-baselines3[extra]) (1.6.0)
Collecting importlib-metadata~=4.13
  Using cached importlib_metadata-4.13.0-py3-none-any.whl (23 kB)
Requirement already satisfied: torch>=1.11 in c:\programdata\mambaforge\lib\site-packages (from stable-baselines3[extra]) (1.13.1)
Collecting gym==0.21
  Using cached gym-0.21.0-py3-none-any.whl
Requirement already satisfied: numpy in c:\programdata\mambaforge\lib\site-packages (from stable-baselines3[extra]) (1.23.5)
Requirement already satisfied: pandas in c:\programdata\mambaforge\lib\site-packages (from stable-baselines3[extra]) (1.5.3)
Collecting autorom[accept-rom-license]~=0.4.2
  Using cached AutoROM-0.4.2-py3-none-any.whl (16 kB)
Requirement already satisfied: pillow in c:\users\karl\appdata\roaming\python\python39\site-packages (from stable-baselines3[extra]) (8.3.1)
Collecting opencv-python
  Using cached opencv_python-4.7.0.68-cp37-abi3-win_amd64.whl (38.2 MB)
Collecting rich
  Using cached rich-13.3.1-py3-none-any.whl (239 kB)
Requirement already satisfied: psutil in c:\users\karl\appdata\roaming\python\python39\site-packages (from stable-baselines3[extra]) (5.8.0)
Requirement already satisfied: tensorboard>=2.9.1 in c:\programdata\mambaforge\lib\site-packages (from stable-baselines3[extra]) (2.11.2)
Collecting ale-py==0.7.4
  Using cached ale_py-0.7.4-cp39-cp39-win_amd64.whl (904 kB)
Requirement already satisfied: tqdm in c:\users\karl\appdata\roaming\python\python39\site-packages (from stable-baselines3[extra]) (4.61.2)
Requirement already satisfied: importlib-resources in c:\programdata\mambaforge\lib\site-packages (from ale-py==0.7.4->stable-baselines3[extra]) (5.10.2)
Requirement already satisfied: click in c:\users\karl\appdata\roaming\python\python39\site-packages (from autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (7.1.2)
Requirement already satisfied: requests in c:\programdata\mambaforge\lib\site-packages (from autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (2.28.2)
Collecting AutoROM.accept-rom-license
  Using cached AutoROM.accept-rom-license-0.5.4.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: zipp>=0.5 in c:\users\karl\appdata\roaming\python\python39\site-packages (from importlib-metadata~=4.13->stable-baselines3[extra]) (3.5.0)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\karl\appdata\roaming\python\python39\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.0.1)
Requirement already satisfied: protobuf in c:\users\karl\appdata\roaming\python\python39\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (3.17.3)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\karl\appdata\roaming\python\python39\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.32.1)
Requirement already satisfied: markdown>=2.6.8 in c:\programdata\mambaforge\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\programdata\mambaforge\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (0.6.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\karl\appdata\roaming\python\python39\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (0.4.6)
Requirement already satisfied: setuptools>=41.0.0 in c:\programdata\mambaforge\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (66.1.1)
Requirement already satisfied: absl-py>=0.4 in c:\programdata\mambaforge\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.4.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\programdata\mambaforge\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.8.1)
Requirement already satisfied: grpcio>=1.24.3 in c:\programdata\mambaforge\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (1.51.1)
Requirement already satisfied: wheel>=0.26 in c:\programdata\mambaforge\lib\site-packages (from tensorboard>=2.9.1->stable-baselines3[extra]) (0.38.4)
Requirement already satisfied: typing_extensions in c:\programdata\mambaforge\lib\site-packages (from torch>=1.11->stable-baselines3[extra]) (4.4.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\mambaforge\lib\site-packages (from matplotlib->stable-baselines3[extra]) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\karl\appdata\roaming\python\python39\site-packages (from matplotlib->stable-baselines3[extra]) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\karl\appdata\roaming\python\python39\site-packages (from matplotlib->stable-baselines3[extra]) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\karl\appdata\roaming\python\python39\site-packages (from matplotlib->stable-baselines3[extra]) (2.4.7)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\mambaforge\lib\site-packages (from pandas->stable-baselines3[extra]) (2022.7.1)
Collecting markdown-it-py<3.0.0,>=2.1.0
  Using cached markdown_it_py-2.1.0-py3-none-any.whl (84 kB)
Collecting pygments<3.0.0,>=2.14.0
  Using cached Pygments-2.14.0-py3-none-any.whl (1.1 MB)
Requirement already satisfied: colorama in c:\users\karl\appdata\roaming\python\python39\site-packages (from tqdm->stable-baselines3[extra]) (0.4.4)
Requirement already satisfied: six in c:\programdata\mambaforge\lib\site-packages (from cycler>=0.10->matplotlib->stable-baselines3[extra]) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\karl\appdata\roaming\python\python39\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->stable-baselines3[extra]) (4.7.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\karl\appdata\roaming\python\python39\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->stable-baselines3[extra]) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\karl\appdata\roaming\python\python39\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->stable-baselines3[extra]) (4.2.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\karl\appdata\roaming\python\python39\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.9.1->stable-baselines3[extra]) (1.3.0)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\karl\appdata\roaming\python\python39\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\karl\appdata\roaming\python\python39\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (2020.6.20)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\mambaforge\lib\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\karl\appdata\roaming\python\python39\site-packages (from requests->autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (2.0.11)
Requirement already satisfied: libtorrent in c:\programdata\mambaforge\lib\site-packages (from AutoROM.accept-rom-license->autorom[accept-rom-license]~=0.4.2->stable-baselines3[extra]) (2.0.7)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\karl\appdata\roaming\python\python39\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.9.1->stable-baselines3[extra]) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\karl\appdata\roaming\python\python39\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.9.1->stable-baselines3[extra]) (3.1.1)
Building wheels for collected packages: AutoROM.accept-rom-license
  Building wheel for AutoROM.accept-rom-license (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for AutoROM.accept-rom-license (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\config\setupcfg.py:520: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      copying AutoROM.py -> build\lib
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      copying build\lib\AutoROM.py -> build\bdist.win-amd64\wheel\.
      running install_egg_info
      running egg_info
      writing AutoROM.accept_rom_license.egg-info\PKG-INFO
      writing dependency_links to AutoROM.accept_rom_license.egg-info\dependency_links.txt
      writing requirements to AutoROM.accept_rom_license.egg-info\requires.txt
      writing top-level names to AutoROM.accept_rom_license.egg-info\top_level.txt
      reading manifest file 'AutoROM.accept_rom_license.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file 'AutoROM.accept_rom_license.egg-info\SOURCES.txt'
      Copying AutoROM.accept_rom_license.egg-info to build\bdist.win-amd64\wheel\.\AutoROM.accept_rom_license-0.5.4-py3.9.egg-info
      running install_scripts
      Traceback (most recent call last):
        File "C:\Users\Karl\AppData\Local\Temp\pip-install-ncrvcrw5\autorom-accept-rom-license_1ee4d0a378b048008f8d26e44147590b\AutoROM.py", line 15, in <module>
          import libtorrent as lt
      ImportError: DLL load failed while importing libtorrent: The specified module could not be found.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "C:\Users\Karl\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\Karl\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Karl\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\dist.py", line 1213, in run_command
          super().run_command(command)
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 360, in run
          self.run_command("install")
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\dist.py", line 1213, in run_command
          super().run_command(command)
        File "C:\Users\Karl\AppData\Local\Temp\pip-build-env-_k4b32jd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 11, in run
        File "C:\Users\Karl\AppData\Local\Temp\pip-install-ncrvcrw5\autorom-accept-rom-license_1ee4d0a378b048008f8d26e44147590b\AutoROM.py", line 17, in <module>
          raise ImportError("It seems that you are trying to install the Atari ROMs on Windows. While this is not supported, the DLL error can be solved by installing the OpenSSL DLLs from: https://slproweb.com/products/Win32OpenSSL.html") from e
      ImportError: It seems that you are trying to install the Atari ROMs on Windows. While this is not supported, the DLL error can be solved by installing the OpenSSL DLLs from: https://slproweb.com/products/Win32OpenSSL.html
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for AutoROM.accept-rom-license
Failed to build AutoROM.accept-rom-license
ERROR: Could not build wheels for AutoROM.accept-rom-license, which is required to install pyproject.toml-based projects
```

**Comment by qgallouedec** [comment]
Have you tried to install the OpenSSL DLLs?
