### ISSUE TITLE
How to acess environment variables in a call back?

### ISSUE THREAD

**Issue by muk465** [DLR-RM/stable-baselines3#1239]
### ❓ Question

```
import gym
from stable_baselines3.common.callbacks import BaseCallback

class NeuroRL4(gym.Env):
  metadata={ 'render.modes':['human','rgb_array'], 'video.frames_per_second':50 }
  def __init__(self,label_name):
    self.img_folder="/home/inspire_lab/Desktop/rl_new2/final_label_img3"
    self.img_path=os.path.join(self.img_folder,label_name)
    self.img_arr=nib.load(self.img_path).get_fdata()

class PlotCallback(BaseCallback):
    """
    A custom callback that derives from ``BaseCallback``.

    :param verbose: Verbosity level: 0 for no output, 1 for info messages, 2 for debug messages
    """
    def __init__(self, verbose=0):
        super(PlotCallback, self).__init__(verbose)
        


    def _on_step(self) -> bool:
      #print(self.locals.keys())
      #obs = self.locals["observations"][0]
      obs = self.locals["new_obs"][0]
      #print("observations in callbacks ",obs)  
      
      model=self.model
      env=model.env
      img_arr=env.img_arr

env=NeuroRL4(label_name=label_name)
n_actions = env.action_space.shape[-1]
action_noise =  OrnsteinUhlenbeckActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions))
model = DDPG('MlpPolicy',env,action_noise=action_noise, verbose=1)
model.learn(total_timesteps=1,callback=PlotCallback())
    

```
1)This is a sample of my env ,i have not added step etc. here only the variables inside the constructor of the env
2)I want to access the env variable img_arr but its showing error ** 'DummyVecEnv' object has no attribute 'img_arr'**
3)I have also used 
```
env=self.locals["env"]
 img_arr=env.img_arr
```
but i am still getting the same error
4)**question is how to access the env variables inside  a callback?**

({'OS': 'Linux-5.13.0-41-generic-x86_64-with-glibc2.29 #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022',
  'Python': '3.8.10',
  'Stable-Baselines3': '1.6.2',
  'PyTorch': '1.13.1+cu117',
  'GPU Enabled': 'False',
  'Numpy': '1.21.2',
  'Gym': '0.21.0'},
 'OS: Linux-5.13.0-41-generic-x86_64-with-glibc2.29 46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022\nPython: 3.8.10\nStable-Baselines3: 1.6.2\nPyTorch: 1.13.1+cu117\nGPU Enabled: False\nNumpy: 1.21.2\nGym: 0.21.0\n')
### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
It is because `env` is vectorized (several envs in one). Here is an ugly but working solution:

```python
env = self.locals["env"].envs[0]
```

where `0` is the env index.

**Comment by araffin** [comment]
`vec_env.get_attr` is a more général solution ;) (cf doc)

**Comment by muk465** [comment]
But why is env getting vectorised here? i am only using one env here 
`env=NeuroRL4(label_name=label_name)`

**Comment by qgallouedec** [comment]
Because the model vectorize the environment if necessary (this is the case here).

**Comment by araffin** [comment]
> But why is env getting vectorised here? i am only using one env here `env=NeuroRL4(label_name=label_name)`

internally, for consistency and simplicity, SB3 always use a VecEnv, even when working with a single env (also in the doc, see "dev guide").

**Comment by muk465** [comment]
Thanks for the clarification
