### ISSUE TITLE
[Question] A Qusetion about "Custom Network Architecture"

### ISSUE THREAD

**Issue by Natmat626** [DLR-RM/stable-baselines3#1241]
### ❓ Question

There is a passage on the official website，
“In the following example, as CartPole’s action space has a dimension of 2, the final dimensions of the net_arch’s layers will be:”
net_arch's layers dimension is set to 2。
I want to figure out the relationship between the action space dimension and the net_arch layers dimension. I can't find more descriptions about the relationship between the them on the official website.
if 'A' is the dimension of the action space，‘B’ is the dimension of the net_arch's layers ,
B>=A  ?
I am new to RL and hope someone can answer my question，Thanks！

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Section of the documentation mentioned: https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html

The network architecture depends on what you specify in `net_arch` parameter. The size of the first layer is the observation size. The size of the actor's last layer is the size of the action space. In the doc's example, observation size is 4, `net_arch` is `[dict(pi=[32, 32], vf=[32, 32])]`, and action size is 2. Thus, the full net structure is:

```
        obs
        <4>
   /            \
 <32>          <32>
  |              |
 <32>          <32>
  |              |
 <2>            <1>
action         value
```

**Comment by Natmat626** [comment]
@qgallouedec  So the action space dimension and net_arch layer dimension,
There is no direct relationship between them, right?

**Comment by qgallouedec** [comment]
To be schematic, the final network follows the following stack:

- observation size
- net_arch
- action size, value size (always 1)
