### ISSUE TITLE
[Question] How do we decide the number of environments for vectorisation?

### ISSUE THREAD

**Issue by rllyryan** [DLR-RM/stable-baselines3#1243]
### ❓ Question

For the vectorisation wrappers:

1. VecEnv
2. DummyVecEnv
3. SubrocVecEnv

What is the maximum number of num_envs that we can set? I have seen somewhere that it refers to the number of cores that the CPU has, but what about the GPU? Can we use the cores in the GPU?

The documentation (SB3) needs to be updated with these pieces of information.

Thank you.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> How do we decide the number of environments for vectorisation?

did you take a look at the notebook about multiprocessing from our tutorial: https://github.com/araffin/rl-tutorial-jnrr19/tree/sb3
Colab: https://colab.research.google.com/github/araffin/rl-tutorial-jnrr19/blob/sb3/3_multiprocessing.ipynb

> What is the maximum number of num_envs that we can set? I
>  have seen somewhere that it refers to the number of cores that the CPU has, but what about the GPU? 

there is no upper limit, but if you read the tutorial you will see there is a compromise, but yes it usually doesn't make sense to use more envs that CPU cores when using multiprocessing (you can but it will just run slower if all cores are at 100%).

> Can we use the cores in the GPU?

GPU usage is not related to the env, unless you are using env that are made for it (we have an issue about that in this repo).
