### ISSUE TITLE
How to get values of enivronment variables when an episode is done and before these variables reset.

### ISSUE THREAD

**Issue by muk465** [DLR-RM/stable-baselines3#1248]
### ❓ Question

1)I am using ddpg for training my environment

```python
from stable_baselines3.common.noise import NormalActionNoise
from stable_baselines3.common.callbacks import BaseCallback
import gym
import os
import numpy as np
import nibabel as nib

class NeuroRL5(gym.Env):
  metadata={ 'render.modes':['human','rgb_array'], 'video.frames_per_second':50 }
  def __init__(self,label_name):
    self.img_folder="/home/inspire_lab/Desktop/rl_new2/final_label_img3"
    self.img_path=os.path.join(self.img_folder,label_name)
    self.img_arr=nib.load(self.img_path).get_fdata()
    self.label_name=label_name
    
    self.action_arr=[]

 def step(self,action):
    #un normalise the action
    u2=math.pi*(action[0]+1)
    print("action",u2)
    #save the action
    self.action_arr.append(u2)
def reset(self):
    
    self.action_arr=[]

class EpisodeCallback(BaseCallback):
    def __init__(self, verbose=0):
        super(EpisodeCallback, self).__init__(verbose)

    def _on_step(self) -> bool:
      env=self.locals["env"].envs[0]
      df2=env.df2
      done=self.locals["dones"][0]
      
      filepath='/home/inspire_lab/Desktop/python/rl/csv_save'
      if done==True:
          df2 = df2.append({'action':env.action_arr})
      return True

   env=NeuroRL5(label_name=label_name)
   n_actions = env.action_space.shape[-1]
  action_noise =  OrnsteinUhlenbeckActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions))
  if is_empty_model(model_dir):
      model = DDPG('MlpPolicy',env,action_noise=action_noise, verbose=1)
  else:
      load_model=os.listdir(model_dir)[0]
      model_path=os.path.join(model_dir,load_model)
      model.set_parameters(model_path)

  #create_plot(label_name)
  model.learn(total_timesteps=100000,callback=[CsvCallback(),EpisodeCallback()])
  model.save(save_path)
```

2)The code is extremely minimal ,what i am trying to ask is 
 i)i have a variable in env action_arr which stores the actions at each step
 ii)and when a reset is called this action array is reset to an empty list
iii)I am using a callback which callsback when done==True and store these values in a csv file
iv)But its giving empty array.
v)**My question is how to resolve this? (as  done is called when trajectory hits goal ,so i want to store these actions)**

how the library was installed : !pip install stable-baselines3
({'OS': 'Linux-5.13.0-41-generic-x86_64-with-glibc2.29 46 20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022',
  'Python': '3.8.10',
  'Stable-Baselines3': '1.6.2',
  'PyTorch': '1.13.1+cu117',
  'GPU Enabled': 'False',
  'Numpy': '1.21.2',
  'Gym': '0.21.0'},
 'OS: Linux-5.13.0-41-generic-x86_64-with-glibc2.29 46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022\nPython: 3.8.10\nStable-Baselines3: 1.6.2\nPyTorch: 1.13.1+cu117\nGPU Enabled: False\nNumpy: 1.21.2\nGym: 0.21.0\n')

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> But its giving empty array.

that's normal, SB3 use VecEnv internally and they are automatically reset.

>  am using a callback which callsback when done==True and store these values in a csv file

you should be using a Wrapper (gym wrapper or `VecEnvWrapper`) for that, not a callback (we have notebooks about that in our tutorial https://github.com/araffin/rl-tutorial-jnrr19).
You could even use the `Monitor` wrapper if you pass that list in the `info` dictionary.

> I am using ddpg for training my environment

You should also use TD3 (improved version of DDPG) or SAC.
