### ISSUE TITLE
[Question] How to reset to a specific state when using Vectorized environment

### ISSUE THREAD

**Issue by MagiFeeney** [DLR-RM/stable-baselines3#1249]
### ❓ Question

I need some help to set a specific state to the environment rather than call env.reset() to get a random initial state. It would be better that the state I want to start can be passed into the function. And I am also worrying whether nested wrappings of environment will make it more difficult? (e.g. VecNormalize)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
did you take a look at `env_method` VecEnv method in the doc? (I just wrote some additional doc, should be up soon: https://github.com/DLR-RM/stable-baselines3/pull/780/commits/ff609adfc0a8b2a7eb7620945440a0b9baa449a0)

**Comment by MagiFeeney** [comment]
Hello,
I've checked it. I have one more question: what "attribute_name" should correspond to the state information?

**Comment by araffin** [comment]
> what "attribute_name" should correspond to the state information?

I'm not sure exactly what you want to do, but if you want to use a specific state at the next reset you can do `vec_env.env_method("set_reset_state", the_state_you_want_to_reset_to)` and inside your `reset()` method you would have something like:

```python
...
def set_reset_state(self, state):
    self.start_state = state

def reset(self):
    if self.start_state is not None:
        return self.start_state
    return self.observation_space.sample()
```

**Comment by MagiFeeney** [comment]
Basically I want to approximate the true action value function of some specific states using monte-carlo approximation, which means that we must rollout multiple trajectories from the given state repeatedly. I am not sure whether your solution modifies the simulator's state info, or just returns a passed-into state but not corresponds to the true state that the agent would be. My attempt would be as follows,


```python
# suppose we just have one environment, so just consider index 0
for i_episode in range(num_episodes):
    envs.get_attr('sim')[0].set_state(sim_state) # sim state is the simulator's state, extracted beforehand
    envs.get_attr('sim')[0].forward()
    done = False
    ep_rew = 0

    # Then we can start from the given state, since we also extracted the action paired with the state
    # We don't have to worry the effect of observation normalization on that state
    # Then just follow on the trajectory from that state to the next state (which should be normalized)

    for step in range(MaxTimeLimit):
	if step > 0:
	    with torch.no_grad():
		action, log_prob, _ = self.actor_critic.act(state)
	else:
	    action = start_action # start action is what we paired with the initial state

	# state, reward and next state
	next_state, reward, done, infos = envs.step(action)
	ep_rew = self.gamma * ep_rew + reward
	if done:
	    break
	state = next_state
```

**Comment by MagiFeeney** [comment]
It works well. I think I should close this issue.
