### ISSUE TITLE
[Feature Request] Adding possibility to use other metric tracking tools

### ISSUE THREAD

**Issue by tmynn** [DLR-RM/stable-baselines3#1253]
### 🚀 Feature

Currently the codebase supports tensorboard logger only. Will be nicer to make the core a bit more abstract and give the possibility to the users to extend from an abstract Logger to track the params using other tools such as Aim, Wandb, MlFlow etc.
I will love to work on this.

### Motivation

Tensorboard is very limited with its capabilities and tracking a big number of experiments can be painful. 

### Pitch

Create an abstraction of Logger class. Extend this class to create the current tensorboard logger. Also add other tools in the future.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by qgallouedec** [comment]
I guess you missed that https://stable-baselines3.readthedocs.io/en/master/guide/integrations.html 😉

**Comment by tmynn** [comment]
Hi, @qgallouedec thanks a lot for the quick response.
Can you track metrics such as "entropy_loss" "value_loss" etc with this integration? As it is done in say PPO's train method?
As far as I can see the wandb integration simply stores some hyperparameters and model checkpoints, but it is not tracking metrics.

**Comment by qgallouedec** [comment]
Yes, wandb integration keeps track of almost everything. See https://wandb.ai/openrlbenchmark/sb3/runs/1sfd7i76 as an example.

**Comment by tmynn** [comment]
Nice, sorry then for bothering. :)
