### ISSUE TITLE
Add Examples Combining Useful Tools For Typical Research Workflows

### ISSUE THREAD

**Issue by Bonifatius94** [DLR-RM/stable-baselines3#1254]
### 📚 Documentation

I've recognized that your RL framework offers lots of nice tools. Nothing is really missing. But the thing is, you're not particularly good at giving a newcomer-friendly quickstart. Even for me with a few years of experience in RL and DL, I had to search several hours to find out that you have all kinds of useful callbacks to back up the model, plot TensorBoard graphs, etc.

You've got all those great tools built into SB3, but people don't know because you don't show them how to combine them in a meaningful way. So IMO, you need some kind of sufficiently full-blown example that people can copy, change some lines and then they're good (not like those examples in your [docs](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html) that outline specific features in isolation). For me, such an example should include a training progress display, model checkpoints, useful evaluation metrics, a live metrics display, proper setup of algorithms concerning hparams / scalability, etc.

Let's think about how a researcher would actually use your RL framework. As a researcher you'd probably get really nervous when you don't see any progress especially when the training takes several days, so put a progress bar. Also, it's really important to see whether the training is going as expected, so put a live metrics display allowing for early abortion of failed experiments. And even if you see the reward graph, it's still an issue when you have to admit "the results were great at timestep x but dropped to a result that's worse than random towards the end, so the trained model is basically crap." Of course you want model checkpoints of some kind to minimize the risk of wasted training efforts. Finally when it comes to evaluating the research outcome, maybe you don't want to say "damn the training went really well, but I don't know how I got there". So sure enough you'll need to record all kinds of metrics/logs/configs per experiment to track down which setup mapped to which outcome.

The outlined example is nothing too special, just basic stuff to support the everyday work of a researcher. Maybe you should expand your thinking to facilitate a better research experience where people can concentrate on the actual research.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

**Comment by araffin** [comment]
Hello,
what you are describing sounds like the RL Zoo: https://github.com/DLR-RM/rl-baselines3-zoo
It has checkpoints, progress bar, periodic evaluation, wandb and tensorboard integration, reproducible experiments and more...

i tried to highlight it more in the past but it seems that some people still miss it.

**Comment by qgallouedec** [comment]
> i tried to highlight it more in the past but it seems that some people still miss it.

Related: #1253 
@Bonifatius94 that you for your feedback. Tell us if the Zoo matches what you are describing. If so, do you have a suggestion so that future new users don't miss out?

**Comment by Bonifatius94** [comment]
Hmm that's quite embarrassing, tbh. I knew you had this zoo repo, but I thought it's just to outline past training results for common Gym environments. But it looks like it's actually doing lots of controlled experimentation setup stuff that I'm interested in. I'm going to review your zoo repo and let you know my findings.
