### ISSUE TITLE
[Question] How to extract the probability distribution of sb3

### ISSUE THREAD

**Issue by 1176358062** [DLR-RM/stable-baselines3#1257]
### ❓ Question

For some reason, I need to get the probability of the PPO model policy in the discrete action space, not the sampling obtained from this probability distribution
Now I know I can use the model.policy.get_distribution method, but when I do that, I only get the following distribution:
<stable_baselines3.common.distributions.CategoricalDistribution object at 0x7fa7f3d864d0>

I don't know how to extract this distribution into a probability distribution in python/numpy

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Try that:

```python
actions = torch.arange(distribution.action_dim)
log_probs = distribution.log_prob(actions)
```

**Comment by 1176358062** [comment]
> Try that:
> 
> ```python
> import torch
> 
> model = ...
> observation = ... # as a torch tensor
> 
> model.policy.get_distribution(observation)
> actions = torch.arange(distribution.action_dim)
> log_probs = distribution.log_prob(actions)
> ```

That works for me
