### ISSUE TITLE
[Feature Request] Implementation of QC_SANE

### ISSUE THREAD

**Issue by surbhigupta1908** [DLR-RM/stable-baselines3#1258]
### 🚀 Feature

I have implemented QC_SANE DRL approach (pytorch framework) and want to add this as feature to this repo.
Research Paper: https://ieeexplore.ieee.org/document/9640528

### Motivation

To contribute to open source (stable baselines3) as this repo and its tensorflow implementations helped me a lot in understanding the implementation of DRL approaches.

### Pitch

I want to provide the implementation of QC_SANE so that DRL community can leverage its implementation.

### Alternatives

I have only pytorch implementation of QC_SANE. No other alternatives are available.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment]
Hello,
this sounds more like something for SB3 contrib (see https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/115 for instance) or for SB3 project list that we have in our doc.

**Comment by surbhigupta1908** [comment]
Yes, it is for SB3 and my codes are prepared using (https://github.com/combra-lab/pop-spiking-deep-rl) as base repo. I have arranged the files according tot SB3 file structure for seamless integration.
