### ISSUE TITLE
[Bug]: `ProgressBarCallback` doesn't match *actual* `total_timesteps`

### ISSUE THREAD

**Issue by dominicgkerr** [DLR-RM/stable-baselines3#1259]
### 🐛 Bug

In a similar way to Issue #1150, a `ProgressBarCallback` can be stepped more/fewer times than the `total_timesteps` value provided to an algorithm's `.learn(...)` method.
![Screenshot from 2023-01-03 16-46-34](https://user-images.githubusercontent.com/12174745/210402171-fc085926-80a5-488b-ab2f-f9478bc1c336.png)

As `tqdm.rich` doesn't always *flush* when `self.pbar.update` is called, `ProgressBarCallback` seems to typically under-report the number of steps actually processed (as seen above). However, this can be easily fixed by adding a `self.pbar.refresh()` call to the `ProgressBarCallback._on_training_end` method.
![Screenshot from 2023-01-03 18-22-17](https://user-images.githubusercontent.com/12174745/210417981-4f1ba3b8-1159-4579-a994-818ed657a76a.png)

To fix the over-reporting of the final (`PPO`) progress bar, I think the `total` value passed into the callback's constructor (file: stable_baselines3/common/callbacks.py, line: 680) should be first rounded-up to a multiple of  
the algorithm's `n_steps`. This should then correctly report the algorithms progress while collecting experience - without this, I can imagine a very large rollout or computationally slow environment, resulting in a long wait without useful progress updates...

More generally, for vectorized environments, I think the `total` should also be rounded-up to a multiple of the callback's `training_env.num_envs`, as its `._on_step()` method advances the displayed progress by more than one. I believe this would be a one/two line change (plus, maybe a new unittest), which I'd be very happy to open!

### To Reproduce

```python
import gym
from stable_baselines3 import DQN, A2C, PPO

env = gym.make('MountainCar-v0')

DQN("MlpPolicy", env, seed=42).learn(total_timesteps=10_000, progress_bar=True) 
A2C("MlpPolicy", env, seed=42).learn(total_timesteps=10_000, progress_bar=True)
PPO("MlpPolicy", env, seed=42).learn(total_timesteps=10_000, progress_bar=True)
```

### System Info

- OS: Linux-5.15.0-56-generic-x86_64-with-glibc2.35 # 62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
- Python: 3.10.6
- Stable-Baselines3: 1.7.0a11
- PyTorch: 1.13.0+cu117
- GPU Enabled: True
- Numpy: 1.23.5
- Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hi!, thank you for the detailed description. We would be happy to look at a PR that fixes the problem you report. I think an additional unittest is not needed for this one.
