### ISSUE TITLE
The target entropy parameter in the SAC algorithm

### ISSUE THREAD

**Issue by mysweetdcm** [DLR-RM/stable-baselines3#1262]
### ❓ Question

I am a little confused as to whether the choice of target_entropy parameter, which defaults to 'auto', is a negative action-space dimension, as stated in the paper?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
https://github.com/DLR-RM/stable-baselines3/blob/4fa17dcf0f72455aa3d36308291d4b052b2544f7/stable_baselines3/sac/sac.py#L157-L160 ?

**Comment by mysweetdcm** [comment]
ok thank u,look at the source code not carefully enough

**Comment by mysweetdcm** [comment]
> https://github.com/DLR-RM/stable-baselines3/blob/4fa17dcf0f72455aa3d36308291d4b052b2544f7/stable_baselines3/sac/sac.py#L157-L160
> 
> ?

ok thank u,look at source code not carefully
