### ISSUE TITLE
AssertionError: The observation returned by `reset()` must be a dictionary

### ISSUE THREAD

**Issue by Paulchen29** [DLR-RM/stable-baselines3#1264]
### 🐛 Bug

Hi Guys

when I do a check_env I get error: `AssertionError: The observation returned by `reset()` must be a dictionary`.
I tried to make a big dicitionary out of single dics. `space_to_observe = space_to_observe | space_single_workpiece`.

When I make `model.learn(total_timesteps=10)` I get the error: `TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Box'` (compare attached screenshots)

![Scrennshot1](https://user-images.githubusercontent.com/35149760/211202754-d22321d6-7d68-4c2c-8113-51a4e93dd9d1.PNG)
![Scrennshot2](https://user-images.githubusercontent.com/35149760/211202755-4fa172a4-c83d-48ba-a208-b99af3d02a58.PNG)

Any advise would be appreciated.

Thanks

### Code example

```python
class PlacementEnv(gym.Env):

    def __init__(self, wp, sl):
        self.reward = None
        self.workpieces = wp
        self.slabs = sl

        # Define the observation space
        i = 1
        space_to_observe = {}

        for workpiece in self.workpieces:
            highx = workpiece.pointMax_X
            highy = workpiece.pointMax_Y
            low = np.array([0, 0])
            high = np.array([highx, highy])

            space_single_workpiece = {
                'points_workpiece' + str(i): gym.spaces.Box(low, high, shape=(2,), dtype=np.int16),
                'slabID_workpiece' + str(i): gym.spaces.Discrete(1)}
            space_to_observe = space_to_observe | space_single_workpiece
            i = i + 1

        dict_space = spaces.Dict(space_to_observe)
        self.observation_space = dict_space

        # Define action space
        # 1=Target Slab, 2=InsertionPoint X, 3=InsertionPoint Y, 4=Rotation Angle (future)
        self.action_space = spaces.MultiDiscrete([len(self.slabs), 3400, 2000])

    def reset(self):
        i = 1
        space_to_observe = {}

        for workpiece in self.workpieces:
            workpiece.slab_id = 0
            workpiece.insertion_point = (0, 0)
            workpiece.rotation_angle = 0
            highx = workpiece.pointMax_X
            highy = workpiece.pointMax_Y
            low = np.array([0, 0])
            high = np.array([highx, highy])
            space_single_workpiece = {
                'points_workpiece' + str(i): gym.spaces.Box(low, high, shape=(2,), dtype=np.int16),
                'slabID_workpiece' + str(i): gym.spaces.Discrete(1)}
            space_to_observe = space_to_observe | space_single_workpiece
            i = i + 1

        return gym.spaces.Dict(space_to_observe)
    
   def step(self)
     pass

```

### Relevant log output / Error message

```shell
AssertionError: The observation returned by `reset()` must be a dictionary
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
`reset` is supposed to return the initial observation (s_0), not the observation space. I recommend you follow the gym's documentation on how to create a custom environment. https://www.gymlibrary.dev/content/environment_creation/

> **Warning**
> There are some changes between the version currently used in SB3 (0.21) and the one used in the documentation (0.27). See https://gymnasium.farama.org/content/migration-guide/

**Comment by qgallouedec** [comment]
By the way, your code is not minimal, so I can't really understand what you are trying to do. Next time, try to make it minimal. Your mistake may be just that you confused `dict` with `spaces.Dict`. If so, the following change may solve your problem.

```diff
- return gym.spaces.Dict(space_to_observe)
+ return space_to_observe
```

**Comment by Paulchen29** [comment]
Hi and thank you very much.
I learned a lot in the last couple of days. That is my first ever project in RL and I think I have a lot to learn still. 
Now I will rewrite my code and pass an np.array.
But one thing is not still clear to me and I can't find a satisfing answer on the internet.
So let's imagine I have an 2D array. Will it be possible to have a dynamic size for each new run. So may idea is to train the model with different sizes. So one training will be with `array[500][500] = ...` once the training is completed it will be for e.g. `array[600][450] = ...` .
You can think about this like passing everytime an image with different sizes. Or does it need to have always a fix size?

**Comment by qgallouedec** [comment]
The size must be fixed. Neural networks take as input a fixed size tensor, so we have the same constraint here.
I hope your problem has been solved.  If so, I invite you to close the issue. If it remains, let us know.
