### ISSUE TITLE
difference between using monitor wrapper, logger,tensorboard integration and wandb callback?

### ISSUE THREAD

**Issue by muk465** [DLR-RM/stable-baselines3#1266]
### ❓ Question

I have a general doubt ,so i will not be giving my env code just the minimal code of sb3.
1)I want  to know whats the use of getting monitor wrapper when if i just use logger i can get all the other variables.

```
from stable_baselines3.common.monitor import Monitor
from stable_baselines3 import DDPG
from stable_baselines3.common.noise import NormalActionNoise, OrnsteinUhlenbeckActionNoise

from stable_baselines3 import TD3
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.results_plotter import load_results, ts2xy
from stable_baselines3.common.noise import NormalActionNoise
from stable_baselines3.common.callbacks import BaseCallback
from stable_baselines3.common.logger import configure

env2=NeuroRL5(label_name)
# Logs will be saved in log_dir/monitor.csv
env2 = Monitor(env2, log_dir)


tmp_path = "/content/drive/MyDrive/logg"
# set up logger
new_logger = configure(tmp_path, ["stdout", "csv", "tensorboard"])

model = TD3("MlpPolicy", env2, action_noise=action_noise, verbose=1, tensorboard_log="/content/drive/MyDrive/logg")
model.set_logger(new_logger)

model.learn(total_timesteps=50, log_interval=1)
```

2)I am using above code for getting  the logs and tensorboard plots.
3)But after i use custom logger to output the tensorflow file and give op in csv format ,i am now not getting the monitor.csv ,also my progress.csv file is coming out to be empty.
4)do i need monitor wrapper if i am using tensorboard integration ?
5)I have read the documentation but got confused regarding using all three together 
System Info
My environment consists of a 3d numpy array which has obstacles and a target ,my plan is to make my agent which follows a action model to reach the target:

I am using colab
how the library was installed : !pip install stable-baselines3[extra]
Python: 3.7.14
*Stable-Baselines3: 1.6.1
*PyTorch: 1.12.1+cu113
*GPU Enabled: True
*Numpy: 1.21.6
*Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
in your case, I'm not sure to understand why you need a custom logger.

**Comment by muk465** [comment]
I want to get the csv file along with the tensorboard file @araffin

**Comment by araffin** [comment]
> I want to get the csv file along with the tensorboard file @araffin

please use the RL zoo, it does that automatically (see https://github.com/DLR-RM/rl-baselines3-zoo/blob/6cc71f1b5c2a3f5a62c005d3b39d588493305128/rl_zoo3/exp_manager.py#L610).
If not, you need to specify a log file for the Monitor wrapper (as you seems to do) and you will also have both (`monitor_dir` if you use `make_vec_env`).
