### ISSUE TITLE
[Feature Request] Make optimizer only when needed

### ISSUE THREAD

**Issue by younik** [DLR-RM/stable-baselines3#1271]
### 🚀 Feature

In BaseModel(s), instead of constructing the optimizer at initialization, make it only when requested (or after at least one forward pass). 

### Motivation

Sometimes, it is useful to construct the network during the first forward pass, for example, when the input shape is not known a priori. 
```python
def forward(self, x):
    if self.net is None:
         self.net = ...
    
    return self.net(x)
```

This fails silently(!) right now because the optimizer is constructed at initialization, thus `.parameters()` doesn't contain `self.net.parameters()`.

### Pitch

A simple way for doing this is by making the optimizer property like this:
```python
@property
def optimizer(self):
    if self._optimizer is None:
       self._optimizer = self.optimizer_class(self.parameters(), lr=lr_schedule(1), **self.optimizer_kwargs)
    return self._optimizer
```

### Alternatives

Do nothing.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment]
>  when the input shape is not known a priori.

why would you not know the shape in advance?

> by making the optimizer property like this:

but you can do that already if you use a custom policy, no?

> Alternatives

I guess computing the shape at initialization, as we do for Nature CNN is not possible?
https://github.com/DLR-RM/stable-baselines3/blob/30a19848cef28f88a4cb38667ba74b3963be8f1d/stable_baselines3/common/torch_layers.py#L97-L101

**Comment by younik** [comment]
> when the input shape is not known a priori.

In my case it is because I am using different `FeaturesExtractor` and tuning for the best choice, running different experiments with different `FeaturesExtractor`.

Yes, you are right, I can do a forward pass on the feature extractor to get the output shape and pass it at the initialization of mlp_extractor.
Yet, as a non-expert of the SB3 internal, relying only on the knowledge in [this doc page](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html), the straightforward solution for me was making the net in the forward pass and it took a bit of pain to catch the problem

**Comment by araffin** [comment]
>  the straightforward solution for me was making the net in the forward pass and it took a bit of pain to catch the problem


mmh, the custom features extractor example do have shape computation in the constructor (i'm surprised you didn't build on top of that one): 
https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-feature-extractor

**Comment by younik** [comment]
> > the straightforward solution for me was making the net in the forward pass and it took a bit of pain to catch the problem
> 
> mmh, the custom features extractor example do have shape computation in the constructor (i'm surprised you didn't build on top of that one): https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-feature-extractor

You are right, this is the suggested approach in the doc. Thanks!
