### ISSUE TITLE
[Bug]: KeyError when observation is a dictionary and one of the keys is an image

### ISSUE THREAD

**Issue by saeidb71** [DLR-RM/stable-baselines3#1275]
### 🐛 Bug

When Observation is a dictionary and one of its keys is an image, it sends a KeyError. Also when "norm_obs=True", it sends another error saying its type needs to be float32 , but the image type is unit8.

### To Reproduce

My code is complex and cannot provide an example.

### Relevant log output / Error message

```shell
../lib/python3.9/site-packages/stable_baselin es3/common/torch_layers.py", line 276, in forward
    encoded_tensor_list.append(extractor(observations[key]))

KeyError: 'depth_image1_channel'
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Thanks for reporting this. Could you try to translate your description into a minimal code, so we can work on it?

**Comment by araffin** [comment]
and please use the custom gym env template (make sure to check the env with the env checker)
