### ISSUE TITLE
[Question] What about env.done = True and it also hits TimeLimit?

### ISSUE THREAD

**Issue by MagiFeeney** [DLR-RM/stable-baselines3#1276]
### ❓ Question

I am curious about how the code below handles timeout for on-policy algorithms. Does the condition filter the case that `env.done = True and truncated = True`? As my test shows that the terminal observation is always not `None` as long as it hits TimeLimit, however, this includes the case that the environment actually reaches the end of episode but also being truncated, in which we do need to modify the actual reward, since single reward signal explains the full episode information.
 
``` python
for idx, done in enumerate(dones):
    if (
        done
        and infos[idx].get("terminal_observation") is not None
        and infos[idx].get("TimeLimit.truncated", False)
    ):
        terminal_obs = self.policy.obs_to_tensor(infos[idx]["terminal_observation"])[0]
        with th.no_grad():
            terminal_value = self.policy.predict_values(terminal_obs)[0]
        rewards[idx] += self.gamma * terminal_value
```
My test script would be:
``` python
for idx, done in enumerate(dones):
    if (
        done
        and infos[idx].get("TimeLimit.truncated", False)
    ):
        if infos[idx].get("terminal_observation") is not None:
            print("Terminal observation exists")
            terminal_obs = self.policy.obs_to_tensor(infos[idx]["terminal_observation"])[0]
            with th.no_grad():
                terminal_value = self.policy.predict_values(terminal_obs)[0]
            rewards[idx] += self.gamma * terminal_value
        else:
            print("Terminal observation is None")
```
### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Does the condition filter the case that env.done = True and truncated = True? 

What do you mean exactly?

Probably relevant: https://github.com/openai/gym/issues/3102

> As my test shows that the terminal observation is always not None as long

for all `VecEnv` and wrappers included in SB3, the terminal observation is always defined but this might not be the case when using custom `VecEnv` (for instance Isaac Sim/envpool).

**Comment by MagiFeeney** [comment]
Suppose we only consider the case that the agent hits the TimeLimit, and this case can be further divided into two cases: `env.done = True` or `env.done = False`. Does the condition in the for loop cover both, or only one of which, if so, which one? (it is hoped to only consider the latter case and not the former)? I am worrying this condition may cover the first case where `env.done = True`, if this happens, we may wrongly bootstrap a further step, because though it hits the TimeLimit at the same time the episode ends, for which we don't have to modify anything.

**Comment by MagiFeeney** [comment]
So after reading https://github.com/openai/gym/issues/3102, I am only unclear about the last case in the table of the old gym API,
which is `env.done = True and truncated = True`, how and where in your code handles this situation? Does it have a `wrapper.done`, `True` or `False`?
|   | `env.done=False` | `env.done=True` |
| :-: | :-: | :-: |
| `truncated=False` | valid next obs `wrapper.done=False` | invalid next obs `wrapper.done=True` |
| `truncated=True`  | valid next obs `wrapper.done=True`  | N/A |

**Comment by araffin** [comment]
To make it simple, SB3 considers time limit (and other truncations) like that:
```python
if need_to_truncate:
    info["TimeLimit.truncated"] = not done
    done = True
```
so if the episode is already over for some reasons (`done=True`), `truncated` will always be false (this behavior was changed in gym 0.26 and that's why I raised the issue in gym repo).
The last case is not considered (env termination and truncation are mutually exclusive in SB3).

I wrote a patch to keep the behavior consistent between 0.21 and 0.26+: https://github.com/DLR-RM/rl-baselines3-zoo/blob/feat/gym-0.24/rl_zoo3/gym_patches.py#L26-L49

**Comment by MagiFeeney** [comment]
If I understand it correctly, can I say that whenever the agent reaches the end of episode in the TimeLimit (≤), the truncated is set to `False`, and the condition `done and infos[idx].get("TimeLimit.truncated", False)` being `True` only implies truncated but not finish the episode?

**Comment by araffin** [comment]
> only implies truncated but not finish the episode?

the episode will be over because of the timelimit/truncation yes (and not because of something else).

> whenever the agent reaches the end of episode in the TimeLimit (≤), the truncated is set to False

if the episode is over for any reason which is not timeout/timelimit/truncation, `truncated` will be `False` in SB3 (gym behavior is inconsistent between versions, that's why we have some patches in the zoo).

**Comment by MagiFeeney** [comment]
Thanks for your concrete explanation. I think the current implementation is more handy, though not intuitive.
