### ISSUE TITLE
[Question] Resuming training of loaded model

### ISSUE THREAD

**Issue by fracapuano** [DLR-RM/stable-baselines3#1277]
### ❓ Question

Hi, 
I am training an agent on a large number of timesteps (50M). In particular, the whole training process would, in principle, take a couple of days (to the very least). 
Considering this, I made a great usage of `CheckpointCallback` and saved a version of my model (via `model.save("checkpoint")`; my model is `MaskablePPO`, which anyway is reported to work exactly as PPO except for action masking) every 500k timesteps. 

With my great surprise, my training process was killed this afternoon, after 33M timesteps only (which, btw, took me more than a day and a half to reach). How can I load back the model to resume training? 

I tried:

```python
model = MaskablePPO.load("mycheckpoint")
model.learn(10_000_000)
```

However, from my logging operations, the training seems to have started once back from scratch.

Is there anything I am missing out?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hi, try

```python
model.learn(10_000_000, reset_num_timesteps=False)
ˋ``

**Comment by fracapuano** [comment]
Hey, 
Thanks for help.

I tried your method and did not succed! The agent seems to have "forgotten" and start learning again.
I am using: 
```python
CheckpointCallback(BaseCallback)
```

Anything I am missing out?

**Comment by fracapuano** [comment]
It works just fine, thanks!
Closing this issue :)
