### ISSUE TITLE
[Bug]: Action noise changes the action dtype

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/stable-baselines3#1278]
### 🐛 Bug

It's more an unwanted behaviour than a bug. As gym/torch works with `float32`, action noise should be `float32`.

### To Reproduce

```python
import numpy as np

from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.noise import OrnsteinUhlenbeckActionNoise

noise = OrnsteinUhlenbeckActionNoise(np.array([0]), sigma=np.array([0]))
env = make_vec_env("Pendulum-v1")

print(env.action_space.sample().dtype)
print((env.action_space.sample() + noise()).dtype)
```

### Relevant log output / Error message

```shell
float32
float64
```

### System Info

- OS: macOS-13.0.1-arm64-arm-64bit Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
- Python: 3.9.16
- Stable-Baselines3: 1.8.0a1
- PyTorch: 1.13.1
- GPU Enabled: False
- Numpy: 1.24.0
- Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by sidney-tio** [comment]
Hey, if no one is working on it, I'll take it up. 

For the respective `__call__` functions in `NormalActionNoise` and `OrnsteinUhlenbeckActionNoise`, I'll cast the outputs to float32 before returning

**Comment by qgallouedec** [comment]
I'm not, I'll be happy to review a PR on this :)
