### ISSUE TITLE
Use python logger instead of print

### ISSUE THREAD

**Issue by araffin** [DLR-RM/stable-baselines3#128]
Currently, we use `self.verbose` and `print` for logging and debug info but a cleaner way would be to use the logging package from python.

**Comment by Miffyli** [comment]
Hmm could you clarify the "cleaner" part? As in the printy-ness level is decided by the `logging` levels instead of our own verbose commands? That part sounds good, but I am worried `logging` would print out its own stuff among the lines and create bit of a mess. 

As a sidenote: Something seems to be printing out control characters, as my bash shell stops refreshing after running some A2C runs. I need to confirm that this is from sb3 though, and not from my scripts.

**Comment by araffin** [comment]
>Hmm could you clarify the "cleaner" part?

This is more about using the right tool and not re-inventing the wheel.
Instead of:
```python

if self.verbose > 0:
    print("")

if self.verbose > 1:
    print("")
```

We would have:
```
logger.info("")
logger.debug("")
```

It would also the user to specify custom formatting, for example: https://github.com/sergionr2/RacingRobot/blob/master/main.py#L35

Here I can print and save the log at the same time and easily format each entry + choose which type of logging level I want for each file handler.

>but I am worried logging would print out its own stuff among the lines and create bit of a mess.

which "own stuff"?

>As a sidenote: Something seems to be printing out control characters, as my bash shell stops refreshing after running some A2C runs. I need to confirm that this is from sb3 though, and not from my scripts.

ah? never experienced that

**Comment by Miffyli** [comment]
Thanks for clarifying! This is what I assumed 👍 

> which "own stuff"?

The timestamps and such, but like you said this can be removed with custom formatting.

> ah? never experienced that

Yeah this is first for me, too. Could very well be from my own codes too though.

**Comment by spider210792** [comment]
You could use [rich](https://github.com/willmcgugan/rich), it's possible to print tables, progress bars, etc. The only problem I see is that to work with PyCharm console you need to enable 'emulate terminal' on settings...

**Comment by tfurmston** [comment]
Would you like some help on this issue? Personally, I would prefer it if the standard python logger were used.

**Comment by Miffyli** [comment]
@tfurmston Help is always welcome! :) . One major thing we need to think about is backwards-compatibility (e.g. keeping the verbose parameter but it sets logger level under the hood).

**Comment by tfurmston** [comment]
ok, let me have a look through the code and see what is going on. 

One initial question, I can see you are using multiple values of `verbose`. For example, I can see `self.verbose > 0` and `self.verbose > 1`. 

I assume these correspond to different logging levels, right? 

Do you have the correspondence you have for these values to logging levels?

**Comment by Miffyli** [comment]
IIRC `verbose = 0` is no printing at all (only exceptions), `verbose = 1` is training statistics and `verbose = 2` is other details like applying transpose on images. Sounds like `logger.info` and `logger.debug` are suitable for these, respectively.

**Comment by tfurmston** [comment]
ok, cool. 

One of the main differences will be that the logging level will be set once in the config and not passed around through the verbose parameter, but it should be easy to change. 

Also there is a class called `Logger` that seems to be more of a stats calculator/collector and really related to the standard python logging.  I am assuming this will stay as it is and is unrelated to the changes proposed in this issue. Is that correct?

**Comment by araffin** [comment]
>Also there is a class called Logger that seems to be more of a stats calculator/collector and really related to the standard python logging. I am assuming this will stay as it is and is unrelated to the changes proposed in this issue. Is that correct?

yes, in fact, there is another issue for that one: https://github.com/DLR-RM/stable-baselines3/issues/109

**Comment by tfurmston** [comment]
ok, thanks. 

I'll have a look through then.

**Comment by tfurmston** [comment]
OK, so this is a first attempt at a PR on this issue, [https://github.com/DLR-RM/stable-baselines3/pull/407](https://github.com/DLR-RM/stable-baselines3/pull/407).  Please let me know what you think.

I've not really touched some of the main logging functionality in `common.utils.py` and instead replaced the print statements with a standard logger. I think it is worth refactoring `common.utils.py` at some point though. From what I can see I expect it can be greatly simplified by using standard tools. I thought it was out of scope for this issue though.

**Comment by Miffyli** [comment]
@tfurmston 

Quickly skimming over the code I see you have made throughout updates to remove all existing prints +1

One major question tho: why dependency on the new library (what is the motivation? Is it necessary?) I would much prefer not adding new dependencies if absolutely necessary).

**Comment by tfurmston** [comment]
[https://github.com/hynek/environ-config](environ-config) can be used to to configure your application, so that all expected  environment variables are used to configure the system in one place, along with validation and conversion as required. 

For example, it avoid having different environment variables being read in lots of different places in the code base, which is hard to maintain.

**Comment by araffin** [comment]
from now on, I think it would be better to have the discussion in the PR directly ;) (that's where I left my comments).

**Comment by tfurmston** [comment]
ok, sure.

**Comment by araffin** [comment]
Closing this after discussion in https://github.com/DLR-RM/stable-baselines3/pull/407
