### ISSUE TITLE
[Question] Is it possible to train models on GPU on Windows?

### ISSUE THREAD

**Issue by george-adams1** [DLR-RM/stable-baselines3#1281]
### ❓ Question

Above. All docs and issues I have seen have been training models with Linux OS. Was wondering if this is possible for Windows. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
>  Was wondering if this is possible for Windows.

yes
