### ISSUE TITLE
[Question] Is the env.reset() method being called at the end of a training and predict epoch?

### ISSUE THREAD

**Issue by rllyryan** [DLR-RM/stable-baselines3#1282]
### ❓ Question

With reference to the code block off the documentation for SB3:
```
import gym

from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env

# Parallel environments
env = make_vec_env("CartPole-v1", n_envs=4)

model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=25000)
model.save("ppo_cartpole")

del model # remove to demonstrate saving and loading

model = PPO.load("ppo_cartpole")

obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

Can I find out where in the source code is the env.reset() function being called in the learning and prediction step? 

I have a custom environment that resets the environment after done == True. I have taken a look at the OnPolicyAlgorithm class in the repository but I am unable to discern the location of the environment's reset function being called. [https://github.com/DLR-RM/stable-baselines3/blob/92f7a6f23b90a9965c2e9cbe53f775055c5e0dc4/stable_baselines3/common/on_policy_algorithm.py#L106]

Thank you for your time in addressing my concern!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/719 and #1114 
The getting started doc will be made clearer in #780

>  I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

it's in the vec env section...

**Comment by rllyryan** [comment]
Hi @araffin thank you for your reply! I now understand where the reset is done.
