### ISSUE TITLE
[Question] When does model.learn() update the TB-Event-File ?

### ISSUE THREAD

**Issue by askppp** [DLR-RM/stable-baselines3#1284]
### ❓ Question

Hello guys,

thanks for this wonderful repo. I'm trying to train a custom env.

My step does take too long (~ 30 sec). I will be stopping the training.. wanted only to see how the things will be done. 

With this code .. when will i get results in tensorboard ? Until now i always have this error (reached 1500 steps).

I'm getting the "events.out.tfevents." file created at the beginning but it didn't get updated. I thought i can see the rewards being given in a graph bcz i can print them from the first step.

```python
from stable_baselines3 import PPO
import os
from custom_env import MyEnv
import time

models_dir = f"models/{int(time.time())}/"
logdir = f"logs/{int(time.time())}/"

if not os.path.exists(models_dir):
    os.makedirs(models_dir)

if not os.path.exists(logdir):
    os.makedirs(logdir)

env = MyEnv()
env.reset()

model = PPO("MultiInputPolicy", env, verbose=1, tensorboard_log=logdir)

TIMESTEPS = 5000
iters = 0
for i in range(1, 100000000):
	iters += 1
	model.learn(total_timesteps=TIMESTEPS, reset_num_timesteps=False, tb_log_name=f"PPO", progress_bar=True)
	model.save(f"{models_dir}/{TIMESTEPS*iters}")
```
Here's what my TB shows all the time:

![TB](https://user-images.githubusercontent.com/102218389/213148241-53ff9d44-49fa-43ba-b0e9-d592ec198fa1.png)

Thank you very much.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> With this code .. when will i get results in tensorboard ?

This is defined by the `log_interval` passed to the `learn()` method (for A2C/PPO, it corresponds to a number of rollouts).
If you want the data sooner, you can call `self.logger.dump(step=self.num_timesteps)` with a callback (cf. doc).

> My step does take too long (~ 30 sec).

if your step takes that long you should consider debugging with a much faster env (for instance built-in gym envs).


Side note: you should be using a `CheckPointCallback` I think instead of multiple calls to `learn()` (cf. doc).

**Comment by askppp** [comment]
Which Callback should i use ? 

Where do i have to write this: `self.logger.dump(step=self.num_timesteps)` ? 

Can i add it in the `CheckPointCallback `? 

Can you maybe provide a minimal working code for that ? 

You wrote `self.logger.dump(step=self.num_timesteps)` but in another Issue it was written: `self.logger.dump(self.num_timesteps)`

Thanks.

**Comment by araffin** [comment]
> Can you maybe provide a minimal working code for that ?

see: 

> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
