### ISSUE TITLE
Limitation: input observations shadowed in `evaluate_policy`

### ISSUE THREAD

**Issue by npit** [DLR-RM/stable-baselines3#1287]
In the `evaluate_policy` util, both input and output observations are assigned to the [same variable name](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/evaluation.py#L89) (i.e., `observations`):

```python
    while (episode_counts < episode_count_targets).any():
        actions, states = model.predict(observations, state=states, episode_start=episode_starts, deterministic=deterministic)
        observations, rewards, dones, infos = env.step(actions)
        current_rewards += rewards
        current_lengths += 1
        for i in range(n_envs):
            if episode_counts[i] < episode_count_targets[i]:

                # unpack values so that the callback can access the local variables
                reward = rewards[i]
                done = dones[i]
                info = infos[i]
                episode_starts[i] = done

                if callback is not None:
                    callback(locals(), globals())

```

This results in a callback invoked [below](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/evaluation.py#L102) to not have access to the input observations.

A simple fix would be renaming the output observations, and restore the `observations` variable to the outputs, once the callback is done.

**Comment by araffin** [comment]
Hello,
could you elaborate a bit more about your specific use case? (what and why do you want to do that)
(I do understand the limitation but I also want to make sure the change is needed)

**Comment by npit** [comment]
Hey,

I want to get all information available during training (both training measures environment-related data)  for  logging and monitoring purposes of the environment's learning and operational dynamics.

To do that I'm using a custom callback, overriding the `_on_step` method which gives me access to info like the above for all envs in a VecEnv. It would be nice if the input observation that caused the output reward / state was available as well.
