### ISSUE TITLE
[Question] Is it possible to set the exploration rate to 0, and turn off network training for a Stable Baselines 3 algorithm?

### ISSUE THREAD

**Issue by HaakonFlaaronning** [DLR-RM/stable-baselines3#1289]
### ❓ Question

After training a stable baselines 3 RL algorithm (I am using mainly PPO) I want to set the exploration rate to 0, and turn off network training so I always get the same output (action) from the model when given the same input (observation). Is it possible to do that? If not, is there a reason for why it should not be possible?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by HaakonFlaaronning** [comment]
Setting deterministic to True when calling model.predict() seems to do the trick (it defaults to False):

    model.predict(observation, deterministic=True)

**Comment by araffin** [comment]
> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

> Setting deterministic to True when calling model.predict() seems to do the trick

yes, this is the way.
