### ISSUE TITLE
May be a wrong "-"

### ISSUE THREAD

**Issue by Leo-xh** [DLR-RM/stable-baselines3#129]
https://github.com/DLR-RM/stable-baselines3/blob/bd2aae0c27d238a6a2c2f3a4c54066dfb30bd49b/stable_baselines3/ppo/ppo.py#L201

the "-“ in this line may be wrong because this line computes entropy_loss instead of entropy.

**Comment by Miffyli** [comment]
Closing as duplicate of #127
