### ISSUE TITLE
`make doc` fails: Definition list ends without a blank line; unexpected unindent

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/stable-baselines3#1290]
See https://github.com/DLR-RM/stable-baselines3/actions/runs/3967647380/jobs/6799855055#step:5:1

It's probably linked to a breaking change in sphinx v6.

The reason is that when sphinx does not find a docstring, for example here:

https://github.com/DLR-RM/stable-baselines3/blob/92f7a6f23b90a9965c2e9cbe53f775055c5e0dc4/stable_baselines3/common/envs/bit_flipping_env.py#L105-L106

it fetches in the super class. And this super class can be wrongly formatted (this is the case of gym.Env.seed). 
Rewriting on these docstring seems to work. I don't know how many functions it affects.
It also states `Warning, treated as error:`(see [here](https://github.com/DLR-RM/stable-baselines3/actions/runs/3967647380/jobs/6799855055#step:5:66)), so I guess there might be a way to treat the warning as a warning.

**Comment by araffin** [comment]
> Rewriting on these docstring seems to work. 

I remember having similar issues with gym... maybe in the gym 0.26 branch.
but yes, rewriting the docstring solves it.

>  be a way to treat the warning as a warning.

we don't allow warnings when building doc, so it's expected.

**Comment by qgallouedec** [comment]
You recommend overwriting all the docstrings then?

**Comment by araffin** [comment]
> You recommend overwriting all the docstrings then?

there are many?
yes for now. I guess it might be fixed by newer gym version?
otherwise, we need to see if there is a way to ignore some warnings

**Comment by qgallouedec** [comment]
> there are many?

I don't know, I'll check

**Comment by qgallouedec** [comment]
After some investigation, it comes from `sphinx_autodoc_typehints` since v2.21. The easy workaround would be to set `sphinx_autodoc_typehints==1.20.2` until gym v0.26. What do you think?

**Comment by araffin** [comment]
> until gym v0.26. What do you think?

we need to check that gym 0.26 actually solves those issues, otherwise I'm fine with the fix.
Maybe check if there is an issue in `sphinx_autodoc_typehints` repo (to be able to deactivate warnings from modules).

**Comment by qgallouedec** [comment]
> we need to check that gym 0.26 actually solves those issues, otherwise I'm fine with the fix.

If we overwrite broken docstring, we won't be able to know if gym 0.26 solves it (unless keeping track of overwritten docstring and remove them manually in gym 0.26 branch). The best way is to set `sphinx_autodoc_typehints==1.20.2` in master but not in gym 0.26 branch.

There is a highly fresh one indeed: https://github.com/tox-dev/sphinx-autodoc-typehints/issues/305
It seems like `sphinx_autodoc_typehints==1.21.1` could be enough. `make doc` locally pass with this version.
