### ISSUE TITLE
[Feature Request] Add a `stats_window` argument to constructor

### ISSUE THREAD

**Issue by jonasreiher** [DLR-RM/stable-baselines3#1302]
### 🚀 Feature

Models'/Algorithms' `learn()` methods should get `rollout_buffer_size` or `rollout_average` or similarly named parameter that determines the `maxlen` of `model.ep_info_buffer` and `model.ep_success_buffer`.

### Motivation

The `rollout/something` values logged by each algorithm are smoothing over a hardcoded 100 episodes by default.
This can sometimes be far to much and at other times far too little smoothing.

Especially considering that smoothing can be performed in a post processing step and TensorBoard or Weights and Biases directly offer this in their interfaces, the non-changeable default smoothing does not make much sense.

### Pitch

This parameter should be added to the `_setup_learn()` method of the `BaseAlgorithm` class since `model.ep_info_buffer` and `model.ep_success_buffer` are initialized here.

**I would be willing to contribute.**

### Alternatives

It could also be a parameter during model initialization or of the logger but both of these alternatives come with more significant code changes.

It's also possible to achieve this with a callback (see https://github.com/DLR-RM/stable-baselines3/issues/1300#issuecomment-1406635163) but this feels unnecessarily hacky.

### Additional context

Issues #1300 and #313 are directly related.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment]
> Models'/Algorithms' learn() methods should get rollout_buffer_size or rollout_average or similarly named parameter that determines the maxlen of model.ep_info_buffer and model.ep_success_buffer

I would actually add that to the base class constructor, not the `learn()` method.

> Alternatives

`RawStatsCallback` should be a good alternative: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/rl_zoo3/callbacks.py#L208-L239
and plotting from monitor files directly too (as done in the RL Zoo).
We also recommend using separate eval env (and an `EvalCallback`) so you don't depend on the window size to know the real current performance of the agent.

**Comment by jonasreiher** [comment]
`RawStatsCallback` is a fair alternative (see #1300) but not easily discoverable when not working with rl-baselines3-zoo.

I'm not sure about adding it to the constructor since I think it's more closely related to the `log_interval` variable in the `learn()` method but I'd be fine with both ways.

Note that this does not replace the need for an `EvalCallback`. It just gives more control over smoothing the existing rollout log.

Do you want me to take this on? If so, what should it be called?

**Comment by araffin** [comment]
> RawStatsCallback is a fair alternative (see https://github.com/DLR-RM/stable-baselines3/issues/1300) but not easily discoverable when not working with rl-baselines3-zoo.

true but it also corresponds to a specific need.

> I'm not sure about adding it to the constructor since I think it's more closely related to the log_interval variable in the learn() method but I'd be fine with both ways.

it is independent, as this parameter only set the number of datapoints to average.
log interval only regulates how often this value is displayed.

> Note that this does not replace the need for an EvalCallback. It just gives more control over smoothing the existing rollout log.

We agree on that =)

> Do you want me to take this on? If so, what should it be called?

yes please =)
I had something like `stats_window` or `stat_window` in mind, but I'm open to better alternatives ;) (I'm not fully satisfied with those two).
