### ISSUE TITLE
Cannot import HParam

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [DLR-RM/stable-baselines3#1305]
### 🐛 Bug

I'm trying to import [HParam as per documentation](https://stable-baselines3.readthedocs.io/en/master/guide/tensorboard.html#logging-hyperparameters) in order to create a callback class. But I'm getting an error during import

### Code example

`from stable_baselines3.common.logger import HParam`

### Relevant log output / Error message

```shell
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_25088/943879046.py in <module>
     21 from stable_baselines3 import A2C, PPO, DQN
     22 from stable_baselines3.common.callbacks import BaseCallback
---> 23 from stable_baselines3.common.logger import HParam
     24 
     25 """

ImportError: cannot import name 'HParam' from 'stable_baselines3.common.logger' (c:\ProgramData\mambaforge\lib\site-packages\stable_baselines3\common\logger.py)
```

### System Info

OS: Windows-10-10.0.19045-SP0 10.0.19045
Python: 3.9.15
Stable-Baselines3: 1.5.0
PyTorch: 1.13.1
GPU Enabled: False
Numpy: 1.23.5
Gym: 0.26.2

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Please upgrade your SB3 version, it also seems that you are using an incompatible gym version.

**Comment by Karlheinzniebuhr** [comment]
I'm using the latest version available on conda which is stable-baselines3         1.5.0, does this version not support HParam?

**Comment by Karlheinzniebuhr** [comment]
Checked the commit history, HParam needs v1.7. Solved it by using pip instead of conda.

**Comment by araffin** [comment]
yes, SB3 is a python only package and we don't have official support for conda, best is to use pip (as shown in the doc).
see https://github.com/DLR-RM/stable-baselines3/issues/738 (@cyprienc did publish it)
