### ISSUE TITLE
[Question] Is it possible to pass options to reset()?

### ISSUE THREAD

**Issue by henke443** [DLR-RM/stable-baselines3#1306]
### ❓ Question

I've been trying to pass the current num_timesteps to my reset function to incrementally make my custom environment more challenging. 

I've investigated the callback to model.learn() but I can't figure out how to make it behave as I want. 

It is possible to call reset() on each step using: `model.env.env_method("reset", options=options)` but is there some way to do this on each new episode after the reset() function has been already called for that episode, so it is overridden?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by ReHoss** [comment]
I guess you want to use a `Callback.on_rollout_end` method, because the environment is reset internally before this call If I remember in the `collect_rollouts` method of On-policy algorithms.

**Comment by araffin** [comment]
>  incrementally make my custom environment more challenging.

I cannot find the issue again (probably in SB2 repo), but callbacks are made for that (you can search on github, there are some examples of curriculum learning).
Best is to use `self.env_method("set_difficulty", "easy")` and this will be used by the env at the next reset.
