### ISSUE TITLE
How to record information during test time?

### ISSUE THREAD

**Issue by muk465** [DLR-RM/stable-baselines3#1307]
### ❓ Question

1)I wanted to know can we create and use a wrapper to record particular env variables used at every reset during prediction?
like we do in training?
2)below is sample code of model.predict

```

model2=DDPG.load(model_path)
dones=False
m=[]
action_arr=[]
while dones!=True:
    action, states = model2.predict(obs)
    action_arr.append(action)
    
    obs, rewards, dones, info = env.step(action)

    
    obs_arr.extend([obs])
```
System Info
My environment consists of a 3d numpy array which has obstacles and a target ,my plan is to make my agent which follows a action model to reach the target:

I am using colab
how the library was installed : !pip install stable-baselines3[extra]
Python: 3.7.14
*Stable-Baselines3: 1.6.1
*PyTorch: 1.12.1+cu113
*GPU Enabled: True
*Numpy: 1.21.6
*Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I wanted to know can we create and use a wrapper to record particular env variables used at every reset during prediction?

yes.
best is to try first before asking ;)
