### ISSUE TITLE
[Question] How to handle terminal observations for `VecEnvWrapper`-derived observation wrappers?

### ISSUE THREAD

**Issue by jonasreiher** [DLR-RM/stable-baselines3#1308]
### ❓ Question

Hi,
I am doing vision-based RL where I take an image of the environment and pass it through a pretrained encoder to get a state representation. Since the encoder lives on the GPU, it's significantly faster to pass a batch/vector of images through it than every image one-by-one.

I therefore want to wrap my environment in a `VecEnvWrapper` and use this to extend the observation with the encoded state representation.

### Setup

My `VecImageEncodingWrapper` wraps a `SubprocVecEnv`. The `SAC` algorithm is used for learning.
The wrapper looks like this:

```python
class VecImageEncodingWrapper(VecEnvWrapper):

    def __init__(self, venv: VecEnv, encoder: nn.Module):

        self.encoder = encoder

        extended_observation_space = gym.spaces.Dict({
            **venv.observation_space,
            'encoded_state': gym.spaces.Box(low=0.0, high=1.0, shape=(venv.num_envs, 16))
        })

        super().__init__(venv=venv, observation_space= extended_observation_space)

    def reset(self) -> Dict:

        obs = self.venv.reset()

        with torch.no_grad():
            images = torch.tensor(np.array(self.get_images()), device='cuda')
            encoded_state = self.encoder(images).cpu().numpy()

        obs['encoded_state'] = encoded_state

        return obs

    def step_wait(self) -> VecEnvStepReturn:

        obs, reward, done, info = self.venv.step_wait()

        with torch.no_grad():
            images = torch.tensor(np.array(self.get_images()), device='cuda')
            encoded_state = self.encoder(images).cpu().numpy()

        obs['feature_points'] = feature_points

        return obs, reward, done, info
```

### Problem

All of this works fine _until_ an episode terminates. Since the vector environment auto-resets, the `'terminal_observation'` key in the `info` dictionary is required to obtain the terminal state and fill a replay buffer. I see that this dictionary entry shows up when there's a `True` in `done` in my wrapper's `step_wait()` method.

_However_, the terminal observation in the `info` dictionary does not include the `'encoded_state'` part of the observation. And I cannot put it there since my environment is already back to the initial state of the next episode. And again, I do not want to do the observation extension in the individual non-vectorized environments for performance reasons.

### Question

How do I extend the terminal observation to include my encoded state in a `VecEnvWrapper`?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
>  The wrapper looks like this:

looks good but the `shape=(venv.num_envs, 16)` looks weird.

> And I cannot put it there since my environment is already back to the initial state of the next episode. 

```python
        with torch.no_grad():
            images = torch.tensor(np.array(self.get_images()), device='cuda')
            encoded_state = self.encoder(images).cpu().numpy()
```

this would have worked if you where not using `get_images()` but rather something that was already in the `obs` dict (that you can remove later).

In your case, it seems that you have no choice but write a custom `SubprocVecEnv` for your needs.
Another solution is to add a `last_image` attribute to your env that you can retrieve to populate the terminal observation.

**Comment by jonasreiher** [comment]
> but the shape=(venv.num_envs, 16) looks weird

Thanks, I wrongly assumed the vector observation space were necessary here.

> this would have worked if you where not using get_images() but rather something that was already in the obs dict (that you can remove later).

Also a valuable hint! I indeed solved it now by first equipping the individual environments with an observation wrapper that stores the image obtained via `env.render()` in the `obs` dict and then accessing this image in the vector wrapper like this:

```python
    def step_wait(self) -> VecEnvStepReturn:

        obs, rewards, dones, infos = self.venv.step_wait()

        with torch.no_grad():
            images = torch.tensor(np.array(obs['image']), device='cuda')
            encoded_state = self.encoder(images).cpu().numpy()
        obs['encoded_state'] = encoded_state
        obs.pop('image', None)

        for i, done in enumerate(dones):
            if not done:
                continue
            image = torch.tensor(infos[i]['terminal_observation']['image'], device='cuda').unsqueeze(dim=0)
            encoded_state = self.encoder(images).cpu().numpy()
            infos[i]['terminal_observation']['encoded_state'] = encoded_state
            infos[i]['terminal_observation'].pop('image', None)

        return obs, rewards, dones, infos
```
