### ISSUE TITLE
[Question] Using predict on a loaded model does not reflect learning progress

### ISSUE THREAD

**Issue by hawxkeye** [DLR-RM/stable-baselines3#1309]
### ❓ Question

I am using A2C in combination with MlpPolicy and an SubprocVecEnv to train an agent on a custom environment.
When I look at the tensorboard logs, and the logging of episode rewards in monitors via callback, the agent is clearly learning. As seen in more steps per episodes and a large improvement of achieved rewards. 
I'm saving the agent periodically, and via Callback (for best model) via model.save()
However, none of my saved models can replicate any behavior seen in the learning process. 
Instead, it seams to be stuck with the same action (out of 151) for all different observation states it gets.

I have tried to manually call model.predict(), as well as using _evaluate_policy_ from _stable_baselines3.common.evaluation_

Is there a major issue I have overlooked, or misunderstood? Should my saved model not represent the learned behavior in some way, and how do I replicate it. Any help would be greatly appreciated. If you need more information, please ask for it. Thank you in advance for your time.

**Steps taken**
I have checked for loading the model correctly, i.e., _model = A2C.load()_
Tested two ways of evaluating the agent
Used multiple saved models to verify my issue
I have set _deterministic_ to True and False, with both options not showing the learned behavior.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by signalprime** [comment]
I'm having the same issue.  How did you end up solving it?  I've been investigating heavily to no avail

**Comment by wilhem** [comment]
Me too.
There is any new on this?
