### ISSUE TITLE
[Feature Request] request title

### ISSUE THREAD

**Issue by george-adams1** [DLR-RM/stable-baselines3#1313]
### 🚀 Feature

Adding the ability to train on TPU hardware.

### Motivation

TPU's are becoming increasingly popular hardware and support would be great. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by qgallouedec** [comment]
> I have checked that there is no similar issue in the repo

#472
