### ISSUE TITLE
`SubprocVecEnv` on a custom environment gives input shape error

### ISSUE THREAD

**Issue by KING-SID** [DLR-RM/stable-baselines3#1314]
### 🐛 Bug

Working with  @trevor-richardson on this

`SubprocVecEnv` on a custom environment gives us a shape error, but using `DummyVecEnv` and keeping all else the same, produces the correct input shape. Details below

To create a multiprocessing-enabled vectorised environment for a custom environment, this is how our code is set up:
```
class CustomEnv(gym.Env):
        def __init__(self, custom, parameters, here, action_dimensionality, state_dimensionality):
              self.custom = custom
              self.parameters = parameters
              self.here = here
              self.action_space = spaces.Box(low=-10, 
              high=10, 
              shape=(self.action_dimensionality,)
              )
              self.observation_space = spaces.Box(
                  low=-np.inf,
                  high=np.inf,
                  shape=(1, state_dimensionality),
              )
...
```
We use this function to create an environment instance:
```
def make_env(args=None, rank=0):
        def _init():
            env = CustomEnv(**args)
            return env
        return _init
```
and use that function to create a `SubprocVecEnv` object:
```
....
env = SubprocVecEnv([make_env(args, rank=i) for i in range(n_envs)])
....
```
this `env` object is then passed into an agent, and then `learn` is called on the agent.

Running this, however, throws this error
```shell
...
File "/home/twrichar/anaconda3/envs/sbtest/lib/python3.8/site-packages/stable_baselines3/common/buffer.py" line 439, in add
       self.observations[self.pos] = np.array(obs).copy()
ValueError: could not broadcast input array from shape (16, 313) into shape (16, 1, 313)
```

Importantly, when we simply swap out the class for the `DummyVecEnv` type instead (leaving all else the same) there is no error, and stepping through with a debugger we see that the input array shape is correctly (16, 1, 313).
This is the swap I was describing:
```
....
env = DummyVecEnv([make_env(args, rank=i) for i in range(n_envs)])
....
```

### Proposed solution
We found that when we manually change the `buffers.py` code to add a dimension to the input array if it doesn't exist, then it works as expected with multiprocessing. 
**If we are using the library wrapper appropriately, and what we suggested fixes the issue in general, then kindly let us know and we'd love to make it a pull request (and our first contribution to the library!)**

### Code example

We use this function to create an environment instance:
```
def make_env(args=None, rank=0):
        def _init():
            env = CustomEnv(**args)
            return env
        return _init
```
and use that function to create a `SubprocVecEnv` object:
```
....
env = SubprocVecEnv([make_env(args, rank=i) for i in range(n_envs)])
....
```
this `env` object is then passed into an agent, and then `learn` is called on the agent.

### Relevant log output / Error message

```shell
...
File "/home/twrichar/anaconda3/envs/sbtest/lib/python3.8/site-packages/stable_baselines3/common/buffer.py" line 439, in add
       self.observations[self.pos] = np.array(obs).copy()
ValueError: could not broadcast input array from shape (16, 313) into shape (16, 1, 313)
```

### System Info

```
(sbtest) twrichar@MSI:~/projects/oam/oam-deep-dynamic-portfolio-allocation$ python -c 'import stable_baselines3 as sb3; sb3.get_system_info()'
- OS: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.17 # 1 SMP Wed Nov 23 01:01:46 UTC 2022
- Python: 3.8.16
- Stable-Baselines3: 1.7.0
- PyTorch: 1.13.1+cu117
- GPU Enabled: True
- Numpy: 1.22.3
- Gym: 0.21.0
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> have checked my env using the env checker

what is the output and warning(s) of it?

**Comment by araffin** [comment]
The following script runs with warnings but without any issue (both with Dummy and SubProc vec env):

```python
import gym

from gym import spaces
from stable_baselines3.common.env_checker import check_env
from stable_baselines3.common.vec_env import DummyVecEnv, SubprocVecEnv
from stable_baselines3.common.env_util import make_vec_env
import numpy as np

class CustomEnv(gym.Env):
    def __init__(self, action_dimensionality=2, state_dimensionality=13):
        self.action_space = spaces.Box(
            low=-10, high=10, shape=(action_dimensionality,)
        )
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(1, state_dimensionality),
        )

    def reset(self):
        return self.observation_space.sample()

    def step(self, action):
        return self.observation_space.sample(), 0, False, {}


if __name__ == "__main__":
    env = CustomEnv()
    check_env(env, warn=True)

    env = make_vec_env(CustomEnv, n_envs=2, vec_env_cls=SubprocVecEnv)

    for _ in range(10):
        obs = env.reset()
        for _ in range(100):
            action = env.action_space.sample()
            obs, reward, done, info = env.step(action)

```
