### ISSUE TITLE
[Bug]: Docker tqdm error

### ISSUE THREAD

**Issue by jaewoo-so** [DLR-RM/stable-baselines3#1315]
### 🐛 Bug

After install tqdm, model.learn with profress_bar occur  ImportError
"model.learn(total_timesteps=int(200), progress_bar=True)"

### To Reproduce

```python
import gym
from stable_baselines3 import DQN
from stable_baselines3.common.evaluation import evaluate_policy
from tqdm import tqdm

env = gym.make("LunarLander-v2")
model = DQN("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=int(200), progress_bar=True)
```

### Relevant log output / Error message

```shell
Exception has occurred: ImportError
You must install tqdm and rich in order to use the progress bar callback. It is included if you install stable-baselines with the extra packages: `pip install stable-baselines3[extra]`
  File "/home/sjw/lux/sb3_tutorial/basic_train_save_load.py", line 9, in <module>
    model.learn(total_timesteps=int(200), progress_bar=True)
ImportError: You must install tqdm and rich in order to use the progress bar callback. It is included if you install stable-baselines with the extra packages: `pip install stable-baselines3[extra]`
```

### System Info

docker : stablebaselines/stable-baselines3
GPU:  RTX 3090 
CUDA : 11.7
Python : 3.7.13
PyTorch : 1.11.0
Gym : 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue, the docker image is indeed outdated.
Best is to either install tqdm in the container and save a local image (snapshot), or build the image from the repo.

**Comment by araffin** [comment]
I've pushed new docker image for https://github.com/DLR-RM/stable-baselines3/pull/1327, which should solve the issue.
