### ISSUE TITLE
[Question] Doubts on n_steps, total_timesteps, SubprocVecEnv

### ISSUE THREAD

**Issue by gowthamnatarajan** [DLR-RM/stable-baselines3#1316]
### ❓ Question

My Custom environment has 6 actions and it terminates after max 30 steps. I have initialized 10 environments using DummyVecEnv. I am using PPO.

Doubts:

1. For SubprocVecEnv should the code for the environment be changed in any way? Should it now handle array of observations, actions, rewards or will the library take care of it?
2. The default value of n_steps is 2048. Since my max steps per episode is 30, should I change this to 30 to make it update after each episode? What should be the batch size?
3. I set total_timesteps in the learn function to 200,000. But it continues to learn beyond 200,000 episodes. Why is that?

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> For SubprocVecEnv should the code for the environment be changed in any way? Should it now handle array of observations, actions, rewards or will the library take care of it?

> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

If you have read the documentation, you may have noticed that no change is required.


> The default value of n_steps is 2048. Since my max steps per episode is 30, should I change this to 30 to make it update after each episode?

> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

See https://github.com/DLR-RM/stable-baselines3/issues/1272

> What should be the batch size?

batch size is an hyperparameter. We have links in our documentation if you want to understand more the algorithm (which you should do given your two questions).

> I set total_timesteps in the learn function to 200,000. But it continues to learn beyond 200,000 episodes. Why is that?

> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

https://github.com/DLR-RM/stable-baselines3/issues/1150

**Comment by gowthamnatarajan** [comment]
`env = SubprocVecEnv([lambda: MyEnv(),lambda: MyEnv(),lambda: MyEnv(),lambda: MyEnv()])
model = MaskablePPO('MultiInputPolicy',env,gamma=1,ent_coef=0.005,verbose=1,tensorboard_log=log_path)
best_path = os.path.join('Training', 'Saved_Models')
stop_callback = StopTrainingOnRewardThreshold(reward_threshold=400, verbose=1)
eval_callback = MaskableEvalCallback(env,
                            callback_on_new_best=stop_callback,
                            eval_freq=10,
                            best_model_save_path=best_path,
                            verbose=1)
model.learn(total_timesteps=200000, callback=eval_callback)`

In the above code if I use DummyVecEnv then everything works fine. If I use SubprocVecEnv and no other changes then I get the following error:

`---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
~\anaconda3\lib\multiprocessing\connection.py in _recv_bytes(self, maxsize)
    316                     finally:
--> 317                         nread, err = ov.GetOverlappedResult(True)
    318                         if err == 0:

BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

EOFError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_30260\4201928720.py in <module>
      8                             best_model_save_path=best_path,
      9                             verbose=1)
---> 10 model.learn(total_timesteps=200000, callback=eval_callback)

~\anaconda3\lib\site-packages\sb3_contrib\ppo_mask\ppo_mask.py in learn(self, total_timesteps, callback, log_interval, tb_log_name, reset_num_timesteps, use_masking, progress_bar)
    519 
    520         while self.num_timesteps < total_timesteps:
--> 521             continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, self.n_steps, use_masking)
    522 
    523             if continue_training is False:

~\anaconda3\lib\site-packages\sb3_contrib\ppo_mask\ppo_mask.py in collect_rollouts(self, env, callback, rollout_buffer, n_rollout_steps, use_masking)
    282         rollout_buffer.reset()
    283 
--> 284         if use_masking and not is_masking_supported(env):
    285             raise ValueError("Environment does not support action masking. Consider using ActionMasker wrapper")
    286 

~\anaconda3\lib\site-packages\sb3_contrib\common\maskable\utils.py in is_masking_supported(env)
     31         try:
     32             # TODO: add VecEnv.has_attr()
---> 33             env.get_attr(EXPECTED_METHOD_NAME)
     34             return True
     35         except AttributeError:

~\anaconda3\lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py in get_attr(self, attr_name, indices)
    162         for remote in target_remotes:
    163             remote.send(("get_attr", attr_name))
--> 164         return [remote.recv() for remote in target_remotes]
    165 
    166     def set_attr(self, attr_name: str, value: Any, indices: VecEnvIndices = None) -> None:

~\anaconda3\lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py in <listcomp>(.0)
    162         for remote in target_remotes:
    163             remote.send(("get_attr", attr_name))
--> 164         return [remote.recv() for remote in target_remotes]
    165 
    166     def set_attr(self, attr_name: str, value: Any, indices: VecEnvIndices = None) -> None:

~\anaconda3\lib\multiprocessing\connection.py in recv(self)
    253         self._check_closed()
    254         self._check_readable()
--> 255         buf = self._recv_bytes()
    256         return _ForkingPickler.loads(buf.getbuffer())
    257 

~\anaconda3\lib\multiprocessing\connection.py in _recv_bytes(self, maxsize)
    324                 except OSError as e:
    325                     if e.winerror == _winapi.ERROR_BROKEN_PIPE:
--> 326                         raise EOFError
    327                     else:
    328                         raise

EOFError: `
