### ISSUE TITLE
Use `Sequence` type hint for `VecEnv.seed` return

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/stable-baselines3#1318]
Just for me to remember:

https://github.com/DLR-RM/stable-baselines3/blob/411ff697dde31df9ff914ba0c335875d1bd5998d/stable_baselines3/common/vec_env/base_vec_env.py#L196

Should be typed hinted with `Sequence` instead of `List` as `Sequence` is invariant.

**Comment by araffin** [comment]
I forgot, what was that needed for?

**Comment by qgallouedec** [comment]
I had a hard time remembering this, but the explanation is basically this. List is invariant, which means that an inherited method cannot be more specific in the return type. For example, this is wrong:

```python
from typing import Union, List

class A:
    def func(self) -> List[Union[int, str]]:
        return [1, 2, "3"]

class B(A):
    def func(self) -> List[int]:
        return [1, 2, 3]
```

What we actually want is a covariant form of `List`. It happens to be `Sequence`.

So this is correct:

```python
from typing import Union, Sequence

class A:
    def func(self) -> Sequence[Union[int, str]]:
        return [1, 2, "3"]

class B(A):
    def func(self) -> Sequence[int]:
        return [1, 2, 3]
```

Note that it is the same for `Dict` (also invariant). When used as return type, we'd rather use `Mapping` (covariant).

Wrong:

```python
from typing import Union, Mapping

class A:
    def func(self) -> Dict[str, Union[int, str]]:
        return {"key1": 1, "keys2": "2"}

class B(A):
    def func(self) -> Dict[str, int]:
        return {"key1": 1, "keys2": 2}
```


Good:

```python
from typing import Union, Mapping

class A:
    def func(self) -> Mapping[str, Union[int, str]]:
        return {"key1": 1, "keys2": "2"}

class B(A):
    def func(self) -> Mapping[str, int]:
        return {"key1": 1, "keys2": 2}
```
