### ISSUE TITLE
[Bug]: VecCheckNan with Dict observation space throws exception

### ISSUE THREAD

**Issue by Naton1** [DLR-RM/stable-baselines3#1319]
### 🐛 Bug

Wrapping an environment with VecCheckNan that uses a Dict observation space results in an exception. Stack trace below.

There's no special logic for handling a Dict in https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/vec_env/vec_check_nan.py

### To Reproduce

```python
import gym
import numpy as np
from stable_baselines3.common.vec_env import DummyVecEnv, VecCheckNan


class MyEnv(gym.Env):
    def __init__(self):
        self.observation_space = gym.spaces.Dict(
            test=gym.spaces.Box(low=-np.inf, high=np.inf, shape=(8, 10)),
            test_discrete=gym.spaces.Discrete(2)
        )
        self.action_space = gym.spaces.Discrete(3)

    def reset(self):
        return {'test': np.zeros((8, 10)), 'test_discrete': 1}

    def step(self, action):
        return {'test': np.zeros((8, 10)), 'test_discrete': 1}, 0, False, {}


env = DummyVecEnv([lambda: MyEnv()])
env = VecCheckNan(env)

env.reset()

```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "C:\Users\Nate\rl-ge\rl-ge\repro.py", line 24, in <module>
    env.reset()
  File "C:\Users\Nate\rl-ge\env\lib\site-packages\stable_baselines3\common\vec_env\vec_check_nan.py", line 43, in reset
    self._check_val(event="reset", observations=observations)
  File "C:\Users\Nate\rl-ge\env\lib\site-packages\stable_baselines3\common\vec_env\vec_check_nan.py", line 54, in _check_val
    has_nan = np.any(np.isnan(val))
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### System Info

- OS: Windows-10-10.0.19044-SP0 10.0.19044
- Python: 3.9.16                          
- Stable-Baselines3: 1.7.0                
- PyTorch: 1.13.1+cpu                     
- GPU Enabled: False                      
- Numpy: 1.24.1                           
- Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
hello,
thanks for reporting the bug. `VecCheckNan` should be updated to support dict obs.
I would be happy to receive a PR that solves this issue ;)

**Comment by DavyMorgan** [comment]
I met the same problem. VecCheckNan fails when fed a env with Dict observation.

**Comment by araffin** [comment]
@DavyMorgan thanks =)
I adapted your code in https://github.com/DLR-RM/stable-baselines3/pull/1348

**Comment by DavyMorgan** [comment]
Cool!


> @DavyMorgan thanks =) I adapted your code in #1348
