### ISSUE TITLE
[Bug]: Nested CallbackList due to progress bar ?

### ISSUE THREAD

**Issue by ReHoss** [DLR-RM/stable-baselines3#1322]
### 🐛 Bug

When `progress_bar=True` in `BaseAlgorithm._init_callback`, the following code produce a nested `CallbackList` when `callback` is an instance of `CallbackList`:

```python

        # Add progress bar callback
        if progress_bar:
            callback = CallbackList([callback, ProgressBarCallback()])

        callback.init_callback(self)
        return callback

```

A possible solution:

```python
        if progress_bar:
            # Check if callback is a callback list
            if isinstance(callback, CallbackList):
                # Check if progress bar callback is already present
                if not any(isinstance(cb, ProgressBarCallback) for cb in callback.callbacks):
                    callback.callbacks.append(ProgressBarCallback())
            else:
                callback = CallbackList([callback, ProgressBarCallback()])

```

Not sure if this nested behaviour is intended though, but I don't think so ? It confused me a bit while constructing some callback.
The nicer way would be `CallbackList` to overload `list` methods because update the attribute `callbacks` instead of calling some `CallbackList.append`  led to this kind of situation.

### To Reproduce

Run 

> stable-baselines3/tests/test_callbacks.pystable-baselines3/tests/test_callbacks.py

### System Info

- OS: Linux-5.15.0-58-generic-x86_64-with-glibc2.31 # 64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023
- Python: 3.10.9
- Stable-Baselines3: 1.8.0a4
- PyTorch: 1.13.1+cu117
- GPU Enabled: True
- Numpy: 1.24.2
- Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
apart from the nested structure, does it cause any issue?

**Comment by ReHoss** [comment]
Hello, No I don't think so, just looping twice the CallbackList loop during initializations (which is confusing).

**Comment by araffin** [comment]
> o, No I don't think so, just looping twice the CallbackList loop during initializations (which is confusing).

then, I don't think it is a bug, and the current implementation allows to have a single line for progressbar support (the proposed change look more complex for no real gain).

It might loop twice but I'm pretty sure it is still pretty fast and not a bottleneck compared to gradient update for instance.

**Comment by ReHoss** [comment]
Not a bug, a design flaw.

I don't think the author had in mind `callback` could be an instance of `CallbackList` in this case. Naturally, I was also fooled by the `CallbackList([callback, ProgressBarCallback()])` line.

I also think It is still pretty fast.

However accumulating this kind of  nested `CallbackList` i.e. a `CallbackList` containing a `callback` and a `CallbackList` might lead to future issues, in my opinion.

A simpler modification, where no existence check is performed:

```python

        if progress_bar:
            if isinstance(callback, CallbackList):
                callback.callbacks.append(ProgressBarCallback())
            else:
                callback = CallbackList([callback, ProgressBarCallback()])
```




Thanks for your consideration,

**Comment by araffin** [comment]
> I don't think the author had in mind callback could be an instance of CallbackList

I am the author of that line (and of the callbacks) and I was aware that it could be a `CallbackList` as it is written 5 lines above:
https://github.com/DLR-RM/stable-baselines3/blob/b702884c23b6aeaa5d2a830b37d6b15fb1bdf983/stable_baselines3/common/base_class.py#L354-L356

But this is not a problem, what matters is that is should be of type `BaseCallback` which is the case here.

> A simpler modification, where no progress bar existence check is performed:

yes, this does look slightly better.

As an alternative, you can also directly pass a single level `CallbackList` to the `learn()` (and set `progress_bar=False`) method which contains a `ProgressBarCallback`.
