### ISSUE TITLE
[Question] For SAC, why is the log_std a nn.Parameter and not a network prediction?

### ISSUE THREAD

**Issue by llucid-97** [DLR-RM/stable-baselines3#133]
Hi I'm trying to use this repo as a reference implementation to reproduce [gSDE](https://arxiv.org/abs/2005.05719). In trying to understand some of the code there, I notice it inherits some behavior from your SAC implementation which differs from that of the SAC author's baseline in how it computes the scale of the gaussian samples for the policy:

Yours implements it as a [learned network parameter](https://github.com/DLR-RM/stable-baselines3/blob/3253ee11e7a941946c3a252e63d981d6735df401/stable_baselines3/common/distributions.py#L140) , while the author's treats it as [a prediction of the policy network](https://github.com/rail-berkeley/softlearning/blob/2b55f00f44da177357be3c996a6e94ad0647f565/softlearning/policies/gaussian_policy.py#L259)

Is this a bug, and if not, why the change?
I notice the `TODO` next to it implies you may change it back, and if so would [the gSDE implementation](https://github.com/DLR-RM/stable-baselines3/blob/af0f3a6a957c9b01586f6038978aa6cf02191d68/stable_baselines3/common/distributions.py#L520) follow suite?

**Comment by araffin** [comment]
Hello,

In fact, for SAC, this is the [SquashedDiagGaussianDistribution](https://github.com/DLR-RM/stable-baselines3/blob/3253ee11e7a941946c3a252e63d981d6735df401/stable_baselines3/common/distributions.py#L195):
https://github.com/DLR-RM/stable-baselines3/blob/3253ee11e7a941946c3a252e63d981d6735df401/stable_baselines3/common/distributions.py#L195

which is used by default. The one that you are pointing at is used by PPO/A2C, where the `log_std` is a separate parameter.

The `log_std` is defined here:
https://github.com/DLR-RM/stable-baselines3/blob/3253ee11e7a941946c3a252e63d981d6735df401/stable_baselines3/sac/policies.py#L109

When using gSDE, then this is the [StateDependentNoiseDistribution](https://github.com/DLR-RM/stable-baselines3/blob/3253ee11e7a941946c3a252e63d981d6735df401/stable_baselines3/common/distributions.py#L408)

https://github.com/DLR-RM/stable-baselines3/blob/3253ee11e7a941946c3a252e63d981d6735df401/stable_baselines3/common/distributions.py#L408

which is used. In that case, `log_std` is a learned parameter.

**Comment by llucid-97** [comment]
Ah I see, my mistake. Thanks
