### ISSUE TITLE
[Bug]: Comparison of trained model with another (base) policy

### ISSUE THREAD

**Issue by AvisP** [DLR-RM/stable-baselines3#1331]
### 🐛 Bug

I want to compare a trained model (SAC) with another one ( a base algorithm) and see how it performs on the same episode. However I am having issues with the `evaluate_policy` function on the `BasePolicy`. I have provided a code snippet below on what I am trying to do

### To Reproduce

```import gym
from stable_baselines3 import SAC
from stable_baselines3.common.policies import BasePolicy
from stable_baselines3.common.evaluation import evaluate_policy

env = gym.make("Pendulum-v1")
env.seed(123456)
model = SAC("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=1000, log_interval=4)

reward_list, episode_list = evaluate_policy(model, model.get_env(), n_eval_episodes=10, return_episode_rewards=True)
reward_list_base, episode_list_base = evaluate_policy(BasePolicy, model.get_env(), n_eval_episodes=10, return_episode_rewards=True)
```

I am getting an error on the last line `TypeError: BasePolicy.predict() missing 1 required positional argument: 'self'`. I would like to compare the trained policy with a 'Do Nothing' policy starting from the same initial state.

Additionally, another issue with my example is every time I run the `evaluate_policy` on the trained model, the `reward_list` and `episode_list` changes even though I have fixed the environment seed. This makes it to difficult to compare with another policy on the same episode....

Any help in clarifying my doubts would be appreciated.

### System Info

- OS: macOS-12.6.3-arm64-arm-64bit Darwin Kernel Version 21.6.0
- Python: 3.10.7
- Stable-Baselines3: 1.7.0
- PyTorch: 1.13.0
- GPU Enabled: False
- Numpy: 1.23.4
- Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Could you please clarify what you mean by "base algorithm" or a "do nothing" policy? Do you mean a random policy that uniformly samples actions from the action space?

It's important to note that ùBasePolicyù is not intended to be instantiated. It is an abstract class used to define policies, including `SACPolicy.`

> Additionally, another issue with my example is every time I run the evaluate_policy on the trained model, the reward_list and episode_list changes even though I have fixed the environment seed. This makes it to difficult to compare with another policy on the same episode....

I'm not entirely sure what you did, but the following code seems to work as expected:

```python
from stable_baselines3 import SAC
from stable_baselines3.common.evaluation import evaluate_policy

model = SAC("MlpPolicy", "Pendulum-v1")
model.learn(total_timesteps=1000)

model.get_env().seed(123456)
reward_list, episode_list = evaluate_policy(model, model.get_env(), n_eval_episodes=10, return_episode_rewards=True)
print(reward_list)  # [-1768.334687, -1620.926779, -1825.088246, -1474.156803, -1634.795299, -1467.259359, -1631.170932, -1558.58933, -1594.087609, -1563.714372]

model.get_env().seed(123456)
reward_list, episode_list = evaluate_policy(model, model.get_env(), n_eval_episodes=10, return_episode_rewards=True)
print(reward_list)  # [-1768.334687, -1620.926779, -1825.088246, -1474.156803, -1634.795299, -1467.259359, -1631.170932, -1558.58933, -1594.087609, -1563.714372]
```

**Comment by AvisP** [comment]
Hi Quentin,

Thanks for your prompt response. Looks like setting the seed form `model.get_env().seed(####)` did the trick rather than setting it at env directly and then putting it in model.

Just to clarify in the example below, PPO and SAC are evaluating on episodes starting at same initial conditions

```
from stable_baselines3 import SAC, PPO
from stable_baselines3.common.evaluation import evaluate_policy
import gym

env = gym.make("Pendulum-v1")
model_SAC = SAC("MlpPolicy", env)
model_SAC.learn(total_timesteps=1000)

model_PPO = PPO("MlpPolicy", env)
model_PPO.learn(total_timesteps=1000)

reward_list, episode_list = evaluate_policy(model_SAC, model_SAC.get_env(), n_eval_episodes=10, return_episode_rewards=True)
print(reward_list) # [-1784.899976, -1671.439939, -1833.458721, -1546.365661, -1684.504284, -1527.47969, -1684.933745, -1621.575036, -1650.662881, -1628.004724]

model_PPO.get_env().seed(123456)
reward_list, episode_list = evaluate_policy(model_PPO, model_PPO.get_env(), n_eval_episodes=10, return_episode_rewards=True)
print(reward_list) # [-1346.520891, -1150.922406, -1468.743701, -840.439299, -1164.06083, -818.115843, -1163.052854, -980.374445, -1070.070249, -969.519451]
```

Regarding the other query of 'do nothing' agent, I would like to make an agent that does not take any action and allows the environment to run as long as possible before it finishes on its own. An example with the pendulum environment would be the agent does not try to provide some input to the environment to stabilize it and the episode continues until the pendulum falls down on its own. I tried to look at the example of SAC and design a DoNothing  agent class but it is complicated and I am not an expert in python. If you can provide an example of how to make such an agent that would be awesome! Thanks!

**Comment by qgallouedec** [comment]
> Just to clarify in the example below, PPO and SAC are evaluating on episodes starting at same initial conditions

Yes, but as those two agents don't share the same weights, they take different actions, leading to different episodes and rewards.

"Doing nothing" doesn't necessarily make sense. It depends on the environment. For example, in chess, you can't pass your turn, you can't "do nothing".
In general, we take a so-called "random" agent as a baseline. Here is simple implementation.

```python
import gym
import numpy as np

from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.evaluation import evaluate_policy


class RandomAgent:
    def __init__(self, action_space):
        self.action_space = action_space

    def predict(self, observation, state=None, episode_start=None, deterministic=False):
        n_envs = observation.shape[0]
        return np.array([self.action_space.sample() for _ in range(n_envs)]), None


env = gym.make("Pendulum-v1")
venv = make_vec_env(lambda: env, n_envs=1)
random_agent = RandomAgent(env.action_space)
reward_list, episode_list = evaluate_policy(random_agent, venv, n_eval_episodes=5, return_episode_rewards=True)
print(reward_list)  # [-1373.248515, -1502.797441, -874.854389, -1140.854283, -1512.079468]
```

**Comment by AvisP** [comment]
Thanks for explanation and the example, I think comparing the trained algorithm with a random agent for same episode will be sufficient for my case.
