### ISSUE TITLE
`HERReplayBuffer`: Runtime error The size of tensor a (53) must match the size of tensor b (256) at non-singleton dimension 0

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/stable-baselines3#1337]
Thanks! I set `learning_starts` at 600 as my environment has a time limit of 300. The error mentioned is solved, however, I get the following:

```
sac.py", line 245, in train
target_q_values = replay_data.rewards + (1 - replay_data.dones) * self.gamma * next_q_values
RuntimeError: The size of tensor a (53) must match the size of tensor b (256) at non-singleton dimension 0 
```

_Originally posted by @tudorjnu in https://github.com/DLR-RM/stable-baselines3/issues/1335#issuecomment-1434713057_

**Comment by qgallouedec** [comment]
The problems come from the compute reward method. It has to be vectorized.

```python
def compute_reward(self, achieved_goal, desired_goal, info):
    return np.zeros(achieved_goal.shape[0], np.float32)
```

@araffin I'm pretty sure that this error will occur often. I would add a check in env checker, what do you think?

**Comment by qgallouedec** [comment]
> @araffin I'm pretty sure that this error will occur often. I would add a check in env checker, what do you think?

Let me guess, you're going to tell me it's already done ;)

https://github.com/DLR-RM/stable-baselines3/blob/12e9917c24dc23d7de7694a924f017c6a8e9a6ce/stable_baselines3/common/env_checker.py#L129-L138

**Comment by wilhem** [comment]
> The problem comes from the compute reward method. It has to be vectorized.
> 
> ```python
> def compute_reward(self, achieved_goal, desired_goal, info):
>     return np.zeros(achieved_goal.shape[0], np.float32)
> ```

I got stucked at the same point.
Moving to gymnasium I have to vectorized the `compute_reward` method as expected by SB3.

The problem here is that, since the `achieved_goal `array contains 3 scalars, the resulting reward will be the same value repeated three times, like:

`[0, 0, 0]`

But running the checker it leads to the following error:

```
  File "/home/ubuntu/Downloads/deepbots-env/lib/python3.10/site-packages/stable_baselines3/common/env_checker.py", line 322, in _check_returned_values
    _check_goal_env_compute_reward(obs, env, float(reward), info)
TypeError: only length-1 arrays can be converted to Python scalars
```

How should the reward look like? Expected is a float number (the reward), but due to vectorization, compute_reward will output an array.

**Comment by qgallouedec** [comment]
Yes the reward should be an array. The function should take a batch of achieved/desired rewards and return an array (1 dim) of rewards
