### ISSUE TITLE
[Question] Clarifications on make_atari_env and pre-processing + vectorization

### ISSUE THREAD

**Issue by azr120** [DLR-RM/stable-baselines3#1338]
### ❓ Question

Hello, I'm new to hands-on RL so not sure if this question seems naive. I want to use stable baselines 3's pre-processing and continue with custom code for the agents but I find the documentation a bit confusing. My understanding is that make_atari_env performs all "standard" atari pre-processing (i.e. everything in atari_wrappers) except frame stacking. Is that correct?

So, if I want to also work with vectorized environments, do the following lines suffice to start with:

```
env = make_atari_env("SeaquestNoFrameskip-v4", n_envs=4)
env = VecFrameStack(env, n_stack=4)
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
yes =)
Just note that this env will be a SB3 vec env (see doc for explanation, we will add more soon with #1327 ), not a gym env.

**Comment by azr120** [comment]
Thanks. Does your note refer to how the reset is handled by the env at the end of an episode?

**Comment by araffin** [comment]
> Does your note refer to how the reset is handled by the env at the end of an episode?

yes and everything which is warning and notes from https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html

A more detailed explanation can be found here: https://github.com/DLR-RM/stable-baselines3/pull/1327/files#diff-a0b0c17357564df74e097f3094a5478e9b28b2af9dfdab2a91e60b6dbe174092
