### ISSUE TITLE
Will exploration continuous when I load a saved agent?

### ISSUE THREAD

**Issue by aheidariiiiii1993** [DLR-RM/stable-baselines3#1340]
Hello,

I want to train my agent (QRDQN) in simulation, then save it and load it later to use in an experimental facility. I used a linear decay exploration which is available in this agent (the agent definition is below). So my agent only performs exploration in 30% of the train phase. In the experiment when I load the agent I want it to keep learning BUT without exploration. Once I load my agent (considering that the timestep of the new environment is again 0) will the agent again start exploration? If yes, how should I avoid it? (for experimental phase I will use model.load and then model.learn)

`model = QRDQN('MlpPolicy',
              environment,
              verbose=0,
              buffer_size=168*2*100,
              learning_rate = 0.003,
              learning_starts=1, 
              batch_size=48,
              tau=0.01,
              gamma=0.9,
              train_freq = 1,
              target_update_interval= 1, 
              exploration_fraction = 0.3, 
              exploration_initial_eps = 0.99,
              exploration_final_eps = 0.001,
              device= "auto")`

Thank you

**Comment by araffin** [comment]
Hello,
>  I want it to keep learning BUT without exploration

without any exploration at all? (usually not recommended)
You can set  `exploration_final_eps=0.0` and `exploration_fraction=0.0` when loading the agent (you can give it a quick try, this should do the trick).
Alternatively, you can manually set `model.exploration_schedule = lambda _: 0.0` after loading.

**Comment by aheidariiiiii1993** [comment]
Thank you @araffin for your reply. 
So does it mean that in SB3 I can train my agent with a set of hyper-parameters, save it, and then when I am loading my saved agent I specify different hyper-parameters and continue another round of training?

**Comment by araffin** [comment]
yes, except policy architecture, and for schedule your need to replace the function (there is an issue about lr/clip range schedule in sb3).
