### ISSUE TITLE
[Question] Asteroids Ship not rendering with noframeskip

### ISSUE THREAD

**Issue by harveybellini** [DLR-RM/stable-baselines3#1343]
### ❓ Question

I was trying to render an asteroids environment with the ship in, code is as following:

env = make_atari_env("AsteroidsNoFrameskip-v4", n_envs=1, seed=0)
env = VecFrameStack(env, n_stack=1)
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

Which produces the Gif below, with no asteroid ship on it. What am I missing?

![lander_a2c](https://user-images.githubusercontent.com/19893000/220611613-9bd3db00-f5d9-4dc0-b147-4e9adee2d5c6.gif)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
It's due to frameskip (`make_atari_env` has it's own frame skip, 4 frames by default, see the doc). The ship is rendered every 2 frames. Run this code to get the intuition of how it works:

```python
import time

from stable_baselines3.common.env_util import make_atari_env

env = make_atari_env("AsteroidsNoFrameskip-v4", n_envs=1, wrapper_kwargs=dict(frame_skip=1))

obs = env.reset()
while True:
    obs, reward, done, info = env.step([env.action_space.sample()])
    env.render()
    if done:
        obs = env.reset()
    time.sleep(1.0)
```

So, if you set `frame_skip=4`, the ship is never rendered.
However, since the observation is the maxpool of the most recent two frames (see the doc), the ship actually part of the observation.

**Comment by harveybellini** [comment]
Cheers
