### ISSUE TITLE
[Question] A question about continuous action space and discrete action space .

### ISSUE THREAD

**Issue by Natmat626** [DLR-RM/stable-baselines3#1344]
### ❓ Question

Why do I feed a single model with the same input value, its output value is not fixed? Whether the action space of this model is discrete or continuous.
I am a novice in the RL, please solve my doubts. thanks very much!! 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Policies are not deterministic by default. See the doc: https://stable-baselines3.readthedocs.io/en/master/_modules/stable_baselines3/common/policies.html
The agent outputs a distribution and then sample from it.

**Comment by Natmat626** [comment]
@qgallouedec  Thanks  ,my question was sloved
