### ISSUE TITLE
How to make ONNX model of the network with CNN-MLP Multi Input policy?

### ISSUE THREAD

**Issue by DoHyun-Chun** [DLR-RM/stable-baselines3#1349]
### ❓ Question

I am interested in using stable-baselines to train an agent, and then export it through ONNX.

So, I made my code as following:
```python
model = PPO.load('Normal_best.zip', env=env)
onnxable_model = OnnxablePolicy.OnnxablePolicy(model.policy.features_extractor, model.policy.action_net, model.policy.value_net, model)
dummy_inputs = {k: th.randn(1, *obs.shape) for k, obs in model.observation_space.items()}
th.onnx.export(
    onnxable_model,
    (dummy_inputs, {}),
    "my_multiPolicy.onnx",
    opset_version=9,
    input_names=["input"],
)
```

and 
```python

class OnnxablePolicy(th.nn.Module):
    def __init__(self, extractor, action_net, value_net, model):
        super(OnnxablePolicy, self).__init__()
        self.extractor = extractor
        self.action_net = action_net
        self.value_net = value_net
        self.model = model

    def forward(self, observation):
        # NOTE: You may have to process (normalize) observation in the correct
        #       way before using this. See `common.preprocessing.preprocess_obs`
        action_hidden, value_hidden = self.extractor(observation)
        return self.action_net(action_hidden), self.value_net(value_hidden)
```

However, I got a error, 
    line 16, in forward
    action_hidden, value_hidden = self.extractor(observation)
ValueError: not enough values to unpack (expected 2, got 1)

How can I fix this?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
the answer is both in the error and in the code.

>  ValueError: not enough values to unpack (expected 2, got 1)

When using CNN, the features extractor is shared by default, so you need to do `action_hidden = value_hidden = self.extractor(observation)` as a single value and not a tuple is returned.
And if you are using discrete actions, you will need to take the argmax (or sample) as `action_net()` will return the logits (it does return the action in case of continuous actions).

For more details, you can read:
https://github.com/DLR-RM/stable-baselines3/blob/085bdd5a68be7748e62ca710162f16ac7b62ddfc/stable_baselines3/common/policies.py#L628-L651

and 
https://github.com/DLR-RM/stable-baselines3/blob/085bdd5a68be7748e62ca710162f16ac7b62ddfc/stable_baselines3/common/policies.py#L590-L612

**Comment by araffin** [comment]
Btw, if you are using PyTorch 2.0 (preview) and ONNX opset 14+, this seems to work (for deterministic policy):

Tagging @Gregwar as the solution is quite simple and works with both MLP/CNN, and with PPO/SAC (and probably the rest =)).

```python
import torch as th

from stable_baselines3 import PPO


class OnnxablePolicyPyTorch2(th.nn.Module):
    def __init__(self, policy):
        super().__init__()
        self.policy = policy

    def forward(self, observation):
        # NOTE: You may have to process (normalize) observation in the correct
        #       way before using this. See `common.preprocessing.preprocess_obs`
        return self.policy(observation, deterministic=True)


# Example: model = PPO("MlpPolicy", "Pendulum-v1")
PPO("MlpPolicy", "Pendulum-v1").save("PathToTrainedModel")
model = PPO.load("PathToTrainedModel.zip", device="cpu")

onnx_pytorch2 = OnnxablePolicyPyTorch2(model.policy)

observation_size = model.observation_space.shape
dummy_input = th.randn(1, *observation_size)
th.onnx.export(
    onnx_pytorch2,
    dummy_input,
    "my_ppo_model.onnx",
    opset_version=17,
    input_names=["input"],
)

##### Load and test with onnx

import onnx
import onnxruntime as ort
import numpy as np

onnx_path = "my_ppo_model.onnx"
onnx_model = onnx.load(onnx_path)
onnx.checker.check_model(onnx_model)

observation = np.zeros((1, *observation_size)).astype(np.float32)
ort_sess = ort.InferenceSession(onnx_path)
actions, values, log_prob = ort_sess.run(None, {"input": observation})

print(actions, values, log_prob)

with th.no_grad():
    print(model.policy(th.as_tensor(observation), deterministic=True))

```

**Comment by Gregwar** [comment]
Including pre processing in ONNX itself seems like the good way to go indeed!

Another thing that would be a nice addition is a way to export the value functions as (we use them in inference as well so that we can compare different policies online for instance), so far we use some similar custom script specific to TD3 but I think it could be extended to other policies and documented

**Comment by GppCalcagno** [comment]
> Btw, if you are using PyTorch 2.0 (preview) and ONNX opset 14+, this seems to work (for deterministic and stochastic policy):
> 
> Tagging @Gregwar as the solution is quite simple and works with both MLP/CNN, and with PPO/SAC (and probably the rest =)), and includes pre-processing too!
> 
> ```python
> import torch as th
> 
> from stable_baselines3 import PPO
> 
> 
> class OnnxablePolicyPyTorch2(th.nn.Module):
>     def __init__(self, policy):
>         super().__init__()
>         self.policy = policy
> 
>     def forward(self, observation):
>         # NOTE: Preprocessing is included, the only thing you need to do
>         # is transpose the images if needed so that they are channel first
>         # use deterministic=False if you want to export the stochastic policy
>         return self.policy(observation, deterministic=True)
> 
> 
> # Example: model = PPO("MlpPolicy", "Pendulum-v1")
> PPO("MlpPolicy", "Pendulum-v1").save("PathToTrainedModel")
> model = PPO.load("PathToTrainedModel.zip", device="cpu")
> 
> onnx_pytorch2 = OnnxablePolicyPyTorch2(model.policy)
> 
> observation_size = model.observation_space.shape
> dummy_input = th.randn(1, *observation_size)
> th.onnx.export(
>     onnx_pytorch2,
>     dummy_input,
>     "my_ppo_model.onnx",
>     opset_version=17,
>     input_names=["input"],
> )
> 

this works for me too (PPO with CNN policy). It would be nice if this snippet could be added to the current documentation: https://stable-baselines3.readthedocs.io/en/master/guide/export.htmls

**Comment by araffin** [comment]
> this works for me too (PPO with CNN policy). It would be nice if this snippet could be added to the current documentation: https://stable-baselines3.readthedocs.io/en/master/guide/export.htmls

Feel free to submit a PR =)
