### ISSUE TITLE
[Bug] Separate feature extractor for target network (SAC/TD3)

### ISSUE THREAD

**Issue by araffin** [DLR-RM/stable-baselines3#135]
Same issue as in https://github.com/DLR-RM/stable-baselines3/pull/132
but for SAC/TD3.
It would need special treatment as it would be beneficial to still share the feature extractor between actor and critic to speedup things.

**Comment by Miffyli** [comment]
I _think_ the fix here is just remove the feature-extractor parameters from the list of update-able parameters. I can recall reading somewhere in docs that only the policy updates feature extractor, which is then shared with rest of the networks.

**Comment by PartiallyTyped** [comment]
Not sure about the original SAC paper, but iirc in RAD and CURL the gradients are propagated from the critics.
