### ISSUE TITLE
[Question] How to modify progress bar using set_postfix?

### ISSUE THREAD

**Issue by gameveloster** [DLR-RM/stable-baselines3#1350]
### ❓ Question

When `progress_bar=True` is passed into `model.learn()`, a `tqdm` progress bar is shown throughout training.

Is it possible to add more metrics to the progress bar using `set_postfix`? Maybe if we can access the progress bar instance from a callback, we can call its `set_postfix` method.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> Is it possible to add more metrics to the progress bar using set_postfix? Maybe if we can access the progress bar instance from a callback, we can call its set_postfix method.

what kind of metrics would you like to log?
The logger is not enough for you?

Otherwise, best is to have a custom callback (cf. doc), you can start from the progress bar one.

**Comment by gameveloster** [comment]
I'll like to add to the progress bar one of the metric that I am already logging to tensorboard, just for convenience. Will try out using a custom callback, thanks
