### ISSUE TITLE
[Feature Request] Fixing TimeLimit Handling for On-Policy algorithm

### ISSUE THREAD

**Issue by shuishida** [DLR-RM/stable-baselines3#1355]
### 🚀 Feature

Instead of the temporary fix implemented in #658 which alters the rewards in the process, distinguish the `dones` due to visiting terminal states and `dones` due to timeout when the GAE is calculated.

### Motivation

The TimeLimit/Infinite Horizon Handling implemented in #658 fixes the problem of not differentiating between dones caused by timeout and due to termination by offsetting the rewards upon timeout by the estimated next value. However, as mentioned in #633 (which is the issue that motivated #658), this is a rather hacky approach to fixing the problem. 

The biggest problem with this approach is that the rewards become sometimes very large due to this offset. Since the rewards no longer follow the rewards that are generated by the MDP, it would be difficult to integrate this with a model-based approach or any other method that relies on the true rewards.

Removing the fix by #658 is also not an option since I have confirmed that that will degrade the performance of the On-Policy algorithms. Instead, I propose a simple solution of having another flag `terminals` for all the `dones` that are NOT due to timeouts, and using these to evaluate the GAE.

### Pitch

Replace 
https://github.com/DLR-RM/stable-baselines3/blob/ed8783cb738136d89feb55e5fe373528513231c8/stable_baselines3/common/on_policy_algorithm.py#L192-L203

with the following:

```
terminals = np.zeros_like(dones)
for idx, done in enumerate(dones):
    if done and not infos[idx].get("TimeLimit.truncated", False):
        terminals[idx] = 1.0

rollout_buffer.add(self._last_obs, actions, rewards, self._last_episode_starts, terminals, values, log_probs)
```

and in the `RolloutBuffer` and `DictRolloutBuffer`, store these `terminals` in addition to `episode_starts`.
Then modify the GAE calculation step at 
https://github.com/DLR-RM/stable-baselines3/blob/ed8783cb738136d89feb55e5fe373528513231c8/stable_baselines3/common/buffers.py#L391-L397
to use these `terminals` instead of `dones`

```
            next_non_terminal = 1.0 - self.terminals[step]
            if step == self.buffer_size - 1:
                next_values = last_values
            else:
                next_values = self.values[step + 1]
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment]
Hello,

> Since the rewards no longer follow the rewards that are generated by the MDP, it would be difficult to integrate this with a model-based approach or any other method that relies on the true rewards.

Could you elaborate on which model based method you are thinking of?
The current code is for on-policy only, I don't expect it to be used by model-based approach.
The off-policy algorithms have the timeout saved in the replay buffer and should be easier to use with model-based approaches.

> with the following:

I'll try to have a closer look at it in the coming days (my stack is already quite full right now).

**Comment by shuishida** [comment]
I am adapting PPO to work with skill-based RL, which also has problems with this implementation of modifying rewards. I believe that a proper implementation would make the algorithm more extendible and show good implementation practice.

**Comment by shuishida** [comment]
Ah sorry, I realise that you'd also have to compute and store the next_value explicitly in the buffer (as `self.values[step + 1]` will be from a different episode), so the modification, although doable, might be a little bigger than what I have described above.

**Comment by shuishida** [comment]
After some consideration I think your way of dealing with the issue is probably sufficient for the majority of cases and it will add more complexity to change it. Even though keeping track of the next values and the terminal signal would be a more precise way of dealing with it, since it works as it is (unless one needs to use model-based or skill-based approaches), I'm happy to leave it as it is and maybe suggest this issue as a footnote if anyone wants to modify it for their own use case.
