### ISSUE TITLE
Does Callback affect training?

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1360]
### ❓ Question

I am curious about the callback functions that could be used to track the learning progress of an agent for certain time intervals. Do these have any affect on our policy? Does the agent use the reward signal to update the policy?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
I assume you are talking about the `EvalCallback`?
You should use a separate env for it.

If so, the answers to your questions are:

>  Do these have any affect on our policy? 

no, evaluation should not influence training.

> Does the agent use the reward signal to update the policy?

no.

**Comment by anilkurkcu** [comment]
Great!
