### ISSUE TITLE
[Question] is it possible to train a model and determine the reward of the action after the end of the episode?

### ISSUE THREAD

**Issue by JavierDiazM** [DLR-RM/stable-baselines3#1370]
### ❓ Question

Hello everyone

I am trying to undertand how to create a custom gym env and train a model where the reward of every step can only determined at the end of the episode

is there any similar example that I can check?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
I’m not aware of such environment. What about returning 0 reward, except for the last timestep ?

**Comment by araffin** [comment]
> What about returning 0 reward, except for the last timestep ?

You could also (in a very hacky way) rewrite the replay buffer, but anyway, it sounds like you are breaking Markov assumption if the reward at every step can be determined only at the end.

**Comment by ReHoss** [comment]
> > What about returning 0 reward, except for the last timestep ?
> 
> You could also (in a very hacky way) rewrite the replay buffer, but anyway, it sounds like you are breaking Markov assumption if the reward at every step can be determined only at the end.


The reward is only a function of a transition in the trajectory induced by the policy and the environment transition probability.

![image](https://user-images.githubusercontent.com/41160498/224060506-716d52d2-53ab-43c4-9b0e-54c26b81d3d7.png)

If the policy (conditional distribution) is Markovian (depend only on the last state) the trajectory obtained is a Markov process.

![image](https://user-images.githubusercontent.com/41160498/224060941-5b0501f4-f592-47ba-8ea9-6e322ab8cb76.png)


For PODMP, the above does not hold anymore.


In Monte Carlo RL, you can imagine sampling without reward and afterwards evaluate your policy on different kind of optimisation loss (determined by the reward).

If the reward is zero except being function of the last **state**, it's fine as pointed out by @qgallouedec.

However, if the final reward is a function of the whole trajectory, then as @araffin pointed out, the Bellman optimality theorem is not satisfied anymore and many techniques cannot be used.


see: O. Hernández-Lerma, J-B. Lasserre - Discrete-Time Markov Control Processes Basic Optimality Criteria (1996)

**Comment by qgallouedec** [comment]
> However, if the final reward is a function of the whole trajectory, then as @araffin pointed out, the Bellman optimality theorem is not satisfied anymore and many techniques cannot be used.

I didn't read the whole paper, but it seems to me that it talks about this "final reward" only for the cost function, and not for the reward calculation, right?
From what I understand, this final reward is not much special, it's just that the authors need a different notation because it can't depend on the action (because there is no action at the end). Correct me if I have misunderstood something.

**Comment by ReHoss** [comment]
> From what I understand, this final reward is not much special, it's just that the authors need a different notation because it can't depend on the action (because there is no action at the end). Correct me if I have misunderstood something.

yes I agree with you it is just a matter of notation to highlight the fact it does not depend on the last action. You can even  consider c(x_N) = c(x_N, a) for any action a and incorporate it into the sum.

Globally I am just saying:
- If you consider the reward being zero except at the last time step T (like task/goal oriented RL).
- The reward function must be a function of x_T (what I call the last state) and not a function of the whole trajectory (x_0, a_0, ... x_T)

I am answering to **the reward of every step can only determined at the end of the episode** from the author of the issue.

> I didn't read the whole paper, but it seems to me that it talks about this "final reward" only for the cost function, and not for the reward calculation, right?

However, from my point of view the choice of a reward function fully determine the cost function here. I recall the goal of RL is to find the distribution of action which optimise the loss, the loss being a sum of reward functions.

**Comment by qgallouedec** [comment]
> If you consider the reward being zero except at the last time step T (like task/goal oriented RL).

In goal-oriented RL, the reward is usually +1 (or whatever value) as soon as the task is completed. The agent usually doesn’t  need to wait until the last timestep to get the reward.

> The reward function must be a function only of x_T (what I call the last state) and not a function of the whole trajectory (x_0, a_0, ... x_T)

We consider all environments as POMDP. (That’s why we use « obs » and not « state ». Note that sometime, the environment is fortunately fully observable.
Anyway, as spotted by @araffin, the strong assumption is about the Markov property. The transition distribution (and the reward) must only depend on the past, and cannot depend on any future state, (hence including the last state). 

> However, from my point of view the choice of a reward function fully determine the cost function here.

The cost function is fully determined by the policy, and the MDP (that includes the transition probabilities, the reward distribution, and the initial state distribution)

> So fixing a distribution pi, you can evaluate many rewards function if you record the data. 

technically yes, but why would you do that? The goal is to find the best policy given the reward function, not the opposite.

> And I guess Offline-RL use this property?

what property? Offline RL method do not overwrite the rewards.

**Comment by ReHoss** [comment]
> > If you consider the reward being zero except at the last time step T (like task/goal oriented RL).
> 
> In goal-oriented RL, the reward is usually +1 (or whatever value) as soon as the task is completed. The agent usually doesn’t need to wait until the last timestep to get the reward.

Ok ok, goal-oriented RL is a subset of MDP with reward zero everywhere except the last random time step. That's what I wanted to say.


> 
> > The reward function must be a function only of x_T (what I call the last state) and not a function of the whole trajectory (x_0, a_0, ... x_T)
> 
> We consider all environments as POMDP. (That’s why we use « obs » and not « state »). Note that sometime, the environment is fortunately fully observable. Anyway, as spotted by @araffin, the strong assumption is about the Markov property.
> The transition distribution (and the reward) must only depend on the past, and cannot depend on any future state, (hence including the last state).

Yes sure.

> 
> > However, from my point of view the choice of a reward function fully determine the cost function here.
> 
> The cost function is fully determined by the policy, and the MDP (that includes the transition probabilities, the reward distribution, and the initial state distribution)

Yes sure, I forgot to mention the policy as in the formula I linked.

> 
> > So fixing a distribution pi, you can evaluate many rewards function if you record the data.
> 
> technically yes, but why would you do that? The goal is to find the best policy given the reward function, not the opposite.
> 
> > And I guess Offline-RL use this property?
> 
> what property? Offline RL methods do not overwrite the rewards.

**Comment by qgallouedec** [comment]
> I think we misunderstand: in the case of @JavierDiazM, if he wants something where "the reward of every step can only determined at the end of the episode". 

To conclude on this specific question, the short answer would be:
You probably don't want to do this, because it violates the Markov property. But if that's really what you want to do, use a callback triggered at the end of each episode to override the reward in the buffer.


[the rest is a bit off-topic]

> Ok ok, goal-oriented RL is a subset of MDP with reward zero everywhere except the last random time step. That's what I wanted to say.

Goal-oriented RL is just when the observation contains some "goal" representation. 
- It does not imply that the episode stops when the goal is achieved (see `Fetch*` and `Panda*` environments).
- It does not imply that the reward is given in the last timestep (it can be [0, 0, 0, 1, 1, 1, 1] if the episode lasts 7 timesteps, and if the goal is reached from t=3).
- It does not implies that the reward is either 0 or 1. For example, in `PandaReachDense-v1`, the reward is the opposite of the current distance and the target position.

Overall, I think that goal-conditioned environment is not a relevant example here.

> The only legal way is to use the last state, not the information from the beginning.

Yes. 
Note that if the DP is markovian, then the "information from the beginning" must be somehow contained in the current state.

--

For the rest, yes, there are advanced uses that "flip" the problem, you have explained it very well.

**Comment by ReHoss** [comment]
Thank @qgallouedec I wanted to edit my answer to summarise but you did it perfectly:)! (and you're right my definition of Goal oriented-RL is poor!)

**Comment by JavierDiazM** [comment]
> > What about returning 0 reward, except for the last timestep ?
> 
> You could also (in a very hacky way) rewrite the replay buffer, but anyway, it sounds like you are breaking Markov assumption if the reward at every step can be determined only at the end.

Oh intresting, yes it could be a very hacky way, since my objetive is to only replace the reward of some specific action steps on the past, so I can either modify the replay buffer or modify my gym_env and add aditional steps with revised observations and rewards, but the actions are not only deterministic but also are the same actions from the past.

my gym has 3 discrete actions

action=0, always return reward = 0
and the reward for action=1 depends of action=2

We do not know by the data contained on the observation if action=1 is good or bad, we have to wait until action=2 has been triggered so the reward/punishment is calculated and shared for both actions.

yes sorry looks like I am violating the Markov property, sorry

if I trigger a callback at the end of the episode, does the replay buffer contain information of the whole episode?

**Comment by qgallouedec** [comment]
> We do not know by the data contained on the observation if action=1 is good or bad, we have to wait until action=2 has been triggered so the reward/punishment is calculated and shared for both actions. 

The reward must therefore be triggered after action 2. Don't rewrite on the previous interaction. 


> yes sorry looks like I am violating the Markov property, sorry

It's not about being sorry. The problem is that all RL algorithms are based on this assumption and it is very likely that your algorithm will completely fail to learn anything if you don't respect it.
Besides, I think in your case, you just don't understand the formalism very well, and you probably confuse the value of an action with the reward the action yields.

**Comment by JavierDiazM** [comment]
> > We do not know by the data contained on the observation if action=1 is good or bad, we have to wait until action=2 has been triggered so the reward/punishment is calculated and shared for both actions.
> 
> The reward must therefore be triggered after action 2. Don't rewrite on the previous interaction.
> 

I see, I see...

So I was thinking about a modification on the gym so that when  action=2 is triggered at t=n, I calculate the corresponding reward for both actions, return the observation and reward for action=2 and, then, on the next step, replay previous action=1, it's observation data and it's corresponding corrected reward on t=n-a1, then also replay t=n-a1+1 with reward=0, and then continue on step t+1. 

in this case, I will have to ignore any action given for these two replayed observations

does it sound crazy?
am I breaking more stuff here???

> > yes sorry looks like I am violating the Markov property, sorry
> 
> It's not about being sorry. The problem is that all RL algorithms are based on this assumption and it is very likely that your algorithm will completely fail to learn anything if you don't respect it. Besides, I think in your case, you just don't understand the formalism very well, and you probably confuse the value of an action with the reward the action yields.

that is also true

**Comment by qgallouedec** [comment]
Why not simply return all your rewards after action 2?

**Comment by JavierDiazM** [comment]
> Why not simply return all your rewards after action 2?

but I do not undertand how, I think it is important to reward action=1 as well, not only action=2, but action=1 was triggered some steps in the relative past of action=2

**Comment by qgallouedec** [comment]
If action 1 is taken at timestep 2 and action 2 at timestep 5, just reward both at timestep 5

**Comment by JavierDiazM** [comment]
> If action 1 is taken at timestep 2 and action 2 at timestep 5, just reward both at timestep 5

Ok, I am going to try that approach, thank you very mucho
