### ISSUE TITLE
[Bug]: loading DQN changes target_update_interval

### ISSUE THREAD

**Issue by todbeibrot** [DLR-RM/stable-baselines3#1373]
### 🐛 Bug

when loading a DQN model, target_update_interval gets divided by n_envs. So saving and loading a DQN model changes target_update_interval.

in dqn, line 160:
self.target_update_interval = max(self.target_update_interval // self.n_envs, 1)

### To Reproduce

```
import gym
from stable_baselines3 import DQN
from stable_baselines3.common.vec_env import DummyVecEnv

env = DummyVecEnv([lambda: gym.make("CartPole-v1") for _ in range(4)])
model = DQN("MlpPolicy", env, verbose=1)

for _ in range(5):
    print(model.target_update_interval)
    model.save("dqn_cartpole")
    del model
    model = DQN.load("dqn_cartpole")
```

### Relevant log output / Error message

```shell
2500
625
156
39
9
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
thanks for spotting the bug =)
i would happy to receive a PR that solves it.

**Comment by tobirohrer** [comment]
I think the cause of this bug lies in the function `_setup_model()` in `dqn/dqn.py`:

When the model is set up, the target update interval is updated by:

`self.target_update_interval = max(self.target_update_interval // self.n_envs, 1)`

A possible solution could be to calculate the target update interval per environment in every step (inside the `_on_step()` function)

I can create a PR in the coming days.

**Comment by araffin** [comment]
> A possible solution could be to calculate the target update interval per environment in every step (inside the _on_step() function)

a better solution would be to avoid overriding the variable and keep the original target network update interval somewhere.
