### ISSUE TITLE
[Question] Weird things happening with log distributions

### ISSUE THREAD

**Issue by danibt656** [DLR-RM/stable-baselines3#1385]
### ❓ Question

I'm implementing a sort-of curriculum learning module in SB3. I have a custom `ActorCriticPolicy` that uses its own Linear module as action_net. This is because I need to have multiple action nets depending on the different action spaces that the curriculum handles (I have already figured that part out). The action nets have all this form:

```
self.action_net_collection = [
            nn.Linear(self.mlp_extractor.latent_dim_pi, env.action_space.n)
            for env in env_collection.envs
        ]
```

Where env_collection is a collection of environments (again, this is not that relevant for my question).

Notice that I don't include any hardcoded activation function, just the Linear module from PyTorch.

This is the custom policy overall (it inherits `ActorCriticPolicy`):

```
CollectionActorCriticPolicy(
  (features_extractor): FeatureExtractorCollection()
  (pi_features_extractor): FeatureExtractorCollection()
  (vf_features_extractor): FeatureExtractorCollection()
  (mlp_extractor): CollectionMlpExtractor(
    (policy_net): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
    )
    (value_net): Sequential(
      (0): Linear(in_features=64, out_features=64, bias=True)
      (1): ReLU()
    )
  )
  (action_net): Linear(in_features=64, out_features=6, bias=True)
  (value_net): Linear(in_features=64, out_features=1, bias=True)
)
```

And so during the `forward()` method of this policy, I pass the current observation through all the action_nets stored in `self.action_net_collection`, saving the outputs (`actions, values & log_prob`). Then a mask tensor is used to extract the actual output tuple corresponding to the actual environment the agent is training.

```
...
outputs = []
for net_idx in range(self.num_extractors):
    self.change_nets(net_idx)
    actions, values, log_prob = super(CollectionActorCriticPolicy, self).forward({ 'observation': curr_obs, 'mask': masks }, deterministic)
    outputs.append((actions, values, log_prob))

# select & return the appropiate output based on the mask
actions, values, log_prob = outputs[torch.nonzero(masks, as_tuple=True)[1][0]]
return actions, values, log_prob
```

When I run my agent, it crashes and gives this error:

`*** ValueError: Expected value argument (Tensor of shape (5,)) to be within the support (IntegerInterval(lower_bound=0, upper_bound=5)) of the distribution Categorical(logits: torch.Size([5, 6])), but found invalid values:
tensor([ 0,  5,  0,  2, 13])`

I have cloned this function to my code so I can debug it, and it appears that the error is in the line with `log_prob = distribution.log_prob(actions)`:

```
def evaluate_actions(self, obs: torch.Tensor, actions: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, Optional[torch.Tensor]]:
        features = self.extract_features(obs)
        if self.share_features_extractor:
            latent_pi, latent_vf = self.mlp_extractor(features)
        else:
            pi_features, vf_features = features
            latent_pi = self.mlp_extractor.forward_actor(pi_features)
            latent_vf = self.mlp_extractor.forward_critic(vf_features)
        distribution = self._get_action_dist_from_latent(latent_pi)
        log_prob = distribution.log_prob(actions)
        values = self.value_net(latent_vf)
        entropy = distribution.entropy()
        return values, log_prob, entropy
```

It appears as the `actions` tensor has shape [5] because of the batch_size (so one action per element of batch).

I think it may be caused by SB3 assigning a distribution to my action space that doesn't correlate to what my custom action net expects. So maybe some kind of activation function between action_net and the distribution is the problem?

Anyone has any help regarding this issue?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> It appears as the actions tensor has shape [5] because of the batch_size (so one action per element of batch).
> *** ValueError: Expected value argument (Tensor of shape (5,)) to be within the support (IntegerInterval(lower_bound=0, upper_bound=5)) of the distribution Categorical(logits: torch.Size([5, 6])), but found invalid values: tensor([ 0,  5,  0,  2, 13])

The error is not complaining about the shape but the value: one of the action has value 13 instead of being between [0, 5] (as stated by the error).

**Comment by danibt656** [comment]
I see, thanks for pointing that out! But even in that case I don't see why I am getting the error.

**Comment by danibt656** [comment]
@araffin I think the root cause is the action nets not actually learning from the environments .When does exactly the action_net perform backpropagation/gradient descent? If I could tackle that method, maybe I could trace back where my problem arises.

**Comment by araffin** [comment]
> I think the root cause is the action nets not actually learning from the environments 

It doesn't look like so, if the actions contains the value 13 (which is out of range for a discrete space with 6 actions), it has nothing to do with learning.

As stated in the issue template/readme, we don't do tech support (we do points to alternative to seek for such kind of help).
Since the bug doesn't seem to come from SB3 but from custom code/env, I will close this issue.
