### ISSUE TITLE
[Question] Consecutive frames for custom environment

### ISSUE THREAD

**Issue by Liuzy0908** [DLR-RM/stable-baselines3#1386]
### ❓ Question

Hi, I'm using stable-baselines3 to train the my custom environment. The input to the algorithm is the image, and I want to use consecutive 4 frames of the image as the input to the network, so what do I do? (Vectorized environment or other methods?)

Is there an API in stable-baselines3 that supports this?

>My ideas:
>For RL algorithms that have a replaybuffer (e.g. DQN,DDPG), my idea is to store 4 consecutive frames into the buffer to train. 
>For RL algorithms without a replaybuffer (e.g. PPO), I don't have a good idea yet.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hi, [VecFrameStack](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html#vecframestack) is probably what you are looking for.

**Comment by Liuzy0908** [comment]
> Hi, [VecFrameStack](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html#vecframestack) is probably what you are looking for.

Thank you for your answer. If I want to turn a custom environment (e.g. AirSim, Carla environment) into a vectorized environment, does the custom environment class need to inherit from the gym.Env and the stable_baselines3.common.vec_env.VecEnv class? 

Are there any examples of custom environments being changed to vectorized environments?

**Comment by araffin** [comment]
> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

**Comment by Liuzy0908** [comment]
> > I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

I am ashamed that I didn't read the previous issue carefully. Now that I have found a solution and put it here, I hope it will be helpful to others.

```python
from stable_baselines3.common.vec_env import VecFrameStack, DummyVecEnv

class CustomEnv(gym.Env)
    ...


venv = DummyVecEnv([lambda:CustomEnv()])    # single env at a time. no parallel.
env = VecFrameStack(venv, n_stack=4)        # Network input: 4 consecutive frames


class CustomCNN(BaseFeaturesExtractor):
    def __init__(self, observation_space: spaces.Box, features_dim: int = 256):
        super().__init__(observation_space, features_dim)
        self.observation_space = observation_space
        n_input_channels = observation_space.shape[0]
        self.cnn = nn.Sequential(
            nn.Conv2d(n_input_channels, 32, kernel_size=8, stride=4, padding=0),
            ...


policy_kwargs = dict(
    features_extractor_class=CustomCNN,
    features_extractor_kwargs=dict(features_dim=128),
)

print("env_shape: ", venv.observation_space.shape)
print("model_architecture: ")
print(model.policy)
```
Out:
```python
env_shape:  (144, 256, 3)
model_architecture: 
ActorCriticCnnPolicy(
  (features_extractor): NatureCNN(
    (cnn): Sequential(
      (0): Conv2d(12, 32, kernel_size=(8, 8), stride=(4, 4))
      ...
```

My environment observation is (144, 256, 3), and the model automatically calculates the observation_space.shape[0] in CustomCNN is 3*4=12. That means success.
