### ISSUE TITLE
Is the source code of gymnasium 0.28.0 available?

### ISSUE THREAD

**Issue by bertanimre** [DLR-RM/stable-baselines3#1388]
### ❓ Question

Hello!

I want to modify (the action space and the reward) an existing gymnasium environment (CartPole-v2) and use an SB3 algorithm (PPO) on it. Probably this is not the best way to do it, but I copied the source code from the gymnasium repository (v0.27.1) to make the modifications. Even if SB3 works with the code, the learning and testing processes weren't appropriate.

When I installed "pip install git+https://github.com/DLR-RM/stable-baselines3@feat/gymnasium-support" to use SB3 on gymnasium, I saw that the version was 0.28.0. So I thought you might have made minor changes to the current gymnasium version. Is it possible to access the source code of the version you created? I can use the version to make the modifications.

Thanks in advance!

Best regards,
Bertan

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
if you look at the PR #1327 , we are simply using the main branch: https://github.com/DLR-RM/stable-baselines3/blob/5328921b58d11904b9c5a6352987751af607ddcd/setup.py#L106

**Comment by bertanimre** [comment]
Thank you for the quick response!

The reason for my problem was that "Truncation: Episode length is greater than 500 (200 for v0)" wasn't applied explicitly in the code. The TimeLimit wrapper solved the problem (https://github.com/Farama-Foundation/Gymnasium/issues/393).

The people who want to modify the existing gymnasium environments from the source code must utilize the wrappers.

Best regards,
Bertan
