### ISSUE TITLE
Pre_Train in Stablebaselines3

### ISSUE THREAD

**Issue by alisonjpp** [DLR-RM/stable-baselines3#139]
Is there a `pre_train` function in PPO of stablebaselines3? There is one in stablebaseline. If not, how to pretrain?

**Comment by araffin** [comment]
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/27

We should probably add the link to the notebook in the doc though.

**Comment by alisonjpp** [comment]
THX for the quick reply!  sorry i did't check issues carefully!
