### ISSUE TITLE
[Bug]: DictRolloutBuffer doesn't reshape action

### ISSUE THREAD

**Issue by younik** [DLR-RM/stable-baselines3#1392]
### 🐛 Bug

DictRolloutBuffer doesn't reshape action in `add` method, making multi-dimensional action space fail to save due to shape mismatch.

### To Reproduce

```python
from stable_baselines3 import PPO
import gym

class MyEnv(gym.Env):
    def __init__(self):
        self.action_space = gym.spaces.Box(-1, 1, shape=(10, 10))
        self.observation_space = gym.spaces.Dict({
            "foo": gym.spaces.Box(-1, 1, shape=(1,)),
            "foo2": gym.spaces.Box(-1, 1, shape=(1,))
        })

    def reset(self):
        return self.observation_space.sample()
    
    def step(self, action):
        return self.observation_space.sample(), 0, False, {}

env = MyEnv()
model = PPO("MultiInputPolicy", env)
model.learn(1000)
```

### Relevant log output / Error message

```shell
/usr/local/lib/python3.9/dist-packages/stable_baselines3/common/buffers.py in add(self, obs, action, reward, episode_start, value, log_prob)
    735             self.observations[key][self.pos] = obs_
    736 
--> 737         self.actions[self.pos] = np.array(action).copy()
    738         self.rewards[self.pos] = np.array(reward).copy()
    739         self.episode_starts[self.pos] = np.array(episode_start).copy()

ValueError: could not broadcast input array from shape (10,10) into shape (1,100)
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
thanks for spotting the bug, I would be happy to receive a PR that fixes it ;)

Btw, for the proposed env, it would be better (and faster) to flatten the observation dict to a single 1D vector.

**Comment by araffin** [comment]
>  thanks for spotting the bug, I would be happy to receive a PR that fixes it ;)

PS: if you do so, please don't use master branch for your fork, that would prevent maintainers to push edits to it.

**Comment by younik** [comment]
> > thanks for spotting the bug, I would be happy to receive a PR that fixes it ;)
> 
> PS: if you do so, please don't use master branch for your fork, that would prevent maintainers to push edits to it.

Ops, I just did it; I can close it and use another branch
