### ISSUE TITLE
[Question] Can models trained on multiple instances of an environment with multiprocessing predict on a single instance of that environment?

### ISSUE THREAD

**Issue by RobertHua96** [DLR-RM/stable-baselines3#1398]
### ❓ Question

Hi there, I understand we can stack environments for model training. For inference, if I only need to predict on an instance of that environment, is that possible?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
yes
