### ISSUE TITLE
Issue during training

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1401]
### ❓ Question

I am getting this error message when using SAC always at approx. 180000 time step:

ValueError: Expected parameter loc (Tensor of shape (1, 50)) of distribution Normal(loc: torch.Size([1, 50]), scale: torch.Size([1, 50])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan]], device='cuda:3')

Any advice?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hi, we need more information to answer you. I suggest you to use the bug report template instead. Unless you are using a custom env, then use the custom env template.
