### ISSUE TITLE
[Feature Request] Upgrade or add PyTorch Profiler TensorBoard plugin to >= 0.2.0 to avoid VsCode warning

### ISSUE THREAD

**Issue by FieteO** [DLR-RM/stable-baselines3#1409]
### 🚀 Feature

When launching the Tensorboard plugin via `Python: Launch TensorBoard` in VsCode, there will be a warning dialog raised by the Python Extension:
```
We recommend installing version >= 0.2.0 of the PyTorch Profiler TensorBoard plugin. Would you like to install the package?
```
When selecting yes, it will install the `torch-tb-profiler` dependency in it's latest version. I am not sure if this dependency is newly added to the project or upgrading it to a newer version.
However it would be cool if this project could bundle an up-to-date version of that dependency, such that this warning will not be shown.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment]
>  However it would be cool if this project could bundle an up-to-date version of that dependency, such that this warning will not be shown.

SB3 doesn't depend on `torch-tb-profiler` and we don't set upper limit for pytorch or tensorboard  versions:
https://github.com/DLR-RM/stable-baselines3/blob/470771b5c2142f0813b6bb1afb9143c960bf09a0/setup.py#L79-L80

**Comment by FieteO** [comment]
So this request doesn't make much sense, does it?
