### ISSUE TITLE
[Question] Access policy network as torch module directly

### ISSUE THREAD

**Issue by BeFranke** [DLR-RM/stable-baselines3#1411]
### ❓ Question

Is it possible to extract the raw policy network as a torch module from a PPO-object?
And the reverse case would also interest me, if I have a trained MLP, can I simply set it as the policy network of PPO (and, for example, train it further?)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
`model.policy` is a `nn.Module`.

**Comment by BeFranke** [comment]
Ah, I see. Thank you.
Is it safe to assign model.policy e.g. with another torch-based MLP?
