### ISSUE TITLE
[Question] Constant weights in training

### ISSUE THREAD

**Issue by jens-t94** [DLR-RM/stable-baselines3#1412]
### ❓ Question

Hi!

I am training an agent with the PPO algorithm on a custom environment.
When training, I keep track of the parameters of the agent.

The weights of the agent (especially those of the features extractor and those of the mlp extractor) do not change at all over training. They follow a normal distribution and visually, they do not change at all.  The bias values from all layers do change, however.
The only changing weights I could find are the ones from the action_net and the ones from the value_net.

Here is an example of the mlp extractor that does not change its weights.
![image](https://user-images.githubusercontent.com/129055134/227914001-9690eede-e511-446c-bfed-a99151de1376.png)

I wonder if this is intentional or if something might be wrong in my code.

The dict observation is normalized with the VecNormalize wrapper for non-image box spaces.
The episode rewards improve however, as expected.

Thanks for your help.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Closing as the issue template for custom environment was not followed (minimal code to reproduce the error is missing).
