### ISSUE TITLE
Action output of 0.0

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1413]
### ❓ Question

I am using SAC as my algorithm during training. I am wondering whether the agent is able to learn to apply null actions. By null actions what I mean is the ones that are 0.0, so when added to a joint, they have no effect at all. And if even though this is theoretically possible, is it very difficult for an agent to learn to output actions of value 0.0 with SAC? I would be assuming continuous action space in range [-1, +1].

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by anilkurkcu** [comment]
So you would suggest using the magnitude of the action taken in the reward function in such a way that e.g. if action is far away from 0.0 the reward given drops?

**Comment by araffin** [comment]
> So you would suggest using the magnitude of the action taken in the reward function in such a way that e.g. if action is far away from 0.0 the reward given drops?

yes if it makes sense for your problem, you can also reduce the action space to make it easier to output zeros (see https://www.youtube.com/watch?v=d874o2rgxXs&t=987s or https://www.youtube.com/watch?v=ngK33h00iBE&list=PL42jkf1t1F7dFXE7f0VTeFLhW0ZEQ4XJV for an example).

**Comment by anilkurkcu** [comment]
Thanks for the links, will check them out.

As a follow up to your previous comment, is it necessary to input the last action taken to the state-space as well?

**Comment by araffin** [comment]
> As a follow up to your previous comment, is it necessary to input the last action taken to the state-space as well?

Only if you use it for the reward/behavior (for instance using a low-pass filter or a continuity cost).
