### ISSUE TITLE
[Feature Request] serializable custom methods

### ISSUE THREAD

**Issue by WreckItTim** [DLR-RM/stable-baselines3#1417]
### 🚀 Feature

I would like to redefine the train() method for my TD3 model. I am making a slight adjustment to the built-in train() method. For my purposes, it can't be accomplished with a callback, because I am adding functionality within each batch iteration. 

I was able to overwrite the train() method fine, such as:
`
td3model.train = functools.partial(new_train, td3model)
`

However, it throws this error when trying to save the model: "TypeError: cannot pickle 'select.epoll' object"

A work around is to set the train method to None before calling save(), then to reset it after. However in general, I think being able to customize functions that are still serializable would be beneficial. I also could not find the cause of the select.epoll error, so maybe I am just doing something wrong?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment]
> I would like to redefine the train() method for my TD3 model. I am making a slight adjustment to the built-in train() method. For my purposes, it can't be accomplished with a callback, because I am adding functionality within each batch iteration.

I'm not sure what you are doing and why you are doing that but you should probably fork SB3/create a subclass for your use-case.

> I was able to overwrite the train() method fine, such as:
td3model.train = functools.partial(new_train, td3model)

You can have another example here: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/rl_zoo3/callbacks.py#L150
