### ISSUE TITLE
[Bug]: Bug Regarding Masks

### ISSUE THREAD

**Issue by DBUSA** [DLR-RM/stable-baselines3#1418]
### 🐛 Bug

In the global variables I read and write from an excel sheet of knapsack values for the integral knapsack problem. All of the values in the global variables I use are positive integers representing weights, values, capacity and the optimal value of each instance i. 

This error occurs randomly when I try to use optuna to optimize the parameters and I am not sure why.  I have provided the parameters that caused this error along with the code to reproduce. All items in knapsack are integers ranging from 0-999 so I do not think this is the issue so I have not included it.  Each trial finds the mean of the same 2000 items from the global variables so I do not think they are the problem or the program would have thrown an error on the first trial. I believe changing the parameters is what causes the error as nothing is changed in any of the trials except for the values of the parameters 

I am unsure if I have made the range for the trials too large but that would be my first guess as to what is wrong. I am a college student and just beginning to use sb3 so if I have made a mistake and this is not a bug I apologize. 

Additionally I have included system information along with a way to recreate the conda env I am utilizing. 

### To Reproduce

```python

def make_env():
    env = KnapsackEnv(N=300, mask=True)
    env = ActionMasker(env,mask_fn)
    return env

#stable baselines action mask function
def mask_fn(env: gym.Env) -> np.ndarray:
    return env.state["action_mask"]
   
def return_mean_sync(model, trials, N):
    #values for knapsack 
    global train_item_values_300
    global train_item_weights_300
    global train_item_capacity_300
    global train_item_optimal_300
    rewards = []
    for i in range(trials):
        reward = run_trial(model, train_item_values_300[i], train_item_weights_300[i], train_item_capacity_300[i], N, train_item_optimal_300[i])
        rewards.append(reward)
    mean_rew = sum(rewards) / trials
    return mean_rew
def run_trial(model, item_values, item_weights, item_capacity, N,optimal):
    env = KnapsackEnv(N=N, mask=True, item_values=item_values, item_weights=item_weights, Index=1, max_weight=item_capacity,max_reward = optimal)
    env = ActionMasker(env, mask_fn)
    obs = env.reset()
    capacity = env.max_weight
    model_chosen = []
    reward = 0
    while True:
        action_masks = get_action_masks(env)
        action, _states = model.predict(obs, action_masks=action_masks)
        obs, rewards, dones, info = env.step(action)
        model_chosen.append(action.tolist())
        reward = reward + rewards
        if dones == True:
            break
    return reward
def objective(trial):
 #various trails for variables
    # n_lay = trial.suggest_int('n_lay', 1,5)
    # layer_size = trial.suggest_int("layer_size", 32, 256,log=True)
    vf_coef = trial.suggest_float('vf_coef', 0.1, .99)
    n_env = trial.suggest_int('n_env',4,32)
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-3,log=True)
    gae_lambda = trial.suggest_float('gae_lambda', 0.1, 0.99)
    clip_range = trial.suggest_float('clip_range', .1,.3)
    n_steps = trial.suggest_int('n_steps',8,256)
    n_epochs = trial.suggest_int('n_epochs', 1, 10)
    batch_size = trial.suggest_categorical('batch_size', [16, 32, 64, 128])
    timesteps = trial.suggest_int('timesteps',1000,200000)

    #Setting up Model for Eval
    n_envs = n_env
    my_vec_env = make_vec_env(make_env, n_envs=n_envs)
    policy_kwargs = {'activation_fn':torch.nn.ReLU,
                     'net_arch': {'pi':[128]*2, 'vf':[128] * 2}}
    trail_mod = MaskablePPO(policy=MaskableMultiInputActorCriticPolicy,batch_size=batch_size,vf_coef=vf_coef,learning_rate=learning_rate,n_epochs=n_epochs,n_steps=n_steps,gae_lambda=gae_lambda,device='cuda',env=my_vec_env)
    trail_mod.learn(total_timesteps=timesteps,use_masking=True)
    mean = return_mean_sync(trail_mod,2000,300)
    return  mean


#produces error
study1 = optuna.create_study(direction='maximize',sampler=TPESampler())
study1.optimize(objective, n_trials= 500,show_progress_bar = True)

```

### Relevant log output / Error message

```shell
[W 2023-03-29 19:29:53,981] Trial 76 failed with parameters: {'vf_coef': 0.8731076861326909, 'n_env': 29, 'learning_rate': 0.0001606186482373522, 'gae_lambda': 0.395629650712754, 'n_steps': 53, 'n_epochs': 9, 'batch_size': 16, 'timesteps': 182588} because of the following error: ValueError("Expected parameter logits (Tensor of shape (16, 300)) of distribution MaskableCategorical(logits: torch.Size([16, 300])) to satisfy the constraint IndependentConstraint(Real(), 1), but found invalid values:\ntensor([[nan, nan, nan,  ..., nan, nan, nan],\n        [nan, nan, nan,  ..., nan, nan, nan],\n        [nan, nan, nan,  ..., nan, nan, nan],\n        ...,\n        [nan, nan, nan,  ..., nan, nan, nan],\n        [nan, nan, nan,  ..., nan, nan, nan],\n        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',\n       grad_fn=<SubBackward0>)").
Traceback (most recent call last):

ValueError: Expected parameter logits (Tensor of shape (16, 300)) of distribution MaskableCategorical(logits: torch.Size([16, 300])) to satisfy the constraint IndependentConstraint(Real(), 1), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<SubBackward0>)
```

### System Info

# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/win-64/ca-certificates-2023.01.10-haa95532_0.conda
https://conda.anaconda.org/nvidia/win-64/cuda-cccl-12.1.55-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/cuda-cudart-11.8.89-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/cuda-cupti-11.8.87-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/cuda-nvrtc-11.8.89-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/cuda-nvtx-11.8.86-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/cuda-profiler-api-12.1.55-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2021.4.0-haa95532_3556.conda
https://conda.anaconda.org/nvidia/win-64/libcublas-11.11.3.6-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libcufft-10.9.0.58-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libcurand-10.3.2.56-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libcusolver-11.4.1.48-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libcusparse-11.7.5.86-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libnpp-11.8.0.86-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libnvjpeg-11.9.0.86-0.tar.bz2
https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2022g-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.27.29016-h5e58377_2.conda
https://repo.anaconda.com/pkgs/main/win-64/winpty-0.4.3-4.conda
https://conda.anaconda.org/nvidia/win-64/cuda-cudart-dev-11.8.89-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/cuda-libraries-11.8.0-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/cuda-nvrtc-dev-11.8.89-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libcublas-dev-11.11.3.6-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libcufft-dev-10.9.0.58-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libcurand-dev-10.3.2.56-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libcusolver-dev-11.4.1.48-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libcusparse-dev-11.7.5.86-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libnpp-dev-11.8.0.86-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/libnvjpeg-dev-11.9.0.86-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-2021.4.0-haa95532_640.conda
https://repo.anaconda.com/pkgs/main/win-64/vc-14.2-h21ff451_1.conda
https://conda.anaconda.org/nvidia/win-64/cuda-libraries-dev-11.8.0-0.tar.bz2
https://conda.anaconda.org/nvidia/win-64/cuda-runtime-11.8.0-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/giflib-5.2.1-h8cc25b3_3.conda
https://repo.anaconda.com/pkgs/main/win-64/jpeg-9e-h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/lerc-3.0-hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libdeflate-1.17-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libiconv-1.16-h2bbff1b_2.conda
https://repo.anaconda.com/pkgs/main/win-64/libsodium-1.0.18-h62dcd97_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libuv-1.44.2-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libwebp-base-1.2.4-h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/lz4-c-1.9.4-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/openssl-1.1.1t-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.41.1-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tk-8.6.12-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/xz-5.2.10-h8cc25b3_1.conda
https://repo.anaconda.com/pkgs/main/win-64/zlib-1.2.13-h8cc25b3_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libpng-1.6.39-h8cc25b3_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libxml2-2.9.14-h0ad7f3c_0.conda
https://repo.anaconda.com/pkgs/main/win-64/python-3.9.16-h6244533_2.conda
https://conda.anaconda.org/pytorch/win-64/pytorch-cuda-11.8-h24eeafa_3.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/zeromq-4.3.4-hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/zstd-1.5.2-h19a0ad4_0.conda
https://repo.anaconda.com/pkgs/main/win-64/attrs-22.1.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/certifi-2022.12.7-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/colorama-0.4.6-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/debugpy-1.5.1-py39hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.7.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/entrypoints-0.4-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/executing-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/filelock-3.9.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/flit-core-3.8.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/freetype-2.12.1-ha860e81_0.conda
https://repo.anaconda.com/pkgs/main/win-64/idna-3.4-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ipython_genutils-0.2.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/win-64/joblib-1.1.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/json5-0.9.6-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libtiff-4.5.0-h6c2663c_2.conda
https://repo.anaconda.com/pkgs/main/win-64/libxslt-1.1.35-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/markupsafe-2.1.1-py39h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mistune-0.8.4-py39h2bbff1b_1000.conda
https://repo.anaconda.com/pkgs/main/win-64/mpmath-1.2.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/nest-asyncio-1.5.6-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/networkx-2.8.4-py39haa95532_1.conda
https://repo.anaconda.com/pkgs/main/win-64/packaging-23.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pandocfilters-1.5.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/parso-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pickleshare-0.7.5-pyhd3eb1b0_1003.conda
https://repo.anaconda.com/pkgs/main/win-64/platformdirs-2.5.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/prometheus_client-0.14.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/psutil-5.9.0-py39h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pure_eval-0.2.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pygments-2.11.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyrsistent-0.18.0-py39h196d8e1_0.conda
https://repo.anaconda.com/pkgs/main/win-64/python-fastjsonschema-2.16.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pytz-2022.7-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pywin32-305-py39h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pywinpty-2.0.10-py39h5da7b33_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyzmq-23.2.0-py39hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/noarch/send2trash-1.8.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/win-64/sniffio-1.2.0-py39haa95532_1.conda
https://repo.anaconda.com/pkgs/main/win-64/soupsieve-2.3.2.post1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tomli-2.0.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tornado-6.2-py39h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/traitlets-5.7.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/webencodings-0.5.1-py39haa95532_1.conda
https://repo.anaconda.com/pkgs/main/win-64/wheel-0.38.4-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/win_inet_pton-1.1.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/wincertstore-0.2-py39haa95532_2.conda
https://repo.anaconda.com/pkgs/main/win-64/zipp-3.11.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/anyio-3.5.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/asttokens-2.0.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/babel-2.11.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/beautifulsoup4-4.11.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/bleach-4.1.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/cffi-1.15.1-py39h2bbff1b_3.conda
https://repo.anaconda.com/pkgs/main/win-64/comm-0.1.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/importlib-metadata-6.0.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jedi-0.18.1-py39haa95532_1.conda
https://repo.anaconda.com/pkgs/main/win-64/jinja2-3.1.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jsonschema-4.17.3-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyter_core-5.2.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyterlab_pygments-0.1.2-py_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libwebp-1.2.4-hbc33d0d_1.conda
https://repo.anaconda.com/pkgs/main/win-64/lxml-4.9.1-py39h1985fb9_0.conda
https://repo.anaconda.com/pkgs/main/win-64/matplotlib-inline-0.1.6-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl-service-2.4.0-py39h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/prompt-toolkit-3.0.36-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pysocks-1.7.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/setuptools-65.6.3-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/sympy-1.11.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/terminado-0.17.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tinycss2-1.2.1-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/typing_extensions-4.4.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/websocket-client-0.58.0-py39haa95532_4.conda
https://repo.anaconda.com/pkgs/main/win-64/argon2-cffi-bindings-21.2.0-py39h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/brotlipy-0.7.0-py39h2bbff1b_1003.conda
https://repo.anaconda.com/pkgs/main/win-64/cryptography-39.0.1-py39h21b164f_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyter_client-7.4.9-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/nbformat-5.7.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.23.5-py39h4da318b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pillow-9.4.0-py39hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pip-23.0.1-py39haa95532_0.conda
https://conda.anaconda.org/pytorch/win-64/pytorch-2.0.0-py3.9_cuda11.8_cudnn8_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/stack_data-0.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/typing-extensions-4.4.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/argon2-cffi-21.3.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/ipython-8.10.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/nbclient-0.5.13-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyopenssl-23.0.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/ipykernel-6.19.2-py39hd4e2768_0.conda
https://repo.anaconda.com/pkgs/main/win-64/nbconvert-6.5.4-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/urllib3-1.26.14-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyter_server-1.23.4-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/requests-2.28.1-py39haa95532_1.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyterlab_server-2.19.0-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/notebook-shim-0.2.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/nbclassic-0.5.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/notebook-6.5.2-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/jupyterlab-3.5.3-py39haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_fft-1.3.1-py39h277e83a_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_random-1.2.2-py39hf11a4ad_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.23.5-py39h3b20f71_0.conda
https://conda.anaconda.org/pytorch/win-64/torchaudio-2.0.0-py39_cu118.tar.bz2
https://conda.anaconda.org/pytorch/win-64/torchvision-0.15.0-py39_cu118.tar.bz2

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

Probably duplicate of https://github.com/DLR-RM/rl-baselines3-zoo/issues/156#issuecomment-910097343 and https://github.com/DLR-RM/stable-baselines3/issues/1401

**Comment by DBUSA** [comment]
It looks like it thank you for your help.

**Comment by vahidqo** [comment]
Hi @DBUSA,

Could you solve the problem? I'm facing the same problem.
If you did, could you please explain how you did it?

Thanks
