### ISSUE TITLE
[feature request] Channels-first environments without extra transpose wrapper

### ISSUE THREAD

**Issue by qxcv** [DLR-RM/stable-baselines3#142]
At present, image-based environments are automatically wrapped in a `VecTranspose` wrapper when they are passed to a policy. Likewise, observations passed to `policy.predict()` are automatically transposed so that the last channel appears first. This adds a bit of unnecessary overhead when working with channels-first environments: users need to wrap such environments in a special wrapper that puts channels last. The wrapper is then "undone" by `VecTranspose`, yielding the original (correct) observation. It would be nice if there was some way to support channels-first environments without two unnecessary transposes.

One way of fixing this would be to simply assume that environments are channels-first; environments that are not channels-first can be wrapped in a `VecTranspose` wrapper before being passed to an RL algorithm. This has a few advantages:

- It simplifies the behaviour of the code slightly, removing surprises like #103 and eliminating the need for transpose-aware checks like the one in `common.utils.check_for_correct_spaces()`
- It removes unnecessary overhead for channels-first environments
- It makes it easier for other libraries to interoperate with SB3 policies. For example, `imitation` trains SB3 policies using behavioural cloning, but that requires all of `imitation` to be aware of the heuristics that SB3 uses to decide whether to transpose images.

I've made a draft PR that does this in #143.

**Comment by qxcv** [comment]
I created a draft PR (#143) with my proposed approach (that is, changing SB to assume channels come first).

**Comment by Miffyli** [comment]
Generally I agree with this proposal: `VecTranspose` happens bit too often in bit too many places around the code to be a clean solution. However since channels-first is not a common convention (e.g. PIL and OpenCV treat images as channels-last), I think it will be a common mistake to feed in channels-last observations. The code should still sanity-check, even in BaseClass, if the first dimension is larger than last dimension. I will check the code more in depth next week when I am back on main machine.

@araffin 
I think we discussed this same at one point and you had some further arguments for the current behaviour?

**Comment by araffin** [comment]
https://github.com/DLR-RM/stable-baselines3/pull/35#issuecomment-636331838

**Comment by araffin** [comment]
>One way of fixing this would be to simply assume that environments are channels-first; environments

Is there an easy way to check if an environment is channel first?

I would avoid assuming that an env is channel first as this would break many code (gym env are channel last by default and tutorials also show this behavior) but I agree that it would simplify greatly our codebase.

As a compromise, if we can easily detect if an env is channel-first/last, then I would wrap the channel last ones automatically if needed.

**Comment by Miffyli** [comment]
> I would avoid assuming that an env is channel first as this would break many code (gym env are channel last by default and tutorials also show this behavior) but I agree that it would simplify greatly our codebase.

I agree. I suggested on PR side (very convenient to have discussion in two places :') ) that the code could check if first axis has less dimensions than the last one and warn/raise exception accordingly. This should work in most cases but should still be documented in big orange boxes in the documentation.
