### ISSUE TITLE
AssertionError: `reset()` must return a tuple (obs, info)

### ISSUE THREAD

**Issue by iswarm** [DLR-RM/stable-baselines3#1422]
### 🐛 Bug

In sb3 document, 

def reset(self):         
    observation = np.random.rand(60, 22)         
    return observation  # **_reward, done, info can't be included_**

However, 

    AssertionError: `reset()` must return a tuple (obs, info) when check_env(env) using stable_baselines3.common.env_checker

How should I correct that?

### Code example

```python
import gym
import numpy as np
from gym import spaces

from stable_baselines3 import A2C
from stable_baselines3.common.env_checker import check_env


class CustomEnv(gym.Env):

    def __init__(self):
        super().__init__()
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(14,))
        self.action_space = spaces.Box(low=-1, high=1, shape=(6,))

    def reset(self):
        return self.observation_space.sample()

    def step(self, action):
        obs = self.observation_space.sample()
        reward = 1.0
        done = False
        info = {}
        return obs, reward, done, info

env = CustomEnv()
check_env(env)

model = A2C("MlpPolicy", env, verbose=1).learn(1000)
```

### Relevant log output / Error message

when executing the "check_env(env)":

AssertionError: reset() must return a tuple (obs, info)

if return self.observation_space.sample(), {}, then the return value of the reset function is inconsistent with the observation space type.

_No response_

### System Info

Jupyter notebook in Colab 

Runtime with GPU

_No response_

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
It’s probably related to your gym version. Please fill the issue template completely, especially the system info section.

**Comment by iswarm** [comment]
System Info： colab jupyter notebook

# Test the agent
obs = env.reset()
for i in range(100):
    #action, _states = model.predict(obs)
    action = env.action_space.sample()
    obs, rewards, dones, info = env.step(action)
    if dones:
        break
    env.render()

It passed when checked using a random agent.

**Comment by araffin** [comment]
> System Info： colab jupyter notebook

please read and follow the instructions of the issue template

**Comment by araffin** [comment]
the template is here: https://github.com/DLR-RM/stable-baselines3/blob/master/.github/ISSUE_TEMPLATE/custom_env.yml
