### ISSUE TITLE
[Bug]: model.predict couldn't read obs value (LunalLander-v2 | gym 0.26)

### ISSUE THREAD

**Issue by adicahyanto** [DLR-RM/stable-baselines3#1427]
### 🐛 Bug

training, saving and loading model upon gym LunarLander-v2 shows no problem.

when trying to put the model to work and predict based on obs value, an error showed up as follow:
ValueError: Error: Unexpected observation shape (2,) for Box environment, please use (8,) or (n_env, 8) for the observation shape. 

### To Reproduce

#the commented out line below are used for training and saving model
import gym
import stable_baselines3
import os
import torch as th
import numpy as np
from stable_baselines3 import PPO

env = gym.make("LunarLander-v2"
               ,render_mode="human"
               )
env.reset()

#-------------------------------------------------------------------------
models_dir = "models/PPO_1"
# logdir = "logs"

# if not os.path.exists(models_dir):
#     os.makedirs(models_dir)
# if not os.path.exists(logdir):
#     os.makedirs(logdir)
#-------------------------------------------------------------------------
# policy_kwargs = dict(activation_fn=th.nn.ReLU,
#                     net_arch=dict(pi=[128, 64, 32], vf=[128, 64, 32]))
# model = PPO("MlpPolicy", env, policy_kwargs=policy_kwargs, verbose=1, tensorboard_log=logdir)
#-------------------------------------------------------------------------
# TIMESTEPS = 10000
# for i in range (1,10):
#     model.learn(total_timesteps=TIMESTEPS, reset_num_timesteps=False, tb_log_name='PPO_1')
#     model.save(f"{models_dir}/{TIMESTEPS*i}")
#-------------------------------------------------------------------------
model_path = f"{models_dir}/90000.zip"
model = PPO.load(model_path,env=env)
#-------------------------------------------------------------------------

for step in range (10):
    env.render()
    obs = env.reset()
    score = 0
    terminated = False
    truncated = False
    while not (terminated or truncated):
        env.render()
        action, _ = model.predict(obs)
        obs, reward, terminated, truncated, info = env.step(action)
        # obs, reward, terminated, truncated, info = env.step(env.action_space.sample())
        score += reward
    print(step, " | ", score)

env.close()

### Relevant log output / Error message

```shell
PS D:\Works\moonlander_sentdex> & C:/Users/adica/anaconda3/python.exe d:/Works/moonlander_sentdex/moonlander_load.py
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
C:\Users\adica\anaconda3\lib\site-packages\stable_baselines3\common\policies.py:239: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  observation = np.array(observation)
Traceback (most recent call last):
  File "d:\Works\moonlander_sentdex\moonlander_load.py", line 50, in <module>
    action, _ = model.predict(obs)
  File "C:\Users\adica\anaconda3\lib\site-packages\stable_baselines3\common\base_class.py", line 539, in predict
    return self.policy.predict(observation, state, episode_start, deterministic)
  File "C:\Users\adica\anaconda3\lib\site-packages\stable_baselines3\common\policies.py", line 328, in predict
    observation, vectorized_env = self.obs_to_tensor(observation)
  File "C:\Users\adica\anaconda3\lib\site-packages\stable_baselines3\common\policies.py", line 243, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
  File "C:\Users\adica\anaconda3\lib\site-packages\stable_baselines3\common\utils.py", line 399, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)
  File "C:\Users\adica\anaconda3\lib\site-packages\stable_baselines3\common\utils.py", line 266, in is_vectorized_box_observation
    raise ValueError(
ValueError: Error: Unexpected observation shape (2,) for Box environment, please use (8,) or (n_env, 8) for the observation shape.
```

### System Info

- OS: Windows-10-10.0.19044-SP0 10.0.19044
- Python: 3.9.13
- Stable-Baselines3: 2.0.0a0
- PyTorch: 2.0.0+cpu
- GPU Enabled: False
- Numpy: 1.21.5
- Gym: 0.26.2

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

when you tick a box, please only do it when you followed the instruction...

you should also probably be using https://github.com/DLR-RM/stable-baselines3/pull/1327
it support gym 0.21/0.26 and gymnasium.

**Comment by araffin** [comment]
you are also using gym 0.21 api but with gym 0.26, so it won't work... please read gym 0.26/Gymnasium examples to see the new api.

**Comment by adicahyanto** [comment]
> > I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.
> 
> when you tick a box, please only do it when you followed the instruction...
> 
> you should also probably be using #1327 it support gym 0.21/0.26 and gymnasium.

i'm sorry for that.

i've try installing #1327 as you mentioned above, but the problem still exist (in gym).
i've also try to move to gymnasium, with gymnasium, i rerun the train and reload the new model to test, and the problem also exist in here as well.

**Comment by araffin** [comment]
`obs = env.reset()` is your issue, reset returns a tuple

**Comment by adicahyanto** [comment]
yes, it's looks like was the cause.

change the code from 
"""
obs = env.reset()
"""
to
"""
obs, _ = env.reset()
"""

solving the problem.
sorry for the trouble and thanks for pointing out where did i miss.
