### ISSUE TITLE
what are the activations used in actor and critic network in stable baselines3 implementation for DDPG,PPO and SAC?

### ISSUE THREAD

**Issue by muk465** [DLR-RM/stable-baselines3#1429]
### ❓ Question

I want to know activations used in neural nets of actor and critics of 
1)DDPG
2)PPO
3)SAC

I am using default networks of the above algorithms,generally relu is used for first layer in both and tanh in last layer of actor and linear ;layer in critic ,is that also the case here?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
yes.
related to https://github.com/DLR-RM/stable-baselines3/issues/1005#issuecomment-1212749119
