### ISSUE TITLE
[Question] Continuous action scalling in on policy algorithms

### ISSUE THREAD

**Issue by TakieddineSOUALHI** [DLR-RM/stable-baselines3#1430]
### ❓ Question

Hi, I have a question about continuous action scalling for on policy algorithms and the way it is done in collect_rollouts() function.  The scalled actions are used to step the environnemnt while in the rollout buffer, it is the unscalled actions that are added. Why not add the clipped actions directly to the rollout buffer? Is there a particular reason to not do so ? 

`
clipped_actions = np.clip(actions, self.action_space.low, self.action_space.high)
new_obs, rewards, dones, infos = env.step(clipped_actions)`

And 

`   
  rollout_buffer.add(self._last_obs, actions, rewards, self._last_episode_starts, values, log_probs)
`

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by TakieddineSOUALHI** [comment]
> > I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
> 
> Probably a duplicate of [#1269 (comment)](https://github.com/DLR-RM/stable-baselines3/issues/1269#issuecomment-1422604490)

Thank you for your reply. In the case of PPO for example, the output is not squashed with tanh() function which makes it possible for the clipped actions can be largely different than those stored in the rollout buffer. Does it make sense to train with actions different than those executed? (from a forward dynamics point of view)

**Comment by araffin** [comment]
> Thank you for your reply. In the case of PPO for example, the output is not squashed with tanh() function which makes it possible for the clipped actions to be largely different than those stored in the rollout buffer. Does it make sense to train with actions different than those executed? (from a forward dynamics point of view)

https://github.com/DLR-RM/stable-baselines3/issues/1431#issuecomment-1496050612
