### ISSUE TITLE
[Bug]: VecFrameStack or rather StackedDictObservations reuses same instance of Dict

### ISSUE THREAD

**Issue by WeberSamuel** [DLR-RM/stable-baselines3#1435]
### 🐛 Bug

If using ``VecFrameStack`` with a dictionary as observation, the ``StackedDictObservation.update`` method updates the stored observation dictionary inplace.
Since ``VecFrameStack`` does not return a copy of the observation (which is not necessary if observation is not a dictionary), this will lead to observation and next_observation in the replay buffer to be equal. Which is obviously wrong.

Solution would be to check in VecFrameStack if Dict is used and make a deepcopy of it, or alternatively modify StackedDictObservation.update to update the new observation dictionary instead of the cached one. 

### To Reproduce

```python
from stable_baselines3.common.vec_env import VecFrameStack, VecEnvWrapper, DummyVecEnv
from gym import make, spaces

class DictVecCartPole(VecEnvWrapper):
    def __init__(self):
        venv = DummyVecEnv([lambda: make("CartPole-v1")])
        obs_space = spaces.Dict({"observation": venv.observation_space})
        super().__init__(venv, observation_space=obs_space)

    def step_wait(self):
        obs, rewards, dones, infos = self.venv.step_wait()
        return {"observation": obs}, rewards, dones, infos
    
    def reset(self):
        return {"observation": self.venv.reset()}
    
env = VecFrameStack(DictVecCartPole(), 3)
last_obs = env.reset()
print("This will be cached by OffPolicyAlgorithm and after next step stored in replay buffer:")
print(last_obs)

next_obs, *_ = env.step([env.action_space.sample()])
print("However the value changed due to reuse of dict in StackedDictObservations.update. Value is now:")
print(last_obs)
print("And new obs is also")
print(next_obs)
print("Therefore replay buffer will have always next_obs == last_obs")
print(next_obs == last_obs)

```

### Output of bug reproduction above
This will be cached by OffPolicyAlgorithm and after next step stored in replay buffer:
``{'observation': array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.03595876,  0.00990718,
        -0.00592437, -0.00838598]], dtype=float32)}``
However the value changed due to reuse of dict in StackedDictObservations.update. Value is now:
``{'observation': array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.03595876,
         0.00990718, -0.00592437, -0.00838598,  0.0361569 ,  0.20511359,
        -0.00609209, -0.3029322 ]], dtype=float32)}``
And new obs is also
``{'observation': array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.03595876,
         0.00990718, -0.00592437, -0.00838598,  0.0361569 ,  0.20511359,
        -0.00609209, -0.3029322 ]], dtype=float32)}``
Therefore replay buffer will have always next_obs == last_obs
``True``

### System Info

- OS: Windows-10-10.0.22621-SP0 10.0.22621
- Python: 3.10.9
- Stable-Baselines3: 1.7.0
- PyTorch: 2.0.0
- GPU Enabled: True
- Numpy: 1.23.5
- Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
thanks for spotting the bug, could you check if it's still there with SB3 master version?
(@qgallouedec refactored the frame stacking recently)

**Comment by araffin** [comment]
After a quick check, it seems solved in https://github.com/DLR-RM/stable-baselines3/pull/1238

**Comment by WeberSamuel** [comment]
Perfect. It is fixed in the master branch👍
Thanks for the fast reply.
