### ISSUE TITLE
[Question] Logging when using SubprocVecEnv and multiple environments

### ISSUE THREAD

**Issue by amanuelanteneh** [DLR-RM/stable-baselines3#1437]
### ❓ Question

Hello, I'm using SB3 with a custom environment (using the gym interface) I made where I return some values in the `info` variable after each call of `step()`. I was originally using 1 environment to train my agent and was logging the values returned by the `info` variable at each timestep and it was fairly straightforward to figure out how to do this. However now I am using multiple (4) environments in parallel and I'm struggling to figure out how to log the same information to tensorboard. I searched for an issue similar to this but wasn't able to find much, would greatly appreciate any help.

Minimal example for logging extra info to tensorboard when using only 1 environment and using a callback:

```
class TimestepCallback(BaseCallback):


    def __init__(self, verbose=0):

        super().__init__(verbose)

    def _on_step(self):
        # Log scalar values 
        extrainfo1= self.training_env.buf_infos[0]['extrainfo1']

        extrainfo2 = self.training_env.buf_infos[0]['extrainfo2']

        self.logger.record("timestep/rollout/info1", extrainfo1)
        
        self.logger.record("timestep/rollout/info2", extrainfo2)

        return(True)


env = customEnv()

timestep_callback = TimestepCallback()

model = PPO('MlpPolicy', env, verbose=0, tensorboard_log='./myLogFolder')

model.learn(total_timesteps=800_000, tb_log_name='myModel', callback=[timestep_callback])
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by ShangqunYu** [comment]
I have something similar, when I used 
```
num_cpu = 4
env = SubprocVecEnv([make_env('myEnv-v0', i) for i in range(num_cpu)])
model = PPO("MlpPolicy", env, verbose=1, tensorboard_log="./loco2dLinear_tensor/")
model.learn(total_timesteps=450000)
``` 
Tensorboard is blank, it doesn't have any data, wonder if I missed anything

**Comment by qgallouedec** [comment]
> I'm struggling to figure out how to log the same information to tensorboard.

[`VecMonitor` with the` info_keywords` arg](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html#vecmonitor)  is probably what you're looking for.

If not, and to make sure you understand your question, you should provide a minimal example with your question.

**Comment by amanuelanteneh** [comment]
> > I'm struggling to figure out how to log the same information to tensorboard.
> 
> [`VecMonitor` with the` info_keywords` arg](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html#vecmonitor) is probably what you're looking for.
> 
> If not, and to make sure you understand your question, you should provide a minimal example with your question.

This is good to know but it seems to log the values to a separate csv file (Monitor.csv) instead of to tensorboard. I've updated my original post with a minimal example of how I accomplished logging the desired values to tensorboard via the use of callbacks when training with only one environment. I'm wondering how to generalize this when using `SubprocVecEnv` .i.e multiple environments.

**Comment by qgallouedec** [comment]
Similar to https://github.com/DLR-RM/stable-baselines3/issues/1160#issuecomment-1305873903

I'd either aggregate (average for example) the values like this:

```python
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import BaseCallback
from stable_baselines3.common.env_util import make_vec_env


class TensorboardCallback(BaseCallback):
    def _on_step(self) -> bool:
        infos = self.locals["infos"]
        probs = [infos[idx]["prob"] for idx in range(len(infos))]
        self.logger.record("prob", np.mean(probs))
        return True

venv = make_vec_env("Taxi-v3", n_envs=2)
PPO("MlpPolicy", venv, tensorboard_log="./tensorboard/").learn(10_000, callback=TensorboardCallback())
```

Or use one keyword per env:

```python
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import BaseCallback
from stable_baselines3.common.env_util import make_vec_env


class TensorboardCallback(BaseCallback):
    def _on_step(self) -> bool:
        infos = self.locals["infos"]
        for idx in range(len(infos)):
            prob = infos[idx]["prob"]
            self.logger.record(f"prob_{idx}", prob)
        return True

venv = make_vec_env("Taxi-v3", n_envs=2)
PPO("MlpPolicy", venv, tensorboard_log="./tensorboard/").learn(10_000, callback=TensorboardCallback())
```
