### ISSUE TITLE
Custom Policy Example (Question)

### ISSUE THREAD

**Issue by olivierp9** [DLR-RM/stable-baselines3#144]
Hello,

First of all thank you for the great library. In stable-baselines there was an example of custom policy (class CustomPolicy(ActorCriticPolicy)). I was wondering if it was possible to add the same for stable-baselines3. I want to use MultiHeadAttention module and have a separate net for value function and policy (PPO). Not sure what the best way to implement the custom policy is.

**Comment by araffin** [comment]
@olivierp9 I added a full example in #167 (mostly copied from my replied to #168 )
this will be merged with master soon ;)

NOTE: the example will work only with the latest master version of SB3 for now

**Comment by olivierp99** [comment]
Thank you much appreciated!

have a nice day
