### ISSUE TITLE
[Question / Bug] Incorrect reward normalization in VecNormalize?

### ISSUE THREAD

**Issue by timosturm** [DLR-RM/stable-baselines3#1447]
Why is the reward not normalized in the same way as the observations are, i.e., by subtracting the mean? Is it not a bad idea to clip the normalized reward in an interval centered around zero [`-clip_reward`, `clip_reward`] if the mean of the normalized reward is not centered around zero?

Observation:
https://github.com/DLR-RM/stable-baselines3/blob/15c9daa2ba213a2e2aceba2b9b8a3983c26423bb/stable_baselines3/common/vec_env/vec_normalize.py#L217

Reward (note how `ret_rms.mean` is not substracted here):
https://github.com/DLR-RM/stable-baselines3/blob/15c9daa2ba213a2e2aceba2b9b8a3983c26423bb/stable_baselines3/common/vec_env/vec_normalize.py#L250

**Comment by araffin** [comment]
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/348#issuecomment-795147337
(and https://github.com/DLR-RM/stable-baselines3/issues/1426#issuecomment-1495694586)
