### ISSUE TITLE
Is there any book that aboard reinforcement learning just using stable- baselinens3?

### ISSUE THREAD

**Issue by orlandombaa** [DLR-RM/stable-baselines3#1457]
### 📚 Documentation

Hi every one ! 

I will start to learn about reinforcement learning in python. I come from machine learning and deep learning approaches and in those cases the libraries and literature about them seem much more clear with the use of sickit learn and tensorflow. However, in the field of reinforcement learning, I don't see it that clearly .

Is there any book that you recommend where the author use stable baseliness3 for his examples ?

Best regards,  

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

**Comment by araffin** [comment]
Hello,
> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

have you checked the resources we link in our documentation ?
there is also https://huggingface.co/deep-rl-course/unit0/introduction by @simoninithomas (btw, Thomas, could you add that one to the doc?)

We also have a notebook tutorial and videos like: https://youtu.be/Ikngt0_DXJg

**Comment by orlandombaa** [comment]
hello @araffin 
thank you for your answer. I will check these sources

**Comment by araffin** [comment]
Closing as the hugginface course is now linked in our docs.
