### ISSUE TITLE
check_env fails with unity environment (as it has float32 type instead of simply float?)

### ISSUE THREAD

**Issue by ThorAvaTahr** [DLR-RM/stable-baselines3#1459]
I have a unity environment that returns float32 rewards on step. 

from python i have the following:

```
    #create unity environment
    unity_env = UnityEnvironment(
        file_name=unity_env_path, seed=1, no_graphics=False,
    )

    # we convert the environment to a gym environment, wrap it with a monitor (for logging reward and
    # episode length) and wrap it with a dummyvec environment for use with stable baselines
    gym_env = UnityToGymWrapper(unity_env=unity_env, allow_multiple_obs=True)
    gym_env = FlattenTupleObservationWrapper(gym_env)
    gym_env = Monitor(gym_env, filename=str(REPORTS_PATH / "logs"))
    vec_env = DummyVecEnv([lambda: gym_env])

```
When I call check_env, for instance immediately after UnityToGymWrapper, it fails with message that my env doesnt have a float reward. When I check this it turns out to be a float32. I think the check_env should accept that, or alternatively the UnityToGymWrapper should convert this (but that is an MLagents function).

**Comment by araffin** [comment]
Hello,

> , or alternatively the UnityToGymWrapper should convert this (but that is an MLagents function).

yes, this look like more a unity gym issue.

>  I check this it turns out to be a float32.

you mean a numpy float32? then a simple Gym wrapper that does `reward = float(reward)` would solve the issue.

Also be careful, the env checker is only for single env and cannot check multiple env (`VecEnv`), see https://github.com/DLR-RM/stable-baselines3/issues/1251
