### ISSUE TITLE
Serialization of PPO policy impossible?

### ISSUE THREAD

**Issue by zhh210** [DLR-RM/stable-baselines3#1460]
Hello, I'm wondering if it is expected that the PPO policy is not serializable (pickle)? I'm able to train a PPO model and reload seems fine:
```
>>> PPO.load('play_sm').policy
ActorCriticPolicy(
  (features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (pi_features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (vf_features_extractor): FlattenExtractor(
    (flatten): Flatten(start_dim=1, end_dim=-1)
  )
  (mlp_extractor): MlpExtractor(
    (shared_net): Sequential()
    (policy_net): Sequential(
      (0): Linear(in_features=5, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
    )
    (value_net): Sequential(
      (0): Linear(in_features=5, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
    )
  )
  (action_net): Linear(in_features=64, out_features=1, bias=True)
  (value_net): Linear(in_features=64, out_features=1, bias=True)
)
```
However, the policy doesn't seem to be serializable with pickle:
```
>>> pickle.loads(pickle.dumps(PPO.load('play_sm').policy))
*** TypeError: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given
```
Given the error message is quite generic, is there way to investigate where the error is exactly from? Thanks. 
```
stable_baselines3==1.7.0
```

**Comment by araffin** [comment]
Hello,
you should probably use torch save/load instead of pickle.
Why do you need pickle here?
Also we do support saving models in a file-like object.

**Comment by zhh210** [comment]
Thanks @araffin , the reason I'm serializing the PPO policy is to pass it over for multiprocessing to do parallel evaluation. I've an example at https://stackoverflow.com/questions/76038856/parallel-evaluation-by-multiprocessing-not-possible-for-stable-baselines3 but it never went through.

I tried to save the policy as file which works ok but `load()` will fail with the same error:

```
>>> torch.save(model.policy, 'tmp.pt'); torch.load('tmp.pt')
*** TypeError: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given
```

**Comment by araffin** [comment]
the policy evaluation **does** support VecEnv.

Since #402

**Comment by zhh210** [comment]
@araffin Brilliant! I wasn't aware that vectorized env is already doing it in parallel. It's definitely cleaner than multiprocessing.
