### ISSUE TITLE
[Question] What is the 'proper' way of evaluating the performance of the trained agent's policy during the training process?

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [DLR-RM/stable-baselines3#1466]
### ❓ Question

I am using a for loop with `model.learn(a few steps)` then `evaluate_policy(...)`

Is this the intended way to evaluate the performance during training, or am I supposed to change some innit arguments in the model?

The [examples](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html) do not cover this, and I was not able to find out from the [model constructor](https://stable-baselines3.readthedocs.io/en/master/modules/td3.html)

Thanks!

```python
import gymnasium as gym
import numpy as np

from stable_baselines3 import TD3
from stable_baselines3.common.logger import configure
from stable_baselines3.common.evaluation import evaluate_policy

RUNS = 10  # Number of Statistical Runs


for run in range(RUNS):
    env = gym.make('Ant-v5', use_contact_forces=True)
    eval_env = gym.make('Ant-v5', use_contact_forces=True)
    eval_path = 'results/ant_v5/run_' + str(run)
    new_logger = configure(eval_path, ["stdout", "csv"])

    model = TD3("MlpPolicy", env, verbose=1)
    model.set_random_seed(run)
    model.set_logger(new_logger)

    mean_returns = []
    std_returns = []
    for _ in range(400):  # run for 400*5000 = 2e6
        model.learn(total_timesteps=5000)
        mean_return, std_return = evaluate_policy(model, eval_env, n_eval_episodes=10, return_episode_rewards=False)
        mean_returns.append(mean_return)
        std_returns.append(std_return)

    np.savetxt(eval_path + '/means.csv', mean_returns, delimiter=",")
    np.savetxt(eval_path + '/std.csv', std_returns, delimiter=",")
    model.save(eval_path + '/model')
```

Note: I am using SB3 2.0.0alpha5 
 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
SB3 tutorials recommend using an `EvalCallback` for that (it is mentioned in RL tips and tricks and in the examples, but shown only in the notebooks).
If you are using the RL Zoo (if not, I would recommended you to give it a try), it is included by default.

**Comment by sidney-tio** [comment]
Hello all, would be happy to take this up if everyone's okay with it

**Comment by araffin** [comment]
@sidney-tio please do =)
