### ISSUE TITLE
Why does there appear to be two forward passes for every step in StableBaselines3 PPO models?

### ISSUE THREAD

**Issue by lquantrill** [DLR-RM/stable-baselines3#1467]
### ❓ Question

I am trying to plot a t-SNE embedding plot of activations coming from the last hidden layer of a StableBaselines3 PPO model - Specifically, the last hidden layer of the actor network. I registered forward hooks on the layer using the following code, in order to get the activations:

```python
activations_list = []

def getValues(name):
    def hook(model, input, output):
        activations_list.append(output.detach().cpu().numpy()[0])
    return hook

module_activations = ModuleList(model.policy.modules())[12]
module_activations.register_forward_hook(getValues(module_activations))
```

This successfully fills the list with activations when evaluating the model using:

```python
model = PPO.load("ppo_seaquest")

env = make_atari_env('Seaquest-v4', n_envs=1, seed=1)
env = VecFrameStack(env, n_stack=1)
model.set_env(env)

vec_env = model.get_env()
obs = vec_env.reset()
for i in range(num_steps):
    action, _states = model.predict(obs, deterministic=True)
    obs, rewards, dones, info = vec_env.step(action)
```

The issue, however, is that the length of the resulting list is (2*num_steps)+1.

I assume that the +1 comes from an initial forward pass to register tensor shapes in model initialisation, as is seen for the feature extractor network in [this documentation](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-feature-extractor) (but I don't know this for sure so please correct me if I am wrong).

Could someone tell me why, then, the resulting list of activations has twice as many entries as the number of steps? It suggests to me that there are two forward passes per step.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
I tried to reproduce your issue but couldn't (with different env and different layers).

Below is a minimal and **working** example (provided code was not sufficient to be run, imports and logic were missing):
```python
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack

activations_list = []


def get_values(name):
    def hook(model, input, output):
        # Modify global variable
        activations_list.append(output.detach().cpu().numpy()[0])

    return hook


env = make_atari_env("Seaquest-v4", n_envs=1, seed=1)
env = VecFrameStack(env, n_stack=1)

model = PPO("CnnPolicy", env)
# model = PPO("MlpPolicy", "CartPole-v1")
module_activations = model.policy.pi_features_extractor.cnn[0]
# module_activations = model.policy.pi_features_extractor.linear[0]
# module_activations = model.policy.mlp_extractor.policy_net[0]

module_activations.register_forward_hook(get_values(module_activations))

num_steps = 400

vec_env = model.get_env()
obs = vec_env.reset()
for i in range(num_steps):
    action, _states = model.predict(obs, deterministic=True)
    obs, rewards, dones, info = vec_env.step(action)

print(len(activations_list))
assert len(activations_list) == 400
```

My guess is that you might be modifying the `activations_list` somewhere else.
