### ISSUE TITLE
[Question] Custom Network for DQN

### ISSUE THREAD

**Issue by fede72bari** [DLR-RM/stable-baselines3#1469]
### ❓ Question

I have tried to use the same code proposed in the documentation for PPO, for DQN. But i get an error. This is the code

```python
# Create log dir
log_dir = "/tmp/gym4/"
os.makedirs(log_dir, exist_ok=True)

env = gym.make("CartPole-v1")
env._max_episode_steps = 500000

total_steps = 10_000_000

# Logs will be saved in log_dir/monitor.csv
env = Monitor(env, log_dir)

policy_kwargs = dict(activation_fn=th.nn.ReLU,
                     net_arch=dict(pi=[512, 256], vf=[512, 256]))

model = DQN("MlpPolicy", 
            env, 
            verbose=1, 
            policy_kwargs=policy_kwargs,
            batch_size=128,
            learning_rate=0.0003,
            target_update_interval = 100,
            tau = 0.8,
            gamma = 0.99)

model.learn(total_timesteps=total_steps)
```

and the error I got is

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_27/507821438.py in <module>
     22             target_update_interval = 100,
     23             tau = 0.8,
---> 24             gamma = 0.99)
     25 
     26            # tensorboard_log="/ppo_cartpole_tensorboard/")

/opt/conda/lib/python3.7/site-packages/stable_baselines3/dqn/dqn.py in __init__(self, policy, env, learning_rate, buffer_size, learning_starts, batch_size, tau, gamma, train_freq, gradient_steps, replay_buffer_class, replay_buffer_kwargs, optimize_memory_usage, target_update_interval, exploration_fraction, exploration_initial_eps, exploration_final_eps, max_grad_norm, stats_window_size, tensorboard_log, policy_kwargs, verbose, seed, device, _init_setup_model)
    138 
    139         if _init_setup_model:
--> 140             self._setup_model()
    141 
    142     def _setup_model(self) -> None:

/opt/conda/lib/python3.7/site-packages/stable_baselines3/dqn/dqn.py in _setup_model(self)
    141 
    142     def _setup_model(self) -> None:
--> 143         super()._setup_model()
    144         self._create_aliases()
    145         # Copy running stats, see GH issue #996

/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/off_policy_algorithm.py in _setup_model(self)
    200             self.action_space,
    201             self.lr_schedule,
--> 202             **self.policy_kwargs,  # pytype:disable=not-instantiable
    203         )
    204         self.policy = self.policy.to(self.device)

/opt/conda/lib/python3.7/site-packages/stable_baselines3/dqn/policies.py in __init__(self, observation_space, action_space, lr_schedule, net_arch, activation_fn, features_extractor_class, features_extractor_kwargs, normalize_images, optimizer_class, optimizer_kwargs)
    148         self.q_net: QNetwork
    149         self.q_net_target: QNetwork
--> 150         self._build(lr_schedule)
    151 
    152     def _build(self, lr_schedule: Schedule) -> None:

/opt/conda/lib/python3.7/site-packages/stable_baselines3/dqn/policies.py in _build(self, lr_schedule)
    160         """
    161 
--> 162         self.q_net = self.make_q_net()
    163         self.q_net_target = self.make_q_net()
    164         self.q_net_target.load_state_dict(self.q_net.state_dict())

/opt/conda/lib/python3.7/site-packages/stable_baselines3/dqn/policies.py in make_q_net(self)
    175         # Make sure we always have separate networks for features extractors etc
    176         net_args = self._update_features_extractor(self.net_args, features_extractor=None)
--> 177         return QNetwork(**net_args).to(self.device)
    178 
    179     def forward(self, obs: th.Tensor, deterministic: bool = True) -> th.Tensor:

/opt/conda/lib/python3.7/site-packages/stable_baselines3/dqn/policies.py in __init__(self, observation_space, action_space, features_extractor, features_dim, net_arch, activation_fn, normalize_images)
     52         self.features_dim = features_dim
     53         action_dim = self.action_space.n  # number of actions
---> 54         q_net = create_mlp(self.features_dim, action_dim, self.net_arch, self.activation_fn)
     55         self.q_net = nn.Sequential(*q_net)
     56 

/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/torch_layers.py in create_mlp(input_dim, output_dim, net_arch, activation_fn, squash_output, with_bias)
    129 
    130     if len(net_arch) > 0:
--> 131         modules = [nn.Linear(input_dim, net_arch[0], bias=with_bias), activation_fn()]
    132     else:
    133         modules = []

KeyError: 0
```

if I skip the line policy_kwargs=policy_kwargs, everything is working properly.  Could somebody underline where I am wrong? Thank you very much.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> in the documentation for PPO, for DQN.
> net_arch=dict(pi=[512, 256], vf=[512, 256])

How is the policy defined for DQN vs PPO?
(the underlying question being: what is the main difference in term of architecture for DQN vs PPO)

If you answer that question, that will solve your problem (we have resources in the doc to learn more about PPO/DQN, DQN example would also give you the answer).

**Comment by fede72bari** [comment]
Thank you araffin, also for your teaching approach. If I well remember DQN has a target network architecturally equal to the policy one, the aim of which is to stabilize the learning process. Its weights are copied from the other network every N steps, where N is possibly configurable. In https://stable-baselines3.readthedocs.io/en/master/modules/dqn.html# i found "target_update_interval (int) – update the target network every target_update_interval environment steps." that should be the hyperparameter devoted to this scope. What I am probably missing, or maybe it is more, is the formalism defining the number of layers and their width. Maybe being the two networks equal it is necessary to define just one? Should i use a name in the dictionary instead of "vi"/"vf"? Googling for SB3 DQN examples I had already found the lunar one https://stable-baselines3.readthedocs.io/en/master/guide/examples.html that uses DQN for which it seems a custom network architecture is not defined. In the same page of examples, I noted that for A2C  the number and width of layers are defined as "policy_kwargs={"net_arch": [32]},", could it be something similar for DQN too?

**Comment by araffin** [comment]
> f I well remember DQN has a target network architecturally equal to the policy one,

but how is the policy defined?
how do you select an action when using A2C/PPO vs when using DQN?

**Comment by araffin** [comment]
For later references:

> but how is the policy defined?

the greedy policy is implicitly defined using $a_t = \pi(s_t) = argmax_a(q(s_t, a))$

>  how do you select an action when using A2C/PPO vs when using DQN?

In A2C/PPO, you have a separate actor, a policy network that output a distribution of actions $\pi(a_t | s_t)$ whereas with DQN, you use an epsilon-greedy defined using the q-network (see above).

Overall, ` net_arch=dict(pi=[512, 256], vf=[512, 256])`, doesn't makes much sense for DQN as there is no actor (policy) network and no value function network, only a Q-network ;) (DQN = Deep Q-Network)
So you should pass only `net_arch=[512, 256]`.
(see type hint also present in the documentation: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/dqn/policies.py#L116).
