### ISSUE TITLE
[Bug]: NumPy requirement is overly relaxed

### ISSUE THREAD

**Issue by troiganto** [DLR-RM/stable-baselines3#1471]
### 🐛 Bug

If a sufficiently old version of NumPy is pre-installed, Stable Baselines becomes unimportable to to a missing module `numpy.typing`, which was added in [NumPy 1.20](https://numpy.org/doc/stable/release/1.20.0-notes.html#numpy-is-now-typed).

The reason is that SB3's `setup.py` file says that it works with any NumPy version, so `pip install` won't upgrade it. I've put together a small PR [here](https://github.com/troiganto/stable-baselines3/tree/fix/numpy-version).

### To Reproduce

```sh
$ python -m venv venvs/repro
$ . venvs/repro/bin/activate
$ pip install -U pip wheel
$ pip install  'numpy<1.20' 'torch<2' 'pandas<1.5'
$ pip install stable-baselines3
$ python -c 'import stable_baselines3'
```

### Relevant log output / Error message

```shell
Traceback:
<own code>:8: in <module>
    import stable_baselines3 as sb3
.../stable_baselines3/__init__.py:5: in <module>
    from stable_baselines3.a2c import A2C
.../stable_baselines3/a2c/__init__.py:1: in <module>
    from stable_baselines3.a2c.a2c import A2C
.../stable_baselines3/a2c/a2c.py:7: in <module>
    from stable_baselines3.common.on_policy_algorithm import OnPolicyAlgorithm
.../stable_baselines3/common/on_policy_algorithm.py:9: in <module>
    from stable_baselines3.common.base_class import BaseAlgorithm
.../stable_baselines3/common/base_class.py:21: in <module>
    from stable_baselines3.common.noise import ActionNoise
...stable_baselines3/common/noise.py:6: in <module>
    from numpy.typing import DTypeLike
E   ModuleNotFoundError: No module named 'numpy.typing'
```
```


### System Info

- OS: Linux-5.14.0-162.18.1.el9_1.x86_64-x86_64-with-glibc2.34 # 1 SMP PREEMPT_DYNAMIC Thu Feb 9 04:28:41 EST 2023
- Python: 3.9.7
- Stable-Baselines3: 1.8.0
- PyTorch: 1.13.1
- GPU Enabled: False
- Numpy: 1.19.5
- Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
> - Stable-Baselines3: 1.8.0

master branch nom uses gymnasium. And gymnasium requires numpy 1.21, so you should encounter this problem anymore.
But I'm not opposed to specifying a minimal version of numpy, it might even be cleaner.

**Comment by araffin** [comment]
> master branch nom uses gymnasium. And gymnasium requires numpy 1.21, so you should encounter this problem anymore.
But I'm not opposed to specifying a minimal version of numpy, it might even be cleaner.

I was about to write the same remark ^^"

**Comment by troiganto** [comment]
Ah, I'm in the process of making the jump to Gymnasium, so I wasn't aware of this. I only encountered this because of a surprising CI failure and figured I might as well attach a minimum version to it.

I've just submitted the PR, so feel free to merge or close it. In any case, thanks for the quick reply!
