### ISSUE TITLE
How to use the SAC algorithm in the SB3 framework to solve the driving decision problem for highway-fast-v0 scenarios

### ISSUE THREAD

**Issue by Phd-Ma** [DLR-RM/stable-baselines3#1473]
### ❓ Question

How to use the SAC algorithm in the SB3 framework to solve the driving decision problem for highway-fast-v0 scenarios
stable-baselines3-----------2.0.0a5
highway-env----------------1.8.1
gym-------------------------0.26.2
gymnasium-----------------0.28.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
SAC only supports continuous action space; `highway-fast-v0` is a discrete environment.

**Comment by qgallouedec** [comment]
I recommend you to try it by yourself next time. SB3's errors are pretty well designed for newcomers, for example:

```python
>>> import highway_env
>>> from stable_baselines3 import SAC
>>> SAC("MlpPolicy", "highway-fast-v0")
/home/qgallouedec/env/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:42: UserWarning: WARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: (5, 5)
  logger.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qgallouedec/env/lib/python3.10/site-packages/stable_baselines3/sac/sac.py", line 120, in __init__
    super().__init__(
  File "/home/qgallouedec/env/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 110, in __init__
    super().__init__(
  File "/home/qgallouedec/env/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 180, in __init__
    assert isinstance(self.action_space, supported_action_spaces), (
AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>,) as action spaces but Discrete(5) was provided
```
