### ISSUE TITLE
[Bug]: eval callback frequency dependent on number of vecenv's 

### ISSUE THREAD

**Issue by Geoffreyvd1** [DLR-RM/stable-baselines3#1474]
### 🐛 Bug

Not sure if intended or not, but currently the evaluation callback frequency is dependent on how many vectorized environments i am training on. To me it is a bit confusing, since i expect the frequency to be the frequency i define. 

For example if i define eval_freq = 2000. Then if i have only 1 environment, the frequency will indeed be 2000. However if i use 4 vecEnv's, then the frequency will be 8000. I looked into the code and it is caused by doing look at n_calls instead of num_timesteps: https://github.com/DLR-RM/stable-baselines3/blob/96526ed08af19f48dd762f70d06e9f32c2c63d18/stable_baselines3/common/callbacks.py#L434 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html#checkpointcallback

We probably need to add the same warning to `EvalCallback`. This is done automatically in the RL Zoo.
Can be fixed by https://github.com/DLR-RM/stable-baselines3/pull/1468

**Comment by Geoffreyvd1** [comment]
Yes i see, from a technical standpoint i get why you did it the way you did it. So its not per se a bug, but I foresee that a lot of people will misunderstand this frequency since its behavior is not that obvious from the outside. Perhaps a different name, like freq_per_vec would be logical?
Anyway besides this very nice work! Love this repo.

**Comment by araffin** [comment]
> So its not per se a bug, but I foresee that a lot of people will misunderstand this frequency since its behavior is not that obvious from the outside. 

That's why we try to document it (as done already in the callback doc and now in #1468), and if you use the RL Zoo, you won't have that issue.

> Perhaps a different name, like freq_per_vec would be logical?

This would be a breaking change and I'm afraid it wouldn't solve the issue (the behavior with multi env is still inconsistent vs one with single env).

>  Anyway besides this very nice work! Love this repo.

your welcome =)
