### ISSUE TITLE
[Feature Request] check_env does not work with gymnasium environments

### ISSUE THREAD

**Issue by Hayden-Stites** [DLR-RM/stable-baselines3#1476]
### 🚀 Feature

The check_env environment checker should work natively with gymnasium environments in addition to gym environments. I'm not sure if this could be considered a bug or not now that SB3 supports gymnasium.

User receives the error:
`AssertionError: The observation space must inherit from gym.spaces cf https://github.com/openai/gym/blob/master/gym/spaces/`
when checking a gymnasium environment.

### Motivation

Since full gymnasium support was added a few weeks back, I've been using SB3 for my workflow. I would be nice to be able to use the environment checker with gymnasium environments to sidestep problems before they occur.

### Additional context

[Pull](https://github.com/DLR-RM/stable-baselines3/pull/1327)

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by araffin** [comment]
Hello,
please fill the issue template completely.
You must have sb3 v2.0+ for gymnasium support.
