### ISSUE TITLE
[feature request] More Informative Errors on `is_image_space`

### ISSUE THREAD

**Issue by decodyng** [DLR-RM/stable-baselines3#148]
Currently,  errors resulting from failures of `is_image_space` as it is called [here](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/torch_layers.py#L66) in the NatureCNN torch layer are pretty uninformative. 

At the beginning of `NatureCNN`'s __init__, it calls: 

```
        assert is_image_space(observation_space), (
            "You should use NatureCNN "
            f"only with images not with {observation_space} "
            "(you are probably using `CnnPolicy` instead of `MlpPolicy`)"
        )
```

Within `is_image_space`, there are various failure modes, including: 
1. Observation space dtype isn't `uint8`
2. Observation space has wrong low/high values 
3. Observation space has the wrong channel orientation 

All of which are all currently grouped under one error template that assumes the user is failing to use an image observation (when it may just be that the image observation is currently formatted as a non-uint data type, or is accidentally pre-normalized to not be 0-255). 

I think this could be pretty easily resolved by just reformatting `is_image_space` to return both a boolean and a failure reason (which could be None in cases of non-failure), and that failure reason could be printed out on the NatureCNN level. If maintainers would be amenable to a solution of this general sort, I'd be happy to put together a PR for it.

**Comment by Miffyli** [comment]
Looks like [`env_checker`](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/env_checker.py) does these similar checks with bit more information. Generally we have been guiding people to use that to spot the problems, but indeed there are tight restrictions on the images in stable-baselines. I see two alternatives:

- Include the more-detailed checks and error messages in `is_image_space´, so people do not have to use `env_checker` and are immediately pointed at the error like here.
- Update error messages to include instructions like "use `env_checker` to validate your environment". Requires more work from users but all diagnostic code like this would be in one place.

@araffin comments?

**Comment by araffin** [comment]
>I personally lean towards the latter option so we can keep all checks for stable-baseline's quirks in one place. @araffin comments?

I agree with that. Also related to #142 .

>Maybe consider automatically applying env_checker stuff when agents are created to avoid manual labour?

I would argue against as `env_checker` will call `reset()` and `step()` method.
