### ISSUE TITLE
[Bug]: Error Running on Colab

### ISSUE THREAD

**Issue by disibaro** [DLR-RM/stable-baselines3#1483]
### 🐛 Bug

Starting today (run the same code yesterday with no error), the learn function throws an error when running on Google Colab, changing the verbose param to 0 in the model prevents the error from being triggered.

Notes:
- Using custom env
- Using Monitor Wrapper
- Using MaskablePPO from SB3Contrib

### Relevant log output / Error message

```shell
ValueError                                Traceback (most recent call last)
<ipython-input-61-9f6e3351cc82> in <cell line: 2>()
      1 # Train the agent
----> 2 model.learn(
      3     total_timesteps=2500000,
      4     tb_log_name=version,
      5     reset_num_timesteps=True

6 frames
/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/logger.py in __init__(self, filename_or_file, max_length)
    169             self.own_file = False
    170         else:
--> 171             raise ValueError(f"Expected file or str, got {filename_or_file}")
    172 
    173     def write(self, key_values: Dict[str, Any], key_excluded: Dict[str, Tuple[str, ...]], step: int = 0) -> None:

ValueError: Expected file or str, got <ipykernel.iostream.OutStream object at 0x7f1a34a25a50>
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [ ] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Pretty sure it was introduced with #1479

**Comment by araffin** [comment]
> Pretty sure it was introduced with https://github.com/DLR-RM/stable-baselines3/pull/1479

yep, in https://github.com/DLR-RM/stable-baselines3/pull/1479/commits/0cc5c5ed9443879edd3e49375112803e208970e2 I would say.
Let's check if there is a better type hint, otherwise, we just revert back.

Thanks for reporting the issue @disibaro , in the meantime, you can install the 2.x beta instead of master version (`pip install stable-baselines3==2.0.0a5`).

**Comment by qgallouedec** [comment]
To reproduce:

```python
!pip install 'stable-baselines3 @ git+https://github.com/DLR-RM/stable-baselines3@master'
!pip install sb3-contrib==2.0.0a4

from sb3_contrib import MaskablePPO
from sb3_contrib.common.envs import InvalidActionEnvDiscrete
from sb3_contrib.common.maskable.evaluation import evaluate_policy


env = InvalidActionEnvDiscrete()
model = MaskablePPO("MlpPolicy", env, verbose=1)
model.learn(5000)
```

**Comment by araffin** [comment]
@qgallouedec are you working on it already? Otherwise I can also take care of it.

**Comment by qgallouedec** [comment]
I am

**Comment by araffin** [comment]
Now fixed in master, sorry for the inconvenience.
