### ISSUE TITLE
RNN / LSTM for SAC

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#1489]
### ❓ Question

Hi, how can I implement a Bidirectional RNN or Bidirectional LSTM for SAC policy?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
You can get inspiration from PPO LSTM in the [SB3-Contrib](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/tree/master). However, I'm quite curious what your idea is considering that the agent never has access to the future states/actions.

**Comment by anilkurkcu** [comment]
Sorry I did not get your comment :)

Could you maybe explain a bit more?

**Comment by qgallouedec** [comment]
The advantage of Bi-LSTM over LSTM is that it captures information from the future in addition to the past. This makes sense in NLP. However, it's not clear to me how you transpose this into RL. At a given timestep, the agent, who has to choose an action, has no access to what will happen in the future (because it depends on the action he will take).

So I would like you to elaborate a bit more so that I understand why you want to use Bi-LSTM for SAC.

**Comment by anilkurkcu** [comment]
Thanks for the explanation. I just did not think clear enough whether Bi-LSTM would be suitable for RL, so my bad :)

And thanks for the previous comment as well, I will go with the PPO LSTM implementation.

**Comment by araffin** [comment]
> why you want to use Bi-LSTM for SAC.

side note: as for NLP, you could use masking to prevent the agent from looking into the future, but that makes things more complicated.

You should also look into R2D2 paper and the "burn-in" phase required for off-policy algorithms when using RNN.

PS: as for PPO, I would always recommend trying with frame-stack first, it is faster,  much simpler and usually competitive if not better in performance.
