### ISSUE TITLE
[Question] actions in self.locals are out of range

### ISSUE THREAD

**Issue by nrigol** [DLR-RM/stable-baselines3#1508]
### ❓ Question

I created a custom gym environment where action space has this form:
`self.action_space = spaces.Box(low=-1, high=1, shape=(1,), dtype=np.float32)`

and I train a PPO algorithm.

If I create a callback to access to the self.locals dictionary and I check the value of 'actions' I obtain:

> Actions [-0.05833455]
> Actions [0.4766237]
> Actions [0.84683895]
> Actions [0.89382654]
> Actions [-1.3808054]
> Actions [0.9494464]
> Actions [-2.3816836]
> Actions [1.0229326]
> .... 

while if I print the actions directly from the my custom environment, I obtain the correct values:

> -0.05833455
> 0.4766237
> 0.84683895
> 0.89382654
> -1.0
> 0.9494464
> -1.0
> 1.0
> ....

Can you explain me why I obtain values out of the range [-1,1] ?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
The action is clipped into the interval of the action space. To get the clipped action, use the `"clipped_actions"` key instead.

```python
import gymnasium as gym
import numpy as np

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import BaseCallback


class ActionMonitor(BaseCallback):
    def _on_step(self) -> bool:
        actions = self.locals["clipped_actions"]
        print("From callback", actions)
        return True


class CustomEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.action_space = gym.spaces.Box(low=-1, high=1, shape=(1,), dtype=np.float32)
        self.observation_space = gym.spaces.Box(low=-1, high=1, shape=(1,), dtype=np.float32)

    def step(self, action):
        print("From step", action)
        return np.array([action]), 0.0, False, False, {}

    def reset(self):
        return np.array([0.0]), {}


model = PPO("MlpPolicy", CustomEnv())
callback = ActionMonitor()

model.learn(total_timesteps=100, callback=callback)
```
