### ISSUE TITLE
[Question] Possible Redundant Code

### ISSUE THREAD

**Issue by tudorjnu** [DLR-RM/stable-baselines3#1510]
### ❓ Question

Since the `observation` key within a goal directed environment is not required (https://github.com/DLR-RM/stable-baselines3/issues/1335) is the following check in `check_env` from [here](https://github.com/DLR-RM/stable-baselines3/blob/fd0cd82339511b54cd3907df228a656f2a32f0b8/stable_baselines3/common/env_checker.py#LL132C5-L135C6) still relevant?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
thanks for pointing that out, it should updated indeed (it was only partially updated in https://github.com/qgallouedec/stable-baselines3/commit/874ae079bc0a14b68fa389450ee74b7b913baa46)
