### ISSUE TITLE
[Question] Logging multiple agent.learn() in one tfevents file for tensorboard

### ISSUE THREAD

**Issue by till2** [DLR-RM/stable-baselines3#1513]
### ❓ Question

For a model-based algorithm, I have the following training cycle:

```txt
For every episode:
1. Update the world model
2. Train a SB3 agent in the learned world model (as an environment)
```

The difference from normal RL is that instead of only calling `agent.learn()` once, here I have to call it a lot of times (with only a few steps each time).

SB3 automatically creates new folders for each call of `agent.learn()`, i.e. I have `A2C_1, A2C_2, A2C_3, ...` but I would like it to log the individual `.learn` results into one folder with one `events.out.tfevents` file instead of creating a new folder with a new log every time. Is there a way to achieve this?

Currently I have one data point per training run and the tensorboard looks like this:
![image](https://github.com/DLR-RM/stable-baselines3/assets/89709351/c9019701-5c39-42b2-9861-21aa9e6c704f)

I have not found any function argument to do this and the only solution that I can think of is scraping all of the individual files at the end to retrieve the datapoints for plotting, but this would not allow for tensorboard logs while training and it creates a lot of folders. 

Any help is really appreciated! :)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Try `reset_num_timesteps=False`.

```python
from stable_baselines3 import A2C

model = A2C("MlpPolicy", "CartPole-v1", tensorboard_log="./a2c_cartpole_tensorboard/")

model.learn(1000)
model.learn(1000, reset_num_timesteps=False)
```

**Comment by till2** [comment]
This works, thank you so much! Saved a lot of time :D
