### ISSUE TITLE
[Question] Passing different observations to the actor and critic feature extractors

### ISSUE THREAD

**Issue by aalmuzairee** [DLR-RM/stable-baselines3#1514]
### ❓ Question

Hi there,

Thank you for all your hard work. I'd like to pass two different observations to the actor and the critic. From the documentation I see that I can have different feature extractors for the actor and critic, but I don't see that I can pass different observations to each. Is there a way to do that?  

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
I suggest using a Dict observation with a key for the actor observation and a key for the critic observation.

Then create a custom combined feature extractor for the actor and the critic.
The critic's feature extractor uses only the key for the critic's observation. The same goes for the actor.

**Comment by aalmuzairee** [comment]
Yeah, I was trying to implement it but then realized the issue, appreciate your input though.

**Comment by aalmuzairee** [comment]
I see, thanks for mentioning it.
