### ISSUE TITLE
[Bug]: check_env incorrectly assumes that an environment has >1 step() available before termination

### ISSUE THREAD

**Issue by lutogniew** [DLR-RM/stable-baselines3#1521]
### 🐛 Bug

When calling `stable_baselines3.common.env_checker.check_env`, the code inside calls `step()` on the checked environment even if the previous `step()` returned `terminated == True`, thus leading to exceptions with some environments under some circumstances (depending on the environment's initial state, the action sampled, ...).

The problem occurs at least with `stable-baselines3` `2.0.0a5` through `2.0.0a10` (checked only the two).

I hope I didn't miss something obvious, or didn't do something stupid about the number of steps that an environment should have available.

### To Reproduce

I've created a minimal example to reproduce the bug here: https://github.com/lutogniew/sb3-envchecker-bug

It's a simple dummy environment that returns `terminated = True` after the configured number of calls to `step()`, and throws an exception afterwards until the environment is `reset()`. It seems that with the default configuration, `check_env` triggers if the environment has only 1 `step()` available. If it has at least 2, then the problem isn't triggered.

### System Info

- OS: Linux-6.2.0-20-generic-x86_64-with-glibc2.37 # 20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023
- Python: 3.11.2
- Stable-Baselines3: 2.0.0a10
- PyTorch: 2.0.1+cu117
- GPU Enabled: True
- Numpy: 1.24.3
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
you are right, this is a corner case when the episode is only one step (normally unlikely).

A simple fix would to call `vec_env.reset()` after that line: https://github.com/DLR-RM/stable-baselines3/blob/1bfb55df0edc6882ecadf499419cd3ecb8fe6a79/stable_baselines3/common/env_checker.py#L112

I would welcome a PR that solves this issue =)
