### ISSUE TITLE
[Question] How to share layers between policy and value in PPO ?

### ISSUE THREAD

**Issue by Florence-C** [DLR-RM/stable-baselines3#1529]
### ❓ Question

Hello, 

I am trying to train a PPO with shared layers between the policy and value. 
The shared_layer parameter is deprecated, so I guess the correct way to do so is to use a feature extractor and share it between policy and value. 

I'm trying to do so with MlpExtractor, but it does not inherit from the BaseFeaturesExtractor class, so when the function make_feature_extractor is called [(here)](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/policies.py#L118), the observation_space is given as input to the MlpExtractor (instead of feature_dim), which provoques an error.

Can MlpExtractor be used as a extractor or should it necessary be coupled with a previous one (e.g. FlattenExtractor) - and if yes, how can two extractors be used ? 

Is there something I am missing ? 

Thanks in advance. 

Regards,

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello Flo =)

yes features extractor is one way to achieve that ( https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-feature-extractor)
but why not inherit from the `BaseFeatureExtractor` ?

and no MlpExtractor is not a features extractor but comes after.
Another solution is to define a custom policy:https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#advanced-example


Related :  https://github.com/DLR-RM/stable-baselines3/issues/1055 https://github.com/DLR-RM/stable-baselines3/pull/1148 and https://github.com/DLR-RM/stable-baselines3/pull/1292

PS: by experience, sharing fully connected layers between actor and critic for ppo is not helpful (only sharing the features is)

**Comment by Florence-C** [comment]
Thanks for you very fast reply !

My question was more precisely, can I share layers without writing a custom extractor or policy ;)

Thanks for again for all the information !
