### ISSUE TITLE
[feature request] Allow to set the device when loading a model

### ISSUE THREAD

**Issue by liorcohen5** [DLR-RM/stable-baselines3#153]
In common/base_class.py in the 'load' method (lines 319-378), I'd really appreciate it if you could add a 'device="auto" argument to the load method definition (line 319), and set the device using this argument on line 355 instead of the hard-coded parameter.

I can change it and submit a PR on a different branch if you prefer, though it's just a 2 lines change.

Thanks a lot in advance and great work on this repo I really like it so far!

**Comment by araffin** [comment]
Hello,

>I'd really appreciate it if you could add a 'device="auto" argument to the load method definition

Sounds like a reasonable request.

>I can change it and submit a PR on a different branch if you prefer, though it's just a 2 lines change.

Please do, don't forget to check the contributing guide first ;)

>Thanks a lot in advance and great work on this repo I really like it so far!

Good to hear =)

**Comment by liorcohen5** [comment]
Great :)
I've followed the guide, made the changes locally, included a test for the new feature, added a line in the changelog, and all the good stuff.
How can I upload it to a new branch before opening a PR?

Thanks!

**Comment by Miffyli** [comment]
You need to make a fork of this repository, make a branch there, add the modifications and then you can make a PR that compares that branch against the master.
