### ISSUE TITLE
[Question] How to render Atari environment in evaluate_policy()?

### ISSUE THREAD

**Issue by chichuenchang** [DLR-RM/stable-baselines3#1536]
### ❓ Question

Need to render Atari environment to see how the agent is doing when evaluating but got this warning when I pass render=True into evaluate_policy().
```
 "No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps."
```
This is my code:

```python        
    def evaluate_model(env_name: str, model_path: str, render_mode: str = None):
        env = make_atari_env(env_name,n_envs=1, seed=0)
        env = VecFrameStack(env, n_stack=4)
        model = A2C.load(model_path)
        mean_reward, std = evaluate_policy(model, env, n_eval_episodes=10, render = True if render_mode != None else False )
        env.close()
        print(mean_reward, std)

    evaluate_model('Breakout-v4', path, render_mode='human')
```

This code works for gym environments but I don't know why it fails on the Atari ones. Did I miss something?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
please fill the issue template completely (notably output of `python -c 'import stable_baselines3 as sb3; sb3.get_system_info()'`)

My guess is that you are using gymnasium. In that case the render mode must be passed at initialization.

Otherwise, SB3 default to `rgb_array` (which is ok) but there might be a bug that will be fixed soon: https://github.com/DLR-RM/stable-baselines3/pull/1525

**Comment by chichuenchang** [comment]
Hi, yes I'm using Gymnasium and here's my get_system_info():
```
>>> sb3.get_system_info()
- OS: Windows-10-10.0.19041-SP0 10.0.19041
- Python: 3.7.12
- Stable-Baselines3: 2.0.0a5
- PyTorch: 1.13.1+cu117
- GPU Enabled: True
- Numpy: 1.21.6
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1
```

Sorry didn't checkup on this post since I later fixed this issue by 
```
    env = make_atari_env(env_name,n_envs=1, seed=0, env_kwargs = {'render_mode': 'rgb_array'})
```
I tried to pass `render_mode` to the kwargs in the `make_atarI_env()` but somehow I missed the `env_kwargs`. So, I was always getting the ` __init__() got an unexpected keyword argument 'render_mode' ` error.

Anyway thanks for replying to me.
