### ISSUE TITLE
Box() must be a scalar value to be a valid obs_space

### ISSUE THREAD

**Issue by adamfrly** [DLR-RM/stable-baselines3#1538]
### 🐛 Bug

I am making my own custom environment whose observation space I'm hoping to be R^56_+ (56 dimensional positive reals). I tried creating a (56,) Box space as the `observation_space` of the environment and everything worked fine when just randomly sampling action from gym.

Once I incorporated stable_baselines3, I received errors saying that I couldn't use multidimensional Box action spaces when training a PPO agent, so I tried using the env checker and I received the below stack trace.

This is weird to me because it seems like almost all of the stock gym environments used in examples have multidimensional Box observation spaces (like the Lunar Lander provided on the documentation page).

### Code example

```python
import gym as gym
import numpy as np
from gym import spaces, logger

from stable_baselines3.common.env_checker import check_env


class CustomEnv(gym.Env):

    def __init__(self):
        super().__init__()

        low = np.array([0] * 56, dtype=np.float32)
        high = np.array([np.finfo(np.float32).max] * 56, dtype=np.float32)

        self.action_space = spaces.Discrete(8)
        self.observation_space = spaces.Box(low=low, high=high, dtype=np.float32)

    def _get_obs(self):
          obs = np.random.rand(56)
          return obs

    def _get_info(self):
        return {"foo": "bar"}

    def reset(self, seed=None, options=None):
       
       self.is_done = False
       self.current_step = 0
       obs = self._get_obs()
       info = self._get_info()
       
       return obs, info

    def step(self, action):
        assert self.action_space.contains(action), f"Invalid action {action}, {type(action)}"

        self.cityflow.set_tl_phase(self.intersection_id, action)
        self.cityflow.next_step()

        state = self._get_obs()
        reward = self._get_reward()
        info = self._get_info()

        self.current_step = self.current_step + 1

        if self.is_done:
            logger.warn("You are calling 'step()' even though this environment has already returned done = True. "
                        "You should always call 'reset()' once you receive 'done = True' "
                        "-- any further steps are undefined behavior.")
            reward = 0.0

        if self.current_step + 1 == self.steps_per_episode:
            self.is_done = True
        
        if self.render_mode == "human":
            self.render()

        return state, reward, self.is_done, False, info

env = CustomEnv()
check_env(env)```


### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "testing_things.py", line 13, in <module>
    check_env(env)
  File "/home/adam/traffic_optim/CityFlow/traffic-env/lib/python3.8/site-packages/stable_baselines3/common/env_checker.py", line 377, in check_env
    _check_returned_values(env, observation_space, action_space)
  File "/home/adam/traffic_optim/CityFlow/traffic-env/lib/python3.8/site-packages/stable_baselines3/common/env_checker.py", line 223, in _check_returned_values
    _check_obs(obs, observation_space, "reset")
  File "/home/adam/traffic_optim/CityFlow/traffic-env/lib/python3.8/site-packages/stable_baselines3/common/env_checker.py", line 162, in _check_obs
    assert not isinstance(
AssertionError: The observation returned by the `reset()` method should be a single value, not a tuple
```

### System Info

- OS: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29 # 1 SMP Fri Apr 2 22:23:49 UTC 2021
- Python: 3.8.10
- Stable-Baselines3: 1.7.0
- PyTorch: 2.0.0+cu117
- GPU Enabled: True
- Numpy: 1.24.2
- Gym: 0.26.2

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
See documentation : "Only Stable-Baselines3 2.x supports Gymnasium. As SB3 2.x is currently in beta, you will need to specify pip install "stable_baselines3[extra]>=2.0.0a9" explicitly, or install the master version (see below)."

SB3 1.x only supports gym 0.21.

**Comment by adamfrly** [comment]
I retried after setting gym to version 0.21.0 and still getting the same issue. Below is the new system info:

- OS: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29 # 1 SMP Fri Apr 2 22:23:49 UTC 2021
- Python: 3.8.10
- Stable-Baselines3: 1.7.0
- PyTorch: 2.0.0+cu117
- GPU Enabled: False
- Numpy: 1.24.2
- Gym: 0.21.0

Is it intended behavior to force Box observation spaces to be scalar values? If so, I will try to find a different option for my observation space. Also, if it helps, this is the [portion of env_checker.py](https://github.com/DLR-RM/stable-baselines3/blob/v1.7.0/stable_baselines3/common/env_checker.py#L161-L164) that is throwing the exception.

```python
def _check_obs(obs: Union[tuple, dict, np.ndarray, int], observation_space: spaces.Space, method_name: str) -> None:
    """
    Check that the observation returned by the environment
    correspond to the declared one.
    """
    if not isinstance(observation_space, spaces.Tuple):
        assert not isinstance(
            obs, tuple
        ), f"The observation returned by the `{method_name}()` method should be a single value, not a tuple"
```

**Comment by araffin** [comment]
you are using gym 0.26 api, you should upgrade to Gymnasium (see their doc) and SB3 v2.x, or update your env to follow gym 0.21 api.

**Comment by adamfrly** [comment]
My bad, got it working after doing those upgrades.
