### ISSUE TITLE
[Question] squash_output option not works for PPO

### ISSUE THREAD

**Issue by DDDOH** [DLR-RM/stable-baselines3#1540]
### ❓ Question

```python
from stable_baselines3.common.env_util import make_vec_env
n_env = 4
vec_env = make_vec_env('Ant-v4', n_envs=n_env)
model = PPO("MlpPolicy", vec_env, verbose=1, policy_kwargs={'squash_output':True})
```

When set squash_output as True and not using gSDE (generalized State-Dependent Exploration), the action distribution is still DiagGaussianDistribution but not SquashedDiagGaussianDistribution.

The document says 
> squash_output (bool) – Whether to squash the output using a tanh function, this allows to ensure boundaries when using gSDE.

And it is unclear that squash_output will NOT work when not using gSDE.

I suggest make the document clear, or change the code such that even without gSDE, squash_output still works. And I think the second option makes more sense, since squash_output is still useful without gSDE. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I suggest make the document clear

I would be happy to receive a PR =) (for both cases, but at least for the doc)

> since squash_output is still useful without gSDE.

There are some discussions in SB2 and SB3 repos about handling action space limits, but so far (and according to a survey paper), clipping doesn't impact much performance (although it is not pretty).

**Comment by tobirohrer** [comment]
I would like to work and this one and can prepare a PR in the upcoming days

**Comment by tobirohrer** [comment]
sorry, but I do not understand the problem and expected behavior completely.

When I look for usages of `SquashedDiagGaussianDistribution`, I can only find one use in `sac/policies.py`. Meaning no matter which parameters I pass to PPO, I would never get the `SquashedDiagGaussianDistribution` as action distribution.

**Comment by araffin** [comment]
> eaning no matter which parameters I pass to PPO, I would never get the SquashedDiagGaussianDistribution as action distribution.

PPO also uses gSDE and it has an option for squashed Gaussian distribution.

**Comment by araffin** [comment]
Closed by https://github.com/DLR-RM/stable-baselines3/pull/1652

**Comment by namheegordonkim** [comment]
> clipping doesn't impact much performance (although it is not pretty).

Are you sure about this? More complex unsupervised RL or imitation learning applications like GAIL seem to suffer a huge problem with distribution drift and undefined OOD predictions that saturate action means extremely quickly without squashing.

**Comment by b1ue1ue1ue** [comment]
> > eaning no matter which parameters I pass to PPO, I would never get the SquashedDiagGaussianDistribution as action distribution.
> 
> PPO also uses gSDE and it has an option for squashed Gaussian distribution.


For problems where the state does not change continuously, the noise of each sampling of gsde changes too much, resulting in a large change between the new and old strategies. The training mode finally crashes, and sometimes log_prob will output nan halfway through the training. Gsde's implementation of squash is a far-fetched approach and the effect is not good.
