### ISSUE TITLE
[Bug]: Wrong episode length after loading HER replay buffer

### ISSUE THREAD

**Issue by lbergmann1** [DLR-RM/stable-baselines3#1542]
### 🐛 Bug

After loading a HER replay buffer and training the model for a few steps, the episode length is not as expected: 

As shown in the example below, the maximum episode length should be 7 (`BitFlippingEnv(n_bits=7)`), but after loading the replay buffer and some more training steps, the maximum episode length in the replay buffer is 10.  This only occurs after saving and loading the replay buffer.

### To Reproduce

```python
import os
import numpy as np
from stable_baselines3 import SAC, HerReplayBuffer
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.envs import BitFlippingEnv

n_envs = 1
n_bits = 7
path = os.path.join(os.getcwd(),"replay_buffer")

def env_fn():
    return BitFlippingEnv(n_bits=n_bits, continuous=True)
env = make_vec_env(env_fn, n_envs)

model = SAC(
        "MultiInputPolicy",
        env,
        replay_buffer_class=HerReplayBuffer,
        replay_buffer_kwargs=dict(
            n_sampled_goal=2,
            goal_selection_strategy="future",
        ),
        gradient_steps=n_envs,
        train_freq=4,
        buffer_size=100,
        policy_kwargs=dict(net_arch=[64]),
        seed=0,
    )

model.learn(135)
if (model.replay_buffer.ep_length > n_bits).any():
    print(f"max episode length in replay buffer is {np.max(model.replay_buffer.ep_length)} (expected: {n_bits})")

print("Saving replay buffer...")
model.save_replay_buffer(path)

del model.replay_buffer

print("Loading replay buffer...")
model.load_replay_buffer(path, truncate_last_traj=True)

model.learn(30)
if (model.replay_buffer.ep_length > n_bits).any():
    print(f"max episode length in replay buffer is {np.max(model.replay_buffer.ep_length)} (expected: {n_bits})")
```

### Relevant log output / Error message

```shell
Saving replay buffer...
Loading replay buffer...
UserWarning: The last trajectory in the replay buffer will be truncated.
If you are in the same episode as when the replay buffer was saved,
you should use `truncate_last_trajectory=False` to avoid that issue.
max episode length in replay buffer is 10 (expected: 7)
```

### System Info

- OS: Linux-5.15.0-73-generic-x86_64-with-glibc2.29 # 80~20.04.1-Ubuntu SMP Wed May 17 14:58:14 UTC 2023
- Python: 3.8.10
- Stable-Baselines3: 2.0.0a11
- PyTorch: 1.13.1+cu117
- GPU Enabled: True
- Numpy: 1.23.0
- Cloudpickle: 2.2.0
- Gymnasium: 0.28.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by lbergmann1** [comment]
Related to this issue, I'm wondering why the last trajectory is truncated if `(self.ep_start[self.pos] != self.pos).any()` instead of `(self._current_ep_start != self.pos).any()`. 

Consider nearly the same example as above:
```python
import os
import numpy as np
from stable_baselines3 import SAC, HerReplayBuffer
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.envs import BitFlippingEnv

n_envs = 1
n_bits = 7
path = os.path.join(os.getcwd(),"replay_buffer")

def env_fn():
    return BitFlippingEnv(n_bits=n_bits, continuous=True)
env = make_vec_env(env_fn, n_envs)

model = SAC(
        "MultiInputPolicy",
        env,
        replay_buffer_class=HerReplayBuffer,
        replay_buffer_kwargs=dict(
            n_sampled_goal=2,
            goal_selection_strategy="future",
        ),
        gradient_steps=n_envs,
        train_freq=1,
        buffer_size=100,
        policy_kwargs=dict(net_arch=[64]),
        seed=0,
    )

model.learn(7)    
assert model.replay_buffer.pos == 7
assert model.replay_buffer.dones[model.replay_buffer.pos] == 0
assert model.replay_buffer.dones[model.replay_buffer.pos-1] == 1
assert model.replay_buffer.ep_start[model.replay_buffer.pos] == 0
assert model.replay_buffer.ep_start[model.replay_buffer.pos-1] == 0
assert model.replay_buffer._current_ep_start == 7

model.save_replay_buffer(path)
del model.replay_buffer
model.load_replay_buffer(path, truncate_last_traj=True)

```
I would not expect to see the ''The last trajectory in the replay buffer will be truncated...." warning since the replay buffer is loaded at the start of a new episode.

**Comment by qgallouedec** [comment]
Hi, thank you for reporting!
Indeed, there is an issue here. Your fix seems to fix it. Can you open a PR?

**Comment by qgallouedec** [comment]
> Related to this issue, I'm wondering why the last trajectory is truncated if `(self.ep_start[self.pos] != self.pos).any()` instead of `(self._current_ep_start != self.pos).any()`.

It's not related, it is the source of the issue. This

https://github.com/DLR-RM/stable-baselines3/blob/4fcda6b2d453a179c615162a36624d654e3456b2/stable_baselines3/her/her_replay_buffer.py#L378

and

https://github.com/DLR-RM/stable-baselines3/blob/4fcda6b2d453a179c615162a36624d654e3456b2/stable_baselines3/her/her_replay_buffer.py#L384

don't make sense, since the current episode starts are in `self._current_ep_start` and not in `self.ep_start[-1]`.
