### ISSUE TITLE
[Question] does sb3 handle each gym step reward in a sum way?

### ISSUE THREAD

**Issue by Pborz** [DLR-RM/stable-baselines3#1545]
### ❓ Question

in a gym env, each step returns a reward
but when env return done, i don't know what exactly happen?
should i mannually add up each step reward, and put it in the "done" state to tell sb3?
or sb3 just already handle each step it've experienced?

finaly, does everyone add a "final total reward" inside the done funtion? or just let the model learn the each step?

@araffin @qgallouedec 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
It seems to me like this is more a question about RL in general.
RL algorithms aim to maximize the expected cumulative reward. So there's no need to manually tweak your env to put all the rewards in the last step. Unless you have a very good reason for doing so, it's generally a bad idea.

**Comment by Pborz** [comment]
> It seems to me like this is more a question about RL in general. RL algorithms aim to maximize the expected cumulative reward. So there's no need to manually tweak your env to put all the rewards in the last step. Unless you have a very good reason for doing so, it's generally a bad idea.

i once thought that this `is more a question about RL in general.`
but after all, sb make out all easily in just one single line `model.learn()`, thus it's not strange that comes out with this kind of confusion about how sb interact with reward, THX

BTW, if i add in a finally reward inside `done`,will sb gather that too for learning? THX

**Comment by Pborz** [comment]
@qgallouedec

**Comment by qgallouedec** [comment]
> BTW, if i add in a finally reward inside `done`,will sb gather that too for learning? THX

I don't know what exactly you mean by "inside done", as `done` is a boolean returned by the env that informs whether the episode is finished.
If your question is "Is the last reward of the episode taken into account?", the answer is yes.

Here are some [useful resources](https://stable-baselines3.readthedocs.io/en/master/guide/rl.html). In your case, I would recommend reading the [reward and return section from spinning up](https://spinningup.openai.com/en/latest/spinningup/rl_intro.html#reward-and-return): 

> @qgallouedec 

no need to ping me every time, I get the notifications ;)

**Comment by Pborz** [comment]
oh sorry for the inside done confusion.
i mean, if i just simply return the done for sb model,then my last reward would be the last action return, maybe just a sigle little reward like every steps before.
but if i make some custom at the same time done triggered, i pass a final number of reward, the sb would consider the final reward is `due to` last action, or due to the whole game behavior-----i mean, in my wishes i'd like sb to learn this final reward as a whole reward not just the last action? 

still sorry for that because sb all in a single line `model.learn()` so that it's not strange that i stuck in no details : >

**Comment by Pborz** [comment]
thanks so much and i would delve into that now
