### ISSUE TITLE
   How to terminate an episode of Pendulum-v1 environment while training with sb3 agent (PPO)?

### ISSUE THREAD

**Issue by shivaniraochepuri21** [DLR-RM/stable-baselines3#1546]
### ❓ Question

How to make the flag '_terminated'_ as True for Pendulum-v1 to stop the training when the pendulum bar has reached the upright position, instead of always keeping _terminated_ and _truncated_ as False? 

Now, this is possible when we are manually writing a training loop, as we will have a '_previous_observation'_ variable and we can put some norm-based criteria for the episode to end. (Episode max length is fixed as 200 for this environment). 

As far as I understand, using sb3, we don't have that control, as **model. learn(total_timesteps=int(1e5))** does not allow such a parameter as an argument. We could use a reward environment wrapper, but we cannot edit the arguments or argument structure of **wrapped_env.step(action)** (as other recursive calls would expect this prototype). That is, I cannot do **wrapped_env.step(action, previous_observation)**, to end the episode when the target is reached.

I think it is important we are able to end the episode, so as to not lose the important _episode_len_ parameter. I am trying to train the environment with PPO and integrate the algorithm with control theoretic approaches for research, and I wonder if timely termination might mean something.

I much appreciate any help and suggestions to get through this trouble, I am stuck at it for a while. Thanks, IA. Would love to have your help and support in the work as well :))   

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
The best option is to wrap the environment to add a condition in the step method. Something like

```python
def step(self, action):
    observation, reward, terminated, truncated, info = self.env.step(action)
    is_upright = ...  # get this from the observation
    if is_upright:
        terminated = True
    return observation, reward, terminated, truncated, info

```
