### ISSUE TITLE
`pip install stable-baselines3` cause installing `gym==0.21` and throw error in gym setup command: 'extras_require'

### ISSUE THREAD

**Issue by yasirroni** [DLR-RM/stable-baselines3#1548]
### 🐛 Bug

Bug installing `stable_baselines3-1.8.0-py3-none-any.whl (174 kB)` resulted in installing `gym==0.21` instead of `gymnasium==0.28.1` or latest `gym==0.26.2`.

```
pip install stable-baselines3 --upgrade
Collecting stable-baselines3
  Using cached stable_baselines3-1.8.0-py3-none-any.whl (174 kB)
Collecting gym==0.21 (from stable-baselines3)
  Using cached gym-0.21.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### To Reproduce

```shell
pip install stable-baselines3 --upgrade
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Didn't found that docs.

https://stable-baselines3.readthedocs.io/en/master/guide/install.html

"Only Stable-Baselines3 2.x supports Gymnasium. As SB3 2.x is currently in beta, you will need to specify pip install "stable_baselines3[extra]>=2.0.0a9" explicitly, or install the master version (see below)."


Duplicate of #1455,  #1406 and https://github.com/openai/gym/issues/3176#issuecomment-1408598628 and #1324 for the error
