### ISSUE TITLE
[Question] Observation space must be a 1D vector or it can be a Dict, Tuple ?

### ISSUE THREAD

**Issue by nrigol** [DLR-RM/stable-baselines3#1549]
### ❓ Question

From what I understood reading documentation and similar issues, sb3 does not support tuple observation spaces but maybe it supports Dict spaces [](https://stable-baselines3.readthedocs.io/en/master/_modules/stable_baselines3/common/envs/multi_input_envs.html#SimpleMultiObsEnv). 

As suggested by araffin here [](https://github.com/hill-a/stable-baselines/issues/100), I would ideally need a Tuple because I want an observation space that has 2 continuous spatial components and 1 discrete value (is there something interesting in that location ?) and I would like to store the history of these 3 variables over M steps.

I decided to use 
`self.observation_space` = Box(low=-1, high=1, shape=(3,M), dtype=np.float32)`
but this leads me to the warning "Your observation  has an unconventional shape (neither an image, nor a 1D vector). We recommend you to flatten the observation to have only a 1D vector or use a custom policy to properly process the data." And training is not successful. 

Would you recommend  to reshape the observation in something like:

`self.observation_space` = Box(low=-1, high=1, shape=(3 * M,), dtype=np.float32)`

or better to use a Dict?
and probably also normalize the observation values in the range [0,1] ?

Hope I did not miss precious information in the documentation or in similar past issues, all the questions regarding the topic seemed a bit old. Thank you in advance for your help.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Would you recommend to reshape the observation in something like:
> self.observation_space = Box(low=-1, high=1, shape=(3 * M,), dtype=np.float32)`

yes and use one hot encoding for the discrete variable.
(the warning is mostly there for users that want to use images as input but don't use the correct type)

The slower alternative is indeed to use a dict observation space (I would recommend it only when you concatenating your input doesn't make sense, or if you need to do some custom manipulation later).

**Comment by araffin** [comment]
>  I said discrete but it is a binary variable. Do I still need to hot encode ?

I let you guess what the one hot encoding of a binary variable ;)

> Honestly, concatenating the input is not something very intuitive to me; but I cannot state it doesn't make sense either

The reason I'm telling you that is because this is what we do internally (we also have an example in the doc):

https://github.com/DLR-RM/stable-baselines3/blob/ffe26ccf95d7e3b37067bd81025d3b4b45825038/stable_baselines3/common/torch_layers.py#L259-L278

>  read that using a dict space would not preserve the order of the elements and that could be problematic.

Since python 3.6 dictionaries preserve the order.

**Comment by nrigol** [comment]
I had rephrased my question but it was too late, it was a very dumb one. Thank you so much!

**Comment by VineetTambe** [comment]
An update on this:
I managed to get it to work! (Not sure whether it is correct though)
Had to use the `from minigrid.wrappers import FlatObsWrapper` on top of the current environment.

I am not 100% sure that warpping the environment with FlatObsWrapper is the right way to do things? 

It is probabbly my lack of understanding but shouldn't minigrid work with sb3 as is?
Is there something I am missing here?
