### ISSUE TITLE
[Question] HER replay buffer: How to save ground truth desired goal that is not part of an observation, but needed to compute the reward?

### ISSUE THREAD

**Issue by lbergmann1** [DLR-RM/stable-baselines3#1550]
### ❓ Question

I use HER and SAC to train a robot to push an object to a desired target position. My observation contains the encoded object state (`observation["achieved_goal"]`) and the encoded target state (`observation["desired_goal"]`). Ground truth positions of object and target are not part of an observation, but I need both to compute the reward. 

My idea is to save the ground truth achieved and desired goal in the `info` dict and set `copy_info_dict = True` (HER). 
However, this means that in case of virtual samples, both the ground truth desired goal in the `info` dict and the encoded desired goal have to be replaced. My problem is that the `info` dict is copied, but the ground truth desired goal remains unchanged:
https://github.com/DLR-RM/stable-baselines3/blob/ffe26ccf95d7e3b37067bd81025d3b4b45825038/stable_baselines3/her/her_replay_buffer.py#L303

Is there another way to relabel data that are not part of an observation, but necessary to calculate the reward?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [ ] If code there is, it is minimal and working
- [ ] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Thank you for this interesting question. Indeed, what you are trying to do is not supported. I think your approach is the right one, but for it to work, you'll have to modify sb3 a bit: modify `_sample_goal` so that it returns not only the new goals but also the new `infos_dict`.

**Comment by lbergmann1** [comment]
[This](https://github.com/lbergmann1/stable-baselines3/commit/02ddd0970ceefc20350536873dcf0cd7f2cbbd88) is my modification to also relabel desired goals in info dictionaries.
If `copy_info_dict = True` and "achieved_goal" and "desired_goal" are keys in `info_dict`,  `info["desired_goal"]` is replaced. Otherwise info dictionaries are not modified.
