### ISSUE TITLE
[Question] Final rewards from model evaluation are different than final rewards from model callbacks

### ISSUE THREAD

**Issue by george-adams1** [DLR-RM/stable-baselines3#1551]
### ❓ Question

In the training env, I've set up callbacks every 10k timesteps where a snapshot of the model in its current state is tested on all of the in-sample training data. Several different metrics are calculated, most importantly reward. At the end of the training, during the last callback when the model is finished training, it gives a certain reward from the callback. However, when the model is finished training, and I take that exact same model and run it manually through an evaluation function through the exact same environment with the same data, the final reward is dramatically different from the reward for the same model at the same number of training timesteps. For example, a callback reward of 4e-4 and an evaluation reward of -4e-4. In both cases, the model is deterministic. 

Any idea why this may be occurring?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by george-adams1** [comment]
@araffin what kind of additional info would help?

**Comment by araffin** [comment]
Filling this template: https://github.com/DLR-RM/stable-baselines3/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
so we can actually reproduce the error.
Please keep the code example minimal (and working).

If it's a custom env problem, you can take a look at https://github.com/DLR-RM/stable-baselines3/blob/master/.github/ISSUE_TEMPLATE/custom_env.yml

**Comment by george-adams1** [comment]
Ok, I'm going to close this issue and create a new one with the proper template. Sorry about that.
