### ISSUE TITLE
[Bug]: Issue during training

### ISSUE THREAD

**Issue by yiptsangkin** [DLR-RM/stable-baselines3#1553]
### 🐛 Bug

Traceback (most recent call last):
  File "env.py", line 102, in <module>
    model.learn(total_timesteps=1000000, log_interval=20)
  File "/learning/venv/lib/python3.6/site-packages/sb3_contrib/ppo_mask/ppo_mask.py", line 554, in learn
    self.train()
  File "/learning/venv/lib/python3.6/site-packages/sb3_contrib/ppo_mask/ppo_mask.py", line 418, in train
    action_masks=rollout_data.action_masks,
  File "/learning/venv/lib/python3.6/site-packages/sb3_contrib/common/maskable/policies.py", line 297, in evaluate_actions
    distribution.apply_masking(action_masks)
  File "/learning/venv/lib/python3.6/site-packages/sb3_contrib/common/maskable/distributions.py", line 152, in apply_masking
    self.distribution.apply_masking(masks)
  File "/learning/venv/lib/python3.6/site-packages/sb3_contrib/common/maskable/distributions.py", line 62, in apply_masking
    super().__init__(logits=logits)
  File "/learning/venv/lib64/python3.6/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/learning/venv/lib64/python3.6/site-packages/torch/distributions/distribution.py", line 56, in __init__
    f"Expected parameter {param} "
ValueError: Expected parameter probs (Tensor of shape (64, 7830)) of distribution MaskableCategorical(probs: torch.Size([64, 7830]), logits: torch.Size([64, 7830])) to satisfy the constraint Simplex(), but found invalid values:
tensor([[1.8722e-06, 1.8720e-06, 1.8728e-06,  ..., 4.6250e-07, 1.8732e-06,
         1.7255e-05],
        [1.8722e-06, 1.8720e-06, 1.8728e-06,  ..., 4.6250e-07, 1.8732e-06,
         1.7255e-05],
        [1.8722e-06, 1.8720e-06, 1.8728e-06,  ..., 4.6250e-07, 1.8732e-06,
         1.7255e-05],
        ...,
        [1.8722e-06, 1.8720e-06, 1.8728e-06,  ..., 4.6250e-07, 1.8732e-06,
         1.7255e-05],
        [1.8722e-06, 1.8720e-06, 1.8728e-06,  ..., 4.6250e-07, 1.8732e-06,
         1.7255e-05],
        [1.8722e-06, 1.8720e-06, 1.8728e-06,  ..., 4.6250e-07, 1.8732e-06,
         1.7255e-05]], device='cuda:0', grad_fn=<SoftmaxBackward0>)�

### To Reproduce

```python
import gym
from gym import spaces

import utils
from game import DockerGame
from stable_baselines3.common.callbacks import CheckpointCallback, EvalCallback
from stable_baselines3.common.monitor import Monitor
from sb3_contrib.common.maskable.policies import MaskableActorCriticPolicy
from sb3_contrib.common.wrappers import ActionMasker
from sb3_contrib.ppo_mask import MaskablePPO


class CustomEnv(gym.Env):
    docker_game = None
    game_status_list = []

    def __init__(self):
        super().__init__()
        self.create_game()

    def create_game(self):
        self.docker_game = None
        self.docker_game = DockerGame('code', '01')
        self.docker_game.create_game()
        self.action_space = spaces.Discrete(len(self.docker_game.action_space))
        self.observation_space = spaces.Box(
            low=-1,
            high=200,
            shape=(len(self.docker_game.observation_space), 39)
        )

    def valid_action_mask(self):
        return self.docker_game.action_mask

    @staticmethod
    def get_key_by_value(d, value):
        for k, v in d.items():
            if v == value:
                return k
        return None

    def action_to_pile_place(self, action):
        action_item = self.docker_game.action_space[action]
        block = self.get_key_by_value(self.docker_game.block_map, action_item[0])
        bay = utils.get_double_num(action_item[1])
        row = utils.get_double_num(action_item[2])
        tier = action_item[3]
        return f'{block}{bay}{row}{tier}'

    def step(self, action):
        done = False
        action_pile_place = self.action_to_pile_place(action)
        if action_pile_place not in self.docker_game.current_able_pile_place_list or self.docker_game.game_status['game_over']:
            done = True
            self.game_status_list.append(self.docker_game.game_status)
        else:
            self.docker_game.take_action(action_pile_place)
        observation = self.docker_game.observation_space
        reward = self.docker_game.game_status['statistics']['last_reward']
        info = {}
        if done:
            print('''
                reward: {},
                reload_count: {},
                reload_twice_count: {},
                horizontal_dist: {},
                vertical_dist: {}
            '''.format(
                sum(self.docker_game.game_status['statistics']['reward_list']),
                self.docker_game.game_status['statistics']['reload_count'],
                self.docker_game.game_status['statistics']['reload_twice_count'],
                self.docker_game.game_status['statistics']['horizontal_dist'],
                self.docker_game.game_status['statistics']['vertical_dist']
            ))
        return observation, reward, done, info

    def reset(self):
        self.create_game()
        return self.docker_game.observation_space

    def render(self, mode="human"):
        pass

    def close(self):
        pass


def mask_fn(cenv):
    return cenv.valid_action_mask()


env = CustomEnv()
env = ActionMasker(env, mask_fn)

checkpoint_callback = CheckpointCallback(save_freq=1000, save_path='./logs/', name_prefix='rl_model')
eval_env = Monitor(env)
eval_callback = EvalCallback(eval_env, best_model_save_path='./logs/',
                             log_path='./logs/', eval_freq=2000,
                             deterministic=True, render=True)

model = MaskablePPO(MaskableActorCriticPolicy, env, verbose=1, device='cuda', gamma=0.9)
model.learn(total_timesteps=20000, log_interval=20)
model.save('./model/train.pkl')

file = open('game_status.txt', 'w')
file.write(str(env.game_status_list))
file.close()


```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [x] I have provided a minimal working example to reproduce the bug
- [x] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by yiptsangkin** [comment]
https://github.com/pytorch/pytorch/issues/81027 maybe is the same problem，but i don‘t know how to set `validate_args` in sb3

**Comment by qgallouedec** [comment]
Although you have checked all the checkboxes in the issue checklist, your issue does not meet any of the stated requirements. The maintainers will not consider your problem until you have corrected it.

**Comment by yiptsangkin** [comment]
> 



> Although you have checked all the checkboxes in the issue checklist, your issue does not meet any of the stated requirements. The maintainers will not consider your problem until you have corrected it.

This is a training model for a responsible custom environment, and it is difficult for me to provide reproducible code. I have searched for documents and issues, and there is no similar issue. Although the issue is a close error, it is caused by an error generated by 'nan', which is not the same as my error. https://github.com/pytorch/pytorch/issues/81027 maybe is the same problem, but i can not found exist params `validate_args` can be set in sb3

**Comment by yiptsangkin** [comment]
try to set dtype to np.float32, it works

**Comment by koliber31** [comment]
> try to set dtype to np.float32, it works

Could you tell where did you change dtype? I'm facing the same problem.
