### ISSUE TITLE
[Question] EvalCallback doest match performance of saved models during training - VecNormalize issue

### ISSUE THREAD

**Issue by lukaskocian** [DLR-RM/stable-baselines3#1556]
### ❓ Question

During training, I have EvalCallback set to evaluate the model every x time steps. To test that the EvalCallback works, I am also saving the model every x time steps during the training and after training I evaluate the saved models (respectively the same model but in different phases of the training) with my evaluation function (code bellow) and I plot their rewards on time step axis. The result should be that the EvalCallback reward plot from tensorboard should match the plot of rewards of saved models, but it doesn't. For both evaluations (EvalCallback & my eval func) I use same IS data and both are set to deterministic. I already know the source of this issue, which is VecNormalize - I normalize both rewards and observations. Without VecNormalize both charts matche, but the performance of the model is significantly worse (I use PPO).

Here are the plots that don't match:
**Plot of saved models evaluated by my evaluation function:**
<img width="757" alt="Screenshot 2023-06-15 at 11 43 39" src="https://github.com/DLR-RM/stable-baselines3/assets/99292682/79881fa0-6396-41e5-8591-61a19fa6989e">
**Plot of evalcallback in tensorboard:**
<img width="417" alt="Screenshot 2023-06-15 at 11 44 13" src="https://github.com/DLR-RM/stable-baselines3/assets/99292682/aa7d4de6-b33b-4c38-8a3d-d7abeff4796d">

I have 2 theories why they don't match

- There is a problem in my evaluation function with not correctly handling the normalization.
- The normalization of rewards is making the plot in tensorboard look too good too be true, because they are not the actual reward calculations, but their modified versions (but as I read, this shouldn't be the case)

Following is the code for envs initialization (BTW get_multiproc_env() function wraps the env into firstly Monitor and then SubprocVecEnv wrapper):

```
self.train_env = ForexTradingEnv(df=self.data_IS, train=True, state_features=self.state_features, **env_kwargs)

self.train_env_sb, _ = self.train_env.get_multiproc_env()
self.train_env_sb = VecNormalize(self.train_env_sb, training=True, norm_obs=True, norm_reward=True)
self.train_env_sb.save('vec_noralize.zip')

self.IS_env_test, _ = self.train_env.get_multiproc_env()
self.IS_env_test = VecNormalize(self.IS_env_test, training=False, norm_obs=True, norm_reward=True)
```

Following is the EvalCallback:
```
eval_callback = EvalCallback(self.IS_env_test,
                                         best_model_save_path='./best_model',
                                         log_path='./tb',
                                         eval_freq=eval_cb_freq,
                                         deterministic=True,
                                         render=False)
```

And lastly, my evaluation function (get_sb_env() function firstly wraps the env into Monitor and then into DummyEnv wrapper):
```
def evaluation(self, model):
    e, _ = self.train_env.get_sb_env()
    env = VecNormalize.load('vec_normalize.zip', e)

    total_rewards = 0
    test_obs = env.reset()
    n_steps = len(env.get_attr("master_data")[0])
    for i in range(n_steps):
        action, _states = model.predict(test_obs, deterministic=True)
        test_obs, rewards, done, info = env.step(action)
        total_rewards += rewards
        if i == (n_steps - 3):
            df_account_value, df_actions, df_cash = env.env_method(method_name="get_records")[0]
            break
        if done:
            df_account_value, df_actions, df_cash = env.env_method(method_name="get_records")[0]
            print("ups, early crash!")
            break
    return df_account_value, df_actions, df_cash, total_rewards
```

Packages:
stable-baselines3==1.6.2
pandas==1.5.0
numpy==1.21.5

I was going through RL Zoo and other issues and still can not solve this. If you have an idea how to solve this, please comment.

Thanks

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
it's hard to say anything as the provided code doesn't allow to reproduce the issue.
Make sure to use make_vec_env or wrap the env with a monitor wrapper before using Vecnormalize.

Please note that we do not offer tech support for getting RL working for task X. 

--- 

**The following is an automated answer:**

as you seem to try to apply RL to stock trading, i also must warn you about it. Here is recommendation from a former professional trader:

Retail trading, retail trading with ML, and retail trading with RL are bad ideas for almost everyone to get involved with. 
* I was a quant trader at a major hedge fund for several years. I am now retired.
* On average, traders lose money. On average, retail traders especially lose money. An excellent approximation of trading, and especially of retail trading, is 'gambling'. 
* There is a lot more bad advice on trading out there than good advice. It is extraordinarily difficult to demonstrate that any particular advice is some of the rare good advice.
* As such, it's reasonable to treat all commentary on retail trading as an epsilon away from snake oil salesmanship. Sometimes that'll be wrong, but it's a strong rule of thumb. 
* I feel a sense of responsibility to the less world-wise members of this community - which includes plenty of highschoolers - and so I find myself unable to let a conversation about retail trading occur without interceding and warning that it's very likely snake oil. 
* I find repeatedly making these warnings and the subsequent fights to be exhausting.
