### ISSUE TITLE
[Question] Extracting diagnostics from PPO.train()

### ISSUE THREAD

**Issue by tinnguyen96** [DLR-RM/stable-baselines3#1558]
### ❓ Question

Hi! 

I would like to save the arrays entropy_losses and value_losses as they exist at the beginning of line 284: 
https://github.com/DLR-RM/stable-baselines3/blob/ffe26ccf95d7e3b37067bd81025d3b4b45825038/stable_baselines3/ppo/ppo.py#L284
I don't think it's possible with callbacks: line 284 is inside PPO.train(), and there are no callback calls in this train() function. If you have any suggestions, I am all ears!

Thank you.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
The callbacks have access to the logger (cf. doc and other issues), if it doesn't work, you can use a fork of SB3.
