### ISSUE TITLE
Episodic learning of OnPolicy algorighthms like PPO

### ISSUE THREAD

**Issue by ss555** [DLR-RM/stable-baselines3#1565]
### ❓ Question

Is there a specific reason why only OffPolicy algorithms are enabled to train at the end of episode i.e **train_freq=[1,episode].**

So I absolutely need to have a learning done at the end of episode, for now I opted for PPO.
After small changes I was able to run PPO of stable-baselines3 without noticable change.
Did somebody verify the perfomance if we do learning every n-episode instead of n_steps for OnPolicy algorithms.

Best regards

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/1059 and https://github.com/DLR-RM/stable-baselines3/issues/1147

In short, both for performance reason (using a variable size list is much less efficient than a fixed sized array) and consistency (you don't know in advance how many steps an episode will be, and it becomes impractical with multiple envs) we only  have the `n_steps` available in SB3.

However, nothing prevents you from forking SB3 and having an episodic data collection.

**Comment by ss555** [comment]
yes, I understand the usefulness of training n_steps on partial trajectories with multiple environment.
