### ISSUE TITLE
[Question] Link with Gymnasium VectorEnv

### ISSUE THREAD

**Issue by paLeziart** [DLR-RM/stable-baselines3#1568]
### ❓ Question

Hello,
I wanted to use [an already-vectorized environment from Gymnasium](https://github.com/Farama-Foundation/Gymnasium/blob/78220765ea10c7983e2ff4886bbaf2d29a15d392/gymnasium/envs/classic_control/cartpole.py#L319), following the [method described for ProcGen, EnvPool or IsaacGym](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#sb3-and-procgenenv), stating that "To use SB3 with those tools, you must wrap the env with tool’s specific `VecEnvWrapper` that will pre-process the data for SB3".

I assumed this was already done by Gymnasium so I tried to run the following code:

```
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecMonitor

vec_env = gym.make_vec("CartPole-v1", num_envs=5, vectorization_mode="custom")
vec_env = VecMonitor(vec_env)

model = PPO("MlpPolicy", vec_env, verbose=1)
model.learn(total_timesteps=25000)
```

which raises an `Exception: Unrecognized type of observation <class 'tuple'>`

The `env_checker` cannot be used to investigate more this exception because it applies for environments that inherit from gym.Env, but this one inherits from gym.VecEnv (feature still pending #1251)

Since I am not expert in SB3 and Gymnasium, I wanted to know your opinion on that. Am I doing something wrong? Or is it an incompatibility on the Gymnasium side that does not provide the data in a way that is compatible for SB3? And, in that case, does that mean I have to write a custom VecEnvWrapper to convert the resulting observation in the proper format?

Thank you for your help,

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
please use SB3 VecEnv (see doc), gym VecEnv are not reliable/compatible with SB3 and will be replaced soon anyway.

if you look at the doc, you will need custom VecEnv wrapper (see envpool or usaac gym) if you you want to use gym vec env, as some conversion is needed.

**Comment by araffin** [comment]
> These incompatibility are linked to [this paragraph](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html#vecenv-api-vs-gym-api) right?

yes and Gym VecEnv has a different API than Gym too.

>  if I were to use 1000 or more envs compared to implementation where envs are directly handled with arrays/tensor 

it depends SB3 offers sequential and asynchronous (with subprocesses, there is a fully asynchronous version in SB3 contrib) VecEnv, you can take a look at https://colab.research.google.com/github/araffin/rl-tutorial-jnrr19/blob/sb3/3_multiprocessing.ipynb

But if you want to do batch computation on GPU, it is possible but you will need a custom VecEnv wrapper (we have links to examples in the doc).

**Comment by paLeziart** [comment]
@araffin Thanks again for the help! I did not found examples in the documentation (searching "GPU" only lead to some pages about how to use the GPU in a docker) but I found a few discussions in the closed issues about environment vectorization.
