### ISSUE TITLE
[Bug]: HER mixed ordering of desired_goal and achieved_goal

### ISSUE THREAD

**Issue by JonathanKuelz** [DLR-RM/stable-baselines3#1569]
### 🐛 Bug

When going through the code of the recently adapted HER, it seems that the order of `*args` for the `env_method` `compute_reward` is mixed up.

In the [code on the master branch](https://github.com/DLR-RM/stable-baselines3/blame/4eed3e97698a4cfbc910af1740ddfb85f8759b1e/stable_baselines3/her/her_replay_buffer.py#L313), the order of arguments is `obs["desired_goal"], next_obs["achieved_goal"], info`, whereas [previously](https://github.com/DLR-RM/stable-baselines3/blame/e5deeed16efb57c34ccdcb14692439154d970527/stable_baselines3/her/her_replay_buffer.py#L341) it was `transitions["next_achieved_goal"], transitions["desired_goal"], info` -- an ordering that is also consistent with other code in SB3, e.g. the [DummyDictEnv](https://github.com/DLR-RM/stable-baselines3/blob/4eed3e97698a4cfbc910af1740ddfb85f8759b1e/tests/test_vec_normalize.py#L76).

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [ ] I have provided a minimal working example to reproduce the bug
- [x] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
after a quick look, I think you are right but this should not affect the performance as `compute_reward()` is usually a distance (so symmetric with respect to input), I'll let @qgallouedec have the last word on that.

**Comment by qgallouedec** [comment]
@JonathanKuelz thanks for reporting!

(I'm just repeating what @araffin wrote, but as I was writing my message I would have been sad to delete it)

You're absolutely right, thank you for pointing that out!

In general, we use the desired and completed goals to calculate a (symmetrical) distance, so interchanging them is not a problem. However, it's conceivable that the reward could be calculated differently, and in this respect, these arguments must correctly ordered.

I'd be glad to receive a PR to fix this.
