### ISSUE TITLE
SubprocEnv does not call `reset()` when expected and `set_attr` behaves weirdly

### ISSUE THREAD

**Issue by fracapuano** [DLR-RM/stable-baselines3#1573]
### 🐛 Bug

I have a custom gym.Env (which passes all `check_env`) steps. Having started this project months ago, I am running on Gym 0.21.0 and SB3 1.8.0. 
My custom env has an attribute (`device_freeze`), which is used in the `reset()` method to trigger a change in the environment dynamics. The goal is to have a callback which every `n_timesteps` interact with my custom env and sets `device_freeze` to False. 
In this way, during the following call of the `reset()` method, the environment's dynamics are changed. Please note that changing the dynamics *at the end* of an episode---and not *during* the episode---is more than a whim: changing the environment dynamics within the episode goes against the MDP formulation that I am considering at the moment (or at least that's what I believe, open on theoretical feedback on this).

Here's the source code of the custom env (inheriting from another custom env which inherits from a BaseEvn subclassing gym.Env---it has been a long project ahahaha): 

```python
import numpy as np
from commons import BaseInterface
from .oscar import OscarEnv
from typing import Iterable, Text, Dict
from numpy.typing import NDArray

class MarcellaEnv(OscarEnv): 
    def __init__(self, 
                         [..., parent class args])
                         devices_and_bounds:Dict[Text, float]={"device1": 50., "device2": 6., "device2": 7.}):
        """
        This argument stores the list of devices used for multi-tasking training and the respective performance bounds. 
        """
        self.device_freeze = True # here the problematic argument
        self.devices_and_bounds = devices_and_bounds

        super().__init__(
           [...parent args]
        )

    @property
    def name(self): 
        return "marcella"
    
    def change_device(self):
        """
        Change the target device based on random selection if device freeze is not enabled.

        Returns:
            None

        Note:
            The method randomly selects a new device from the available devices and updates the target
            device and upper accordingly. This only happens if device freeze is not enabled.

        """
        if not self.device_freeze:
            new_device = np.random.choice(list(self.devices_and_bounds.keys()))
            self.target_device = new_device
            self.new_bound = self.devices_and_bounds[new_device]
            # entered the loop because device freeze was False, switch sets it to True
            self.device_freeze = True

    def reset(self)->NDArray:
        """Resets custom env attributes."""
        self._observation = self.observation_space.sample()
        self.change_device()
        self.update_current_net()

        self.timestep_counter= 0

        return self._get_obs()
```

The following is instead the callback code: 
```python
"""Custom callbacks to be used during training to record the learnign process."""
from stable_baselines3.common.callbacks import BaseCallback
import numpy as np
from stable_baselines3.common.vec_env import VecEnv
from typing import Text, Iterable

class MultiTask_Callback(BaseCallback): 
    """Custom callback inheriting from `BaseCallback`.

    :param verbose: (int) Verbosity level 0: not output 1: info 2: debug.

    Performs various actions when triggered (intended to be a child of EventCallback): 
        1. Evaluates current policy (for n_eval_episodes)
        2. Updates a current best_policy variable
        3. Logs stuff on wandb. More details on what is logged in :meth:_on_step.
    """
    def __init__(
            self,
            verbose:int=0):
        """Init function defines callback context."""
        super().__init__(verbose)
        
        self.devices_history = []

    def _on_step(self) -> bool:
        """
        This method will be called by the model after each call to `_env.step()`.
        For child callback (of an `EventCallback`), this will be called
        when the event is triggered.
        :return: (bool) If the callback returns False, training is aborted early.
        """
        # storing the current hardware used for training
        current_device = self.model.env.get_attr("target_device")

        # stores the target hardware the model has been currently training on
        self.devices_history.append(current_device)

        print(self.model.env.get_attr("device_freeze"), self.model.env.get_attr("target_device"))
        
        # flips the switch that prevents different devices to be chosen at episode init
        self.model.env.set_attr("device_freeze", False)
 
        return True
    
    def get_devices_history(self):
        """Returns the full history of hardware devices"""
        return self.devices_history
```

When using `DummyVecEnv` or `SubprocEnv` I obtain the following std-output from the callback execution within a training scipt: 

```bash
[True] ['device1']
[False] ['device1']
[False]  ['device1']
[False]  ['device1']
[False] ['device1']
[False] ['device1']
...
```
Which is not plausible, since the print is triggered every 30 timesteps and the maximal number of timesteps is set to 50. 
However, **if I modify the callback code in the following way**: 
```python
self.model.env.set_attr("device_freeze", False)
```
becomes: 
```python
for env_idx in range(self.model.env.num_envs):
      # manually changing, since setattr appears to be useless here
      self.model.env.envs[env_idx].unwrapped.device_freeze = False
```
Then the output I obtain is:
```bash
[True] ['device1']
[False]  ['device1']
[True]  ['device2']
[True]  ['device3']
[True]  ['device3']
[False]  ['device3']
[True] ['device1']
[True] ['device2']
[False] ['device2']
[True] ['device3']
[False]['device3']
````

My issue is that when this "forceful" fix would clearly not work for SubprocEnv (I've already tried) since SubprocEnv does not allow to iterate across envs. 

What is very weird here is the fact that `setattr` does not change the value of the `device_freeze` but once. Then, it looks like it is ignored even tho the callback `_on_step()` method is executed (one printed line per call).

Would really appreciate some help in figuring out why this!

### Code example

Code in issue message.

### Relevant log output / Error message

```shell
AttributeError: SubprocEnv does not have the envs attribute
```

### System Info

Libraries installed via pip. 

- OS: Linux-5.13.0-52-generic-x86_64-with-glibc2.31 # 59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022
- Python: 3.10.8
- Stable-Baselines3: 1.8.0
- PyTorch: 2.0.1+cu117
- GPU Enabled: True
- Numpy: 1.24.3
- Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Thank you for reporting. The actual MRE should be

```python
from stable_baselines3.common.env_util import make_vec_env

vec_env = make_vec_env("Pendulum-v1")
env = vec_env.envs[0].unwrapped
env.a = 0
vec_env.set_attr("a", 1)
assert env.a == vec_env.get_attr("a")[0] # AssertionError
```

Can be fixed by replacing

https://github.com/DLR-RM/stable-baselines3/blob/472ff8edb815070c405da913dcbe64c1a06e0e7d/stable_baselines3/common/vec_env/dummy_vec_env.py#L120-L122

by
 
```python
 target_envs = self._get_target_envs(indices) 
 for env_i in target_envs: 
     setattr(env_i.unwrapped, attr_name, value) 
```

@araffin can you confirm?

**Comment by fracapuano** [comment]
Thank you for your super sharp reply!

I see your fix being relative to DummyVecs only and fixing the bug that I am using to make things work now (this project is my MSc thesis ahahaha)

I am curious if you can give me some guidance on why the `set_attr` only works once? Theoretically it should trigger `device_freeze` to False, which on the next reset call would trigger the device change and switch `device_freeze` back to False. However, this does not happen and I only see the first value of `device_freeze` all along... 

I am madly interested in knowing why this happen

**Comment by araffin** [comment]
Hello,
@qgallouedec thanks for the simplification, much appreciated =)

i see the issue but i'm not sure if it's a bug. 
You can solve your problem by use a setter (using a method) instead of trying to modify the attribute directly (i'm also wondering, if you could call settattr on ".unwrapped" directly).
I think i also saw a similar issue on Gymnasium repo (but i don't recall if it was for gym wrappers or vec env).

**Comment by araffin** [comment]
With some code:
```python

import types

from stable_baselines3.common.env_util import make_vec_env

# Quick setter for the demo
def set_a(self, a):
    self.a = a

vec_env = make_vec_env("Pendulum-v1")
# Get unwrapped env
env = vec_env.envs[0].unwrapped
# Hack to show how it works with a setter
env.set_a = types.MethodType(set_a, env)


vec_env.env_method("set_a", 1.0)
print(vec_env.get_attr("a")[0])

```
This should solve your issue.

**Comment by fracapuano** [comment]
Will try this out tomorrow :)

(I don't see how using a setter solves this, maybe is just me tho)

**Comment by qgallouedec** [comment]
> (I don't see how using a setter solves this, maybe is just me tho)

import gymnasium as gym
from gymnasium import spaces

from stable_baselines3.common.env_util import make_vec_env


class MyEnv(gym.Env):
    def __init__(self) -> None:
        super().__init__()
        self.observation_space = spaces.Box(0, 1, (1,))
        self.action_space = spaces.Discrete(2)

    def reset(self, **kwargs):
        return self.observation_space.sample(), {}

    def step(self, action):
        return self.observation_space.sample(), 0.0, False, False, {}

    def set_a(self, new_a):
        self.a = new_a


vec_env = make_vec_env(MyEnv)
env = vec_env.envs[0].unwrapped
env.a = 0
vec_env.env_method("set_a", 1)
assert env.a == vec_env.get_attr("a")[0]

**Comment by fracapuano** [comment]
Maybe I am clear in what I ask. I am asking you to produce code I could then reuse (even tho I very much appreciate it). I am asking you to explain *why* I observe this behavior

**Comment by qgallouedec** [comment]
This is because environments are wrapped in a monitor wrapper. `set_attr` sets the attribute of the wrapper and not of the inner environment.

**Comment by fracapuano** [comment]
Uh, I see

Why does it work once tho?

**Comment by qgallouedec** [comment]
> Why does it work once tho? Once being the first time the method is called

It doesn't. [here](https://github.com/DLR-RM/stable-baselines3/issues/1573#issuecomment-1606157693) the method is called once, and attribute of the inner env does not change.

**Comment by fracapuano** [comment]
> This is because environments are wrapped in a monitor wrapper. `set_attr` sets the attribute of the wrapper and not of the inner environment.

Can we agree this behavior is somewhat unexpected? What is the rationale behind having these two layers in VecEnv?

**Comment by fracapuano** [comment]
For what's worth it, I think mentioning it in the documentation is more than enough. Also, having this issue here will probably already help out the next ones who are going to have this issue. I really couldn't find anything online :(

**Comment by qgallouedec** [comment]
If you want to submit this improvement in the documentation, I encourage you to open a PR :)

**Comment by araffin** [comment]
I agree it is not intuitive and would definitely welcome a PR =), but I also think it is more a Gym issue, see discussion https://github.com/Farama-Foundation/Gymnasium/issues/357 and https://github.com/Farama-Foundation/Gymnasium/pull/358

**Comment by fracapuano** [comment]
Hey there! Would love to do a PR to sb3 - I have been using the library forever and I would love contribute. 
Only thing is that I am working around the clock to finish my MSc thesis atm and would start working on this PR not earlier than a couple of weeks from now. Is this timeline ok with you all @araffin @qgallouedec ?

**Comment by qgallouedec** [comment]
Yes, it sounds good!

**Comment by fracapuano** [comment]
Hey there! 
I was wondering if anybody could offer some guidance on how to exactly contribute to the documentation as we were discussing

**Comment by richy330** [comment]
I also ran into this issue a few days ago, thanks for the fix mentioned here! I agree that this behavior could definitely be mentioned in the documentation, and maybe also in the tutorials (i guess changing environment behavior during training would not be uncommon, and could bite many more people to come). Also the list attribute `envs` on vectorized environments was new to me and is not mentioned in the documentation i believe.

**Comment by fracapuano** [comment]
Hey! Sorry it took some time, been busy :(

Looking forward to hearing back from you guys with some feedback :)
