### ISSUE TITLE
[Question] Roadblocks to using SB3 for multi-agent settings

### ISSUE THREAD

**Issue by elliottower** [DLR-RM/stable-baselines3#1575]
### ❓ Question

Hi, I was just wondering if there were any specific things I should be aware of that would cause issues with training agents in multi-agent settings. 

In a previous issue back in march you mentioned SB3 is for model free single agent RL, which is totally fair to not natively support it and have to answer questions and provide documentation, etc. I’ve just had a number of people asking in the Farama discord or pettingzoo issues about getting SB3 to work, and I figured it would be good to touch base and see if this would have major problems, before trying to mess around and write my own tutorial (to be in the pettingzoo tutorials, can totally get you not wanting that kind of stuff on here officially)

Super appreciative of all the work you’ve put into this library and especially the big push for gymnasium support.

A side note is I’m planning to add some links and information to SB3 in gymnasium somewhere, as many users have asked about it and now that your entire docs site is using gymnasium it’s probably the most comprehensive set of tutorials/starter code for new users. If you’d like to give any specific pointers or have thoughts about that I can send you the pr for when I do add it.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

>  if there were any specific things I should be aware of that would cause issues with training agents in multi-agent settings.

I'm afraid I don't have enough experience in MA RL (almost none) to give you any advice.
But if you have more specific questions, I would happy to answer.

> Super appreciative of all the work you’ve put into this library and especially the big push for gymnasium support.

Thanks =)

> A side note is I’m planning to add some links and information to SB3 in gymnasium somewhere

Good to hear =)

> If you’d like to give any specific pointers or have thoughts about that I can send you the pr for when I do add it.

Yes, you can do that and tag @qgallouedec too (I deactivated notifications from gymnasium repo though, best would be to contact me on discord).
