### ISSUE TITLE
[Question] Relation between gradient_steps, train_freq and batch_size.

### ISSUE THREAD

**Issue by luiz0992** [DLR-RM/stable-baselines3#1576]
### ❓ Question

Hi,

I saw the documentation for the TD3 model and there are three flags I am confused

```
train_freq (Union[int, Tuple[int, str]]) – Update the model every train_freq steps. Alternatively pass a tuple of frequency and unit like (5, "step") or (2, "episode").

gradient_steps (int) – How many gradient steps to do after each rollout (see train_freq) Set to -1 means to do as many gradient steps as steps done in the environment during the rollout.

batch_size (int) – Minibatch size for each gradient update
```

I am confused about the relation and difference of these three parameters: `train_freq`, `gradient_steps`, and `batch_size`. 

For example, if we set `train_freq = (16, 'steps')` and `gradient_steps = 4`, and the `episode length=16` steps. Then, the model will be updated every 16 steps. But we will calculate the gradients 4 times during one episode (16 steps). Do we use the 4 gradients to update the model once?

Also, if the `batch_size = 8`, does that mean we update the model twice every episode? If so, then this is a conflict with train_freq.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by SteamerLee** [comment]
Up to my understanding and a given example (train_freq = (16, 'steps'), gradient_steps = 4, episode length=32, and batch_size = 8), TD3 enters the train() function every 16 timepoints. Then in the train() function, it repeatly extracts 8 samples and updates the model for 4 times. In an episode, TD3 will execute above steps for 2 times (32/16=2). Thanks!

**Comment by luiz0992** [comment]
Great!

Thanks @araffin  and @SteamerLee. Still need to wrap my head around it, but still much clearer.
