### ISSUE TITLE
[Bug]: ValueError: high is out of bounds for int32

### ISSUE THREAD

**Issue by MikhailGerasimov** [DLR-RM/stable-baselines3#1579]
### 🐛 Bug

Hi.

SB3 v2.0
The following code causes an error on Win64.  

https://github.com/DLR-RM/stable-baselines3/blob/472ff8edb815070c405da913dcbe64c1a06e0e7d/stable_baselines3/common/vec_env/base_vec_env.py#L281

The reason is:
https://stackoverflow.com/a/36279549/2965317

Steps to reproduce:
Just create a Env calling make_vec_env on Windows x64

If I set the dtype=np.int64 everting works. On Linux runs without changes.

It was introduced by this commit: https://github.com/DLR-RM/stable-baselines3/commit/9c338f917a822c8be13b1aa9f7b2319770481b62#diff-fbbbeff0096dec393a26abdfb588b08aede5e15e5b9a0e7ff4f5ea45fc031896

### To Reproduce

```python
from stable_baselines3 import ...
make_vec_env("CartPole-v1", n_envs=2)
```

### Relevant log output / Error message

```shell
seed = np.random.randint(0, 2**32 - 1)
File "mtrand.pyx", line 746, in numpy.random.mtrand.RandomState.randint
File "_bounded_integers.pyx", line 1336, in numpy.random._bounded_integers._rand_int32
ValueError: high is out of bounds for int32
```
```


### System Info

- OS: Windows-10-10.0.22621-SP0 10.0.22621
- Python: 3.10.10
- Stable-Baselines3: 2.0.0
- PyTorch: 2.0.0
- GPU Enabled: True
- Numpy: 1.23.5
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1
- OpenAI Gym: 0.21.0

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue.
I guess an easy fix is to pass a seed explicitly? 

A longer term fix to have a an `if` condition that check the platform?

**Comment by MesmerV** [comment]
Temporary fix for those using `make_vec_env` in win64: manually settinf the seed so the faulty line isn't called.

```python
from stable_baselines3.common.env_util import make_vec_env
make_vec_env("CartPole-v1",seed=1, n_envs=2)
```

**Comment by MikhailGerasimov** [comment]
@araffin 
I would suggest fixing it by explicitly setting the data type. In this case, NumPy ignores platform-dependent defaults.
`seed = np.random.randint(0, 2**32 - 1, dtype=np.int64 ) `

**Comment by araffin** [comment]
then i would welcome a pr that fixes this issue =)
