### ISSUE TITLE
[Bug]: MultiDiscrete Policies are not Cartesian Products

### ISSUE THREAD

**Issue by nollied** [DLR-RM/stable-baselines3#1599]
### 🐛 Bug

Create a PPO class with a gym environment who's action space is a multi discrete wtih a shape of something like (10, 5, 5). The resulting model's policy head output will be 10 + 5 + 5 = 20 instead of 10 * 5 * 5 = 250. 

This causes catastrophic silent failures. I'm not sure if this is the case for other spaces or algorithms, but this is a pretty big issue for those using multi dimensional action spaces.

### To Reproduce

Can't share my environment.

### Relevant log output / Error message

```shell
No errors, it's silent for my case.
```

### System Info

- OS: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.17 # 1 SMP Fri Jan 27 02:56:13 UTC 2023
- Python: 3.8.12
- Stable-Baselines3: 2.0.0a9
- PyTorch: 2.0.0+cu117
- GPU Enabled: True
- Numpy: 1.23.1
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1
- OpenAI Gym: 0.26.2

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by nollied** [comment]
i'm personally able to work around this, but others might not be able to depending on their envs.

**Comment by pseudo-rnd-thoughts** [comment]
SB3 is correct in its implementation as `MultiDiscrete` is equivalent to a tuple of `Discrete` space, i.e., the spaces are independent of each other - https://gymnasium.farama.org/api/spaces/fundamental/#multidiscrete
What you actually have is just a discrete space with 250 options which is more elegantly represented as a tuple of 3 elements

**Comment by nollied** [comment]
@pseudo-rnd-thoughts interesting. should that be documented? i feel like it's quite counter-intuitive, as per their own definition in the link you sent they define the space as the cartesian product of spaces, right? shouldn't that mean you multiply their sizes together to get the total number of actions available? 

if actions being independent is what is shown to be best by the literature to be best, then i understand, but in my intuition it feels like a composite of the spaces should be multiplicative.

however, i guess it makes sense because in this way of keeping them independent, then you can represent them as N (where N=len of shape) different gaussians.

**Comment by pseudo-rnd-thoughts** [comment]
Yes, multi discrete is a Cartesian product in the sense that the space contain any element of the product of sub discrete spaces. 

While it is possible to utilise the multi discrete where the sub actions are dependent on each other. It looks like sb3 implement this such that the actions are independent of each other. I.e., I can sample each action without knowledge of the other actions chosen. This is in line with the space's sample function.

Therefore, if you require sampling where the sub actions are dependant each other, I would use the discrete space.

**Comment by nollied** [comment]
@pseudo-rnd-thoughts ah yeah seems like this is an open research question as to which is better. this may be worth exploring? my intuition tells me that having dependent action spaces (which would essentially be a multi-modal distribution) is better since actions are intuitively dependent. like, i wouldn't press left AND right on the d-pad at the same time for instance.

anyways, yeah we can close this issue. but it might be worth adding a little flag in there to allow this. i was really interested in trying it out, but there isn't an easy way to do it without modifying the code.

![image](https://github.com/DLR-RM/stable-baselines3/assets/26421036/7ae76cfe-66c4-481a-a4e5-8a6c0f94d234)
[source](https://iclr-blog-track.github.io/2022/03/25/ppo-implementation-details/)

**Comment by pseudo-rnd-thoughts** [comment]
This is fair but in the end, sb3 has correctly implemented a `MultiDiscrete` policy that aligns with the `MultiDiscrete.sample` function. 
I agree that dependant action spaces are an interesting research area but this would require new algorithms for PPO, etc as Costa points out in the article. 
Therefore, we agree that this is not a bug.
If you want $prob(a) = prob(a^1) prob(a^2)$ I would use a Discrete space

**Comment by nollied** [comment]
@pseudo-rnd-thoughts cool, thanks!
