### ISSUE TITLE
[Question] What`s the difference if set deterministic=True or False when evaluate a trained sac agent

### ISSUE THREAD

**Issue by akux2021** [DLR-RM/stable-baselines3#1600]
### ❓ Question

I noticed "SAC predict() method has now deterministic=False by default for consistency. To match SB2 behavior, you need to explicitly pass deterministic=True"

After I trained a sac agent and evaluated it, I found that set deterministic=False or True seems will not affect reward, but set deterministic=False will provide much diverse action.

Should I set deterministic=True when testing the SAC agent or keep the default setting (deterministic=False)?
What`s the difference between these two settings in SAC when evaluating the agent after training?

Thanks!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by ReHoss** [comment]
@akux2021 
Your learn a stochastic policy, i.e. a state-dependent distribution of actions. When used, actions are sample with respect to this state-dependent distribution.

In the other hand, the deterministic policy, always outputs the mode https://en.wikipedia.org/wiki/Mode_(statistics) in `stable-baselines3`.

Applying one or the other in practice depends on your problem, but the algorithm learns to maximise the rewards under a stochastic policy.

**Comment by hanqing-yu** [comment]
> Applying one or the other in practice depends on your problem, but the algorithm learns to maximise the rewards under a stochastic policy.

@ReHoss Hi, I am confused that if we are training a stochastic policy, why should we evaluate it deterministically instead of stochastically? In some case where there exist an optimal deterministic policy, does setting deterministic=True guarantee that the induced deterministic policy is better than stochastic one?

**Comment by ReHoss** [comment]
> > Applying one or the other in practice depends on your problem, but the algorithm learns to maximise the rewards under a stochastic policy.
> 
> [@ReHoss](https://github.com/ReHoss) Hi, I am confused that if we are training a stochastic policy, why should we evaluate it deterministically instead of stochastically? In some case where there exist an optimal deterministic policy, does setting deterministic=True guarantee that the induced deterministic policy is better than stochastic one?

That's a good remark. I had the same question too.

There are two point of views to discuss this. The practical vs. the theoretical.

In practice and intuitively, learning under a stochastic policy is more robust (this is theoretically proven) to change in the underlying reward or state transition function.
If I remember correctly, `deterministic=True` always samples the **mode** of the stochastic policy (which is also the mean in the Gaussian case). The idea behind choosing `deterministic=True` for inference is that a stochastic policy is needed only for exploration (see DDPG [2]), thus during training.
However, one ends up using a deterministic policy that is different than the stochastic policy solving the learning objective.
But practitioners are fine with this usage.

In theory, I am not aware of any result saying the deterministic policy obtained by choosing the mode of an optimal stochastic policy is still optimal. As you said, in the fully observed case, there always exists a deterministic solution so the resulting question is, does the mean function of the gaussian policy is the optimal deterministic policy ?



[1]: B. Eysenbach, S, Levine - Maximum Entropy RL (Provably) Solves Some Robust RL Problems (2022)
[2]: T. P. Lillicrap et al. - Continuous Control with Deep Reinforcement Learning (2016)
