### ISSUE TITLE
[feature request] is it necessary to add another rollout buffer to check if the policy network is overfitting?

### ISSUE THREAD

**Issue by wujiren** [DLR-RM/stable-baselines3#161]
if the algorithm has two rollout buffer, one is collected for training, another collect relative small number of data to check the network is overfitted or not. is it possible or necessary? 
maybe only some on-policy algorithm can use it

**Comment by araffin** [comment]
Hello,
I think you should read the "evaluation" part of the RL tips in the doc ;)
https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#how-to-evaluate-an-rl-algorithm

You may also read the paper "RL that matters".
