### ISSUE TITLE
[Question] when is an environment reset?

### ISSUE THREAD

**Issue by yichao-liang** [DLR-RM/stable-baselines3#1613]
### ❓ Question

Hi,

I'm wondering when is the environment reset when using, e.g., the PPO algorithm. I've delved into the algorithm thoroughly but couldn't identify the exact mechanism for this, and would greatly appreciate your guidance.

Is the environment reset triggered every time `collect_rollout` is invoked, as seen [here](https://github.com/DLR-RM/stable-baselines3/blob/d68ff2e17f2f823e6f48d9eb9cee28ca563a2554/stable_baselines3/common/on_policy_algorithm.py#L259)? If this is the case, does it imply that the policy only interacts with the initial n_rollout_steps within the environment?

In contrast, should the environment be reset each time the status is marked as done, I am uncertain about the implications if the number of rollouts does not yet reach n_rollout_steps. Would the collection process persist within the same environment post-task completion (or once the max_episode_length is attained), or does the environment reset and start collection afresh?

Thank you very much for your time and assistance in this matter. I look forward to your invaluable insights on these queries.

Best,
Yichao

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [x] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

> I'm wondering when is the environment reset when using, e.g., the PPO algorithm. I've delved into the algorithm thoroughly but couldn't identify the exact mechanism for this, and would greatly appreciate your guidance.

Diving into the code should be done after reading the doc ;)

> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

We have several issues and documentation about your first question, I let you find the answer.

> Would the collection process persist within the same environment post-task completion (or once the max_episode_length is attained), or does the environment reset and start collection afresh?

We collect `n_steps` transitions before each update but we keep the state of the env in between.
One thing that we do to account for un-finished episodes is that we use bootstrap using the value function to estimate the return for un-finished trials.
I recommend you to read the blog post about PPO (link in our doc).
