### ISSUE TITLE
[Bug]: baselines3==1.7.0 setup.py egg info error

### ISSUE THREAD

**Issue by skgr07** [DLR-RM/stable-baselines3#1619]
### 🐛 Bug

![화면 캡처 2023-07-23 003327](https://github.com/DLR-RM/stable-baselines3/assets/132796787/0026864b-2a20-4700-b968-1c18ee8fa7c3)
![화면 캡처 2023-07-23 004855](https://github.com/DLR-RM/stable-baselines3/assets/132796787/e9a091b5-576a-4fa6-9aa6-c43436fec23b)
I had error while using DQN example code, and I found someone who solved this problem by downgrading stablebaselines. So, I tried downgrading stablebaselines, and it is what i got.

### To Reproduce

```
conda activate (virtual environment)
pip install stable_baselines3==1.7.0
```

### Relevant log output / Error message

```shell
(airsim) C:\Users\user>pip install stable_baselines3==1.7.0
Collecting stable_baselines3==1.7.0
  Using cached stable_baselines3-1.7.0-py3-none-any.whl (171 kB)
Collecting gym==0.21 (from stable_baselines3==1.7.0)
  Using cached gym-0.21.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

please check harder next time, there are many duplicates both on sb3 and gym repos.
