### ISSUE TITLE
[Question] switch models for the same environment

### ISSUE THREAD

**Issue by xibeisiber** [DLR-RM/stable-baselines3#1621]
### ❓ Question

Hi,
Based on the same custom gym environment, I trained two models corresponding to two tasks.

Now my demand is to switch one model to the other during simulation. Since the tasks are different, the normalized vectors of the observation are slightly different. Therefore before using `predict() `of the second model, I need to switch the normalized vector using `env = VecNormalize.load(vecnormfile2, env)`, right?

Currently the task switching behavior is desired. I'm trying to find where the problem is.  The first question is that the original obs is slightly different immediately after the vecnorm file is changed without any` step()`.
```
obs1 = env.get_original_obs()
env = VecNormalize.load(vecnormfile2, env)
obs2 = env.get_original_obs()
```
i.e. `obs1!=obs2`.

What am I missing here?
Thanks！

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Therefore before using predict() of the second model, I need to switch the normalized vector using env = VecNormalize.load(vecnormfile2, env), right?

probably although it would be better to have the same normalization for both envs.

> i.e. obs1!=obs2.

this is normal as it seems you are wrapping the env twice with a `VecNormalize` wrapper.
