### ISSUE TITLE
Hybrid PPO

### ISSUE THREAD

**Issue by SimRey** [DLR-RM/stable-baselines3#1624]
### 🚀 Feature

Hi everyone,

I hope you're all doing well. I wanted to explore the possibility of contributing to this fantastic library. As part of my Master's thesis, I've come across the need to utilize a Hybrid PPO, based on the research outlined in this paper: https://arxiv.org/pdf/1903.01344.pdf.

It would be great to implement this algorithm in this library. To implement this approach effectively, I had the opportunity to discuss the topic with @AlexPasqua, who has already made significant contributions to the library. He has generously offered to provide guidance and support throughout my implementation process.

Thanks again and hopefully sounds interesting.

Best regards,
Simone

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
Hello,
please move that issue to the sb3 contrib repo, and make sure to fill the issue template completely (and read the contributing guide, bit different from sb3 one).
