### ISSUE TITLE
[Question] Possibility of including Multi Agent Reinforcement Learning

### ISSUE THREAD

**Issue by berttggg** [DLR-RM/stable-baselines3#1626]
### ❓ Question

Hi, I am wondering if recently or lately, will the developers include multi-agent reinforcement learning (MARL) model? If yes, will they be adapted to robotics platforms such as Omniverse Isaac Gym and Issac Sim Orbit? Thank you!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
You'll probably find the answer here: #69

**Comment by araffin** [comment]
If you meant support for massively parallel simulators and not just MARL, please take a look at the doc.
