### ISSUE TITLE
SAC/TD3 Train Logger for Actor/Critic loss

### ISSUE THREAD

**Issue by mloo3** [DLR-RM/stable-baselines3#163]
I was testing with both SAC and TD3, and it seems like SAC logs actor/critic loss, but TD3 does not. I was wondering if there was a specific reasoning for this. 

https://github.com/DLR-RM/stable-baselines3/blob/f5104a5efca7d1aefbbbb86a41a19c156f6abb2d/stable_baselines3/sac/sac.py#L264-L269

https://github.com/DLR-RM/stable-baselines3/blob/f5104a5efca7d1aefbbbb86a41a19c156f6abb2d/stable_baselines3/td3/td3.py#L173-L174

**Comment by Miffyli** [comment]
Indeed this looks like bit of a bug. @araffin ?

**Comment by araffin** [comment]
I forgot to add that logging... this was because before, I had two method for training the actor and the critic (because I was trying CEM-RL) and it was harder to get the losses at a same place.
But we would appreciate a PR that solves that issue ;)
