### ISSUE TITLE
[Question] Single environment video

### ISSUE THREAD

**Issue by clarkphd** [DLR-RM/stable-baselines3#1631]
### ❓ Question

When using VecVideoRecorder with SubprocVecEnv is is possible to record just one environment out of the many sub processes? 
The documentation for the trigger only allows you to choose it by intervals of steps?

The following makes a cartpole environment and the subsequent videos have both environments in them.  

```
import gym
from stable_baselines3 import  PPO
from stable_baselines3.common.utils import set_random_seed
from stable_baselines3.common.vec_env import (SubprocVecEnv, VecMonitor,
                                              VecVideoRecorder)

def make_env(env_id, rank, seed=0):
    """
    Utility function for multiprocessed env.

    :param env_id: (str) the environment ID
    :param num_env: (int) the number of environments you wish to have in subprocesses
    :param seed: (int) the inital seed for RNG
    :param rank: (int) index of the subprocess
    """
    def _init():
        env = gym.make(env_id)
        env.seed(seed + rank)
        return env
    set_random_seed(seed)
    return _init

if __name__ == '__main__':
    env_id = 'CartPole-v0'
    num_cpu = 2  # Number of processes to use
    # Create the vectorized environment
    kwargs = {}
    env = SubprocVecEnv([make_env(env_id, i)
                        for i in range(num_cpu)])
    # Wrap it
    env = VecMonitor(env)
    # Record video
    env = VecVideoRecorder(
        env, "./videos", record_video_trigger=lambda x: x % 2000 == 0, video_length=200)
    model = PPO('MlpPolicy', env, verbose=1)
    model.learn(total_timesteps=25000)
```

producing

https://github.com/DLR-RM/stable-baselines3/assets/79987173/d0c7f69f-cc78-46da-8f5c-4cdf64e7109a

<video width="320" height="240" controls>
  <source src=["movie.mp4"](https://github.com/DLR-RM/stable-baselines3/assets/79987173/d0c7f69f-cc78-46da-8f5c-4cdf64e7109a) type="video/mp4">
</video>

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
One solution is to wrap your vec env with

```python
from stable_baselines3.common.vec_env import VecEnvWrapper


class SingleEnvRender(VecEnvWrapper):
    def get_images(self):
        return [self.venv.get_images()[0]]
```

**Comment by qgallouedec** [comment]
SB3 does not provide this feature. The quick workaround is to modify the sb3 source code a little:

https://github.com/DLR-RM/stable-baselines3/blob/ba77dd7c6180c0ec9a47dfa98291c2103e6750df/stable_baselines3/common/vec_env/base_vec_env.py#L246

to

```python
    images = [self.get_images()[0]]
```

**Comment by clarkphd** [comment]
> 

Is there any way of doing this without editing the source code? I use it with wandb and train across a cluster so recording a video with every environment is a bit of a pain when there are 60 all in a grid!

**Comment by qgallouedec** [comment]
It's a bit hacky, but it works.

```python
import types

from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv, VecVideoRecorder


def get_images(self):
    self.remotes[0].send(("render", None))
    return [self.remotes[0].recv()]


if __name__ == "__main__":
    env_id = "CartPole-v0"
    vec_env = make_vec_env(env_id, n_envs=2, vec_env_cls=SubprocVecEnv)
    vec_env.get_images = types.MethodType(get_images, vec_env)
    vec_env = VecVideoRecorder(vec_env, "./videos", record_video_trigger=lambda x: x % 2000 == 0, video_length=200)
    PPO("MlpPolicy", vec_env).learn(total_timesteps=25000)
```

**Comment by clarkphd** [comment]
> It's a bit hacky, but it works.
> 
> ```python
> import types
> 
> from stable_baselines3 import PPO
> from stable_baselines3.common.env_util import make_vec_env
> from stable_baselines3.common.vec_env import SubprocVecEnv, VecVideoRecorder
> 
> 
> def get_images(self):
>     self.remotes[0].send(("render", None))
>     return [self.remotes[0].recv()]
> 
> 
> if __name__ == "__main__":
>     env_id = "CartPole-v0"
>     vec_env = make_vec_env(env_id, n_envs=2, vec_env_cls=SubprocVecEnv)
>     vec_env.get_images = types.MethodType(get_images, vec_env)
>     vec_env = VecVideoRecorder(vec_env, "./videos", record_video_trigger=lambda x: x % 2000 == 0, video_length=200)
>     PPO("MlpPolicy", vec_env).learn(total_timesteps=25000)
> ```

Doesn't seem to work for me. I still seem to get two videos.

**Comment by qgallouedec** [comment]
Sorry to ask, but can you please double check? It seems very odd that the exact same code gives the stacking of two videos in your system but not in mine. @araffin, can you take a quick look?

**Comment by clarkphd** [comment]
Yes I have double-checked now. Apologies earlier I ran it on my own environment and it still produced two videos. Running the exact same code as above I get an error in fact.


`
2023-07-28 08:57:10.098 python[86602:7558285] Connection Invalid error for service com.apple.hiservices-xpcservice.
2023-07-28 08:57:10.098 python[86602:7558269] Error received in message reply handler: Connection invalid
2023-07-28 08:57:10.125 python[86602:7558269] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection invalid
Traceback (most recent call last):
  File "/Users/edwardclark/Documents/MARLIN/dev/dev_question.py", line 65, in <module>
    PPO("MlpPolicy", vec_env).learn(total_timesteps=25000)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/stable_baselines3/ppo/ppo.py", line 317, in learn
    return super().learn(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 246, in learn
    total_timesteps, callback = self._setup_learn(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 489, in _setup_learn
    self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 68, in reset
    self.start_video_recorder()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 79, in start_video_recorder
    self.video_recorder.capture_frame()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/gym/wrappers/monitoring/video_recorder.py", line 132, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 183, in render
    bigimg = tile_images(imgs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 32, in tile_images
    n_images, height, width, n_channels = img_nhwc.shape
ValueError: not enough values to unpack (expected 4, got 1)
Exception ignored in: <function VecVideoRecorder.__del__ at 0x13585a670>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 112, in __del__
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/stable_baselines3/common/vec_env/vec_video_recorder.py", line 108, in close
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: <function VideoRecorder.__del__ at 0x12188c310>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/gym/wrappers/monitoring/video_recorder.py", line 197, in __del__
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/gym/wrappers/monitoring/video_recorder.py", line 164, in close
AttributeError: 'NoneType' object has no attribute 'remove'
`

**Comment by araffin** [comment]
> Sorry to ask, but can you please double check? It seems very odd that the exact same code gives the stacking of two videos in your system but not in mine. @araffin, can you take a quick look?

The video recording works but the code crash after.
Upgrading to gymnasium 0.29 solves the issue.

**Comment by jamesheald** [comment]
> def get_images(self):
>     self.remotes[0].send(("render", None))
>     return [self.remotes[0].recv()]

This also didn't work for me.

I created a subclass of SubprocVecEnv that takes an argument num_env_render specifying how many environments to render.

```
class SubprocVecEnvRenderSubset(SubprocVecEnv):

    def __init__(self, env_fns: list[Callable[[], gym.Env]], start_method: Optional[str] = None, num_env_render = int):
        super().__init__(env_fns, start_method)
        self.num_env_render = num_env_render

        assert num_env_render <= len(env_fns), f"The number of environments to render must be less than or equal to the number of environments"

    def get_images(self) -> Sequence[Optional[np.ndarray]]:
        if self.render_mode != "rgb_array":
            warnings.warn(
                f"The render mode is {self.render_mode}, but this method assumes it is `rgb_array` to obtain images."
            )
            return [None for _ in self.remotes[:self.num_env_render]]
        for pipe in self.remotes[:self.num_env_render]:
            # gather render return from subprocesses
            pipe.send(("render", None))
        outputs = [pipe.recv() for pipe in self.remotes[:self.num_env_render]]
        return outputs
```
