### ISSUE TITLE
[Bug] in `env_checker.py` observation space upper and lower bounds check

### ISSUE THREAD

**Issue by Gabo-Tor** [DLR-RM/stable-baselines3#1632]
### 🐛 Bug

Currently, the Gym Environment Checker does not output the correct warning message when dealing with observation spaces that have different upper and different lower bounds.

For example, 
given the observation space `Box([ 0.  -1000. ], [ 100.  1000.], (2,), float32)`
and the observation `[-100, -200]` 
the incorrect warning would be displayed as follows `Expected: obs >= -1000.0, actual min value: -200.0 at index 1`

Code snippets from `env_checker.py` where the bug occurs by using max and argmax:
```python
if isinstance(observation_space, spaces.Box):
    assert np.all(obs >= observation_space.low), (
        f"The observation returned by the `{method_name}()` method does not match the lower bound "
        f"of the given observation space {observation_space}."
        f"Expected: obs >= {np.min(observation_space.low)}, "
        f"actual min value: {np.min(obs)} at index {np.argmin(obs)}"
    )
    assert np.all(obs <= observation_space.high), (
        f"The observation returned by the `{method_name}()` method does not match the upper bound "
        f"of the given observation space {observation_space}. "
        f"Expected: obs <= {np.max(observation_space.high)}, "
        f"actual max value: {np.max(obs)} at index {np.argmax(obs)}"
    )
```
I can fix `env_checker.py`, extend the tests, and submit a PR if that's okay with you

### Relevant log output / Error message

```shell
assert np.all(obs >= observation_space.low), (
AssertionError: The observation returned by the `reset()` method does not match the lower bound of the given observation space Box([    0.     0. -1000. -1000.    -1.    -1. -1000.], [ 100.  100. 1000. 1000.    1.    1. 1000.], (7,), float64).Expected: obs >= -1000.0, actual min value: -100.0 at index 0
```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
you're right, please go ahead =)
