### ISSUE TITLE
[Bug]: str indexing in utils.py:is_vectorized_dict_observation()

### ISSUE THREAD

**Issue by stwykd** [DLR-RM/stable-baselines3#1637]
### 🐛 Bug

`key` is from `for key, subspace in observation_space.spaces.items():`
the type of `observation_space.spaces` is `dict[str, Space[Any]]`

Seems to me `key` is always `str` and observation always a `ndarray`.
The error is because you can't index index into an `ndarray` with `str`

### To Reproduce

```python
from stable_baselines3 import PPO
env1 = gym.make('FetchReach-v2')
model = PPO("MultiInputPolicy", env1, verbose=1)
model.learn(total_timesteps=100)
obs = env.reset()
for _ in range(1000):
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, done, info = env.step(action)
    env.render()
    if done:
      obs = env.reset()
```

### Relevant log output / Error message

```shell
action, _states = model.predict(obs, deterministic=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stwykd/mambaforge/envs/fetch/lib/python3.11/site-packages/stable_baselines3/common/base_class.py", line 555, in predict
    return self.policy.predict(observation, state, episode_start, deterministic)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stwykd/mambaforge/envs/fetch/lib/python3.11/site-packages/stable_baselines3/common/policies.py", line 346, in predict
    observation, vectorized_env = self.obs_to_tensor(observation)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stwykd/mambaforge/envs/fetch/lib/python3.11/site-packages/stable_baselines3/common/policies.py", line 264, in obs_to_tensor
    vectorized_env = is_vectorized_observation(observation, self.observation_space)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stwykd/mambaforge/envs/fetch/lib/python3.11/site-packages/stable_baselines3/common/utils.py", line 400, in is_vectorized_observation
    return is_vec_obs_func(observation, observation_space)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stwykd/mambaforge/envs/fetch/lib/python3.11/site-packages/stable_baselines3/common/utils.py", line 350, in is_vectorized_dict_observation
    if observation[key].shape != subspace.shape:
       ~~~~~~~~~~~^^^^^
```

### System Info

python -c 'import stable_baselines3 as sb3; sb3.get_system_info()'
- OS: macOS-13.5-arm64-i386-64bit Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
- Python: 3.11.4
- Stable-Baselines3: 2.0.0
- PyTorch: 2.0.1
- GPU Enabled: False
- Numpy: 1.23.5
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> My issue does not relate to a custom gym environment. (Use the custom gym env template instead)

**Comment by qgallouedec** [comment]
It's

> I was using the Gymnasium Robotics environment. I didn't think of it as a custom environment since it's from Farama
> 
> I've run the environment checker and this is the output
> 
> ```
> >>> import gymnasium as gym
> >>> env1 = gym.make('FetchReach-v2')
> >>> check_env(env1)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/stwykd/mambaforge/envs/fetch/lib/python3.11/site-packages/stable_baselines3/common/env_checker.py", line 438, in check_env
>     _check_returned_values(env, observation_space, action_space)
>   File "/Users/stwykd/mambaforge/envs/fetch/lib/python3.11/site-packages/stable_baselines3/common/env_checker.py", line 315, in _check_returned_values
>     assert isinstance(reward, (float, int)), "The reward returned by `step()` must be a float"
> AssertionError: The reward returned by `step()` must be a float
> ```

This is because the reward is a `numpy.float32` (and not a builtin python float). This shouldn't be a problem, but feel free to open an issue in the Gymnasium Robotics repo.

**Comment by qgallouedec** [comment]
> ```python
> from stable_baselines3 import PPO
> env1 = gym.make('FetchReach-v2')
> model = PPO("MultiInputPolicy", env1, verbose=1)
> model.learn(total_timesteps=100)
> obs = env.reset()
> for _ in range(1000):
>     action, _states = model.predict(obs, deterministic=True)
>     obs, reward, done, info = env.step(action)
>     env.render()
>     if done:
>       obs = env.reset()
> ```

> * Gymnasium: 0.28.1


Please double-check you code. With gymnasium, `step` returns 5 values, not 4.

```python
import gymnasium as gym

from stable_baselines3 import PPO

env = gym.make("FetchReach-v2", render_mode="human")
model = PPO("MultiInputPolicy", env, verbose=1)
model.learn(total_timesteps=100)
observation, info = env.reset()
for _ in range(10):
    action, _ = model.predict(obs, deterministic=True)
    observation, reward, terminated, truncated, info = env.step(action)
    env.render()
    if terminated or truncated:
        observation, info = env.reset()
```

**Comment by araffin** [comment]
I cannot reproduce the bug using the correct code provided by @qgallouedec .
The issue comes from mixing gym 0.21 API with gym 0.26+ api: `env.reset()` returns a tuple.

If you want to keep using a similar API, you must use SB3 VecEnv (see doc).
