### ISSUE TITLE
[Question] offline reinforcement learning

### ISSUE THREAD

**Issue by rampluto** [DLR-RM/stable-baselines3#1640]
### ❓ Question

Hi, Is there any plan to support offline reinforcement learning and related algorithms like CQL, Cal-QL in near future.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
no this is out of scope of SB3.
However, you can take a look at 
- d3rlpy: https://github.com/takuseno/d3rlpy
- CORL: https://github.com/tinkoff-ai/CORL
