### ISSUE TITLE
[Question] Can MultiDiscrete observations be represented as an index instead of one-hot encoding?

### ISSUE THREAD

**Issue by pablo-sanchez-sony** [DLR-RM/stable-baselines3#1642]
### ❓ Question

Hello,

I'm currently using PPO with a custom feature extractor inherited from BaseFeaturesExtractor. Additionally, I'm working with an environment where the observation space is a dictionary containing a MultiDiscrete space. This MultiDiscrete space can be quite large, with tens of dimensions, each consisting of a discrete space with thousands of categories.

I have noticed that the observations passed to the feature extractor are one-hot encoded. For instance, if we have a space defined as:

```
space = MultiDiscrete([1000,]*10)
```

then the observations have a shape of `[batch_size, 1000x10]` due to the one-hot encoding.

I'm curious if there's a way to represent this space as an index, allowing the observations' shape to be `[batch_size, 10]` instead.

Thank you in advance for your assistance.

Best regards, 

Pablo

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I'm curious if there's a way to represent this space as an index, allowing the observations' shape to be [batch_size, 10] instead.

You can do that using a box space but this is not recommended as:
1. you would need to normalize the input to have large magnitude
2. the distance between the value doesn't mean anything (index 1 is not closer to index 2, there are just different indices, that's why we use one-hot encoding normally)

**Comment by psanch21** [comment]
Hi,

Thanks a lot for the reply :D

Thanks a lot for pointing out those two aspects. Still, in my use-case each dimension of the MultiDiscrete space refers to an index of another tensor. Thus, I do not need to worry about the two points you mentioned.

**Comment by pablo-sanchez-sony** [comment]
Hi,

Thanks a lot for the reply :D

Thanks a lot for pointing out those two aspects. Still, in my use case each dimension of the MultiDiscrete space refers to an index of another tensor. Thus, I do not need to worry about the two points you mentioned.
