### ISSUE TITLE
[Feature Request] Add the possiblity to prevent the creation of subdirectory in Tensorboard

### ISSUE THREAD

**Issue by charraut** [DLR-RM/stable-baselines3#1651]
### 🚀 Feature

Hey!

When we create a a new run with the logging handled by Tensorboard, it automatically create one dir for the exp and one sub dir for the Tensorboaord file

```python
def configure_logger(
    verbose: int = 0,
    tensorboard_log: Optional[str] = None,
    tb_log_name: str = "",
    reset_num_timesteps: bool = True,
) -> Logger:
    """
    Configure the logger's outputs.

    :param verbose: Verbosity level: 0 for no output, 1 for the standard output to be part of the logger outputs
    :param tensorboard_log: the log location for tensorboard (if None, no logging)
    :param tb_log_name: tensorboard log
    :param reset_num_timesteps:  Whether the ``num_timesteps`` attribute is reset or not.
        It allows to continue a previous learning curve (``reset_num_timesteps=False``)
        or start from t=0 (``reset_num_timesteps=True``, the default).
    :return: The logger object
    """
    save_path, format_strings = None, ["stdout"]

    if tensorboard_log is not None and SummaryWriter is None:
        raise ImportError("Trying to log data to tensorboard but tensorboard is not installed.")

    if tensorboard_log is not None and SummaryWriter is not None:
        latest_run_id = get_latest_run_id(tensorboard_log, tb_log_name)
        if not reset_num_timesteps:
            # Continue training in the same directory
            latest_run_id -= 1
        save_path = os.path.join(tensorboard_log, f"{tb_log_name}_{latest_run_id + 1}")
        if verbose >= 1:
            format_strings = ["stdout", "tensorboard"]
        else:
            format_strings = ["tensorboard"]
    elif verbose == 0:
        format_strings = [""]
    return configure(save_path, format_strings=format_strings)
```

It would be interesting to only create a directory with the `tensorboard_log` path. 

### Motivation

A lot of times when we handle experiences and runs, we already tag our exp name with specific names, such as datetime. Adding a subdirectory such as "PPO_1" seems useless in that use case and it would be handier to only have one directory with the tensorboard log inside

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
Hello,

> If I'm requesting a new feature, I have proposed alternatives

Please don't forget that next time.
For your use case, would `configure()` and `set_logger()` be sufficient?

See https://stable-baselines3.readthedocs.io/en/master/common/logger.html

**Comment by charraut** [comment]
> Hello,
> 
> > If I'm requesting a new feature, I have proposed alternatives
> 
> Please don't forget that next time. For your use case, would `configure()` and `set_logger()` be sufficient?
> 
> See https://stable-baselines3.readthedocs.io/en/master/common/logger.html

Sorry I didn't read everything properly

Thanks for the answer, yes these methods are sufficient for my problem ! Have a good day
