### ISSUE TITLE
[Question] Dict observation space support

### ISSUE THREAD

**Issue by katjamuench** [DLR-RM/stable-baselines3#1653]
### ❓ Question

Dict observation space support is listed amongst the features on the main page but I couldn't find anything about it in the docs. Is there anywhere I can read about it?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hi, check https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#dict-observations and https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#multiple-inputs-and-dictionary-observations

**Comment by araffin** [comment]
> Am I right to assume that a dictionary is currently not possible for an action space?

https://github.com/DLR-RM/stable-baselines3/issues/527

**Comment by katjamuench** [comment]
Thank you!
