### ISSUE TITLE
[Question] Lunar Lander termination

### ISSUE THREAD

**Issue by suargi** [DLR-RM/stable-baselines3#1669]
### ❓ Question

Hi,

I have trained a PPO agent. I have created the following code to enjoy the agent:

```
env = make_vec_env("LunarLander-v2",
                       n_envs=N_ENVS,
                       # seed=0,
                       monitor_dir=LOG_DIR,
                       env_kwargs={'continuous':True})

env = VecNormalize(venv=env,
                       norm_obs=False,
                       norm_reward=False,
                       clip_obs=10.)

model = PPO.load("best_model.zip", env=env)

def record_video(env_id, model, video_length=500, prefix="", video_folder="videos/"):
        """
        :param env_id: (str)
        :param model: (RL model)
        :param video_length: (int)
        :param prefix: (str)
        :param video_folder: (str)
        """
        eval_env = DummyVecEnv([lambda: gym.make(env_id,
                                                 render_mode="rgb_array",
                                                 continuous=True)])
        # Start the video at step=0 and record 500 steps
        eval_env = VecVideoRecorder(
            eval_env,
            video_folder=video_folder,
            record_video_trigger=lambda step: step == 0,
            video_length=video_length,
            name_prefix=prefix,
        )

        obs = eval_env.reset()
        for _ in range(video_length):
            action, _ = model.predict(obs)
            obs, reward, done, info = eval_env.step(action)

        # Close the video recorder
        eval_env.close()

record_video("LunarLander-v2", model, video_length=350, prefix="ppo_cnt-lunarlander")
```

I enclose a video of the trained agent. The problem is that the ship lands but it stays on the surface with the lateral boosters on till the maximum number of steps in the episode, 1000, is reached. Then and only then, the flag  `done` is set `True`. I would expect this flag to be `True` right after touchdown, always in accordance with the gymnasium environment setup:

> ## Episode Termination
>     The episode finishes if:
>     1) the lander crashes (the lander body gets in contact with the moon);
>     2) the lander gets outside of the viewport (`x` coordinate is greater than 1);
>     3) the lander is not awake.

https://github.com/DLR-RM/stable-baselines3/assets/64904120/e81090be-f063-4849-ab43-f7312dc520d2

When using rl_zoo3.enjoy with my agent the episodes end before the maximum number of steps is reached, as one would expect. The command I use is: `python -m rl_zoo3.record_video --algo ppo --env LunarLanderContinuous-v2 -f logs/ --load-best -n 1000`. The resulting video:

https://github.com/DLR-RM/stable-baselines3/assets/64904120/e447744c-c9a6-46a1-ba8b-f01647a7cad2

This makes me think that the problem might not be the agent but maybe in sb3 env.step(). What do you think?

If you want I can share the full code and the trained agent.
If this is a gymnasium related problem, please let me know.

Thanks.

P.S: I do not know why with rl_zoo3 the results are "smoother" or not that "intense" as with my code.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
i guess the answer is here: "the lander is not awake.", you need booster off to terminate.

**Comment by suargi** [comment]
> i guess the answer is here: "the lander is not awake.", you need booster off to terminate.

That's what I guess as well. However:
- Why do I only experience this problem when enjoyed with my code but not with rl_zoo3.enjoy? Does rl_zoo3 do something else?
- How can we prevent such behaviour? Is there something we can add to the training?

I trained a model using rl_zoo3.train and enjoyed with my code. I observe the same problem described in my first post. Again, this model does not experience the problem when enjoyed using rl_zoo3.enjoy.

**Comment by araffin** [comment]
> Why do I only experience this problem when enjoyed with my code but not with rl_zoo3.enjoy? Does rl_zoo3 do something else?

RL Zoo enjoy uses deterministic evaluation by default (except for Atari games), you can overwrite the setting to use the stochastic policy instead `--stochastic` if what you are looking for.

> How can we prevent such behaviour? Is there something we can add to the training?

Usually giving more budget solves the problem.

**Comment by suargi** [comment]
> RL Zoo enjoy uses deterministic evaluation by default (except for Atari games), you can overwrite the setting to use the stochastic policy instead `--stochastic` if what you are looking for.

Right on! Thank you

> Usually giving more budget solves the problem

Will try that
