### ISSUE TITLE
[Question] Feed tabular data for pre-training before actual training

### ISSUE THREAD

**Issue by yasirroni** [DLR-RM/stable-baselines3#1673]
### ❓ Question

My current project involves a decision process of static environment that can be formatted into tabular data. In the other hand, call to evaluate action in the environment is costly and time consuming.

Thus, utilizing a the static tabular data for pre-training before actual training should reduce the overall training process. The tabular data is an approximate that should be useful for the agent. It contains data about observation of the environment for given action.

Can we feed the tabular data directly to the agent for pre-training (we control the action selected by the agent, and fetch the observation from tabular data)? Then, move the weight or the model to the actual environment after that?
___
If it is not possible yet, would you like to point me to somewhere in the code so that I can contribute?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
what you are describing should like offline rl, you should have a look at d3rlpy and corl libraries.

You can of course fill a replay buffer and train on it but thus has some known issues (see BCQ paper).

**Comment by yasirroni** [comment]
@araffin Thank you very much. Your guidance is very clear and help me a lots. I'm newb in RL, but already capable designing environment using SB3 and successfully training some models.

So, there are something called off-policy RL. Does SB3 only support on-policy RL (I can't find this in the docs)?

If not, which library (or policiy) does in your knowledge support transfering model weight or policy to SB3 agent? This is because if possible, I want to stick with the on-policy RL and environment in SB3 that I already know, but wanting to improve the agent via off-policy in pre-training. If this is not supported, then I will use d3rlpy as you explained, following [this tutorial](https://d3rlpy.readthedocs.io/en/v2.1.0/tutorials/finetuning.html).

Very appreciated.

**Comment by araffin** [comment]
> So, there are something called off-policy RL. Does SB3 only support on-policy RL (I can't find this in the docs)?

on-policy and off-policy are something different (please see the resources we link in our doc), I was talking about offline-RL (which is very close to supervised learning, so learn with a fixed dataset vs learn while interacting with the world).

The two libraries I mentioned support offline RL (CORL and d3rlpy).

**Comment by yasirroni** [comment]
Thank you very much. This little exchange really help me. Let me close this issue, with a note that:

**Currently SB3 did not support offline RL**.
