### ISSUE TITLE
[Question] Shared feature extractor with multiple critics in SAC

### ISSUE THREAD

**Issue by PatrickHelm** [DLR-RM/stable-baselines3#1674]
### ❓ Question

Hello, 

I noted the following behavior when using `shared_features_extractor=True` and `n_critics=2`  in SAC: 

The feature extractor is shared between the policy and one Q-function network, but for the second Q-function network, a new feature extractor is created. Is this behavior intended? And if yes, how can I disable it in the code? 

I know the estimates of the Q-functions should be independent, but sharing the feature extractor between policy and one Q-function gave me a boost in performance, so I am wondering whether sharing it across all Q-functions would be beneficial. I looked at the code, but could not find a way to disable this behavior manually. 

I would appreciate any help on this.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
>  Is this behavior intended? And if yes, how can I disable it in the code?

yes it is (to keep code simple), you will probably need a fork of SB3 (if you do so, please link it here).

**Comment by PatrickHelm** [comment]
Thanks for your answer. Could you please point me to the code that I have to edit?
I looked at the `ContinuousCritic`, but I could find no differential treatment of the two networks in terms of the feature extractor.

**Comment by araffin** [comment]
Actually, looking closer at the code, the features extractor is always shared between the n-critics:
https://github.com/DLR-RM/stable-baselines3/blob/1cd6ae42d50988a236cbca7d822340e6a498bdc5/stable_baselines3/common/policies.py#L933-L939
