### ISSUE TITLE
[Bug]: SimpleMultiObsEnv sometimes returns an integer reward (instead of float)

### ISSUE THREAD

**Issue by NixGD** [DLR-RM/stable-baselines3#1675]
### 🐛 Bug

The reward of SimpleMultiObsEnv is an integer instead of a float when it completes the gridworld, which is inconsistent with the type signature and breaks some other libraries.

### To Reproduce

```python
from stable_baselines3.common.envs import SimpleMultiObsEnv

env = SimpleMultiObsEnv(random_start=False)
env.reset()
_ = env.step(1)
_ = env.step(1)
_ = env.step(1)
_ = env.step(2)
_ = env.step(2)
_, rew, _, _ = env.step(2)
type(rew)
```
gives `int`.

### System Info

- OS: macOS-13.3.1-arm64-arm-64bit Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
- Python: 3.9.18
- Stable-Baselines3: 1.8.0
- PyTorch: 2.0.1
- GPU Enabled: False
- Numpy: 1.25.2
- Gym: 0.21.0

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
thanks for the remark (although according to python guidelines, it is acceptable to have int returned when the fn is annotated with float: https://stackoverflow.com/questions/50928592/mypy-type-hint-unionfloat-int-is-there-a-number-type)
