### ISSUE TITLE
[Bug]: incorrect type signature  that take in dictionary observations

### ISSUE THREAD

**Issue by NixGD** [DLR-RM/stable-baselines3#1679]
### 🐛 Bug

Looking at [the implementation of `.predict`](https://github.com/DLR-RM/stable-baselines3/blob/99712760c8f2bb8a40c201158b649eb0041b830f/stable_baselines3/common/policies.py#L323) in the base policy class, you'd reasonably assume that the call to [`.obs_to_tensor(observation)`](https://github.com/DLR-RM/stable-baselines3/blob/99712760c8f2bb8a40c201158b649eb0041b830f/stable_baselines3/common/policies.py#L231) would flatten a dictionary-typed observation to a tensor. The type signatures confirm this.`obs_to_tensor` claims to output a tensor, and the observations are passed into `_predict(self, observation: th.Tensor, ...)`.

In practice, `.obs_to_tensor(observation)` outputs a dictionary which is passed into `._predict`. The dictionary observations are eventually handled by an appropriate feature extractor.

This problem is also seen in the type signature of [`.evaluate_actions(self, obs: th.Tensor, actions: th.Tensor)`](https://github.com/DLR-RM/stable-baselines3/blob/99712760c8f2bb8a40c201158b649eb0041b830f/stable_baselines3/common/policies.py#L683). It's correct to pass a `dict[str: th.Tensor]` observation into this function if the feature extractor can handle it.

This is a fine approach, but the type signatures are incorrect and `obs_to_tensor` is a bit of a misnomer. This is both confusing, and means that subclasses of policy or code that interacts directly with these methods doesn't typecheck.

### To Reproduce

```python
from gym import spaces
from stable_baselines3.common import policies

obs_space = spaces.Dict({"a": spaces.Discrete(2,), "b": spaces.Box(0,1,(2,))})
policy = policies.MultiInputActorCriticPolicy(
    obs_space,
    spaces.Discrete(4,),
    lambda _: 0.001,
)
obs = obs_space.sample()
policy.obs_to_tensor(obs)
```
gives `({'a': tensor([1]), 'b': tensor([[0.7694, 0.0154]])}, False)`

### System Info

- OS: macOS-13.3.1-arm64-arm-64bit Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
- Python: 3.9.18
- Stable-Baselines3: 1.8.0
- PyTorch: 2.0.1
- GPU Enabled: False
- Numpy: 1.25.2
- Gym: 0.21.0

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
thanks for spotting that issue, I think the good way to solve it would be to have a `TypeVar` with a `Generic`.
