### ISSUE TITLE
[Feature Request] Upgrade to use Poetry for versioning

### ISSUE THREAD

**Issue by HadiSDev** [DLR-RM/stable-baselines3#1680]
### 🚀 Feature

Poetry makes the package management easier to manage modern python packages. I think it is time to upgrade sb3 to use it as well.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/545
