### ISSUE TITLE
[Bug]: The observation_space and action_space were not given, can't verify new environments

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [DLR-RM/stable-baselines3#1682]
### 🐛 Bug

This error didn't occur in my old environment. After a clean new conda env setup without any changes to my codebase suddenly this popped up when loading existing models with a custom env. The error makes no sense since those values are declared correctly in my custom env and I can print them in debug mode before trying to load the model which is where the error occurs:

```
print(self.RLEnv.observation_space)
print(self.RLEnv.action_space)

Box(-inf, inf, (10, 5), float32)
Discrete(2)
```

### To Reproduce

```
model = PPO.load(model_path, seed=self.seed)
or 
model = PPO.load(model_path, seed=self.seed, env=self.RLEnv)
```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
    self.model = PPO.load(model_path, seed=self.seed, env=self.RLEnv)
  File "C:\ProgramData\anaconda3\envs\ML\lib\site-packages\stable_baselines3\common\base_class.py", line 706, in load
    raise KeyError("The observation_space and action_space were not given, can't verify new environments")
KeyError: "The observation_space and action_space were not given, can't verify new environments"
```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by Karlheinzniebuhr** [comment]
* Update, after retraining the model it loads correctly. What causes this error and how can I circumvent it without retraining everything ?

**Comment by araffin** [comment]
> I have provided a minimal and working example to reproduce the bug

Closing for the above reason.

**Comment by mohammad200h** [comment]
I have the same issue, I copied the model while training was going on. Do we know what is causing this?

**Comment by D-o-d-o-x** [comment]
Use
`model = PPO.load(model_path, seed=self.seed, env=self.RLEnv, custom_objects={'observation_space': self.RLEnv.observation_space, 'action_space': self.RLEnv.action_space})`
instead. Then it will work.

**Comment by WreckItTim** [comment]
same issue. This should throw a warning not an error.

**Comment by critcorez** [comment]
My problem was solved when i changed numpy version to the same as when i trained my model

**Comment by Ruphobia** [comment]
Same issue, upgrading numpy on second machine to same version of numpy resolved the issue.   Is it normal that you have to have same version of numpy or you can't load the model?  Is there a way to make this less brittle?

**Comment by Abc11c** [comment]
Hi @Ruphobia, @critcorez ,

Facing the same issue, what is the version of numpy you happen use? having the same problem

**Comment by Delta-Sigma** [comment]
I had trained a model on numpy=1.26.4 and then downgraded for some unrelated reason to 1.23.5.. Upgrading back to 1.26.4 fixed the problem.
