### ISSUE TITLE
[Feature Request] Allow Sequence gym space

### ISSUE THREAD

**Issue by HadiSDev** [DLR-RM/stable-baselines3#1688]
### 🚀 Feature

I want to implement a new feature for sb3 which allows the Gymnasium Sequence space to be used:
https://gymnasium.farama.org/main/_modules/gymnasium/spaces/sequence/

### Motivation

In cases where we don't know the length of an observation, Sequence comes quite useful as they allow for dynamic sizes. For example in the scenario I am working on I have a list of indexes which maps to another observation set. I need to pass this list to the NN at each step. The max length of the list of indexes is not known beforehand and can be different for each episode.

As a more concrete example, think of a scenario of a Capacitated Vehicle Routing Problem (CVRP), where we want to track the route at each timestep for each vehicle. The length of the finished route is not known beforehand. To solve this you could do this: 

````partial_routes = spaces.Sequence(spaces.Sequence(spaces.Discrete(self.n_depots + self.n_nodes))) ````

The first Sequence represents the dimension of the number of vehicles
and the second Sequence represent a list of node indices.

The space would be converted to regular tensors or lists

### Alternatives

I am not sure

### Additional context

I don't mind implementing it

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
> Alternatives

you could pad your observation.

> I want to implement a new feature for sb3

do you have a working version somewhere?

I'm afraid this would add quite some complexity to the codebase (compared to its probably uncommon use), but I would be happy to link to your fork if you have something working.

**Comment by HadiSDev** [comment]
@araffin padding would only work if I knew the max length. The point here is that I don't :) 

But I am still working on the code. I will get back to you once I have something ready
