### ISSUE TITLE
[Bug]: ep_rew_mean computation in Monitor

### ISSUE THREAD

**Issue by nrigol** [DLR-RM/stable-baselines3#1689]
### 🐛 Bug

I realize ep_rew_mean was not computing the mean but summing the reward within an episode, and then computing the mean over this sum.
I would surprised to be right, but it looks like this from here/

From  [https://stable-baselines3.readthedocs.io/en/master/_modules/stable_baselines3/common/monitor.html](https://stable-baselines3.readthedocs.io/en/master/_modules/stable_baselines3/common/monitor.html) :

# 
           if terminated or truncated:
            self.needs_reset = True
            ep_rew = sum(self.rewards)
            ep_len = len(self.rewards)
            ep_info = {"r": round(ep_rew, 6), "l": ep_len, "t": round(time.time() - self.t_start, 6)}
            for key in self.info_keywords:
                ep_info[key] = info[key]

While from [https://stable-baselines3.readthedocs.io/en/master/_modules/stable_baselines3/common/on_policy_algorithm.html](https://stable-baselines3.readthedocs.io/en/master/_modules/stable_baselines3/common/on_policy_algorithm.html)

            # Display training infos
            if log_interval is not None and iteration % log_interval == 0:
                assert self.ep_info_buffer is not None
                time_elapsed = max((time.time_ns() - self.start_time) / 1e9, sys.float_info.epsilon)
                fps = int((self.num_timesteps - self._num_timesteps_at_start) / time_elapsed)
                self.logger.record("time/iterations", iteration, exclude="tensorboard")
                if len(self.ep_info_buffer) > 0 and len(self.ep_info_buffer[0]) > 0:
                    self.logger.record("rollout/ep_rew_mean", safe_mean([ep_info["r"] for ep_info in self.ep_info_buffer]))
                    self.logger.record("rollout/ep_len_mean", safe_mean([ep_info["l"] for ep_info in self.ep_info_buffer]))

### To Reproduce

```python
from stable_baselines3 import ...

```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
I guess there is a misunderstanding of what "mean episodic reward" means (https://stable-baselines3.readthedocs.io/en/master/common/logger.html).
It should be called "mean return", and the return is defined as the sum of rewards during one episode.

**Comment by nrigol** [comment]
It makes lot of sense, thank you
