### ISSUE TITLE
[Feature Request] BitFlippingEnv observation_space argument

### ISSUE THREAD

**Issue by kylesayrs** [DLR-RM/stable-baselines3#1691]
### 🚀 Feature

As it stands, the `BitFlippingEnv` has two boolean initializer arguments, `discrete_obs_space`  and `image_obs_space`. Since they are mutually exclusive arguments, they should be folded in to one argument `observation_space`.

### Motivation

Make it clearer for first time users of the environment which version of the environment is being used. This also helps developers avoid logic conflicts and follows good practice.

I don't see the reasoning in not implementing this change for backwards compatibility, since this is only a demo environment and already diverges from SB's implementation.

### Pitch

The added `observation_space` argument should be a string. The observation space should be created by a `_create_observation_space` helper function, where we can check `observation_space` for invalid values.

### Alternatives

The added argument's value could also be implemented as an enum, which is preferred but overkill for a simple demo environment imho.

### Additional context

I'm looking for simple improvements so I can learn more about the contribution process for SB3.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
Hello,
`BitFlippingEnv` is mostly meant for testing things, not really meant to be used outside/be generic.

> Alternatives

what about adding a quick assert that check in the init that both argument are not True? (and output a nice error if it's the case)
We should probably update the documentation too.

**Comment by kylesayrs** [comment]
@araffin I think that's a good solution too. I'll work on putting together a PR
