### ISSUE TITLE
Tensorboard not Logging

### ISSUE THREAD

**Issue by MichiBab** [DLR-RM/stable-baselines3#170]
**Describe the bug**
Tensorboard Logging is not working with Stable Baselines 3, but works with Stable Baselines.

**Code example**
```#!/usr/bin/env python3
import gym
from stable_baselines3 import A2C
from stable_baselines3.common.cmd_util import make_vec_env

def main():
    # Parallel environments
    env = make_vec_env('CartPole-v1', n_envs=4)
    model = A2C('MlpPolicy', env, verbose=1, tensorboard_log="./tmplog")
    model.learn(total_timesteps=25000, log_interval=1)
    print("learning done")

if __name__ == "__main__":
    main()
```

There will be no tmplog folder with logs in it.
But if you change the imports to:
```from stable_baselines import A2C
from stable_baselines.common.cmd_util import make_vec_env
```
It is working.

Tried with Bleeding Edge and Stable Version.

**Comment by araffin** [comment]
Hello,

Do you have tensorboard package installed?
I just tested your code snippet and it works as expected....

**Comment by Miffyli** [comment]
@araffin beat me to it but I too was able to run the code with current `master` and it produced log as expected.

**Comment by MichiBab** [comment]
I removed it, reinstalled it with [extra] and it works now, thank you very much.
