### ISSUE TITLE
[Bug]: ImportError with docker image stablebaselines/stable-baselines3-cpu:latest

### ISSUE THREAD

**Issue by blurLake** [DLR-RM/stable-baselines3#1702]
### 🐛 Bug

when I run the docker image stablebaselines/stable-baselines3-cpu:latest and try to import SAC from stable_baselines3, i got ImportError: cannot import name 'SAC' from 'stable_baselines3' (unknown location). Any suggestions?

### To Reproduce

```python
from stable_baselines3 import SAC

```

### Relevant log output / Error message

```shell
ImportError: cannot import name 'SAC' from 'stable_baselines3' (unknown location)
```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by blurLake** [comment]
BTW, the setup.py in /home/mambauser in executed by `python3 setup.py install`, and I have `stable-baselines3             2.2.0a1       /opt/conda/lib/python3.10/site-packages/stable_baselines3-2.2.0a1-py3.10.egg` from pip list.

**Comment by araffin** [comment]
> when I run the docker image stablebaselines/stable-baselines3-cpu:latest and try to import SAC from stable_baselines3, i got ImportError: cannot import name 'SAC' from 'stable_baselines3' (unknown location). Any suggestions?

did you follow the documentation and use the scripts?
the sb3 docker images doesn't contain sb3 but its dependencies, it's meant for development, if you want sb3 too you either need to use the script (see doc) or use the RL Zoo image.

**Comment by blurLake** [comment]
Thank you for your help. I switch to rl-zoo image and it works well!
