### ISSUE TITLE
[Bug]: Deterministic prediction is not well implemented

### ISSUE THREAD

**Issue by GuillermoHijano** [DLR-RM/stable-baselines3#1703]
### 🐛 Bug

I am looking into the code of stable-baselines3/stable_baselines3/dqn/policies.py and in line 68 I see:

`def _predict(self, observation: th.Tensor, deterministic: bool = True) -> th.Tensor:
        q_values = self(observation)
        # Greedy action
        action = q_values.argmax(dim=1).reshape(-1)
        return action`

I think there is a bug in the implementation as the deterministic argument is not being used inside the function. Therefore, I would say that the algorithm will not always select the action with highest probability

### To Reproduce

```python
from stable_baselines3 import ...

```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
you should look at dqn.py

**Comment by GuillermoHijano** [comment]
Hi araffin, thanks for your reply. However, I still believe there might be a bug: In dqn.py there is a line for executing a deterministic prediction:

`action, state = self.policy.predict(observation, state, episode_start, deterministic)`

Above, the policy is a DQNPolicy. And if you look at the code for the deterministic prediction in DQNPolicy class (in policies.py script) you can see that the code, in the end, points to this function:

`def _predict(self, observation: th.Tensor, deterministic: bool = True) -> th.Tensor: q_values = self(observation) # Greedy action action = q_values.argmax(dim=1).reshape(-1) return action`

where the deterministic argument is not being used. I would therefore suggest that it might be that the deterministic prediction is not being performed well.

**Comment by araffin** [comment]
> dqn.py there is a line for executing a deterministic prediction:

https://github.com/DLR-RM/stable-baselines3/blob/c6c660e51bdad1a60e3770e121a88dcb666e7dbf/stable_baselines3/dqn/dqn.py#L236-L256

?

yes, this is fine, the fact that we pass deterministic keyword is slightly confusing I agree but this is the greedy policy, so no issue, the "epsilon-greedy" (non-deterministic) part is handled by the lines above it.
