### ISSUE TITLE
ProcGen Env Wrapper for SB3 

### ISSUE THREAD

**Issue by tbuckworth** [DLR-RM/stable-baselines3#1712]
### 📚 Documentation

[This](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#sb3-and-procgenenv) example from the docs throws an error:
```from procgen import ProcgenEnv

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecExtractDictObs, VecMonitor

# ProcgenEnv is already vectorized
venv = ProcgenEnv(num_envs=2, env_name="starpilot")

# To use only part of the observation:
# venv = VecExtractDictObs(venv, "rgb")

# Wrap with a VecMonitor to collect stats and avoid errors
venv = VecMonitor(venv=venv)

model = PPO("MultiInputPolicy", venv, verbose=1)
model.learn(10_000)
```

Error:
```AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>, <class 'gymnasium.spaces.discrete.Discrete'>, <class 'gymnasium.spaces.multi_discrete.MultiDiscrete'>, <class 'gymnasium.spaces.multi_binary.MultiBinary'>) as action spaces but Discrete(15) was provided```

stable_baselines3 version 2.1.0
procgen version 0.10.7

I have seen that issues #1475 #1371 #1274 and #1588 have a similar issue, but relate to using the gym package instead of gymnasium.

Also, this issue seems to have been addressed back in #665, but there is still this error.

Is there no support for ProcGen environments? 
Any way to successfully wrap them?

If not then the example in the docs should probably be removed.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

**Comment by tbuckworth** [comment]
I have created a wrapper for ProcGen if of interest.
It seems to work, though I'm still figuring it out.
If there is an official version of this please let me know.
Additionally, if anyone sees anything wrong with this, please let me know.

```
class ProcGen4SB3(gym.Env):
    metadata = {"render_modes": ["human"], "render_fps": 30}

    def __init__(self, env_args):
        super().__init__()
        self.env_args = copy.deepcopy(env_args)
        self.env_args["num"] = 1
        self.env = ProcgenGym3Env(**self.env_args)

        self.action_space = spaces.Discrete(self.env.ac_space.eltype.n)
        self.observation_space = spaces.Box(low=0, high=255, shape=self.env.ob_space["rgb"].shape, dtype=np.uint8)

    def observe(self):
        rew, obs, first = self.env.observe()
        infos = self.env.get_info()
        return obs["rgb"].squeeze(), float(rew[0]), bool(first[0]), infos[0]

    def step(self, action):
        # TODO:
        #   Truncated is not implemented
        #   https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html#vecenv-api-vs-gym-api
        self.env.act(np.array([action], dtype=np.int32))
        obs, rew, first, info = self.observe()
        return obs, rew, first, False, info
        # return observation, reward, terminated, truncated, info

    def reset(self, seed=None, options=None):
        self.env = ProcgenGym3Env(**self.env_args)
        obs, rew, first, info = self.observe()
        return obs, info

    def render(self):
        return

    def close(self):
        return
```

and here is an example of using it:

```
def run_cust_pytorch_env():
    env_args = {"num": 1,
                "env_name": "coinrun",
                "start_level": 0,
                "num_levels": 500,
                "paint_vel_info": True,
                "distribution_mode": "easy"}

    venv = ProcGen4SB3(env_args)
    check_env(venv)

    model = PPO("CnnPolicy", venv, verbose=1)
    model.learn(10_000)
```

**Comment by araffin** [comment]
> Is there no support for ProcGen environments?
> Any way to successfully wrap them?

it looks more like a Gym issue, you should probably take a look at https://github.com/Farama-Foundation/Procgen2 which should support Gymnasium.

> I have created a wrapper for ProcGen if of interest.

Otherwise yes, a custom `VecEnvWrapper` that overwrites the obs/action space would be the way to go.

**Comment by tbuckworth** [comment]
@araffin great, thank you, I was unaware of procgen2, I'll look into that
