### ISSUE TITLE
[Question] How does model.predict() assign integers when the actions are strings?

### ISSUE THREAD

**Issue by epdavid1** [DLR-RM/stable-baselines3#1715]
### ❓ Question

Suppose I have 7 actions which are in strings. 

`['SEKER', 'BARBUNYA', 'BOMBAY', 'CALI', 'HOROZ', 'SIRA', 'DERMASON']`

After training the agent, the model.predict() outputs integers instead of the strings. 

I have not assigned any particular integer with an action so I don't know which action is represented by the integer.

Are these integer predictions based on the alphabetical order of the actions? 

Or is it based on the order of appearance of the actions in the dataframe?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by epdavid1** [comment]
X looks like this:

![image](https://github.com/DLR-RM/stable-baselines3/assets/110080859/b073429e-b9a1-4f28-9664-92eb9983d02e)

y:

![image](https://github.com/DLR-RM/stable-baselines3/assets/110080859/70ef5d00-859e-466b-891b-ecbd44f0a49f)


Snippet of my environment __init__:
`
      self.X = X
      self.y = y

      self.action_space = spaces.Discrete(7)
      self.observation_space = spaces.Box(low=0, high=1, shape=(X.shape[1],), dtype=np.float32)
`

Training the agent:
`env = AdRecommenderEnv(X_train, y_train)
model = PPO('MlpPolicy', env, verbose=0, gamma=0)
model.learn(total_timesteps=30000)
`

Trying prediction:
![image](https://github.com/DLR-RM/stable-baselines3/assets/110080859/3e8eecb2-08b7-43da-a13f-c8cfe613ba17)


The prediction is an integer to which I have no idea what action it represents.

**Comment by araffin** [comment]
please use the env checker (see doc and custom env issue template), i would also recommend using latest sb3/Gymnasium versions (master version for sb3, instructions are in the doc too,).

**Comment by qgallouedec** [comment]
What I see is just a discrete action space environment. So where are the strings you're referring to?

**Comment by epdavid1** [comment]
Anyway, I did eventually add a dictionary to map. Thanks for the help!

`self.actions = {0:'SEKER', 1:'BARBUNYA', 2:'BOMBAY', 3:'CALI', 4:'HOROZ', 5:'SIRA', 6:'DERMASON'}`
