### ISSUE TITLE
[Question] Loading model with Custom Feature Extractor

### ISSUE THREAD

**Issue by MarkWrobelUCL** [DLR-RM/stable-baselines3#1716]
### ❓ Question

Hi, I have trained an RL model using the PPO algorithm with images as an input with a CustomCNN feature extractor class passed to the model ([as seen here](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html)). The Issue I'm having is that I am unsure how to load this model. 
When training an RL model using the PPO algo with an array as input i just use PPO.load() in order to load the model however, this doesn't work with a model trained with the CustomCNN feature extractor. Is there a different function for loading a CnnPolicy PPO? Thanks in advance.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
>  If code there is, it is minimal and working
> If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

Closing as the minimum requirements for seeking help are not met.

**Comment by Fengtao22** [comment]
Add a comment for others: If you face issues loading a checkpoint with custom model settings (e.g., custom feature extractor), you can resolve this by explicitly specifying in the PPO.load() by adding an extra line:  

 _custom_objects= {"policy_kwargs": policy_kwargs}_

where policy_kwargs is dictionary that specify the custom model settings
