### ISSUE TITLE
[Feature Request] NormalizeObservation Wrapper for Gym GoalEnv

### ISSUE THREAD

**Issue by ammar-n-abbas** [DLR-RM/stable-baselines3#1719]
### 🚀 Feature

I could not find a wrapper for gym goal_env for normalizing observation. my custom env is not a vectorized env. Is the only way to achieve that through vectorizing the env?  

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
Hello,
yes, you can use the make_vec_env util for that.
alternatively, Gymnasium provides a similar wrapper but probably with different features.

**Comment by ammar-n-abbas** [comment]
Hi,
Okay thanks!
