### ISSUE TITLE
Unable to Use Monitor Wrapper with Atari Environments in Stable Baselines 3

### ISSUE THREAD

**Issue by Gribesh** [DLR-RM/stable-baselines3#1721]
### ❓ Question

I've been using `stable_baselines3` for recently and successfully applied the `Monitor` wrapper for the classic control problems, like so:

```python
from stable_baselines3.common.monitor import Monitor

env = gym.make('CartPole-v1')
env = Monitor(env, "path_to_log_dir")
```
It saves logs to the log directory, and I can use it to plot the graph to see performance.

However, I ran into issues when I tried applying the same method to Atari environments, specifically while using vectorized environments. Here's a snippet of what I tried:

```python
from stable_baselines3.common.envs import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack

env = make_atari_env("ALE/BeamRider-v5", n_envs=4)
env = Monitor(env, "path_to_log_dir")
env = VecFrameStack(env, n_stack=4)
```

Upon trying the above, I received an following error. 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[20], line 5
      3 env = make_atari_env("ALE/BeamRider-v5", n_envs=4)
      4 # Stack 4 consecutive frames together to provide temporal information
----> 5 env = Monitor(env, logs_dir)
      6 env = VecFrameStack(env, n_stack=4)

File /opt/conda/lib/python3.10/site-packages/stable_baselines3/common/monitor.py:44, in Monitor.__init__(self, env, filename, allow_early_resets, reset_keywords, info_keywords, override_existing)
     42 self.results_writer = None
     43 if filename is not None:
---> 44     env_id = env.spec.id if env.spec is not None else None
     45     self.results_writer = ResultsWriter(
     46         filename,
     47         header={"t_start": self.t_start, "env_id": str(env_id)},
     48         extra_keys=reset_keywords + info_keywords,
     49         override_existing=override_existing,
     50     )
     52 self.reset_keywords = reset_keywords

AttributeError: 'DummyVecEnv' object has no attribute 'spec'
```

I understand that Atari environments are more complex due to being vectorized, and this might be causing the problem. 

Could anyone guide me on properly using the `Monitor` wrapper with vectorized Atari environments in `stable_baselines3`? I'd appreciate a solution that explains the steps in simple terms. 

Thank you in advance!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
`make_atari_env` already includes `Monitor`.
Try:

```python
from stable_baselines3.common.envs import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack

env = make_atari_env("ALE/BeamRider-v5", n_envs=4, monitor_dir="path_to_log_dir")
```

**Comment by qgallouedec** [comment]
Note that it also includes frame skip and frame stacking, check https://stable-baselines3.readthedocs.io/en/master/common/atari_wrappers.html#module-stable_baselines3.common.atari_wrappers

**Comment by Gribesh** [comment]
Thanks!!
It works.

Also, just to confirm,  if I want to use `ALE/BeamRider-v5`, how can I monitor it? Is there another way to do this? Or is this environment created for another purpose?

**Comment by qgallouedec** [comment]
What configuration do you want exactly? In general, the most common configuration is the default Atari wrapper setting. If you really want to use v5 for some reason, use

python
from stable_baselines3.common.env_util import make_atari_env

env = make_atari_env(
    "ALE/BeamRider-v5",
    n_envs=4,
    monitor_dir="path_to_log_dir",
    env_kwargs={"frameskip" : 1, "repeat_action_probability" : 0.0},
)
```

but note that this is equivalent to my previous answer.

If you want to change the default config, (eg, if you want not to clip the rewards) use `wrapper_kwargs={"clip_reward": False}`. Check the doc more more details: https://stable-baselines3.readthedocs.io/en/master/common/atari_wrappers.html

**Comment by Gribesh** [comment]
I used ALE/BeamRider-v5, as it was mentioned in the docs https://www.gymlibrary.dev/environments/atari/beam_rider/

Thanks for your answer.
