### ISSUE TITLE
[Question] TypeError: step() missing 1 required positional argument: 'rewards'

### ISSUE THREAD

**Issue by zju-wyh** [DLR-RM/stable-baselines3#1722]
### ❓ Question

The location of the error report is /stable_baselines3/common/vec_env/subproc_vec_env.py，Isn't the step function just receiving actions? Why do we need to receive rewards？Please refer to line 29 for details. I am using version 0.11
![image](https://github.com/DLR-RM/stable-baselines3/assets/103970426/732e78e3-ef78-42c3-8180-11603a2586db)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
I'm not sure to understand the issue (this is gym 0.21 API), what would you expect instead ?

PS: SB3 0.11 is pretty old, you should upgrade
