### ISSUE TITLE
[Feature Request] make_vec_env should support multiple wrappers

### ISSUE THREAD

**Issue by Mark2000** [DLR-RM/stable-baselines3#1726]
### 🚀 Feature

I'd like to be able to wrap my `make_vec_env` vectorized environment with multiple different wrappers.

### Motivation

I have a variety of different observation, action, and reward wrappers that I'm testing combinations of. Manually/programmatically defining composite types for each combination of wrappers is not very clean.

### Pitch

In env_util.py, `make_vec_env` would be modified to accept a list of wrappers.
```
            # Optionally, wrap the environment with the provided wrapper
            if type(wrapper_class) == list:
                for wc in wrapper_class:
                    env = wc(env, **wrapper_kwargs)
            elif wrapper_class is not None:
                env = wrapper_class(env, **wrapper_kwargs)
```
There may be interest in allowing for a list of `wrapper_kwargs` as well so that each wrapper gets its own warts.
### Alternatives

None identified after some digging, but maybe there's already a clean way of doing this with existing gymnasium or sb3 features that I'm missing.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
> maybe there's already a clean way of doing this with existing gymnasium or sb3 features that I'm missing.

there is an alternative indeed, and that's what we use in the rl zoo: https://github.com/DLR-RM/rl-baselines3-zoo/blob/2f2da3808668ae62e3aff1cdc0329068b3568a30/rl_zoo3/utils.py#L106

Pass a callable that does the for loop on wrappers when called.

**Comment by Mark2000** [comment]
Ah that works, though mildly annoying to need to add the additional dependency. Still probably not worth pursuing this change.

**Comment by araffin** [comment]
> mildly annoying to need to add the additional dependency

yes, but that's also a cleaner way to specify the correct parameters for each wrapper.
