### ISSUE TITLE
[Question] "Exception ignored" message on save_to_zip when filtering warnings as errors

### ISSUE THREAD

**Issue by npit** [DLR-RM/stable-baselines3#1728]
### ❓ Question

I am wrapping training code with warning filtering as below, to debug stuff in my code:

```python
    with warnings.catch_warnings():
        warnings.filterwarnings("error")
        main() # training code
```

When doing so, I'm seeing output messages while model saving like below, with everything else working as expected however:
```
Exception ignored in: <_io.FileIO name='path/to/model.zip' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/nik/training/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 845, in save
    save_to_zip_file(path, data=data, params=params_to_save, pytorch_variables=pytorch_variables)
ResourceWarning: unclosed file <_io.BufferedWriter name='path/to/model.zip'>
``` 

Is this expected behaviour?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
It seems you forgot to replace `path/to/model.zip` with a correct path in your code. Anyway, it's hard to help you with so little information. If the problem persists, close this exit, and re-open an exit with the correct time (bug report). Remember to provide minimal, functional code so that we can reproduce it.

**Comment by npit** [comment]
Thanks for the feedback. 
> It seems you forgot to replace path/to/model.zip with a correct path in your code

I just replaced the path with a placeholder.

> re-open an issue with the correct template (bug report)

Gotcha, opened #1729 . Closing this.
