### ISSUE TITLE
DQN loss graph not available in tensorboard [question]

### ISSUE THREAD

**Issue by kmsgnnew** [DLR-RM/stable-baselines3#173]
**Description**
I tried to train a custom environment with DQN and observed the loss graph is not included in tensorboard. but if i switch to A2C loss graphs are integrated to tensorboard

**Comment by Miffyli** [comment]
Related issue #170. Try uninstalling SB3 and installing with [extra]s.

Please fill in the issue template (mainly library versions and code to replicate the issue).

**Comment by araffin** [comment]
Hello,
the loss is actually not logged yet. We would appreciate a PR that solves this issue ;)

**Comment by kmsgnnew** [comment]
@araffin wow thanks for the fix. it works !!! verified. it works @Miffyli  thanks for reply
