### ISSUE TITLE
eval the policy with train_env

### ISSUE THREAD

**Issue by yinzikang** [DLR-RM/stable-baselines3#1731]
### ❓ Question

I customized my env based on the Gazebo +ROS, so making multiple instances of my env is not allowed, which causes me some trouble. 
1. I cannot make a multi-instance env as my `train_env` during training.
2. I cannot make a `eval_env` for the `EvalCallback` because of the existence of my `train_env`, so I have to eval the policy with the `train_env`

Currently, the `EvalCallback` is called on `on_step()`, so I'm trying to design a custom eval callback which is called after on the rollout end (almost the same as the `EvalCallback`, only the `on_step()` is changed to the `_on_rollout_end`).  So here is my question.
1. I used the PPO and noticed that the `_on_rollout_end` is called at the end of the function `collect_rollouts`.
2. I didn't see any `env.reset()` at the beginning of the  `collect_rollouts`, so I worry that my custom eval callback would influence the next `collect_rollouts`.
3. Will the env reset at the beginning of each `collect_rollouts`? If the answer is no, will the eval callback interrupt the last unfinished episode and make some trouble?
4. What is the best option to eval the policy when only one env instance is available? 

Any help in clarifying my doubts would be appreciated.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
>     3. Will the env reset at the beginning of each `collect_rollouts`? 

No, the env is reset when it needs to be reset (truncated or terminated). The rollout always collect the same number of steps. In other words, the env is not reset at the beginning of each rollout, and the env reset doesn't implies that we are at the beginning of a rollout.

> If the answer is no, will the eval callback interrupt the last unfinished episode and make some trouble?

Usually no, since the eval env(s) and the training env(s) are different instances. But in your custom env, I can't know.

>     4. What is the best option to eval the policy when only one env instance is available?

An option is not to evaluate during training: save checkpoints and evaluate the checkpoints once the training is done.

**Comment by yinzikang** [comment]
Oh I see, thanks for your advice
