### ISSUE TITLE
Report an error:TypeError: The reset() method must accept a `seed` parameter

### ISSUE THREAD

**Issue by ybl998877** [DLR-RM/stable-baselines3#1738]
### 🐛 Bug

TypeError: The reset() method must accept a `seed` parameter

### Code example

import gymnasium as gym
import numpy as np
import pickle
import time
import subprocess

import nest_asyncio
nest_asyncio.apply()

class starwar2env(gym.Env):
    def __init__(self):
        super(starwar2env,self).__init__()
        self.observation_space = gym.spaces.Box(low=0,high=255,shape=(224,224,3),dtype=np.uint8)
        self.action_space = gym.spaces.Discrete(6)
    
    def step(self,action):

        while True:
            try:
                 with open('transaction.pkl','rb') as f:
                        transaction = pickle.load(f)
                 if transaction['action'] is None:
                    transaction['action'] = action
                    with open('transaction.pkl','wb') as f:
                        pickle.dump(transaction,f)
                    break
                 time.sleep(0.1)
            except Exception as e :
                time.sleep(0.1)
                pass

        while True:
            try:
                 with open('transaction.pkl','rb') as f:
                        transaction = pickle.load(f)
                 if transaction['action'] is None:
                     observation = transaction['observation']
                     reward = transaction['reward']
                     done = transaction['done']
                     break
                 time.sleep(0.1)
            except Exception as e :
                time.sleep(0.1)
                pass
        info = {}
        return observation,reward,done,info   
        
    def reset(self):
        print('Reset the envirnment')
        map = np.zeros((224,224,3),dtype = np.uint8)
        observation = map
        transaction = {'observation':map,'reward':0,'action':None,'done':False}
        with open('transaction.pkl','wb') as f:
            pickle.dump(transaction,f)

        subprocess.Popen(['python3','WorkRushBot.py'])
        return observation

sc2 = starwar2env()
from stable_baselines3.common.env_checker import check_env
check_env(sc2)

### Relevant log output / Error message

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File e:\Anaconda3\envs\starwar2\lib\site-packages\stable_baselines3\common\env_checker.py:408, in check_env(env, warn, skip_render_check)
    407 try:
--> 408     env.reset(seed=0)
    409 except TypeError as e:

TypeError: reset() got an unexpected keyword argument 'seed'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
e:\code\RL\starwar2\Starwar2Env.ipynb 单元格 9 line 2
      1 from stable_baselines3.common.env_checker import check_env
----> 2 check_env(sc2)

File e:\Anaconda3\envs\starwar2\lib\site-packages\stable_baselines3\common\env_checker.py:410, in check_env(env, warn, skip_render_check)
    408     env.reset(seed=0)
    409 except TypeError as e:
--> 410     raise TypeError("The reset() method must accept a `seed` parameter") from e
    412 # Warn the user if needed.
    413 # A warning means that the environment may run but not work properly with Stable Baselines algorithms
    414 if warn:

TypeError: The reset() method must accept a `seed` parameter
```

### System Info

- OS: Windows-10-10.0.22621-SP0 10.0.22621
- Python: 3.9.18
- Stable-Baselines3: 2.1.0
- PyTorch: 2.1.0+cpu
- GPU Enabled: False
- Numpy: 1.26.1
- Cloudpickle: 3.0.0
- Gymnasium: 0.29.1
- OpenAI Gym: 0.23.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hi, the error message is quite explicit: the reset method of your env must accept a `seed` parameter.

**Comment by araffin** [comment]
Please read the gymnasium documentation (we have links and examples in our doc).

**Comment by qgallouedec** [comment]
```diff
- def reset(self):
+ def reset(self, seed=None, options=None):
```
https://stable-baselines3.readthedocs.io/en/master/guide/custom_env.html
https://gymnasium.farama.org/api/env/#gymnasium.Env.reset
