### ISSUE TITLE
[Bug]: ERROR: Could not find a version that satisfies the requirement stable-baseline3[extra] (from versions: none) 

### ISSUE THREAD

**Issue by oldwhitenotblack** [DLR-RM/stable-baselines3#1741]
### 🐛 Bug

It did not work out when I Install the stable-baseline3.My Python interpreter version is 3.8, and the programming environment I'm using is PyCharm.I hope you experts can help.

### To Reproduce

It did not work out  when I executed the command "pip install stable-baseline3[extra]"

### Relevant log output / Error message

```shell
ERROR: Could not find a version that satisfies the requirement stable-baseline3[extra] (from versions: none)
ERROR: No matching distribution found for stable-baseline3[extra]
Note: you may need to restart the kernel to use updated packages.
```

### System Info

Python version:3.8

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
`pip install stable-baselines3[extra]` is what you need (with an "s").

**Comment by oldwhitenotblack** [comment]
> `pip install stable-baselines3[extra]`是您需要的（带有“s”）。

Thanks! Surprisingly, it turned out to be this reason.After modifying the command, I encountered an 'ERROR: Could not build wheels for AutoROM.accept-rom-license,' but I have already resolved it.
