### ISSUE TITLE
[Question] How to set up the termination condition as the number of calls of the step function

### ISSUE THREAD

**Issue by PBerit** [DLR-RM/stable-baselines3#1744]
### ❓ Question

Hi all,

I use the code "model.learn(total_timesteps=4)" to specify the desired number of timesteps for the learning process of a stable-baselines 3 algorithm. Every time I call the step function of the gymnasium envrionment and perform an action of the environment (by getting a reward and a new state) I increment an internal counter variable. However, the internal counter variable has values over 500 before the algorithm stops learning meaning that the step function is called more than 500 times while I only want it to be called 4 times. 

So my question is how can I specify a termination condition based on the number of step function calls (which is equivalent to the number of iterations with the environment). Apparently just specyfying "model.learn(total_timesteps=4)" has a different couting system.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by PBerit** [comment]
@araffin : Thanks araffin for your answer. In your posted link it is written "PPO/A2C and derivates collect n_steps * n_envs of experience before performing an update, so if you want to have exactly total_timesteps you will need to adjust those values"

How can I do that? The problem is really strange. I only specified 4 timesteps but the step function was called 2000 times before the algorithm terminates. How can I stop the training after the specified number of interactions with the environment when using PPO?

**Comment by qgallouedec** [comment]
It's because the agent waits until the end of the rollout to test whether it has collected enough interactions. By default, this rollout length is 2048 (arg `n_steps`). In your case, you should set it to 4:

```python
from stable_baselines3 import PPO

PPO("MlpPolicy", "CartPole-v1", n_steps=4).learn(total_timesteps=4)
```

**Comment by PBerit** [comment]
@qgallouedec : Thanks Quentin for your answer. Actually now it works. However, I still don't understand what the difference between n_steps and total_timesteps is in Stable-Baselines3? Why does Stable-Baselines3 distinguish between 2 stopping criteria and how are they related to each other?

**Comment by qgallouedec** [comment]
`n_steps` is the number of steps per rollout, while `total_timesteps` is the target total number of steps of the training. Consequently, the number of rollouts is `ceil(total_timesteps/n_steps)`, and the actual total number of steps `ceil(total_timesteps/n_steps)*n_steps`

In your initial example: `ceil(total_timesteps/n_steps)*n_steps = ceil(4/2048)*2048 = 2048`

**Comment by araffin** [comment]
> However, I still don't understand what the difference between n_steps and total_timesteps is in Stable-Baselines3? 

I would highly recommend you to read more about PPO, notably the spinning up guide and the blog post, both are linked in our doc.

**Comment by PBerit** [comment]
Ah okay. Thanks @qgallouedec Quentin and @araffin Antonin for your great help. I really appreciate it.
