### ISSUE TITLE
TD3 and DDPG produces boundary or nan action values at a point in time after learning_starts

### ISSUE THREAD

**Issue by mhmodayman** [DLR-RM/stable-baselines3#1749]
### 🐛 Bug

I am using SB3 and the gym to train the reinforcement learning algorithm for driving in the Carla simulator.

I have set total_time_steps to 500 seconds and learning_starts at 2*total_time_steps = 1000.

Before 1000 time_steps passes, the code is working fine. 

After learning starts immediately or after a while, I start getting constant actions at the boundaries of the action space, and sometimes I get np.nan values, and this behavior stays forever.

I faced this issue with TD3 and DDPG but not PPO.

This is my action space:
action_space = spaces.Box(np.array([-0.9, -0.9]), np.array([0.9, 0.9]), dtype=np.float32)

### Code example

```python
import gym
import gym_carla
from stable_baselines3 import PPO, TD3, DDPG

class CarlaEnv(gym.Env):

    def __init__(self):
        super().__init__()
        observation_space_dict = {
                'camera': spaces.Box(low=0, high=1, shape=(self.height, self.width, 1), dtype=np.uint8),
                'state': spaces.Box(np.array([-1000, -1000, -1, -1, -5]),
                                               np.array([1000, 1000, 1, 1, 10]), dtype=np.float32)
            }
        action_space = spaces.Box(np.array([-0.9, -0.9]), np.array([0.9, 0.9]), dtype=np.float32)

    def reset(self, seed=None, options=None):
        obs = {
                'camera': np.array([camera sensor feed]),  # shape 200, 100, 1
                'state': np.array([x, y, np.sin(yaw), np.cos(yaw), speed]), 
            }

         return obs

    def step(self, action):
        obs = {
                'camera': np.array([camera sensor feed]),  # shape 200, 100, 1
                'state': np.array([x, y, np.sin(yaw), np.cos(yaw), speed]), 
            }
        reward = 1.0
        terminated = False
        truncated = False
        info = {}
        return obs, reward, done, info

ITERS = 1000  # number of episodes
learning_rate = 0.001
batch_size = 16
buffer_size = 30 * batch_size
total_time_steps = 500

params['max_time_episode'] = total_time_steps

env = gym.make('carla-v0', params=params)
obs = env.reset()

model_name = 'TD3'
model = TD3('MultiInputPolicy', env,  # MlpPolicy, MultiInputPolicy
            verbose=1,
            learning_rate=learning_rate,
            tensorboard_log=current_session_logdir,
            batch_size=batch_size,
            buffer_size=buffer_size,
            learning_starts=total_time_steps*2)

iteration = 0
while iteration < ITERS:
    iteration += 1

    print('Iteration ', iteration, ' is to commence...')

    model.learn(total_timesteps=total_time_steps, reset_num_timesteps=False, tb_log_name=model_name)
    model.save(f"{current_session_models_dir}/{total_time_steps * iteration}")

    print('Iteration ', iteration, ' has been trained')
```

### Relevant log output / Error message

```shell
In the logs below you will find that actions (dx and dy) are random which is expected, but the last two values are at the boundaries (-0.9, 0.9). Boundaries are the same for dx and dy.

connecting to Carla server...

Carla server connected!

origin Location(x=-85.202950, y=-123.918488, z=-0.072201)

destination Location(x=-84.830643, y=12.590994, z=0.000000)

Using cuda device

Wrapping the env with a `Monitor` wrapper

Wrapping the env in a DummyVecEnv.

venv/lib/python3.7/site-packages/stable_baselines3/common/vec_env/patch_gym.py:50: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  "You provided an OpenAI Gym environment. "

Iteration  1  is to commence...
Logging to logs/1699963198_150x200_grayscale/TD3_0
timestep 0 dx -0.649, dy -0.723, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx -0.594, dy -0.429, steer 0.889, throttle 1.000, brake 0.000
timestep 0 dx 0.422, dy -0.379, steer 0.000, throttle 0.000, brake 0.000
timestep 0 dx 0.569, dy -0.534, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx 0.538, dy -0.870, steer -0.473, throttle 1.000, brake 0.000
timestep 100 dx -0.169, dy -0.454, steer 0.838, throttle 1.000, brake 0.000
timestep 0 dx 0.119, dy 0.023, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx 0.727, dy -0.672, steer -0.395, throttle 1.000, brake 0.000
timestep 100 dx -0.895, dy 0.404, steer 0.828, throttle 1.000, brake 0.000

| rollout/           |           |
|    ep_len_mean     | 91.2      |
|    ep_rew_mean     | -1.28e+04 |
| time/              |           |
|    episodes        | 4         |
|    fps             | 9         |
|    time_elapsed    | 39        |
|    total_timesteps | 365       |

timestep 0 dx 0.187, dy -0.214, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx 0.529, dy 0.768, steer -0.726, throttle 1.000, brake 0.000
timestep 0 dx 0.240, dy 0.822, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx 0.705, dy -0.522, steer -0.825, throttle 1.000, brake 0.000
Iteration  1  has been trained
Iteration  2  is to commence...
Logging to logs/1699963198_150x200_grayscale/TD3_0
timestep 0 dx -0.841, dy 0.019, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx -0.393, dy -0.620, steer 0.726, throttle 1.000, brake 0.000
timestep 100 dx 0.319, dy 0.036, steer -0.807, throttle 1.000, brake 0.000
timestep 0 dx 0.175, dy -0.572, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx 0.261, dy 0.174, steer -0.543, throttle 1.000, brake 0.000

| rollout/           |           |
|    ep_len_mean     | 85.8      |
|    ep_rew_mean     | -1.22e+04 |
| time/              |           |
|    episodes        | 8         |
|    fps             | 10        |
|    time_elapsed    | 15        |
|    total_timesteps | 686       |

timestep 0 dx -0.827, dy -0.122, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx 0.375, dy -0.347, steer -0.789, throttle 0.000, brake 0.000
timestep 0 dx -0.569, dy -0.870, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx 0.595, dy 0.710, steer -0.772, throttle 1.000, brake 0.000
timestep 100 dx 0.354, dy 0.594, steer -0.896, throttle 1.000, brake 0.000
timestep 0 dx -0.711, dy 0.567, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx 0.400, dy 0.120, steer -0.763, throttle 1.000, brake 0.000
timestep 0 dx -0.511, dy -0.574, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx -0.647, dy 0.426, steer 0.814, throttle 0.000, brake 0.000

| rollout/           |           |
|    ep_len_mean     | 82.4      |
|    ep_rew_mean     | -1.18e+04 |
| time/              |           |
|    episodes        | 12        |
|    fps             | 10        |
|    time_elapsed    | 44        |
|    total_timesteps | 989       |

timestep 0 dx -0.153, dy 0.154, steer 0.000, throttle 0.000, brake 0.000
timestep 50 dx -0.004, dy -0.113, steer -0.004, throttle 1.000, brake 0.000
timestep 100 dx -0.007, dy -0.099, steer 0.088, throttle 0.000, brake 0.000
timestep 150 dx -0.010, dy -0.083, steer 0.671, throttle 0.000, brake 0.000
Iteration  2  has been trained
Iteration  3  is to commence...
Logging to logs/1699963198_150x200_grayscale/TD3_0

# 1000 timesteps already passed ... (time to start learning) #

timestep 0 dx -0.900, dy 0.900, steer 0.000, throttle 0.000, brake 0.000
timestep 0 dx -0.900, dy 0.900, steer 0.000, throttle 0.000, brake 0.000
```

### System Info

- OS: Linux-5.15.0-88-generic-x86_64-with-Ubuntu-20.04-focal # 98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023
- Python: 3.7.17
- Stable-Baselines3: 2.0.0
- PyTorch: 1.13.1+cu117
- GPU Enabled: True
- Numpy: 1.21.6
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1
- OpenAI Gym: 0.12.5
({'OS': 'Linux-5.15.0-88-generic-x86_64-with-Ubuntu-20.04-focal # 98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023', 'Python': '3.7.17', 'Stable-Baselines3': '2.0.0', 'PyTorch': '1.13.1+cu117', 'GPU Enabled': 'True', 'Numpy': '1.21.6', 'Cloudpickle': '2.2.1', 'Gymnasium': '0.28.1', 'OpenAI Gym': '0.12.5'}, '- OS: Linux-5.15.0-88-generic-x86_64-with-Ubuntu-20.04-focal # 98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023\n- Python: 3.7.17\n- Stable-Baselines3: 2.0.0\n- PyTorch: 1.13.1+cu117\n- GPU Enabled: True\n- Numpy: 1.21.6\n- Cloudpickle: 2.2.1\n- Gymnasium: 0.28.1\n- OpenAI Gym: 0.12.5\n')

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
>  If code there is, it is minimal and working

Closing as the minimum requirements for seeking help are not met.

**Comment by tuantd** [comment]
I faced the same problem. The action returns NaN when the number of timesteps reached learning_starts.

**Comment by Leong1230** [comment]
Hi, I also faced the same problem. The agent seems to predict boundary action after the start learning. I am using TD3 with HER, a custom env, and feature extraction network.

```
policy_kwargs = dict(
        features_extractor_class=feature_extractor,
        features_extractor_kwargs=dict(hparams=hparams),
        normalize_images=False,
        # share_features_extractor = False
    )
    kwargs = dict(
        policy = hparams.policy,
        env = vec_env,
        policy_kwargs=policy_kwargs,
        verbose=1,
        buffer_size = 100000,
        action_noise = NormalActionNoise(mean=np.zeros(3), sigma=0.1 * np.ones(3)),
        batch_size=hparams.batch_size,
        # gamma = 0.96,
        # max_grad_norm = 1.03,
        # learning_rate = 1e-4,
        # n_steps = 512,
        replay_buffer_class=HerReplayBuffer,
        replay_buffer_kwargs=dict(
            n_sampled_goal=4,
            goal_selection_strategy="future",
            copy_info_dict=True
        )
    )

     model = TD3(**kwargs)
    model.learn(total_timesteps=1000000, callback=callback) #

```
![1722901347626](https://github.com/user-attachments/assets/d4b4c391-0854-408b-8588-17bb7e4da9a7)

**Comment by FinishFYP** [comment]
> Hi, I also faced the same problem. The agent seems to predict boundary action after the start learning. I am using TD3 with HER, a custom env, and feature extraction network.
> 
> ```
> policy_kwargs = dict(
>         features_extractor_class=feature_extractor,
>         features_extractor_kwargs=dict(hparams=hparams),
>         normalize_images=False,
>         # share_features_extractor = False
>     )
>     kwargs = dict(
>         policy = hparams.policy,
>         env = vec_env,
>         policy_kwargs=policy_kwargs,
>         verbose=1,
>         buffer_size = 100000,
>         action_noise = NormalActionNoise(mean=np.zeros(3), sigma=0.1 * np.ones(3)),
>         batch_size=hparams.batch_size,
>         # gamma = 0.96,
>         # max_grad_norm = 1.03,
>         # learning_rate = 1e-4,
>         # n_steps = 512,
>         replay_buffer_class=HerReplayBuffer,
>         replay_buffer_kwargs=dict(
>             n_sampled_goal=4,
>             goal_selection_strategy="future",
>             copy_info_dict=True
>         )
>     )
> 
>      model = TD3(**kwargs)
>     model.learn(total_timesteps=1000000, callback=callback) #
> ```
> 
> ![1722901347626](https://private-user-images.githubusercontent.com/44676836/355266309-d4b4c391-0854-408b-8588-17bb7e4da9a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzYzNzEsIm5iZiI6MTczMjY3NjA3MSwicGF0aCI6Ii80NDY3NjgzNi8zNTUyNjYzMDktZDRiNGMzOTEtMDg1NC00MDhiLTg1ODgtMTdiYjdlNGRhOWE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAyNTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YjdlNDY1MjE3ODllOTgzNzllNGViYjRiMjZmNDA2Mjc5MzUxYWE0ODQ5NDVjMzNhNWQwNzI5ZTkxNDM1MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cjQ8DxdpZ7miqFCM_CwksDB86P8OVr7ViXQBPoORRkI)

Hello, I meet the same problem recently, have you resolve it? If so, please tell me how to resolve this problem, thank you.

**Comment by mhmodayman** [comment]
I had to do the following changes to (init_weights, and select_action functions) in Agent class of SB3's TD3 implementation for TD3 to work properly after learning starts (inspired by SB3's PPO implementation):

Case 1 is the original case, case 2 is my modifications (as far as I remember :) )

```
class Agent():
    """Agent that plays and learn from experience. Hyper-paramters chosen from paper."""
    def __init__(
            self, 
            state_size, 
            action_size, 
            max_action, 
            discount=0.99,
            tau=0.005,
            policy_noise=0.2,
            noise_clip=0.1,
            policy_freq=2
        ):

        ...
        ...
        ...
        ...

    def init_weights(self, layer, gain=1):
        # -------------------------------------------
        # # case 1
        # """Xaviar Initialization of weights"""
        # if(type(layer) == nn.Linear):
        #   nn.init.xavier_normal_(layer.weight)
        #   layer.bias.data.fill_(0.01)
        # -------------------------------------------
        # -------------------------------------------
        # case 2
        """
        Orthogonal initialization (used in PPO and A2C)
        """
        if isinstance(layer, (nn.Linear, nn.Conv2d)):
            nn.init.orthogonal_(layer.weight, gain=gain)
            if layer.bias is not None:
                layer.bias.data.fill_(0.0)
        # -------------------------------------------

    def select_action(self, state, action_space):
        """Selects an automatic epsilon-greedy action based on the policy"""
        # -------------------------------------------
        # # case 1
        # state = torch.FloatTensor(state.reshape(1, -1)).to(device)
        # unscaled_action = self.actor(state).cpu().data.numpy().flatten()
        # scaled_action = self.scale_action(unscaled_action, action_space)
        # -------------------------------------------
        # case 2 [this works better]
        unscaled_action = action_space.sample()  # sample() is a feature in gym environments
        scaled_action = self.scale_action(unscaled_action, action_space)
        # -------------------------------------------
        return scaled_action
```

**Comment by FinishFYP** [comment]
> I had to do the following changes to (init_weights, and select_action functions) in Agent class of SB3's TD3 implementation for TD3 to work properly after learning starts (inspired by SB3's PPO implementation):
> 
> Case 1 is the original case, case 2 is my modifications (as far as I remember :) )
> 
> ```
> class Agent():
>     """Agent that plays and learn from experience. Hyper-paramters chosen from paper."""
>     def __init__(
>             self, 
>             state_size, 
>             action_size, 
>             max_action, 
>             discount=0.99,
>             tau=0.005,
>             policy_noise=0.2,
>             noise_clip=0.1,
>             policy_freq=2
>         ):
> 
>         ...
>         ...
>         ...
>         ...
> 
>     def init_weights(self, layer, gain=1):
>         # -------------------------------------------
>         # # case 1
>         # """Xaviar Initialization of weights"""
>         # if(type(layer) == nn.Linear):
>         #   nn.init.xavier_normal_(layer.weight)
>         #   layer.bias.data.fill_(0.01)
>         # -------------------------------------------
>         # -------------------------------------------
>         # case 2
>         """
>         Orthogonal initialization (used in PPO and A2C)
>         """
>         if isinstance(layer, (nn.Linear, nn.Conv2d)):
>             nn.init.orthogonal_(layer.weight, gain=gain)
>             if layer.bias is not None:
>                 layer.bias.data.fill_(0.0)
>         # -------------------------------------------
> 
>     def select_action(self, state, action_space):
>         """Selects an automatic epsilon-greedy action based on the policy"""
>         # -------------------------------------------
>         # # case 1
>         # state = torch.FloatTensor(state.reshape(1, -1)).to(device)
>         # unscaled_action = self.actor(state).cpu().data.numpy().flatten()
>         # scaled_action = self.scale_action(unscaled_action, action_space)
>         # -------------------------------------------
>         # case 2 [this works better]
>         unscaled_action = action_space.sample()  # sample() is a feature in gym environments
>         scaled_action = self.scale_action(unscaled_action, action_space)
>         # -------------------------------------------
>         return scaled_action
> ```

Thank you for your detailed reply. But I can't find the similar source code in SB3 as you have written above, could you please tell me if this was written by yourself or if it was a modification to the source code?

**Comment by FinishFYP** [comment]
> I had to do the following changes to (init_weights, and select_action functions) in Agent class of SB3's TD3 implementation for TD3 to work properly after learning starts (inspired by SB3's PPO implementation):
> 
> Case 1 is the original case, case 2 is my modifications (as far as I remember :) )
> 
> ```
> class Agent():
>     """Agent that plays and learn from experience. Hyper-paramters chosen from paper."""
>     def __init__(
>             self, 
>             state_size, 
>             action_size, 
>             max_action, 
>             discount=0.99,
>             tau=0.005,
>             policy_noise=0.2,
>             noise_clip=0.1,
>             policy_freq=2
>         ):
> 
>         ...
>         ...
>         ...
>         ...
> 
>     def init_weights(self, layer, gain=1):
>         # -------------------------------------------
>         # # case 1
>         # """Xaviar Initialization of weights"""
>         # if(type(layer) == nn.Linear):
>         #   nn.init.xavier_normal_(layer.weight)
>         #   layer.bias.data.fill_(0.01)
>         # -------------------------------------------
>         # -------------------------------------------
>         # case 2
>         """
>         Orthogonal initialization (used in PPO and A2C)
>         """
>         if isinstance(layer, (nn.Linear, nn.Conv2d)):
>             nn.init.orthogonal_(layer.weight, gain=gain)
>             if layer.bias is not None:
>                 layer.bias.data.fill_(0.0)
>         # -------------------------------------------
> 
>     def select_action(self, state, action_space):
>         """Selects an automatic epsilon-greedy action based on the policy"""
>         # -------------------------------------------
>         # # case 1
>         # state = torch.FloatTensor(state.reshape(1, -1)).to(device)
>         # unscaled_action = self.actor(state).cpu().data.numpy().flatten()
>         # scaled_action = self.scale_action(unscaled_action, action_space)
>         # -------------------------------------------
>         # case 2 [this works better]
>         unscaled_action = action_space.sample()  # sample() is a feature in gym environments
>         scaled_action = self.scale_action(unscaled_action, action_space)
>         # -------------------------------------------
>         return scaled_action
> ```
thank you for your detailed reply. But I cannot accurately locate this code in SB3, can you tell me its exact location?
