### ISSUE TITLE
[breaking change]: save closes files now

### ISSUE THREAD

**Issue by araffin** [DLR-RM/stable-baselines3#1751]
### 🐛 Bug

I'm not sure if it's a bug or not, but this is a consequence of https://github.com/DLR-RM/stable-baselines3/pull/1742.

because we are now closing the file, we cannot do what is shown in the bug report.
Maybe we could add an option (`close_file=True`) to the save method?

See failure in https://github.com/DLR-RM/rl-baselines3-zoo/actions/runs/6894076123/job/18755195768?pr=424

### To Reproduce

```python
import tempfile
from stable_baselines3 import PPO

temp_file = tempfile.TemporaryFile()
PPO("MlpPolicy", "CartPole-v1").save(temp_file)
model = PPO.load(temp_file)
```

### Relevant log output / Error message

```shell
File "stable_baselines3/common/save_util.py", line 212, in open_path
    raise ValueError(f"File stream {path} is closed.")
ValueError: File stream <_io.BufferedRandom name=14> is closed.
```

### System Info

- Python: 3.10.9
- Stable-Baselines3: 2.2.0
- PyTorch: 2.1.0+cpu
- GPU Enabled: False
- Numpy: 1.24.4
- Cloudpickle: 2.2.1
- Gymnasium: 0.29.1
- OpenAI Gym: 0.26.2

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Without having looked at the implementation details, from a usage point of view, I expect the following examples to work:

With a stream: 
```python
fp = tempfile.TemporaryFile()
PPO("MlpPolicy", "CartPole-v1").save(fp)
model = PPO.load(fp)
fp.close()
```

```python
with tempfile.TemporaryFile() as fp:
    PPO('MlpPolicy', 'CartPole-v1').save(fp)
    model = PPO.load(fp)
```

Or, with `str`:
```python
fp = "ppo_cartpole.zip"
PPO('MlpPolicy', 'CartPole-v1').save(fp)
model = PPO.load(fp)
```

```python
fp = "ppo_cartpole.zip"
with open(fp, 'wb') as f:
    PPO('MlpPolicy', 'CartPole-v1').save(fp)

with open(fp, 'rb') as f:
    model = PPO.load(fp)
```

And I except this not to work:

```python
fp = tempfile.TemporaryFile()
PPO("MlpPolicy", "CartPole-v1").save(fp)
fp.close()
model = PPO.load(fp)
```

```python
with tempfile.TemporaryFile() as fp:
    PPO('MlpPolicy', 'CartPole-v1').save(fp)

model = PPO.load(fp)
```

I don't like the option of adding a `close_file=True` argument.

**Comment by araffin** [comment]
> I don't like the option of adding a close_file=True argument.

you mean it would be better `close_file=False` or to revert back to no closing at all (what was done here: https://github.com/DLR-RM/stable-baselines3/pull/1742)?
and close manually in the checkpoint callback?

To make it clear, the behavior that you expect was the one before https://github.com/DLR-RM/stable-baselines3/pull/1742.

**Comment by qgallouedec** [comment]
Easier to explain with code: #1754
