### ISSUE TITLE
[Bug]: Pop out window Glitchy

### ISSUE THREAD

**Issue by AdrianRamos956** [DLR-RM/stable-baselines3#1753]
### 🐛 Bug

Hi if anyone can help me I'm new to this. I just installed stable-baselines3 and when I try and run the quick example of how to train and run A2C on a CartPole environment this is the pop-out window that shows at the end
![Glitchy](https://github.com/DLR-RM/stable-baselines3/assets/55201263/f41547cc-fa90-4206-ad46-461e11cb70fb)

### To Reproduce

import gymnasium as gym
from stable_baselines3 import A2C

env = gym.make("CartPole-v1", render_mode="rgb_array")

model = A2C("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10_000)

vec_env = model.get_env()
obs = vec_env.reset()
for i in range(1000):
    action, _state = model.predict(obs, deterministic=True)
    obs, reward, done, info = vec_env.step(action)
    vec_env.render("human")
    # VecEnv resets automatically
    # if done:
    #   obs = vec_env.reset()

### System Info

- OS: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 # 1 SMP Thu Oct 5 21:02:42 UTC 2023
- Python: 3.10.12
- Stable-Baselines3: 2.2.0
- PyTorch: 2.1.1+cu121
- GPU Enabled: True
- Numpy: 1.26.2
- Cloudpickle: 3.0.0
- Gymnasium: 0.29.1

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
have you tried with render_mode="human" instead?
it is likely to be a open cv issue, not really sb3

**Comment by AdrianRamos956** [comment]
so weirdly enough with that line changed to env = gym.make("CartPole-v1", render_mode="human") the render now opens before the training is finished and it opens a pygame window now, sadly still has the same issue in the rendering
![Glitchy2](https://github.com/DLR-RM/stable-baselines3/assets/55201263/a456a3d6-42ac-4bed-b011-97e48bfb19bc)

**Comment by araffin** [comment]
then, it's definitely not a sb3 problem...
