### ISSUE TITLE
[Question] Which stable-baselines3 algorithm implements the AlphaGo Zero or AlphaZero algorithm?

### ISSUE THREAD

**Issue by dimitri-rusin** [DLR-RM/stable-baselines3#1755]
### ❓ Question

So, I have seen this list here: https://stable-baselines3.readthedocs.io/en/master/guide/algos.html

But which of those comes closest to the actual algorithm they used to solve the game of Go?

Thank you for looking at my question!

By the way, you are awesome for making this repository! Thank you so much!!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

None of them: https://github.com/DLR-RM/stable-baselines3/issues/1464
