### ISSUE TITLE
[Bug]: v2.2.0 has no GitHub release tag

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [DLR-RM/stable-baselines3#1756]
### 🐛 Bug

[2.2.0](https://pypi.org/project/stable-baselines3/2.2.0/) has been release in pypi, but no GitHub release was made

### To Reproduce

go to https://github.com/DLR-RM/stable-baselines3/tags

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
we realised there was a breaking change just before doing the full release, so we are working on a hotfix : https://github.com/DLR-RM/stable-baselines3/pull/1754 (and related issues).

Out of curiosity: is the fact that there is no tag breaking something ?

**Comment by Kallinteris-Andreas** [comment]
> Out of curiosity: is the fact that there is no tag breaking something ?

I wanted to use a custom `EvalCallback` (with deterministic evaluation) and wanted to make sure that the version I am basing it on is the same as the one in `2.2.0` and would be easier for me to that if there was tag

**Comment by araffin** [comment]
Fixed by https://github.com/DLR-RM/stable-baselines3/releases/tag/v2.2.1
