### ISSUE TITLE
[Question] proper order to use the monitor wrapper

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [DLR-RM/stable-baselines3#1757]
### ❓ Question

Should an obs/reward wrapper inside or outside the

the doc does not specify https://stable-baselines3.readthedocs.io/en/master/common/monitor.html

(ie which one of the following is correct)
```py
    env = TransformReward(Monitor(gym.make(env_id, render_mode=None)), f= lambda d : d+1)
    env = Monitor(TransformReward(gym.make(env_id, render_mode=None), f= lambda d : d+1))
```

Note that `env` will later be used in a `EvalCallback`

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
See https://github.com/DLR-RM/stable-baselines3/issues/181

It depends on what you want to do/benchmark, but option 1 is usually the recommended one (logging original reward).

In case you need both, you can use two monitor wrappers that would log to different files.
