### ISSUE TITLE
[feature request] Add info to rollout buffer

### ISSUE THREAD

**Issue by neighthan** [DLR-RM/stable-baselines3#176]
Currently the rollout buffer doesn't store the info returned at each step of the environment. I assume this is for efficiency since the info may often not be needed. My use case is that I want to access the info from a callback's `on_rollback_end` for logging. Would it be possible to add a flag to the rollout buffer which controls whether the info is saved as well? If we use a list instead of a numpy array, then we don't need to know the structure of the info ahead of time. I expect this would be easy to implement and would be happy to make a PR if this feature would be accepted. (it seems like [`RolloutBuffer.add`] would need to be changed to optionally accept an `info` argument; I'm not sure where this is called from, but we'd have to add info to any calls between the environment's step and adding to the rollout buffer)

([`rlpyt`] has a nice named tuple array object for storing the info so that you can access fields by name and also do slicing like in an array; something like this could be an alternative instead of just a list of dictionaries, but it's less general (we'd need to know the info keys ahead of time and all keys have to be present at all steps or else have some defined "missing" value; also, you'd probably only want numeric info)).

[`RolloutBuffer.add`]: https://github.com/DLR-RM/stable-baselines3/blob/55912576edd4cb459494f3d48f0b0d0806eced3f/stable_baselines3/common/buffers.py#L329
[`rlpyt`]: https://github.com/astooke/rlpyt

**Comment by araffin** [comment]
Hello,
Good point.

> My use case is that I want to access the info from a callback's on_rollback_end for logging.

Why don't you access it from the `_on_step()` using `self.locals["infos"]` ?

**Comment by neighthan** [comment]
Hm, I suppose I'd just wanted to deal with it at the end of the rollout with all of the other information. But I could easily put tracking the info into my `_on_step` instead of into `RolloutBuffer` and then have the accumulated info ready for the end of the rollout. That's an easy enough workaround that I'll go ahead and close this issue unless there's any further interest in the info being present in the rollout buffer itself.
