### ISSUE TITLE
[Question] Why is `DQN`'s default `learning_starts` parameter set to much higher value than all the other algorithms

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [DLR-RM/stable-baselines3#1760]
### ❓ Question

[DDPG](https://stable-baselines3.readthedocs.io/en/master/modules/ddpg.html#stable_baselines3.ddpg.DDPG), [SAC](https://stable-baselines3.readthedocs.io/en/master/modules/sac.html#stable_baselines3.sac.SAC) and [TD3](https://stable-baselines3.readthedocs.io/en/master/modules/td3.html#stable_baselines3.td3.TD3) have their `learning_starts` argument set to `=100` but [DQN](https://stable-baselines3.readthedocs.io/en/master/modules/ddpg.html#stable_baselines3.ddpg.DDPG) has its `learning_starts` argument set to `=50000`, 
is there a design reason for it? (e.g. do Discrete action space algorithms require more a bigger `learning_starts` parameter?)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
the main reason was to match Atari default hyperparameters, but as for TD3, it might time to change as it confuses many users.

**Comment by Kallinteris-Andreas** [comment]
I would recommend 50k for all algorithms to be consistent, and because it is 5% of the default ERB max_size which generally is a good compromise for most environments
(note: I have only experimented on robotic envs though)

**Comment by araffin** [comment]
Fixed in https://github.com/DLR-RM/stable-baselines3/pull/1785
