### ISSUE TITLE
[Question] Why does my ppo predict always return action= 0 on all data or action=1 on all data. 

### ISSUE THREAD

**Issue by Sankalp96** [DLR-RM/stable-baselines3#1764]
### ❓ Question

Here is the env i'm using:
class PushNotificationRecommenderEnv(gym.Env):
    def __init__(self, user_nudge_df, user_features_df, nudge_features_df):
        super(PushNotificationRecommenderEnv, self).__init__()

        self.user_nudge_df = user_nudge_df
        self.user_features_df = user_features_df
        self.nudge_features_df = nudge_features_df
        self.num_users = len(user_nudge_df)
        self.pushed_nudges = {}
        self.reward_lst = []
        self.regret = 0
        self.action_space = gym.spaces.Discrete(2)  # Two possible actions: 0 (drop nudge) or 1 (send nudge)
        self.observation_space = gym.spaces.Box(low=-np.inf, high=np.inf, shape=(17,), dtype=np.float32)

        self.reset()

    def reset(self):
        self.user_queue = [[] for _ in range(self.num_users)]
        self.user_index = 0
        self.index = 0
        self.time_step = 0
        self.reward_lst = []
        state = self._get_state()
        return state

    def step(self, action):
        self.index += 1
        self.user_index += 1
        self.time_step += 1

        if self.user_index >= self.num_users:
            self.user_index = 0

        if self.index == len(self.user_nudge_df):
            self.index = 0

        if self.time_step >= self.num_users:
            done = True
        else:
            done = False

        if action:
            reward = user_nudge_df.loc[self.index]['Rewards']
           
        else:
            reward = 0

        next_state = self._get_state()
        self.pushed_nudges[self.user_nudge_df.loc[self.index]['CLIENT_CODE']] = action
        return next_state, reward, done, {}

    def get_reward(self, user_index):
        return self.user_nudge_df['Rewards']

    def _get_state(self):
        user_features = self.user_features_df[self.user_features_df['CLIENT_CODE'] == eval(self.user_nudge_df.iloc[self.index]['CLIENT_CODE'])].iloc[0, 1:]
        nudge_features = self.nudge_features_df[self.nudge_features_df['callid'] == self.user_nudge_df.iloc[self.index]['callid']].iloc[0, 1:]
        return np.concatenate((user_features, nudge_features)).astype(np.float32)

    def render(self, mode='human'):
        pass

Using this for prediction on entire dataset:

env = PushNotificationRecommenderEnv(user_nudge_df, user_features, nudge_features)

num_episodes = 1  # You can adjust this as needed

total_rewards = []
i=0
for episode in range(num_episodes):
    print(f'episode number --- {episode} --')
    obs = env.reset()
    episode_reward = 0

    i+=1
    while True:
        action, _ = model.predict(obs, deterministic=True)  # Use the trained model to select actions deterministically
        # print(i)
        print(action)
        obs, reward, done, _ = env.step(action)
        # print(reward)
        episode_reward += reward

        if done:
            break

    total_rewards.append(episode_reward)
    print(f'reward mean in this episode =  {np.mean(total_rewards)} ---')

avg_reward = np.mean(total_rewards)
print("Average Reward:", avg_reward)

I don't understand because while training it considers both action 1 and 0 but during prediction it always return either 0 on all or 1 on all data.
![image](https://github.com/DLR-RM/stable-baselines3/assets/76246701/972f6647-079c-49f5-91d2-2b0ba8362adb)

For reward purpose giving 1 for each click and -1 for not seeing the notification. Rewards are almost distributed symmetrical.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [x] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by Sankalp96** [comment]
Which boxes are you referring to? @araffin

**Comment by araffin** [comment]
> Which boxes are you referring to? 

> ### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

and

"If your issue is related to a custom gym environment, please use the custom gym env template."

**Comment by araffin** [comment]
Closing as the minimum requirements for seeking help are not met.
