### ISSUE TITLE
[Question] Independent vector environments

### ISSUE THREAD

**Issue by zichunxx** [DLR-RM/stable-baselines3#1772]
### ❓ Question

Hi!

I want to test if an environment will converge with the same model structure but with different seeds. After training, I want to get five curves of success rate to derive median rates with shaded areas. 

I have read the document and think `SubprocVecEnv` could be the best choice for me, but finally I can get only one training curve.

Can I use a vectorized environment to achieve my goals? Or, do I have to perform different training tasks at 5 different terminals each?

Thanks in advance!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
You're confusing run and environments. Actually, environment vectorisation enables the interactions collection to be parallelized to make the run faster. But only one agent is learned.

What you want to do is repeat the run several times. So yes, use 5 different processes, and launch a run on each one.
