### ISSUE TITLE
make_vec_env much slower than SubprocVecEnv when using multiprocessing with custom gym environment

### ISSUE THREAD

**Issue by atharvaaalok** [DLR-RM/stable-baselines3#1778]
### 🐛 Bug

I have created a custom gym environment and want to train a model using it in parallel, therefore, I am trying to use multiprocessing.
On #1775 I asked about the issue of no reward getting printed during training when I use the `SubprocVecEnv` function.
I was suggested to use the `make_vec_env` approach instead.
I am using that now but the training is much slower with it (atleast 2-3x slower as shown in the log below).
Details of my custom environment are available in #1775 

What can I do to print mean rewards during training and get the speed up of multiprocessing?

### Code example

My previous approach with `SubprocVecEnv`:
```
def make_env(env_id: str, rank: int, seed: int = 0) -> Callable:

    def _init() -> gym.Env:
        s0 = np.array([[1, 0], [0.75, 0.05], [0.625, 0.075], [0.5, 0.1], [0.25, 0.05], [0, 0], [0.25, -0.05], [0.5, -0.1], [0.625, -0.075], [0.75, -0.05], [1, 0]])
        idx_to_change = [1, 2, 3, 4, 6, 7, 8, 9]
        a_scaling = (1 / 1000)
        valid_states_file_path = os.path.dirname(__file__) + '/Dataset/Arrays_as_rows.txt'

        # Get the environment
        training_env = CFD_Env(s0, idx_to_change, a_scaling, valid_states_file_path)
        # Reset the environment
        observation, info = training_env.reset(seed = seed + rank)

        return training_env

    set_random_seed(seed)
    return _init

if __name__ == '__main__':
    env_id = 'CFD_Gym_Env'
    num_cpu = 5
    env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])
    # Train PPO on the environment
    model = PPO('MlpPolicy', env, verbose = 1, tensorboard_log = log_dir)
```

My new approach with `make_vec_env`:
```
def make_env() -> Callable:

    def _init() -> gym.Env:
        s0 = np.array([[1, 0], [0.75, 0.05], [0.625, 0.075], [0.5, 0.1], [0.25, 0.05], [0, 0], [0.25, -0.05], [0.5, -0.1], [0.625, -0.075], [0.75, -0.05], [1, 0]])
        idx_to_change = [1, 2, 3, 4, 6, 7, 8, 9]
        a_scaling = (1 / 1000)
        valid_states_file_path = os.path.dirname(__file__) + '/Dataset/Arrays_as_rows.txt'

        # Get the environment
        training_env = CFD_Env(s0, idx_to_change, a_scaling, valid_states_file_path)
        # Reset the environment
        observation, info = training_env.reset()

        return training_env

    return _init

if __name__ == '__main__':
    env_id = 'CFD_Gym_Env'
    num_cpu = 5
    vec_env = make_vec_env(make_env(), n_envs = num_cpu)
    # Train PPO on the environment
    model = PPO('MlpPolicy', vec_env, verbose = 1, tensorboard_log = log_dir)
```

### Relevant log output / Error message

```shell
When using make_vec_env
1% ━╸━━━━━━━━━━━━━━ 50/5,000  [ 0:00:10 < 0:17:00 , 5 it/s ]

When using SubprocVecEnv
 2% ━━╺━━━━━━━━━━━ 80/5,000  [ 0:00:04 < 0:04:56 , 17 it/s ]
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by atharvaaalok** [comment]
No when I try using built-in gym environment as below, I observe similar performance.
```
import time

import gymnasium as gym
import numpy as np

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, SubprocVecEnv
from stable_baselines3.common.utils import set_random_seed
from stable_baselines3.common.env_util import make_vec_env


from typing import Callable


def make_env(env_id: str, rank: int, seed: int = 0) -> Callable:

    def _init() -> gym.Env:
        env = gym.make(env_id)
        env.reset(seed=seed + rank)
        return env

    set_random_seed(seed)
    return _init

if __name__ == '__main__':
    env_id = "CartPole-v1"
    num_cpu = 5  # Number of processes to use
    # Create the vectorized environment

    # # Using SubprocVecEnv
    # env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])
    # model = PPO('MlpPolicy', env, verbose = 1)
    # model.learn(total_timesteps = 100_000, progress_bar = True)


    # # By default, we use a DummyVecEnv as it is usually faster (cf doc)
    vec_env = make_vec_env(env_id, n_envs=num_cpu)
    model = PPO('MlpPolicy', vec_env, verbose = 1)
    model.learn(total_timesteps = 100_000, progress_bar = True)
```

**Comment by atharvaaalok** [comment]
> Is it only the case with your custom env?

My custom environment makes calls to subprocesses and calls a .exe file to calculate the reward

**Comment by qgallouedec** [comment]
I can't see any difference on my side: 20 sec to complete the training with both settings.

**Comment by atharvaaalok** [comment]
> I can't see any difference on my side: 20 sec to complete the training with both settings.

are you referring to my custom environment?
Or to the trial script I provided?

**Comment by atharvaaalok** [comment]
> I am referring to this answer: [#1778 (comment)](https://github.com/DLR-RM/stable-baselines3/issues/1778#issuecomment-1846157813)

Yes that does not give me any difference either.
That is a dummy example I used to test whether it was just my custom environment that had different performance under SubprocVecEnv and make_vec_env.

**Comment by atharvaaalok** [comment]
Oh I see, my bad, grammatical error ;)
Thanks this fixed my problem, it seems to be working great!
