### ISSUE TITLE
[Question] Is it possible to block on just one SubprocVecEnv while others run?

### ISSUE THREAD

**Issue by batu** [DLR-RM/stable-baselines3#178]
Hello!

Great work on the SB3, looking forward to seeing 1.0.

Currently, I am trying to reimplement [Learning from Human Preferences](https://openai.com/blog/deep-reinforcement-learning-from-human-preferences/) paper and get a human in the loop RL training workflow working.

Ideally, I would use one SubprocVecEnv to collect feedback from the human while others continue to collect experience and train. Is this even possible?

For context, I am currently using PPO, and asking for human feedback in `collect_rollouts` function, right before the advantages are computed. 

Hope I could explain my question, let me know if more details are needed.

Thank you for the great library!

**Comment by Miffyli** [comment]
To summarize: In SubprocVecEnv, you'd like to use one of the environments to provide feedback from humans while other environments continue collecting experiences as normally.

Answer is "not without modifications". Despite being in separate processes, VecEnv environments all run in sync, so other environments will wait for the human's feedback before moving onto next step. To separate the two you'd have to modify the code in [rollout collection](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/on_policy_algorithm.py#L123), which should be doable depending on how exactly the experiences from humans and environments are combined.

**Comment by batu** [comment]
The summary is correct!

I realized that all the environments wait until each of them returns the step. My approach was going to be updating the SubprocVecEnv itself, and having the environment wrapper run a data collection process.

Would you mind sharing a little bit more? I don't think the code can we wrapped up using the async module, so what you are saying I can spin up a new process in rollout collection?

thank you for your time

**Comment by Miffyli** [comment]
> so what you are saying I can spin up a new process in rollout collection?

Yes, essentially. If you want agent to be collecting environment data (standard vec-env steps) but also collected human data at the same time, you need to spin up a new process inside the rollout collection to handle this. However if your environment is fast and you can interleave environment-human actions (e.g. collect 2 rollouts from env, ask human for reward, collect 2 rollouts from env, ask human for reward, etc...), then you can manage without adding new processes, instead you modify the core algorithm code to accommodate this. Rollouts are collected (here)[https://github.com/DLR-RM/stable-baselines3/blob/a10e3ae5870836ed38e0b65c4176bbec3f22a1cb/stable_baselines3/common/on_policy_algorithm.py#L217] and parameters are updated bit later (here)[https://github.com/DLR-RM/stable-baselines3/blob/a10e3ae5870836ed38e0b65c4176bbec3f22a1cb/stable_baselines3/common/on_policy_algorithm.py#L237].

**Comment by batu** [comment]
That is enough for me to get started, thank you!
