### ISSUE TITLE
[Question] On the issue of changing policy networks

### ISSUE THREAD

**Issue by yshichseu** [DLR-RM/stable-baselines3#1780]
### ❓ Question

![5d7e622c5b288bb7cb43bb076c04a43](https://github.com/DLR-RM/stable-baselines3/assets/106796102/29bb67c9-853a-4c34-8f11-20eaa6fa4a59)
Hello, I am a beginner in reinforcement learning algorithms, so thank you for providing me with such a library to learn. Since I changed the observation method in the Gym environment to the grid method, I used cnnpolicy instead of mlppoolicy in the policy network and found that I cannot observe my average reward and average step size through Tensorboard. How can I adjust it? Thank you!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> If code there is, it is minimal and working

Closing because the minimum requirements for seeking help are not met.
