### ISSUE TITLE
[Feature Request] Turn Logger OFF

### ISSUE THREAD

**Issue by WreckItTim** [DLR-RM/stable-baselines3#1782]
### 🚀 Feature

Hello, thanks for the great repo!

Is it possible to turn the logger off during model.learn() ? For now I am just using a high log_interval like 9999.
The reason being is that I sync with Dropbox across multiple devices, and Dropbox keeps a recycle bin of all files - including all of the logging output being written by SB3 --- which quickly adds up to 100s of gb for how much training I am doing. It is a nightmare lol.

Anyways, if there is no functional purpose of the logger I would like a simple feature just to turn it off. I don't see it in the docs, but maybe I missed it. Thanks!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
> f. I don't see it in the docs, but maybe I missed it. Thanks!

`verbose=0` or `log_interval=1000`

For instance, for PPO: https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html#stable_baselines3.ppo.PPO
