### ISSUE TITLE
[Bug]: Custom Policy Type Error

### ISSUE THREAD

**Issue by AdamLabiosa** [DLR-RM/stable-baselines3#1784]
### 🐛 Bug

Hello, I couldn't find any examples of this anywhere else so I apologize if this is a trivial mistake on my part. I'm using a custom policy network to train my policies. Training seems to work fine. When I to load it in to visualize it and test however I get an error. Importantly, using the policy `from stable_baselines3.ppo import MlpPolicy` works but when I change it to the custom policy it has an error.

### To Reproduce

It should be possible to reproduce simply by using this policy

```
class LargeMlpPolicy(ActorCriticPolicy):
    def __init__(self, *args, **kwargs):
        super(LargeMlpPolicy, self).__init__(
            *args, **kwargs, net_arch=dict(pi=[1024, 1024, 1024], vf=[1024, 1024, 1024])
        )
```

```
model = PPO(
        LargeMlpPolicy,
        env,
        batch_size=args.batch_size,
        ent_coef=0.01,
        verbose=1,
        tensorboard_log=f"./runs/{run_name}",
        device=device,
    )
```

And learn and save commands:

 ```
model.learn(total_timesteps=args.train_steps)
model.save("policies/" + args.env + "_policy")
```

And finally loading it 
```
model = PPO.load(policy_path)
```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "/Users/adamlabiosa/Documents/research/AbstractSim/global_self_play/runTE.py", line 149, in <module>
    render(args)
  File "/Users/adamlabiosa/Documents/research/AbstractSim/global_self_play/runTE.py", line 133, in render
    model = PPO.load(policy_path)
  File "/Users/adamlabiosa/Documents/research/AbstractSim/.venv/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 731, in load
    policy=data["policy_class"],
KeyError: 'policy_class'
```

### System Info

```
- OS: macOS-14.1.2-arm64-arm-64bit Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112
- Python: 3.9.18
- Stable-Baselines3: 2.1.0
- PyTorch: 2.0.1
- GPU Enabled: False
- Numpy: 1.26.0
- Cloudpickle: 2.2.1
- Gymnasium: 0.29.1
```
I am using a custom environment but the error here is not related to that. It should happen in any environment I believe.

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
why are you not using `policy_kwargs` as shown in the doc?

I cannot reproduce the error when doing:
```python
from stable_baselines3.common.policies import ActorCriticPolicy
from stable_baselines3 import PPO


class LargeMlpPolicy(ActorCriticPolicy):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs, net_arch=dict(pi=[10], vf=[10]))


model = PPO(LargeMlpPolicy, "CartPole-v1")
model.save("tmp")
del model
model = PPO.load("tmp.zip")
```

You might want to register your policy too (see https://github.com/DLR-RM/stable-baselines3/issues/841) and an example:
```python
from stable_baselines3.common.policies import ActorCriticPolicy
from stable_baselines3 import PPO


class LargeMlpPolicy(ActorCriticPolicy):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs, net_arch=dict(pi=[10], vf=[10]))

# Register custom policy
PPO.policy_aliases["CustomPolicy"] = LargeMlpPolicy

model = PPO("CustomPolicy", "CartPole-v1")
model.save("tmp")
del model
model = PPO.load("tmp.zip")

```

**Comment by AdamLabiosa** [comment]
I'm sorry for the mislabeled post. It is not a bug. 

Adding in 
``` 
PPO.policy_aliases["LargeMlp"] = LargeMlpPolicy
```

Fixed the issue. 

I'm unsure why the base code wasn't working in my case but worked in yours but that is just something for me to figure out. Thanks for your help!
