### ISSUE TITLE
Better Hyperparameter editing

### ISSUE THREAD

**Issue by AwesomeCap** [DLR-RM/stable-baselines3#1788]
### 🚀 Feature

Hyperparameter edit

### Motivation

This will increase the models result by 2x-5x in some cases

### Pitch

In the paper: https://arxiv.org/abs/2006.05990 different hyperparameters are tested to see what hyperparameters have the most effect on training. The best hyperparameters setups have more than a 2x result when training.

<img width="530" alt="Skärmavbild 2023-12-18 kl  18 03 00" src="https://github.com/DLR-RM/stable-baselines3/assets/48380481/333831bc-8b0c-4989-a8a1-2ffdd4d34e50">

Most of hyperparameters have no effect on the result, but some hyperparameters that does, according to the paper, can't be in a easy way set with Stable Baseline 3. 

Like for example Initial standard deviation (have a big effect), a lot of entropy related values etc.

<img width="545" alt="Skärmavbild 2023-12-18 kl  18 04 58" src="https://github.com/DLR-RM/stable-baselines3/assets/48380481/7f155744-4def-449f-8b8e-73efecb42b1b">

It would be great to make these values easy to set to get better results.

### Alternatives

Just fix so you can set the hyperparameter Initial standard deviation.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by Ivan-267** [comment]
Hello,

I've recently done some experimentation with changing the initial standard deviation while training my envs, here is the relevant snippet:

```python
    policy_kwargs = dict(log_std_init = log(1))
    model = PPO("MultiInputPolicy", env, policy_kwargs=policy_kwargs) 
```

You can see various policy kwargs that you can change for the policy here:
https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html#stable_baselines3.ppo.MlpPolicy
(that is for PPO MlpPolicy, but I see the same option for e.g. SAC).

There's some more info on custom policy settings here:
https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-network-architecture

You may already be aware of this and asking for a different way to add the setting, or different settings, I'm just adding this info in case it helps.

**Comment by qgallouedec** [comment]
I see two things here:

1. On the one hand, you say that by changing certain hyperparameters, we could get significantly better results on certain environments. It would be great to run a few trainings with the [zoo](https://github.com/DLR-RM/rl-baselines3-zoo), and compare them with the existing benchmark (see [Open RL Benchmark / SB3](https://wandb.ai/openrlbenchmark/sb3)). If we find that the results are indeed significantly better, then we'll modify the hyperparameters values in the zoo (e.g. for PPO Hopper: [link](https://github.com/DLR-RM/rl-baselines3-zoo/blob/28dc22896abceb68ea5258dd7dee1d20a691864a/hyperparams/ppo.yml#L454)).

2. You write

> It would be great to make these values easy to set

I think, for example, that the way to set the initial log std is satisfactory (see @Ivan-267's comment), but perhaps you have other examples?
