### ISSUE TITLE
[Question] Multiple Callbacks For callback_on_new_best

### ISSUE THREAD

**Issue by EitanGronich** [DLR-RM/stable-baselines3#1791]
### ❓ Question

I have a simple use case that I have found no answer to in the documentation. (v. 2.2.1)
I want to pass two chained callbacks as a `callback_on_new_best` for `EvalCallback`. (A custom one for drawing a figure and a library one - StopTrainingOnRewardThreshold)
Passing a `CallbackList` doesn't seem to work, since the `parent` attribute of the callbacks is None, and the code throws an `AssertionError` because it asserts their `parent` is the `EvalCallback`.
There seem to be no other options except building a custom callback that does them both, but this doesn't seem like good practice given that CallbackList does exist.
Am I missing something?
Minimal reproducible:

```python
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import BaseCallback, EvalCallback, StopTrainingOnRewardThreshold, CallbackList

class CustomCallback(BaseCallback):

    def __init__(self, verbose=0):
        super().__init__(verbose)
    
    def _on_step(self):
        # Draw a figure
        return True


eval_env = gym.make("Pendulum-v1")

stop_on_threshold_callback = StopTrainingOnRewardThreshold(reward_threshold=-200, verbose=1)

eval_callback = EvalCallback(eval_env, best_model_save_path="./logs/",
                             log_path="./logs/", eval_freq=500,
                             deterministic=True, render=False,
                             callback_on_new_best=CallbackList([CustomCallback(), stop_on_threshold_callback])
                             )

model = PPO("MlpPolicy", "Pendulum-v1")
model.learn(5000, callback=eval_callback)
```
Thanks a lot!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue, I think we need to give access to the common parent when using a `CallbackList`.

**Comment by icheered** [comment]
Running into the same issue! Is there really no work around?

**Comment by araffin** [comment]
> Is there really no work around?

a quick workaround is to redefine `StopTrainingOnRewardThreshold`, combine the two callbacks in one

a better workaround is to fix the code and I would appreciate a PR that solves this issue ;)

**Comment by will-maclean** [comment]
I'm happy to work on implementing this one
