### ISSUE TITLE
tensorflow.python.framework.errors_impl.FailedPreconditionError: ./logs\SAC_SmallScale_1 is not a directory

### ISSUE THREAD

**Issue by oldwhitenotblack** [DLR-RM/stable-baselines3#1792]
### 🐛 Bug

When I input visualization parameters `tensorboard_log='./logs'` and `tb_log_name='SAC_SmallScale'` in SAC () and learn(), an error occurs: `tensorflow.python.framework.errors_impl.FailedPreconditionError: ./logs\SAC_SmallScale_1 is not a directory`.

### Code example

model = SAC("MultiInputPolicy", env,tensorboard_log='./logs',verbose=1)
model.learn(total_timesteps=10000, log_interval=4,tb_log_name='SAC_SmallScale')

### Relevant log output / Error message

```shell
My custom environment is fine and can be used for model training without any issues. The error only occurs during visualization.Moreover, there is no error when I use `check_env`.
```

### System Info

python version --3.9.13
cpu --amd
pycharm --2023.3 profession
tensorflow version --2.15

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
It looks like you are mixing up linux `/` and windows `\` separators for paths.
Closing as it seems to be related to windows/tensorboard, not really sb3.
