### ISSUE TITLE
[Question] Does the Pong game have speed in their actions?

### ISSUE THREAD

**Issue by gglsmm** [DLR-RM/stable-baselines3#1798]
### ❓ Question

The pong game has 6 basic actions. Noop, fire, right, rightfire, left, left fire. My question is do actions that have fire options speed up the ball? 
According to the AtariAge page, the red button in the actual controller adds some speed. Did you add this feature to the gymnasium?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
https://github.com/Farama-Foundation/Gymnasium/issues/865
