### ISSUE TITLE
[Question] Is there any paper reference on the principles behind the multiprocess training in Stable-baselines3?

### ISSUE THREAD

**Issue by syemichel** [DLR-RM/stable-baselines3#1803]
### ❓ Question

I want to use the multiprocessing code from stable baselines 3 as a baseline, but I don't know what paper to cite.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
you can cite SB3 paper and also refer to the A2C blog post or A3C paper.

**Comment by syemichel** [comment]
> Hello, you can cite SB3 paper and also refer to the A2C blog post or A3C paper.

Thank you, I will carefully read the A3C paper.
