### ISSUE TITLE
EvalCallback on an episode-by-episode basis

### ISSUE THREAD

**Issue by docane** [DLR-RM/stable-baselines3#1804]
### 🚀 Feature

EvalCallback on an episode-by-episode basis

### Motivation

I'd like to make the evaluation an episode cycle rather than a step cycle, but the EvalCallback function doesn't support it. So I suggest this
https://github.com/DLR-RM/stable-baselines3/issues/140
I think it's similar to this

### Pitch

I hope EvalCallback can be run on an episode-by-episode basis.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [x] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
>  If I'm requesting a new feature, I have proposed alternatives

you can use a custom callback for that.

You can get inspiration from https://github.com/DLR-RM/stable-baselines3/blob/a653aec10d8cb4b82443f818fdde123f06c95f75/stable_baselines3/common/callbacks.py#L590.
