### ISSUE TITLE
[Question] How can I serialize a VecMonitor-wrapped env?

### ISSUE THREAD

**Issue by npit** [DLR-RM/stable-baselines3#1810]
### ❓ Question

In a deployment setting, I have set up and configured an environment wrapped with a `VecMonitor`. I want to provide that env object to other processes. 
When I try to pickle it however, I'm getting a message `cannot pickle 'mappingproxy' object`, caused by attempting to pickle the `class_attributes` member variable.

How can I serialize the wrapped env to disk?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
could you provide a minimal example to reproduce the error?

In general, environments are not meant to be serialized (and some can not be, for instance `SubprocVecEnv` or environments that uses locks/sockets/...)


> I want to provide that env object to other processes.

What is your end goal?
You might want to use a `Monitor` wrapper (at the env level) instead of a `VecMonitor` (at the `VecEnv` level).

**Comment by npit** [comment]
Here's a MRE:

```python
import pickle
import gymnasium as gym
from stable_baselines3.common.vec_env import DummyVecEnv, VecMonitor

env = gym.make('CartPole-v1')

env = VecMonitor(DummyVecEnv([lambda: env]))
with open('env.pkl', 'wb') as f:
    pickle.dump(env, f)
```

> What is your end goal?
> You might want to use a Monitor wrapper (at the env level) instead of a VecMonitor (at the VecEnv level).

Basically I want to apply the normalization learned during training in different workers.
Is there a normalizatoin wrapper other than VecNormalize at the env level?

**Comment by araffin** [comment]
> Basically I want to apply the normalization learned during training in different workers.
>  Is there a normalizatoin wrapper other than VecNormalize at the env level?

this is only at test time?
and why `VecNormalize` is not working for you?

There is a normalize wrapper in gymnasium, but it needs to be adapted to have all the features from `VecNormalize`.

**Comment by npit** [comment]
Yes, only at test time. My workflow:
1. Train and save model and vecnormalize stats
2. Load model / vecnormalize; for convenience and reproducibility, I'm creating the environment object in the same as in the training code (i.e. VecMonitor, VecNormalize, VecEnv, etc.).
3. Spawn a rest api with K workers, which should the wrapped environment for observation normalization (if any), the model for decision making and invoke an enrivonment step to generate simulation results.

Since I don't want to expose model-loading and env-creating functionality to the workers and run them multiple times, I'd like to do all that once in the main thread, serialize the results, and read them in each worker. Currently:
- Serializing a VecMonitor does not work
- Serializing a VecNormalize(DummyVecEnv(...)) with `dill` works, but the deserialized vec_env has a `None` value for `vec_env.venv`.

Does any fix / workaround come to mind? Should I just serialize the singular env and apply the normalization stored in the normalization wrapper by hand?

**Comment by araffin** [comment]
> Should I just serialize the singular env and apply the normalization stored in the normalization wrapper by hand?

probably, if you have only one env, you should not need `VecEnv`.
For the normalization, you mostly need to define a gym wrapper.
