### ISSUE TITLE
[Question] Do we have to set observation_space correctly in custom environments?

### ISSUE THREAD

**Issue by Everglow0214** [DLR-RM/stable-baselines3#1811]
### ❓ Question

What if I cannot know the lower bound and upper bound of some part of the observation? Is the member variable "observation_space" used for training in SB3?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
(Box space I guess?)
The boundaries of the observation space are not used. However, it's recommended to normalize the observation whenever possible. See [Tips and Tricks when creating a custom ](https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment).

**Comment by Everglow0214** [comment]
> (Box space I guess?) The boundaries of the observation space are not used. However, it's recommended to normalize the observation whenever possible. See [Tips and Tricks when creating a custom ](https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment).

Thanks for your reply. Yeah it is box space. As you recommend, I add normalization for observation. But for some parts of the observation, I can only try with different values of bounds and see the performance.
Thanks again for your comments ; )
