### ISSUE TITLE
[Question] Should SB3 add render_mode for GymV21CompatibilityV0?

### ISSUE THREAD

**Issue by Beanpow** [DLR-RM/stable-baselines3#1812]
### ❓ Question

# Question
As figure2, the `_patch_env` function didn't provide the `render_mode`, which is None in `GymV21CompatibilityV0`. Maybe we could change the _patch_env from

```
# Gym 0.21 env
return shimmy.GymV21CompatibilityV0(env=env)
```
to
```
# Gym 0.21 env
return shimmy.GymV21CompatibilityV0(env=env, render_mode=getattr(env, "render_mode", None))
```

In case you need it, I could submit a PR.

# Appendix
## Figure1. The GymV21CompatibilityV0 class for old gym env, which needs the parameter of render_mode
![image](https://github.com/DLR-RM/stable-baselines3/assets/37178760/8ccf4d09-994a-4dea-9ba3-33416a7a4e80)

## Figure2. The _patch_env function of SB3 for old gym env, which didn't provide the render_mode
![image](https://github.com/DLR-RM/stable-baselines3/assets/37178760/997d656d-5d63-40df-959a-4d92d233391c)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
does that prevent you from rendering an env? recording an env? what is the error?
