### ISSUE TITLE
[Question] Choosing action manually during training

### ISSUE THREAD

**Issue by phcha57** [DLR-RM/stable-baselines3#1813]
### ❓ Question

I am using a custom environment and calling model.learn on PPO.
I want to choose actions for my model during some of the training.
This is akin to imitation learning (at least for some part of the training).
The problem as I see it is that during the learning, when step is called, the action is already chosen.

For example, at the beginning of the training, there is a high probability that the action that it will take is the one that I would take. After N step, I reduce the probability that the action it performs is the one I would take. So on and so forth until all actions are chosen normally (without me needing to specify anything).

I want to decide the action that is taken by the model. Is there a way to specify the action before going into the step function during the learning?

Note: As an alternative, I could also overwrite the action chosen once it gets into the step function. But for this alternative to work, I would need a way to tell the replay buffer which action was overwrite. I also do not know how to do such a thing.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
>  I want to choose actions for my model during some of the training.

It seems you are breaking some assumptions if you do that with PPO (would be ok with an off-policy algorithm like SAC).

> Is there a way to specify the action before going into the step function during the learning?

For custom needs like yours, best is to either fork SB3 or redefine PPO/the parts that you want to change.

**Comment by phcha57** [comment]
Thank you for the answer.
I did as you suggested and redefine some part of the code.
I believe you are right and that doing so break some assumptions on PPO. PPO does not seem to be working properly even though I am confident that I nailed the log probably calculation. I have not tested it fully but the learning is slower and it seems to get stuck with lower rewards.
I also modify the code for SAC like you suggested. In the case of SAC it seems to be working just fine. I have not tested it fully but the initial learning is faster and the rewards converge to something similar. Since the initial reason for trying this approach was to achieve faster learning, I am kind of satisfied.

If someone wishes to reproduce this approach, here is what you need to know (I am using version 2.1.0 of stable-baselines3):
Inside stable_baselines3/sac you will find sac.py.
Inside the class SAC, you will find the learn function.
The learn function is inherited from OffPolicyAlgorithm.
off_policy_algorithm.py can be found under stable_baselines3/common.
The learn function call collect_rollouts.
collect_rollouts call _sample_action.
Inside _sample_action, an action is chosen randomly or according to policy.
This is where you want to specify your action, probably before the rescaling happen.
