### ISSUE TITLE
[Question] How to set env.reset() interval in model.learn() function of PPO2?

### ISSUE THREAD

**Issue by yeedonghyun** [DLR-RM/stable-baselines3#1819]
### ❓ Question

hello,

I used a PPO model and called the model.learn() function.
But the training result is not good and I want to set the interval of env.reset().
How can I set it?

Or where can I check the interval of env.reset()?

simple my code 
`env = make_vec_envs(env_name, representation, log_dir, n_cpu, **kwargs)`
`    model = PPO2(policy, env, verbose=1, tensorboard_log="./runs")`
`    model.learn(total_timesteps=int(steps), tb_log_name=exp_name, callback=callback)`

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

**Comment by araffin** [comment]
PPO2 is from SB2, not SB3...
And everything that has to do with `reset()` is related to the environment (and timelimit), not the algorithm.
