### ISSUE TITLE
Better advantage estimation for OnPolicyAlgorithm

### ISSUE THREAD

**Issue by Wovchena** [DLR-RM/stable-baselines3#183]
Hi.
Your reimplementation helped me to figure out how a2c works. But while I was studying it, I found some places which can be improved in the reimplementation.
1.	There is a bug in https://github.com/DLR-RM/stable-baselines3/blob/a1e055695c3638f9f15de0cb805b8fcbb5c02764/stable_baselines3/common/on_policy_algorithm.py#L182 `compute_returns_and_advantage()` should take values which correspond to the very last observations as it takes the last `dones`. But here the function takes values corresponding to previous observations. It should take values corresponding to `new_obs`, which you need to infer first.
2.	https://github.com/DLR-RM/stable-baselines3/blob/a1e055695c3638f9f15de0cb805b8fcbb5c02764/stable_baselines3/common/buffers.py#L322 The `if` handles only first iteration of the loop. It could be just moved out of the loop.

**Comment by Miffyli** [comment]
1) Very nice catch! These off-by-one errors seem to be very hard to iron out, even when comparing learning curves and all... 
2) Good point. If the first iteration can be moved outside without too much edge-case checking and other mess I think this could be done. Sadly in Python this might not offer a big performance bonus, but if clarity of the code remains I agree this could be done.

A PR to fix both would be welcome :)
