### ISSUE TITLE
How to access self.locals['dones'] via _on_step callback in ARS algo

### ISSUE THREAD

**Issue by pavelxx1** [DLR-RM/stable-baselines3#1838]
### ❓ Question

Can't access `self.locals['dones']` via `_on_step ` callback  in **`ARS`** algo, key `'dones'` not found in dict
How to solve issue?
Thx

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [ ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
this is more a question for SB3 contrib.
ARS is special as it is a population based algorithm where candidates can be evaluated asynchronously (for maximum speed).
You would need to fork SB3 contrib and modify https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/8dca5d5e22315fb01c11ed24ef6a4546aa4c508e/sb3_contrib/ars/ars.py#L165

**Comment by pavelxx1** [comment]
thx
