### ISSUE TITLE
When using custom environments in a loop that trains multiple models, CUDA VRAM is never deallocated when iteration is done.

### ISSUE THREAD

**Issue by john-woolley** [DLR-RM/stable-baselines3#1840]
### 🐛 Bug

SB3 models never deallocate the VRAM they use in a process even if they are deleted.  This can lead to hardware issues including full system crashes that remain unbootable until the VRAM resets due to power loss (~30 seconds of unbootability).

### Code example

```python
import gymnasium as gym
import numpy as np
from gymnasium import spaces

from stable_baselines3 import A2C
from stable_baselines3.common.env_checker import check_env


class CustomEnv(gym.Env):

    def __init__(self):
        super().__init__()
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(50, 800))
        self.action_space = spaces.Box(low=-1, high=1, shape=(50,))


    def reset(self, seed=None, options=None):
        return self.observation_space.sample(), {}


    def step(self, action):
        obs = self.observation_space.sample()
        reward = 1.0
        terminated = False
        truncated = False
        info = {}
        return obs, reward, terminated, truncated, info


env = CustomEnv()
check_env(env)

for i in range(1000):
    model = A2C("MlpPolicy", env, verbose=1).learn(1000)
    model.save("a2c_trader")
    del model
```

### Relevant log output / Error message

```shell
OutOfMemoryError
"CUDA out of memory. Tried to allocate 122.00 MiB (GPU 0; 10.76 GiB total capacity; 9.51 GiB already allocated; 65.56 MiB free; 9.86 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

Or alternatively it will sometimes just silently kill the whole system on trying to save the trained model.
```

### System Info
```
Threadripper 3970 CPU
RTX 2080 TI GPU
Fedora 34
Torch 1.13
```
### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
this sounds more like a pytorch issue, no?

**Comment by john-woolley** [comment]
My understanding was that you can `del` the tensors, etc. when the work is done, but I'm not sure where to add them to the code within SB3 that uses torch.  If I'm mistaken on this, my apologies.

**Comment by araffin** [comment]
> My understanding was that you can del the tensors, etc. when the work is done, but I'm not sure where to add them to the code within SB3 that uses torch. If I'm mistaken on this, my apologies.

`model.policy` is a `torch.nn.Module`, I would assume `del model` triggers `del model.policy`, you might also try to trigger the garbage collector manually `gc.collect()` and `torch.cuda.empty_cache()`.

See https://stackoverflow.com/questions/70508960/how-to-free-gpu-memory-in-pytorch
