### ISSUE TITLE
[Question] Loading a trained PPO model in PyTorch without any SB3 dependencies

### ISSUE THREAD

**Issue by SarvagyaVaish** [DLR-RM/stable-baselines3#1844]
I created a custom gym environment and successfully trained a model using PPO. I then saved it using the model.save() method and got back a zip file (as per the documentation [here](https://stable-baselines3.readthedocs.io/en/master/guide/save_format.html)). All good so far! 

I now want to do inference using my trained model on a different device (in fact it's a jetson nano). How do I load and create a pytorch model from this zip file? I cannot install SB3 on this machine.

I have tried looking for something that does this but am worried my approach isn't correct. Any recommendations for an RL noobie? 

Checklist
✅ I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- There are a few related issues in the old stable baselines repo, but the examples there are not working out for me.

✅ I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) *
- Yes. Both the save/load and the exporting models one. Unable to find stuff around PyTorch. 
- Happy to update the docs as per the conclusion here. 

✅ Here's a [Google Colab](https://colab.research.google.com/drive/1SFrVg6o-Ts0jL528dfraO9IAli87ABSh#scrollTo=mRG4Igjhqmoi)

**Comment by SarvagyaVaish** [comment]
Hi @araffin !
Could you help me out, please? Unable to find the answer in the documentation. Most examples online require creating a python class that matches the architecture of the neural network being used in PPO. How do I access that?

**Comment by SarvagyaVaish** [comment]
Here are some of the links I have read through.
- https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/sb3/advanced_saving_loading.ipynb
- https://stable-baselines3.readthedocs.io/en/master/guide/export.html

I am stuck on how to save the SB3 model, and load it into PyTorch.
- https://pytorch.org/tutorials/beginner/saving_loading_models.html

**Comment by araffin** [comment]
> https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/sb3/advanced_saving_loading.ipynb

```python
policy = model.policy
policy.save("sac_policy_pendulum")
```
is what you need, `policy` is a `torch.nn.Module` object, independent from SB3, so you can use `th.save()` with it, and then use python or c++ with pytorch to load it.

> https://stable-baselines3.readthedocs.io/en/master/guide/export.html

if you look at "Export to ONNX", it is independent from SB3 and PyTorch, no? you only need `onnxruntime`.

> I cannot install SB3 on this machine.

if it's a jetson nano, you can install torch, which means SB3 on that machine too. You should be able to find pre-compiled wheel for this architecture online (for pytorch, SB3 is python only).

**Comment by SarvagyaVaish** [comment]
Thank you for the code snippet.

> so you can use th.save() with it, and then use python or c++ with pytorch to load it.

When calling `.save` on the policy as you described, it saves the `ActorCriticPolicy` object in my case (since I'm using PPO).  Here's the code: 

```
# Train
model = PPO("MlpPolicy", env, verbose=1, n_steps=64)
model.learn(total_timesteps=3000)

# Save the policy
policy = model.policy
policy.save("my_policy")
```

The issue I'm running into is that based on these [PyTorch docs](https://pytorch.org/tutorials/beginner/saving_loading_models.html), it seems like I need to create a class based on `torch.nn.Module` to load the saved model. Here's the relevant snippet: 

```
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
model.eval()
```

I don't know enough about the internals of PPO to recreate the class that represents the architecture PPO is using internally. Is there a specific class from the SB3 repo I should copy and paste into my model loading code? Perhaps the ActorCriticPolicy class, but it seems rather involved to strip out all the non-SB3 specific stuff. I also found [this article](https://wandb.ai/wandb/common-ml-errors/reports/How-to-Save-and-Load-Models-in-PyTorch--VmlldzozMjg0MTE) talking about loading PyTorch models, and it seems to confirm my understanding. 

I am clearly missing something. Would it help if I created a google colab?

----

> if it's a jetson nano, you can install torch, which means SB3 on that machine too. 

There is a version compatibility issue. SB3 requires a much later version of PyTorch than the Jetson Nano supports. 

- Stable-Baselines3 (v1.4.0) requires python 3.7+ and PyTorch >= 1.8.1. [[reference](https://stable-baselines3.readthedocs.io/en/v1.4.0/guide/install.html)]
- Stable-Baselines3 (v2.1.2) requires python 3.8+ and PyTorch >= 1.13 [[reference](https://stable-baselines3.readthedocs.io/en/v2.2.1/guide/install.html)]

If I had the Jetson Nano Orin, it wouldn't have been an issue. I am stuck on Python 3.6 and Ubuntu 18.04. I could [build PyTorch from source](https://i7y.org/en/pytorch-build-on-jetson-nano/), but keeping that in my back pocket as I'm sure that'll come with a whole lot of its own issues. 

----

> if you look at "Export to ONNX", it is independent from SB3 and PyTorch

True. The current minimum python version of [onnxruntime](https://pypi.org/project/onnxruntime/) is 3.8. So I can try running it in a virtual environment. Will try that out and report back.

**Comment by SarvagyaVaish** [comment]
Here's a [Google Colab](https://colab.research.google.com/drive/1SFrVg6o-Ts0jL528dfraO9IAli87ABSh#scrollTo=mRG4Igjhqmoi) to iterate over the solution.

I was able to save the `model.policy` using `torch.save()`, however, the inference output is not the same. I'm wondering if using the `load_state_dict` approach will have better luck. But, and this is the same step I was stuck on earlier, I can't do that without creating a class that represents the architecture and has the same layer names as those used by SB3. 

![image](https://github.com/DLR-RM/stable-baselines3/assets/1449905/4d43550c-d857-4bec-a7db-8cadab5ae135)

**Comment by SarvagyaVaish** [comment]
Not really "completed" unfortunately. If you're marking it as is since this ticket is too old, I understand.
Do you have any suggestions for what I'm doing wrong based on the collab I posted above?

**Comment by darkopetrovic** [comment]
Thanks for your code, this is exactly what I was looking for. It is not easy to find the right solution when we do it for the first time. 

You are doing right actually. But don't forget to set the `deterministic` parameter to true to compare the predictions.

This is what I did:

```
import torch
preds1, _ = model_ppo_sb3.predict(observations, deterministic=True)
torch.save(unwrapped.model.policy, "policy.pth")
model = torch.load("policy.pth")
preds2, _ = model.predict(observations, deterministic=True)
assert np.array_equal(preds1, preds2)
```
