### ISSUE TITLE
[Question] Continuous action space must have a finite lower and upper bound

### ISSUE THREAD

**Issue by onnoeberhard** [DLR-RM/stable-baselines3#1850]
### ❓ Question

I want to use soft actor-critic in an environment with continuous state and action spaces. The environment is implemented in a `gym.Env` class with state and action spaces of the type `gym.spaces.Box(-np.inf, np.inf, shape)`. When trying to train a soft actor-critic (`sb3.SAC`), I get the following error: `AssertionError: Continuous action space must have a finite lower and upper bound`. My question is: why? Neither the soft actor-critic algorithm nor the gym interface require bounded action spaces. Indeed, I would think unbounded action spaces are easier to deal with, as there is no need for clamping or squishing. Am I missing something?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/897

**Comment by onnoeberhard** [comment]
Thanks. I couldn't find it in the issues (I searched for the error message).
