### ISSUE TITLE
[Bug]: Selecting from self.observations when the buffer is full for batch_inds containing idx=self.pos-1 results retrieving an incorrect next_obs in ReplayBuffer

### ISSUE THREAD

**Issue by bean217** [DLR-RM/stable-baselines3#1853]
### 🐛 Bug

I'm currently writing a modified replay buffer to be able to grab the N most recently added transitions and noticed that in `_get_samples` when `self.optimize_memory_usage` is `True` and `self.handle_timeout_termination` is `False`, if the buffer is full (i.e. `self.full == True`) and an index in `batch_inds == self.pos-1` then it will grab an incorrect `next_obs`. This is inherently because the observation stored at `self.pos` is not a transition which followed the observation stored at `self.pos-1`, but is instead a very old transition.

I don't have any logs to provide. This was just an issue that I noticed while working through the code. #934 also references this issue, but only with respect to `self.handle_timeout_termination` also being `True`.

### Code Area

In `common.buffers.ReplayBuffer`:
```python
def _get_samples(self, batch_inds: np.ndarray, env: Optional[VecNormalize] = None) -> ReplayBufferSamples:
    # Sample randomly the env idx
    env_indices = np.random.randint(0, high=self.n_envs, size=(len(batch_inds),))

    if self.optimize_memory_usage:
        next_obs = self._normalize_obs(self.observations[(batch_inds + 1) % self.buffer_size, env_indices, :], env)
        ...
```

### Example
Suppose `self.buffer_size = 10` but `12` transitions have been added.
Then `self.pos = 2`, `self.full = True`, and if `batch_inds` contains index `1` then it will get the observation stored at `self.observations[2]` as the `next_obs`, which is not it's true `next_obs`.

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
I understand your concern but looking at the code, I think it is ok.

Let's say `buffer_size=5`, `full=True` and `pos=1`.

When we store a new transition, we store the obs at `index=pos=1` 
https://github.com/DLR-RM/stable-baselines3/blob/56f20e40a2206bbb16501a0f600e29ce1b112ef1/stable_baselines3/common/buffers.py#L265
and the next obs at `index=pos+1=2`:
https://github.com/DLR-RM/stable-baselines3/blob/56f20e40a2206bbb16501a0f600e29ce1b112ef1/stable_baselines3/common/buffers.py#L267-L268

The pos is then incremented to `pos + 1 = 2`:
https://github.com/DLR-RM/stable-baselines3/blob/56f20e40a2206bbb16501a0f600e29ce1b112ef1/stable_baselines3/common/buffers.py#L279

In that case, when sample, we avoid sampling `index=2`, but if we sample `index=1`, `next_obs`  at `index=2` is valid, no?
https://github.com/DLR-RM/stable-baselines3/blob/56f20e40a2206bbb16501a0f600e29ce1b112ef1/stable_baselines3/common/buffers.py#L298-L301



As a side note, this should not be a big issue if the replay buffer size is large enough.

**Comment by bean217** [comment]
Oh I see where I was mistaken.
I am just noticing that `start=1` in `np.random.randing(1, self.buffer_size, ...` to avoid sampling `index=2`.
I apologize for submitting an invalid bug. Thank you for clearing my confusion.
