### ISSUE TITLE
[feature request] Support Tensorboard video logging (convenience)

### ISSUE THREAD

**Issue by SwamyDev** [DLR-RM/stable-baselines3#186]
When investigating RL algorithms I've found it quite useful to report videos of a trajectory to Tensorboard, to directly relate it to other performance measures and look at the agent at different stages. 

The implementation would be quite simple I think and if you decide this to be a useful feature I'd be happy to implement it. As a matter of fact I've already done so in my own fork of this repo. Here is how I envisioned its usage:

```python
def render_trajectory(env, model):
    obs = env.reset()
    rewards = []
    done = False
    screens = []
    while not done:
        actions, _ = model.predict(obs, deterministic=True)
        obs, _, done, _ = env.step(actions)
        screen = env.render(mode='rgb_array')
        screens.append(screen.transpose(2, 0, 1))

    return Video(th.ByteTensor([screens]), fps=40)

class ReportTrajectoryCallback(BaseCallback):
    def __init__(self, eval_env, check_freq):
        super().__init__()
        self._eval_env = eval_env
        self._check_freq = check_freq

    def _on_step(self):
        if self.n_calls % self._check_freq == 0:
            video = render_trajectory(self._eval_env, self.model)
            self.logger.record("trajectory/video", video)
        return True

env = gym.make('CartPole-v1')
model = A2C('MlpPolicy', env)
model.learn(total_timesteps=int(1e4), callback=ReportTrajectoryCallback(env, 1000))
```

I'd suggest introducing a `Video` object and a simple extension of the logger to record the video. The `TensorBoardOutputFormat` would simply check for a video object and forward it to the `SummaryWriter`. All other `KVWriter` classes would just ignore it. As mentioned I've done this already for me self. Here is the relevant commit:
https://github.com/SwamyDev/stable-baselines3/commit/d6b15416000011a5aeddd4af1bfb9f9a2d79d22f

Of course I'm open to any different approaches. For instance checking the type directly in the Formater classes is not good object oriented style and maybe an explicit video logging function would be better. However, it is relatively simple and get's the job done.

What do you think? Would this is be a small but useful contribution?

**Comment by Miffyli** [comment]
Hey, I agree this kind of things are useful. Gym offers the video recorder wrapper but that only works with files, and indeed I see the usefulness in the tensorboard videos. This would be a perfect contribution to the sb3-contrib repository we are cooking (should be out soon™) which is designed for all kinds of useful utilities like this :). I will poke here once the repo is out.

**Comment by araffin** [comment]
In fact, part of it should be included inside SB3 repo, because we need to change the tensorboard writer.
But I agree that the callback and the helper should go in the contrib folder.

And there is a simpler way to use it: `record("trajectory/video", video, exclude=("json", "stdout", "log", "csv"))`

**Comment by SwamyDev** [comment]
Hi there, glad you think the idea useful :). 

I agree using the exclude explicitly would simplify the implementation. The reason I opted for extending all `*Format` classes to handle the `Video` object is, that I wanted to take the burden of deciding which format is invalid the user. I was worried that it might result in hard to understand error messages or strange log outputs when one tries to log a video to a format where it doesn't make sense . It's a trade-off between complexity and usability.

On another note, while investigating the simpler way you've suggested I've noticed that the json exclude doesn't seem to work, as it is still trying to log the key to the json file. When looking at the code of `JSONOutputFormat` it seems like it's just not converting array like objects to lists when json is part of the exclude list, but otherwise dumping the whole `key_values` dictionary to json. Also `CSVOutputFormat` seems to completely ignore the `key_excluded` parameter. 

If this is indeed unintended behavior I'd be happy to file a bug, and also provide a fix with regression tests :)

**Comment by araffin** [comment]
>On another note, while investigating the simpler way you've suggested I've noticed that the json exclude doesn't seem to work, as it is still trying to log the key to the json file

>If this is indeed unintended behavior I'd be happy to file a bug, and also provide a fix with regression tests :)

oh thanks, looks like a bug, please do ;)

**Comment by araffin** [comment]
Last thing, you can use `evaluate_policy` and the `callback` attribute of it instead of `render_trajectory` ;)

**Comment by SwamyDev** [comment]
Ah thanks for the suggestion that makes my code a lot simpler :)

Ok, I'll file a proper bug report and everything for the other issue

**Comment by SwamyDev** [comment]
With that issue out of the way, the video implementation becomes trivial. Now its just the introduction of the `Video` class and an extra type check in `TensorBoardOutputFormat::write`.

 However, I'd suggest to handle the Video class in the other `*Format` classes as well and raise a an error when `record("trajectory/video", video, ...)` is called without the proper excludes, explaining that videos are not supported for the selected logging format. What do you think?

Also should I create I PR for this as well or do you want to wait for the `sb3-contrib` repository?

**Comment by araffin** [comment]
>Also should I create I PR for this as well

yes, please do, as it need to be done anyway.
we are currently beta-testing the contrib repo ;) (should be out soon)

**Comment by araffin** [comment]
The contrib repo is here ;) https://github.com/Stable-Baselines-Team/stable-baselines3-contrib

(we don't advertise it yet as we want to check the process and not get too many request for now)

**Comment by SwamyDev** [comment]
Awesome, thanks for the info! I'll have a look soon :)
