### ISSUE TITLE
[Question] Can the parameters of a custom feature extractor be trained?

### ISSUE THREAD

**Issue by d505** [DLR-RM/stable-baselines3#1860]
### ❓ Question

I would like to use cnn or lstm as a feature extractor. In that case, will the parameters of the feature extractor be learned without doing anything special? I asked this question because it did not seem to do so when I tried to run it.

I referred to the following
https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html
### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [x] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
>  I asked this question because it did not seem to do so when I tried to run it.

yes, this should be the default.
You can directly check if the parameters are updated using something similar to https://github.com/DLR-RM/stable-baselines3/blob/f375cc393938a6b4e4dc0fb1de82b4afca37c1bd/tests/test_cnn.py#L128

**Comment by d505** [comment]
Thank you !
I checked by inserting the following before and after model.learn(total_timesteps=n)
```
for i in model.policy.features_extractor.parameters():
        print(i)
```
I could see that the parameter values have changed slightly.
