### ISSUE TITLE
PPO model sizes and pytorch_variables.pth question

### ISSUE THREAD

**Issue by Dual111** [DLR-RM/stable-baselines3#1862]
### ❓ Question

Hey, 
**Project:**
I have program that uses SB3 Pytorch PPO to learn to play league of legends. It seems like it is working as intended, it loads the existing model, saves it (including the optimizer state), after loading the model again and playing, it completes the n_steps it shows how many n_updates it has completed in total (meaning it does save the optimizer state and loads it correctly).

**So the question is** 
My PPO model size doesn't change in size. It stays at 2 863 992 kb size even after going through 10 hours of training. Is this normal? Policy.optimizer.pth stays at 1 901 217kb, policy.pth stays at 950 611kb AND pytorch_variables.pth is always only 1 kb?

**Should the pytorch_variables.pth change in size? Should the other .pth files change in size?**
It doesn't matter if the model has gone through 1 minute of training or 10 hours of training, it has same size. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
why should it change in size?

**Comment by Dual111** [comment]
> Hello, why should it change in size?

I don't know, Its my first time training an PPO model so I'm just asking if it should change. I asked ChatGPT the same question and he said there might be something wrong if the .pth files don't change in size? And seeing the other 2 .pth files have bigger size it made me think maybe there is something wrong with the pytorch_variables.pth since its only 1 kb but I assume its normal then?
