### ISSUE TITLE
[Bug]: PPO handle TimeLimit.truncated incorrectly

### ISSUE THREAD

**Issue by yinzikang** [DLR-RM/stable-baselines3#1864]
### 🐛 Bug

I am trying to design my PPO based on the PPO from sb3. 
As for the GAE part, in my opinion, if the task is done with failure after action $a_t$, such as crash, the TD target should be $r_t$.
If the task is done with `TimeLimit.truncated`, the TD target should be $r_t + \gamma * V(s_{t+1})$, just the same as mentioned in issue 633 https://github.com/DLR-RM/stable-baselines3/issues/633.

So issue 633 suggests a reward augment $\gamma * V(s_{t+1})$ for a truncated situation, and do nothing for the failed situation. However, the code from 210-221 lines in `/stable-baselines3/tree/master/stable_baselines3/common/on_policy_algorithm.py` seems do the opposite.

```
  # Handle timeout by bootstraping with value function
  # see GitHub issue #633
  for idx, done in enumerate(dones):
      if (
          done
          and infos[idx].get("terminal_observation") is not None
          and infos[idx].get("TimeLimit.truncated", False)
      ):
          terminal_obs = self.policy.obs_to_tensor(infos[idx]["terminal_observation"])[0]
          with th.no_grad():
              terminal_value = self.policy.predict_values(terminal_obs)[0]  # type: ignore[arg-type]
          rewards[idx] += self.gamma * terminal_value
```
To be precise, the failed situations are processed, instead of the truncated situations. Should the condition be modified to the following?
```
and infos[idx].get("TimeLimit.truncated", True)
```

### To Reproduce

```python
from stable_baselines3 import ...

```

### System Info

- OS: Linux-5.15.0-97-generic-x86_64-with-glibc2.17 # 107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024
- Python: 3.8.18
- Stable-Baselines3: 2.2.1
- PyTorch: 2.2.1+cu121
- GPU Enabled: True
- Numpy: 1.24.4
- Cloudpickle: 3.0.0
- Gymnasium: 0.29.1
- OpenAI Gym: 0.25.1

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
just to be sure, the `get()` syntax here is for default value, in case the key `"TimeLimit.truncated"` is not present, we consider it to be a real termination (hence default to `False`).

```python
demo = {}
assert demo.get("hello", False) == False # default value, key doesn't exist
demo["hello"] = True
assert demo.get("hello", False) == True # the key "hello" exists, we use it
```

**Comment by yinzikang** [comment]
oh, I see, I misunderstood the code. Thank you for your help, haha.
