### ISSUE TITLE
[Question] How can I wrap a non-image observation trained model via an image observation wrapper?

### ISSUE THREAD

**Issue by zichunxx** [DLR-RM/stable-baselines3#1871]
### ❓ Question

Hi!

I have a custom-trained model with non-image observation and want to collect some image observations with the trained model. 

Below is the code of my brief implementation:

```py

import gymnasium as gym
from stable_baselines3 import SAC, DDPG, PPO
from gymnasium.experimental.wrappers import PixelObservationV0

env = gym.make("CustomEnv", render_mode="rgb_array")

model = SAC.load("trained_model", env=env)

vec_env = model.get_env()

vec_env = PixelObservationV0(vec_env)

obs = vec_env.reset()

for i in range(1000):
    action, _states = model.predict(obs, deterministic=True)

    obs, reward, done, info = vec_env.step(action)

    # print(obs.shape)

    if done:
         obs = vec_env.reset()

vec_env.close()
```

But I got the TypeError like this

```
Traceback (most recent call last):
  File "/home/xzc/mambaforge/envs/sb-zoo/lib/python3.9/site-packages/gymnasium/core.py", line 515, in reset
    obs, info = self.env.reset(seed=seed, options=options)
TypeError: reset() got an unexpected keyword argument 'seed'
```

I've checked the documentation and issue list, but haven't found any examples of pixel wrappers for trained environments. Or maybe I missed something.

Many thanks for considering my request.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
you are mixing `gym.Env` (the wrapper you used) and `VecEnv` (please have a look at our docs for the main differences).
I'm also not sure how you plan to predict on images with a model that was trained on non-image input.

**Comment by araffin** [comment]
> vec_env.render() seems to solve my problem without any wrapper, right?

it should, as long as you use only one env.
You might need a bit more if you use multiple envs (you need to check if the images are concatenated or not).
