### ISSUE TITLE
[Question] Training PPO model with single step episodes

### ISSUE THREAD

**Issue by oshadajay** [DLR-RM/stable-baselines3#1874]
### ❓ Question

Hi, I have been using Stable Baselines 3 with a custom environment for a RL application. However, all of my episodes have a fixed length of one and the purpose of the agent is to decide the optimal action for the current observations. I have 3 discreet actions and 1 observation. I'll clarify using a code segment.

```
if action == 0:
    self.reward = 0
elif action == 1:
    self.slots += 1
    self.reward = -2000*self.slots
    self.reward += 5000
elif action == 2 and self.slots != 0:
    self.slots -= 1
    self.reward = 2000*self.slots
    self.reward += -5000
```

So slots is my observation which can vary from 0 to 5. The agent can take actions 0, 1 and 2. At a lower number of slots, the reward is high for action 1. At a higher number of slots, the reward is high for action 2. Though this is a very simple scenario, the PPO model with Mlppolicy does not seem to learn this behavior. I assume this could have something to do with each episode having a fixed length of 1. Is there a way to fix this or is PPO model not suitable for an application like this? I am a beginner for RL model training and your help is highly appreciated. Thank you.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
I don't understand how your slot can vary from 0 to 5 knowing that you only increment/decrement it by 1 and that the episode length is 1. Or is it randomly initialized on this range?

**Comment by oshadajay** [comment]
It is randomly initialized on this range at reset. And the done variable is set to True after running one action.

**Comment by qgallouedec** [comment]
After a quick experiment, it seems to work very well for me. If the problem persists, please post an MRE. 

```python
import gymnasium as gym
import numpy as np
from gymnasium import spaces
from stable_baselines3 import PPO


class CustomEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.action_space = spaces.Discrete(3)
        self.observation_space = spaces.Discrete(6)

    def step(self, action):
        if action == 0:
            reward = 0
        elif action == 1:
            reward = -2 * (self.x + 1) + 5
        elif action == 2:
            reward = 2 * (self.x - 1) - 5

        return self.x, reward, True, False, {}

    def reset(self, seed=None, options=None):
        self.x = np.random.randint(0, 5)
        return self.x, {}


model = PPO("MlpPolicy", CustomEnv(), n_steps=10, verbose=1).learn(1000, log_interval=1)
```

**Comment by oshadajay** [comment]
Thank you so much for your help. The code you have posted works well and I think the issue I am having is with regard to specifying the observation space. The problem I have posted above is a simplified version and in my actual problem there are 2 observations. One is the slots which can vary from 0 to 5. There is another variable which could vary from 0 to 1000. What I did was having the second one constant and trained with only varying the first one and I couldn't get the expected results. I have defined the observation space as follows.

```
self.observation_space = spaces.Box(low=0, high=1000, shape=(2,), dtype=np.float32)
```

Is the above definition wrong? What I want is something like below.

```
self.observation_space = spaces.Tuple([spaces.Box(low=0, high=1000), spaces.Discrete(6)])
```

Yet I observed that dict and tuple spaces are not supported by the algorithms. Is there a way to reshape the Tuple into a box? Appreciate your support in this a lot. Thank you.

**Comment by araffin** [comment]
https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment

"When applying RL to a custom problem, you should always normalize the input to the agent (e.g. using VecNormalize for PPO/A2C) "

**Comment by oshadajay** [comment]
Hi, thank you for the information. I am now trying to use VecNormalize for my environment. My code for training and predicting look like this and the predicted action is always 1 regardless of the observations. Am I doing something wrong? Thanks in advance.

```
import gymnasium as gym
import numpy as np
from gymnasium import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecNormalize, DummyVecEnv
import time

class CustomEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.action_space = spaces.Discrete(3)
        self.observation_space = spaces.Box(low=0, high=100, shape=(2,))

    def step(self, action):
        if action == 0:
            reward = 0
        elif action == 1:
            reward = -20 * (self.x + 1) + 5 + self.y * 1
        elif action == 2:
            reward = 20 * (self.x - 1) - 5 - self.y * 1

        observation = np.array([self.x, self.y])

        return observation, reward, True, False, {}

    def reset(self, seed=None, options=None):
        self.x = np.random.randint(0, 5)
        self.y = np.random.randint(0, 100)
        observation = np.array([self.x, self.y])
        return observation, {}

models_dir = f"models/{int(time.time())}/"

env = DummyVecEnv([lambda : CustomEnv()])
env = VecNormalize(env, norm_obs=True, norm_reward=True)

model = PPO("MlpPolicy", env, n_steps=10, verbose=1).learn(1000, log_interval=1)
model.save(f"{models_dir}/{1000}")
env.save("saved_env.pkl")

count_dict = {"0":0, "1":0, "2":0}
for j in [10, 20, 30, 40, 50, 60, 70, 80]:
    for k in range(5):
        print(j)
        print(k)
        count_dict = {"0":0, "1":0, "2":0}
        for i in range(100):
            observation = np.array([k, j])
            action, _states = model.predict(observation)
            if action == 0:
                count_dict["0"]+=1
            if action == 1:
                count_dict["1"]+=1
            if action == 2:
                count_dict["2"]+=1                
        print(count_dict)
```

**Comment by qgallouedec** [comment]
Hard to say. Unfortunately we don't really have time for tech support. You'll have better luck if you ask your question on the Discord. Also, make sure your env passes the env checker.
Don't hesitate to post the answer here to help others.
