### ISSUE TITLE
[Feature Request] Resume trained model with set_parameters without reset_num_timesteps

### ISSUE THREAD

**Issue by tanielsfranklin** [DLR-RM/stable-baselines3#1877]
### 🚀 Feature

Resume trained model with set_parameters without reset_num_timesteps

### Motivation

I think this is useful when training using rounds. This feature can keep the record on the tensorboard, even when changing some training hyperparameters

### Pitch

Train some rounds and tensorboard logging remain continuous even with hyperparameters changing

### Alternatives

When I use de the load() method works well, but don't allow changes in batch size and n_steps 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
> When I use de the load() method works well, but don't allow changes in batch size and n_steps

```python
from stable_baselines3 import PPO

PPO("MlpPolicy", "CartPole-v1").save("ppo_cartpole")

model = PPO.load("ppo_cartpole", n_steps=64, batch_size=32)

```

?

**Comment by tanielsfranklin** [comment]
> > When I use de the load() method works well, but don't allow changes in batch size and n_steps
> 
> ```python
> from stable_baselines3 import PPO
> 
> PPO("MlpPolicy", "CartPole-v1").save("ppo_cartpole")
> 
> model = PPO.load("ppo_cartpole", n_steps=64, batch_size=32)
> ```
> 
> ?

Load method does not accept this parameters.
classmethod load(path, env=None, device='auto', custom_objects=None, print_system_info=False, force_reset=True, **kwargs)

**Comment by araffin** [comment]
> Load method does not accept these parameters.

yet the provided code works...

you should have a look at `**kwargs` and what that means in python.

**Comment by tanielsfranklin** [comment]
> > Load method does not accept these parameters.
> 
> yet the provided code works...
> 
> you should have a look at `**kwargs` and what that means in python.

Oh, it's my fault. I was thinking on this right now. It will be very useful, thanks.
