### ISSUE TITLE
How does stable-baselines work with a multi-agent pettingzoo environment?

### ISSUE THREAD

**Issue by AnastasiaPsarou** [DLR-RM/stable-baselines3#1878]
### ❓ Question

I have created a ParallelEnv Pettingzoo custom environment with 600 agents, according to this [tutorial](https://pettingzoo.farama.org/tutorials/sb3/waterworld/). The env is created based on this [page](https://pettingzoo.farama.org/content/environment_creation/) ParallelEnv tutorial. I see that 600 different environments are created (one for each agent) and they are somehow concatenated in a vectorized environment. From what I see there is only one neural network created (or two or three depending on the rl algorithm) but I would expect 600 different NNs, as each agent, should supposedly have its own knowledge. But I see there is only one neural network created and its output looks like being addressed to one agent. Can someone explain to me how the policy corresponds to each agent's actions and how this thing works? Thanks in advance!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
this issue belongs to the Pettingzoo repo.
