### ISSUE TITLE
[Question] Why are env_kwargs ignored in make_vec_env?

### ISSUE THREAD

**Issue by ManifoldFR** [DLR-RM/stable-baselines3#188]
**Describe the bug**

The `common.cmd_util.make_vec_env` function ignores the `env_kwargs` argument when an env ID is supplied instead of a class constructor:
https://github.com/DLR-RM/stable-baselines3/blob/2599f04940f14436290273caa2df9366a54b375c/stable_baselines3/common/cmd_util.py#L47-L50

I don't see why this is necessary? The `gym.make` function can have optional kwargs passed as `gym.make(env_id, **env_kwargs)`.

**Comment by araffin** [comment]
Hello,
That's a good point (in fact, `env_kwargs` are supported in the rl zoo).
The main reason is that `gym.make()` did not support keyword arguments until recently.
I would appreciate a PR that solves this issue ;)

**Comment by ManifoldFR** [comment]
Alright, I address this in PR #189.
