### ISSUE TITLE
[Question] Saving PPO rollout buffer on GPU

### ISSUE THREAD

**Issue by Ahmed-Radwan094** [DLR-RM/stable-baselines3#1891]
### ❓ Question

I am using PPO algorithm, and it seems that the rollout buffer is saved to the CPU, which causes high memory consumption on my device. Is it possible to move the rollout buffer completely to the GPU?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Is it possible to move the rollout buffer completely to the GPU?

By saving, you mean that the data stored in on the cpu?
currently not, you would need to write a custom buffer (and probably update SB3, gym API assumes numpy arrays), you can also have a look at related issues on SB3 repo (https://github.com/DLR-RM/stable-baselines3/issues/314 and all linked issues).

**Comment by Ahmed-Radwan094** [comment]
Thank you for the fast response. Yes, I meant storing.
I think I will work on upgrading to support tensors.
