### ISSUE TITLE
[Bug]: Potential Bug in PPO? Clarification requested

### ISSUE THREAD

**Issue by azrael417** [DLR-RM/stable-baselines3#1894]
### 🐛 Bug

Hello all,

I am sorry in case this is a false alarm, but should the th.min in

https://github.com/DLR-RM/stable-baselines3/blob/5623d98f9d6bcfd2ab450e850c3f7b090aef5642/stable_baselines3/ppo/ppo.py#L231

not be a th.minimum ? th.min behaves differently from th.minimum. I was reimplementing your implementation of the PPO algo in libtorch and the compiler barfed at that point and I think the compiler is right.

Let me know what you think

Best regards
Thorsten

### To Reproduce

```python
from stable_baselines3 import ...

```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
>  th.min behaves differently from th.minimum.

are you sure?

```python
import torch as th

a = th.ones(2, 4)
b = th.zeros(2, 4)
b[0, 2] = 3

assert th.allclose(th.min(a, b), th.minimum(a,b))

```

**Comment by azrael417** [comment]
You are right, in the case where you give it two tensors it seems to be the same. That is good to know. You can close this bug.
