### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by Hamza-101** [DLR-RM/stable-baselines3#1905]
### ❓ Question

# Scaling my environment

I have a Multi-Agent RL Environment trained using 3 agents. My observation and action space are dynamic seemingly.
I have trained and tested it using 3 Boids. However I want to have _n_ Boids do the training and then have > _n_ Boids for testing my model.

```
min_action = np.array([-5, -5] * len(self.agents), dtype=np.float32)
max_action = np.array([5, 5] * len(self.agents), dtype=np.float32) 

self.action_space = spaces.Box(low=min_action, high=max_action, dtype=np.float32)

min_obs = np.array([[-np.inf, -np.inf, -2.5, -2.5]] * len(self.agents), dtype=np.float32) 
max_obs = np.array([[np.inf, np.inf, 2.5, 2.5]] * len(self.agents), dtype=np.float32)

self.observation_space = spaces.Box(low=min_obs, high=max_obs, dtype=np.float32)
```

My setup for agents is also made Multi-Agent though I am using PPO from SB3, in an OpenAI Gym custom environment. I want my model to run for 10 agents to test it.
When doing this I get an error that the observation space mismatch:

![image](https://github.com/DLR-RM/stable-baselines3/assets/45544623/b6c461bc-93f4-4591-84b4-5e4c726017fa)

Any help is appreciated

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hi @Hamza-101, 
I think it's because your env takes obs sizes (n_envs, 3, 4). Use a wrapper to make it compatible in terms of shape.

Next time, please be more careful when opening an issue:

> Important Note: If your question is anything like "Why is my code generating this error?", you must [submit a bug report](https://github.com/DLR-RM/stable-baselines3/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=%5BBug%5D%3A+bug+title) instead.

> If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) *

> If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces. *

> My issue does not relate to a custom gym environment. (Use the custom gym env template instead) *

If the error remains, please open a new issue, in the right way this time.

**Comment by Hamza-101** [comment]
That's the issue. I will repost in a detailed one.
