### ISSUE TITLE
Handing mission space in Babyai env 

### ISSUE THREAD

**Issue by Chainesh** [DLR-RM/stable-baselines3#1914]
### 🐛 Bug

Hii,

I'm trying to train **BabyAI environment** for _specific missions_ during training. The observation space of BabyAI looks like this `Dict('direction': Discrete(4), 'image': Box(0, 255, (7, 7, 3), uint8), 'mission': MissionSpace(<function BabyAIMissionSpace._gen_mission at 0x7f813d9da940>, None))` 
and using **RGBImgPartialObsWrapper** I've converted the observation Space to 
`Dict('direction': Discrete(4), 'image': Box(0, 255, (56, 56, 3), uint8), 'mission': MissionSpace(<function BabyAIMissionSpace._gen_mission at 0x7aa32616bc40>, None))`.

Whether I pass DummyVecEnv or not it throws me the same error `TypeError: 'NoneType' object is not iterable ` due to the fact that mission key is None. How can I train this model considering I want to use MultiInputPolicy after converting the mission into vector embedding and concatenating it with image embedding. 

Any help on this would be much appreciated. Let me know if something else is needed to solve this. Thanks :) 

### Code example

```
import gymnasium as gym 
from minigrid.wrappers import RGBImgObsWrapper, RGBImgPartialObsWrapper
from stable_baselines3.common.vec_env import VecTransposeImage, DummyVecEnv
from minigrid.wrappers import RGBImgPartialObsWrapper
from stable_baselines3.common.monitor import Monitor
from stable_baselines3 import PPO

class CustomEnv(gym.Env):
    def __init__(self, env, mission):
        self.env = env
        self.observation_space = env.observation_space
        self.action_space = env.action_space
        self.mission = mission

    def reset(self, **kwargs):
        obs = self.env.reset(**kwargs)
        while self.env.mission != self.mission:
            obs = self.env.reset(**kwargs)
        return obs

    def step(self, action):
        return self.env.step(action)

    def render(self, *args, **kwargs):
        return self.env.render(*args, **kwargs)

missions  = ["pick up the red ball"]
for mission in missions:
    env  = gym.make("BabyAI-PickupLoc-v0")#, render_mode = "human" )
    env = RGBImgPartialObsWrapper(env)
    env = CustomEnv(env, mission)
    print(env.observation_space)
    env = Monitor(env)
    env = DummyVecEnv([lambda: env])
    env = VecTransposeImage(env)
    print(env.observation_space)
    model =  PPO("MlpPolicy", env, seed = 42, verbose=1)
    model.learn(50000)
```

### Relevant log output / Error message

```shell
Dict('direction': Discrete(4), 'image': Box(0, 255, (56, 56, 3), uint8), 'mission': MissionSpace(<function BabyAIMissionSpace._gen_mission at 0x7aa32616bc40>, None))
Traceback (most recent call last):
  File "/home/scl/ranfom.py", line 43, in <module>
    env = DummyVecEnv([lambda: env])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scl/anaconda3/lib/python3.11/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 46, in __init__
    self.buf_obs = OrderedDict([(k, np.zeros((self.num_envs, *tuple(shapes[k])), dtype=dtypes[k])) for k in self.keys])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scl/anaconda3/lib/python3.11/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 46, in <listcomp>
    self.buf_obs = OrderedDict([(k, np.zeros((self.num_envs, *tuple(shapes[k])), dtype=dtypes[k])) for k in self.keys])
                                                              ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [x] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hey, please provide the system info
As far as I remember, the babyai mission is a str right?

**Comment by qgallouedec** [comment]
Text observation is not supported. Technically, to resolve the error, you can convert the text to a discrete value, for example.
That said, depending on what you're trying to do and show, this solution may not be relevant.

**Comment by qgallouedec** [comment]
it should work yes
