### ISSUE TITLE
[Question] The error about DQN--ep_len_mean&ep_rew_mean output

### ISSUE THREAD

**Issue by AnnyOrange** [DLR-RM/stable-baselines3#1918]
### ❓ Question

**q**: I found that by running dqn, the output of ep_len_mean&ep_rew_mean are the same. Why this happens? How can I solve this?

By running the example code:
```python
import gymnasium as gym
from stable_baselines3 import DQN
env = gym.make("CartPole-v1", render_mode="human")
model = DQN("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10000, log_interval=4)
model.save("dqn_cartpole")
del model # remove to demonstrate saving and loading
model = DQN.load("dqn_cartpole")
obs, info = env.reset()
while True:
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, terminated, truncated, info = env.step(action)
    if terminated or truncated:
        obs, info = env.reset()
```
From my perspective, ep_len_mean is Episode Length Mean, ep_rew_mean output denotes Episode Reward Mean. These two should not be the same. However, from the output of terminal:
<img width="196" alt="1714814999560" src="https://github.com/DLR-RM/stable-baselines3/assets/99806202/8eff661f-937e-40db-b984-6c7eab872f83">
and the output from tensorboard:
<img width="887" alt="1714815031615" src="https://github.com/DLR-RM/stable-baselines3/assets/99806202/d36e3fc3-1ff2-47a6-9501-7cca15731c19">
these two are the same.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
CartPole is particular: the agent gets +1.0 reward per timestep. That’s why they are equal. But in general they aren’t.
