### ISSUE TITLE
[Question] LSTM and SAC - Am I understanding the docs correctly?

### ISSUE THREAD

**Issue by DJT777** [DLR-RM/stable-baselines3#1924]
### ❓ Question

Hello!

I was reading the docs here https://stable-baselines3.readthedocs.io/en/master/modules/sac.html#notes and it notes that it does not accept recurrent policies. If I implement my own custom network into SAC then will it not run if I use an LSTM to encode the observation space before a forward pass to something like a MLP based critic or actor?

Basically just wondering if any use of an LSTM at all in a custom policy network would be supported or not. The docs are indicating that it's not, and I want to make sure: https://stable-baselines3.readthedocs.io/en/master/modules/sac.html#notes

![image](https://github.com/DLR-RM/stable-baselines3/assets/47899472/b2969b90-0a0a-4be3-a9e9-1464f9010cbe)

Is that saying the SAC implementation won't support ANY recurrent neural networks or it doesn't support the available recurrent policies developed and available in the library.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by DJT777** [comment]
@araffin If the question is duplicate can you point me in the direction to the discussion about implementation of LSTM into SAC?

**Comment by araffin** [comment]
Related to https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/201 and https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/222 (and maybe other I forgot)

> Basically just wondering if any use of an LSTM at all in a custom policy network would be supported or not.

No lstm at all is supported currently, you would need to fork SB3 too (see related issues to have a starting point).

**Comment by DJT777** [comment]
@araffin awesome, thank you!
