### ISSUE TITLE
[bug] Agent uses GPU even with `device="cpu"` argument.

### ISSUE THREAD

**Issue by Miffyli** [DLR-RM/stable-baselines3#193]
Creating agents with `device="cpu"` still loads CUDA libraries and takes up GPU memory when looking at `nvidia-smi`:

```python
from stable_baselines3 import PPO # Happens with A2C too
agent = PPO("MlpPolicy", "CartPole-v1", device="cpu")
```

v0.8.0 is the latest version that does not have this bug.

Versions:
 * Python 3.6
 * Pytorch 1.6

**Comment by araffin** [comment]
It may come from https://github.com/DLR-RM/stable-baselines3/pull/141
