### ISSUE TITLE
[Question] SAC, a torch model becomes a bool somehow

### ISSUE THREAD

**Issue by JaimeParker** [DLR-RM/stable-baselines3#1930]
### ❓ Question

I'm using a customized env, doing a `model.learn`, and the error log is:

```
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    model.learn(total_timesteps=int(log_total_steps), progress_bar=True)
  File "/home/sjtu2327/stable_baselines3/sac/sac.py", 
line 307, in learn
    return super().learn(
  File 
"/home/table_baselines3/common/off_policy_algo
rithm.py", line 347, in learn
    self.train(batch_size=self.batch_size, gradient_steps=gradient_steps)
  File "/home/sjtu2327/stable_baselines3/sac/sac.py", 
line 201, in train
    self.policy.set_training_mode(True)
  File 
"/home/sjtu2327/stable_baselines3/sac/policies.py", line
364, in set_training_mode
    self.critic.set_training_mode(mode)
  File 
"/home/sjtu2327/stable_baselines3/common/policies.py", 
line 211, in set_training_mode
    self.train(mode)
  File 
"/home/sjtu2327/3rdParty/anaconda3/envs/sb3/lib/python3.8/site-packages/torch/nn/modules/module.
py", line 2394, in train
    module.train(mode)
  File 
"/home/sjtu2327/3rdParty/anaconda3/envs/sb3/lib/python3.8/site-packages/torch/nn/modules/module.
py", line 2394, in train
    module.train(mode)
  File 
"/home/sjtu2327/3rdParty/anaconda3/envs/sb3/lib/python3.8/site-packages/torch/nn/modules/module.
py", line 2394, in train
    module.train(mode)
AttributeError: 'bool' object has no attribute 'train'
```

pretty weird, how could a torch nn module became a bool?

I'm using:

* ubuntu 22.04
* NVIDIA driver 550.54.15
* cuda 12.4
* torch 2.2.2 + cu121

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hi, thanks for reporting, but next time, please read the form more carefully:

> Important Note: If your question is anything like "Why is my code generating this error?", you must [submit a bug report](https://github.com/DLR-RM/stable-baselines3/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=%5BBug%5D%3A+bug+title) instead.

It's hard to understand this error as it stands, too many context elements are missing. You'd have to provide all the elements requested in the custom env issue template. Feel free to close this issue and open a new one if it's easier for you.
