### ISSUE TITLE
[Feature Request] Random Network Distillation with PPO (RND-PPO)

### ISSUE THREAD

**Issue by edofazza** [DLR-RM/stable-baselines3#1935]
### 🚀 Feature

It would be interesting to integrate Random Network Distillation policies (https://arxiv.org/abs/1810.12894) to be used with PPO.

### Motivation

RND implementation on GitHub are scarse and many of them are very old and not practical to use. Having this features inside stable-baseline3 could improve researches in many field.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [ ] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
Hello,
if you want SB3 + RND, you should probably have a look at https://github.com/RLE-Foundation/RLeXplore (the link is in our doc).

**Comment by zbenmo** [comment]
I'm going to try to wrap an environment with reward wrapper and to add the RND loss to the given reward, then use PPO from sb3. Should be more or less the same.
