### ISSUE TITLE
[Question] Optimization of memory usage

### ISSUE THREAD

**Issue by zichunxx** [DLR-RM/stable-baselines3#1936]
### ❓ Question

Hi! 

First of all, thanks to the SB3 team. I've been learning a lot of worthwhile things from this repo.

Recently, I've been struggling with the optimization of memory usage when training with three stacked image inputs. I hope I can get some guidance from you.

The visual-input training process usually takes plenty of memory for the replay buffer, like [drqv2](https://github.com/facebookresearch/drqv2.git). I tried to reproduce the results in drqv2, but I found the used memory has achieved 30 GB+ with only 300,000 training steps, which is not enough for visual-based reinforcement learning. In drqv2, the experience is stored on disk and loaded with PyTorch IterableDataset and DataLoader. The frequent save/load process seems to trigger the memory leak.

Thus, I want to replace the replay buffer in drqv2 with the SB3 API. Before the training started, I got a warning that this system does not have enough memory to store the complete replay buffer 63.52GB > 55.54GB even with `optimize_memory_usage=True`.

Is there any better way to optimize memory usage with the SB3 API? Any suggestions would be greatly appreciated!

Thanks!

Issues I checked:
* https://github.com/DLR-RM/stable-baselines3/issues/387
* https://github.com/DLR-RM/stable-baselines3/issues/37

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Increase your swap maybe?

**Comment by qgallouedec** [comment]
> Thanks for the advice. I just know less about increasing swap to relieve memory pressure. I will find out how to implement what you suggested.

In fact, I'd recommend trying to increase the swap before. It's probably easier.
