### ISSUE TITLE
[Question] Relationship between n_step, episode, and advantage in episodic tasks

### ISSUE THREAD

**Issue by d505** [DLR-RM/stable-baselines3#1938]
### ❓ Question

Hello!

I have a question about n_step and the relationship between episodes and advantage in episodic tasks. I have an episodic task that ends with the same step every time.  And I use PPO.
If n_step is greater than episode length, I believe that the advantage function will take into account and compute for the next episode as well. What do you think is actually the case? 
Then I would prefer n_step equal to episode length without including other episodes.

The following piece of code.
https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/buffers.py#L402

On the other hand, other questions seemed to suggest that including other episodes would be a good idea.
https://github.com/DLR-RM/stable-baselines3/issues/560

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
If the episode length is constant, and n_step is greater than the episode length, then yes, the rollout will contain data from several episodes. In fact, as explained in the issue you linked, this allows for more stable updates.
Why do you want to reduce n_step so that this isn't the case?

**Comment by d505** [comment]
Thanks for the reply.
I thought it might not be a problem when calculating the advantage. I understand that Advantage is similar to cumulative rewards. It seemed to me that the reward for an action in another episode is not related to the action in the current episode.

**Comment by d505** [comment]
Thank you.
Maybe I didn't understand  code well enough. Am I correct that self.episode_starts[] is set to 1 each time the episode changes?
