### ISSUE TITLE
[Question] How to set learning rate and scheduler for custom feature extractor?

### ISSUE THREAD

**Issue by edwardjjj** [DLR-RM/stable-baselines3#1941]
### ❓ Question

Hi, everyone
I would like to set a learning rate and scheduler for the feature extractor that differs from those of the actor-critic networks. Is there a way to do this?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hello, this is not a supported feature at the moment. You will probably need to modify the sb3 source code to do what you describe. Feel free to link to your branch or anything else that might be useful if you manage to get it working.
