### ISSUE TITLE
[Question] multi processus observation collection

### ISSUE THREAD

**Issue by kenzlegouge** [DLR-RM/stable-baselines3#1949]
### ❓ Question

I built an env that relies on an external DLL. Due to the constraints of this Dll, it cannot be loaded twice in the same process.
This makes make_vec_env impossible.

Is it possible launch multiple env in separate processes, and collect the different observations and feed them to the learner (PPO in my case)?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Is it possible launch multiple env in separate processes, and collect the different observations and feed them to the learner (PPO in my case)?

Hello, 
have you looked into `SubprocVecEnv` in the doc? (it can be passed as parameter to `make_vec_env`)
