### ISSUE TITLE
Imcompatibility with gym env despite having stable_baselines3 version 2.x

### ISSUE THREAD

**Issue by KevinHan1209** [DLR-RM/stable-baselines3#1951]
### 🐛 Bug

Trying to run the example learn.py from the original gym_pybullet_drone repo and came across a problem with the HoverAviary env. Seems to still be incompatible with gym env even with various versions of 2.x that I tried for stable_baselines3, which is said to support gymnasium. Not sure what's wrong at this point.

Stable_baselines3 versions checked:

- 2.2.1
- 2.3.2
- 2.4.0a1

### Code example

```

from stable_baselines3.common.env_checker import check_env
from gym_pybullet_drones.envs.HoverAviary import HoverAviary
from gym_pybullet_drones.utils.enums import ObservationType, ActionType


env = HoverAviary(obs=ObservationType('kin'), act=ActionType('one_d_rpm'))
check_env(env)

```

### Relevant log output / Error message

```shell
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[1], line 7
      3 from gym_pybullet_drones.utils.enums import ObservationType, ActionType
      6 env = HoverAviary(obs=ObservationType('kin'), act=ActionType('one_d_rpm'))
----> 7 check_env(env)

File ~/opt/anaconda3/envs/drones/lib/python3.10/site-packages/stable_baselines3/common/env_checker.py:461, in check_env(env, warn, skip_render_check)
    458     return
    460 # ============ Check the returned values ===============
--> 461 _check_returned_values(env, observation_space, action_space)
    463 # ==== Check the render method and the declared render modes ====
    464 if not skip_render_check:

File ~/opt/anaconda3/envs/drones/lib/python3.10/site-packages/stable_baselines3/common/env_checker.py:288, in _check_returned_values(env, observation_space, action_space)
    286             raise AssertionError(f"Error while checking key={key}: " + str(e)) from e
    287 else:
--> 288     _check_obs(obs, observation_space, "reset")
    290 # Sample a random action
    291 action = action_space.sample()

File ~/opt/anaconda3/envs/drones/lib/python3.10/site-packages/stable_baselines3/common/env_checker.py:207, in _check_obs(obs, observation_space, method_name)
    200 if isinstance(obs, np.ndarray):
    201     # check obs dimensions, dtype and bounds
    202     assert observation_space.shape == obs.shape, (
...
    213         lower_bounds, upper_bounds = observation_space.low, observation_space.high

AssertionError: The observation returned by the `reset()` method does not match the data type (cannot cast) of the given observation space Box([[-inf -inf   0. -inf -inf -inf -inf -inf -inf -inf -inf -inf  -1.  -1.
   -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.  -1.]], [[inf inf inf inf inf inf inf inf inf inf inf inf  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.]], (1, 27), float32). Expected: float32, actual dtype: float64
```

### System Info

- OS: macOS-10.16-x86_64-i386-64bit Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
- Python: 3.10.14
- Stable-Baselines3: 2.2.1
- PyTorch: 2.2.2
- GPU Enabled: False
- Numpy: 1.26.4
- Cloudpickle: 3.0.0
- Gymnasium: 0.28.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
this is not a gym issue.
if you look at the error message: `The observation returned by the `reset()` method does not match the data type (cannot cast) of the given observation space`
`Expected: float32, actual dtype: float64`

Also, in that case, even if the env checker raises an error, it may work when running the algorithm.
