### ISSUE TITLE
[Bug]: Crash when importing PPO module

### ISSUE THREAD

**Issue by izycheva** [DLR-RM/stable-baselines3#1970]
### 🐛 Bug

I have a MacBook M3 Pro and trying to use the `stable_baselines3` Python library. As soon as I import the library, Python crashes. For me the crash happens when I load `ppo` component (and also if I import the whole library), I assume the M3 chip is not supported and using Intel-like Cpu instructions fails. 

### To Reproduce

```
$ python3
from stable_baselines3 import ppo
```
on a MacBook M3 Pro

### Relevant log output / Error message

```shell
Here are the versions I am using:

Python 3.12.4
pip 24.1.2
stable_baselines3  2.3.2
```
and the output in the console:
```
(.venv) % python3
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from stable_baselines3 import ppo
zsh: illegal hardware instruction  python3
```
```


### System Info

Chip: Apple M3 Pro
macOS Sonoma 14.4.1


### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
i guess this is a PyTorch issue, not a sb3 one (see related issue too).

**Comment by izycheva** [comment]
Hey,
I am not sure, torch seems to find the mps device (at least).
```
$ python3
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> if torch.backends.mps.is_available():
...     mps_device = torch.device("mps")
...     x = torch.ones(1, device=mps_device)
...     print (x)
... else:
...     print ("MPS device not found.")
... 
tensor([1.], device='mps:0')
```

Do you have a suggestion how to test it? Is there a parametrized way to import sb3? Since I cannot import it, I cannot tell it which device to use yet.

**Comment by araffin** [comment]
If it's not pytorch, it might be numpy then. What version are you using? Can you import it?

The reason is SB3 is a pure python library, so if something goes wrong, it's most probably due to C library with python wrapper (PyTorch, Numpy, ...).

**Comment by izycheva** [comment]
ohh, I found the culprit now, it's `tensorflow` library, seems like there's a different library for macs `tensorflow-macos` (which I also cannot simply install with pip, ah well). Thanks for your help!
