### ISSUE TITLE
Actions are generated out of the range

### ISSUE THREAD

**Issue by fardinabbasi** [DLR-RM/stable-baselines3#1972]
### ❓ Question

In my custom environment, the action space is supposed to be limited to the range from 1 to an integer value. However I found out the actions are generated regardless of the specified range, and then clipped to the range.

```python
self.observation_space = gym.spaces.Box(
    low=-np.inf,
    high=np.inf,
    shape=(len(self.assets), len(features_col)),
    dtype=np.float64
)
self.action_space = gym.spaces.Box(
    low=1.0,
    high=len(self.assets),
    shape=(len(self.assets),),
    dtype=np.float64
)
```
I used the following LoggerCallback class to store each step's action:
```python
class LoggerCallback(BaseCallback):
    def __init__(self, verbose=2):
        super(LoggerCallback, self).__init__(verbose)
        self.rewards = []
        self.infos = []
        self.actions = []

    def _on_step(self) -> bool:
        print(self.locals)
        reward = self.locals['rewards']
        info = self.locals['infos']
        action = self.locals['actions']
        self.rewards.append(reward[0])
        self.infos.append(info[0])
        self.actions.append(action[0])
        return True
```
After training an A2C agent, I found that the generated actions are not within the specified range but are clipped to fit the range:
```python
reward_logger = LoggerCallback()
model = A2C("MlpPolicy", env, verbose=2, learning_rate=1e-4, tensorboard_log="./a2c/", seed = 456)
model.learn(total_steps, log_interval = 1,
            callback=reward_logger,
            tb_log_name="train")
```

Here is an example of the actions and the clipped actions:
```
'actions': array([[-0.7474299 ,  0.60156524,  0.29603988, -0.46686748, -0.17088744,
         0.720998  ,  1.477527  , -0.13571589]], dtype=float32)
```
```
'clipped_actions': array([[1.        , 1.        , 1.        , 1.        , 1.        ,1.        , 1.47752702, 1.        ]])
```
I expected the actions to be distributed within the range and not to be clipped. Can anyone help me understand why this is happening?

**Stable Baseline Version:** 2.3.2
**Python Version:** 3.10.12
**Environment:** Google Colab

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment

**Comment by fardinabbasi** [comment]
> > I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
> 
> https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment

Thanks😬
