### ISSUE TITLE
[Question] New to this and can't get it installed plz help

### ISSUE THREAD

**Issue by Misticfury** [DLR-RM/stable-baselines3#1987]
### ❓ Question

![image](https://github.com/user-attachments/assets/d57f9b2a-460e-4969-a037-1c98e3952131)

when i run the pip install it fails here plz help.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> If code there is, it is minimal and working

Closing because the minimum requirements for seeking help are not met.
