### ISSUE TITLE
[Question] About the output layer of algorithms

### ISSUE THREAD

**Issue by abdulkadrtr** [DLR-RM/stable-baselines3#1988]
### ❓ Question

Hello, I am working on a project using SAC and PPO algorithms from stable-baselines3. I have connected my working environment to a gym environment, and for example, my action space is defined as 
`self.action_space = spaces.Box(low=np.array([-2, 0]), high=np.array([2, 8]), dtype=np.float32)`
Do the algorithms I use adjust their output layer according to the defined action space? Specifically, what is used in the output layer of algorithms like SAC, PPO, and TD3?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment and many related/duplicate issues. In general, I would recommend you to read more about PPO/SAC (we have link to resource in our doc).
