### ISSUE TITLE
Clarification on Dependency Between Elements in Action Generation

### ISSUE THREAD

**Issue by fardinabbasi** [DLR-RM/stable-baselines3#1989]
### ❓ Question

Hello,

I have a question regarding the action generation process in Stable Baselines3. Specifically, I’m working with a box action space that has a shape of an array with n elements.

Could you please clarify whether each element in this action space array is generated independently, or if there is some statistical dependency between them during the action generation process?

If possible, I would also appreciate any documentation or specific sections of the source code that I could review to get a deeper understanding of this process.

Thank you for your time and support!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

which algorithms are you using?

Most algorithms rely on a Gaussian distribution with a diagonal covariance matrix.
So they are sampled independently although the parameters of the Gaussian come from the same network (so not fully independent).

https://github.com/DLR-RM/stable-baselines3/blob/4a1137ba3ac0ff0ae095aca564edc82ec37b7f1c/stable_baselines3/common/distributions.py#L125

https://github.com/DLR-RM/stable-baselines3/blob/4a1137ba3ac0ff0ae095aca564edc82ec37b7f1c/stable_baselines3/common/policies.py#L654-L655

https://github.com/DLR-RM/stable-baselines3/blob/4a1137ba3ac0ff0ae095aca564edc82ec37b7f1c/stable_baselines3/sac/policies.py#L101

**Comment by fardinabbasi** [comment]
Thank you for your response! I’m actually planning to perform a benchmark using all SB3 algorithms, so the information you provided is really helpful.

I have a few follow-up questions:

* Weight Updates: Could you clarify when exactly the agent updates its weights? Is it after each sample of (observation, action, reward), or does it follow a different mechanism?

* Training Control: Is there a specific parameter that allows me to control when the agent is trained? For instance, can I control whether it updates after every step or after a batch of experiences?

If possible, I would greatly appreciate any documentation or specific sections of the source code that I could review to get a deeper understanding of these processes.

Thank you again for your support!

**Comment by araffin** [comment]
> I’m actually planning to perform a benchmark using all SB3 algorithms, 

you should have a look at https://wandb.ai/openrlbenchmark/sb3 then (we did a benchmark using the RL Zoo).

> Weight Updates: Could you clarify when exactly the agent updates its weights? Is it after each sample of (observation, action, reward), or does it follow a different mechanism?

> Training Control: Is there a specific parameter that allows me to control when the agent is trained? For instance, can I control whether it updates after every step or after a batch of experiences?

It depends on the algorithm, see https://github.com/DLR-RM/stable-baselines3/issues/1150#issuecomment-1302119777

for off policy algos:
https://github.com/DLR-RM/stable-baselines3/blob/4a1137ba3ac0ff0ae095aca564edc82ec37b7f1c/stable_baselines3/common/off_policy_algorithm.py#L328-L347

**Comment by fardinabbasi** [comment]
Thank you for your support!
