### ISSUE TITLE
[Feature Request] Add support for optional environment wrapping in base_class.py

### ISSUE THREAD

**Issue by hasan-yaman** [DLR-RM/stable-baselines3#1996]
### 🚀 Feature

A similar feature request is made #671 

The mentioned issue clearly shows the motivation and details of the feature request. 

#700 tries to solve the issue. However, adding a `skip` option to `VecTransposeImage` is not enough because the `skip` option is not used in `BaseAlgorithm`. https://github.com/DLR-RM/stable-baselines3/blob/9a3b28bb9f24a1646479500fb23be55ba652a30d/stable_baselines3/common/base_class.py#L246

Therefore, it is better to have functionality to skip wrapping environments.

### Alternatives

- We can just add support to skip `VecTransposeImage` transformation.  https://github.com/DLR-RM/stable-baselines3/blob/9a3b28bb9f24a1646479500fb23be55ba652a30d/stable_baselines3/common/base_class.py#L228
above code can be replaced with

```python
if not is_vecenv_wrapped(env, VecTransposeImage) and wrap_with_vec_transpose_image: 
```
(We can add above support for each transformation in `_wrap_env`)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
Hello,

> However, adding a skip option to VecTransposeImage is not enough because the skip option is not used in BaseAlgorithm. 

The idea of the `skip` parameter is that the user need to wrap the env manually and set `skip=True` before passing the `VecEnv` to the model constructor.
If it is wrapped, then `if not is_vecenv_wrapped(env, VecTransposeImage): ` will be skipped.

**Comment by hasan-yaman** [comment]
Hello @araffin 
Thanks for your response! I understand the code better now!
