### ISSUE TITLE
Is possible to filter experience from the episode whose length is longer than a specified value to add into replay_buffer?

### ISSUE THREAD

**Issue by CornfileChase** [DLR-RM/stable-baselines3#1999]
### ❓ Question

In the self-build custom environment, I suppose that some state-action pair that from very short episode is not helpful to the training process, thus I want to filter the experience from these episodes and do not push into the replay_buffer, can anyone tell me how to implement this function? thanks!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I suppose that some state-action pair that from very short episode is not helpful to the training process

why not?
failures are important to learn what not to do.

>  I want to filter the experience from these episodes and do not push into the replay_buffer, 

If you want to do that, you would need to fork SB3 or  subclass SB3 algorithms.
