### ISSUE TITLE
[Feature Request] Safe Reinforcement Learning & Multi-Objective Reinforcement Learning

### ISSUE THREAD

**Issue by cherrywoods** [DLR-RM/stable-baselines3#2008]
### 🚀 Feature

Some reinforcement problems, like [safe reinforcement learning](https://github.com/PKU-Alignment/safety-gymnasium/tree/main), require the environment to return multiple reward-like values. For example, in safe reinforcement learning, the environment returns a second value besides the reward, typically called a cost, that needs to be kept below a certain threshold. In [multi-objective reinforcement learning](https://www.jmlr.org/papers/volume15/vanmoffaert14a/vanmoffaert14a.pdf), the environment returns several reward terms. By allowing `env.step` to return multiple rewards like so:
```
obs, *rewards, dones, infos = env.step(...)
```
one can easily support arbitrarily many reward terms. 

Stable baselines3 provides many useful helpers (Monitors, Normalization, ...) that could easily be generalized to support multiple reward terms (just apply the reward processing to multiple rewards).

### Motivation

It would be nice to be able to use all the helpers from SB3 in the multi-reward setting.

### Pitch

By allowing `env.step` to return multiple rewards like so:
```
obs, *rewards, dones, infos = env.step(...)
```
one can support arbitrarily many reward terms, while being fully compatible with existing environments that return a single reward. 

The environment wrappers that process rewards would need to be rewritten to apply their processing to every reward. Here is the skeleton of a `Monitor` that supports multiple rewards (everything that is left out remains as in the current `Monitor` implementation:
```python
class Monitor(...):
    def __init__(...):
        ...
        self.rewards: List[List[float]] | None = None  # initialized once we know how many reward terms there are
        ...

    def _init_rewards(rewards: Sequence[float]):
        if self.rewards is None:
            self.rewards = [[] for _ in rewards]

    def reset(...):
        self.rewards = None

    def step(...):
        ...
        observation, *rewards, terminated, truncated, info = self.env.step(...)
        self._init_rewards(rewards)
        for i, rew in enumerate(rewards):
            self.rewards[i].append(rew)
        if terminated or truncated:
            ...
            ep_rews = [sum(rews) for rews in self.rewards]
            ...
            ep_info = {f"r{i}: round(ep_rew[i], 6) for i in range(len(ep_rews))}
            ep_info |= {"l": ep_len, ...}
            ...
        return observation, *rewards, terminated, truncated, info
```

### Alternatives

- Environments return sequences of rewards: Same 4/5-element return value of environments, but existing environments would have to be modified to return 1-element sequences. Otherwise, wrappers would have to consider two cases: one where the environment returns a single reward, and one where it returns a sequence of rewards. 
- Return additional rewards in the info `dict`: Also possible, but less nice. Allows to use existing wrappers out of the box, but requires writing additional wrappers that duplicate much of the functionality of the SB3 wrappers. 

### Additional context

There is an older issue that asked for something similar, but less general, and breaking backwards compatibility: https://github.com/DLR-RM/stable-baselines3/issues/1160

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
Hello,
thanks for the proposal but I would consider that to be out of the scope of SB3.

**Comment by cherrywoods** [comment]
Alright, I just wanted to post the idea in case there would be interest. Thanks for considering it!
