### ISSUE TITLE
[question/doc] Name of the class RolloutBuffer

### ISSUE THREAD

**Issue by stheid** [DLR-RM/stable-baselines3#201]
on-policy algorithms in this library use a buffer called "RolloutBuffer"

In RL the term rollout is usually used in the context of model-based RL and planning. However, as it is used here its just a special kind of experience replay buffer where all elements are produced by playing out one policy on the environment. In planning, the rollout also has a consecutive quality to it. Also "rollout buffer" is permutated randomly.

Hence i would suggest to rename the buffer in a different way to prevent misconception or at least clarify this in the class documentation.

If you broadly follow along my argument i could make a suggestion and perhaps create a PR.

**Comment by araffin** [comment]
Hello,

>In RL the term rollout is usually used in the context of model-based RL and planning.

I would disagree with that statement. Rollout is used both in model-free (see [Spinning Up guide](https://spinningup.openai.com/en/latest/search.html?q=rollout&check_keywords=yes&area=default)) and model-based RL.

In model-free RL (the current focus of this library), it usually corresponds to using the current policy and collect some data in the environment, before updating the policy and collecting new data using the updated policy.

> Also "rollout buffer" is permutated randomly.

This is true only for PPO. (and not for "classic" policy gradient algorithms like A2C).

>Hence i would suggest to rename the buffer in a different way to prevent misconception or at least clarify this in the class documentation.

What name do you propose then?

**Comment by stheid** [comment]
Hey, thanks for your quick replay!

Hm, than there might be conflicting views on that in literature. In Sutton&Bato as well as Bertsekas i have never seen the term used for model-free RL. So at least i can say the naming confused me and my colleague (who comes from the optimal control field).

What about OnPolicyBuffer? "collects a trajectory of length n_steps using the current policy played out on the environment. if env is done, it will reset."

But i fully understand that naming variables in a way that everyone gets the right impression immediately is almost impossible :D

Cheers

**Comment by araffin** [comment]
>So at least i can say the naming confused me and my colleague (who comes from the optimal control field).
>But i fully understand that naming variables in a way that everyone gets the right impression immediately is almost impossible :D

yes, that's why we have docstrings ;)

>Hm, than there might be conflicting views on that in literature. In Sutton&Bato as well as Bertsekas i have never seen the term used for model-free RL

that's true. I was mostly referring to "practical" use of that term that you find in different implementations like [pytorch-a2c-ppo-acktr-gail](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail), [OpenAI Baselines](https://github.com/openai/baselines), [RL Coach](https://github.com/NervanaSystems/coach) or [rllab](https://github.com/rll/rllab).

>What about OnPolicyBuffer? "collects a trajectory of length n_steps using the current policy played out on the environment. if env is done, it will reset."

why not, but would have to rename our internal API `collect_rollout()` too (used both in on- and off-policy algorithms to collect data with current policy). Do you have also a name for that?

**Comment by stheid** [comment]
What about calling it agnostic: "collect trajectories" or "fill experience buffer"

In my opinion the "onpolicy/rollout" buffer is just a special type of experience replay that is recorded in a particular way.

**Comment by Miffyli** [comment]
I am going to support @araffin here and say we should probably stay with "rollout" term. As he said, this is used in practice around RL and also used by some groups (e.g. Levine uses it in his [offline RL](https://arxiv.org/abs/2005.01643) tutorial and other lectures, although this might stem from his experience on the optimal control side). 

"collect trajectories" will cause confusion regarding if it will collect full trajectories or not (experienced this with others using e.g. rllib and other libraries), while "experience buffer" sounds more like experience-replay buffer which is offline-learning side. Indeed rollout buffer is bit of a special case of offpolicy buffer, however the crucial part is that it keeps different environments separate for computing the returns and advantages. Maybe later on these two could be somehow merged, where off-policy buffer would also keep different episodes separate so things like n-step returns and the likes become muuuuch easier to do.

**Comment by stheid** [comment]
For me the issue is solved, my main interest was to raise awareness of the confusion we had. (at least discussion wise)

Maybe additional highlighting in the documentation, which notion of rollout is referred to here and slight changes like "collect_experience" will already be enough to point other people in the right direction.

Thanks for the discussion.

**Comment by Miffyli** [comment]
Thank you for bringing this out! Confusions like these are not fun, and we would be happy to minimize them! 

> Maybe additional highlighting in the documentation, which notion of rollout is referred to here and slight changes like "collect_experience" will already be enough to point other people in the right direction.

A PR to do this would be welcome! Maybe add a small note to docstrings of `collect_rollouts` and `RolloutBuffer` that these refer to model-free side of things.

**Comment by stheid** [comment]
i will :)
