### ISSUE TITLE
[Question] Auto-regressive manner policy network?

### ISSUE THREAD

**Issue by wadmes** [DLR-RM/stable-baselines3#2010]
### ❓ Question

Hi there, 

I am trying to implement a autoregressive policy network, for example, 
in each action, I need to sample target object, and then use the target object embedding to sample the action type, and finally output the action parameters.

But it looks it is impossible to achive this since what `_build_mlp_extractor` in `MaskableActorCriticPolicy` asks it to return a action embedding and value embedding.

Is there a good way to achieve the feature?

Example figure:

![image](https://github.com/user-attachments/assets/821ade01-b5de-4c0c-b10a-c90a3cf7eab8)

Thanks!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Is there a good way to achieve the feature?

For something custom like that, it's probably better to fork SB3 / use CleanRL as a starting point.
