### ISSUE TITLE
[Bug]: Episode start flag is never set for off policy algorithms 

### ISSUE THREAD

**Issue by josndan** [DLR-RM/stable-baselines3#2011]
### 🐛 Bug

In `_sample_action` of `OffPolicyAlgorithm` class, `self.predict` function is called. But `episode_start` flag is never set for any off policy algorithms. 

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
that's correct because there is current only `RecurrentPPO` that make use of `states` (LSTM states) and episode starts (to reset the states).
