### ISSUE TITLE
[Feature Request] Warn users when using GPU with `A2C`/`PPO` + update documentation

### ISSUE THREAD

**Issue by jws-1** [DLR-RM/stable-baselines3#2012]
### 🚀 Feature

Produce a warning to users when they are using GPU with `A2C`/`PPO`, and not using a CNN.

### Motivation

As mentioned in the documentation, and various issues, `A2C` is primarily meant to be run on CPU (when not using a CNN), however the default device is `auto`, leading to GPU being used, if available. Users may gloss over this documentation, resulting in them running `A2C` on GPU (intentionally, or by `auto`). I think it'd be good to produce a warning, and direct the users to the documentation. Additionally, https://github.com/DLR-RM/stable-baselines3/issues/1245#issuecomment-1435766949 mentions that the same recommendations regarding CPU apply to `PPO`, which is not documented.

### Pitch

Produce a warning, recommending that `A2C`/`PPO` are primarily meant to run on CPU, referring to the documentation, inside the constructor of `A2C`/`PPO` if GPU is being used AND a CNN is not being used. Potentially, also update the documentation of `PPO` to reflect https://github.com/DLR-RM/stable-baselines3/issues/1245#issuecomment-1435766949.

### Alternatives

Update the example for `A2C` to heed to advice regarding CPU utilisation / move the advice to before the example.

### Additional context

Reading the documentation is important, but users running sb3 code out of the box (for instance, directly following the example given in the `A2C` docs) might miss this crucial piece of information that can speed up their experiments.

I'd happily work on a PR for this if the maintainers find this an acceptable and well-motivated modification.

Thanks for your great work on this project!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by Dev1nW** [comment]
Hi @jws-1 and @araffin, 

I was wondering if this task was still available to work on? If so I would like to help.

**Comment by jws-1** [comment]
> Hi @jws-1 and @araffin,
> 
> I was wondering if this task was still available to work on? If so I would like to help.

I'm working on a PR for this, should get it in this evening! :)

**Comment by Dev1nW** [comment]
Hi @jws-1,

I just saw this and over the weekend created some code which warns the user if they are using GPU when not using CNN for both A2C and PPO as well as updated the documentation code for PPO. I ran it through all the tests in the contribution guidelines and it works, if you would like I can share the code or do a PR.

**Comment by jws-1** [comment]
> Hi @jws-1,
> 
> I just saw this and over the weekend created some code which warns the user if they are using GPU when not using CNN for both A2C and PPO as well as updated the documentation code for PPO. I ran it through all the tests in the contribution guidelines and it works, if you would like I can share the code or do a PR.

If you have it ready, go for it with a PR I suppose :). I got caught up with other work commitments last night, so didn't have time to finish it off. But no point us both working on the same thing!

**Comment by araffin** [comment]
closed by https://github.com/DLR-RM/stable-baselines3/pull/2017
