### ISSUE TITLE
[Question] How to change my loaded model's "exploration_initial_eps", "exploration_final_eps", "exploration_fraction" parameters?

### ISSUE THREAD

**Issue by Melih96** [DLR-RM/stable-baselines3#2018]
### ❓ Question

I have a trained model which I load it with a .zip file. I can change my "learning_rate" with "**_custom_objects_**" dictionary structure. When I write the epsilon parameters to the "**_custom_objects_**" to **_change starting epsilon and its decay rate_** to train again with my previously trained model, nothing happens. 

I am trying to try curriculum learning with minimal exploration for my second task. I have taught my agent to solve the first task and trying to give it a harder problem. I do not want to start from epsilon=1.0 or epsilon=0.05 which was my trained model's final epsilon. I want to start training with epsilon=0.1 and decay it from there.

Asking for an advice: 
1) Should I start with epsilon=0.1 and decay from there? "**_replay_buffer_**" is fully cleared.
2) Save the previously trained session's "**_replay_buffer_**" and start to the next task from epsilon=1.0?

How can I adjust my starting epsilon values for my loaded model?

My algorithm is QR-DQN.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
See https://github.com/DLR-RM/stable-baselines3/issues/1629#issuecomment-1653026257 and callbacks in the doc.

You need to update the exploration schedule as for the lr schedule: https://github.com/DLR-RM/stable-baselines3/issues/735#issuecomment-1047638011

Exploration schedule is defined here:
https://github.com/DLR-RM/stable-baselines3/blob/56c153f048f1035f239b77d1569b240ace83c130/stable_baselines3/dqn/dqn.py#L149

I you reload the model, you might be able to pass directly `exploration_initial_eps` argument to the load method (`DQN.load(..., exploration_initial_eps=...)`).

**Comment by Melih96** [comment]
(DQN.load(..., exploration_initial_eps=...)) has worked for me, thanks!

**Comment by Melih96** [comment]
(DQN.load(..., exploration_initial_eps=...)) has worked for me, thanks!
