### ISSUE TITLE
[Question] Can stable-baselines3 be installed through pip without cuda dependencies? Is the CPU only docker image the only alternative?

### ISSUE THREAD

**Issue by joemc94** [DLR-RM/stable-baselines3#2019]
### ❓ Question

Question in the title: Can stable-baselines3 be installed through pip without cuda dependencies? Is the CPU only docker image the only alternative?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
>  Can stable-baselines3 be installed through pip without cuda dependencies?

You need to install torch cpu version first: 

https://github.com/DLR-RM/stable-baselines3/blob/56c153f048f1035f239b77d1569b240ace83c130/.github/workflows/ci.yml#L34-L35
