### ISSUE TITLE
[Feature Request] request title jax API and  gymnax

### ISSUE THREAD

**Issue by quanmissq** [DLR-RM/stable-baselines3#2020]
### 🚀 Feature

Suggest updating the stable version of the jax API and the algorithm API for gym

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
Hello, 
could you please provide more information.

Are you referring to https://github.com/DLR-RM/stable-baselines3/pull/1837 ?
