### ISSUE TITLE
[Question] WSL Freeze with Rocm

### ISSUE THREAD

**Issue by darkavatar23** [DLR-RM/stable-baselines3#2021]
#### **Description**
I am encountering an issue where the training process freezes indefinitely when using the GPU. The same code works perfectly when running on the CPU. However, when I switch to the GPU, the process gets stuck at:

```
Using cuda device
```
![image](https://github.com/user-attachments/assets/e0ce2fc6-738b-4f39-94de-aba5f3660d5f)

The code freezes after this message and no progress is made.

#### **Steps to reproduce:**
1. Follow the [ROCm PyTorch installation guide for WSL](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html).
2. Use the following setup to train the model:

```python
model = model_class("MlpPolicy", 
                    env, 
                    policy_kwargs=policy_kwargs_other, 
                    verbose=3,
                    # device='cpu',  # Uncomment for CPU (works fine)
                    learning_rate=learning_rate, 
                    buffer_size=10000,
                    batch_size=100,
                    learning_starts=100,
                    train_freq=1)
```

3. With the `device='cuda'`, the process gets stuck.

#### **Expected behavior:**
The training should run without freezing when using the GPU.

#### **Current behavior:**
- The process freezes after printing `Using cuda device`.
- There is no further progress, and the training doesn't start.

#### **Environment information:**
- **PyTorch installation**: Verified using the [ROCm PyTorch guide](https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html).
- **Verifications:**

```bash
# PyTorch import test
python3 -c 'import torch' 2> /dev/null && echo 'Success' || echo 'Failure'
```
- Output: `Success`

```bash
# Check CUDA availability
python3 -c 'import torch; print(torch.cuda.is_available())'
```
- Output: `True`

```bash
# Check GPU device name
python3 -c "import torch; print(f'device name [0]:', torch.cuda.get_device_name(0))"
```
- Output: `device name [0]: AMD Radeon RX 6800`

```bash
# PyTorch environment information
python3 -m torch.utils.collect_env
```
- Output:
  ```
  Collecting environment information...
  PyTorch version: 2.1.2+rocm6.1.3
  Is debug build: False
  ROCM used to build PyTorch: 6.1.40093-bd86f1708

  OS: Ubuntu 22.04.5 LTS (x86_64)
  Python platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
  GPU models and configuration: AMD Radeon RX 6800
  HIP runtime version: 6.1.40093
  MIOpen runtime version: 3.1.0
  ```

#### **System Information:**

- **OS**: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- **Python**: 3.10.12
- **Stable-Baselines3**: 2.3.2
- **PyTorch**: 2.1.2+rocm6.1.3
- **GPU Enabled**: True
- **Numpy**: 1.26.4
- **Cloudpickle**: 3.0.0
- **Gymnasium**: 0.29.1
- **OpenAI Gym**: 0.26.2

#### **Additional Information:**
- **CPU**: AMD Ryzen 7 3800XT 8-Core Processor
- **GPU**: AMD Radeon RX 6800
- **Environment**: WSL 2

Any help or suggestions to resolve the freezing issue when using the GPU would be greatly appreciated!

---

### **References:**
- PyTorch ROCm installation guide: https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
this sounds more like a PyTorch issue than a SB3 issue.
I assume that if you would try to do any another computation with pytorch on your GPU (without SB3), it would also fail?

**Comment by darkavatar23** [comment]
Yeah, it's a problem with Pytorch it self, sorry

**Comment by ludwig-jo** [comment]
I am facing the same problem. How did you fix it in the end?
