### ISSUE TITLE
[Feature Request] When are you planning to upgrade to Gymnasium v1.0.0

### ISSUE THREAD

**Issue by drulye** [DLR-RM/stable-baselines3#2023]
### 🚀 Feature

When are you planning to upgrade to Gymnasium v1.0.0

https://github.com/Farama-Foundation/Gymnasium/releases/tag/v1.0.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] If I'm requesting a new feature, I have proposed alternatives

**Comment by araffin** [comment]
Support added in SB3 v2.4.0a11 (pre-release, also on master), please give it a try.
