### ISSUE TITLE
[Question] Batch Size Selection for a Finite MDP

### ISSUE THREAD

**Issue by DavidLudl** [DLR-RM/stable-baselines3#2024]
### ❓ Question

Hello.

I would like to ask if I have a finite MDP, where each episode has a same fixed timestep \$T$\. Then during the training, do I have to choose batch size with \$n\times T$\? Or any other batch size is also OK?

Thank you for your time,

Best regards,

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Then during the training, do I have to choose batch size with n × T ? Or any other batch size is also OK?

What algorithm are you using?
I guess you are talking about on policy algorithm (A2C/PPO) and the n steps parameter?

In that case, you can use any number of steps.

**Comment by DavidLudl** [comment]
I am using PPO. They parameter I want to ask is the batch_size. Should I set the batch_size (default 64) in PPO algorithm to n*T ?

**Comment by araffin** [comment]
The mini batch size can be kept as is, it is only about the gradient step.

**Comment by DavidLudl** [comment]
Thank you, now I understand.
