### ISSUE TITLE
[Question] Error Installing stable-baselines3[extra] on Windows

### ISSUE THREAD

**Issue by bajramienes** [DLR-RM/stable-baselines3#2033]
### ❓ Question

I encountered an error while trying to install stable-baselines3[extra] using pip. The following command was executed:
`pip install stable-baselines3[extra]`

Error Output:
```
Collecting stable-baselines3[extra]
  Using cached stable_baselines3-2.3.2-py3-none-any.whl.metadata (5.1 kB)
Collecting gymnasium<0.30,>=0.28.1 (from stable-baselines3[extra])
  Using cached gymnasium-0.29.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.20 in c:\users\enes\appdata\local\programs\python\python313\lib\site-packages (from stable-baselines3[extra]) (2.1.2)
INFO: pip is looking at multiple versions of stable-baselines3[extra] to determine which version is compatible with other requirements. This could take a while.
Collecting stable-baselines3[extra]
  Using cached stable_baselines3-2.2.1-py3-none-any.whl.metadata (5.0 kB)
  Using cached stable_baselines3-2.1.0-py3-none-any.whl.metadata (5.2 kB)
  Using cached stable_baselines3-2.0.0-py3-none-any.whl.metadata (5.4 kB)
Collecting gymnasium==0.28.1 (from stable-baselines3[extra])
  Using cached gymnasium-0.28.1-py3-none-any.whl.metadata (9.2 kB)
Collecting stable-baselines3[extra]
  Using cached stable_baselines3-1.8.0-py3-none-any.whl.metadata (5.0 kB)
Collecting gym==0.21 (from stable-baselines3[extra])
  Using cached gym-0.21.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        ...
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

error: metadata-generation-failed
```
OS: Windows
Python version: 3.13

Could you provide guidance on how to resolve this issue, or suggest any compatible alternatives?

Regards

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
What version of pip are you using?
Could you try with python 3.11/asking for a specific sb3 version ?

Pip is downloading some old version for some reasons and gym cannot be installed.

**Comment by bajramienes** [comment]
Hi @araffin, my pip version is 24.3.1

**Comment by bajramienes** [comment]
Hello @araffin, any updates on this issue?

**Comment by araffin** [comment]
did you try with another python version? (python 3.11)

**Comment by araffin** [comment]
and could you try with the latest sb3 version and the current master version (see doc on how to install)?
