### ISSUE TITLE
[question] How to change the learning env of the model

### ISSUE THREAD

**Issue by liushunyu** [DLR-RM/stable-baselines3#205]
Hello, I want to do the multi-task learning based on the SB3, but I have some question about change the env.

What I want to do is to change the learning `env` of the `model` as follows.

```python
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack

env_id_1 = "PongNoFrameskip-v4"
env_1 = make_atari_env(env_id_1, n_envs=8, seed=seed)
env_1 = VecFrameStack(env_1, n_stack=4)

model = PPO('CnnPolicy', env)
model.learn(total_timesteps=25000)

env_id_2 = "BreakoutNoFrameskip-v4"
env_2 = make_atari_env(env_id_2, n_envs=8, seed=seed)
env_2 = VecFrameStack(env_2, n_stack=4)

###########################################################
# what I should do here to change the env of the model #
###########################################################

model.learn(total_timesteps=25000)
```

I want to directly change the `model.env`, but I find that some variables associated with it, such as `_vec_normalize_env`, and some variables is not None, such as `ep_info_buffer`. Should I directly change all these variables?

I hope to ask you for help, thank you!

**Comment by Miffyli** [comment]
There is [`set_env`](https://stable-baselines3.readthedocs.io/en/latest/modules/ppo.html#stable_baselines3.ppo.PPO.set_env) function which does necessary checks and updates to facilitate the training in new environment.

**Comment by araffin** [comment]
>There is set_env function which does necessary checks and updates to facilitate the training in new environment.

I'm surprised it is not anymore in the documentation... I probably forgot it.
It was there for SB: https://stable-baselines.readthedocs.io/en/master/guide/examples.html#continual-learning

**Comment by Miffyli** [comment]
@araffin It is here https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html#stable_baselines3.ppo.PPO.set_env (I first linked "latest" instead of "master").

**Comment by liushunyu** [comment]
Thank you!
