### ISSUE TITLE
[Bug]: Last step in environment will not be saved to replay buffer, when using a callback 

### ISSUE THREAD

**Issue by JaMueDFKI** [DLR-RM/stable-baselines3#2056]
### 🐛 Bug

The last step an off-policy agent does in an environment does not get saved in the replay buffer when using a callback. This might make learning impossible. 

In my case, I used DQN and wanted to use learn with exactly one episode at a time by using the StopTrainingOnMaxEpisodes Callback. Unfortunately, the agent was unable to learn and an empty log file was produced each time.

I looked into the code and saw, that the callback can end the training before the transition can be saved to the buffer and before the log will be dumped.

This had the result, that the only transition, which receives a reward >0 was not in the replay buffer and the agent was thus unable to learn.

I propose to move the code checking the callback.on_step() returns at off_policy_algorithm:568f to the end of the while loop, after line 597, to only end rollout after the rollout step is executed in its entirety.

### To Reproduce

```python
import gymnasium
from stable_baselines3 import DQN
from stable_baselines3.common.callbacks import StopTrainingOnMaxEpisodes

episodes = 100
max_steps = 100
env = gymnasium.make("FrozenLake-v1",max_steps)

env.reset()

agent = DQN(policy="MlpPolicy", env=env, tensorboard_log="./results")

for episode in range(episodes):
    agent.learn(episodes * max_steps,
                [StopTrainingOnMaxEpisodes(1)],
                tb_log_name="Training_" + str(episode),
                reset_num_timesteps=False,
                log_interval=1)

print("Test")

obs, info = env.reset()
test_return = 0
step_counter = 0
terminated = False
while not terminated and step_counter < max_steps:
    action, _state = agent.predict(obs, deterministic=True)
    print(str(action))
    obs, reward, terminated, truncated, info = env.step(int(action))
    test_return += reward
    step_counter += 1
print("Test return: " + str(test_return))
print("Test steps: " + str(step_counter))
```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by JaMueDFKI** [comment]
The for loop is just an simulation, how my agent is used in a more complex environment.
The thing is, that resetting in this environment is not so simple, since I use HRL.
Therefore, I have to limit the training of the agent to 1 episode each time. 
That the last step in the rollout will not be saved to the replay buffer and the log file will not be written in case of using the callback seams to be problematic nonetheless.

**Comment by araffin** [comment]
For your very specific use-case, the easiest is probably to either subclass DQN or recreate the `learn()` call manually:
https://github.com/DLR-RM/stable-baselines3/blob/9caa168686342ffc358c4acc7fbd842fc5fc8aac/stable_baselines3/common/off_policy_algorithm.py#L314-L351

**Comment by JaMueDFKI** [comment]
Thanks for the help.
I will use a subclass then, in which I try out, if my agent would learn with the changes I described above.
