### ISSUE TITLE
[question] TypeError: type Tensor doesn't define __round__ method

### ISSUE THREAD

**Issue by Yufei-Kang** [DLR-RM/stable-baselines3#208]
Hi, 

I implemented the PPO on my custom environment and encountered the following problem:

![image](https://user-images.githubusercontent.com/41565676/97752555-93c7e880-1aca-11eb-9fe7-e28882d98e87.png)

Notably, the error was reported when the eposiode ends and `reset()` is called. I tested three different machine learning workloads and only one of them encountered such problem. I am really confused. Could you please offer some suggestions? Thank you very much.

By the way, the custom environment has been checked with `check_env` and no warnings or errors have been reported. 

**System Info**
 * stable-baselines3 was installed with 'pip'.
 * Tesla V100
 * Python 3.7.3
 * PyTorch 1.6.0
 * Gym 0.17.3

**Comment by araffin** [comment]
Hello,

Please provide a minimal code to reproduce the error.
I suspect that the reward returned is at some point a `torch.Tensor` and not a float.
The env checker should check that (at least for one step).

**Comment by Yufei-Kang** [comment]
> Hello,
> 
> Please provide a minimal code to reproduce the error.
> I suspect that the reward returned is at some point a `torch.Tensor` and not a float.
> The env checker should check that (at least for one step).

Hello, 

Here's the code in both `reset ` and `__init__`:
![image](https://user-images.githubusercontent.com/41565676/97755121-01761380-1acf-11eb-9fc3-8531f6ab58c7.png)
where Delta2 is of class 'numpy.ndarray' and computed by a custom function. 

The reward returned in `step` is computed by an exponential function. And the env checker reported nothing about the type problem. Thanks.

**Comment by araffin** [comment]
>Here's the code in both reset and __init__:

this is not a minimal example to reproduce the bug... and the issue comes from the `step()`.

>The reward returned in step is computed by an exponential function. And the env checker reported nothing about the type problem. Thanks.

the env checker only checks one call to `reset()` and one call to `step()`.

**Comment by Yufei-Kang** [comment]
Code in the `step()` is similar...
![image](https://user-images.githubusercontent.com/41565676/97756167-d1c80b00-1ad0-11eb-897a-b2efc79785fa.png)
and reward is computed by a exponential function.

From the log, the '__round__' is utilized to compute the `ep_info`, am I in the correct direction? Thank you.

**Comment by Yufei-Kang** [comment]
> Code in the `step()` is similar...
> ![image](https://user-images.githubusercontent.com/41565676/97756167-d1c80b00-1ad0-11eb-897a-b2efc79785fa.png)
> and reward is computed by a exponential function.
> 
> From the log, the '**round**' is utilized to compute the `ep_info`, am I in the correct direction? Thank you.

And here is the definition of action space
![image](https://user-images.githubusercontent.com/41565676/97756583-7e09f180-1ad1-11eb-9d79-8268d35eebc9.png)
thank you.

**Comment by Miffyli** [comment]
As arrafin said, please include the _code_ to reproduce the bug. We do not offer much technical support outside stable-baselines issues/bugs. Debugging by snippets of code results in a lot of overhead of asking and answering both ways around.

**Comment by araffin** [comment]
Closing this issue as no minimal working example was provided to reproduce the bug, and as the bug seems to come from the custom gym env.

**Comment by Yufei-Kang** [comment]
Thank you, Miffyli and Arrafin. There's a bug in my personal code, and now it has been fixed.

**Comment by Yufei-Kang** [comment]
Thank you, Miffyli and Araffin. There's a bug in my personal code, and now it has been fixed.

**Comment by zhwork92d** [comment]
add .item() that is ok
