### ISSUE TITLE
[question/feature request] Logging in SAC

### ISSUE THREAD

**Issue by MichiBab** [DLR-RM/stable-baselines3#209]
I have a custom Gym, that is very slow ( 1 Second per Step ) and that it barely gets to return done ( robot driving simulation ).

I use PPO successfully on it and i can always see the Logs from Tensorboard.
PPO seems to Log after every n_steps.
But if im using SAC, i never get any Logs. The Log File is created on the right spot, but never gets input.

I think the issue is, that only when done gets returned, a Log entry will be made, which is a huge problem on my environment.

On BipedalWalker-v3 a Log will be made aswell only when the episode ends. Is it possible, to use logging like on ppo, where its step based? 

The log_interval is set to 1.

It would be great to set a log interval for each steps for example, which kinda works on ppo through the n_steps parameter.

**Comment by araffin** [comment]
Hello,
you should probably take a look at the callbacks in the doc for doing such thing ;) (it has `self.logger` attribute)
