### ISSUE TITLE
Transposing image environments even if it's not needed.

### ISSUE THREAD

**Issue by avandekleut** [DLR-RM/stable-baselines3#212]
Default in the base class is to always transpose image-based environments under the assumption that they are channels-last. 
This is not always true.

https://github.com/DLR-RM/stable-baselines3/blob/6327cc6156756f5cd0b1fb600c346fc21fbd7b11/stable_baselines3/common/base_class.py#L179-L182

Code to reproduce an issue: Make an environment from pixels with `CxHxW` ordering and use a `CnnPolicy`.

```python
import gym
import dmc2gym
from stable_baselines3 import SAC

env = dmc2gym.make(domain_name='point_mass', task_name='easy', seed=1, from_pixels=True, visualize_reward=False)
print(env.observation_space.shape)
model = SAC(
    "CnnPolicy",
    env=env,
)
```

Possible solutions, none of which are very elegant: 
- Check membership in a set of known environments that are channels-last and transpose
- Guess which dimension is channels (the smallest one?)

**Comment by Miffyli** [comment]
Thanks for reporting this, but it is already covered by #142 with on-going PR #143. Lets move discussion to the PR and close this one.
