### ISSUE TITLE
[Question] How to use multiple cores with PPO?

### ISSUE THREAD

**Issue by JoeRakhimov** [DLR-RM/stable-baselines3#217]
### Question

I would like to know if it is possible to use PPO on multiple cores of CPU?

### Additional context

I would like to train an agent in multiple cores to make it faster.

### Checklist

- [ x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Gathering data by multiple workers via [vectorized environments](https://stable-baselines3.readthedocs.io/en/latest/guide/vec_envs.html), but distributed training like IMPALA is not planned before v1.2 or so (see #69).

**Comment by AlessandroZavoli** [comment]
Is it possible to run vectorized environment over multiple nodes in a cluster?

**Comment by Miffyli** [comment]
Nope, the current vectorized environments ("VecEnv") only support threads or multiprocessing (i.e. on same machine). However you could create a new VecEnv that inherits the base class and implements some kind of a multi-node communication, e.g. over MPI or sockets.

**Comment by JoeRakhimov** [comment]
> Gathering data by multiple workers via [vectorized environments](https://stable-baselines3.readthedocs.io/en/latest/guide/vec_envs.html), but distributed training like IMPALA is not planned before v1.2 or so (see #69).

Should I set the learner (PPO)'s total_timesteps 1_000_000/64 if I am running the script on 64 cores machine and I want to run 1M iterations?

**Comment by Miffyli** [comment]
`total_timesteps` counts the _total_ number of `step` calls over all environments, with 1M `total_timesteps` each environment will run `1M / 64` steps.

**Comment by araffin** [comment]
Also related: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/11

Closing as the original question was answered.
