### ISSUE TITLE
How to integrate PPO with PyG

### ISSUE THREAD

**Issue by haoxingren** [DLR-RM/stable-baselines3#219]
To build a graph neural network based RL agent, we need to use a graph package such as PyG https://pytorch-geometric.readthedocs.io/en/latest/ . I think we can use dict to represent the graph, however, PPO algorithm does not support dict observation space yet. What is the best way to modify PPO to support dict with a PyG based policy network in PPO?  Is there a plan to support graph neural networks in general in the future? 

Thanks
Mark Ren

**Comment by Miffyli** [comment]
There is no support for graph networks at this time and none planned (yet). I do not have much knowledge on graph neural networks, but if they can be used more-or-less as an drop-in replacement for a regular network with the addition of dictionary observations, then this should not be too difficult to support. However this would be much later in v1.2+ onwards. We plan to support Dict/Tuple observations in v1.1 (there is in fact a PR/issue regarding this already).

**Comment by haoxingren** [comment]
Thanks. I think graph network can be implemented as a special custom policy as long as observations support Dict. When will you release v1.1?

**Comment by Miffyli** [comment]
That will not be anytime soon. We will first release v1.0 inside a month or so, and after that focus on such features. Meanwhile you could represent the dict observation as one long vector and split it into appropriate chunks inside policy (e.g. obs[0] represents one thing, obs[1] represents another, etc).

**Comment by haoxingren** [comment]
thanks for the suggestion. I can start with that. Will close the issue.

**Comment by mfogelson** [comment]
@haoxingren Did you get this to work? would you be willing to share your example?

**Comment by simonefelicioni** [comment]
@haoxingren have you made it work with GNNs? How did you initialize the observation space to manage the variable number of nodes and edges in graphs? Thanks.

**Comment by haoxingren** [comment]
I just used int array as observations. part of the array is considered as the edge list, and other parts are considered as real observations. The model has to be 'parse' that.
