### ISSUE TITLE
Why would the predict method of the DQN model return an array of multiple indices for the next action?

### ISSUE THREAD

**Issue by nbro** [DLR-RM/stable-baselines3#221]
I am not yet able to reproduce this error with a simple example (given that I am not using a gym environment), but, at some point, the `predict` method is returning an array as the predicted action, while it does not return anything for the next state/observation, i.e., at some point, the following statement

```
action, _states = model.predict(next_observation)
```

returns `action = [0 1 0 0]` (whose type is `numpy.ndarray`) and `_states = None`. Why would this be the case?

I am using 

```
from stable_baselines3.dqn.dqn import DQN
from stable_baselines3.dqn.policies import MlpPolicy

model = DQN(MlpPolicy, env, verbose=1, exploration_fraction=0.1, tensorboard_log="some_folder")
model.learn(total_timesteps=10000)
```

Note that, before this happening, `model.predict` correctly returns only one index, which represents only 1 action, but `_states` is always `None` (not sure why too).

By looking at your implementation [here](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/dqn/dqn.py#L207), this should happen if `not deterministic and np.random.rand() < self.exploration_rate:`. Now, in my case, I don't set the parameter `deterministic`, whose default value is `False`, so `not deterministic` is true, so what is causing the problem is `np.random.rand() < self.exploration_rate`. The thing is: I never experienced this when I was playing with stable-baselines 2. Also, I don't understand your logic in that implementation anyway. Why would `n_batch = observation.shape[0]` and then sample multiple actions? I guess that if I set `deterministic=True`, then I will not experience this problem anymore. 

Should `deterministic` always be True after learning?

**Comment by araffin** [comment]
>Note that, before this happening, model.predict correctly returns only one index, which represents only 1 action, but _states is always None (not sure why too).

`state` refers to the hidden states for recurrent policies (cf doc) and should not be confused with the environment state, returned by `env.reset()` or `env.step()` (written `obs` for observation in stable-baselines).


>returns action = [0 1 0 0] 
> Also, I don't understand your logic in that implementation anyway. Why would n_batch = observation.shape[0] and then sample multiple actions? 

Well, it depends of the shape of the observation. It is made to work with vectorized environments (cf doc).

>Should deterministic always be True after learning?

it depends. In continuous control, it is recommended, for Atari games, as the game is deterministic too, it may lead to an infinite game (where the agent neither win, no loses, see https://twitter.com/araffin2/status/1164902485749915649).


EDIT: I see what you mean, will push a bug fix soon

**Comment by araffin** [comment]
Thanks for reporting the bug, this will be fixed in https://github.com/DLR-RM/stable-baselines3/pull/222
