### ISSUE TITLE
[Bug] arguments order error in explained_variance()

### ISSUE THREAD

**Issue by thisray** [DLR-RM/stable-baselines3#225]
Hi,

The calculation method of explained variance in the comment is: `1 - Var[y-ypred] / Var[y]`. In the scenario of value loss, I think the `y_true` is `return` and `y_pred` is `value`.

The calculation of explained variance in ppo.py:

https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/ppo/ppo.py#L223
```
explained_var = explained_variance(self.rollout_buffer.returns.flatten(), self.rollout_buffer.values.flatten())
```

But the arguments in this function:

https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/utils.py#L42
```
def explained_variance(y_pred: np.ndarray, y_true: np.ndarray) -> np.ndarray:
```

It seems the order is not right?

thanks!

**Comment by Miffyli** [comment]
You are right, it seems to be the wrong way around. @araffin Can you double-confirm this, as you seem to be one who touched the code last? 

In case this is a bug, we need to calls to `explained_variance` for typos like this.

**Comment by araffin** [comment]
Hello,
nice catch ;) (the good news is that this variable is only used for debugging purposes)

**Comment by thisray** [comment]
Yes, it just a little bug. Many thanks for this library, it is very useful and make me learn a lot!

**Comment by araffin** [comment]
>Yes, it just a little bug. Many thanks for this library, it is very useful and make me learn a lot!

I edited my message a bit late, but we would be happy if you could submit a PR that solves this issue ;)
