### ISSUE TITLE
Duplicated parameter in EvalCallback

### ISSUE THREAD

**Issue by tfederico** [DLR-RM/stable-baselines3#233]
### 📚 Documentation

In the documentation of `EvalCallback` there is a duplicate parameter `deterministic`, with a copy of the description of `render`

### Checklist

- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by tfederico** [comment]
I think it's fetching the extra parameter from [https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/callbacks.py](here)

**Comment by araffin** [comment]
Nice catch ;)
I will fix that in #230 (see https://github.com/DLR-RM/stable-baselines3/pull/230/commits/79aea6dfe55c9592ab7443cfa1688f99ab7f49fe)
