### ISSUE TITLE
OverflowError : cannot serialize a bytes object larger than 4 GiB when saving replay buffer

### ISSUE THREAD

**Issue by hn2** [DLR-RM/stable-baselines3#238]
python --version
Python 3.6.11
torch 1.6.0+cu101

The solution is probably this:
Use pickle with protocol=4, e.g.,
pickle.dump((X,c), f, protocol=4)

**Comment by araffin** [comment]
Hello,

Thanks for reporting the bug, this seems in fact to be an issue until python 3.8.
I will push a fix soon ;)
