### ISSUE TITLE
SB3 doesn't write tensorboard logs

### ISSUE THREAD

**Issue by hn2** [DLR-RM/stable-baselines3#241]
I'm not sure if it is a bug or not, however, when training a model, no tensorboard logs are written. Possibly it is due to my python envrionment (below).  I do see model running (verbose=1) and it is also writing monitor csv file to the same directory defined as tensorboard directory.

Python 3.6.11

torch                              1.6.0+cu101

also installed:

tensorboard                        1.14.0
tensorboardX                       2.0
tensorflow                         1.14.0
tensorflow-estimator               1.14.0
tensorflow-gpu                     1.14.0

**Comment by araffin** [comment]
Hello,
**Please fill up the issue template COMPLETELY**.
If we have an issue template, it is not for it to be ignored ;)

@hn2 you were banned from SB2 issues for that exact same reason (https://github.com/hill-a/stable-baselines/issues/380 and https://github.com/hill-a/stable-baselines/issues?q=is%3Aissue+author%3Ahn2+is%3Aclosed, opening many issues without following the rules and filling up the issue template), this your **first and LAST warning** on this repo.

**Comment by araffin** [comment]
closing in favor of https://github.com/DLR-RM/stable-baselines3/issues/242
