### ISSUE TITLE
[Question] how custom monitor and custom tensorboard callback behave under multiprocessing mode

### ISSUE THREAD

**Issue by zhaopansong** [DLR-RM/stable-baselines3#247]
Suppose my game is turn-based with 200 rounds for each day (then env.reset will be called to reset env of another day), I would like to monitor/log sum of rewards for each day of N independent environments using multiprocessing.
How are current  custom monitors and tensorboard callbacks fit in multiprocessing mode?

**Comment by Miffyli** [comment]
Monitor files work fine and dandy with parallel environments as long as you assign each of them to write to a different Monitor file, see [`make_vec_env`](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/env_util.py#L89) for this. @araffin can you comment on the state of tensorboards?

**Comment by zhaopansong** [comment]
> Monitor files work fine and dandy with parallel environments as long as you assign each of them to write to a different Monitor file, see [`make_vec_env`](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/env_util.py#L89) for this. 
I read the linked above. It seems in multiprocessing mode, each env will use a same monitor file.
And in monitor.step(), if env is a vec_env and self.reward is an array of many envs, ep_rew = sum(self.rewards) would add reward of same step  instead of trajactory of different environments.
[https://github.com/DLR-RM/stable-baselines3/blob/723b341c61d168e1460399592d5cebd4c6ef3cc8/stable_baselines3/common/monitor.py#L17](url)

**Comment by Miffyli** [comment]
No, `make_vec_env` will create separate Monitor files (one per parallel environment), regardless of the underlying parallelization technique (i.e. works with `subprocvecenv`). It separates the log files by the parallel environment index.

**Comment by araffin** [comment]
> @araffin can you comment on the state of tensorboards?

tensorboard only report aggregated stats.
You would to create a custom callback if you want to have one graph per environment.
