### ISSUE TITLE
Running PPO with default HP fails on Pendulum [question]

### ISSUE THREAD

**Issue by MoMe36** [DLR-RM/stable-baselines3#25]
Hello, 

I am running a PPO agent on usual Gym environments (Pendulum and BipedalWalker-v3) and I am surprised to observe that the rewards doesn't exceed -1000 even after 5e5 timesteps. I am running the agent with default hyperparameters, having just copied-pasted from the readthedocs examples. 
Here's said code: 
```

from stable_baselines3 import PPO
from stable_baselines3.ppo import MlpPolicy
from stable_baselines3.common.cmd_util import make_vec_env


if __name__ == '__main__': 
    # Parallel environments
    env = make_vec_env('Pendulum-v0', n_envs=6)

    model = PPO(MlpPolicy, env, verbose=1)
    model.learn(total_timesteps=500000)
    model.save("ppo_cartpole")

    del model # remove to demonstrate saving and loading

    model = PPO.load("ppo_cartpole")

    obs = env.reset()
    while True:
        action, _states = model.predict(obs)
        obs, rewards, dones, info = env.step(action)
        env.render()
    env.close()
``` 
Final results: 
```
---------------------------------------
| approx_kl            | 0.0011709424 |
| clip_fraction        | 0            |
| clip_range           | 0.2          |
| entropy_loss         | -1.07        |
| ep_len_mean          | 200          |
| ep_rew_mean          | -1.06e+03    |
| explained_variance   | -1.57        |
| fps                  | 1270         |
| iterations           | 41           |
| learning_rate        | 0.0003       |
| n_updates            | 400          |
| policy_gradient_loss | 0.000337     |
| std                  | 0.709        |
| time_elapsed         | 396          |
| total timesteps      | 503808       |
| value_loss           | 4.19e+03     |
---------------------------------------

```

Am I doing something wrong ? 
Thanks ! ((:

**Comment by araffin** [comment]
Hello,
As mentioned in the [documentation](https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#general-advice-when-using-reinforcement-learning):
"don’t expect the default ones to work on any environment."
In fact, `Pendulum-v0` is easy to solve with SAC/TD3 but requires some tuning for PPO.

You can take a look at the ones found in the [rl zoo](https://github.com/DLR-RM/rl-baselines3-zoo) (again as mentioned in the documentation).

**Comment by MoMe36** [comment]
Indeed, I must have missed it. Sorry for that, TD3 does work like a charm. 
Closing the issue, thanks for your help!
