### ISSUE TITLE
[Question] How is logger initiated and how to use it

### ISSUE THREAD

**Issue by zhaopansong** [DLR-RM/stable-baselines3#250]
From codes of Logger and PPO, I could not find where logger is initiated under PPO. It seems logger is a combination of many kinds of logging system(tensorboard, csv...).In ppo, there is code like "logger.record("train/loss", loss.item())"
However in the docs, chapter of tensorboard integration, in the example of logging more values, you use code like "self.logger.record('random_value', value)".
It confuse me about the relationship between logger object and ppo object. Is logger a global variable initiated when import logger, or  a attribute of model?
Could you clearify the way to use logger? 
Thank you

**Comment by araffin** [comment]
>From codes of Logger and PPO, I could not find where logger is initiated under PPO

The logger is initialized here: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/utils.py#L169
`self.logger` in the callback is just a reference to the same `logger` object used in PPO.
We have a plan to make things a little bit cleaner in https://github.com/DLR-RM/stable-baselines3/issues/109

**Comment by zhaopansong** [comment]
> The logger is initialized here: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/utils.py#L169
Thank you for reply.
However could u explain more about how the logger is initiated?
Based on my understanding, in def configure_logger(),
 when it runs to this line `logger.configure(save_path,` `["tensorboard"])`
the logger object hasn't been created yet, so how can you call its attribute function?
Is it because you already initiated a logger object as global variable when importing the logger module?
The syntax here is new to me.

**Comment by araffin** [comment]
>However could u explain more about how the logger is initiated?
Based on my understanding, in def configure_logger(),

I see, here `logger` is the module.
See below:

```python
# Instead of 
from stable_baselines3.common.logger import configure
configure(...)
# we do:
from stable_baselines.common import logger  # logger is the module not an object
logger.configure(...)
```

**Comment by zhaopansong** [comment]
Ok, then in logger.confogire(...), this line Logger.CURRENT = Logger(folder=folder, output_formats=output_formats)  creates a Logger object. How can  this logger object be accessible in model in a similar way as global variable ? Is it because  the loggre object is is a singleton and already exist when importing the module logger?

**Comment by araffin** [comment]
>How can this logger object be accessible in model in a similar way as global variable ? Is it because the loggre object is is a singleton and already exist when importing the module logger?

more or less yes. And then we pass the reference of that object to the callback so it can access it. It works but it is not super clean, that's why we would to improve it in #109.

**Comment by zhaopansong** [comment]
Thank you very much, leanred a lot
