### ISSUE TITLE
[Question] SAC Tensorboard Logging Reward

### ISSUE THREAD

**Issue by Max-Fu** [DLR-RM/stable-baselines3#251]
Hi! I am trying to run naive SAC with tensorboard. However, it doesn't show any information with regards to average reward in the tensorboard. A minimal example is shown below. Does reward logging only work for online policies? 

```
import gym
import numpy as np
from stable_baselines3 import SAC
from stable_baselines3.sac import MlpPolicy, CnnPolicy
import os 

env = gym.make("CarRacing-v0")
policy_kwargs = dict(net_arch=dict(pi=[64, 64], qf=[400, 300]))
exp_name = "car-racing"
tensorboard_log = os.path.join("./logs", exp_name)

model = SAC(CnnPolicy, env, verbose=1, policy_kwargs=policy_kwargs, tensorboard_log=tensorboard_log)
model.learn(total_timesteps=50000, log_interval=4)
model.save(exp_name)
```

The logs do show up in ./logs, however, it only includes the losses and fps, but no ep_len_mean and ep_rew_mean as shown in the [tutorial](https://stable-baselines3.readthedocs.io/en/master/_images/Tensorboard_example.png).

**Comment by araffin** [comment]
Hello,
Please don't forget the issue checklist next time ;)

This is a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/232 .

To solve your issue, use a `Monitor` wrapper (as mentioned in the doc) or install the master version of Stable-Baselines3 (cf doc):
```
pip install git+https://github.com/DLR-RM/stable-baselines3
```

Note: `pip install stable-baselines3==0.11.0a1` should work as well

**Comment by Max-Fu** [comment]
Sorry. I didn't see that issue when I was searching for this problem :( Thanks for the help. Closing the question.
