### ISSUE TITLE
[Bug] self.logger in custom callback behave as module instead of object

### ISSUE THREAD

**Issue by zhaopansong** [DLR-RM/stable-baselines3#252]
### 🐛 Bug

I copy the example in docs, in chapter of custome callback function, modify the function of def _on_rollout_end(self), try to write values into tensorboard. However, after running, it works fine but I cannot delete the tensorboard file from pycharm. I guess it is because the filewriter is still occupying the tensorboard file. So I added  one line "self.logger.close()". Then an error shows out,saying 
  File "<ipython-input-33-40cee20834ac>", line 46, in _on_rollout_end
    self.logger.close()
AttributeError: module 'stable_baselines3.common.logger' has no attribute 'close' 
Based on my understanding of docs, the self.logger should be an objectof logger class, and therefore has attribute of close()

`
class CustomCallback(BaseCallback):
    """
    A custom callback that derives from ``BaseCallback``.

    :param verbose: (int) Verbosity level 0: not output 1: info 2: debug
    """
    def __init__(self, verbose=0):
        super(CustomCallback, self).__init__(verbose)
  

    def _on_training_start(self) -> None:
        pass

    def _on_rollout_start(self) -> None:

        pass

    def _on_step(self) -> bool:
        return True

    def _on_rollout_end(self) -> None:
        this_roll_episode_rewards=self.model.rollout_buffer.rewards.sum(axis=0)
        print(self.num_timesteps)
        for i in range(self.model.n_envs):
            num_step=self.num_timesteps-i*self.model.n_steps
            print(num_step)
            self.logger.record('episode_reward',this_roll_episode_rewards[i])
            self.logger.dump(num_step)
        pass
        self.logger.close()

    def _on_training_end(self) -> None:

        pass
mycallback=CustomCallback()
model1 =PPO(MlpPolicy, vec_env, verbose=1,gamma=0.5,n_steps=200,learning_rate=0.0001,tensorboard_log ='./test/')
model1.learn(total_timesteps=1000,callback=mycallback)
`

**Comment by araffin** [comment]
Hello,

sorry for misguiding you in #250 .
The `self.logger` in the callback is the module (it was the logger object in a previous version, hence my first answer).
If you want to access the `Logger` object, you just need to do `self.logger.Logger.CURRENT`.
I recommend you to take a look at `common/logger.py` to understand what's happening and why `self.logger.record()` works ;)


Also please use [Markdown codeblock](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks)  correctly next time ;) (cf Github doc and issue template).
