### ISSUE TITLE
Action values become a negative float value after 100 total timestep

### ISSUE THREAD

**Issue by cosmir17** [DLR-RM/stable-baselines3#253]
### 🐛 Bug
Action values become a negative float value after 100 total timestep

### To Reproduce
My env file
```
class NQEnv(gym.Env):
    metadata = {'render.modes': ['console']}
    def __init__(self):
        self.action_space = spaces.Discrete(6)
        self.observation_space = spaces.Box(low=0, high=255, shape=(70, 70, 1), dtype=np.uint8)
...
actions = ['left_arrow', 'right_arrow', 'up_arrow', 'down_arrow', 'spacebar', 'nothing']
        try:
            print("action: " + str(actions[action]) + "  which stage: " + str(self._stage))
...
```

main.py
```
from stable_baselines3 import SAC
from stable_baselines3.common.cmd_util import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.sac.policies import CnnPolicy
..

env = DummyVecEnv([lambda: NQEnv()])
model = SAC(CnnPolicy, env, verbose=2).learn(total_timesteps=5000, log_interval=1)
```

I run `main.py` and it works fine until the total timesteps hit 100 (3 minutes?). Action values become a negative float value afterwards as shown on the following screenshots.
![Screenshot 2020-12-04 at 23 58 23](https://user-images.githubusercontent.com/2845708/101226629-fc3b5400-368c-11eb-8cae-b97018c2f89f.png)

![Screenshot 2020-12-04 at 23 41 34](https://user-images.githubusercontent.com/2845708/101226633-ffcedb00-368c-11eb-98cf-3614034a15fd.png)

### Expected behavior
Action values continue to be integer

### System Info

Describe the characteristic of your environment:
-macos big sur
-python 3.8.6
-tf-nightly:  2.5.0.dev20201204
-numpy : 1.19.4
-stable-baselines3:       0.10.0
-gym                     0.17.3

`pip check` doesn't show any broken dependencies.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Miffyli** [comment]
Hey. SAC does not support `Discrete` action spaces (see [docs](https://stable-baselines3.readthedocs.io/en/master/modules/sac.html#can-i-use)). I recommend trying out either DQN, A2C or PPO for such environments.

However I think there is a related enhancement we should add: users should be warned about invalid action spaces with an appropriate warning rather than obscure errors like this. I tried running similar code with CartPole-v0, and it only crashes to an AssertionError inside environment of SAC's actions (continuous) not being part of action space.

**Comment by cosmir17** [comment]
Hi @Miffyli, Thank you for your kind reply. I have just tried A2C & PPO and it's working fine.
I am grateful to people(including you) developing/maintaining this library. Wish you a good day.

P.S. Do you want me to close this page? since it's not a bug.

**Comment by Miffyli** [comment]
Thanks for the kind words! These help us stay motivated to contribute projects like this :) 

Lets keep this issue open until @araffin comments on my comment above about possible enhancement.

**Comment by cosmir17** [comment]
@Miffyli, I am super excited to use this library!

**Comment by cosmir17** [comment]
@Miffyli btw, when I tried PPO, it seemed not logging. Is it an expected or known behaviour?

**Comment by Miffyli** [comment]
@cosmir17 All algorithms should log/print out statistics during training with `verbose=2`, however in some algorithms this takes longer than in others, so I suggest you let it run for a longer while and/or adjust the parameters that suit your task better.

**Comment by cosmir17** [comment]
When I used A2C, I saw Stable-Baselines logs every step (log_interval=1). 4(?) variables are shown.
When I used PPO, it was like every 100 step. 8(?) variables were shown.

Closing this issue.
