### ISSUE TITLE
RL Baselines3 Zoo custom env training and hyperparameter optimization

### ISSUE THREAD

**Issue by hn2** [DLR-RM/stable-baselines3#259]
I am reading the docs here:
https://stable-baselines3.readthedocs.io/en/master/guide/rl_zoo.html
and here:
https://github.com/DLR-RM/stable-baselines3/blob/master/docs/guide/rl_zoo.rst
The examples are for standard registered envs.
Is it possible to train and optimize custom env with RL Baselines3 Zoo?
Is it possible to pass parameters?
If yes, can you post a concrete example?

**Comment by araffin** [comment]
Hello,
please open such issue in the rl zoo.

> Is it possible to train and optimize custom env with RL Baselines3 Zoo?

yes.
Take a look at https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/import_envs.py
that's where we import envs for registration.

> Is it possible to pass parameters?

what do you mean?

**Comment by hn2** [comment]
My custom env accepts ~12 parameters.
How to pass them?
How to use the import_envs utility precisely?

**Comment by araffin** [comment]
> How to pass them?

this is in the README: `--env-kwargs`.

> How to use the import_envs utility precisely?

Please read more about gym env registration (we have links in our doc).
You need to format your custom env as a python package that registers the env when it is imported.
so you need to slightly modify the `import_envs.py` to import your package that will register the custom env.

**Comment by hn2** [comment]
--env-kwargs
How to train and optimize programmatically from a python script(not command line)?

**Comment by araffin** [comment]
well, I would recommend you to study the code of the RL-Zoo...
we have a simplified version here: https://github.com/optuna/optuna/blob/master/examples/rl/sb3_simple.py

**Comment by hn2** [comment]
I will study the code. 
At first glance, I see that it does not save the results only prints them on screen?

**Comment by araffin** [comment]
> At first glance, I see that it does not save the results only prints them on screen?

It does.

I will close this issue then as all the original questions were answered.
