### ISSUE TITLE
Support Divergence-Augmented Policy Optimization?

### ISSUE THREAD

**Issue by szrlee** [DLR-RM/stable-baselines3#26]
Divergence-Augmented Policy Optimization
https://papers.nips.cc/paper/8842-divergence-augmented-policy-optimization

**Comment by araffin** [comment]
Hello,
could you please motivate your suggestion? (context, weighting pros and cons, ...)

**Comment by araffin** [comment]
related to https://github.com/thu-ml/tianshou/issues/17
