### ISSUE TITLE
Log Print Frequency?

### ISSUE THREAD

**Issue by E666GT** [DLR-RM/stable-baselines3#260]
Hi SB3 team,

Is there a way to control the log print frequency? I may want to see the log printout (verbose=1) more frequently.

Thanks

**Comment by araffin** [comment]
Hello,
this is called `log_interval` in the `learn()` method (cf doc) ;)

**Comment by E666GT** [comment]
> Hello,
> this is called `log_interval` in the `learn()` method (cf doc) ;)

Thanks for the quick reply.
