### ISSUE TITLE
[Feature Request] request title

### ISSUE THREAD

**Issue by hn2** [DLR-RM/stable-baselines3#262]
Is it possible to create MuZero implementation for stable baselines? Are you planning to?

**Comment by araffin** [comment]
Hello,

Despite multiple warnings and a first sanction on the SB2 repo, you continued to forget the rules for opening issues (filling the issues template completely).
As a result, you will now be blocked on that repo too (in the meantime, any new opened issue will be closed).

Motivation:
- https://github.com/DLR-RM/stable-baselines3/issues/241#issuecomment-732046857 (I explicitly warned you here for the last time)
- https://github.com/hill-a/stable-baselines/issues/380 (explanation of the initial ban)

>Is it possible to create MuZero implementation for stable baselines? Are you planning to?

no as we are focusing on model-free RL. But could be an addition to the SB3 contrib repo.
