### ISSUE TITLE
[Bug] Silent NaNs in PPO Loss Calculation if n_steps=1 and n_envs=1 

### ISSUE THREAD

**Issue by decodyng** [DLR-RM/stable-baselines3#265]
### 🐛 Bug

This is somewhere between a bug and a request for more informative errors: 

When n_steps and n_envs are both set to 1, the batch returned by a rollout buffer [here](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/ppo/ppo.py#L160) will be of length 1. This will make the `advantages` calculation return `nan` values, since the normalization step involves calculating the standard deviation of advantages, which is undefined for a single element.

I recognize that this small of a setting is definitely an edge case (I ran into it during testing, when we were setting all values quite low for speed reasons), so I'm not sure it makes sense to have logic for this case, but at minimum, I think it would be beneficial to have some kind of explicit warning that checks if `actions` or `advantages` have a single element, so that there's a clear indication of the source of the issue, rather than having to follow a breadcrumb trail of `nan`s from some higher abstraction level of code

### To Reproduce

```import gym
from stable_baselines3 import PPO

env = gym.make('CartPole-v1')
model = PPO('MlpPolicy', env, verbose=1, n_steps=1)
model.learn(total_timesteps=10)
```
This will fail with an unclear error : 
```
RuntimeError: invalid multinomial distribution (encountering probability entry < 0)
```
If you put a debugger or insert logging statements at ppo.py:170, you'll be able to see that (1) `len(advantages) = 1` and consequently (2) `advantages.std() = nan`, which first arises as a visible bug when you try to collect an on-policy rollout after your first training step, since the `nan` values in loss propagate into `nan` parameter values. 

### Expected behavior

Either (1) explicit support for training on effective batches of size 1, or (2) a clearer and earlier error when you attempt to construct an algorithm object with `n_steps=1` and `n_envs=1`, informing the user that the case isn't supported.

### System Info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...): Cloned from fork of current master, installed via `pip` 
 * GPU models and configuration: N/A 
 * Python version: 3.7.0 
 * PyTorch version: 1.7.1 
 * Gym version: 0.17.3
 * Versions of any other relevant libraries: N/A

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,
nice catch =)

Even though this case is unlikely to happen (using PPO with `n_steps=1` and `n_envs=1`), I agree we should have a better error message, an assert should do the trick ;)

We would happy if you could submit a PR that solves this issue ;)

**Comment by decodyng** [comment]
Sound good; I already have a fork with that basic assert, and would be happy to merge that in. 

One subtler thing that I'd be curious for the maintainers' perspective on: my impression from the testing I did in uncovering this bug is that the effective batch size used in an update is `min(batch_size, n_envs*n_steps)`. 

First off, I'm curious if that is also your understanding of how you expect things to work. Secondly, if that impression is correct, would the maintainers be open to also adding a Warning if `n_envs*n_steps` is less than a specified batch size, since that might mean the intended batch size isn't actually being used for updates?

**Comment by araffin** [comment]
>One subtler thing that I'd be curious for the maintainers' perspective on: my impression from the testing I did in uncovering this bug is that the effective batch size used in an update is min(batch_size, n_envs*n_steps).

What makes you think that?
The only thing that can happen when using the rollout buffer with PPO, is that the last minibatch will be truncated (so the last minibatch size will be:
```python
total_transitions = n_envs * n_steps
n_minibatches = total_transitions // batch_size # number of minibatches with correct batch size

# the last minibatch size will be smaller in that case
if total_transitions - n_minibatches * batch_size > 0:
    last_minibatch_size = total_transitions - n_minibatches * batch_size
```

but it would probably be good to add a warning too.

**Comment by decodyng** [comment]
Here's an example demonstrating the thing I think I'm seeing here: 

```
import gym
from stable_baselines3 import PPO

env = gym.make('CartPole-v1')
model = PPO('MlpPolicy', env, verbose=1, n_steps=14, batch_size=16)
model.learn(total_timesteps=100)
```

If I put a debug statement at ppo.py:183 to print `len(advantages)` (which I _think_ is the effective batch size, since the loss is calculated and gradient update is done within that loop), I'm seeing that debug line always return a value of 14 (=14 steps*1 env) rather than 16 (the specified batch size), for all batches, rather than just the final batch.

**Comment by decodyng** [comment]
Ah, reading over your comment again, I now think we're saying the same thing here, except you're framing it as the last minibatch getting truncated, and in the situation I'm describing, you can't pull even a single minibatch from the amount of data present in `n_steps*n_envs`, so all batches are truncated

**Comment by decodyng** [comment]
If I set the `batch_size` to instead be 8, I see what you're referring to (where the effective batch size alternates between 8 and 6, to add up to 14)

**Comment by decodyng** [comment]
Given this, I could see two opportunities to warn: 
1. The thing I was thinking of, where you've set your steps and envs poorly such that every batch will end up truncated 
2. Warning when `n_steps*n_envs % batch_size !=0` in general, and just noting that the final batch in each buffer will end up truncated. This seems less important than (1) especially when the number of batches per buffer is large, but still potentially worth noting. (Obviously (1) is a subset situation of (2), but I think it'd be worth explicitly calling out since I think it's a larger problem when all batches will be truncated) 


We could also try to merge these into some kind of aggregated error, where we pre-calculate how often a truncated batch will happen, and explicitly say "k of every K batches will be truncated to a value of x", which might nicely cover both cases, and hopefully give people pause when they see "10 of every 10 batches will be truncated," or something like that 


This is a situation that, I think if you understand all the relevant parameters well, you hopefully wouldn't run into, but I think the nuance of how envs, steps, timesteps, and batch_size work together here is subtle enough that it's worth covering cases like these.

**Comment by araffin** [comment]
Just warn at model creation that the last minibatch size will have a size smaller than `batch_size` (and we can print those two) because `n_envs * n_steps` is not a multiple of `batch_size`

**Comment by Dylan-Kerler** [comment]
I think this should throw an error not a warning. Took quite some time to debug this and find out what the issue was when combining the PPO model with bayesian optimisation.

**Comment by Miffyli** [comment]
@Dylan-Kerler There should be an error if `n_envs * n_steps = 1`, and a warning if it is smaller than batch-size.

**Comment by externalsupplierstaff** [comment]
I'm getting
```bash
UserWarning: You have specified a mini-batch size of 80, but because the `RolloutBuffer` is of size `n_steps * n_envs = 20`, after every 0 untruncated mini-batches, there will be a truncated mini-batch of size 20
We recommend using a `batch_size` that is a multiple of `n_steps * n_envs`.
Info: (n_steps=20 and n_envs=1)
```
but to the best of my knowledge `batch_size=80` is a multiple of `n_steps*n_envs=20`.
Using `n_envs=80` and `batch_size=20` gives no warning. Am I confused with the definition of multiple? Should it be "factor"?

**Comment by araffin** [comment]
>Am I confused with the definition of multiple? Should it be "factor"?

yes, you should have `n_steps * n_envs = k * batch_size` (we would appreciate a PR that solves this typo and the issue https://github.com/DLR-RM/stable-baselines3/issues/440)

**Comment by hughperkins** [comment]
the issue with n_env * n_step == 1 should be fixed now by https://github.com/DLR-RM/stable-baselines3/pull/1028
