### ISSUE TITLE
[Feature Request] Add image to tensorboard

### ISSUE THREAD

**Issue by zampanteymedio** [DLR-RM/stable-baselines3#266]
### 🚀 Feature

Add image logging support for logging to TensorBoard.

### Motivation

There is currently a way to log video into tensorBoard. Nevertheless, many environments need to log images, not videos.

### Pitch

Log images in TensorBoard,

### Alternatives

Creating and storing the images directly on my machine instead of tensorboard.
Creating videos of 1 frame.

### Additional context

Update logger module and implement images in TensorBoardOutputFormat class.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by zampanteymedio** [comment]
I'm happy to implement it myself and send a Pull Request if you consider that this feature is interesting for you.

**Comment by araffin** [comment]
Hello,
sounds like a reasonable feature, please go ahead with the PR ;)
