### ISSUE TITLE
CNN policy needs a normalize preprocess?

### ISSUE THREAD

**Issue by E666GT** [DLR-RM/stable-baselines3#268]
Dear SB3 Support Team,

Thanks for your great work, and I may have a question about your implementation.

If I try a custom CNN, in [sb3 doc, custom policy](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html).

**Do I need to provide the normalized image?**

I'm now giving the image with shape: 
spaces.Box(**0, 255**, shape=(3,128,128), dtype='float32')
and now, Im wondering if it needs preprocess by myself to feed img to the NN like 
(**-1,1,** shape=(3,128,128), dtype='float32')

**Comment by E666GT** [comment]
I have made a experiment to see. Now it seems to be necessary to write a preprocess, like transform.Normalize((128,128,128),(128,128,128)) to make it better to learn.

Thanks, It is solved. If you have any comment , please. If not, you may close it.

**Comment by E666GT** [comment]
btw, I guess in the SB2, you have the auto normalize for the image input?

**Comment by araffin** [comment]
Hello,
Images are normalized by default when using the `CnnPolicy`, see https://stable-baselines3.readthedocs.io/en/master/guide/custom_env.html ( `normalize_images` is set to true in each policy, for instance https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html#ppo-policies).

The preprocessing code is here: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/preprocessing.py#L77

**Comment by E666GT** [comment]
Thanks, I got it.
there is an API checking, and my image just doesn't pass this API. I haven't set the Image with Uint8
is_image_space

**Comment by araffin** [comment]
>there is an API checking, and my image just doesn't pass this API. I haven't set the Image with Uint8
is_image_space

we have an env checker for those kind of details ;) (cf doc)

**Comment by E666GT** [comment]
> > there is an API checking, and my image just doesn't pass this API. I haven't set the Image with Uint8
> > is_image_space
> 
> we have an env checker for those kind of details ;) (cf doc)

Really NICE! You've considered everything detailed
