### ISSUE TITLE
[Question] AttributeError 'Box' object has no attribute 'n'

### ISSUE THREAD

**Issue by AptX395** [DLR-RM/stable-baselines3#272]
### Question

I'm running a simple code follow the documentation of Stable-Baselines3. But I meet an error. I've searched this error, and I still don't know how to solve it.

The following is a screenshot of the specific situation.

What caused it?

![](https://i.loli.net/2020/12/25/8MIp2WmFPCXu63i.png)

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
DQN does not support continuous action spaces, and would not work with `Pendulum-v0` environment. See docs on supported environments.

**Comment by AptX395** [comment]
> DQN does not support continuous action spaces, and would not work with `Pendulum-v0` environment. See docs on supported environments.

Thanks for your reply!

My code is exactly the same as the sample code in the document, but it can't work properly, which really confuses me.

The link of example is https://stable-baselines3.readthedocs.io/en/master/modules/dqn.html .

![](https://i.loli.net/2020/12/26/xHl7PgZpi5u9TvL.png)

Thank you for your help!

**Comment by Miffyli** [comment]
Ooh good catch! That indeed is wrong and should be `CartPole-v0`, not `Pendulum-v0`. A PR that fixes this issue would be welcomed :)

**Comment by AptX395** [comment]
> Ooh good catch! That indeed is wrong and should be `CartPole-v0`, not `Pendulum-v0`. A PR that fixes this issue would be welcomed :)

Haha, I'll commit a PR. 👍
