### ISSUE TITLE
[Question] preload replay buffer

### ISSUE THREAD

**Issue by RafieeAshkan** [DLR-RM/stable-baselines3#278]
Hi
I am using SAC for controlling motion of a ship. My understanding is that I can use results with other controller e.g PID controller to help to make SAC learn faster.

The way I implemented this is, as follows:

```
model = SAC(
            MlpPolicy,
            env,
            verbose=1,
            learning_rate=lr,
            buffer_size=buffer_size,
            batch_size=batch_size,
            gradient_steps=1,
            learning_starts=int(Nsteps * RLsets["exploration_episodes"]),
            tau=1.0e-2,
            gamma=0.99,
            seed=random_seed,
            use_sde=True,
            use_sde_at_warmup=True,
            policy_kwargs={"net_arch": NetLayers,
                           "activation_fn": torch.nn.ReLU,
                           "log_std_init": -1., },
        )

# get results of PID controller
motions, actions = get_from_simulation(sim_PID)
rewards = compute_reward(motions)
for step in motions:
    model.replay_buffer.observations[step] = motions[step]
    model.replay_buffer.actions[step] = actions[step]
    model.replay_buffer.rewards[step] = rewards[step]

model.learn( total_timesteps=int(time_steps), log_interval=10, callback=callback, )
```

I was wondering if this is the correct way or there is a better way to achieve this?

**Comment by Miffyli** [comment]
You need to use the `add` function of replay buffers to add samples. See [this](https://github.com/DLR-RM/stable-baselines3/blob/06498e8be71b9c8aee38226176dbd28443afbb4f/stable_baselines3/common/off_policy_algorithm.py#L439) and [function definition](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/buffers.py#L204). For your code you only need to replace stuff inside the `for step...` loop.

Do note that the benefit from doing this is not guaranteed and you probably need to experiment with different setups before it provides help.

**Comment by RafieeAshkan** [comment]
Thanks for the helpful comment. Can you elaborate on why the benefit is not guaranteed. Would not this essentially mean a "expert exploration phase" rather than purely random exploration? Therefore, intuitively this should provide more stable behavior of the agent!

**Comment by Miffyli** [comment]
The idea is sound and I have seen it being used in other works, so there is a good chance it will help :). However in RL many things that "intuitively" sound good do not work out too well for one reason or another, and usually there are settings that require tuning to get it to work. But, it is worth a shot!

You may close this issue if there are no further questions.

**Comment by RafieeAshkan** [comment]
Many thanks for very helpful comments.

**Comment by araffin** [comment]
To complement the answer, you may also take a look at all the "Offline RL" litterature, so learning from a fixed dataset (that may come from an expert controller).

For instance, in the [AWAC](https://arxiv.org/abs/2006.09359) paper, they show that pre-training with behavior cloning (i.e. using expert trajectories and then continue training) does not necessary help.

A good overview of the challenges of offline algorithms like SAC with such data can be found in the [BQC](https://arxiv.org/abs/1812.02900) paper.

To get started: https://github.com/takuseno/d3rlpy/ 
(there is a SB3 wrapper in that repo)

**Comment by RafieeAshkan** [comment]
@araffin Many thanks for the comments and links to the papers and repo. Really appreciate it!
