### ISSUE TITLE
[Question] Training DQN in Atari Env occupy multiple threads 

### ISSUE THREAD

**Issue by PaladinEE15** [DLR-RM/stable-baselines3#283]
Training DQN in atari env will occupy 9-10 threads, is it a normal phenomenon?
(Platform： Nvidia Titan XP + Xeon E5-2630 v4)

**Comment by araffin** [comment]
Hello,
this is normal, PyTorch is using threads to parallelize matrix computation.
You can change that using:
- `th.set_num_threads()` see [doc](https://pytorch.org/docs/stable/generated/torch.set_num_threads.html) (and optionally `th.set_num_interop_threads()`)
- `export OMP_NUM_THREADS=1` (to set [OpenMP](https://scc.ustc.edu.cn/zlsc/sugon/intel/mkl/mkl_userguide/GUID-B13E207A-FC51-4973-9676-B40545599272.htm) threads to 1)

**Comment by PaladinEE15** [comment]
> Hello,
> this is normal, PyTorch is using threads to parallelize matrix computation.
> You can change that using:
> 
> * `th.set_num_threads()` see [doc](https://pytorch.org/docs/stable/generated/torch.set_num_threads.html) (and optionally `th.set_num_interop_threads()`)
> * `export OMP_NUM_THREADS=1` (to set [OpenMP](https://scc.ustc.edu.cn/zlsc/sugon/intel/mkl/mkl_userguide/GUID-B13E207A-FC51-4973-9676-B40545599272.htm) threads to 1)

Thank you very much!
