### ISSUE TITLE
Expanded Custom Policy Documentation to include Off-Policy Examples

### ISSUE THREAD

**Issue by DanielDowns** [DLR-RM/stable-baselines3#285]
I'm trying to implement a Custom Policy Class for SAC, similar to [the custom PPO Actor Critic policy shown in the docs](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html). However, the ContinuousCritic is different enough from ActorCriticPolicy that building one is requiring me to go deep into the code to figure out what its looking for. An example would be very useful.

**Comment by Miffyli** [comment]
Good point! This is especially confusing as the policies you need to modify are [next to the agent code](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/sac/policies.py#L195), not in the `common` as with ActorCriticPolicy (that is, if you want to change the whole policy and not just feature extractors).

@araffin Could you do this as you are more familiar with SAC/TD3?

**Comment by araffin** [comment]
Hello,

>However, the ContinuousCritic is different enough from ActorCriticPolicy that building one is requiring me to go deep into the code to figure out what its looking for. 

I'm wondering what you want to change more than the network architecture and/or the feature extractor (both are already documented)?

**Comment by DanielDowns** [comment]
Two things I've been looking at trying:
1) Loading network weights for pi, as it seemed like it might be easier to do it in the network construction (I found I can do this through model.policy.actor.latent_pi)
2) building a multiheaded network for pi as the kwargs method doesn't seem to support this

I did end up switching to SACPolicy which was way easier to get working. I found ContinuousCritic looking at the policy file so maybe a mention of their differences would be useful?

**Comment by araffin** [comment]
>Loading network weights for pi, as it seemed like it might be easier to do it in the network construction (I found I can do this through model.policy.actor.latent_pi)

We have an example in the doc for that: https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#accessing-and-modifying-model-parameters
(and https://stable-baselines3.readthedocs.io/en/master/guide/save_format.html)

>building a multiheaded network for pi as the kwargs method doesn't seem to support this

What do you mean exactly by multihead actor network?

**Comment by DanielDowns** [comment]
I'm attempting to pre-train the model by using a network that was trained via supervised learning. The model architecture that performed best had several heads, each in charge of different outputs. I've never actually seen anyone using multiple heads in reinforcement learning but I'm hoping it will yield something interesting.

**Comment by araffin** [comment]
>'ve never actually seen anyone using multiple heads in reinforcement learning

sounds like auxiliary loss/tasks to me.


Closing this as 1) is already covered in the doc and 2) is very experimental and should not be a default example.
