### ISSUE TITLE
[Feature Request] Add Support for More Tensorboard Summary Formats (e.g. Text)

### ISSUE THREAD

**Issue by lorenz-h** [DLR-RM/stable-baselines3#286]
### 🚀 Feature

Add support for text (and potentially other formats) to TensorBoardOutputFormat. If there is some interest, I would be happy to create a PR.

### Motivation

Since torch offers a wide variety of tensorboard formats, It would make sense to offer some way of using most of these in stable baselines. In particular stable baselines should really support text to cater to the large community that is applying RL to Natural Language Processing.

### Pitch

Allowing text could be done by modifying the  TensorBoardOutputFormat.write(...) method. If we wanted to add support for more complex formats ([graphs](https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_graph), [embeddings](https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_embedding), etc.) it might be easier to just add a way for power users to directly access the underlying SummaryWriter (see alternatives below).

### Alternatives

More generally speaking it may make sense to allow users direct access to the summary writer in some cases. Right now the only way to access the writer that I have found is as follows (this is very hacky):

``` python
class Callback(BaseCallback):
  def add_text_record(self, tag: str, value: str, step: int) -> None:
     # could probably be made prettier with lambdas but there seems to be no way around iterating over the formatters.
      formatter_found = False
      for formatter in self.logger.Logger.CURRENT.output_formats:
          if isinstance(formatter, TensorBoardOutputFormat):
              formatter_found = True
              formatter.writer.add_text(tag, value, step)
              formatter.writer.flush()
  
      if not formatter_found:
          self.logger.warning("Could not log text to tensorboard. Could not find tb formatter in logger.")
```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by zampanteymedio** [comment]
Other formats could include graph representation of the agent? :-)

**Comment by araffin** [comment]
>Other formats could include graph representation of the agent? :-)

We already tried that when integrating tensorboard (see https://github.com/DLR-RM/stable-baselines3/pull/30#issuecomment-633670808) but it was not really useful.

PS: I will try to reply to the rest of the feature request later

**Comment by zampanteymedio** [comment]
I don't think that graph is thaaat bad...is there an alternative way to dive deep and make sure that the graph is how you wanted it to be?

**Comment by lorenz-h** [comment]
@araffin Are you still  interested in this? What are your thoughts on allowing power users to access the summary writer directly?

**Comment by araffin** [comment]
>@araffin Are you still interested in this? What are your thoughts on allowing power users to access the summary writer directly?

sorry for the late reply, I was quite busy after new year ... (unstacking all the github notification and also preparing v1.0 release)

>More generally speaking it may make sense to allow users direct access to the summary writer in some cases. Right now the only way to access the writer that I have found is as follows (this is very hacky):

to be honest, it is a bit hacky but it is only 6 lines of code... which could be simplified because the formatter don't change from time to time (I also think the `flush()` may not be needed, but I'm not sure):
```python
class Callback(BaseCallback):
  def _on_training_start(self):
      output_formats = self.logger.Logger.CURRENT.output_formats
      # Save reference to tensorboard formatter object
      # note: the failure case (not formatter found) is not handled here, should be done with try/except.
      self.tb_formatter = next(formatter for formatter in output_formats if isinstance(formatter, TensorBoardOutputFormat))

  def add_text_record(self, tag: str, value: str, step: int) -> None:
      self.tb_formatter.writer.add_text(tag, value, step)
      # I'm not sure if the flush is needed
      self.tb_formatter.writer.flush()
```

>Add support for text (and potentially other formats) to TensorBoardOutputFormat. If there is some interest, I would be happy to create a PR.

I see the point for adding text output (which should be added to other formatters too).
However, for other type of outputs, it seems closely related to tensorboard and quite specific (depending on the application), so I would rather update the documentation to showcase how to plot the graph using your hack ;)

**Comment by lorenz-h** [comment]
May I create a PR that adds the documentation and the text formatter?

**Comment by araffin** [comment]
Please do ;)
