### ISSUE TITLE
RLBench Environment

### ISSUE THREAD

**Issue by SamuelePolimi** [DLR-RM/stable-baselines3#289]
Describe the bug
----------------------

During the learning procedure, the log file appears to be closed, and therefore the I/O operation throws an error.

Code examples
---------------------

CODE EXAMPLE 1

```
import gym
import rlbench.gym
import numpy as np
import stable_baselines3.common.env_checker
from gym.spaces import Box
from stable_baselines3 import PPO

class CustomEnv(gym.Env):
  metadata = {'render.modes': ['human']}

  def __init__(self):
    super(CustomEnv, self).__init__()
    self.eval_env = gym.make('reach_target-state-v0')
    self.action_space = self.eval_env.action_space
    self.observation_space = self.eval_env.observation_space

  def step(self, action):
    return self.eval_env.step(action)

  def reset(self):
    return self.eval_env.reset()  # reward, done, info can't be included

  def render(self, mode='human'):
    #return self.eval_env.render(mode)
    pass

  def close (self):
    return self.eval_env.close()

env = CustomEnv()

print(stable_baselines3.common.env_checker.check_env(env))

model = PPO('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=1000)
```

CODE EXAMPLE 2

```
import gym
import rlbench.gym
import numpy as np
import stable_baselines3.common.env_checker
from gym.spaces import Box
from stable_baselines3 import PPO

env = gym.make('reach_target-state-v0')

print(stable_baselines3.common.env_checker.check_env(env))

model = PPO('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=1000)
```

```bash
Traceback (most recent call last):
  File "/home/samuele/Projects/LAMPO/try.py", line 50, in <module>
    model.learn(total_timesteps=1000)
  File "/home/samuele/miniconda3/envs/mini-rl/lib/python3.7/site-packages/stable_baselines3/ppo/ppo.py", line 264, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/home/samuele/miniconda3/envs/mini-rl/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 240, in learn
    logger.dump(step=self.num_timesteps)
  File "/home/samuele/miniconda3/envs/mini-rl/lib/python3.7/site-packages/stable_baselines3/common/logger.py", line 378, in dump
    Logger.CURRENT.dump(step)
  File "/home/samuele/miniconda3/envs/mini-rl/lib/python3.7/site-packages/stable_baselines3/common/logger.py", line 543, in dump
    _format.write(self.name_to_value, self.name_to_excluded, step)
  File "/home/samuele/miniconda3/envs/mini-rl/lib/python3.7/site-packages/stable_baselines3/common/logger.py", line 142, in write
    self.file.write("\n".join(lines) + "\n")
ValueError: I/O operation on closed file.
QMutex: destroying locked mutex
```

System Info
----------------

Describe the characteristic of your environment:
 * Miniconda. I installed RLBench following the procedures.
 * GPU GeForce RTX, Cuda version 11.0
 * Python 3.7.9
 * PyTorch 1.7.1
 * Gym 0.18.0
 * RLBEnch 1.0.7

Additional Information
-----------------------------

Other users experienced the same problem, as can be seen in [https://github.com/stepjam/RLBench/issues/103](https://github.com/stepjam/RLBench/issues/103).

Checklist
------------

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have checked my env using the env checker (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,

Please try to provide a **minimal** example to reproduce the bug.
The current examples requires to install RLBench completely, which is far from minimal...

**Comment by SamuelePolimi** [comment]
Hi, I agree with you and I am sorry for that. 
But I guess if I would be able to write the minimal example without using RLBench, I would been able to fix the bug too. 

If you want I can work on providing a minimal example with PyRep (rlbench is based on PyRep) if this can be of any help.

**Comment by araffin** [comment]
Well, that's not always the case, but I would agree here.

Looking at the traceback it seems that it comes from `HumanOutputFormat(sys.stdout)`, so the `sys.stdout` gets somehow closed by RLBench...

**Comment by araffin** [comment]
On linux, you could try that type of hack (re-opening stdout if it was closed):

```python
import sys

file_ = sys.stdout
file_.write("Hello\n")
file_.flush()
file_.close()

# Check if it is closed
if file_.closed:
    file_ = open("/dev/stdout", "w")
    file_.write("Hello\n")
    file_.flush()

```

You will need a custom version of SB3 to try it.

Search for the `HumanOutputFormat` in the logger ;)

**Comment by SamuelePolimi** [comment]
Thanks, I "solved" in this way.

**Comment by araffin** [comment]
>Thanks, I "solved" in this way.

Well, I would say that the issue really come from RLBench then... It does not make sense that a program closes `stdout`.
I will close this issue for now.
Feel free to re-open it again if you think something can be changed from SB3 side ;)
