### ISSUE TITLE
[Bug] Saved video empty 

### ISSUE THREAD

**Issue by chisarie** [DLR-RM/stable-baselines3#294]
### 🐛 Bug

Hello. 

Following this [example from the documentation](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#record-a-video), a video file is generated, but it remains empty. 

Can you also reproduce the problem? Or is it only an issue with my setup? Thank you very much for the help and for this nice library.

### To Reproduce

```python
import gym
from stable_baselines3.common.vec_env import VecVideoRecorder, DummyVecEnv

env_id = "CartPole-v1"
video_folder = "logs/videos/"
video_length = 100

env = DummyVecEnv([lambda: gym.make(env_id)])

obs = env.reset()

# Record the video starting at the first step
env = VecVideoRecorder(
    env,
    video_folder,
    record_video_trigger=lambda x: x == 0,
    video_length=video_length,
    name_prefix="random-agent-{}".format(env_id),
)

env.reset()
for _ in range(video_length + 1):
    action = [env.action_space.sample()]
    obs, _, _, _ = env.step(action)
# Save the video
env.close()

```

### Expected behavior

The video should show the agent. It is empty instead.

### System Info

 * Describe how the library was installed:
```bash 
conda create --name baselines3_env  
conda activate baselines3_env  
conda install python
pip install stable-baselines3[extra]  
pip install pybullet
```

 * Python version: 3.9.1
 * Gym version: 0.18.0

**Comment by araffin** [comment]
Hello,
this issue comes from gym apparently, see https://github.com/openai/gym/pull/2139 and https://github.com/openai/gym/issues/2145

Please upgrade to use the master version of gym ;)

**Comment by chisarie** [comment]
It worked! Thank you very much Antonin :)
