### ISSUE TITLE
Custom environment conflict with PyCuda

### ISSUE THREAD

**Issue by ivandrodri** [DLR-RM/stable-baselines3#300]
Hello, I have created a custom environment that uses pycuda for some calculations and I have the following error:

ERROR:
'''
Using cuda device
Traceback (most recent call last):
File "simulation.py", line 65, in
model = PPO('MlpPolicy', env2, verbose=1, device="cuda").learn(1)
File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/stable_baselines3/ppo/ppo.py", line 264, in learn
reset_num_timesteps=reset_num_timesteps,
File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 215, in learn
total_timesteps, eval_env, callback, eval_freq, n_eval_episodes, eval_log_path, reset_num_timesteps, tb_log_name
File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/stable_baselines3/common/base_class.py", line 356, in _setup_learn
self._last_obs = self.env.reset()
File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 61, in reset
obs = self.envs[env_idx].reset()
File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/stable_baselines3/common/monitor.py", line 86, in reset
return self.env.reset(**kwargs)
File "/home/ivan/Documents/GIT_PROJECTS/RL_obstacle_avoidance/Environment/EnvironmentPyCuda.py", line 48, in reset
func(a_gpu, block=(4,4,1))
File "/home/ivan/anaconda3/envs/MLProjects/lib/python3.6/site-packages/pycuda/driver.py", line 436, in function_call
func._set_block_shape(*block)
pycuda._driver.LogicError: cuFuncSetBlockShape failed: invalid resource handle
'''

Please find below a simple Environment test case that reproduces the mentioned error. The check_env(env, warn=True) function works perfectly fine with the Environment below but the problem appears when I try to train a PPO algorithm and it seems it is coming from the kernel launched in the reset function (the reset function kernel works perfectly fine). If I comment the pycuda part everything works. It works also if I run the algorithm on cpu, i.e. model = PPO('MlpPolicy', env, verbose=1, device="cpu").learn(1) . 

CUSTOM ENVIRONMENT TEST:

'''
import numpy as np
import pycuda
import pycuda.autoinit
import pycuda.driver as drv
from pycuda.compiler import SourceModule

import gym
from gym import spaces

##Simple Cuda Kernel
mod = SourceModule("""
global void doublify(float a)
{
int idx = threadIdx.x + threadIdx.y4;
a[idx] *= 2;
}
""")

class EnvironmentPyCuda(gym.Env):

metadata = {'render.modes': ['human']}

def __init__ (self):
    super(EnvironmentPyCuda, self).__init__()

    nActions = 3 
    self.action_space = spaces.Discrete(nActions)
    self.observation_space = spaces.Box(low=-10.0, high=10.0, shape=(8,), dtype=np.float32)

def reset(self):

    ####### If I comment the pycuda part below everything works perfectly. ######
    a = np.random.randn(4,4)
    a = a.astype(np.float32)
    a_gpu = drv.mem_alloc(a.nbytes)
    drv.memcpy_htod(a_gpu, a)

    func = mod.get_function("doublify")
    func(a_gpu, block=(4,4,1))

    a_doubled = np.empty_like(a)
    drv.memcpy_dtoh(a_doubled, a_gpu)
    print (a_doubled)
    print (a)
    ########################
    
    obsState = np.array([-1.0, -1.0, -1.0, -1.0, -1.0, 1.1, 1.2, 1.3 ]).astype(np.float32)
    return obsState

def step(self, action):
    obsState = np.array([-1.0, -1.0, -1.0, -1.0, -1.0, 1.1, 1.2, 1.3 ]).astype(np.float32)
    return obsState, 0, False, {}

def render(self, mode='human'):
    print("RENDER")

def close(self):
    pass
'''

I am training the algorithm in this way:

env = EnvironmentPyCuda()
check_env(env, warn=True)
env = make_vec_env(lambda: env, n_envs=1)

model = PPO('MlpPolicy', env, verbose=1, device="cuda").learn(1)

Thank you very much for any help!

**Comment by Miffyli** [comment]
As mentioned in the [SB2 issue](https://github.com/hill-a/stable-baselines/issues/1073), we do not offer tech support for issues that stem from outside stable-baselines. This seems a like a complication with Torch and PyCuda. Best thing I can suggest is to try using CPU for your agent with `model = PPO('MlpPolicy', env, verbose=1, device="cpu").learn(1)`.

**Comment by ivandrodri** [comment]
Hello @Miffyli , thanks for your reply. Sorry I asked it again here but from your last reply I thought that stable-baselines and stalbe-baselines3 were somehow unrelated. Anyway, I followed your suggestion and I found that you were right and the problem is related with an incompatibility between tensorflow and custom cuda kernels. So I guess that stable-baselines3 is using at some point tensorflow as this is the only external library I am using besides Gym. 

Just in case someone has the same issue, this is how I solved it:

##########################
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
from tensorflow.compat.v1.keras import backend as K

num_cores = 1

CPU = False
GPU = True

if GPU:
    num_GPU = 1
    num_CPU = 1
if CPU:
    num_CPU = 1
    num_GPU = 0

config1 = tf.ConfigProto(intra_op_parallelism_threads=num_cores,
                        inter_op_parallelism_threads=num_cores, 
                        allow_soft_placement=True,
                        device_count = {'CPU' : num_CPU,
                                                  'GPU' : num_GPU}
                       )

session = tf.Session(config=config1)
K.set_session(session)
##############################

**Comment by araffin** [comment]
Closing this as apparently unrelated to SB2/SB3 but rather Tensorflow / PyTorch issues.
