### ISSUE TITLE
Dict observation vs flattening and concatinating boxes

### ISSUE THREAD

**Issue by ErikVester** [DLR-RM/stable-baselines3#304]
Thank you @araffin, I appreciate the quick reply and help!

>for one question, it is ok but later, issues are made for that ;)

I still had one followup question so I just opened an issue for now :) 

>yes, you can flatten the observation (there is a wrapper in gym for that) but you will lose the spatial information that could be used by the CNN, and that the mlp will have to learn (which also means more parameters here).

Just to check whether I understood it correctly; Mlp always flattens the box observations right? So does this mean that when not using a CNN, flattening 2 Box observations from a Dict and concatenating them into one 1D array would not differ from somehow directly using the Dict observations with the Mlppolicy? I am still relatively new to all this, so it might be that I am missing something ;)

>In any case, you can also already use that branch if you want (see install from source guide in the documentation).

Sorry, not entirely sure if I understand correctly, but this would be the branch which would enable using the dict observations right? 

Thanks again! 

_Originally posted by @araffin in https://github.com/DLR-RM/stable-baselines3/issues/243#issuecomment-767571525_

**Comment by Miffyli** [comment]
> Just to check whether I understood it correctly; Mlp always flattens the box observations right? So does this mean that when not using a CNN, flattening 2 Box observations from a Dict and concatenating them into one 1D array would not differ from somehow directly using the Dict observations with the Mlppolicy? I am still relatively new to all this, so it might be that I am missing something ;)

What he meant is that you can use [this](https://github.com/openai/gym/blob/master/gym/wrappers/flatten_observation.py) wrapper to automatically flatten dictionary observation into one vector. You should do any array-flattening in your environment just for the sake of clarity. If you used Dict observations with this branch you could setup the 2D array as 3D one (like an image) and use CNN layers to process it, which would keep the spatial information and be much more efficient to compute.

> Sorry, not entirely sure if I understand correctly, but this would be the branch which would enable using the dict observations right?

The easiest way is to [clone the repo where the branch is](https://github.com/J-Travnik/stable-baselines3/tree/feat/dict_observations), use git to checkout the branch in question (`feat/dict_observations`) and then install that with `pip3 install -e .`.

**Comment by ErikVester** [comment]
Thank you  for the quick response and help! I really appreciate how supportive you guys are, this helps people like me getting a better understanding of this field!  I will first just try working with the new branch :)
