### ISSUE TITLE
[Question] SubprocVecEnv & running a batch calculation

### ISSUE THREAD

**Issue by jaysonfrancis** [DLR-RM/stable-baselines3#306]
Hi, I'm looking for some pointers on how to approach this. (i.e via VecEnv? or should I be doing something else).

I've got a external simulation that is best utilized when given batch jobs (i.e a list of N environment actions). 

I currently have an environment and some objective function like this.

```python

def simulate(actions):
  results = run_simulation(actions)
return results
  
class Env(gym.env):
  def step(action):
      out = simulate(action)
```

My `simulate` function can take batch of multiple `actions` & process them in parallel. This is

**Comment by araffin** [comment]
Hello,
I'm not sure what to add more than what is already in the documentation:
- [VecEnv example](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#multiprocessing-unleashing-the-power-of-vectorized-environments)
- [VecEnv doc](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html)
- [Custom Env doc](https://stable-baselines3.readthedocs.io/en/master/guide/custom_env.html)

>I've got a external simulation that is best utilized when given batch jobs (i.e a list of N environment actions).

it seems that you may need to define a custom `VecEnvWrapper` that will ignore `env.step()` and do the batch computation (and then pass the results to the underlying envs if needed)
or you can even define a custom `VecEnv`.

**Comment by jaysonfrancis** [comment]
Oops, I didn't notice I had actually submitted this yet.. Thank you, I'll look into leveraging `VecEnvWrapper`
