### ISSUE TITLE
[Question] Anyway for the Predict method to predict the esimated reward

### ISSUE THREAD

**Issue by c0x65o** [DLR-RM/stable-baselines3#308]
### Question

Is there any way to have the predict method (or another method) to have a prediction on what the reward might be with using the action that was predicted? I can see a lot of use cases for this, but couldn't find or think of a creative way to accomplish this.

### Checklist

- [X ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [X ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

>Is there any way to have the predict method (or another method) to have a prediction on what the reward might be with using the action that was predicted? 

Do you know about regression?
(and if you have access to the environment, you can access the reward computation)
If you care about final return, that's what the q-value is about (and for that I can only recommend to learn more about RL, see resources in our doc ;) )

In fact, we used such objective (predict reward given state and action) to learn a state representation in this [paper](https://arxiv.org/abs/1901.08651), with associated code: https://github.com/araffin/robotics-rl-srl

**Comment by c0x65o** [comment]
I am somewhat familiar with q-value and using QNetwork to predict QValues. I do not have access to the environment after I save, then load it. Looking at the predict method I don't see a way to get an estimated QValue (expected returns). Without access to the environment, is there a way to get this value?

**Comment by araffin** [comment]
>Without access to the environment, is there a way to get this value?

well, it depends on the algorithm you are using.
If it is SAC/TD3 for instance, you can access the Q-value function via `model.critic` (please take a look at the code for the expected input/output).
If you are using A2C/PPO, there is no q-value function, only a value function (please take a look at the code again if you want more details).

The predict method is only meant to predict actions.

**Comment by c0x65o** [comment]
Would DQN have something like SAC has with `model.critic`? I am not seeing anything in the code.

**Comment by Miffyli** [comment]
@c0x65o For DQN there is no separation between actor/critic parts, there is only `q_net` which outputs the Q-values.

**Comment by araffin** [comment]
>Would DQN have something like SAC has with model.critic? I am not seeing anything in the code.
>@c0x65o For DQN there is no separation between actor/critic parts, there is only q_net which outputs the Q-values.

Yes, DQN is not an actor critic method. You can read more about it here: https://stable-baselines3.readthedocs.io/en/master/modules/dqn.html#notes
