### ISSUE TITLE
Add examples to stable baselines 3 on aws sagemaker

### ISSUE THREAD

**Issue by drose188** [DLR-RM/stable-baselines3#315]
Add complete examples to stable baselines 3 on aws sagemaker with different algos  (ppo, td3, sac), custom env etc.
Show how to create a launcher and docker image. 
Show how to monitor training and how to do hyperparameters tuning.
Currently, there is only one simple example with tensorflow.

**Comment by araffin** [comment]
Hello,
>Add complete examples to stable baselines 3 on aws sagemaker with different algos (ppo, td3, sac), custom env etc.

Why would that be SB3 job and not part of AWS Sagemaker documentation?
I think we have a quite complete documentation that cover already a lot of cases and that can be adapted easily.
Regarding hyperparameter tuning and experiment management, we have the rl zoo for that: https://github.com/DLR-RM/rl-baselines3-zoo

> Currently, there is only one simple example with tensorflow.

I guess you are refering to [this](https://github.com/aws/amazon-sagemaker-examples/tree/master/reinforcement_learning/rl_roboschool_stable_baselines)?
We have a [migration guide](https://stable-baselines3.readthedocs.io/en/master/guide/migration.html) too, to migrate from SB2 to SB3.


> Show how to create a launcher and docker image.

We have pre-built docker images (cf documentation)
For the launcher, it seems it can be easily adapted from the SB2 example (see migration guide).

**Comment by drose188** [comment]
Yes, I was referring to the example you mentioned (Roboschool).
This is working with ppo launcher. I work with sac and td3 also.
Can you share the link to the pre-built docker images?
I had some issues with building the docker image.
I was hoping for a complete end-to-end notebook code example that can be run tested easily on sagemaker.

**Comment by araffin** [comment]
> Can you share the link to the pre-built docker images?

Please read the [documentation](https://stable-baselines3.readthedocs.io/en/master/guide/install.html#using-docker-images).

RL zoo images are here: https://hub.docker.com/r/stablebaselines/rl-baselines3-zoo (see dockerhub: https://hub.docker.com/u/stablebaselines)

I will close this issue as I think this should be sagemaker documentation, not SB3.
