### ISSUE TITLE
[Question] HER implementation baselines - SB3

### ISSUE THREAD

**Issue by Cladett** [DLR-RM/stable-baselines3#318]
Hello,
I have a question regarding the different HER implementation across baselines, SB2 and SB3.
I have a very simple environment with a robot that performs a reaching task (reaching a target).

Using HER+DDPG  from baselines the agent is able to solve the environment.

I have been trying with SB2 and SB3 without any success.
I have noticed that SB2 documentation states the following: 

_HER was re-implemented from scratch in Stable-Baselines compared to the original OpenAI baselines. If you want to reproduce results from the paper, please use the rl baselines zoo in order to have the correct hyperparameters and at least 8 MPI workers with DDPG._

While SB3 documentation does not mention anything anymore.
Would it be possible to know which are the main change that have been perform across SB2 and SB3?
Is it just a matter of hyperparams?

Thank you very much for all the work for this repo and all the support.

**Comment by araffin** [comment]
Hello,

>I have been trying with SB2 and SB3 without any success.

I would recommend you to use the zoo (cf doc) with tuned hyperparameters, for instance: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/her.yml#L56

Even though you cannot use workers with SB3, having a bigger batch size have the same effect on learning.


>Would it be possible to know which are the main change that have been perform across SB2 and SB3?
Is it just a matter of hyperparams?
> Would it be possible to know which are the main change that have been perform across SB2 and SB3?

See [Migration Guide](https://stable-baselines3.readthedocs.io/en/master/guide/migration.html#her)

**Comment by araffin** [comment]
>Would it be possible to know which are the main change that have been perform across SB2 and SB3?
Is it just a matter of hyperparams?

the main changes is that SB3 implementation now relies on a custom replay buffer that allow online sampling (as done by OpenAI Baselines) and that we don't support MPI anymore.

> Is it just a matter of hyperparams?

for it to work on your task? yes probably.
The SB3 was tested both in simulation (on mujoco robotics tasks) and on a real robot.

**Comment by araffin** [comment]
Hello,
it seems that your issue may be caused by https://github.com/DLR-RM/stable-baselines3/issues/331 (the fix will be merged with master soon).
The problem was not present for SAC (hence the parameters of the zoo are working).

**Comment by Cladett** [comment]
Hello,
thank you very much for letting me know and for the work. I will have a look
