### ISSUE TITLE
Save/Load models from s3

### ISSUE THREAD

**Issue by drose188** [DLR-RM/stable-baselines3#322]
Save/Load model, parameters, replay buffer directly to/from s3

**Comment by araffin** [comment]
Hello,

have you read the documentation?

and please fill in the issue template completely next time ;)

**Comment by araffin** [comment]
Hello,
Could you please fill in the issue template completely?

**Comment by araffin** [comment]
Note: this is already the [4th issue](https://github.com/DLR-RM/stable-baselines3/issues/created_by/drose188) that you open without using the issue template, if you continue like that, **we will stop replying and close your issues automatically in the future**.
Consider this message as a first and LAST warning.
