### ISSUE TITLE
[Question] Resume of  training from saved model does not give similar result

### ISSUE THREAD

**Issue by kmsgnnew** [DLR-RM/stable-baselines3#326]
### Question

Does Resume training from saved model give similar results in stable baseline 3??

### Additional context
A model is trained for 10 epochs,  model is saved  at 5 epochs then loaded using DQN.load() and then training is continued with model.learn for another 5 epoch. This continuation does not match for me. does it match for anyone or is it still not supported

Note: 1 epoch is over entire dataset

I have already seen similar issue comments in stable baseline at
https://github.com/hill-a/stable-baselines/issues/692
https://github.com/hill-a/stable-baselines/issues/301

**Comment by araffin** [comment]
Hello,
have you saved the replay buffer? (cf doc)
have you make sure that the exploration factor (epsilon) starts at the same value it ended?

It is hard to compare training policy, better to compare deterministic ones, usually used for evaluation (cf doc).

Please provide a minimal working example (cf issue template)

**Comment by kmsgnnew** [comment]
thanks araffin for quick reply.

as I understand adding following  two changes should improve:
1)  {have you saved the replay buffer?}
save_replay_buffer while training and then first load model using _DQN.load() also  load_replay_buffer_ from pickle file

2) 
 { have you make sure that the exploration factor (epsilon) starts at the same value it ended? }

for ensuring exploration factor (epsilon) starts at the same value it ended.

# Get the parameters as the starting point for ES
mean_params = model.get_parameters()
save this dictonary.
_DQN.load() also  set_parameters(load_path_to_dictonary)_

**Comment by araffin** [comment]
https://github.com/hill-a/stable-baselines/issues/950#issuecomment-790109983
