### ISSUE TITLE
The Lunar Lander example throws a 'NoneType' object error on env variable

### ISSUE THREAD

**Issue by JulesVerny** [DLR-RM/stable-baselines3#327]
The Lunar Lander example in the getting started documentation:
 https://stable-baselines3.readthedocs.io/en/master/guide/examples.html

This example creates the Lunar Lander environment:  env = gym.make('LunarLander-v2') 
It then goes on to performs the Training cycles. 
But when it comes to run the evaluated model, the 
obs = env.reset()    line throw up a  'NoneType' object has no attribute 'reset'

Which suggests that the env variable has been overwritten somehow. 

I can run the model, by simply creating the env = gym.make('LunarLander-v2'),  loading the saved model file, and performing and the  obs = env.reset() and the rendering cycles then operate OK. 

But this does not explain, why the original documented example throw up the NoneType error

**Comment by Miffyli** [comment]
Good catch! An embarrassing bug in the very first example indeed...

The issue is that `env` is not stored with model upon save (as intended, if I am not horribly mistaken), so `model.get_env()` returns `None` after loading it. The simplest solution for this is use `env` instead of `model.get_env()` in call to evaluation. A PR to fix this would be welcomed :)

**Comment by sycz00** [comment]
Hey, one question which might be related to that one: is the Lunar Lander example supposed to work after the training ? I tested it twice and the lander just keeps itself up and never lands.. f it should work, then I might have some bug in SB3. I am currently investigating the pipeline of my main task which uses SB3. Thanks in advance :)

**Comment by Miffyli** [comment]
>  Hey, one question which might be related to that one: is the Lunar Lander example supposed to work after the training ? I tested it twice and the lander just keeps itself up and never lands.. f it should work, then I might have some bug in SB3. I am currently investigating the pipeline of my main task which uses SB3. Thanks in advance :)

Hmm you are right, it does not seem to train (or would at least require more samples to do so).

@araffin should the DQN+LunarLander example train a good agent? Looking at the [optimized params](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/dqn.yml#L51) it should at least have some more params in it. For cleanliness, maybe we should change it to PPO or something else?

**Comment by sycz00** [comment]
Okay good to know

**Comment by araffin** [comment]
> is the Lunar Lander example supposed to work after the training ?

>@araffin should the DQN+LunarLander example train a good agent? Looking at the optimized params it should at least have some more params in it. For cleanliness, maybe we should change it to PPO or something else?

Examples are here only to show how to quickly run something. Optimized hyperparameters and proper training are done in the RL Zoo.

**Comment by Miffyli** [comment]
> Examples are here only to show how to quickly run something. Optimized hyperparameters and proper training are done in the RL Zoo.

Right, but I feel these examples give bit of a bad impression, and I can't blame people for expecting them to work.
How about minimal working arguments (e.g. sooner learning_starts and bit more training), or a comment/note that this might not learn and a pointer to proper params?

**Comment by araffin** [comment]
>  How about minimal working arguments (e.g. sooner learning_starts and bit more training), or a comment/note that this might not learn and a pointer to proper params?

for DQN it is tricky to make it work with a small budget (see optimized hyperparams), I would prefer a warning/note also to keep the examples simple ;)
