### ISSUE TITLE
[Question] Sequential creation of environments

### ISSUE THREAD

**Issue by ewan15** [DLR-RM/stable-baselines3#328]
### Question

Currently I have a single environment that is built (from crazy large sets of data). When attempting to use multiple envs I run out of memory on my system. Is there a way to sequentially make environment or could this become a feature request (which I would be happy to work on)

**Comment by ewan15** [comment]
* The process of making the env is what creates a lot of data not the env itself

**Comment by Miffyli** [comment]
If you are using A2C or PPO then there is no way around this: their learning depends on having multiple, parallel environments. You could try using a very large `n_steps` with only one environment but I can not guarantee this will work as well as many environments + smaller `n_steps`. Creating and assigning new environments as learning progresses would not help in this case (you could also modify the environment in place, which will give you the same results but you do not have to modify stable-baselines3 code to achieve that)

**Comment by araffin** [comment]
>The process of making the env is what creates a lot of data not the env itself

making or resetting? (if it is just making and then the memory is freed, then you can have a big `time.sleep()` between the creation of each env...)

A better option is to share this large dataset between envs and/or loading the dataset chunk by chunk.

Anyway, not really related to SB3, rather to gym. Therefore, if you have no other question related to SB3, you may close this issue ;)

**Comment by ewan15** [comment]
Ah cool yeh, added within the gym code.

Apologies thought that was part of SB3 not gym.

Cheers
