### ISSUE TITLE
[Question] Is it possible to get a picture/print of the NN-architecture?

### ISSUE THREAD

**Issue by HadiSDev** [DLR-RM/stable-baselines3#329]
### Question

Is it possible to ask the summary writer to add a graph or picture of the NN-architecture? I just want a way to confirm that the NN is actually implemented correctly.

**Comment by araffin** [comment]
>Is it possible to ask the summary writer to add a graph or picture of the NN-architecture? I just want a way to confirm that the NN is actually implemented correctly.

two options:
1. Take a look at `model.policy` (this is a PyTorch module and it has a state dict), I recommend to use interactive python debugger for that, or ipython
2. Use Tensorboard (but this may yield ugly graph) as I already mentioned in https://github.com/hill-a/stable-baselines/issues/1093

**Comment by HadiSDev** [comment]
@araffin  Thanks. I will have a look
