### ISSUE TITLE
[feature-request] Vectorized/Stacked Action Noise

### ISSUE THREAD

**Issue by PartiallyTyped** [DLR-RM/stable-baselines3#33]
I am opening an issue to discuss the implementation and leave the PR for the code review.

The motivation behind this addition is that for OU or other noise processes we need the state to exist until the end of the trajectory. We can't use a single process for multiple parallel episodes as they have different lengths. Thus, stacked/vectorized processes allow us to keep the processes for as long as the particular episode goes.

My internal code (from the old issue in SB2).

```python

class VecNoise(ActionNoise):

    def __init__(self, base_class: Type[ActionNoise], num_noise: int, **noise_params):
        super().__init__()
        constr = partial(base_class, **noise_params)
        self._noise: List[ActionNoise] = [constr() for _ in range(num_noise)]

    def reset(self) -> None:
        """
        Call reset in all noise objects
        """
        for noise in self._noise:
            noise.reset()

    def reset_by_index(self, indices: Iterable[int]) -> None:
        """
        Args:
            indices: the indices to reset
        """
        for index in indices:
            self._noise[index].reset()

    def __repr__(self) -> str:
        return "VecNoise({})".format(repr(self._noise[0]))

    def __call__(self) -> np.ndarray:
        return np.stack([noise() for noise in self._noise])

```

An alternative is to provide the noise directly and copy/deepcopy it

```python

class VecNoise(ActionNoise):

    def __init__(self, base_noise:ActionNoise, num_noise: int):
        super().__init__()
        self._noise: List[ActionNoise] = []
        for _ in range(num_noise):
            noise = copy.deepcopy(base_noise)
            noise.reset() 
            self._noise.append(noise)
   ...
```
Or
```python

class VecNoise(ActionNoise):

    def __init__(self, base_noise:ActionNoise, num_noise: int):
        super().__init__()
        self._noise: List[ActionNoise] = tuple(map(copy.deepcopy, [base_noise]*num_noise))
        tuple(map(ActionNoise.reset, self._noise))
   ...
```

**Comment by araffin** [comment]
Hello,
I like both option 1 and option 2 but I would go for option 2 as it avoids having unknown `noise_params`.

Minor:
- I would name the noise list `_noises` to reflect the fact that it is a vector of noise
- you should use f-strings now
- I would use `n_envs` instead of `num_noise` to be consistent with the `VecEnv`s
- where do you need the `reset_by_index`? I would also rather expose a property named `noises` in that case (so you don't have access to only the reset method)
- I would include the number of envs in the representation
- for option 2, you can do the reset after creating the complete list, it will be more concise that way

**Comment by PartiallyTyped** [comment]
> where do you need the reset_by_index?

Considering TD3/SAC reset the noise process on done, the goal here is to reset individual processes without resetting the others.

However, I think that using just one function is better:

```
    def reset(self, indices=None) -> None:
        if indices is None:
            indices = range(len(self.noise))
        for index in indices
            self._noises[index].reset()
```

> I would also rather expose a property named noises in that case (so you don't have access to only the reset method)

Perhaps I could add a `__getitem__` and a property so it behaves like a list with extra functionality?

**Comment by araffin** [comment]
>However, I think that using just one function is better:

sounds good

>Perhaps I could add a __getitem__ and a property so it behaves like a list/tuple with extra functionality?

I'm not sure if this is really needed, but why not.
Usually we just want to reset or query the action noise, no?

**Comment by PartiallyTyped** [comment]
>  Usually we just want to reset or query the action noise, no?

Usually yes, I will just leave it (`__getitem__`) out and if it's ever needed, we can deal it then.
