### ISSUE TITLE
[Feature Request] wandb logging?

### ISSUE THREAD

**Issue by drozzy** [DLR-RM/stable-baselines3#333]
How would I go about logging to weights and biases (wandb)?

**Comment by araffin** [comment]
Hello,
You should have a look at callback in the documentation.

After a quick search, you can find https://github.com/alexliniger/learning-to-race-sagemaker/blob/77ce31c4a556708bec063018ef5fcd73327917bc/wandb_callback.py

Related: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/6

**Comment by araffin** [comment]
Now officially supported: https://docs.wandb.ai/guides/integrations/other/stable-baselines-3
Video: https://www.youtube.com/watch?v=ed1bqaZGOQw
