### ISSUE TITLE
What does "Tried to step environment that needs reset" from monitor.py +mean exactly?

### ISSUE THREAD

**Issue by mpgussert** [DLR-RM/stable-baselines3#339]
There is an error message that seems to be produced with my custom environment when I try to continue training with "reset_num_timesteps" set to false.  I expect this is an issue in my env and not in your actual codebase because I can't reproduce it using something like cartpole.  Also this only started happening this week, after SB3 was officially released (I am currently migrating over my project)

anyway, my concern right now is just trying to understand the following error message.  The runtime error is raised on line 92 of common/monitor.py

```
if self.needs_reset:
            raise RuntimeError("Tried to step environment that needs reset")
```

This error **only** seems to occur when i try to continue logging from the last time step.  That is, if I set "reset_num_timesteps" to true, training continues normally from the last checkpoint, but i get a second "PPO_2" line in the tensorboard display.  manually resetting the environment if I load a checkpoint before calling learn doesn't have any effect (nor should it).

What does this error mean?  

It isn't documented anywhere, and I can't find any specific logging requirement specified in the custom env docs.  Any discussion on this would be helpful!

Thanks!

**Comment by araffin** [comment]
Hello,

> expect this is an issue in my env and not in your actual codebase because I can't reproduce it using something like cartpole. 

this is why we have "custom env" issue template.

>when I try to continue training with "reset_num_timesteps" set to false.

hello, please provide a minimal working example.
I think the error is pretty explicit: it means that you try to call `step()` after a `done=True` signal was returned (which mean the env needs to be reset).

**Comment by mpgussert** [comment]
Again, **I'm not trying to get this issue addressed explicitly**, i am trying to understand what the exception raised on line 92 of common/monitor.py means, as it isn't documented anywhere and the runtime error it returns is non descriptive.

I can't provide you any of my code, and as I said, I can't reproduce this error using something like cartpole.  To give you a minimum working example I would need to write a custom dummy env with the same issue as the one I am using, and I can't identify what that issue is without understanding this error.

> I think the error is pretty explicit: it means that you try to call step() after a done=True signal was returned (which mean the env needs to be reset).

Again, as I stated, I have tried manually resetting the environment if I load a checkopoint before calling learn and it has no effect.  I'm 99% sure that "reset" here is explicitly referring to resetting the timestep counter because the error is being thrown from monitor.py, and it does not occur if i keep "reset_num_timesteps" set to true.

**Comment by Miffyli** [comment]
>  I'm 99% sure that "reset" here is explicitly referring to resetting the timestep counter because the error is being thrown from monitor.py, and it does not occur if i keep "reset_num_timesteps" set to true.

Hmm this sounds like unintended behaviour / a bug. The `reset` here refers to environment´s `reset()` function, which needs to be called after `done=True` (this is what the exception solely means: monitor keeps additional track  of the correct ordering of step-reset calls to make sure monitor's behaviour stays sane). The choice of environment _shouldn't_ matter as bug raises from monitor.py code, so it should happen with CartPole or other environments.

**Comment by mpgussert** [comment]
sure!  my order of operations are as follows

```
env = MyCustomEnvironment(env_kwargs)

checkpoint_callback = CheckpointCallback(
        save_freq=args.save_freq, save_path="./params/", name_prefix=args.checkpoint_name
    )

 net_arch = [256, 256, dict(pi=[128, 64, 32], vf=[128, 64, 32])]
  policy_kwargs = {"net_arch": net_arch, "activation_fn": torch.nn.ReLU, "features_extractor_class": CustomCNN}

  if args.loaded_checkpoint == "":
      model = PPO(
          "CnnPolicy",
          env,
          verbose=1,
          tensorboard_log=args.tensorboard_dir,
          policy_kwargs=policy_kwargs,
          device="cuda",
          n_steps=args.step_freq,
          batch_size=512,
          n_epochs=50,
          learning_rate=0.0005,
      )

  else:
      model = PPO.load(args.loaded_checkpoint, env)

  #if args.reset_num_timesteps is False, and we loaded a checkpoint, this line throws the error
  model.learn(
      total_timesteps=args.total_steps,
      callback=checkpoint_callback,
      eval_env=env,
      eval_freq=args.eval_freq,
      eval_log_path=args.evaluation_dir,
      reset_num_timesteps=args.reset_num_timesteps,
  )
  model.save(args.checkpoint_name)

```

I agree, it's really weird, but **good news**!  I managed to get my cartpole test to reproduce this error!  the reason why i couldn't before was because this seems to only occur if you load the checkpoint a separate script.


below is a slightly modified example i stole from your docs.  When you run it, it will train a model to run cartpole, then save the model, then delete the model, then it will load that file and continue training with reset_num_timesteps = False.  It does this without error.
```
import gym

from stable_baselines3 import PPO
from stable_baselines3.ppo import MlpPolicy
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.callbacks import BaseCallback, CheckpointCallback

# Parallel environments
env = make_vec_env('CartPole-v1', n_envs=4)

#checkpoint_callback = CheckpointCallback(
#        save_freq=1000, save_path="./bugParams/", name_prefix="cartpoleTest"
#    )

model = PPO(MlpPolicy, env, verbose=1, tensorboard_log="bugTensorboard")
model.learn(total_timesteps=25000, reset_num_timesteps=True)
model.save("ppo_cartpole")

#del model  # remove to demonstrate saving and loading

# the following executes without error
print("CONTINUE TRAINING")
model2 = PPO.load("ppo_cartpole", env)
model2.learn(total_timesteps=25000, reset_num_timesteps=False)
print("TRAINING CONTINUATION COMPLETE")

obs = env.reset()
while True:
    action, _states = model2.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

However, if we load the file created with this script in a separate script, the error occurs.  once you have created ppo_cartpole.zip, then executing this script from the command line throws the error if reset_num_timesteps = False, but does not throw the error if it's True
```

import gym

from stable_baselines3 import PPO
from stable_baselines3.ppo import MlpPolicy
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.callbacks import BaseCallback, CheckpointCallback

env = make_vec_env('CartPole-v1', n_envs=4)

print("CONTINUE TRAINING")
model2 = PPO.load("ppo_cartpole", env)
model2.learn(total_timesteps=25000, reset_num_timesteps=False)
print("TRAINING CONTINUATION COMPLETE")
```

**Comment by araffin** [comment]
>However, if we load the file created with this script in a separate script, the error occurs. once you have created ppo_cartpole.zip, then executing this script from the command line throws the error if reset_num_timesteps = False, but does not throw the error if it's True

this is expected. As shown in the documentation (https://stable-baselines3.readthedocs.io/en/master/guide/tensorboard.html), `reset_num_timesteps = False,` is meant to be used when you call `.learn()` sequentially several times and when the env state should not be changed.
If `reset_num_timesteps=True` the model will call `env.reset()` internally, see https://github.com/DLR-RM/stable-baselines3/blob/65100a4b040201035487363a396b84ea721eb027/stable_baselines3/common/base_class.py#L378

In your case, if you want still to load a checkpoint and use `reset_num_timesteps = False,`, you will need to do those different steps manually:
https://github.com/DLR-RM/stable-baselines3/blob/65100a4b040201035487363a396b84ea721eb027/stable_baselines3/common/base_class.py#L378-L383

**Comment by mpgussert** [comment]
I don't think this behavior is desirable, and the documentation you linked doesn't actually tell you that this is required when loading a checkpoint from a separate script.  This behavior also was not present in the beta (it only started happening once i migrated to 1.0).

I would suggest checking for this scenario internally, so the end user does not need intimate knowledge of the source code in order to use it properly, or adding an this detail to the documentation and the produced error message.

**Comment by njanirudh** [comment]
I have the same error when using 'Monitor(env)' on a custom environment trained using PPO  with  `reset_num_timesteps = False`.  
I am a little confused about the solution to this problem.

> In your case, if you want still to load a checkpoint and use `reset_num_timesteps = False,`, you will need to do those different steps manually:

Does this mean that we must  'reset()' manually inside some logic in the 'step()' function of the env?

**Comment by mpgussert** [comment]
I didn't.  for environments like cartpole you can avoid the error by resetting before calling learn only if you are loading a checkpoint.  However, this didn't work for me when using a custom environment, and i wasn't able to figure out why. I resolved the issue by reverting back to the last beta release

**Comment by araffin** [comment]
Since PR https://github.com/DLR-RM/stable-baselines3/pull/469, the user can now define custom logger and override default behavior, see example in https://github.com/DLR-RM/stable-baselines3/issues/433#issuecomment-860685073
