### ISSUE TITLE
Obtaining different results using diferent machines using PPO 

### ISSUE THREAD

**Issue by Koneru1919** [DLR-RM/stable-baselines3#342]
I have created a Custom Environment using stablebaselines3 and currently using a windows PC .I have passed an argument seed=0 i,e model = PPO(seed=0).While I run on my pc the results are the same all the time.

When I run the same code with seeding on other windows systems and Linux, I get different results.

**Comment by araffin** [comment]
https://stable-baselines3.readthedocs.io/en/master/guide/algos.html#reproducibility

**Comment by Koneru1919** [comment]
Thank you.I will check it.
