### ISSUE TITLE
[Question] Where to contribute PPG algorithm

### ISSUE THREAD

**Issue by janEbert** [DLR-RM/stable-baselines3#346]
### Question

I've implemented the [phasic policy gradient](https://arxiv.org/abs/2009.04416) (PPG) algorithm for sb3 (see [sb3-ppg repo](https://github.com/janEbert/sb3-ppg)). Should I open a pull request here or in the [sb3-contrib repo](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib)?

While the algorithm's code is simple, heavily reusing PPO, it requires an altered policy with an additional auxiliary head. This added complexity would probably speak for the contrib repo but I wanted to check here first.

### Checklist

- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
>Should I open a pull request here or in the sb3-contrib repo?

Please open an issue in the contrib repo and make sure to read the contribution guide carefully ;) (different from SB3):
https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/CONTRIBUTING.md

**Comment by janEbert** [comment]
Hey araffin, I'll do so! Thanks for the heads-up regarding the different contribution guidelines!

Did I do something wrong or why the winking smiley? :D
I thought opening an issue was the right way to get started according to the contribution guidelines here.

**Comment by Miffyli** [comment]
> Did I do something wrong or why the winking smiley? :D

That's the arrafin™ way of doing things, you are all good :)

> I thought opening an issue was the right way to get started according to the contribution guidelines here.

**Comment by janEbert** [comment]
All righty, thanks! :o)
See you later in contrib then!

**Comment by araffin** [comment]
quick question: do you still plan to contribute PPG to contrib or should I create an issue in contrib so someone else could take over?

**Comment by araffin** [comment]
> Is that okay with you?

perfect =) (I was mostly wondering if you were still interested or not)

**Comment by janEbert** [comment]
Oh absolutely! Again, sorry for asking for more patience. :)
