### ISSUE TITLE
Canonical Channels First/Last Clarification

### ISSUE THREAD

**Issue by decodyng** [DLR-RM/stable-baselines3#349]
### 📚 Documentation

This is a very minor quibble with in-code documentation/defaults, but: I noticed that `is_image_space` has a [default](https://github.com/DLR-RM/stable-baselines3/blob/237223f834fe9b8143ea24235d087c4e32addd2f/stable_baselines3/common/preprocessing.py#L27) `channels_last=True` parameter, even though in NatureCNN,[ the assumption is that channels are first](https://github.com/DLR-RM/stable-baselines3/blob/237223f834fe9b8143ea24235d087c4e32addd2f/stable_baselines3/common/torch_layers.py#L64). 

In NatureCNN, `is_image_space` isn't called with `check_channels`, so that parameter doesn't end up being used, but I briefly found it a bit confusing, when I was debugging my image spaces being the right construction, that the default value for `channels_last` in the function definition conflicted with the assumed default for the canonical CNN feature extractor.

I realize that switching the default value on `is_image_space` would be a pain, since it would be a breaking change to peoples' code, but perhaps a workable middle ground would be to just add a clarification to the docstring of `channels_last` [here](https://github.com/DLR-RM/stable-baselines3/blob/237223f834fe9b8143ea24235d087c4e32addd2f/stable_baselines3/common/preprocessing.py#L37) saying something like "by the way, this parameter doesn't come into play unless `check_channels` is set, and also the default being `True` is different from NatureCNN's expectations" 

### Checklist

- [x ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Thanks for pointing this out! These channel/transpose things are getting bit messy...

As `is_image_space` is used actively elsewhere in the code I tend to agree we should not touch default values, but the doc update you suggested sounds like a pleasant middle ground! A PR on this would be welcomed :)

**Comment by araffin** [comment]
Hello,

>In NatureCNN, is_image_space isn't called with check_channels, so that parameter doesn't end up being used, but I briefly found it a bit confusing, when I was debugging my image spaces being the right construction, 

In your case, I would recommend using the env checker, no?
the `is_image_space` here is mostly to provide with a more informative error if the user forgot to use the env checker first or if the user is using a `CnnPolicy` on a flat vector. The reason that `check_channels` is False by default is because checking if something is an image is quite tricky.
As a simple example, if you stack 4 grayscale images (as for Atari games), you will end up with a channel size of 4 (which does not look like RGB nor grayscale image at all...).

Also, please note that we do support channel last images by using `VecTranspose` wrapper automatically.

**Comment by decodyng** [comment]
> In your case, I would recommend using the env checker, no?
the is_image_space here is mostly to provide with a more informative error if the user forgot to use the env checker first or if the user is using a CnnPolicy on a flat vector. The reason that check_channels is False by default is because checking if something is an image is quite tricky.

I wasn't calling `is_image_space` directly, I was more debugging errors raised by it in the course of trying to use NatureCNN. (Also, I don't think env checker would have worked for my situation for somewhat complex reasons*). I don't think I'm arguing that `is_image_space` is the right thing direct debugging tool to use here, I more wanted to point out that, if someone were examining the code in the process of trying to debug some error, and saw the `channels_last=True` as the default value for what seems to be the canonical image-checking function, that might lead to confusion about the system's overall default. I should also note: I've been able to get what I need to get running fine at this point, I more wanted to raise this as being slightly unintuitive for others who may run into it in future. 

I'd be happy to put together a small suggested doc change, @Miffyli , and submit that as a PR. 



* I'm working with environments that have Dict Observation and Action spaces, and have written custom wrappers and policy classes to handle that, so my expectation is that even if an env is in a state where my usage of `NatureCNN` would succeed (since it's called after extracting an image space from within a Dict() one) I imagine the env as a whole would fail on `env_checker` because of it using natively-unsupported obs and act spaces.

**Comment by araffin** [comment]
>I'm working with environments that have Dict Observation and Action spaces,

for dict observations, you might have a look at https://github.com/DLR-RM/stable-baselines3/pull/243 it should be merged with master once https://github.com/DLR-RM/stable-baselines3/pull/351 is ready.
(i've updated the env checker there too). Dict action spaces are much more tricky to handle, so the support is not really planned yet.


>I more wanted to point out that, if someone were examining the code in the process of trying to debug some error, and saw the channels_last=True as the default value for what seems to be the canonical image-checking function,

I see, maybe another thing to do (in addition to the doc PR) would be to explicitly specify `check_channels=False` in the NatureCNN to avoid confusion?

**Comment by decodyng** [comment]
> I see, maybe another thing to do (in addition to the doc PR) would be to explicitly specify check_channels=False in the NatureCNN to avoid confusion?

Yeah, I think that would be a nice additional bit of clarification! 


> For dict observations, you might have a look at #243, it should be merged with master once #351 is ready.
(i've updated the env checker there too). Dict action spaces are much more tricky to handle, so the support is not really planned yet.

Cool, good to know! I've already written the code I need to make both sides of this work (and possibly ended up reinventing the wheel relative to what you guys did, since the bulk of it was written over a year ago, before that PR got going) but it definitely would be nice in the long run for it to be fully supported by SB3 itself. 

(Unrelated to this issue, I had actually thinking of checking in with the maintainers to see if there was any interest in taking as a PR any of the aspects of how I chose to design support for Dict Action spaces in our codebase, which revolves around a MultiModalActionDistribution class that that provides the external interface of a single action distribution, but internally can maintain multiple different distribution types, and then merge those together as is appropriate for sampling, entropy, log prob, etc)

**Comment by Miffyli** [comment]
> (Unrelated to this issue, I had actually thinking of checking in with the maintainers to see if there was any interest in taking as a PR any of the aspects of how I chose to design support for Dict Action spaces in our codebase, which revolves around a MultiModalActionDistribution class that that provides the external interface of a single action distribution, but internally can maintain multiple different distribution types, and then merge those together as is appropriate for sampling, entropy, log prob, etc. No worries if your goal is to go down a different design route, but since our project had independent reason to do the work, it seemed at least worth seeing if it'd something you'd want to integrate)

We would definitely be interested in having support for more complex action spaces down the line! However as there does not seem to be "correct" approach to it (how to handle dependencies etc. See [this link](https://www.reddit.com/r/MachineLearning/comments/c7tct4/d_reinforcement_learning_with_combined_continuous/) shared by @arrafin ), it would be better to start with a discussion on [contrib](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/) first and see how much can be done there before touching SB3 too much.
