### ISSUE TITLE
How can I use plaidml with stable-baselines3

### ISSUE THREAD

**Issue by gkourogiorgas** [DLR-RM/stable-baselines3#352]
I have been using plaidml and Keras on my Mac to train some simple dqn RL agents. Unfortunately Keras is too high level for most RL models. Is there a way to make it work? I wouldn't mind contributing to a plaidml version of stable-baselines

**Comment by araffin** [comment]
Hello,
what you are probably looking for is exporting models?

As policy are pytorch modules, they can be exported to ONNX easily (or to Torchscript if you want to use c++ later),
however it is not documented yet (we would welcome such contribution ;)):

https://stable-baselines3.readthedocs.io/en/master/guide/export.html

But it seems you are looking for training with plaidml, in that case you may need a custom version of SB3...
I'm also not sure of what plaidml is meant for.

**Comment by gkourogiorgas** [comment]
So exporting is for already trained models? 
If so, then I would be interested in leveraging my AMD GPU for the training bit.
PlaidML is a compiler and could perhaps work like this for TF:
https://kenthinson.com/machine-learning-with-gpu-on-mac-osx/
And perhaps similarly for Pytorch?

**Comment by araffin** [comment]
> And perhaps similarly for Pytorch?

https://stackoverflow.com/questions/63008040/how-to-use-amd-gpu-for-fastai-pytorch

**Comment by gkourogiorgas** [comment]
I know. It doesn't support Mac. I tried linuux on parallels (VM) but doesn't access the GPU card directly, so it doesn't see it.

**Comment by araffin** [comment]
>I know. It doesn't support Mac. I tried linuux on parallels (VM) but doesn't access the GPU card directly, so it doesn't see it.

you probably need to compile it yourself (there was a link apparently in the answer) or wait AMD GPU to be officially supported for Mac by the pytorch team.

Anyway, as this is related to PyTorch only (and not about exporting), I will close this issue.
