### ISSUE TITLE
[Question] VecNormalize and EvalCallback

### ISSUE THREAD

**Issue by ErikVester** [DLR-RM/stable-baselines3#362]
Hi, 

### Question

I was wondering how to 'properly' use the eval callback with the VecNormalize wrapper. As I am using multiple environments during training, I make a separate eval_env which is also a vec_env and to which I also apply the VecNormalize wrapper: 
`
#Separate env for evaluation `
`
eval_env = make_vec_env(env_id, env_kwargs= env_kwargs, n_envs = 1)
`
`
eval_env = VecNormalize(eval_env, norm_obs = True, norm_reward= False, gamma = gamma) 
`

I saw some examples where 'training' is set to False for the evaluation but I am not sure what is the right way to ensure a similar normalization in the evaluation as in the training? 

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

Kind regards, 

Erik

**Comment by araffin** [comment]
Hello,
Good question, the answer is that the `EvalCallback` wrapper is taking care of the normalization (it is important that training is set to False):
https://github.com/DLR-RM/stable-baselines3/blob/e1ee87fef7a5a7d7486fd6e5889cfdface2d0cda/stable_baselines3/common/callbacks.py#L357-L358

**Comment by ErikVester** [comment]
Hi Araffin, 

Thank you for your quick response and the explanation, I missed that one! Thank you :) 

Kind regards, 

Erik
