### ISSUE TITLE
[Question] Can agents be forced to respect total_timesteps (not padding to the next multiple of N)?

### ISSUE THREAD

**Issue by semitrivial** [DLR-RM/stable-baselines3#366]
### Question

When I run `A2C('MlpPolicy', env).learn(total_timesteps=1)`, `env.step` is called 5 times. Likewise, `total_timesteps=6` calls `env.step` 10 times. It seems like `A2C` rounds `total_timesteps` up to a multiple of 5.

Likewise, `PPO` seems to round `total_timesteps` up to a multiple of 2048. `DQN` seems to round `total_timesteps` up to a multiple of 4.

Is there a way to disable this rounding and make the agents follow the exact number of specified timesteps?

### Additional context

Here is some code to illustrate the problem:
```
from stable_baselines3 import PPO
import gym
from gym import spaces

class CustomEnv(gym.Env):
  def __init__(self):
    super(CustomEnv, self).__init__()
    self.action_space = spaces.Discrete(2)
    self.observation_space = spaces.Discrete(1)
    self.stepcount = 0

  def step(self, action):
    self.stepcount += 1
    obs, reward, done, info = 0, 0, False, {}
    return obs, reward, done, info
  def reset(self):
    return 0
  def render(self, mode='human'):
    return
  def close (self):
    return

env = CustomEnv()
model = PPO('MlpPolicy', env).learn(total_timesteps=100)
print(env.stepcount)  # Prints 2048, not 100 like we would expect
```

**Comment by semitrivial** [comment]
Digging deeper, it looks like:

- `DQN.__init__` takes an optional `train_freq` argument which you can set to 1 (default is 4)
- `A2C.__init__` takes an optional `n_steps` argument which you can set to 1 (default is 5)
- `PPO.__init__` takes an optional `n_steps` argument which you can set to 2. You can't reduce it to 1 unless you increase `n_envs` to more than 1. Is there a reason for that limitation?

**Comment by araffin** [comment]
>Is there a way to disable this rounding and make the agents follow the exact number of specified timesteps?

this is because of the way those algorithms work...
If you really want to stop after `n` timesteps, you can use a callback, but then for `A2C`/`PPO` training again would not always be possible.
