### ISSUE TITLE
Memory allocation for buffers

### ISSUE THREAD

**Issue by Artemis-Skade** [DLR-RM/stable-baselines3#37]
With the current implementation of buffers.py one can request a buffersize which doesn't fit in the memory provided but because of numpys implementation of ``np.zeros()`` the memory is not allocated before it is actually used. But because the buffer is meant to be filled completely (otherwise one could just use a smaller buffer) the computer will finally run out of memory and start to swap heavily. Because there are only smaller parts of the buffer that are accessed at once (minibatches) the system will just swap the necessary pages in and out of memory. At that moment the progress of the run is most likely lost and one has to start a new run with a smaller buffer.

I would recommend using ``np.ones`` instead, as it will allocate the buffer at the beginning and fail if there is not enough memory provided by the system. The only issue is that there is no clear error description in the case where the system memory is exceeded but python gets simply killed by the OS with a SIGKILL. Maybe one could catch that command?

**Comment by PartiallyTyped** [comment]
I suggest using `np.empty((shape))` instead of `np.ones`, `np.ones` takes a long time to fill if the memory is available, whereas `np.empty` does not, but it still performs memory checking.

````
>>> try:np.empty((100000,1000000000))
... except MemoryError:
...     print('====caught')
...
python(36866,0x107e22dc0) malloc: can't allocate region
:*** mach_vm_map(size=800000000000000, flags: 60000100) failed (error code=3)
python(36866,0x107e22dc0) malloc: *** set a breakpoint in malloc_error_break to debug
====caught
````

**Comment by Artemis-Skade** [comment]
Yes, that will also display a nice error message. Thank you

**Comment by Miffyli** [comment]
`np.empty` sound good (`np.ones` does throw an error for me, but `np.empty` is faster and semantically sounds better). I think you could include this change in the DQN branch, being a trivial change.

**Comment by Artemis-Skade** [comment]
Well, actually np.empty has the same issue as np.zeros. It uses sparse arrays and therefore doesn't allocate the whole array at the beginning, whereas np.zeros necessarily does, maybe I can provide an example code.

**Comment by Miffyli** [comment]
Ah yes, that indeed is the case. Seems like you only get memory errors when you try to allocate past RAM+swap size. e.g. I have 64GB RAM and 64GB swap, and following happens (similar behaviour without allocating with `zeros` and `empty`:

```python3
>>> import numpy as np
>>> _ = np.ones((70000,500,500))
Traceback (most recent call last):
MemoryError: Unable to allocate 130. GiB for an array with shape (70000, 500, 500) and data type float64
>>> _ = np.ones((65000,500,500))
# Begins to allocate memory and goes to swap
```

Looks like this needs bit more work, but I still agree that such feature should exist.

**Comment by PartiallyTyped** [comment]
This is OS dependent though:
<img width="862" alt="Screenshot 2020-05-29 at 5 34 11 PM" src="https://user-images.githubusercontent.com/52372765/83272468-dad84780-a1d3-11ea-86f9-0a1fc37ba06a.png">

My machine managed to almost fill the disk before killing the process.

**Comment by PartiallyTyped** [comment]
This should work:


```python
import psutil

import psutil
mem = psutil.virtual_memory()
# svmem(total=17179869184, available=7359184896, percent=57.2, used=9309233152, free=2441043968, active=4924092416, inactive=4230881280, wired=4385140736)
mem.available
# 7359184896

import numpy as np
x = np.empty(1000000000)
x.nbytes
# 8000000000
assert x.nbytes < mem.available
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# AssertionError
```

**Comment by araffin** [comment]
@Miffyli I'm not sure if we should add it as a requirement... maybe document it and do a try/except rather than forcing people to download it?

I would say it should be part of the `tests` or `extra` requirements?

**Comment by Miffyli** [comment]
@araffin I agree, I am not fan of more requirements. Another option would be to print out the memory usage, and give buffers a "verbose" parameter too (e.g. `verbose >= 1`  -> print out maximum memory usage of buffer in GB).

**Comment by PartiallyTyped** [comment]
This shouldn't be addresed in the DQN patch nor now tbh.

Since n-step methods are in 1.1+, this should be addressed along with/ or after them simply because off-policy correction requires state-action pairs and storing action selection probability for the behavior policy.

**Comment by Miffyli** [comment]
I think we can still have a simple print or check @Artemis-Skade already implemented. It is not too many lines, and yes, while it will be modified off later on we have something to work on.

**Comment by araffin** [comment]
Quick thought: am i missing something or the `next_observations` variable is just the `observations` shifted by one?
If so, we could reduce the buffer size by almost a factor of two!

**Comment by Miffyli** [comment]
Yeap it is. I think other implementations like some Rainbow ones do it this way (only one buffer for observations, and then you take two consecutive ones you return). Changing things to work like this takes bit more of complex-ish code, but also will support any future changes better (e.g. n-step returns).

**Comment by PartiallyTyped** [comment]
This works iff the observations are stored sequentially, and it needs to be in a deque. The deque is necessary because it ensures that sampled trajectories don't blend together. 

By blend, i mean that a the next state of a transition can't belong to a state from a different trajectory. We can blend only a terminal transition (done=true), because the next state is irrelevant because of the (1-done)  term  in the DQN update

**Comment by araffin** [comment]
it was fast and easy ;) https://github.com/DLR-RM/stable-baselines3/pull/28/commits/81bc9c0f9407fee74f01ea90ed0fdbbc6b5da3f9
I can finally have a 1M buffer =)

true, would work only for 1-step buffer. For n-step, we need to avoid copying things and only use references.

**Comment by PartiallyTyped** [comment]
After some more thought, we can further reduce the memory cost by k-fold, where k is the number of stacked frames by keeping track of single frame references, but it will make it slightly trickier and introduces implementation issues in the algorithm.

**Comment by Miffyli** [comment]
@araffin 

Looks good! I was afraid it would be more work but this indeed should work fine :D.

@PartiallyTyped 

Good point, but yeah that should be for later (also tying it to frame stacking makes this bit complicated). My personal suggestion would be to try out LZ4 compression for buffers (using it in personal projects with ~10% slowdown and 3x memory saved), but that too is for waaaay later versions and updates ^^

**Comment by araffin** [comment]
>The buffer effectively becomes one large lazy frame.

yes, would be nice if it does not complexify things too much. There was a `lazy_image` wrapper in SB  (used only by DQN apparently) which is now in gym.

> LZ4 compression for buffers 

I saw something like that in gym too...

**Comment by JakobThumm** [comment]
Is it possible to use the `optimize_memory_usage` option together with an HER buffer?
