### ISSUE TITLE
Custom policy having both CNN and MLP components

### ISSUE THREAD

**Issue by soumyatattwa** [DLR-RM/stable-baselines3#380]
Hi,

I am using a custom Mujoco env where I have a camera in hand setup (camera mounted on a robotic arm). For my environment, the observation spaces are as follows

1. An Image 
2. A data vector

I wish to create a custom Policy where I am using a CNN feature extractor for the image and a MLP for the data vector. Concatenate the results from them both (followed by some fully connected layers) and then finally get the probabilities for my action space.

I was wondering if there is a way to do this using stablebasline3

**Comment by araffin** [comment]
Duplicate of https://github.com/DLR-RM/stable-baselines3/pull/243
