### ISSUE TITLE
Run A2C on GPU

### ISSUE THREAD

**Issue by hpc-unex** [DLR-RM/stable-baselines3#384]
Hello,

Im using TensorFlow with A2C method under MlpPolicy. With device="cuda" as parameter for A2C things aren't going well. GPU utilization is only 4%-6% at the same time with only one CPU of 16 are used with 99% usage.

It is possible to run all on GPU? How can I speedup training?

**Comment by araffin** [comment]
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/314 and https://github.com/DLR-RM/stable-baselines3/issues/350

Please fill up the issue template next time.
