### ISSUE TITLE
Could you explain what reset_keywords and info_keywords in Monitor do?

### ISSUE THREAD

**Issue by drozzy** [DLR-RM/stable-baselines3#393]
Could you explain what reset_keywords and info_keywords in Monitor do? The comments are very short, and the code is a bit confusing for it:
https://github.com/DLR-RM/stable-baselines3/blob/ddbe0e93f9fe55152f2354afd058b28e6ccc3345/stable_baselines3/common/monitor.py#L24

I'm looking to aggregate some metric from the `info` dict just like monitor does with the `episode_returns`.
Can I use Monitor for that?

Specific example: let's say my info dict has the key: `info = { 'flag' : 1}`, I would like to get `flags = [0, 1, 0, 1, 0, 1]`  at the end of the episode.

**Comment by araffin** [comment]
Hello,

for the reset argument:
https://github.com/DLR-RM/stable-baselines3/blob/ddbe0e93f9fe55152f2354afd058b28e6ccc3345/stable_baselines3/common/monitor.py#L24-L25

the answer is some lines below:
https://github.com/DLR-RM/stable-baselines3/blob/ddbe0e93f9fe55152f2354afd058b28e6ccc3345/stable_baselines3/common/monitor.py#L74-L79

and

https://github.com/DLR-RM/stable-baselines3/blob/ddbe0e93f9fe55152f2354afd058b28e6ccc3345/stable_baselines3/common/monitor.py#L102

so it corresponds to additional argument passed to the `reset()` method  (not recommended as it changes gym api) that will be stored in the monitor file.

for the info keyword:

https://github.com/DLR-RM/stable-baselines3/blob/ddbe0e93f9fe55152f2354afd058b28e6ccc3345/stable_baselines3/common/monitor.py#L26

the doc is in fact incomplete (we would welcome a PR that update it ;)):
https://github.com/DLR-RM/stable-baselines3/blob/ddbe0e93f9fe55152f2354afd058b28e6ccc3345/stable_baselines3/common/monitor.py#L97-L98

only the infos at the last timestep (`done=True`) is recorded (for instance, for `GoalEnv`, we record `is_success` key at the end of each episode in the RL Zoo).

If you want to record `flags = [0, 1, 0, 1, 0, 1]` you will be need an additional wrapper.

**Comment by drozzy** [comment]
Ok thanks. That's what I ended up doing, writing a wrapper with a step override.
