### ISSUE TITLE
[Question] quick: how do I log the excel spread sheet?

### ISSUE THREAD

**Issue by dotaking2021** [DLR-RM/stable-baselines3#394]
### Question
If I do:
`model = A2C(CnnPolicy, env, verbose=2, tensorboard_log=PATH)`, this logs the tensor board. How do I just log the training process with the excel spreadsheet instead?

### Additional context

Add any other context about the question here.

### Checklist

- [ ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
```python
import gym
from stable_baselines3 import A2C
from stable_baselines3.common import logger

env = gym.make('CartPole-v1')
logger.configure(folder=".", format_strings=["csv"])
model = A2C('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=10000)
```
This will create a "progress.csv" file in the script's directory which contains the learning stats.


@araffin 
This stuff does not seem to be documented well despite support being there. Can you confirm I just wasn't blind?

**Comment by araffin** [comment]
> This stuff does not seem to be documented well despite support being there. Can you confirm I just wasn't blind?

related to #109 , i am not even sure if your fix work...
no, this should be documented (but I would prefer after #109 ).

**Comment by araffin** [comment]
Fixed in https://github.com/DLR-RM/stable-baselines3/pull/469

**Comment by gehirndienst** [comment]
@RefiloeShabe I have the same problem, actually I can't save csv logger neither by configuring the logger like: 
``` python
        env = gym.make("LunarLander-v2")
        model = PPO('MlpPolicy', env)
        logger.configure("./logs", ['log','csv'])
        model.learn(total_timesteps=100, log_interval=1)
```
nor by additionally including the logger it in model.save
``` python
        ...
        model.save("model", include= ["_logger","_custom_logger"])
```
progress.csv is empty whereas log.txt has only "Logging to ./logs"
