### ISSUE TITLE
[Question] Is this behavior expected in VecFrameStack?

### ISSUE THREAD

**Issue by UsmannK** [DLR-RM/stable-baselines3#396]
### Question

I am trying to evaluate a pretrained model from https://github.com/DLR-RM/rl-baselines3-zoo.

I make an environment as such:

```python
env = make_atari_env("SeaquestNoFrameskip-v4", n_envs=1)
env = VecFrameStack(env, n_stack=4)
```

My understanding is that this is required to run an agent that was trained on 4 envs simultaneously.

I then sample from the environment:

```python
all_obs = []
observation = env.reset()
all_obs.append(observation)
for _ in range(10):
    action = env.action_space.sample()
    observation, reward, done, info = env.step([action])
    print(observation.shape) # (1, 84, 84, 4)
    all_obs.append(observation)
all_obs = np.array(all_obs).squeeze()
```

**What I expect:** The 4 observation output at each timestep are identical, as I specified `n_envs=1`
**What occurs:** This is never the case, and for the first 4 timesteps some observations are just black. This is confusing because I expected to only have 1 environment and an evaluated model does in fact output exactly one action. Which environment is it using to determine the action?

I have plotted the first 6 timesteps below. The first image is the raw observation, the second image is the observation in col_0 subtracted from the one in col_n. The row represents the timestep.

```python
import matplotlib.pyplot as plt
fig,axs = plt.subplots(6,4)
for row in range(6):
    for col in range(4):
        # GRAYSCALE IMAGE ONLY
        axs[row,col].imshow(all_obs[row,...,col], cmap='gray')
        # COLORED IMAGE ONLY
        axs[row,col].imshow(all_obs[row,...,col] - all_obs[row,...,0])
plt.show()
```

![ts_6](https://user-images.githubusercontent.com/8558782/114938369-e46e9c00-9df3-11eb-8421-7ca03352dc56.png)

![ts_diff_6](https://user-images.githubusercontent.com/8558782/114938385-e9335000-9df3-11eb-96d6-21183b998301.png)

I suspect that this is expected behavior and I just misunderstand the library functions. If anyone is able to pinpoint what I may have missed, I'd greatly appreciate clarification :)

Thanks!

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by UsmannK** [comment]
Now that I look closer, is it just the case that these 4 frames are sequential? If I'm passing 4 frames into my model at every step, is it just using the first one?

If so, is it the case that the following code does not evaluate the final 3 frames?

```python
        while True:
            action, state = model.predict(observation, state=state, deterministic=True)
            observation, reward, done, info = env.step(action)
            
            if done:
                print("Episode {} finished after {} timesteps".format(i_episode,t))
                break
```

**Comment by Miffyli** [comment]
> Now that I look closer, is it just the case that these 4 frames are sequential? Is the model evaluating the 4th one every time? That would make sense.

Yes. FrameStack stacks N successive frames into one image, in a sense giving agent a short term memory. This is motivated by the original DQN paper (see first paragraph of Methods section [here](https://www.datascienceassn.org/sites/default/files/Human-level%20Control%20Through%20Deep%20Reinforcement%20Learning.pdf)).

If you have no further questions you may close the issue :)

**Comment by UsmannK** [comment]
Thank you for the explanation and the reference. Very helpful answer to a noob question :)
