### ISSUE TITLE
[Feature Request] Public Leaderboard for stable-baselines3

### ISSUE THREAD

**Issue by Leemoonsoo** [DLR-RM/stable-baselines3#397]
Hi there! I'm not sure it is a feature request or not, but anyway

### 🚀 Feature

A public leaderboard, automatically generated for stable-baselines3 or rl-baselines3-zoo.

### Motivation

According to the [README.md](https://github.com/DLR-RM/stable-baselines3/blob/master/README.md) of this repository,

> We expect these tools will be used as a base around which new ideas can be added, and as a tool for comparing a new approach against existing ones. 

Compare the new approach against the existing one will be easier when there's a public leaderboard who already have all the evaluation result of existing models.

Also, opportunities to put an idea on the top of the leaderboard will encourage to add more new ideas.

### Pitch

(Disclaimer:  I work for Luna ML)

[Luna ML](https://luna.staroid.com/) provides an evaluation environment and leaderboard for connected Github repositories. The repository defines the evaluation environment and scoring rule by creating [luna.yaml](https://luna-ml.github.io/luna/) file in it. When models (pre-trained models, agent) are pushed to the repository, it evaluates the model and displays evaluation results. And model's score is added to the leaderboard.

Currently, you can see a few open-ai gym challenges and a couple of submitted models from the service.
For example, [leaderboard for a CartPole-v1 challenge](https://luna.staroid.com/project/github.com/luna-ml/leaderboard/cartpole-v1/leaderboard) looks like

[![image](https://user-images.githubusercontent.com/1540981/114967557-89579c00-9e29-11eb-9994-c9914161c2ca.png)](https://luna.staroid.com/project/github.com/luna-ml/leaderboard/cartpole-v1/leaderboard)

Click the individual model to see evaluation results in detail, such as logs, plot, video recordings.

https://github.com/luna-ml/leaderboard is an example repository that shows how those evaluation environments and models are configured through the yaml configurations, scripts, and code.

### Alternatives

- Construct and maintain leaderboards manually, like https://github.com/openai/gym/wiki/Leaderboard.
   Since the evaluation result is submitted manually, difficult to re-evaluate when needed. Not all submissions produce the necessary evaluation outputs like video since there's no standard evaluation environment. In general, it is hard to scale.
- Create Kaggle challenge and leverage dashboard there.
   Management Kaggle challenges like updating evaluation criteria, creating new challenges, review submissions, etc are independent workflow from Github. So, unless the community defines and adopts a new workflow to maintain a leaderboard in Kaggle, it's difficult to use in a scalable way.

### Additional context

I'm working for Luna ML and the founder of the company.
And Luna ML is still in the very early stage of development. (actually, this is the first message I write about Luna ML in public) So there's a lot of room for us to listen to this community and enhance the service way the community needs. Wish, Luna ML benefits the community and I can have an opportunity to learn from it.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
I think this is a bit out of scope for that repo.

As mentioned in the [benchmark file](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/benchmark.md): "This benchmark is meant to check algorithm (maximal) performance, find potential bugs and also allow users to have access to pretrained agents."


>(Disclaimer: I work for Luna ML)

In fact, there exist already a public leaderboard (and you are probably aware of it) from Papers with Code. For example: https://paperswithcode.com/sota/continuous-control-on-pybullet-ant

>Also, opportunities to put an idea on the top of the leaderboard will encourage to add more new ideas.

I would disagree with that. Just trying to beat SOTA on a benchmark encourages hyper-parameter tuning, tricks and not necessary new ideas (that would perform worse at first).

**Comment by Miffyli** [comment]
> I would disagree with that. Just trying to beat SOTA on a benchmark encourages hyper-parameter tuning, tricks and not necessary new ideas (that would perform worse at first).

I second this. While the idea does sound nice, experience tells a different story (OpenAI Gym leaderboards, RL competitions, etc...). The results very rarely extend beyond that single environment.

**Comment by Leemoonsoo** [comment]
Thank @araffin  @Miffyli  for the answers!

Another perspective, If I say,

"Luna ML more focused on providing an automated evaluation environment that can handle data and evaluation criteria over time. But benchmark stable baseline3 is more like the SOTA benchmark, which not usually expect change of data or evaluation criteria over time. And this case existing leaderboard does the job"

would it be also right understanding?

> > I would disagree with that. Just trying to beat SOTA on a benchmark encourages hyper-parameter tuning, tricks, and not necessarily new ideas (that would perform worse at first).

> I second this. While the idea does sound nice, experience tells a different story (OpenAI Gym leaderboards, RL competitions, etc...). The results very rarely extend beyond that single environment.

I see. interesting. Just curious in a real-world experience, was there anything particular that encouraged new ideas?

**Comment by Miffyli** [comment]
> "Luna ML more focused on providing an automated evaluation environment that can handle data and evaluation criteria over time. But benchmark stable baseline3 is more like the SOTA benchmark, which not usually expect change of data or evaluation criteria over time. And this case existing leaderboard does the job"

I did not quite understand this part. SB3/SB3-zoo results are not for SOTA results, but for baseline results and for easy evaluation of new and existing algorithms (for bugs). There is no intent to rank algorithms by their performance in SB3 per se.

> I see. interesting. Just curious in a real-world experience, was there anything particular that encouraged new ideas?

Only if the competition sets strict rules or evaluation setups that encourage generalizable solutions, like [MineRL 2020](https://arxiv.org/pdf/2101.11071.pdf) (retraining during evaluation) and [ProcGen](https://www.aicrowd.com/challenges/neurips-2020-procgen-competition) (test over multiple unseen environments) competitions.
