### ISSUE TITLE
[Question] How to access the "ep_rew_mean" value from rollouts during training?

### ISSUE THREAD

**Issue by drozzy** [DLR-RM/stable-baselines3#400]
During training I see this value being printed to the terminal. How can I gain access to it in my callback so that I can log it to a file?
Thanks!

![Screenshot from 2021-04-19 00-15-14](https://user-images.githubusercontent.com/140710/115180791-713f8100-a0a4-11eb-8cc3-afb62ce1c6e2.png)

**Comment by Miffyli** [comment]
Somewhat related to #394.

If you just want to log those values to a file, see above issue. If you want to access them in a callback, these values are logged [here](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/on_policy_algorithm.py#L240) (you want to read `ep_info_buffer`).

**Comment by drozzy** [comment]
I understand. Thank you.
