### ISSUE TITLE
[Feature Request] support vec env evaluation with n_envs >1

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/stable-baselines3#402]
Description

Issue for #398

Right now, policy evaluation can only happen on vector environments with n=1 copies of the env. This is a small change to expand this.

Motivation and Context

-When doing hyperparameter tuning on certain environments, large numbers of evaluations are required to get accurate performance metrics. This lets that happen much faster.
-This is required for all the wrappers to work when PettingZoo environments are used

Both of these have been problems for be recently.

This change is so small that I don't know what tests if any would be sensible to add.

### Alternatives

Having to manage my own fork with this functionality

### Additional context

Similar libraries do this:

https://github.com/cpnota/autonomous-learning-library/blob/develop/all/experiments/parallel_env_experiment.py#L90

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
to sum up what needs to be edited/done:
- as we cannot ensure that all environments will terminate at the same time, the `n_eval_episodes` in `evaluate_policy` becomes a lower bound when using multiple envs and we need to warn the user about it. Some episodes will be truncated too.
- the check in `EvalCallback` can be lifted (as long as we warn users in the `evaluate_policy`) or maybe we should warn them here. There might be an issue when the number of eval episodes is greater than expected (we should probably truncate it to avoid unexpected results when plotting)

@Miffyli did I forget anything?

>https://github.com/cpnota/autonomous-learning-library/blob/develop/all/experiments/parallel_env_experiment.py#L90

For the implementation, I would go for a vectorized version of what you linked (avoid for loop if possible, but I'm not sure if it is).

**Comment by Miffyli** [comment]
> @Miffyli did I forget anything?

I have not spent brain-time on pondering this issue, but to be on the safest side, I would implement multi-env evaluation like this:
- Split `n_eval_episodes` as evenly as possible to all workers (or envs)
- Each worker/env does its share. No more, no less. No early termination
- If one worker/env completes its evaluation episodes sooner than the others, it will wait for them to finish as well.

This is to ensure we do not bias towards shorter episodes. This could be achieved with VecEnvs where the envs that already did their share keep `step`ing but their data is not used.

**Comment by araffin** [comment]
>This is to ensure we do not bias towards shorter episodes. This could be achieved with VecEnvs where the envs that already did their share keep steping but their data is not used.

Good point, but I'm a bit afraid of the complexity this would add...

**Comment by Miffyli** [comment]
> Good point, but I'm a bit afraid of the complexity this would add...

Actually scratch that. I ran some simulations and there does not seem to be a problem with the method you described (running all envs and terminating once satisfactory number of episodes have been completed).

**Comment by Miffyli** [comment]
Take that back: there is a bias towards shorter episodes when you increase number of environments (code 
[here](https://github.com/DLR-RM/stable-baselines3/files/6358182/multi_env_eval_simulation.zip))

![Figure_1](https://user-images.githubusercontent.com/1633800/115714207-89065600-a37f-11eb-9d15-081d8ce0c080.png)

Here `multi-env` evaluation refers to setup where you run N environments in parallel, continue `step`ing through them equally and continue until you have collected `n_eval_episodes` completed episodes (and their sum-of-rewards). You can see that especially with more envs and smaller `n_eval_episodes` there is considerable bias downwards.

**Comment by weepingwillowben** [comment]
So one way to implement a safe, unbiased approach without increasing software complexity is this:

1. Vector environment automatically resets as usual. 
2. Episode summaries are saved in a seperate list for each sub-environment .
2. Episode number k in vector environment element i is only counted in final evaluation if 1) every vector element j < i has k completed episodes and 2) every vector element j > i has  k-1 completed episodes.

This ensures that the environments which are counted in the final evaluation are picked in advance, independent of their length, so are unbiased. It is also efficient, that is, in the limit with large numbers of evaluations, there will be no wasted computation.

@Miffyli Does this sound right? Am I missing something?

**Comment by Miffyli** [comment]
@weepingwillowben 

This is a late-night reply, but I fail to see how this is more efficient than:

1) Use normal VecEnv
2) Each time episode ends, gather its stats and append to a single list
3) Once `n_eval_episodes` is reached, return results (i.e. the samples from on-going environments will be wasted)

Much like your suggestion, this does not waste computation in the limit of `n_eval_episodes`. 

A quick simulation code or an example where your method excels over this would be nice. This one seems much simpler to implement without additional if-elseing.

**Comment by weepingwillowben** [comment]
I think this may be exactly what I was thinking. Sorry if that wasn't clear.

**Comment by Miffyli** [comment]
@justinkterry 

Would you like to implement this, or would @weepingwillowben be interested to create a PR for this? :)

**Comment by weepingwillowben** [comment]
I can make a PR. Might have one  in a week or two.

**Comment by phiresky** [comment]
When this is implemented, will it be possible to use the training vec environment for evaluation as well instead of creating separate ones?

**Comment by Miffyli** [comment]
@phiresky Technically yes, but it should not be done. Doing an evaluation between training would lead to training environments being reset suddenly (from the point of view of training code), which changes distribution of samples.
