### ISSUE TITLE
Loading pre-trained feature extractor into a custom policy

### ISSUE THREAD

**Issue by salarrahili** [DLR-RM/stable-baselines3#409]
Hi, 
I am trying to find a way to load a pre-trained model (encoder) as a feature extractor to my custom policy. 
I could not find any example or document about such a case. Is there such a functionality for custom policy?
If yes, is there a way to specify when to backprop through it or not? (basically changing the requires_grad on and off)

**Comment by Miffyli** [comment]
Hey.

Two parts:

1) To load only specific parameters, you can use the [`set_parameters`](https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html#stable_baselines3.ppo.PPO.set_parameters) function. The function will only load parameters which you provide.

2) To freeze parameters (not update them), you can iterate over the model parameters and set `param.requires_grad=False` for parameters you do not want to be updated.

**Comment by araffin** [comment]
Hello,
to complement @Miffyli answer, the feature extractor is just a PyTorch module, so you can access/set/freeze parameters the same way you would do it for PyTorch.
We have an example on manipulating parameters in the doc: https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#accessing-and-modifying-model-parameters

If you freeze the feature extractor, I would recommend you to use a `gym.Wrapper` instead (this will save computation and memory).

**Comment by salarrahili** [comment]
Thank for your quick responses.
