### ISSUE TITLE
 [question] Should collect_rollouts have env.reset() at the end of each episode?

### ISSUE THREAD

**Issue by mloo3** [DLR-RM/stable-baselines3#41]
I was looking at the `collect_rollouts` function in `base_class.py`, and it doesn't seem to call `env.reset()` to reset the environment between each episode. 
https://github.com/DLR-RM/stable-baselines3/blob/403fff5d5063c31368098502f3cc66f20b6e956f/stable_baselines3/common/base_class.py#L893-L901

Comparing that to sb, which does seem to call `env.reset()`
https://github.com/hill-a/stable-baselines/blob/c20df905363cb6a3649ea275a0be0bf82d6a575f/stable_baselines/sac/sac.py#L474-L478

Is there some place that `env.reset()` is being called that I am not seeing, or could it be that I am not quite undersating how collect rollouts should work?

**Comment by PartiallyTyped** [comment]
Yes, if you notice the type of the environment, it needs to be `VecEnv`.

`VecEnv` is a wrapper around environments that collects and stacks observations together. It automatically reset the environment on done.

**Comment by mloo3** [comment]
That clears things up. Thanks!
