### ISSUE TITLE
Logging addional values from info dictionary in evaluate_policy in EvalCallback

### ISSUE THREAD

**Issue by JeremyAlain** [DLR-RM/stable-baselines3#410]
### Question
Hi there, 
First of all thanks a lot for this great repo, I really like it. My question is basically if there is a very simple way to log (e.g. for tensorboard) additonal metrics that are contained in the info buffer during the evaluate_policy function that is called in the EvalCallback during training? 

Let me explain what I mean in more detail. I am fully aware that if I call evaluate_policy on its own (after training for e.g.) I can pass a Callback function which then accesses the info field and logs additional metrics. However I feel like this is not possible during training. I would like to use the default way of evaluating my policy that is provided by you, i.e. i pass an environment to eval_env field of the learn() function. This will then create an EvalCallback class which in turn calls evaluate_policy in the _on_step function. evaluate_policy does actually have the info field, but does not return it. Which means EvalCallback has no way of accessing the info field that is produces in evaluate_policy and there is no way of logging additional metrics that are contained in the info field (as far as I can tell). 

Now yes I could completely rewrite the EvalCallback class and make sure that it passes another callback to evaluate_policy such that I can log additional metrics. However i feel like this is not the best option because I would have to copy and paste a lot of your code in order to change a small thing. Also I feel like it's safer to use the default way provided by you. So to sum up I believe that there probably is a simple way of doing it, but I am really not aware of how to do it. 

One idea I had was to wrap my evaluation environment into the Monitor class and then log certain things from there into a file and later on read it back from a different callback. But I am not sure if that is the best option. 

Update: I tried out my idea and it would work in principle. But at the end I realized that the Monitor class in the step() function only logs certain info fields when the episode is over, i.e. it does not allow one to sum up all the episode rewards and log them . 

thanks for your help

**Comment by araffin** [comment]
>My question is basically if there is a very simple way to log (e.g. for tensorboard) additonal metrics that are contained in the info buffer during the evaluate_policy function that is called in the EvalCallback during training?

>Now yes I could completely rewrite the EvalCallback class and make sure that it passes another callback to evaluate_policy such that I can log additional metrics. However i feel like this is not the best option because I would have to copy and paste a lot of your code in order to change a small thing.

What you are describing is currently the way to go.
In fact, that is what I'm doing for logging the success rate (see https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/callbacks.py#L335).

The thing is each user would have a very specific usage, so the best is to define a custom `EvalCallback` for that.

Regarding the `Monitor` wrapper: yes it only logs things once per episode (again, see what I do in the rl zoo to log the training success rate: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/exp_manager.py#L491).
If you want to log more training values, best si to define a custom `gym.Wrapper`.

**Comment by JeremyAlain** [comment]
Ok thanks a lot :) good to know that it is the intended way to go! I understand that making it customisable for everybody might not easily generalise to all the use cases.
