### ISSUE TITLE
[Question] How should we cite Stable-Baselines3?

### ISSUE THREAD

**Issue by cboettig** [DLR-RM/stable-baselines3#411]
### Question

How should we cite Stable-Baselines3?  Is there a related article or preprint you would like us to cite?  Would you consider adding a `codemeta.json` (see https://codemeta.github.io/) or CITATION file to the project, which could be parsed by tools such as [CiteAs](https://citeas.org/about) and [Software Heritage Archive](https://archive.softwareheritage.org/)?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
There is a [bibtex entry in the README file](https://github.com/DLR-RM/stable-baselines3#citing-the-project) you should use :)

**Comment by araffin** [comment]
> There is a [bibtex entry in the README file](https://github.com/DLR-RM/stable-baselines3#citing-the-project) you should use :).
> 
> The suggestions do sound nice though, especially if some bigger archival project is using them.

and there is a paper under review too...

**Comment by araffin** [comment]
Our [JMLR Paper](http://jmlr.org/papers/v22/20-1364.html) was finally published =), the bibtex is:

```bibtex
@article{stable-baselines3,
  author  = {Antonin Raffin and Ashley Hill and Adam Gleave and Anssi Kanervisto and Maximilian Ernestus and Noah Dormann},
  title   = {Stable-Baselines3: Reliable Reinforcement Learning Implementations},
  journal = {Journal of Machine Learning Research},
  year    = {2021},
  volume  = {22},
  number  = {268},
  pages   = {1-8},
  url     = {http://jmlr.org/papers/v22/20-1364.html}
}
```
