### ISSUE TITLE
[Feature Request] Flexible OnPolicyAlgorithm Policies

### ISSUE THREAD

**Issue by 09tangriro** [DLR-RM/stable-baselines3#412]
### 🚀 Feature

Flexible `OnPolicyAlgorithm` Policies to support more complex on policy algorithms.

### Motivation

I'm adding PPG to the Contrib library (an on-policy algorithm). In doing so, I have created a policy which extends `BasePolicy` (so that it can be registered as 'MlpPolicy'/'CnnPolicy') but the `OnPolicyAlgorithm` base class only accepts `ActorCriticPolicy` as the `policy_base`. I could extend the PPG policy from `ActorCriticPolicy` but this isn't supported by the `register_policy` method. The only option thus far is to register under a different policy name (e.g. 'PpgMlpPolicy') which goes against the design philosophy of the library.

### Pitch

Add `policy_base` input to the `OnPolicyAlgorithm` base class just like the `OffPolicyAlgorithm` base class.

### Alternatives

In `register_policy`, first check for extensions from subclasses of `BasePolicy` so other policy extentions can be registered under the standard string denominations.

### Additional context

NOTE: sorry for this bit being messy, I'm unsure how to make multi-lines of code layout :(

This is what the new `OnPolicyAlgorithm` definition would look like:
```python
def __init__(
        self,
        policy: Union[str, Type[ActorCriticPolicy]],
        env: Union[GymEnv, str],
        learning_rate: Union[float, Schedule],
        n_steps: int,
        gamma: float,
        gae_lambda: float,
        ent_coef: float,
        vf_coef: float,
        max_grad_norm: float,
        use_sde: bool,
        sde_sample_freq: int,
        **policy_base: Type[BasePolicy] = ActorCriticPolicy,**
        tensorboard_log: Optional[str] = None,
        create_eval_env: bool = False,
        monitor_wrapper: bool = True,
        policy_kwargs: Optional[Dict[str, Any]] = None,
        verbose: int = 0,
        seed: Optional[int] = None,
        device: Union[th.device, str] = "auto",
        _init_setup_model: bool = True,
        supported_action_spaces: Optional[Tuple[gym.spaces.Space, ...]] = None,
    ):

        super(OnPolicyAlgorithm, self).__init__(
            policy=policy,
            env=env,
            policy_base=policy_base,
            learning_rate=learning_rate,
            policy_kwargs=policy_kwargs,
            verbose=verbose,
            device=device,
            use_sde=use_sde,
            sde_sample_freq=sde_sample_freq,
            create_eval_env=create_eval_env,
            support_multi_env=True,
            seed=seed,
            tensorboard_log=tensorboard_log,
            supported_action_spaces=supported_action_spaces,
        )

```
A rudimentary example of `register_policy` check for subclasses:

```python
    sub_class = None
    for cls in ActorCriticPolicy.__subclasses__():
        if issubclass(policy, cls):
            sub_class = cls
            break
    if sub_class is None:
        for cls in BasePolicy.__subclasses__():
            if issubclass(policy, cls):
                sub_class = cls
                break
    if sub_class is None:
        raise ValueError(
            f"Error: the policy {policy} is not of any known subclasses of BasePolicy!"
        )
```
### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by Miffyli** [comment]
Sounds like a good addition, especially given that off-policy algos already have this (works as a good role model for this one). @araffin any comments? 

PS: You can do neat codeblocks by writing \``` code like this \``` :)

**Comment by araffin** [comment]
>Sounds like a good addition, especially given that off-policy algos already have this (works as a good role model for this one). 

Looks good too ;) (the reason it is there for off-policy algorithms was because of the `HER` algorithm that works as a wrapper)
We just need to be careful that is does not break previously saved models (but should be fine).

**Comment by 09tangriro** [comment]
Cool! I'll get to work on a PR :)
(thanks for the formatting tip too @Miffyli!)
