### ISSUE TITLE
VecNormalize in zero-shot learning experiment

### ISSUE THREAD

**Issue by ErikVester** [DLR-RM/stable-baselines3#420]
Hi, 

I would like to test my model’s generalisation capabilities in a zero-shot learning experiment. 
Is there a way to still use the VecNormalize wrapper in this scenario? My observations for the task I want to transfer/generalise to can be made of the same observation space, however the observations will of course be different from the original task and therefore the normalisation will probably not work well? 

Would it in this case be best to just train and test without VecNormalize or would there still be another solution? 

Kind regards, 

Erik 

### Checklist

- [x ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
I think this falls in the realm of experimentation to see what works and what does not. On one hand, VecNorm is sometimes crucial for learning, but it "enforces" the agent to expect normally distributed data, which probably suddenly changes when you change environments. On the other hand, same shift will happen with or without normalization, but at least you would have less moving parts if you drop VecNorm.

**Comment by ErikVester** [comment]
Ok, thanks! I will try out both and see what works best :) Thanks for thinking along!
