### ISSUE TITLE
[Question] How the rewards are incorporated into the learning process?

### ISSUE THREAD

**Issue by GPrathap** [DLR-RM/stable-baselines3#421]
### Question

Actually, I have an environment in which I am trying to learn the system dynamics. Since my example is quite big, I am using the following example to clarify the problem I have. 

**The problems** 

 1.Can I know where actually environment reword incorporate into the learning process? 

 2.Is there any upper and lower bound for the rewards?
    

```
     from stable_baselines.common.policies import MlpPolicy
     from stable_baselines.common.vec_env import DummyVecEnv
     from stable_baselines import PPO2
    
     env = gym.make('CartPole-v1')
       
    
     model = PPO2(MlpPolicy, env, verbose=1)
     model.learn(total_timesteps=10000)
    
     obs = env.reset()
     for i in range(1000):
         action, _states = model.predict(obs)
         obs, rewards, dones, info = env.step(action)
         env.render()

```
I could not find any information regarding this yet. I asked in [SO](https://stackoverflow.com/questions/67420287/how-the-rewards-are-incorporated-into-the-learning-process) but still haven't got any clue

**Comment by Miffyli** [comment]
I do not quite understand your question. If you want to understand how the algorithm works, I recommend reading things like [OpenAI Spinning-up](https://spinningup.openai.com/en/latest/user/introduction.html). Stable-baselines code is not meant for new-comers for understanding the algorithms.

**Comment by GPrathap** [comment]
Maybe I am wrong, what I want to know is that do we have to normalize reward or there is no such restriction when defining a reward function? If the reward is incorporated when learning the model, i.e.,  `model.learn`,  it has a direct effect. I want to clarify whether the reward is incorporated when learning the policy or not?

**Comment by Miffyli** [comment]
Yes, reward is used when training the policy. However in the above example the code inside for loop is only doing evaluation, no training happens there. All training happens behind the `learn` function.
