### ISSUE TITLE
When Customizing Policy Network, how to define Dropout layer in a fully-connected network?

### ISSUE THREAD

**Issue by watermeloncq** [DLR-RM/stable-baselines3#422]
According to the doc of Custom Policy Network, a fully-connected network is formatted like 'dict(qf=[400, 300], pi=[64, 64])'. But if I want to insert dropout in a fully-connected network, how to do it?

**Comment by Miffyli** [comment]
The answer is in the same documentation: you have to create a custom policy class, where-in you also add dropout layers and whatnot.

**Comment by watermeloncq** [comment]
> The answer is in the same documentation: you have to create a custom policy class, where-in you also add dropout layers and whatnot.

Thank you for your answer. But I still have a question: If I create a custom policy class in which the dropout layer being defined in a fully-connected network, does this means that I cannot define a fully-connected network  by using the formatted code like 'dict(qf=[400, 300], pi=[64, 64])'?

**Comment by Miffyli** [comment]
You can, if you use those parameters in your custom policy class (see [the example](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#advanced-example)).

**Comment by watermeloncq** [comment]
I will have a try, thank you again, best wishes.

**Comment by araffin** [comment]
Related https://github.com/DLR-RM/stable-baselines3/issues/535
