### ISSUE TITLE
[Enhancement] Support Different VecEnvWrapper Depths

### ISSUE THREAD

**Issue by scottemmons** [DLR-RM/stable-baselines3#426]
Is there a reason that this while loop assumes `env` and `eval_env` are wrapped in the same number of `VecEnvWrapper`s?
https://github.com/DLR-RM/stable-baselines3/blob/2ada2dd0b2b10f71d0be38ce032d49391b875c4e/stable_baselines3/common/vec_env/__init__.py#L66
This assumption is causing a bug for me in one of my use cases. The following code relaxes this assumption and fixes my use case:
```
while isinstance(env_tmp, VecEnvWrapper) or isinstance(eval_env_tmp, VecEnvWrapper)
    if isinstance(env_tmp, VecNormalize):
        eval_env_tmp.obs_rms = deepcopy(env_tmp.obs_rms)
        eval_env_tmp.ret_rms = deepcopy(env_tmp.ret_rms)
    try:
        env_tmp = env_tmp.venv
    except AttributeError:
        pass
    try:
        eval_env_tmp = eval_env_tmp.venv
    except AttributeError:
        pass
```

**Comment by Miffyli** [comment]
Definitely seems like unintended behaviour to me. To me it seems like code does this:

a) Find the VecNormalize of both envs (might be at different "depths")
b) Update stats of eval-env normalizer to match env's

But this code assumes that the two environments have VecNormalize at the same depth, and for some reason also seems to support multiple levels of VecNormalize wrappers (???).

@araffin Can you confirm if above is the desired functionality? If so, a PR to update it would be welcome :)

**Comment by araffin** [comment]
>Is there a reason that this while loop assumes env and eval_env are wrapped in the same number of VecEnvWrappers?

This is intended, why would you wrap the eval env differently? Allowing so (in fact it is the case when `VecNormalize` is not involved) would lead to silent errors.

The `EvalCallback` will in fact output a warning if it is not the case.

>a) Find the VecNormalize of both envs (might be at different "depths")

We already have something for that in fact...

**Comment by Miffyli** [comment]
Ah ok. How about adding exceptions if VecNormalize is not at the same depth here as well (with clarifying error message about this), and breaking once the first VecNormalize is found? I think some clarifying errors should be added to avoid similar confusion in future :)

**Comment by scottemmons** [comment]
My use case is multi-agent RL using PettingZoo. In order to train multiple agents as if they were a single agent, the PettingZoo training environment is converted into a `VecEnv` where each "env" is a different agent. At evaluation time, however, this trick doesn't work because `EvalCallback` [assumes](https://github.com/DLR-RM/stable-baselines3/blob/2ada2dd0b2b10f71d0be38ce032d49391b875c4e/stable_baselines3/common/callbacks.py#L308) there is only one evaluation environment. So I wrapped my training env and my evaluation env differently. (The training env uses `VecMonitor` whereas the testing env uses `Monitor`.)

**Comment by scottemmons** [comment]
Is it okay to apply `VecMonitor` to a `VecEnv` where each individual `env` already has `Monitor` applied? (The `VecEnv` was created with `stable_baselines3.common.env_util.make_vec_env`.)

Thanks - once #402 is done that will help me, too!

**Comment by araffin** [comment]
>Is it okay to apply VecMonitor to a VecEnv where each individual env already has Monitor applied? (The VecEnv was created with stable_baselines3.common.env_util.make_vec_env.)

It is unless you have some low level wrappers that changes the reward: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/vec_env/vec_monitor.py#L43

**Comment by scottemmons** [comment]
Great - these solutions should work for me!
