### ISSUE TITLE
[Feature Request] Full KL Divergence

### ISSUE THREAD

**Issue by 09tangriro** [DLR-RM/stable-baselines3#430]
### 🚀 Feature

Add a full form KL Divergence function that is compatible with the `Distribution` wrappers and can easily be called.

### Motivation

When implementing the PPG algorithm in the Contrib library, it would be useful to have a full form KL Divergence function in the `distributions.py` file which is compatible with the `Distribution` wrappers around the PyTorch distributions. OpenAI also use the full form equation for KL Divergence in their PPG implementation.

### Pitch

I want to add a `kl_divergence(dist1: Distribution, dist2: Distribution) -> th.Tensor` method to the `distributions.py` file which would essentially be a wrapper around the PyTorch `kl_divergence` function. As well as PPG, I think this would be a useful feature in general.

### Alternatives

N/A

### Additional context

N/A

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
sounds good to me ;)
Please go ahead and do not forget to add tests.
