### ISSUE TITLE
verbose=1, SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by KarimHFahmy** [DLR-RM/stable-baselines3#434]
### 🐛 Bug

A syntax error on in verbose parameter

### To Reproduce

Steps to reproduce the behavior.

```import gym
import highway_env
import numpy as np

from stable_baselines3 import HerReplayBuffer, SAC, DDPG, TD3
from stable_baselines3.common.noise import NormalActionNoise

env = gym.make("parking-v0")

# Create 4 artificial transitions per real transition
n_sampled_goal = 4

# SAC hyperparams:
model = SAC(
    "MultiInputPolicy",
    env,
    replay_buffer_class=HerReplayBuffer,
    replay_buffer_kwargs=dict(
      n_sampled_goal=n_sampled_goal,
      goal_selection_strategy="future",
      # IMPORTANT: because the env is not wrapped with a TimeLimit wrapper
      # we have to manually specify the max number of steps per episode
      max_episode_length=100,
      online_sampling=True,
    )
    verbose=1,
    buffer_size=int(1e6),
    learning_rate=1e-3,
    gamma=0.95,
    batch_size=256,
    policy_kwargs=dict(net_arch=[256, 256, 256]),
)

model.learn(int(2e5))
model.save("her_sac_highway")

# Load saved model
# Because it needs access to `env.compute_reward()`
# HER must be loaded with the env
model = SAC.load("her_sac_highway", env=env)

obs = env.reset()

# Evaluate the agent
episode_reward = 0
for _ in range(100):
    action, _ = model.predict(obs, deterministic=True)
    obs, reward, done, info = env.step(action)
    env.render()
    episode_reward += reward
    if done or info.get("is_success", False):
        print("Reward:", episode_reward, "Success?", info.get("is_success", False))
        episode_reward = 0.0
        obs = env.reset()
```

 ```File "<ipython-input-40-4fe65ec13cb2>", line 26
    verbose=1
          ^
SyntaxError: invalid syntax
```
### Expected behavior
I was trying to run the highway-parking environment. I tried it a few days ago and it ran perfectly. Now whenever I run it it shows this syntax error.

### System Info

Describe the characteristic of your environment:
 *Used the conda.yml file Highway and Baselines3 were PIP installed
 * No GPU (but the same error appears on colab as well)
 * 3.6

### Additional context
The example is here https://github.com/DLR-RM/stable-baselines3/blob/master/docs/guide/examples.rst

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,
please fill up the issue template completely.

**Comment by KarimHFahmy** [comment]
Sorry, Now It is filled out. It is a very basic problem that came out of nowhere

**Comment by araffin** [comment]
>Sorry, Now It is filled out. It is a very basic problem that came out of nowhere

Please use markdown codeblock to format everything properly (again, as explicitely mentioned in the issue template...)

**Comment by araffin** [comment]
I see the issue, we need to add a comma after the parenthesis. Will push a fix soon.

**Comment by KarimHFahmy** [comment]
Thank you!
