### ISSUE TITLE
[Feature Request] Pass additional wrapper parameters to helper function make_vec_env

### ISSUE THREAD

**Issue by amy12xx** [DLR-RM/stable-baselines3#442]
### 🚀 Feature

make_vec_env() allows a wrapper function to be passed, that is applied to the environment. But does not support additional wrapper parameters to be passed. wrapper_kwargs argument can be included in make_vec_env to pass the additional parameters. It's a very simple fix, and I don't mind submitting a PR for it, if you agree.

**Comment by araffin** [comment]
Hello,
It sounds like a reasonable feature, please go ahead and don't forget the checklist (notably adding tests).

You can also already pass a function to the constructor (that's what is done in the zoo to support wrappers with arguments, as in https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/sac.yml#L79) or use a `VecEnvWrapper` afterward.

Please fill in the issue template completely next time ;) (notably the alternative section).
