### ISSUE TITLE
[Bug] CheckpointCallback save_freq not working

### ISSUE THREAD

**Issue by Dylan-Kerler** [DLR-RM/stable-baselines3#446]
### 🐛 Bug

Add a `save_freq` of 50,000 to `CheckpointCallback` and expect it to save the model every 50,000 steps but it doesn't - it saves roughly every million steps or so.

Here is my code:

```python
# Enviroment
trade_env = TradeEnv
env = make_vec_env(
  trade_env, n_envs=32, vec_env_cls=SubprocVecEnv,
  env_kwargs=dict(days_lookback=1, episode_days_duration=1, fee=0.000, slippage=0.000)
)

# Model
policy_kwargs = dict(features_extractor_class=CustomNet, features_extractor_kwargs=dict(features_dim=128),)
model = PPO(
  "MlpPolicy", env, 
  policy_kwargs=policy_kwargs, verbose=1, 
  gamma=0.9995, device="cuda", 
  tensorboard_log="./trade_env_1_logs/",
  learning_rate=0.0001,
) 

# Train
checkpoint_callback = CheckpointCallback(save_freq=50000, save_path=base_path + 'trade_model/', name_prefix='trade_model')
model.learn(total_timesteps=3000000, tb_log_name="main", callback=checkpoint_callback)
```

Here is what gets saved after all 3,000,000 steps of training are completed - just one model at 1,600,000 steps:

![Screenshot 2021-05-22 at 11 16 39](https://user-images.githubusercontent.com/37438950/119223064-35f30080-baef-11eb-953c-b689c52f1c0e.jpg)

Expected it to save a model at every 50,000 steps but it doesn't.

**Comment by araffin** [comment]
Hello,
this expected behavior (even though the documentation is not so clear), you need to divide by the number of envs, as done in the rl zoo : https://github.com/DLR-RM/rl-baselines3-zoo/blob/6af373e5269f5ceb06eeece5d81423fdec98aefc/utils/exp_manager.py#L383

we would appreciate a PR that clarify that.
