### ISSUE TITLE
[Question] By default, are gym environments normalized?

### ISSUE THREAD

**Issue by zhihanyang2022** [DLR-RM/stable-baselines3#455]
### Question

By default setting, are the observations of gym environments normalized, in any way?

### Additional context

I have parsed through the codebase, and my answer seems to be no. But I hoped to double-check. Thanks!

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
they are not normalized by SB3 by default, unless the observations are images.

**Comment by Mickeyyyang** [comment]
> 

Hi, where does SB3 know that the observation input I gave is an image? Is it reflected in the code?

**Comment by araffin** [comment]
> Hi, where does SB3 know that the observation input I gave is an image? Is it reflected in the code?

We use heuristics: https://github.com/DLR-RM/stable-baselines3/blob/88e1be9ff5e04b7688efa44951f845b7daf5717f/stable_baselines3/common/preprocessing.py#L27
But this can be bypassed in case you have a false positive (something that looks like an image but is not or should not be normalized) by passing `normalize_images=False` to the policy constructor (cf. doc).
