### ISSUE TITLE
Documentation improvements surrounding callback arguments when using vector environments

### ISSUE THREAD

**Issue by justinkterry** [DLR-RM/stable-baselines3#459]
### 📚 Documentation

Before looking through how eval_freq is calculated in exp_manager.py in RL zoo, I genuinely could never figure out how to correctly choose eval_freq and related arguments when using vector environments in SB3. I tried twice before and am only a partial idiot (and at minimum have used SB much more than most people reading the docs at this point). The documentation for this likely should be improved both at the code and website levels. I'm willing to do a PR for all thisthis weekend, but I don't 100% know what the best way would be.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by justinkterry** [comment]
Tangentially related to https://github.com/DLR-RM/rl-baselines3-zoo/issues/103

**Comment by araffin** [comment]
Hello,
are you talking about https://github.com/DLR-RM/stable-baselines3/issues/446 that was fixed in https://github.com/DLR-RM/stable-baselines3/pull/450 ?

**Comment by justinkterry** [comment]
I didn't see that, I apologize. I would argue that something like the vector env notes that PR adds to the code should be added  to the website though.

**Comment by araffin** [comment]
>. I would argue that something like the vector env notes that PR adds to the code should be added to the website though.

it is there (see warning): https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html#checkpointcallback

and here (warning again): https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html#stable_baselines3.common.callbacks.EvalCallback
