### ISSUE TITLE
Potential continuity bug in the replay buffer when calling .learn multiple times

### ISSUE THREAD

**Issue by PartiallyTyped** [DLR-RM/stable-baselines3#46]
```python
agent.learn(N)
agent.learn(N)
# ER isn't reset but the environment is.
```
This isn't a bug - as is - but the exact behaviour needs to be defined in order to decide what is the correct way to deal with a bug in ER in the DQN branch:

_Originally posted by @PartiallyTyped in https://github.com/DLR-RM/stable-baselines3/pull/28#issuecomment-640253275_

**Comment by araffin** [comment]
What do you propose as a fix?
I would say set `done=True` to the last observation (index `self.pos -1`), no?
I don't see a better one yet...

**Comment by PartiallyTyped** [comment]
> I would say set done=True to the last observation (index self.pos -1), no?

This messes up the MDP though, it's the same reason we use `TimeFeatureWrapper`, only in this case, *we* alter the signal.

**Comment by araffin** [comment]
>only in this case, we alter the signal.

Well, the user alters the signal, otherwise, he just need to use `reset_num_timesteps=False`

**Comment by PartiallyTyped** [comment]
That's true. I think that we should state that when `reset_num_timesteps=True` the buffer is emptied/freed. This resolves the problem without a hacky or weird solution. If the user wants to fill in the buffer, they can do it with callbacks imho.

**Comment by araffin** [comment]
>the buffer is emptied/freed. 

Sounds quite radical compared to stopping one trajectory early.

**Comment by araffin** [comment]
I'm also thinking about having 2 replay buffer implementations, one that is simple and easy to read and one that is memory efficient. But I don't like duplicating code...

**Comment by PartiallyTyped** [comment]
Maybe for the time being, we can keep the plain buffer until we resolve these issues, then again, a single transition is nothing when we can effectively double the size.

**Comment by araffin** [comment]
I decided to disable the memory efficient variant by default and add a warning if the user is doing multiple `.learn()` calls.
I also decided to truncate the trajectory (less radical than clearing the buffer)

See https://github.com/DLR-RM/stable-baselines3/pull/28/commits/8193f5a9e2fab47bf1854e8e8db5061892919aa8

**Comment by PartiallyTyped** [comment]
LGTM! Feel free to close this.
