### ISSUE TITLE
[Question] When does env.reset happen for DDPG?

### ISSUE THREAD

**Issue by zhihanyang2022** [DLR-RM/stable-baselines3#460]
### Question

In my understanding, this is what DDPG, TD3 and SAC use to collect rollouts:

https://github.com/DLR-RM/stable-baselines3/blob/a038044d11d7d5e4676c512c1561e9d3d33d6713/stable_baselines3/common/off_policy_algorithm.py#L553

However, I don't see when the environment is reset upon done. 

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
answer is in the doc (2nd note): https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html
