### ISSUE TITLE
[Question] what is `batch_size` ?

### ISSUE THREAD

**Issue by externalsupplierstaff** [DLR-RM/stable-baselines3#461]
### Question

Hey! Well, just to confirm.
Is batch size comprised of consecutive variables in a trajectory or is it related to "independent" samples like in computer vision?

### Additional context

I could not find in the documentation the definition of batch size. I would like it to be something like "independent trajectories put in a tensor together" but my understanding is something more like "consecutive variables of the same trajectory put in a tensor together".

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
In case of PPO, it is like in computer vision: you take a trajectory of samples, shuffle them and train on them in mini-batches of size `batch_size`.

**Comment by externalsupplierstaff** [comment]
so, this is only one trajectory, thanks for clarifying (btw the "computer vision" type I referred to was related to different trajectories, i.e. parallelizing trajectories in the batch dimension, but the second part of the answer is crystal clear).

I'm currently using a static (non trainable) vgg16 to convert each state (image) to observations (features) in my partially observable environment. This means the observations are resulting from many individual forward passes over the network and only then being batched. To use the batches in the network I should move it to be a part of the policy network. Is this right?

**Comment by Miffyli** [comment]
Yup, if you do it on the environment level, this happens as you described it. You need to change the `feature_extractor` part if you want to use custom networks.
