### ISSUE TITLE
[Question] why is the parallelized ppo with custom env not logging rewards?

### ISSUE THREAD

**Issue by externalsupplierstaff** [DLR-RM/stable-baselines3#462]
### Question

I find that most variables (fps, entropy_loss, etc.) are being logged (visualized in tensorboard and in the terminal output) but i don't see `ep_mean_rew`, as I'm used to. I'm using a custom env.
### Additional context

The custom env I'm using works well in this sense for the non-parallelized ppo: I can see len and reward means being logged.

some other unrelated things that could be issues that I decided not to open but would like an opinion on
- should I open another question with the following list?
- it would be nice to have a big picture of how the code works in the documentation. This is, what's implemented in the algorithmic side, what's implemented in the environment side, and the interface between them (notably, collect rollout). I find the only way to know this is to reading the code directly, and it's pretty nested
- I'm not using `EvalCallback` because when I wrap it in a SubprocVecEnv I get a warning saying this should be a Monitor, and when I wrap it in a Monitor it gives that it's not the same type of the trial (which is SubprocVecEnv). I remember this working properly at some point, any thought about my potential implementation bug?
- how do I get a progress bar? I'm using a custom callback and adding 1 `on_step`. But the total number seems inaccessible. I'm estimating it as `self.locals['total_timesteps'] / 4` when 4 is the number of envs, hardcoded. Is this correct? is there a nicer way?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Note that we do not offer custom tech support for "should I do X or Y" situations. Almost all answers are in the doc. If something is not covered, it is probably not in the library. These issues are mainly for bugs and enhancements. 

IIRC `ep_mean_rew` is not logged under same name but under `episodic_reward` or something like this (@araffin can you confirm? I have not used tensorboard)

**Comment by araffin** [comment]
The main issue is that your problem is related to a custom gym env and you did not fill the proper template, which normally include minimal code to reproduce the problem.

As mentioned in the doc, you must use the `Monitor` wrapper or the `VecMonitor` (done automatically when using `make_vec_env`) to have the episodic reward logged.

**Comment by externalsupplierstaff** [comment]
I will separate the questions in several issues then, thanks

**Comment by araffin** [comment]
>how do I get a progress bar? I'm using a custom callback and adding 1 on_step. But the total number seems inaccessible. I'm estimating it as self.locals['total_timesteps'] / 4 when 4 is the number of envs, hardcoded. Is this correct? is there a nicer way?

We have a tutorial for that, see "callback" notebook in https://github.com/araffin/rl-tutorial-jnrr19
