### ISSUE TITLE
[Question] When n_step=2048 why is rollout only 500 long?

### ISSUE THREAD

**Issue by drozzy** [DLR-RM/stable-baselines3#463]
Given the following simple mwe:
![Screenshot from 2021-06-05 11-22-07](https://user-images.githubusercontent.com/140710/120896626-6b6c1380-c5f0-11eb-8111-e098bd9c3f21.png)

This is the result of training:
![Screenshot from 2021-06-05 11-18-47](https://user-images.githubusercontent.com/140710/120896634-732bb800-c5f0-11eb-9a9c-22d741dfd684.png)

But why is the rollout reward 500 for cartpole? I can't find the number `500` anywhere in the defaults of the PPO code.
The `n_step` is set to 2048 by default, so shouldn't the rollout converge to `2048`?
https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/ppo/ppo.py#L73

**Comment by drozzy** [comment]
Nevermind, it is because the CartPole-v1 has max_episode_steps=500.

**Comment by araffin** [comment]
Hello,

>But why is the rollout reward 500 for cartpole? 

the answer lies in the task description: `CartPole-v1` has a timeout of 500 timesteps (see https://github.com/openai/gym/blob/master/gym/envs/__init__.py#L63), so the maximum episodic reward you can get is 500 (+1 for each step).

**Comment by araffin** [comment]
>Nevermind, it is because the CartPole-v1 has max_episode_steps=500.

voilà ...

**Comment by drozzy** [comment]
Thank you!
