### ISSUE TITLE
[Question] Where to change parameters of Actor Critic Policy?

### ISSUE THREAD

**Issue by TomoCoder123** [DLR-RM/stable-baselines3#465]
How do you change the parameters of the A2C policy without creating a custom class? I am a little confused about where to instantiate the MlpPolicy and change the parameters.

**Checklist**
- [x] I have read the documentation
- [x] I have checked that there is no similar issue in the repo (required)

**Comment by araffin** [comment]
Hello,

> I have read the documentation

Are you sure?

https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html

and what type of parameters are you referring too?

**Comment by TomoCoder123** [comment]
I am trying to change the net_arch parameter in MlpPolicy.

**Comment by araffin** [comment]
>I am trying to change the net_arch parameter in MlpPolicy.

Then, what is missing from the doc?

**Comment by TomoCoder123** [comment]
Oh thanks, I figured it out.
