### ISSUE TITLE
[Question] Explanation of entropy_loss parameter

### ISSUE THREAD

**Issue by Zymoo** [DLR-RM/stable-baselines3#466]
Hello, I was working with your PPO model and while plotting the training results I saw a plot of entropy_loss. I could not find any explanation of how this parameter should behave during the training session. I understand that entropy itself should rather decrease over time, yet 'entropy loss' combination makes me pretty confused. Should this parameter get close to 0 during the training as it does in my results (screenshot attached below).

![image](https://user-images.githubusercontent.com/33435149/120920995-d2a5c880-c6c1-11eb-99ad-1249173fc2b9.png)

As far as I know other plots seem to behave as they should.

**Comment by araffin** [comment]
Hello,

>I could not find any explanation of how this parameter should behave during the training session.

Have you read A2C/PPO paper?

The entropy loss is defined like that:
https://github.com/DLR-RM/stable-baselines3/blob/88e1be9ff5e04b7688efa44951f845b7daf5717f/stable_baselines3/ppo/ppo.py#L237

and combined with the other losses here:
https://github.com/DLR-RM/stable-baselines3/blob/88e1be9ff5e04b7688efa44951f845b7daf5717f/stable_baselines3/ppo/ppo.py#L241

when `ent_coef  > 0`, it favors exploration by avoiding the policy to collapse to a deterministic one too soon.
With this loss, we want to maximize the entropy, which is the same as minimizing the negative entropy.

Over training, the policy will become more and more deterministic and therefore the entropy (and negative entropy, aka entropy loss here) will come close to zero.
Normally, if you have an `ent_coef` too large, the policy will converge to uniform sampling when using discrete actions (maximizing its entropy) and you will observe a plateau in the loss.

**Comment by Zymoo** [comment]
Thank you, appreciate the answer so much! I've read partially the original PPO paper (not A2C to be honest) with additional explanations and checked out your code, however still wasn't sure how to interpret this metric. Your explanation was exactly what I needed! Therefore closing the issue.

**Comment by sapountzis** [comment]
How should I interpret this?? Is it normal?? (ent_coef = 0.03)

![image](https://user-images.githubusercontent.com/48756095/212566211-d19de0d8-f97b-472a-8a88-2b4515a7cf4e.png)
