### ISSUE TITLE
How to save the normalization statistics when saving the best model?

### ISSUE THREAD

**Issue by manuelsager** [DLR-RM/stable-baselines3#468]
### Question

The EvalCallback() offers the possibility to save the best model according to the performance in the eval environment. Moreover, the example in the documentation emphasizes the importance of saving the VecNormalize statistics as well when we save the agent. Looking at the code of EvalCallback(), I saw that both the training and testing environments are synchronized before the evaluation. However, the VecNormalize statistics are not saved. Is this implemented somewhere outside EvalCallback()? Is it even necessary to save the normalization statistics and if so, would you recommend using a custom callback?

Thanks a lot in advance and thanks for your great work on this repository 

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

>However, the VecNormalize statistics are not saved.

By default no. You can save it following https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#pybullet-normalizing-input-features

>if so, would you recommend using a custom callback?

If you want to save statistic with the best agent, yes a callback is what you need.
In fact, that's what we are using the RL Zoo: https://github.com/DLR-RM/rl-baselines3-zoo/blob/f6b3ff70b13d2c2156b3e0faf9994c107c649c82/utils/callbacks.py#L55

and 

https://github.com/DLR-RM/rl-baselines3-zoo/blob/f6b3ff70b13d2c2156b3e0faf9994c107c649c82/utils/exp_manager.py#L407

**Comment by manuelsager** [comment]
Thanks a lot for your quick response. Keep up the good work.
