### ISSUE TITLE
[Question] Is make_vec_env running in parallel with pybullet?

### ISSUE THREAD

**Issue by cadop** [DLR-RM/stable-baselines3#474]
### Question

I am having a hard time understanding the context of 'parallel' for `make_vec_env` param `n_envs`. Does "the number of environments you wish to have in parallel" refer to separate instances of python, or is it more like threading? 

Below I try to provide some more context/flow of what I think is confusing me (and maybe could help to improve docs). 

### Additional context

If I first look at the multiprocessing example [here]( https://stable-baselines3.readthedocs.io/en/master/guide/examples.html?highlight=make_vec_env#multiprocessing-unleashing-the-power-of-vectorized-environments), 

The parameter says `num_cpu`, implying its the number of cores. 

```
    env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])
```

The comment says
>  `make_vec_env()` does "exactly the previous steps for you".  

The previous step is using `SubprocVecEnv`.   

The documentation [here ](https://stable-baselines3.readthedocs.io/en/master/common/env_util.html?highlight=make_vec_env#stable_baselines3.common.env_util.make_vec_env)for `make_vec_env()` says 

> By default it uses a DummyVecEnv which is usually faster than a SubprocVecEnv.

So it seems like its not doing "exactly" the same thing, right?  More important, I think look at `DummyVecEnv`, and this documentation [here](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html?highlight=make_vec_env#stable_baselines3.common.vec_env.DummyVecEnv) says  

> Creates a simple vectorized wrapper for multiple environments, calling each environment in sequence on the current Python process.

So with these pieces of info, its hard to really grasp why the demo for multiprocessing says `make_vec_env()` does this, then its own documentation says it uses `DummyVecEnv`, which docstring says its calls in sequence on the current process. 

Also I am not sure if it matters, but I am using it with pybullet. In my past experience, if I use multiprocessing in python and spawn a bunch of procs running separate bullet instances, the simulations use almost 100% per proc/cpu, compared to `make_vec_env()` which kind of seems to use multiple cpus but looks like threading in task manager (spiking from 5%-100% alot). 

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by daysofthunder98** [comment]
I think make_vec_env uses DummyVecEnv by default as can be seen in the source code [here](https://github.com/DLR-RM/stable-baselines3/blob/180a2e3832c12e1742545d5dc40fc7e0c8bc8009/stable_baselines3/common/env_util.py#L101). I don't think DummyVecEnv parallelizes by default and even if it uses threads as you say it won't be true parallelization due to Python's GIL(but I am not very sure about this and would love to hear what others say). You should be able to do vec_env_cls = SubprocVecEnv in make_vec_env to run environments in parallel

**Comment by Miffyli** [comment]
Yup, as noted, `make_vec_env` uses DummyVecEnv by default (i.e. no parallelization).

That's a good catch on the documentation! It indeed is rather confusing, especially with the whole "use multiprocessing but hahaa we actually do not use it :-)". A PR to update the documentation with a simple fix to `make_vec_env` call (use SubProcVecEnv instead) would be very welcomed!

**Comment by araffin** [comment]
> Yup, as noted, `make_vec_env` uses DummyVecEnv by default (i.e. no parallelization). You need to pass `vec_env_cls=SubProcVecEnv` as a parameter in `make_vec_env` to put each environment into a separate process.
> 
> That's a good catch on the documentation! It indeed is rather confusing, especially with the whole "use multiprocessing but hahaa we actually do not use it :-)". A PR to update the documentation with a simple fix to `make_vec_env` call (use SubProcVecEnv instead) would be very welcomed!

i won't change the default but update the doc.
See multiprocessing notebook from https://github.com/araffin/rl-tutorial-jnrr19 for a longer explanation ;)

**Comment by araffin** [comment]
>Also I am not sure if it matters, but I am using it with pybullet. In my past experience, if I use multiprocessing in python and spawn a bunch of procs running separate bullet instances, 


If you are using the [RL Zoo](https://github.com/DLR-RM/rl-baselines3-zoo), you can easily compare the two approaches by passing `--vec-env dummy` or `--vec-envs subproc`.
