### ISSUE TITLE
[Feature Request] Can't install imitation because of jaxlib

### ISSUE THREAD

**Issue by meric-sakarya** [DLR-RM/stable-baselines3#475]
### 🚀 Feature

Imıtation can not be installed on Windows device because jaxlib is not supported on Windows yet.

### Motivation

Hello I am working in a team and we are using stable baselines. We recently decided to use GAIL but for that we need the imitation package. When I run pip install imitation I get the following error:
ERROR: Could not find a version that satisfies the requirement jaxlib~=0.1.47 (from imitation) (from versions: none)
ERROR: No matching distribution found for jaxlib~=0.1.47 (from imitation) 

Can you please help me in any way :)

**Comment by Miffyli** [comment]
I think you are confusing packages here. [stable-baselines](https://stable-baselines.readthedocs.io/en/master/) is different from stable-baselines3 (here), and the former has GAIL implemented. However neither package uses `jaxlib`. I think you are talking about [this](https://github.com/HumanCompatibleAI/imitation) repository.

I highly recommend setting up a Linux machine in one way or another. Many libraries used for research are developed and designed to function on Linux systems, so you might run into problems like this in future again.

**Comment by meric-sakarya** [comment]
The stable-baselines3 docu says to install imitation via pip install imitation, that is when I receive the error.

**Comment by Miffyli** [comment]
Yes, in that case you should be in their repository, as this repository does not handle `imitation` things (we just point to it as a good source of IL algorithms).
