### ISSUE TITLE
[Question] PPO ended up with large policy.log_std

### ISSUE THREAD

**Issue by rhelpacc** [DLR-RM/stable-baselines3#476]
Hi - I'm new to PPO. I trained it with noisy financial returns data for about 10 assets. I noticed that at the end of training, PPO always yields large policy.log_std (I'm using DiagGaussian). I think this mutes the log probability. I wonder if you have experienced anything like this? Any suggestions would be appreciated.

**Comment by Miffyli** [comment]
Hey. Please fill in issue template next time. These issues are for enhancement proposals and bug reports, and we do not offer tech support in getting algorithms working in your custom environments. Check the links in [the issue template](https://github.com/DLR-RM/stable-baselines3/blob/master/.github/ISSUE_TEMPLATE/question.md) for other forums to ask on.

Closing as no tech support.
