### ISSUE TITLE
[Question] Accessing output of hidden layers during evaluation

### ISSUE THREAD

**Issue by ErikVester** [DLR-RM/stable-baselines3#478]
Hi, 

### Question

I am working with a custom feature extractor which uses attention. I would like to visualise the attention weights during evaluation and I am trying to write a callback which does this. I manage to log plots to tensorboard, however, I cannot find a smart way to access the attention weights in my feature extractor during evaluation. The attention weights can be seen as the output of some of the layers in the feature extractor.

 Is there a an easy way to either write a  custom  'predict' function which returns more than just the features or a way access these weights during evaluation? 

I looked through the documentation and the issues here and didn't find any info on comparable situations/questions. 
Any help or suggestions would be highly appreciated! 

Kind regards, 

Erik 

### Checklist

- [ x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Sadly there is no pre-made functionality for this, and if you wanted to use `predict` functions, you will need to modify the code quite a bit.

I think an easier approach for you would be store the intermediate values inside your feature extractor into new variables (e.g. in `forward` you save your attention weights to `self.previous_attention_weights = your_pytorch_tensor`), and then in your callbacks you access the policy's feature extractor with `policy.feature_extractor.previous_attention_weights`. Pretty dirty and you need to take care that the variable contains what you desire it to contain (e.g. it is not overwritten in other locations), but should do the trick :)

**Comment by ErikVester** [comment]
Thank you @Miffyli for the quick reply for helping me out! That works indeed :)
