### ISSUE TITLE
Different activation functions throughout the network architecture

### ISSUE THREAD

**Issue by rschlos-snl** [DLR-RM/stable-baselines3#481]
### Question
How do you/is it possible to use different activation functions throughout the network architecture? 

### Additional context

Considering:

`net_arch = [128, dict(vf=[256], pi=[16])]`

located [here](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html)

How could I use a relu activation function in the first (shared) hidden layer and linear activation functions in the second layer?

### Checklist

- [ X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
>How could I use a relu activation function in the first (shared) hidden layer and linear activation functions in the second layer?

Have you looked at the advanced example located just below?

https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#advanced-example

**Comment by rschlos-snl** [comment]
You linked me to the page I referenced. Yes I read the page.  

I suggest documentation is enhanced with something more complex than a single layer to help readers better answer my question, and propose an enhancement so the activation function can be specified layer-wise.

**Comment by araffin** [comment]
>You linked me to the page I referenced. Yes I read the page.

I linked to the advanced example section as you were referring only to the `net_arch` argument.

>I suggest documentation is enhanced with something more complex than a single layer to help readers better answer my question, and propose an enhancement so the activation function can be specified layer-wise.

In the advanced example, we show where to define custom networks, the `Sequential` objects are only there as placeholders (we cannot cover all possible use cases). For more customization, this is a PyTorch problem (how to define a custom `nn.Module`), not really a SB3 one...

**Comment by AlexPasqua** [comment]
So the only way to pass different activation functions to the so-called "network architecture" is to implement your own neural network? Isn't it possible to do it using the `policy_kwargs`?
