### ISSUE TITLE
Any limitation on number of environments? 

### ISSUE THREAD

**Issue by ErikVester** [DLR-RM/stable-baselines3#482]
Hi all, 

This is quite a straightforward question I think but I couldn't find any info on it and it might also be useful for others:

### Question
I realised in the Stablebaselines Zoo that most of the tuned algorithms have a relatively low number of environments when using vectorised environments.  Is there any reason to not increase this to more environments? I personally have an environment which runs with a lot higher FPS when I use a lot of them vectorised (400 environments). This does ofc lead to a larger buffer, which is less sample efficient I guess? However, in wall-clock time it is faster than running with less environments.
Am I missing any other potential drawbacks off using a lot of environments?

Thank you! 

Kind regards, 

Erik
### Checklist

- [ x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by minhlong94** [comment]
I recently have a conversation that is similar to this: the main bottleneck is the environment sampling time, so if your env can run on high FPS I think you are good to go: https://github.com/DLR-RM/stable-baselines3/issues/472

**Comment by araffin** [comment]
Hello,

>Am I missing any other potential drawbacks off using a lot of environments?

The best answer I have for you would the notebook from our JNRR19 tutorial: https://github.com/araffin/rl-tutorial-jnrr19#content

Basically, it is a compromise between sample efficiency and wall clock time, and at some point the bottleneck will be the gradient updates, not the simulation time (you might consider using a MPI version for that then, see https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/11).

**Comment by ErikVester** [comment]
Hi @araffin  and @minhlong94, thank you both for your answers and apologies for my very late reply! I have looked at the tutorial which was very helpful. I am working with MiniGrid environments which can be run on high FPS so therefore it makes sense for me to work with a lot of environments. Thanks again! :)
