### ISSUE TITLE
Add Python 3.9 to CI tests

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/stable-baselines3#483]
### 🚀 Feature

Add Python 3.9 to CI tests

### Motivation

PyTorch has supported Python 3.9 for months, and according to the setup.py SB3 should support 3.9 as well. However, new PRs (and the existing code) aren't being tested for this. That seems like a minor problem.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
sounds like a reasonable change.
I'm just afraid we will have to change the minimum required pytorch version (which is a breaking change but I think we will have to do that at some point anyway).
@Miffyli  any remark against upgrading minimum pytorch version in case it is needed?

**Comment by Miffyli** [comment]
Hmm hmm upgrading PyTorch shoooouldn't be a problem, since we mainly use the core-features of PyTorch which have been fixed for a good while. I am good with this update 👍 .
