### ISSUE TITLE
[Bug] Wrong DictReplayBuffer observation dtype

### ISSUE THREAD

**Issue by c-rizz** [DLR-RM/stable-baselines3#484]
### 🐛 Bug

DictReplayBuffer does not set the dtype for the observation buffer according to the environment observation_space.
The issue can be solved as in [this commit](https://github.com/c-rizz/stable-baselines3/commit/eef6ec14412961df9bf20b47e4d63f821918238b)
I'm not sure if the same issue is present in DictRolloutBuffer, from the code it looks like it but I did not try it.

### To Reproduce

I couldn't recreate a simple example, sorry. I found this out working on a relatively big project that I'm working on that uses stable_baselines. It is not published and not public (yet), so I cannot provide an example from that. However I believe the issue is quite clear. I think that in examples such as [the one in docs](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html?highlight=dict#dict-observations) the problem is being hidden by the observation preprocessing. But it could still lead to performance degradation. I believe right now all observations are being represented in the buffer as float64 (default dtype in [numpy.zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html))

### Expected behavior

Correct dtypes being used.

### System Info

 * Installed via pip
 * 1080 Ti GPU
 * Python 3.7
 * PyTorch 1.8.0
 * Gym 0.17.1
 * Numpy 1.20.3

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,
nice catch, we would appreciate a PR that solves this issue ;)

**Comment by c-rizz** [comment]
Hi,
Great! I'll create the PR.
Regarding the DictRolloutBuffer I see it is always using float32, but rollout buffers are small and also RolloutBuffer is doing the same, so I will leave it as it is.
