### ISSUE TITLE
while using evalcallback with DummyVecEnv, env's reset() method will be call twice

### ISSUE THREAD

**Issue by qingzew** [DLR-RM/stable-baselines3#490]
### 🐛 Bug && Reproduce

using evalcallback with DummyVecEnv, for example
```
eval_env = gym.make('Pendulum-v0')
eval_callback = EvalCallback(eval_env, best_model_save_path='./logs/',
                             log_path='./logs/', eval_freq=500,
                             deterministic=True, render=False)

model = SAC('MlpPolicy', 'Pendulum-v0')
model.learn(5000, callback=eval_callback)
```

when the env emit a ```done=True``` signale, I found that env's reset() method will be call twice

the first time: 
episode is done
(https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/vec_env/dummy_vec_env.py#L49)

the second time:
evaluate_policy call again
(https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/evaluation.py#L82)

so the problem is that if I have more than one episode event, the last episode done with reset(), obs will be set to the next episode's, but when the next EvalCallBack call, evaluate_policy call reset() again,  the result is that every time EvalCallBack is called, one episode event will be missed

### Expected behavior

I think the right thing is that reset() call one time in each evalcallback triggered

**Comment by Miffyli** [comment]
Hmm I having bit of hard time understanding the issue here. For evaluation, we need to call `reset` before runs to ensure we start from fresh episodes, and inside `VecEnv` we need to do this kind automatic resetting to ensure all envs are always step-able.

Could you try to rephrase the issue and/or demonstrate a concrete fix?

**Comment by qingzew** [comment]
in evaluate_policy() function, env's reset() will be call twice

```
 while len(episode_rewards) < n_eval_episodes:
        if not isinstance(env, VecEnv) or not_reseted:
            ######################
             # call env.reset() derectily
            #######################
            obs = env.reset() 
            not_reseted = False
        done, state = False, None
        episode_reward = 0.0
        episode_length = 0
        while not done:
            action, state = model.predict(obs, state=state, deterministic=deterministic)
            ###########################
            # again, env is a DummyVecEnv object, its fathter class's  VecEnv
            #  VecEnv's step() again call child class DummyVecEnv's step_wait, step_wait in VecEnv is virtual funcion
            # here is reset() : https://github.com/DLR-RM/stable-baselines3/blob/v1.0/stable_baselines3/common/vec_env/dummy_vec_env.py#L49
            ###########################
            obs, reward, done, info = env.step(action)
            episode_reward += reward
            if callback is not None:
                callback(locals(), globals())
            episode_length += 1
            if render:
                env.render()
```

so when env emit a done signal(an episode end), first DummyVecEnv call reset, then backto evaluate_policy() funcicon, this code call reset again
```
        if not isinstance(env, VecEnv) or not_reseted:
            ######################
             # call env.reset() derectily
            #######################
            obs = env.reset() 
            not_reseted = False
```

**Comment by araffin** [comment]
>so when env emit a done signal(an episode end), first DummyVecEnv call reset, then backto evaluate_policy() funcicon, this code call reset again

It seems that the code you are showing in not in master anymore...

We had a similar issue that was fixed in the past: https://github.com/DLR-RM/stable-baselines3/issues/60

**Comment by qingzew** [comment]
I am using version 1.0, the master code is right

**Comment by qingzew** [comment]
in master branch, between two evaluate_policy() call, a episode will be missed also, maybe remove reset() from evaluate_policy()?

**Comment by Miffyli** [comment]
You are not looking at the master branch with that. Here is the up-to-date version with different logic: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/evaluation.py
