### ISSUE TITLE
more help on creating vectorized environments

### ISSUE THREAD

**Issue by externalsupplierstaff** [DLR-RM/stable-baselines3#495]
### 📚 Documentation

Create a section for custom vectorized environments, as there is only one reference to gym3 procgenEnv that is not expanded in the documentations nor in the environment tutorial.

I will dig in into the code, but it could be nice if this was explained in the documentation.

**My case**
My main problem is that I want to provide observations that are features extracted from a CNN (along with other variables) but creating a VecEnv with size `n` implies one forward pass for each one of the `n` states.

I don't want to put the CNN on the policy side because 1- it's a fixed network supposed to be on the environment side and 2- to do this I should implement a custom fixed CNN + a concatenation layer with the other features + a MLP, probably using dict observations, which seems like too much (given that the VecEnv is customizable).

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by externalsupplierstaff** [comment]
Following up and honoring the question label

what is the recommended way of creating custom VecEnvs? Through procgenEnv or directly using SB3 classes?

**Comment by araffin** [comment]
> My main problem is that I want to provide observations that are features extracted from a CNN (along with other variables) but creating a VecEnv with size n implies one forward pass for each one of the n states.

why?
What you are looking for is probably a `VecEnvWrapper` ?

The simplest example is https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/vec_env/vec_extract_dict_obs.py
But I agree, we should add an example of such wrapper in the doc (we would be happy to receive a PR for that ;))

> Through procgenEnv or directly using SB3 classes?

Depends what you are doing, the most general way would creating a subclass of `VecEnv` but in most cases you just need to write a wrapper.

**Comment by externalsupplierstaff** [comment]
Hey @araffin , thanks for the quick response. I'm sorry, I'm not sure I understood the example. 

Is the idea to create a custom gym.Env, vectorize it, and then create a wrapper over the resulting VecEnv to process the states and give the desired observations?
If this is the case, I don't know how to vectorize the gym.Env, as this is handled inside the algorithms. I only know how to do this with SubprocVecEnv. Will this work with SubprocVecEnv?

**Comment by Miffyli** [comment]
> Is the idea to create a custom gym.Env, vectorize it, and then create a wrapper over the resulting VecEnv to process the states and give the desired observations?

Yup, this is exactly the idea! Keep looking at [other VecEnvWrappers SB3 has](https://github.com/DLR-RM/stable-baselines3/tree/master/stable_baselines3/common/vec_env) for examples. They function more or less the same as normal Wrappers, except that the observation/action spaces have an additional dimension `n_envs`.

> If this is the case, I don't know how to vectorize the gym.Env, as this is handled inside the algorithms. I only know how to do this with SubprocVecEnv. Will this work with SubprocVecEnv?

See how [VecNormalize](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#pybullet-normalizing-input-features) is applied on envs. You first create the VecEnv, and then apply the VecEnvWrapper. This will also work with SubProcVecEnv the same way.
