### ISSUE TITLE
Document what "Feature Extractor" is

### ISSUE THREAD

**Issue by drozzy** [DLR-RM/stable-baselines3#500]
### 📚 Documentation

It would be awesome if the "feature extractor" concept had a section in the docs. It is referred to in a few places (e.g. [here](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-feature-extractor)).

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
you mean having a separate section? because it is currently documented right above what you linked: https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#sb3-policy

**Comment by drozzy** [comment]
I mean like mention what methods you need to define to have a feature extractor.
It is mentioned, as an example, in the `CustomCNN` feature extractor.
I guess it's just the forward method?
So would it be the same interface as torch Module?

**Comment by Miffyli** [comment]
Yes, it is mainly same as Torch Module, with the addition of providing valid `features_dim` to the base class so later network constructors know how big feature vectors are coming in.

**Comment by araffin** [comment]
> So would it be the same interface as torch Module?

>Yes, it is mainly same as Torch Module, with the addition of providing valid features_dim to the base class so later network constructors know how big feature vectors are coming in.

yes, it is briefly mentioned in the [export](https://stable-baselines3.readthedocs.io/en/master/guide/export.html#manual-export) and [example](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#accessing-and-modifying-model-parameters) sections, SB3 policies are all `torch.nn.Module`, and for the feature extractor, you only need to implement the `forward()` method and provide the `feature_dim` variable.

**Comment by drozzy** [comment]
Ok thanks.
