### ISSUE TITLE
[Feature Request] discrete soft actor-critic

### ISSUE THREAD

**Issue by lingweizhu** [DLR-RM/stable-baselines3#505]
### 🚀 Feature

A discrete version of Soft actor-critic.

### Motivation

I have been using SB3 quite heavily recently and found that there is no (correct me if I made a mistake) discrete off-policy actor-critic algorithm , which can serve as a prototype for implementing various algorithms of research interest.

I have been researching entropy-regularized RL algorithms and I believe with such a prototype many more algorithms could be developed by simply changing the Shannon entropy to something else (e.g. KL divergence or alpha divergence). For example. all of the algorithms (more than 10) in this [paper](https://proceedings.neurips.cc/paper/2020/hash/8e2c381d4dd04f1c55093f22c59c3a08-Abstract.html) could be implemented based on such prototype.

I also found that this [repo](https://github.com/ku2482/sac-discrete.pytorch) has a good implementation and the author has mentioned the possibility of contributing #157 .  I have also talked with its author @ku2482 who still thinks it is important and willing to contribute.

### Pitch

A discrete version of soft actor-critic could serve as prototype for implementing various algorithms of research interest, especially policy iteration style algorithms.

### Alternatives

I have thought about several alternatives but currently I have no better idea to circumvent the need for such a prototype entropy-regularized discrete off-policy actor-critic algorithm.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Hey. We would indeed be interested in having those algos! These less-known/newer algorithms should go to the [contrib](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib) repository, to avoid bloating up / complicating this core code too much. If you or @ku2482 wants to implement discrete SAC, feel free to open a PR in that repo and we can discuss further :)

**Comment by lingweizhu** [comment]
Hi, thanks for the reply Miffyli! 

I think there is indeed such a [paper](https://arxiv.org/abs/1910.07207) detailing the structure. It seems there is no great changes from the original SAC except discrete action support. But after having tinkered with the code a little bit myself , I don't have a clear idea whether it would be **trivial** to be integrated into SB3 .

But I think it would definitely provide a lot of ease for implementing the recently popular algorithms such as all of the algorithms in this [paper](https://proceedings.neurips.cc/paper/2020/hash/8e2c381d4dd04f1c55093f22c59c3a08-Abstract.html).

**Comment by araffin** [comment]
Hello,
as mentioned already in https://github.com/DLR-RM/stable-baselines3/issues/157, I would prefer it to be in contrib first.
Please open an issue there and make sure to read the contributing guide of SB3 contrib if you want to implement the algorithm and submit a PR ;)

**Comment by araffin** [comment]
Closing this one as it belongs to SB3 contrib (please open one there).
