### ISSUE TITLE
performance inconsistency of ppo in stablebaseline3 and stablebaseline

### ISSUE THREAD

**Issue by alisonjpp** [DLR-RM/stable-baselines3#512]
While training using ppo， i can get very stable results using SB, but in SB3, the resulst is not good. Is it common？
The code is like this
In SB：
```
from stable_baselines import PPO2
from stable_baselines import SAC
from stable_baselines.common.vec_env import SubprocVecEnv
from stable_baselines.common import set_global_seeds, make_vec_env
num_cpu = 8
vec_env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])
model = PPO2('MlpPolicy', vec_env,n_steps=64,policy_kwargs=dict(net_arch=[dict(pi=[32,32],vf=[32,32])]), lam=0.998，ent_coef=0.0,verbose=1,n_cpu_tf_sess=num_cpu)
```
In SB3
```
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv
num_cpu = 8
vec_env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])

model = PPO('MlpPolicy', vec_env,n_steps=64,policy_kwargs=dict(net_arch=[dict(pi=[32,32],vf=[32,32])]),batch_size=4,learning_rate=0.00025,clip_range_vf=0.2,gae_lambda=0.998,n_epochs=4,ent_coef=0.0,verbose=1)
```
I try to make the parameters shared by the two algorithms the same
but the performance in SB3 is much worse.

**Comment by Miffyli** [comment]
Hey. Please fill in the issue template regarding questions (e.g. full code to replicate etc). 

We went to great lengths while checking that algo performance matches between SB and SB3. Make sure you set parameters correctly (see e.g. [migration guide](https://stable-baselines3.readthedocs.io/en/master/guide/migration.html))

**Comment by alisonjpp** [comment]
> Hey. Please fill in the issue template regarding questions (e.g. full code to replicate etc).
> 
> We went to great lengths while checking that algo performance matches between SB and SB3. Make sure you set parameters correctly (see e.g. [migration guide](https://stable-baselines3.readthedocs.io/en/master/guide/migration.html))

Can you plz check my updated issue. Thanks very much!

**Comment by araffin** [comment]
From the doc: `batch_size = (n_steps * n_envs) // nminibatches` which does not seem right here.

**Comment by araffin** [comment]
closing as the batch size was probably the issue.
