### ISSUE TITLE
[Question] HER algorithm on bit flipping env

### ISSUE THREAD

**Issue by Milad-Rakhsha** [DLR-RM/stable-baselines3#515]
### Question
I was trying to use the SB 1.1.0 HER algorithm for a problem and I could not get it to converge so I went back to the sample bit flipping environment  provided here:
https://stable-baselines3.readthedocs.io/en/master/modules/her.html

I ran the problem but it looks like it is not converging as well if I understand it correctly 
trying to print obs after learning is done in the prediction loop I get the following observations when " if done" before resetting the env 
OrderedDict([('observation', array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1], dtype=int8)), ('achieved_goal', array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1], dtype=int8)), ('desired_goal', array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))]) 
which does not look correct to me. Is there anything I am missing?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

>I ran the problem but it looks like it is not converging as well if I understand it correctly

Could you provide a minimal code example to reproduce the experiment.
This is quite surprising as we have a performance test for that test case: 
https://github.com/DLR-RM/stable-baselines3/blob/75b6f3b3b0f207456d9dcac2c6e86e8e2a22115f/tests/test_her.py#L367-L400

**Comment by Milad-Rakhsha** [comment]
Okay I think it is a problem with the hyperparameter of the model  (specifically the target_update_interval) 
the following is taken with no change from what is posted in the above link. Also in the example, it says it works with SAC and DDPG, would it be possible to post the hyperparameter used for those algorithms as well? 
`
from stable_baselines3 import HerReplayBuffer, DDPG, DQN, SAC, TD3
from stable_baselines3.her.goal_selection_strategy import GoalSelectionStrategy
from stable_baselines3.common.envs import BitFlippingEnv
from stable_baselines3.common.vec_env import DummyVecEnv

model_class = DQN  # works also with SAC, DDPG and TD3
N_BITS = 15

env = BitFlippingEnv(n_bits=N_BITS, continuous=model_class in [DDPG, SAC, TD3], max_steps=N_BITS)

# Available strategies (cf paper): future, final, episode
goal_selection_strategy = 'future' # equivalent to GoalSelectionStrategy.FUTURE

# If True the HER transitions will get sampled online
online_sampling = True
# Time limit for the episodes
max_episode_length = N_BITS

# Initialize the model
model = model_class(
    "MultiInputPolicy",
    env,
    replay_buffer_class=HerReplayBuffer,
    # Parameters for HER
    replay_buffer_kwargs=dict(
        n_sampled_goal=4,
        goal_selection_strategy=goal_selection_strategy,
        online_sampling=online_sampling,
        max_episode_length=max_episode_length,
    ),
    verbose=1,
)

# Train the model
model.learn(1000)

model.save("./her_bit_env")
# Because it needs access to `env.compute_reward()`
# HER must be loaded with the env
model = model_class.load('./her_bit_env', env=env)

obs = env.reset()
for _ in range(100):
    action, _ = model.predict(obs, deterministic=True)
    obs, reward, done, _ = env.step(action)

    if done:
        obs = env.reset()
`

**Comment by araffin** [comment]
>it says it works with SAC and DDPG, would it be possible to post the hyperparameter used for those algorithms as well?

There is the RL Zoo for that (cf. doc), you can take a look at TQC ones (SAC + distributional RL) for robotics envs: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/tqc.yml#L162

But the bit flipping env for continuous algorithms is a hack to check that everything is running fine.
