### ISSUE TITLE
PPO NaNs on backwards using ZOO's hyperparam optimizer.

### ISSUE THREAD

**Issue by VVIERV00** [DLR-RM/stable-baselines3#519]
Using the command python zoo/train.py --algo ppo --env myEnv-v0 -n 30000 -optimize --study-name example3 --storage mysql+mysqlconnector://xxx:xxx@localhost/example2

After some iterations, an error is raised: 
```bash
divbackwards0 returned nan in its 1th output
```
or
```bash
ExpBackward returned nan values in its 0th output
```

on sb3 ppo.py: 259
```python
loss.backward()
```

My data is perfectly fine, no Nans or Infs. 
Debugging the library I have seen:
on sb3 ppo.py: 199 
```python
values, log_prob, entropy = self.policy.evaluate_actions(rollout_data.observations, actions)
```
the arguments are fine, but the returned log_probs contains Nans
Debugging the library I have seen these traces inside self on ppy:
```bash
RuntimeError: real is not implemented for tensors with non-complex dtypes.\n'
RuntimeError: imag is not implemented for tensors with non-complex dtypes.\n'
```

### About my env:
Im sorry I can't easily provide a code that replicates it. I hope that error traces can help us.
```python
class CustomEnv(gym.Env):

  def __init__(self):
    super(CustomEnv, self).__init__()
    self.observation_space = spaces.Dict({
            OBS_CLIMATE : spaces.Box(low=0, high=1, shape=(30, 10), dtype=np.float64),
            OBS_ENERGY : spaces.Box(0, 2000000, shape=(1,), dtype=np.float64),
            OBS_INNER_STATE : spaces.Box(low=0, high=2000000, shape=(1, 3), dtype=np.float64) 
        }) 
    self.action_space = gym.spaces.Box(llow=np.array([-1, 0]), high=np.array([1, 1]), dtype=np.float64))

   def reset(self):
        estado = self.render()
        logging.info(f"Resumen {estado}")
        self.weatherFeed.resetea()
        return self.getObservation()

    def step(self, action):
        self._takeAction(action)
        done = self.getDone()
        reward = self.getReward()
        obs = self.getObservation()
        return obs, reward, done, {}
```

### System Info
 * Pip installed sb3, git installed rl zoo
 * RTX2070Super
 * python 3.8.10 64 bits
 * PyTorch 1.9.0+cu102
 * Gym 0.18.3
 * Zoo  1.1.0

### Additional context
I have no problem with 
```python
model.learn(total_timesteps=300000, callback=TensorboardCallback(entorno))
```
the problem raises only, randomly (after 5 minutes or so) with the command I provided above.
### Checklist
- [done] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [done] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [done] I have checked my env using the env checker (**required**)
- [so so :(] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Miffyli** [comment]
Hard to debug without hard code to replicate, but some wild guesses:

1) Check training losses. You have very big numbers in your observation spaces (e.g. max), which might lead to large losses -> large gradient updates -> network gets spooked -> NaNs. I recommend normalizing your observations to lie in [-1, 1] range.
2) Check that your `step` function always outputs observations of same shape and dtype. Also consider changing the dtypes to np.float32 (does not change results, but under the hood SB3 uses float32s).

**Comment by VVIERV00** [comment]
> Hard to debug without hard code to replicate, but some wild guesses:
> 
> 1. Check training losses. You have very big numbers in your observation spaces (e.g. max), which might lead to large losses -> large gradient updates -> network gets spooked -> NaNs. I recommend normalizing your observations to lie in [-1, 1] range.
> 2. Check that your `step` function always outputs observations of same shape and dtype. Also consider changing the dtypes to np.float32 (does not change results, but under the hood SB3 uses float32s).

You were completely right. The problem was on my side, the loss was too big. I am very grateful!
