### ISSUE TITLE
[Question] The current obs and the next obs have different goals in the last transition of each episode when using HER

### ISSUE THREAD

**Issue by JatGwingLam** [DLR-RM/stable-baselines3#520]
### Question

I went through [the rollout method](https://github.com/DLR-RM/stable-baselines3/blob/503425932f5dc59880f854c4f0db3255a3aa8c1e/stable_baselines3/common/off_policy_algorithm.py#L510), and found in the [_store_transition method](https://github.com/DLR-RM/stable-baselines3/blob/503425932f5dc59880f854c4f0db3255a3aa8c1e/stable_baselines3/common/off_policy_algorithm.py#L584), [the current obs and the next obs](https://github.com/DLR-RM/stable-baselines3/blob/503425932f5dc59880f854c4f0db3255a3aa8c1e/stable_baselines3/common/off_policy_algorithm.py#L484) have different goals in the last transition (which contains done==True) of each episode when using HER. Shouldn't they have the same goal? Or do I miss some point here?

My thought is that the policy train method would not use the next observation of the transition containing done==True, and this [line](https://github.com/DLR-RM/stable-baselines3/blob/503425932f5dc59880f854c4f0db3255a3aa8c1e/stable_baselines3/common/off_policy_algorithm.py#L566) would trigger the env to reset everything (including goal) for a new episode when done==True, and that's why the goal in the next observation is different (this next observation is the next episode first observation). However I can not find which function behind this [line](https://github.com/DLR-RM/stable-baselines3/blob/503425932f5dc59880f854c4f0db3255a3aa8c1e/stable_baselines3/common/off_policy_algorithm.py#L566) triggers the env.reset(). Any tips would be appreciated!

### Additional context

I'm using this [code example](https://github.com/DLR-RM/stable-baselines3/blob/master/docs/guide/examples.rst#hindsight-experience-replay-her) and set the [duration](https://github.com/eleurent/highway-env/blob/ab9a8ef031f7fc354ce50e124da5b2157633f2f9/highway_env/envs/parking_env.py#L41) of each episode to 3 for easier debugging. 

### Checklist

- [ Y] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ Y] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

>the current obs and the next obs have different goals in the last transition (which contains done==True) of each episode when using HER. Shouldn't they have the same goal? Or do I miss some point here?

we normally retrieve the correct next observation here (but please check that it is the case, otherwise this is a bug): https://github.com/DLR-RM/stable-baselines3/blob/503425932f5dc59880f854c4f0db3255a3aa8c1e/stable_baselines3/common/off_policy_algorithm.py#L487-L492

>However I can not find which function behind this line triggers the env.reset(). Any tips would be appreciated!

this is in the documentation (and in other issues like https://github.com/DLR-RM/stable-baselines3/issues/41), we are using `VecEnv` so the reset is automatic.

**Comment by JatGwingLam** [comment]
@araffin 

Thanks for the clarification!
