### ISSUE TITLE
[Question] Change position of grapped video

### ISSUE THREAD

**Issue by mat-l** [DLR-RM/stable-baselines3#521]
### Question

I am wondering if one can set a new position for the recorded videos?
I have followed the documentation as mentioned here: https://stable-baselines3.readthedocs.io/en/master/guide/tensorboard.html#logging-videos

This results in a recorded video of the env which is working so far, but the view points position is not usefull at all as one can only see the table and an shadow of the robot, but not the robot/agent in action itself:
![grafik](https://user-images.githubusercontent.com/5571947/126762954-6dbfaae5-fd57-4db4-8067-a56c7ff3847c.png)

Is it possible to change the view point or position of the recording camera?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

>Is it possible to change the view point or position of the recording camera?

This is a PyBullet issue, not an SB3 one, please take a look at their documentation to position camera.

**Comment by mat-l** [comment]
I found also the error. The position was defined in the env.render() function of my gym environment. Sorry for posting in the wrong repo.
