### ISSUE TITLE
[Feature Request(?)] Upstream Gym API test to Gym

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/stable-baselines3#525]
### 🚀 Feature

Having the Gym API compliance test in Gym itself is makes substantially more sense than containing it in SB3, and now that I'm maintaining Gym I would merge this. Accordingly, how would you guys feel about your API test being upstreamed?

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

what do you mean exactly by "compliance tests"? the env checker?
yes, we can probably use it directly in gym but you should know that we have some SB3 specific warnings.

**Comment by jkterry1** [comment]
Ya I mean the env checker-` from stable_baselines3.common.env_checker import check_env`.

Presumably the non-SB3 specific things could be included in on Gym though, yes?

**Comment by araffin** [comment]
closing in favor of https://github.com/openai/gym/issues/2278
