### ISSUE TITLE
[Question] Exploration rate DQN algorithm

### ISSUE THREAD

**Issue by pcarrenom** [DLR-RM/stable-baselines3#529]
### Question

Hello,

While playing around with the DQN code I noticed that in the cases where learning_starts < learning_steps and the default linear scheduler is used to update the exploration rate, by the time the num_timesteps reaches the learning_starts limit, the exploration rate is already at its end value (exploration_final_eps argument). 

Knowing that:
 - the target and policy network only start to be trained once num_timesteps > learning_starts, and
 - network predictions are used to sample actions according to the exploration rate

I wonder if this is the intended behaviour of the linear scheduler? To my understanding, we should keep exploring as the network starts to learn and this is not possible unless exploration_final_eps is assigned to a value greater than the default parameter shown in the documentation.

I am unsure if this question belongs here. I will be happy to post it elsewhere if that's the case.

### Additional context

I am currently trying to train a DQN, however, my network keeps predicting and sampling the same action for all states. While trying to understand what could be the issue, I also noticed that exploration was poor once the learning_steps threshold is reached. Hence my question.

**Comment by Miffyli** [comment]
Yes, this is somewhat expected. There are three parameters that control exploration in DQN:

exploration_initial_eps: Initial exploration rate
exploration_final_eps: Final exploration rate
exploration_fraction: The fraction of `num_timesteps` where exploration will reach `exploration_final_eps`. 

Like you noted, exploration schedule tarts from initial_eps and linearly decays to final_eps. So if you want to extend your exploration period, you may increase `exploration_fraction`, too.

**Comment by pcarrenom** [comment]
Hello @Miffyli ,

Thank you for your quick reply. Yes, I was expecting a decrease in the exploration fraction. However, I thought that the decrease will happen for the whole duration of the learning phase instead of only during the warm-up phase.

Specifically, what I noticed was that with the values:

learning_starts = 4000 steps
learning_steps = 16000 steps
explortation_initial_eps = 1.0
exploration_final_eps = 0.05
exploration_fraction = 0.9

by the time num_steps == learning_starts, the exploration rate was already at the final value.

**Comment by Miffyli** [comment]
Hmm that should not have happened: it should be lower than initial_eps, but not final value indeed. 

Could you share a minimal code with e.g. Cartpole environment to replicate this issue?

**Comment by araffin** [comment]
Closing as no minimal code was provided.
