### ISSUE TITLE
[Question] Difference between VecFrameStack and FrameStack

### ISSUE THREAD

**Issue by nikhilrayaprolu** [DLR-RM/stable-baselines3#531]
What is the difference between the [VecFrameStack](https://github.com/DLR-RM/stable-baselines3/blob/ddbe0e93f9fe55152f2354afd058b28e6ccc3345/stable_baselines3/common/vec_env/vec_frame_stack.py#L11
) method and [FrameStack](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/atari_wrappers.py#L197) in Atari Wrappers?

**Comment by Miffyli** [comment]
VecFrameStack works on VecEnvs (i.e. multiple envs), instead of individual envs. This version is bit more efficient than individually wrapping environments with FrameStack.
