### ISSUE TITLE
Clarification Needed on A2C Parameters

### ISSUE THREAD

**Issue by QuantumCrazy** [DLR-RM/stable-baselines3#534]
I'm still very new to RL and I'm trying to apply A2C in a financial trading environment.  I am seeking a few clarifications, namely:

1) For training  my A2C model, I am only calling the **total_timesteps** parameter in model.learn. Currently my logic is total_timesteps = number of eposides * frame_bound of my training dataframe. But I noticed there is another parameter called **n_eval_episodes**. Is this a proxy for the number of episodes or something different?

2) For the actual A2C model, what if I want the agent to not trade very frequently, how can I alter the reward function so very short term trades are penalized and medium/longer term trades are encouraged? Has it got something to do with tweaking gamma or vf_coef? And how to do that?

Many thanks!

**Edit**: I see someone has referred me to the documentation. Is there something more in depth about the parameters available than below? I want to know more technical details about the parameters.

 https://stable-baselines3.readthedocs.io/en/master/modules/a2c.html

**Comment by Miffyli** [comment]
Hey. The details should be laid out in the documentation as you pointed out. `total_timesteps` sets limit on `env.step` calls to do during training, nothing else.  Note that we do not offer task-specific tech support: we do not have the answers on "what will work" (your second question), especially for custom envs, and you need to perform some trial-and-errors to see what works.
