### ISSUE TITLE
[Question] super() function in DictReplayBuffer class

### ISSUE THREAD

**Issue by zhefan** [DLR-RM/stable-baselines3#536]
I wonder if there's any particular reason why using `super(ReplayBuffer, self).__init__(...)` in [DictReplayBuffer's `__init__()`](https://github.com/DLR-RM/stable-baselines3/blob/c41368f2ead24c0cea218164c19e58d48a47422c/stable_baselines3/common/buffers.py#L492) function, instead of `super(DictReplayBuffer, self).__init__(...)`?

It seems that using `super(ReplayBuffer, self).__init__(...)` would skip `ReplayBuffer` init function and call `BaseBuffer` init function instead. Is this on purpose?

Similarly, I wonder about [the sample function in DictReplayBuffer](https://github.com/DLR-RM/stable-baselines3/blob/c41368f2ead24c0cea218164c19e58d48a47422c/stable_baselines3/common/buffers.py#L583) as well.

**Comment by Miffyli** [comment]
Passing by, but pinging @J-Travnik in case he would have time to take a peek :)

**Comment by araffin** [comment]
>  Is this on purpose?

yes (otherwise we would call the `ReplayBuffer` init which would allocate way too much (unneeded) memory.
