### ISSUE TITLE
[Feature Request] add Curiosity-driven RL agent

### ISSUE THREAD

**Issue by ruifeng96150** [DLR-RM/stable-baselines3#538]
Can add a curiosity-driven RL agent from https://github.com/pathak22/noreward-rl ?

**Comment by araffin** [comment]
Hello,
please fill in the template completely next time.

See issue https://github.com/hill-a/stable-baselines/issues/309
For short, that would be for the contrib repo and as a gym wrapper (you can open an issue there) and you can already find implementations on github:
- https://github.com/khalilsarwari/episodic-curiosity
- https://github.com/dgsqf/CuriousAI

**Comment by ruifeng96150** [comment]
Thank for your reply. I will fill the template next time and look into those two projects.
