### ISSUE TITLE
A2C - Best Practices for Loading/Saving Models

### ISSUE THREAD

**Issue by QuantumCrazy** [DLR-RM/stable-baselines3#539]
I am in the process of testing quite a few models in sequence, all from the same family of algorithm - A2C. They all have slightly different parameters, for a handful of parameters that I think are important in controlling agent and policy decisions. The backdrop here is trading, so the agent must make a minimum profit figure and get above a certain reward threshold before the model is saved. Any algo that fails this will not have a model saved so on the next round of testing, it will start from scratch until it does. For those which have saved models, they are loaded and testing resumes from those models at every new round of testing.

My expectation is that saved models are somewhat successful therefore, loading them again should result in better and better performance over time compared to models that do not save or load and have to run anew every single time. However, I noticed that loaded models that passed my reward and profit requirements, do not necessarily perform well on the next iteration of testing. A recurring scenario that I have noticed _across models_ is that there are always instances when the agent makes the same trade in almost the entire testing dataset, meaning for example in 2 years, 1 sell order, and 729 buy orders. Is this an error or just bad policy that is inevitable? - **side question.**

So my **main** question is, what is the best practice for improving the model over time? **Should I keep on doing the logic of saving an instance of the model passing certain thresholds, then re-loading it again next time and so on, or would it be better to just not save or load at all, and start it from scratch at every instance? How will it best learn?**

Note: I am using a dynamic dataset that gets updated every day with a new row of data, which is automatically split into training and testing parts and I am running the same window and number of episodes for each model over this data. The models differ only in having different permutations of a few parameters.

**Comment by Miffyli** [comment]
This goes beyond the bugs/issues that these github issues are for, quite simply: we do not know the answer, and generally do not offer tech support for "what works best". You are better off asking somewhere else like Reddit or [RL Discord](https://discord.com/invite/xhfNqQv).

**Comment by QuantumCrazy** [comment]
OK, it seems like I am going beyond just bugs and issues here. Thanks anyhow for the pointers.
