### ISSUE TITLE
[Question] Monitor

### ISSUE THREAD

**Issue by ZY-KK** [DLR-RM/stable-baselines3#542]
In Monitor.py file, I found that only if done=True, the writer will write data.
![image](https://user-images.githubusercontent.com/25016163/129521982-9c1e4fc7-9ae1-4b2d-ba29-c2166a42abeb.png)
 But if I want to plot success rate figure, only successful step is not enough, so could you please tell me how to fix it? and One more question, when the monitor is called？Although I got result, but I do not know when the function called, I use stable-baselines3 zoo train.py to train my agent. Thanks!

**Comment by Miffyli** [comment]
> But if I want to plot success rate figure, only successful step is not enough, so could you please tell me how to fix it?

You would have to modify the said file to support this. Monitor is designed to record full-episode statistics by default.

> One more question, when the monitor is called？

Monitor wrapper is applied on the environment in `make_vec_env` function [here](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/env_util.py#L92). RL Zoo uses `make_vec_env` to create the envs.

**Comment by araffin** [comment]
>But if I want to plot success rate figure, only successful step is not enough, so could you please tell me how to fix it? 

I think there might be a confusion of what the `done` signal does.
`done=True` only means that the episode ends, the success logging is done using the `info` variable (see example env https://github.com/DLR-RM/stable-baselines3/blob/75b6f3b3b0f207456d9dcac2c6e86e8e2a22115f/stable_baselines3/common/envs/bit_flipping_env.py#L175)
As most environments have timeouts (max number of steps per episode), you don't normally need successful trial to have the logging enable.

For logging it, you will also need to modify slightly the rl zoo: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/utils/exp_manager.py#L490
