### ISSUE TITLE
[Feature Request] Pydantic > NamedTuples

### ISSUE THREAD

**Issue by 09tangriro** [DLR-RM/stable-baselines3#546]
### 🚀 Feature

I think pydantic is a better alternative to the NamedTuples currently used in type_aliases.py. Pydantic allows for validation checks and basically "schema-fies" the data structures. For example, a useful check might be to assert the length of the observation and action tensors are the same.

### Motivation

Just good to keep on top of the latest best practices.

### Pitch

Convert the NamedTuples to pydantic BaseModels.

### Alternatives

Could use dataclasses instead which are built in to Python, but I think pydantic is better because of the easy validation checks!

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

Although I appreciate and understand the motivation, it seems a bit overkill to me to add a new dependency only for one use-case (and those checks are mostly needed when debugging the algorithm).
