### ISSUE TITLE
Inconsistent action type

### ISSUE THREAD

**Issue by JingZhang918** [DLR-RM/stable-baselines3#547]
Hi everyone,

I wrote my own environment. Here is the action space I defined:
```self.action_space = gym.spaces.Box(low=-10, high=10, shape=(3,),dtype=np.int64)```
It's int type. 

When I use sample method
```
env_train = DummyVecEnv([lambda: StockTradingEnv(train)])
env_test = DummyVecEnv([lambda: StockTradingEnv(test)])
env_train.action_space.sample()
# [10  8 -1]
```
everything works fine. But when I try to train the model, during the training and prediction it all becomes float, like this:
```
[0.69327372 0.83050752 0.28413573]
[-0.646411    1.43026614 -0.03086906]
[ 0.99178988 -0.31390417 -0.15796679]
```

Here is my code:

```
env_train = DummyVecEnv([lambda: StockTradingEnv(train)])
env_test = DummyVecEnv([lambda: StockTradingEnv(test)])

env_train.action_space.sample()

training_start = datetime.now()
model = PPO('MlpPolicy', env_train)

model.learn(total_timesteps=1)
training_end = datetime.now()
print(str(training_end-training_start))
model.save("test")
del model # remove to demonstrate saving and loading

model = PPO.load("test")

test_obs = env_test.reset()
for i in np.arange(test.shape[0]):
    action, _states = model.predict(test_obs)
    print(action)
    test_obs, rewards, dones, info = env_test.step(action)
```

Please help me~

**Comment by Miffyli** [comment]
"Box" is used for continuous action spaces and the code does not respect the dtype. You need to use `Discrete` or `MultiDiscrete` spaces for discrete choices like this.

**Comment by JingZhang918** [comment]
> "Box" is used for continuous action spaces and the code does not respect the dtype. You need to use `Discrete` or `MultiDiscrete` spaces for discrete choices like this.

This is really helpful!!! Thank you!!!
