### ISSUE TITLE
Can't replicate results

### ISSUE THREAD

**Issue by JingZhang918** [DLR-RM/stable-baselines3#549]
Hello there,

I trained a PPO model, saved the model, and loaded it every time I ran the test. But I get different results every time. It's really hard for me to evaluate the model. Is there a way to replicate it? I tried ```PPO.set_random_seed(0)``` but it's not working. I also tried the parameter deterministic``` model.predict(test_obs, deterministic=True)``` but the actions are always the same no matter the next state.

Help me ˜˜˜˜ 😁

**Comment by JingZhang918** [comment]
Big mistake

**Comment by vahidqo** [comment]
@JingZhang918
did you solve your problem?
I have same problem
Help me please

**Comment by JingZhang918** [comment]
> @JingZhang918 did you solve your problem? I have same problem Help me please

Yes, I have. https://jingzhang.tech/index.php/2021/11/20/tutorial-for-drl-hyperparameter-tuning-in-a-custom-environment/
I wrote here. :D

**Comment by JingZhang918** [comment]
> 

Yep. It's not the stable baselines' problem. The agent is not learning. That's why every time it outputs the same results.

**Comment by vahidqo** [comment]
@JingZhang918
what about using SB3?

**Comment by JingZhang918** [comment]
> @JingZhang918 what about using SB3?

I used ray

**Comment by JingZhang918** [comment]
> @JingZhang918 what about using SB3?

What's SB3?

**Comment by vahidqo** [comment]
> > @JingZhang918 what about using SB3?
> 
> What's SB3?

Stable-baseline3 package
