### ISSUE TITLE
[feature request] Low-level API

### ISSUE THREAD

**Issue by mhtb32** [DLR-RM/stable-baselines3#55]
Having a lower level API can be helpful for some users to have more control over the training loop. The low-level API is particularly useful in Hierarichal RL or Multi-Agent RL problems. One idea is to provide an API like [this repo](https://github.com/eleurent/rl-agents/) from @eleurent:

```Python

for episode in episodes:
    while not done:
        action = agent.act(state)
        next_state, reward, done, info = env.step(action)
        agent.record(state, action, next_state, reward, done, info)

```

**Comment by mhtb32** [comment]
Thanks.
I think it is worth adding a tutorial about using low-level API to docs.

**Comment by Miffyli** [comment]
Agreed, this question came up in sb repository quite often. Another related thing we could do is to make getting action probabilities/values bit easier / clarified.

**Comment by LittleRobertTables** [comment]
> Hello,
> 
> Why not, but I would say you already have one:
> 
> > `action = agent.act(state)`
> 
> It is called `predict()`: `action, _ = agent.predict(state)`
> 
> > `agent.record(state, action, next_state, reward, done, info)`
> 
> As mentioned in the developer guide (cf doc), if you are rewriting the training loop (take a look at `collect_rollout()`, you have access to `agent.rollout_buffer` or `agent.replay_buffer` which does what you want. Finally, the gradient update is located in `agent.train()`.

@araffin  could you explain more how you would use the rollout buffer to do this?

**Comment by araffin** [comment]
Different updates regarding this issue:

> Agreed, this question came up in sb repository quite often. Another related thing we could do is to make getting action probabilities/values bit easier / clarified.

We now provide `policy.obs_to_tensor` (for all algorithms), `policy.predict_values()` and  `policy.get_distribution()` (for on-policy algorithms).

> @araffin could you explain more how you would use the rollout buffer to do this?

We have a [developer guide](https://stable-baselines3.readthedocs.io/en/master/guide/developer.html) on where to look when you want to dive deeper into SB3. I won't give more details that "please read the code and learning about the algorithms" as you really need to understand how algorithms work when you are accessing/changing the low-level logic.
