### ISSUE TITLE
Note- Gym is deprecating the monitor wrapper in the next release

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/stable-baselines3#551]
I don't know where to put this and I figured I should warn you- Gym is deprecating monitor in the next release in a few weeks (see https://github.com/openai/gym/issues/2297, https://github.com/openai/gym/pull/2354, https://github.com/openai/gym/pull/2332, https://github.com/openai/gym/pull/2300, https://github.com/openai/gym/pull/2296). It'll just raise a warning so it won't break anything for a little while, and the replacements should be able to be added without much issue, but I figured I should let you know.

**Comment by araffin** [comment]
Hello,
the Monitor wrapper is an internal SB3 one, so we should not be affected, but thanks for the issue anyway ;)
