### ISSUE TITLE
Can environment feed model data in addition to observations?

### ISSUE THREAD

**Issue by Zymoo** [DLR-RM/stable-baselines3#555]
Hey!

I would like to know if the obs returned by the env.step is the only input to the model or if there is a possibility that the environment adds additional info with the returned obs?

I am not sure if the Markov state is equal to the observation provided.

Adding part of the code I refer to:
```model.set_env(env)
obs = env.reset()
for i in range(10000):
  action, _state = model.predict(obs, deterministic=True)
  obs, reward, done, info = env.step(action)
  if done:
    env.render()
    obs = env.reset()
    break
```
    
 Thank you for your time!

**Comment by araffin** [comment]
>I would like to know if the obs returned by the env.step is the only input to the model or if there is a possibility that the environment adds additional info with the returned obs?

yes.
The `_state` in the code example if for the state of recurrent policies (hidden state of an LSTM for instance) but is not implemented yet.

**Comment by Zymoo** [comment]
Thank you so much, I am using a library which utilizes stable-baselines and I really got confused here!

**Comment by Zymoo** [comment]
So I understand that it is safe to refer to obs as the state in MDP?

**Comment by araffin** [comment]
>So I understand that it is safe to refer to obs as the state in MDP?

yes.
`obs` is what is called `state` in MDP, but in practice, as the env is not always fully observable, `observation` is a more general term.

**Comment by Zymoo** [comment]
Appreciate that, thanks!
