### ISSUE TITLE
[Feature Request] Contributing ARS implementation. 

### ISSUE THREAD

**Issue by sgillen** [DLR-RM/stable-baselines3#565]
### 🚀 Feature

I would like to contribute an [ARS ](https://arxiv.org/pdf/1803.07055.pdf) implementation to SB3.

### Motivation

BRS/ARS is a dead simple algorithm that works more often than most people would expect. I wish more people would try it on their custom environments (and maybe realize they don't really need DRL at all, or that their environment is too easy etc). 

### Pitch

I contribute a version of ARS that is compatible with and to up to the standards of SB3.

I have a version I made for myself [here](https://github.com/sgillen/seagul/blob/master/seagul/rl/ars/ars_torch.py), and there are [other implementations](https://github.com/ray-project/ray/blob/master/rllib/agents/ars/ars.py) I can compare performance to. ARS is very simple, though some care will be needed to find the most natural / least intrusive way to incorporate it into the existing code base. If you are down with the general idea I can come up with a proposal on that front as well. 

I'd also like to run and contribute ARS agents to the sb3-zoo.

I'm happy to do all this with minimal help, but only if the team actually thinks this is useful and will merge it. 

### Alternatives

1. Add this to the sb3-contrib repo instead. I don't think ARS is super cutting edge or fancy, but possibly the team would prefer I put it there anyway. 

2. I don't write this algorithm at all and continue using my own version and grumbling that people aren't benchmarking against this simple baseline. 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
yes please open an issue in the contrib repo.
You can also take a look at a CEM implementation ('ot completely clean but you get the idea on how to implement such algorithm): https://github.com/osigaud/stable-baselines3/blob/master/stable_baselines3/cem/cem.py

**Comment by sgillen** [comment]
Done: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/41
