### ISSUE TITLE
[Question] Are the parameters of feature extractors also trained / updated during the training loop?

### ISSUE THREAD

**Issue by RobertHua96** [DLR-RM/stable-baselines3#570]
### Question

Hi there, I'm wondering if I use a CNN For feature extraction from images - whether that CNN's parameters are also trained as the agent interacts with environment?

Or am I better of loading a pretrained image model for feature extraction?

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by Miffyli** [comment]
Yes. CNN part (and the whole network) is trained as part of the agent training process by default, unless you specifically start to modify the NN structure.

**Comment by RobertHua96** [comment]
Thanks so much for that! So with regards to the modifying the NN Structure - does that mean explicitly freezing weights?

Or is it the case if I wanted to plug in a vision transformer, that I'll need to develop extra functionality to ensure it also trains as part of the agent training process?

**Comment by Miffyli** [comment]
>  So with regards to the modifying the NN Structure - does that mean explicitly freezing weights?

If you create a custom policy, you would have to explicitly define in there which parameters you want to be updated the usual Torch style.

>Or is it the case if I wanted to plug in a vision transformer, that I'll need to develop extra functionality to ensure it also trains as part of the agent training process?

As long it is inside the policy, it will be trained by default (unless you exclude it from the `parameters()` function iteration).

**Comment by RobertHua96** [comment]
Thank you!!!
