### ISSUE TITLE
[Question] PPO multi-processing in SpinUp vs SB3

### ISSUE THREAD

**Issue by zhihanyang2022** [DLR-RM/stable-baselines3#571]
### Question

In OpenAI SpinningUp's PPO code, multi-processing is done such that the number of environment interaction is shared across multiple processes. For example, if we want to collect 4000 interactions for each PPO update and there are 10 processes, each process can just collect 4000/10=400, which greatly speeds things up.

https://github.com/openai/spinningup/blob/master/spinup/algos/pytorch/ppo/ppo.py#L223

In SB3, this seem to be done differently; see the `n_steps` argument to the Parameters section of [documentation](https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html). For example, if we want to collect 4000 interactions for each PPO update and there are 10 processes, then each process needs to collect 4000 interactions.

Is my understanding correct? 

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
> Is my understanding correct?

yes, if you want the same behavior, you can set `n_steps = 400` and use 10 envs, this will collect 10 * 400 = 4000 steps of interaction for the gradient update.

related: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/11

**Comment by zeeshanalipanhwar** [comment]
Hi

> > Is my understanding correct?
> 
> yes, if you want the same behavior, you can set `n_steps = 400` and use 10 envs, this will collect 10 * 400 = 4000 steps of interaction for the gradient update.
> 
> related: [Stable-Baselines-Team/stable-baselines3-contrib#11](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/11)

Hi @araffin, can you please elaborate how to " use 10 envs"? The agent initialization and learning functions do not seem to have such a parameter, the gym env create function does not have it either. Thank you.
