### ISSUE TITLE
[Question] Is actions = actions.cpu().numpy() in on_policy_algorithms.py necessary?

### ISSUE THREAD

**Issue by rhelpacc** [DLR-RM/stable-baselines3#581]
### Question

Hi,

The following code snippet from on_policy_algorithms.py (line 161-176 in master branch) shows that the actions is to be converted to numpy array. Is this necessary?
I noticed that we want to do np.clip operation ONLY when action space is box. If continuous, do we still need to make actions a numpy array? I'd like to know if we can avoid this under continuous space because converting tensor to numpy array is generally slow in my understanding.

while n_steps < n_rollout_steps:
            if self.use_sde and self.sde_sample_freq > 0 and n_steps % self.sde_sample_freq == 0:
                # Sample a new noise matrix
                self.policy.reset_noise(env.num_envs)

            with th.no_grad():
                # Convert to pytorch tensor or to TensorDict
                obs_tensor = obs_as_tensor(self._last_obs, self.device)
                actions, values, log_probs = self.policy.forward(obs_tensor)
            **actions = actions.cpu().numpy()**

            # Rescale and perform action
            clipped_actions = actions
            # Clip the actions to avoid out of bound error
            if isinstance(self.action_space, gym.spaces.Box):
                clipped_actions = np.clip(actions, self.action_space.low, self.action_space.high)

### Checklist

- [ x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Actions need to be converted into numpy array for the `env.step` call just after that part, so there is no way around that really (unless your environment accepts torch tensors for some reason).

**Comment by araffin** [comment]
> Actions need to be converted into numpy array for the env.step call just after that part, so there is no way around that really (unless your environment accepts torch tensors for some reason).

and unless you rewrite all buffers to use PyTorch instead.
