### ISSUE TITLE
PPO documentation environment mixup

### ISSUE THREAD

**Issue by IljaAvadiev** [DLR-RM/stable-baselines3#585]
### 📚 Documentation

The documentation in the example section for PPO https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html#example states the following: "Train a PPO agent on **Pendulum-v0** using 4 environments". While the code right below uses **CartPole-v1**.

```python

import gym

from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env

# Parallel environments
env = make_vec_env("CartPole-v1", n_envs=4)

model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=25000)
model.save("ppo_cartpole")

del model # remove to demonstrate saving and loading

model = PPO.load("ppo_cartpole")

obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Hey! Thanks for reporting this! Feel free to make a PR that fixes this issue (remember to complete steps in the checklist) :)
