### ISSUE TITLE
[Question] Train with only a single life with Atari Games

### ISSUE THREAD

**Issue by Syzygianinfern0** [DLR-RM/stable-baselines3#591]
### Question

Currently for training Atari games continues even after the life is lost (reset is not called, but done is True). How can it be made so that a reset is actually performed whenever a life is lost. Just changing [the wrapper](https://github.com/DLR-RM/stable-baselines3/blob/740d61ada3360306389210a4dd8ee88ad75592db/stable_baselines3/common/atari_wrappers.py#L105-L109) and making it always call `self.env.reset(**kwargs)` does not seem to be enough as still the logs (I use sb3-zoo for training) show that rewards and episode lengths are higher than possible in a single life. 
Upon further investigation I located the source to be related to the `Monitor` and within [Evaluator scripts](https://github.com/DLR-RM/stable-baselines3/blob/740d61ada3360306389210a4dd8ee88ad75592db/stable_baselines3/common/evaluation.py#L102-L108). 

Am I on the right track? Is there any simple way to just make the environment hard reset after a single life is lost during both training and evaluation?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
You are on the right track. The Monitor wrapper is applied as the first-most wrapper on the original Atari environment to ensure the `episode` reward statistics are not skewed (e.g. they represent the score and length of the full game over all lifes). You would have to modify the ordering of the wrappers so that this life control wrapper is applied before Monitor wrapper. I do not know where exactly code for this would be in zoo, but you probably have to replace a call to `make_vec_env` or so with a manual version that does not apply Monitor wrapper on the environment.

**Comment by Syzygianinfern0** [comment]
That was exactly what I did and it worked! Thanks for your reply confirming that. I was concerned that I might have broken some things by changing the Monitor wrapper order, but the training seems to be proceeding as I expected (as of now). 

For anyone stumbling upon this issue later on, this is the complete solution

## 1. Changing the Wrapper
- Make a copy of [this file](https://github.com/DLR-RM/stable-baselines3/blob/740d61ada3360306389210a4dd8ee88ad75592db/stable_baselines3/common/atari_wrappers.py) in your project with the following changes

```diff
class EpisodicLifeEnv(gym.Wrapper):
    """
    Make end-of-life == end-of-episode, but only reset on true game over.
    Done by DeepMind for the DQN and co. since it helps value estimation.
    :param env: the environment to wrap
    """

    def __init__(self, env: gym.Env):
        gym.Wrapper.__init__(self, env)
        self.lives = 0
        self.was_real_done = True

    def step(self, action: int) -> GymStepReturn:
        obs, reward, done, info = self.env.step(action)
        self.was_real_done = done
        # check current lives, make loss of life terminal,
        # then update lives to handle bonus lives
        lives = self.env.unwrapped.ale.lives()
        if 0 < lives < self.lives:
            # for Qbert sometimes we stay in lives == 0 condtion for a few frames
            # so its important to keep lives > 0, so that we only reset once
            # the environment advertises done.
            done = True
        self.lives = lives
        return obs, reward, done, info

    def reset(self, **kwargs) -> np.ndarray:
        """
        Calls the Gym environment reset, only when lives are exhausted.
        This way all states are still reachable even though lives are episodic,
        and the learner need not know about any of this behind-the-scenes.
        :param kwargs: Extra keywords passed to env.reset() call
        :return: the first observation of the environment
        """
-       if self.was_real_done:
-           obs = self.env.reset(**kwargs)
-       else:
-           # no-op step to advance from terminal/lost life state
-           obs, _, _, _ = self.env.step(0)
+       obs = self.env.reset(**kwargs)

        self.lives = self.env.unwrapped.ale.lives()
        return obs
```

- Copy the `make_atari_env` in your project where instead of using `env = AtariWrapper(env, **wrapper_kwargs)`, rather use your local version with the above change. 

https://github.com/DLR-RM/stable-baselines3/blob/740d61ada3360306389210a4dd8ee88ad75592db/stable_baselines3/common/env_util.py#L108

- Use the `make_atari_env` in your main training script to generate the envs. 

## 2. Changing the order of wrappers
- Copy the `make_vec_env` in your project with the following changes

https://github.com/DLR-RM/stable-baselines3/blob/740d61ada3360306389210a4dd8ee88ad75592db/stable_baselines3/common/env_util.py#L38

- Changes: move 92 so that its under line 95
https://github.com/DLR-RM/stable-baselines3/blob/740d61ada3360306389210a4dd8ee88ad75592db/stable_baselines3/common/env_util.py#L90-L96

- Call your newly defined `make_vec_env` in your earlier created `make_atari_env`.
