### ISSUE TITLE
[Feature Request] Recurrent Policies for A2C 

### ISSUE THREAD

**Issue by sreejank** [DLR-RM/stable-baselines3#592]
Hi!

I've read on a bunch of other issues that there is no active development for recurrent policies. I love using Stable Baselines and this is something that would really make things easier for me at the moment. Normally I would stick to the previous stable baselines for recurrent policies, which uses TF 1.x. However, at the moment, I'm interested in incorporating pretrained models that are mostly in TF2 or Pytorch in my meta-learning agent (I'm using the architecture from RL^2 in Duan et al. 2016 / Wang et al. 2016) so it would be really nice if I could continue to use stable baselines through Pytorch. 

If this is something that is not planned to be added at the moment, could I ask why out of curiosity? Would it make the codebase complex? I'm also willing to help out if that is possible, though I haven't contributed directly to SB so maybe I might not be as experienced if this thing requires a large revamp. I totally understand if this is something that would unnecessarily complicate the codebase at a time when you guys are moving forward with other features. 

Thanks so much! I love using this framework and really appreciate the work you guys do :)

**Comment by araffin** [comment]
Duplicated of https://github.com/DLR-RM/stable-baselines3/issues/18 and https://github.com/DLR-RM/stable-baselines3/issues/160 (and others).

Please see discussion there for why it is not maintainers priority.
One of the main argument is that frame-stacking is competitive and avoid complexifying a lot the codebase.

See ![stackingvslstm](https://user-images.githubusercontent.com/1973948/135600364-f8e24a8c-9e70-4610-bd3e-12ae0af46a4c.png)

from https://arxiv.org/abs/1912.01588

**Comment by sreejank** [comment]
Thanks for letting me know. I think the recurrence in RL^2 is key to the agent's capability to meta-learn (or at least that's what those works claim) so framestacking probably won't work for me. I'll try to pursue an alternative solution. I appreciate the response though!
