### ISSUE TITLE
Incorrect predictions after save and load

### ISSUE THREAD

**Issue by o-evgeny** [DLR-RM/stable-baselines3#595]
I trained PPO and made predictions:
model.learn (...)
model.predict (obs)
Repeating this cycle from time to time, they do not change. (seed is determined)

BUT!!!
If I save it and load it, the results are completely different.
model.learn (...)
model.save (‘modelName’)
model = PPO.load (‘modelName’)
model.predict (obs)

The prediction results are completely wrong :(

Python=3.7
SB3=1.2.0

**Comment by araffin** [comment]
Hello,
please fill the issue template completely (minimal example to reproduce the error is missing).
And if you are using a custom env, please fill the custom env template.

**Comment by o-evgeny** [comment]
Thanks for answer


The input of this function is model after learn
If I add lines:
        model.save('PPO_010421')
        model=PPO.load('PPO_010421')
predictions are getting bad

def DRL_prediction(self,model,name,last_state,iter_num,turbulence_threshold,initial):
        ### make a prediction based on trained model###

        ## trading env
        trade_data = data_split(self.df, start=self.unique_trade_date[iter_num - self.rebalance_window], end=self.unique_trade_date[iter_num])
        trade_env = DummyVecEnv([lambda: StockTradingEnv(trade_data,
                                                        self.dim,
                                                        self.hmax,
                                                        self.initial_amount,
                                                        self.buy_cost_pct,
                                                        self.sell_cost_pct,
                                                        self.reward_scaling,
                                                        self.state_space,
                                                        self.action_space,
                                                        self.tech_indicator_list,
                                                        turbulence_threshold=turbulence_threshold,
                                                        initial=initial,
                                                        previous_state=last_state,
                                                        model_name=name,
                                                        mode='trade',
                                                        iteration=iter_num,
                                                        print_verbosity=self.print_verbosity)])

        trade_obs = trade_env.reset()
        model.save('PPO_010421')
        model=PPO.load('PPO_010421')
        for i in range(len(trade_data.index.unique())):
            f=open('test.txt','a')
            action, _states = model.predict(trade_obs)
            f.write('\ndata:'+str(i)+'\nobs:'+str(trade_obs)+'\nact:'+str(action)+'\n===')
            f.close()
            trade_obs, rewards, dones, info = trade_env.step(action)

**Comment by Miffyli** [comment]
Our tests check that loading a saving load has the same results as not saving at all. The error might be somewhere in the environment (e.g. environment dynamics change, for some reason) or some wrapper is missing. I recommend you take [the save-load example](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#basic-usage-training-saving-loading), put your environment there and start modifying it bit-by-bit and see where it breaks.

**Comment by o-evgeny** [comment]
As I understand it, only the model needs to be saved for PPO. Neither policies nor replay buffers need to be saved. So I don't know what I'm doing wrong :(

**Comment by Miffyli** [comment]
Saving PPO saves the policies (the core of the agent that chooses the actions), so this code should work out. Unfortunately we do not have time to give individual tech support, and I recommend you start by taking a known-to-work code (e.g., the example) and start modifying it bit-by-bit to see when things go wrong. 

If you find a bug which can be replicated with a small environment code etc, please share the findings with a bug report.

Closing this as "no tech support".
