### ISSUE TITLE
[Question] Continued Training in Stable Baseline 3

### ISSUE THREAD

**Issue by Necropsy** [DLR-RM/stable-baselines3#597]
### Question

The agent does not demonstrate to be learning over time by following a continuing training model. Would it be a problem with this specific training model or with sb3?

### More details

I have a custom env that connects to a network simulator, where the size of each simulation is fixed at 500 timesteps, and after this number of steps, I must end the training, save it to restart the simulator, and then restart the training. Using DQN in my env I realized that the agent didn't learn over time, so I decided to test the training model in a gym environment in order to validate the idea of ​​continued training, but I got the same problem.

### Code

Continued training:

```python
import gym
import numpy as np

import os
import random as rd

from stable_baselines3 import DQN
from stable_baselines3.common.monitor import Monitor

def create_env():
    env = gym.make("CartPole-v0")
    return env

seeds = []
seeds = rd.sample(range(1,5001), 51)

log_dir = "logs/"
os.makedirs(log_dir, exist_ok=True)

env = create_env()
env = Monitor(env, log_dir+"_test_0")
obs = env.reset()

model = DQN("MlpPolicy", env,
            learning_rate = 1e-3,
            buffer_size = 1000000,
            learning_starts = 500,
            batch_size = 64,
            tau = 1.0,
            gamma = 0.99,
            train_freq = 4,
            gradient_steps = 1,
            optimize_memory_usage = False,
            target_update_interval = 250,
            exploration_fraction = 0.1,
            exploration_initial_eps = 1.0,
            exploration_final_eps = 0.05,
            max_grad_norm = 10,
            policy_kwargs=dict(net_arch=[32, 32]),
            device ='cpu',
            verbose=1
            )

#CartPole has 200 max steps
model.learn(total_timesteps=200, log_interval=4)

model.save('./logs/dqn_save')
model.save_replay_buffer('./logs/dqn_save_replay_buffer')

del env
del model

# Load and Train
for i in range(50):
    env = create_env()
    env = Monitor(env, log_dir+"_test_"+str(i+1))
    
    model = DQN.load("logs/dqn_save")
    model.load_replay_buffer('logs/dqn_save_replay_buffer')
    
    model.set_env(env)
    model.set_random_seed(seeds[i])
    
    model.learn(total_timesteps=200, log_interval=4)

    model.save('logs/dqn_save')
    model.save_replay_buffer('logs/dqn_save_replay_buffer')
    
    del model
    del env
```

Non-Continued training:

```python
log_dir = "logs/"
os.makedirs(log_dir, exist_ok=True)

env = create_env()
env = Monitor(env, log_dir+"_test_0")
obs = env.reset()

model = DQN("MlpPolicy", env,
            learning_rate = 1e-3,
            buffer_size = 1000000,
            learning_starts = 500,
            batch_size = 64,
            tau = 1.0,
            gamma = 0.99,
            train_freq = 4,
            gradient_steps = 1,
            optimize_memory_usage = False,
            target_update_interval = 250,
            exploration_fraction = 0.1,
            exploration_initial_eps = 1.0,
            exploration_final_eps = 0.05,
            max_grad_norm = 10,
            policy_kwargs=dict(net_arch=[32, 32]),
            device ='cpu',
            verbose=1
            )

model.learn(total_timesteps=10000, log_interval=4)

model.save('./logs/dqn_save')
model.save_replay_buffer('./logs/dqn_save_replay_buffer')

del env
del model
```

![ag1_50ep200st](https://user-images.githubusercontent.com/11506710/136264332-3bfdab6b-0498-4c83-910f-e516fd71dfb6.png)
![ag1_10000st](https://user-images.githubusercontent.com/11506710/136264335-326a1ba9-5ab5-436c-8b2e-7b74eed8e5a7.png)

* I used the load_parameters and get_parameters but to no avail (it didn't change the results)
### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked the repo [issue](https://github.com/DLR-RM/stable-baselines3/issues) (**required**)
I saw #435, #326, #51, #29 but I couldn't answer the question.

**Comment by araffin** [comment]
Hello,
First of all, this type of training is very special...

if you take a close look at #435, the learning in your case fail for a very special reason:
`learning_starts` and `target_update_interval` are above each budget `total_timesteps` for individual call for `.learn()` so you agent is just behaving randomly and never updating the target network (and because `reset_num_timesteps=True`).

For this special case, a simple fix is to replace https://github.com/DLR-RM/stable-baselines3/blob/3efab0d267e74cb03264411d4500ddde0c163404/stable_baselines3/common/base_class.py#L411

by `if False` (so it does not reset the counter but still reset the environment).
We may need a fix for SB3 but it seems to be a very specific case though...
