### ISSUE TITLE
[Question] How to set first action of PPO

### ISSUE THREAD

**Issue by idoyehe** [DLR-RM/stable-baselines3#599]
Hi,

I am using the PPO and MLP policy for training and I would like to know if there is any way to make the PPO start from a specific first action. 
For example, if my action is a single real number between 0-1 I would like the first try of exploration will be 0.5.

Ido

**Comment by Miffyli** [comment]
Hey. If you wish to enforce that actions agent would always take at the start of the training, you can change the parameters of the final layer accordingly. E.g. if you want the agent always to output 0.5 during first rollouts, you could set the weights of the final policy layer to zero and biases to 0.5 for mean and put them something small for variance/std.

**Comment by Miffyli** [comment]
You can use the `get_parameters` and `set_parameters` functions to get the the network parameters (before training), modify them as you please and then load them back up. The final layers are probably the last set of parameters in those dictionaries.
