### ISSUE TITLE
TD3 action space clamping

### ISSUE THREAD

**Issue by dorbittonn** [DLR-RM/stable-baselines3#608]
### Question
when implementing TD3 in line 150-153 in the attached link, the values are clamped onto the [-1,1] range.
what if my action space is [0,1] or [-10,10] ? there's no support in that issue?

thanks in advance

### link to implementation

https://github.com/DLR-RM/stable-baselines3/blob/09e9fc42eb653cacc0b6db203fa83faa0530e297/stable_baselines3/td3/td3.py#L16

**Comment by araffin** [comment]
Related: https://github.com/DLR-RM/stable-baselines3/issues/355
