### ISSUE TITLE
Policy architecture discrepancy in TD3

### ISSUE THREAD

**Issue by mloo3** [DLR-RM/stable-baselines3#61]
In the original paper it looks like the [400, 300] architecture was actually used for their modified version of DDPG rather than for TD3. It seems like they actually used [256, 256] as their architecture. 

Here is their DDPG:
https://github.com/sfujim/TD3/blob/ade6260da88864d1ab0ed592588e090d3d97d679/OurDDPG.py#L14-L44

Here is their TD3:
https://github.com/sfujim/TD3/blob/ade6260da88864d1ab0ed592588e090d3d97d679/TD3.py#L14-L44

**Comment by araffin** [comment]
Hello,
The original implementation/paper uses [400, 300] neural net for DDPG and TD3.
It was only changed after the paper release here: https://github.com/sfujim/TD3/commit/a8d53f7ad28e22b9cb28189b1ba9fac096587e88

We are using the original paper hyperparameters as they have shown to be working quite well,
see https://arxiv.org/abs/2005.05719 .

**Comment by mloo3** [comment]
I see. Thanks for clearing that up
