### ISSUE TITLE
Model Regularization?

### ISSUE THREAD

**Issue by DavidChiumera-404** [DLR-RM/stable-baselines3#610]
### Question
I am wondering how one would approach regularizing a DRL model using this library.
 
### Additional context
I have found resources online, claiming it can be done through using the entropy coefficient or discount factor, but I was wondering if something like L1/L2 or dropout is part of this library? I know it could involve potentially modifying the loss function if not, but it doesn't seem clear to me which loss function would make the most sense to use (policy?). I also found this post #240, but it doesn't seem like wight_decay is a parameter used by all model types, such as with PPO for example.

### Checklist
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Ah, should have more clear: `weight_decay` parameter is not exposed by SB3 API, so you have to modify the code/algorithms to achieve this :)
