### ISSUE TITLE
[Question] Predictable 'batch size' with A2C

### ISSUE THREAD

**Issue by abdel** [DLR-RM/stable-baselines3#611]
### Question

I am aware that currently RNN/LSTM policies are not supported in the built-in policies. But I was attempting to implement my own policy, but had issues controlling the reset of the RNN hidden state at the end of the rollout.

Using A2C on CarRacing environment with `n_steps=6`, I was expecting the Feature Extractor to receive observations with batch_size = 6, and so my policy network to also receive features with the same batch size. But I am trying to figure out why the first 7 inputs received by the networks are batch_size=1, then switch to 6 for a while, then switch back to 1?

I couldn't distinguish a particular pattern and I couldn't find an explanation for the behaviour in the documentation.

I am attempting to find some predictability so that I can utilise callback hooks to reset the RNN state at the end of the rollout, but if the batch size may be different then at that point in time, I don't have the correct shape to set the RNN hidden state.

### Additional context

Console outputs of feature shape and RNN hidden state
```
features = torch.Size([1, 3, 64, 64])
hidden = torch.Size([1, 256])

features = torch.Size([1, 3, 64, 64])
hidden = torch.Size([1, 256])

features = torch.Size([1, 3, 64, 64])
hidden = torch.Size([1, 256])

features = torch.Size([1, 3, 64, 64])
hidden = torch.Size([1, 256])

features = torch.Size([1, 3, 64, 64])
hidden = torch.Size([1, 256])

features = torch.Size([1, 3, 64, 64])
hidden = torch.Size([1, 256])

features = torch.Size([1, 3, 64, 64])
hidden = torch.Size([1, 256])

features = torch.Size([6, 3, 64, 64])
Traceback (most recent call last):
  File "train_a2c.py", line 216, in <module>
    controller.learn(total_timesteps=1000, callback=callback)
  File "/home/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/a2c/a2c.py", line 192, in learn
    return super(A2C, self).learn(
  File "/home/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 257, in learn
    self.train()
  File "/home/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/a2c/a2c.py", line 137, in train
    values, log_prob, entropy = self.policy.evaluate_actions(rollout_data.observations, actions)
  File "/home/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/policies.py", line 661, in evaluate_actions
    latent_pi, latent_vf, latent_sde = self._get_latent(obs)
  File "/home/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/stable_baselines3/common/policies.py", line 605, in _get_latent
    latent_pi, latent_vf = self.mlp_extractor(features)
  File "/home/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "train_a2c.py", line 106, in forward
    inputs = torch.cat([z, self.hidden[0]], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 0. Got 1 and 6 (The offending index is 0)
```

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
That's because during rollouts you will have to predict on action per environment per step (`batch_size=n_envs`, and I assmume `batch_size=n_envs=1`). After `n_steps` steps in all environments the agent is updated with the rollout data, which is now `batch_size=n_steps`. 

It is cool that somebody is working on RNNs, though! If you get something functional up, we would be happy to see a PR on this :)
