### ISSUE TITLE
[Feature Request] Add relevant package versions to saved file

### ISSUE THREAD

**Issue by araffin** [DLR-RM/stable-baselines3#612]
### 🚀 Feature

We should save relevant python/package information when saving a model, this will help debug errors.

### Motivation

We get several issues regarding loading model from environments that were different from the training env.

### Pitch
We would add a new file in the zip that contains all package infos (there is only one current containing SB3 version).
I would also add a `debug` flag to loading that compares current python env from saved python env.
It would be nice to also add a `sb3.print_infos()` to make debug of issues easier (instead of manually copying info from pip).

### Alternatives

Doing nothing.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Agree on all points 👍 . In 20/20 hindsight, this should have been added to save-files a loooong time ago, but better late than never :')
