### ISSUE TITLE
Inconsistency with the API on saving stuff

### ISSUE THREAD

**Issue by tirafesi** [DLR-RM/stable-baselines3#62]
`BaseAlgorithm.save` takes as an argument the path to the output **file**. Same thing with `VecNormalize.save`.

https://github.com/DLR-RM/stable-baselines3/blob/494ebfd20abe90acc136fdaf215c76ec566acd2c/stable_baselines3/common/base_class.py#L479

https://github.com/DLR-RM/stable-baselines3/blob/494ebfd20abe90acc136fdaf215c76ec566acd2c/stable_baselines3/common/vec_env/vec_normalize.py#L181

However, `OffPolicyAlgorithm.save_replay_buffer` takes as an argument the path to the output **directory**.

https://github.com/DLR-RM/stable-baselines3/blob/494ebfd20abe90acc136fdaf215c76ec566acd2c/stable_baselines3/common/off_policy_algorithm.py#L109

In order to keep things consistent, I believe `save_replay_buffer` should be changed to match the API of the other two methods. It would also allow for more control over the resulting file name.

**Comment by araffin** [comment]
Hello,

Sounds reasonable. We would appreciate a PR that solves this issue ;)
(the zoo needs to be updated afterward)

**Comment by Miffyli** [comment]
I can include this in the load/save review I will be working on soon-ish once PPO/A2C performance checks are done, but would not mind a PR before it on it either :)
