### ISSUE TITLE
Linear Schedule of the entropy coefficient in A2C

### ISSUE THREAD

**Issue by NestorasChalkidis** [DLR-RM/stable-baselines3#628]
Hi everyone, 

I have seen in stable baselines that is possible to evaluate a linear schedule in order to constantly decrease the learning rate during training. 

I was wondering if there is any implementation in stable baselines where one can use the linear schedule in order to decrease the entropy coefficient in A2C model during training. 

Any help would be much appreciated.

King regards,
Nestoras

**Comment by NestorasChalkidis** [comment]
Hi, 
I managed to apply the linear schedule for the entropy coefficient by making only a few alternations in the base class, a2c and on the on_policy_algorithm. If this is of interest I could upload my code as I want to contribute to the community :)

**Comment by Miffyli** [comment]
@NestorasChalkidis Thanks for the offer, but as discussed in #316, this is a) possible to do with callbacks if necessary and b) not a very common thing that merits code changes over the code base (we try to keep things mostly clean) ˆˆ'

**Comment by hiraz01** [comment]
The self.model.ent_coef change within the step function of callback does not seem to update the variable during the training. Is there any more documentation on this? Reviewing all the various issues and discussions has not led to any useful information for actually getting the ent_coef to update during the course of training for me.

**Comment by araffin** [comment]
@hiraz01 what did you try exactly and what make you think it's not updated?

**Comment by hiraz01** [comment]
I apologize. I think I got it working. Visualizing in tensorboard now. Very sorry.
