### ISSUE TITLE
[Question] Comparison to OpenAI SpinUp (observation & value regression target normalization)

### ISSUE THREAD

**Issue by zhihanyang2022** [DLR-RM/stable-baselines3#644]
### Question

In OpenAI Spinup, there's a quote (see https://spinningup.openai.com/en/latest/spinningup/bench.html):

> The Spinning Up implementations of VPG, TRPO, and PPO are overall a bit weaker than the best reported results for these algorithms. This is due to the absence of some standard tricks **(such as observation normalization and normalized value regression targets)** from our implementations. For research comparisons, you should use the implementations of TRPO or PPO from OpenAI Baselines.

I know that SB3 is intended to be a PyTorch parallel of OpenAI Baselines; does SB3 do these two things by default, given a standard environment like `halfcheetah-v2`? 

### Additional context

By reading the source code of PPO, it does not seem to normalize **value regression targets**, but I'm asking anyway to double-check (in case it's done somewhere else).

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Obs normalization is not done by default but you can do it easily with `VecNormalize`. See https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#pybullet-normalizing-input-features

PPO does not normalize value regression targets, however as per original PPO implementation, [value losses might be clipped](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/ppo/ppo.py#L218-L229) which prevents having huge value losses which would destabilize training.
