### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'record'

### ISSUE THREAD

**Issue by zeeshanalipanhwar** [DLR-RM/stable-baselines3#646]
### 🐛 Bug

The initialization of the inherited class must take _init_setup_model as the _init_setup_model that the initialization function of the inheriting class is getting. Note the order agent files might require the same update.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_6988/1580690086.py in <module>
      1 agent = PPO(policy="MlpPolicy", env=env_train, n_steps=2048*8, batch_size=64*8, n_epochs=10//5,
      2             tensorboard_log='../log', verbose=1, device='cuda', _init_setup_model=True)
----> 3 agent.train()

~/anaconda3/envs/sb3/lib/python3.7/site-packages/stable_baselines3/ppo/ppo.py in train(self)
    170         self.policy.set_training_mode(True)
    171         # Update optimizer learning rate
--> 172         self._update_learning_rate(self.policy.optimizer)
    173         # Compute current clip range
    174         clip_range = self.clip_range(self._current_progress_remaining)

~/anaconda3/envs/sb3/lib/python3.7/site-packages/stable_baselines3/common/base_class.py in _update_learning_rate(self, optimizers)
    295         """
    296         # Log the current learning rate
--> 297         self.logger.record("train/learning_rate", self.lr_schedule(self._current_progress_remaining))
    298 
    299         if not isinstance(optimizers, list):

AttributeError: 'NoneType' object has no attribute 'record'

### To Reproduce

```python
agent = PPO(...)
agent.train()
```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Miffyli** [comment]
You need to call `learn` instead of `train` to do training :). `train` is an internal function that triggers one round of updates.

**Comment by zeeshanalipanhwar** [comment]
Hmm.. Yes, I use `learn`, but do not know what the `train` is for. So, `train` is an internal function of which?

**Comment by zeeshanalipanhwar** [comment]
BTW, does that invalidate the change I have proposed in my pull-request? If so, I would close that too.

**Comment by Miffyli** [comment]
> BTW, does that invalidate the change I have proposed in my pull-request? If so, I would close that too.

For future record, the related PR (#645) was also closed for another reason mentioned in the PR.
