### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by zeeshanalipanhwar** [DLR-RM/stable-baselines3#649]
I have created a `tensortrade.env.generic.environment.TradingEnv` using `tensortrade.env.default.create` as follows:

```python
env_train = default.create(
    action_scheme=action_scheme,
    reward_scheme=reward_scheme,
    portfolio=portfolio_train,
    feed=feed_train,
    window_size=10,
    renderer="screen-log",
    enable_logger=True
)
```
The above environment works fine as it is but my model: `PPO` utilizes the GPU only around 0-3 %. Therefore, I wanna create a vector environment consisting of multiple environments for multiprocessing, and this is how I do it:

```python
from stable_baselines3.common.env_util import make_vec_env
vec_env_train = make_vec_env(env_train, n_envs=num_envs, seed=42, vec_env_cls=SubprocVecEnv)
```
That results in `BrokenPipeError: [Errno 32] Broken pipe`. The error has been discussed in [509](https://github.com/DLR-RM/stable-baselines3/issues/509#issue-941340864) and according to that the above code should work.

**Clarification:** The error relates to `SB3`, not `TensorTrade`. The following is the complete trace of the error:

```python
---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
<ipython-input-13-3b5897de4e37> in <module>()
      3 from stable_baselines3.common.env_util import make_vec_env
      4 
----> 5 vec_env_train = make_vec_env(env, n_envs=4, seed=42, vec_env_cls=SubprocVecEnv)

4 frames
/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/env_util.py in make_vec_env(env_id, n_envs, seed, start_index, monitor_dir, wrapper_class, env_kwargs, vec_env_cls, vec_env_kwargs, monitor_kwargs, wrapper_kwargs)
    103         vec_env_cls = DummyVecEnv
    104 
--> 105     return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
    106 
    107 

/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/vec_env/subproc_vec_env.py in __init__(self, env_fns, start_method)
    108             work_remote.close()
    109 
--> 110         self.remotes[0].send(("get_spaces", None))
    111         observation_space, action_space = self.remotes[0].recv()
    112         VecEnv.__init__(self, len(env_fns), observation_space, action_space)

/usr/lib/python3.7/multiprocessing/connection.py in send(self, obj)
    204         self._check_closed()
    205         self._check_writable()
--> 206         self._send_bytes(_ForkingPickler.dumps(obj))
    207 
    208     def recv_bytes(self, maxlength=None):

/usr/lib/python3.7/multiprocessing/connection.py in _send_bytes(self, buf)
    402             # Also note we want to avoid sending a 0-length buffer separately,
    403             # to avoid "broken pipe" errors if the other end closed the pipe.
--> 404             self._send(header + buf)
    405 
    406     def _recv_bytes(self, maxsize=None):

/usr/lib/python3.7/multiprocessing/connection.py in _send(self, buf, write)
    366         remaining = len(buf)
    367         while True:
--> 368             n = write(self._handle, buf)
    369             remaining -= n
    370             if remaining == 0:

BrokenPipeError: [Errno 32] Broken pipe
```
### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have checked my env using the env checker (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by zeeshanalipanhwar** [comment]
To replicate the error, kindly follow this [colab-notebook](https://colab.research.google.com/drive/1vspBTyQcr4nUsy4TPy-vjwd38TVwcO9g?usp=sharing) that uses `TradingEnv` of `TensorTrade` and `PPO` of `SB3`.

**Comment by zeeshanalipanhwar** [comment]
Hi @araffin, kindly use the linked colab notebook for all the information needed.

**Comment by araffin** [comment]
Hello,
sounds more like an error from Tensortrade, not SB3... And please fill the custom env template completely (minimal example to reproduce the error is missing, the code provided, which involve installing tensortrade is far from minimal).

*The following is an automated answer:*

as you seem to try to apply RL to stock trading, i also must warn you about it. Here is recommendation from a former professional trader:
"
Retail trading, retail trading with ML, and retail trading with RL are bad ideas for almost everyone to get involved with. 
* I was a quant trader at a major hedge fund for several years. I am now retired.
* On average, traders lose money. On average, retail traders especially lose money. An excellent approximation of trading, and especially of retail trading, is 'gambling'. 
* There is a lot more bad advice on trading out there than good advice. It is extraordinarily difficult to demonstrate that any particular advice is some of the rare good advice.
* As such, it's reasonable to treat all commentary on retail trading as an epsilon away from snake oil salesmanship. Sometimes that'll be wrong, but it's a strong rule of thumb. 
* I feel a sense of responsibility to the less world-wise members of this community - which includes plenty of highschoolers - and so I find myself unable to let a conversation about retail trading occur without interceding and warning that it's very likely snake oil. 
* I find repeatedly making these warnings and the subsequent fights to be exhausting.

"

**Comment by zeeshanalipanhwar** [comment]
`An excellent approximation of trading, and especially of retail trading, is 'gambling'.` 100% right! :p

**Comment by zeeshanalipanhwar** [comment]
`sounds more like an error from Tensortrade, not SB3...`
The error relates to `SB3`, not `TensorTrade`. I have edited the description of the issue with the complete trace of the error.

**Comment by araffin** [comment]
> The error seemingly relates to SB3, not TensorTrade. I have added the complete trace of the error now.

if it does, then please provide a **minimal** example to reproduce it.
It seems that it comes from `self.remotes[0].send(("get_spaces", None))`:
https://github.com/DLR-RM/stable-baselines3/blob/18d10dbf42dd6dff6d457b45b521fdf2a1169a7e/stable_baselines3/common/vec_env/subproc_vec_env.py#L46-L47

**Comment by araffin** [comment]
> The following code resolves the issue.

yes, although you should do that with a lambda... it will give the same env object instead of instantiating new ones for each env.
