### ISSUE TITLE
[Feature Request] Passing kwargs in reset of VecEnvs and VecEnv Wrappers

### ISSUE THREAD

**Issue by jank324** [DLR-RM/stable-baselines3#650]
### 🚀 Feature

On calling `reset` of a (wrapped) VecEnv with keyword arguments, these should be passed to the environment inside.

### Motivation

This feature is commonplace with Gym wrappers, including those provided by the Gym package itself.

You might need this feature when you want an episode to run under certain conditions or with a custom goal. In that case your custom environment would implement something like
```python
def reset(self, goal=None, condition=None):
    # do something
    return observation
```
For this to work, all wrappers you might wrap the custom environment in need to pass on the keyword arguments.

### Pitch

This is a fairly easy fix in most cases, where the fixed version just adds `**kwargs` in the `reset` function's arguments and passes it to the reset function of `self.venv`.
```python
def VecExampleWrapper(VecEnvWrapper):
    # stuff
    def reset(self, **kwargs):
        observation = self.venv.reset(**kwargs)
        # do other things
        return observation
```

Slightly less trivial is the implementation of this feature in `SubprocVecEnv`. Here, I would suggest passing `kwargs` as data in `remote.send`
```python
def reset(self, **kwargs) -> VecEnvObs:
        for remote in self.remotes:
            remote.send(("reset", kwargs))
        obs = [remote.recv() for remote in self.remotes]
        return _flatten_obs(obs, self.observation_space)
```
and then unpacking `data` in the call to `env.reset` in the `_worker` function
```python
elif cmd == "reset":
    observation = env.reset(**data)
    remote.send(observation)
```

I will provide a pull request with these implementations shortly.

### Checklist

- [ x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

> This feature is commonplace with Gym wrappers, including those provided by the Gym package itself.

not really... the current gym api of `reset()` does not accept `kwargs` (although some wrappers do).

you forgot to fill the "atlernatives" part.
We provide access to the env via the [env_method](https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html#stable_baselines3.common.vec_env.VecEnv.env_method) function. This should allow you to call any method of the env with any arguments (including `reset()`).

**Comment by jank324** [comment]
Does the Gym documentation make any claims about the arguments taken by `reset`? I couldn't find anything specific on it. Pretty much every wrapper in the Gym repository passes `**kwargs`, though. I would therefore consider it to be the expected behaviour.

I wasn't actually aware of the `env_method` function. Having had a look now, I don't think it is an adequate alternative to passing `**kwargs`. Below is a minimal example as I would find it in my own work, where I believe `env_method` wouldn't solve the problem. I think this is a fairly common use case with Gym environments. Please correct me if I'm wrong, or you would consider the example too specialised.

If I have a custom environment that defines a task where we want to achieve some goal that can be redefined for each episode (say drive the car to position [x,y]), I would have this position randomly generated during training, but then when I use my agent, I would want to be able to set my own destination. The environment's `reset` function would look something like this:
```python
def reset(self, destination=None):
    self.destination = destination if destination is not None else self.random_destination()
    # ...
    return observation
```
If this is wrapped in a `VecNormalize` wrapper similar to this:
```python
env = DummyVecEnv([MyCustomEnv()])
env = VecNormalize(env, norm_obs=True)
```
then I would want a call to reset to return the normalised observation because my model needs the latter as input. Calling
```python
observation = env.env_method("reset", destination=some_city)
```
however would give me the unnormalised observation, whereas
```python
observation = env.reset(destination=some_city)
```
with `**kwargs` passing would return the normalised observation.

I hope this explains why I believe this is an important feature to have.

**Comment by jank324** [comment]
That's a nice solution and definitely works for the use case I had in mind.

Nonetheless, the question: Is there a particular reason not to pass the keyword arguments through `reset`. It seems to be a more elegant and intuitive solution that - for all I can tell - is embraced by *Gym* itself.

**Comment by araffin** [comment]
> Is there a particular reason not to pass the keyword arguments through reset? 

I don't like having `**kwargs` as argument. First, it would change our current API and then you cannot check the type of the objects passed to `reset()`.
I prefer to explicitly have the name and type of available arguments.

`reset(**kwargs)` is maybe more intuitive but I wouldn't say more elegant...

**Comment by jank324** [comment]
Alright, that makes a lot of sense!
I'll close this issue then, because you've given me a solution to achieve the same thing.
