### ISSUE TITLE
[Feature Request] Use cunumeric and cudf to speed up numpy and pandas on GPU

### ISSUE THREAD

**Issue by rrfaria** [DLR-RM/stable-baselines3#663]
### 🚀 Feature

You may use cuDF if gpu is available on machine
It helps you to faster math calculation
and it has the same api as pandas
https://github.com/rapidsai/cudf

and you can also use cunumeric to speed up numpy 
https://developer.nvidia.com/cunumeric

### Motivation

GPU usage can speed up our development

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
could you elaborate ?
we are not using pandas except for plotting and numpy is used because gym env uses it.
i'm also not sure to see the benefits of cunumeric vs using pytorch when gpu is available.
