### ISSUE TITLE
[Question] PPO's n_steps might not contain a complete episode

### ISSUE THREAD

**Issue by zhihanyang2022** [DLR-RM/stable-baselines3#668]
### Question

Here's an example:

Suppose that a hypothetical environment always have episode length of 500.

In that case, would it be reasonable / justified to use an `n_step` of 100? If so, why?

Some hyperparams in rl-baselines3-zoo do exactly something like this (e.g., mujoco envs). 

### Additional context

I understand 
- what `n_steps` mean, just not how it interact with complete episodes;
- episodes can "continue across" multiple data collection rounds of length `n_steps`, if length of episode >> `n_steps`.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

> In that case, would it be reasonable / justified to use an n_step of 100? If so, why?

why would that be a problem?

**Comment by zhihanyang2022** [comment]
I guess I was trying to understand what happens when n_steps don't contain a complete episode:

(1) Advantage computation

Bootstrapping takes care of the truncation of episode due to buffer size:

https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/buffers.py#L374

(2) Value regression

Targets are computed by `self.advantages + self.values`, so if advantages are calculated correctly then the whole thing is correct.

**Remark** I think it's important that we don't reset the environments between n_steps (which is what SB3 does) - I missed this earlier when reading code.

**Comment by araffin** [comment]
> If n_steps never contain a full episode, how does reporting episode length and episode return work though? I think I know where this is in the code but would appreciate a short answer.

Take a look at the `Monitor` wrapper.
