### ISSUE TITLE
[Feature-Request] make_vec_env for bsuite environments

### ISSUE THREAD

**Issue by PartiallyTyped** [DLR-RM/stable-baselines3#67]
## Motivation
Bsuite environments are short/simple to run and are often good validation environments. The idea is to implement the equivalent of `make_atari`/`make_vec_env` but for the bsuite environments.

## Details
More or less the same implementation as `make_vec_env`, except the bsuite environments will also be wrapped in an adapter to make them compatible with the `gym` interface. This will also be optional, and available iff `bsuite` is installed.

**Comment by araffin** [comment]
Tell me if I'm wrong, but by looking at [that code](https://github.com/deepmind/bsuite/blob/master/bsuite/baselines/third_party/openai_ppo/run.py):
```python
make_vec_env(env, wrapper_class=bsuite.utils.gym_wrapper.GymFromDMEnv)
```

would work, no?

**Comment by PartiallyTyped** [comment]
Ah, sorry, mb. I was under the impression that `make_vec_env` only took strings so loading bsuite env would be slightly more involved.

**Comment by araffin** [comment]
In fact, it expects an env class or a string (I updated my example)
