### ISSUE TITLE
Gym 0.21.0 support

### ISSUE THREAD

**Issue by AvivSham** [DLR-RM/stable-baselines3#674]
Hi All,
Thank you for you valuable contribution to the RL community!
I'm working with SB and [MinAtar](https://github.com/kenjyoung/MinAtar/tree/master) their latest commit requires `gym==0.21.0` which creates conflict with SB3. The current workaround is to checkout to older commit and then installing MinAtar.
When do you tend to release a version which supports `gym==0.21.0`?

Thanks in advance.

**Comment by araffin** [comment]
> I'm working with SB and MinAtar their latest commit requires gym==0.21.0 which creates conflict with SB3. The current workaround is to checkout to older commit and then installing MinAtar.

One other simple workaround is to install it with `--no-dependencies` flag, otherwise, you can follow https://github.com/DLR-RM/stable-baselines3/pull/572
