### ISSUE TITLE
Can I separate out the steps of learn() 

### ISSUE THREAD

**Issue by LittleRobertTables** [DLR-RM/stable-baselines3#677]
I'm working on a project where two agents train simultaneously, but each agent only sometimes needs to make a decision. Is it possible to have code that follows roughly the following structure:

```py
model = A2C("MlpPolicy", env, verbose=1, learning_rate=0.0005)
obs = env.reset()
for i in range(2000000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)

    model.update_from_experience(obs, action, reward) #Does this type of function exist?
```
If this isn't possible is sb3 is there another library that would be better?

Thanks!

**Comment by LittleRobertTables** [comment]
This might be related to #55 but I still can't figure out how to do it

**Comment by araffin** [comment]
moving the discussion to https://github.com/DLR-RM/stable-baselines3/issues/55
