### ISSUE TITLE
Questions about CPU utilization

### ISSUE THREAD

**Issue by Huwenbo-git** [DLR-RM/stable-baselines3#682]
When I used dual-core Xetron processor 5118, RTx2080Ti graphics card to train PPO algorithm, I found that the training time was long and the CPU utilization rate was only 2%.  How to improve the utilization of CPU

**Comment by araffin** [comment]
Related to https://github.com/DLR-RM/stable-baselines3/issues/314 and https://github.com/DLR-RM/stable-baselines3/issues/350

You first need to identify the bottleneck, one way to improve things is to optimize the env (by writing it in a lower-level language, like c++ or rust), you can find examples there: https://github.com/sail-sg/envpool

**Comment by araffin** [comment]
Another way is to rewrite PPO with MPI, help is welcomed in SB3 contrib ;) https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/11

**Comment by Huwenbo-git** [comment]
Thank you for your answer. I'll try your advice

**Comment by Huwenbo-git** [comment]
I found that the poor single-core performance of my CPU made computing very inefficient. I trained PPO algorithm faster on i5 10400F processor without graphics card than on Xeon 5118 processor RTX2080Ti. So it should be CPU performance that affects the training speed. If I want to replace CPU recently, should I pay more attention to single-core performance?  The i9 12 generation processor uses a small core design. I don't think it's a good idea. I would like to ask if there is a recommended CPU selection.

**Comment by Miffyli** [comment]
@Huwenbo-git See the topics araffin linked above regarding CPU utilization and bottlenecks (TL;DR: GPU is not useful unless you have very large batch sizes and/or image observations). The i9's should be fine since I would imagine the workload is delegated to the performance cores.

Closing as resolved and no tech support.
