### ISSUE TITLE
[Feature Request] Is there any plan to add deepmind PBT algorithm？

### ISSUE THREAD

**Issue by borninfreedom** [DLR-RM/stable-baselines3#687]

**Comment by Miffyli** [comment]
No plans to add PBT. I think it would most benefit from highly parallel systems (or in asynch training setups), so it is not that great of a fit for stable-baselines3, but we would be happy to accept PRs to our [contrib](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/) repository :).

**Comment by araffin** [comment]
Hello,
if I recall PBT is for hyperparameter optimization, so out of scope of SB3 (but could be a good addition to Optuna).

Please also fill up the issue template completely next time.
