### ISSUE TITLE
[Question] "The number of environments used is greater than the target network" in DQN multiprocessing

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/stable-baselines3#688]
I've recently been using the new DQN multiprocessing off master with rl baselines zoo, and I've been getting the warming "The number of environments used is greater than the target network". This raises two points for me:

1. What exactly is going on here? I'm just using .learn on a prebuilt vector environment that works fine with SB3 PPO. The message itself also seems like it would imply some sort of unexpected behavior in SB3 if the number of environments in the target network aren't what they should be?
2. Could this warning please be made more verbose/clear? I strongly suspect this is going to need to be a far more detailed warning if I'm this confused.

**Comment by araffin** [comment]
Hello,
are you referring to that warning?
is it not displayed completely?
https://github.com/DLR-RM/stable-baselines3/blob/77f4f5021d54a5b009d271b44be21656926d0c02/stable_baselines3/dqn/dqn.py#L146

**Comment by jkterry1** [comment]
That warning would make dramatically more sense. And no, I'm not getting the whole warning and I don't entirely know why? I assume the issue is on my end from your code snippet though?
