### ISSUE TITLE
[Bug] `VecNormalize` followed by `VecFrameStack` does not work for off-policy algorithms

### ISSUE THREAD

**Issue by araffin** [DLR-RM/stable-baselines3#693]
### 🐛 Bug

Not sure if there is a good solution apart from inverting wrappers... 
(one can invert wrapper or use `gym.wrappers.FrameStack` before wrapping into `VecEnv`, which is the same is `VecFrameStack` and then `VecNormalize`)

issue is
```python
if self._vec_normalize_env is not None:
    new_obs_ = self._vec_normalize_env.get_original_obs()
    reward_ = self._vec_normalize_env.get_original_reward()
```

### To Reproduce

```bash
python train.py --algo sac --env Pendulum-v0 -params normalize:True frame_stack:2
```

```bash
File "stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 602, in collect_rollouts
  self._store_transition(replay_buffer, buffer_actions, new_obs, rewards, dones, infos)
File "stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 520, in _store_transition
  infos,
File "stable-baselines3/stable_baselines3/common/buffers.py", line 246, in add
  self.observations[self.pos] = np.array(obs).copy()
ValueError: could not broadcast input array from shape (1,3) into shape (1,6)

```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by buoyancy99** [comment]
This bug also happens to VecTransposeImage after VecNormalize. VecTransposeImage is applied very often as it's automatically by off policy algorithems for image spaces.

`import gym
import numpy as np
from stable_baselines3 import SAC
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.vec_env import VecNormalize


class TestEnv(gym.Env):
    def __init__(self):
        super(TestEnv, self).__init__()
        self.observation_space = gym.spaces.Box(low=0, high=255, shape=(84, 84, 3), dtype=np.uint8)
        self.action_space = gym.spaces.Box(low=-1.0, high=1.0, shape=(4,), dtype=np.float32)

    def step(self, action):
        return self.observation_space.sample(), 0, False, {}

    def reset(self):
        return self.observation_space.sample()

print('Testing Offpolicy without VecNormalize')
env = DummyVecEnv([lambda: TestEnv()] * 2)
model = SAC(policy='CnnPolicy', env=env, verbose=1)
model.learn(1000)
print('Succss')

print('Testing Offpolicy with VecNormalize')
env = DummyVecEnv([lambda: TestEnv()] * 2)
env = VecNormalize(env)
model = SAC(policy='CnnPolicy', env=env, verbose=1)
model.learn(1000)
print('Succss')
`

**Comment by araffin** [comment]
> VecTransposeImage after VecNormalize

This sounds wrong as images are normalized by default (cf. doc).

**Comment by buoyancy99** [comment]
> > VecTransposeImage after VecNormalize
> 
> This sounds wrong as images are normalized by default (cf. doc).

I use VecNormalize mostly for reward and set norm_obs to False. The error will occur in this case even if VecNormalize doesn't change image

**Comment by araffin** [comment]
> > > VecTransposeImage after VecNormalize
> > 
> > 
> > This sounds wrong as images are normalized by default (cf. doc).
> 
> I use VecNormalize mostly for reward and set norm_obs to False. The error will occur in this case even if VecNormalize doesn't change image

should be fixed at the same time as https://github.com/DLR-RM/stable-baselines3/issues/724 then

**Comment by araffin** [comment]
Closing as it won't probably be fixed and workarounds are available.
