### ISSUE TITLE
Off-Policy MultiProcessing Example

### ISSUE THREAD

**Issue by christqoh** [DLR-RM/stable-baselines3#697]
I am unable to run the SAC Off-Policy MultiProcessing Example shown [here](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#multiprocessing-with-off-policy-algorithms)

### To Reproduce

```python
import gym

from stable_baselines3 import SAC
from stable_baselines3.common.env_util import make_vec_env

env = make_vec_env("Pendulum-v0", n_envs=4, seed=0)

# We collect 4 transitions per call to `ènv.step()`
# and performs 2 gradient steps per call to `ènv.step()`
# if gradient_steps=-1, then we would do 4 gradients steps per call to `ènv.step()`
model = SAC('MlpPolicy', env, train_freq=1, gradient_steps=2, verbose=1)
model.learn(total_timesteps=10_000)
```

```bash
(dynamic) user@MBPM1 % python testing_stuff.py                        
Using cpu device
Traceback (most recent call last):
  File "/Users/user/testing_stuff.py", line 11, in <module>
    model = SAC('MlpPolicy', env, train_freq=1, gradient_steps=2, verbose=1)
  File "/Users/user/opt/miniconda3/envs/dynamic/lib/python3.9/site-packages/stable_baselines3/sac/sac.py", line 106, in __init__
    super(SAC, self).__init__(
  File "/Users/user/opt/miniconda3/envs/dynamic/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 109, in __init__
    super(OffPolicyAlgorithm, self).__init__(
  File "/Users/user/opt/miniconda3/envs/dynamic/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 175, in __init__
    raise ValueError(
ValueError: Error: the model does not support multiple envs; it requires a single vectorized environment.
```

### System Info

Describe the characteristic of your environment:
 * conda env w/ pip install 
* OS: macOS-10.16-x86_64-i386-64bit Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101
* Python: 3.9.7
* Stable-Baselines3: 1.3.0
* PyTorch: 1.10.0
* GPU Enabled: False
* Numpy: 1.21.4
* Gym: 0.19.0

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
    - [x] I am aware of #439 but expected the example to work since it already made it to the documentation
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
    - [x] I am aware of [RL algos and the note below on dict obs spaces only being single level](https://stable-baselines3.readthedocs.io/en/master/guide/algos.html#rl-algorithms) 
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,
you need master version of SB3 (cf. doc for installation and changelog that states this feature is after 1.3.0).
The doc is by default for master version of SB3.

**Comment by christqoh** [comment]
Installed sb3 using `pip install git+https://github.com/DLR-RM/stable-baselines3` and it now works. Thanks!
