### ISSUE TITLE
[Question] HRL in SB3

### ISSUE THREAD

**Issue by sycz00** [DLR-RM/stable-baselines3#698]
### Question

Hey there, 

I am using SB3 now for a while and glad you maintained this lib so well. Now things have changed in my project for which I want to try some Hieracical approach. My question is, is there any smart possibility of using SB3 as it is now to apply some HRL approach ? I first wanted to ask before I really dig deeper into the library. Any hints or suggestions would be amazing as well:)

### Additional context

PPO would be the algorithm of choice 

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Hey. There are no pre-made solutions for this in SB3 (and a quick look at older issues there does not seem to be older discussions on this), so unfortunately I can not give many tips :). 

A self-plug, but we used SB3 with manual-hierarchy in a short paper, where separate agents were trained for different situations (see [this](https://github.com/Miffyli/rl-human-prior-tricks/tree/vizdoom), for example). The code is not super easy to follow and not very informative (it just creates many agents).

**Comment by sycz00** [comment]
Hey,

okay, thanks anyway :)  Iam gonna look into the manual-hierarchy project. By "existing algorithms", you are talking about algorithms not from SB3 ?
In essence, I just need two agents. One for taking decisions such as "explore" and "open" (high level policy) and the other low level policy for accomplishing the exploration+navigation.

**Comment by Miffyli** [comment]
@sycz00 Yup this kind of stuff goes beyond SB3 and you would have to modify the code to have algorithms like this. Doing it the manual way of defining two agents is not very elegant and you miss a lot of potential (e.g. usually gradient information is passed between hierarchies, see [feudal networks for RL](https://arxiv.org/abs/1703.01161) for an example).

You can close this issue if no further questions remain.

**Comment by araffin** [comment]
After a quick search on Github, you can probably take a look at:
- https://github.com/NotAnyMike/HRL
- https://github.com/AboudyKreidieh/h-baselines

Both are using SB2, but SB3 shares the same API.

with SB3:
- https://github.com/guojm14/HRL

**Comment by sycz00** [comment]
alright thank you both for your good answers ! I am gonna close the question.
