### ISSUE TITLE
[Bug] `device` not always a positional argument 

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/stable-baselines3#701]
This is not really a bug, but rather an inconsistency in the use of `device` as an argument. 
It is sometimes a positional argument, sometimes a keyword argument. I will submit a PR to fix this.

**Comment by Miffyli** [comment]
Sounds good! Examples of this in issues would be nice (just one is enough), but you can add that once you have done the PR :)

**Comment by qgallouedec** [comment]
When I define a custom buffer (`MyBuffer`), with an additional positional argument (`my_arg`),

```python
import gym

from stable_baselines3.common.buffers import ReplayBuffer
from stable_baselines3.dqn.dqn import DQN


class MyBuffer(ReplayBuffer):
    def __init__(
        self,
        buffer_size,
        observation_space,
        action_space,
        my_arg,
        device = "cpu",
        n_envs = 1,
        optimize_memory_usage = False,
        handle_timeout_termination= True,
    ):
        super().__init__(buffer_size, observation_space, action_space, device, n_envs, optimize_memory_usage, handle_timeout_termination)


env = gym.make("CartPole-v0")
DQN("MlpPolicy", env, replay_buffer_class=MyBuffer, replay_buffer_kwargs={"my_arg": 1})
```

I encounter the following error:

```bash
Traceback (most recent call last):
  File "/Users/quentingallouedec/stable-baselines3/src/bug.py", line 25, in <module>
    model = DQN("MlpPolicy", env, replay_buffer_class=MyBuffer, replay_buffer_kwargs={"my_arg": 1})
  File "/Users/quentingallouedec/stable-baselines3/stable_baselines3/dqn/dqn.py", line 132, in __init__
    self._setup_model()
  File "/Users/quentingallouedec/stable-baselines3/stable_baselines3/dqn/dqn.py", line 135, in _setup_model
    super(DQN, self)._setup_model()
  File "/Users/quentingallouedec/stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 213, in _setup_model
    self.replay_buffer = self.replay_buffer_class(
TypeError: __init__() got multiple values for argument 'my_arg'
```

The error seems not to be related with `device`, but it is. The error comes from these lines
- https://github.com/DLR-RM/stable-baselines3/blob/798b16aaf76ec051498a730a1d922e00184b4473/stable_baselines3/common/off_policy_algorithm.py#L200
- https://github.com/DLR-RM/stable-baselines3/blob/798b16aaf76ec051498a730a1d922e00184b4473/stable_baselines3/common/off_policy_algorithm.py#L207
- ...

Since the `device` is passed as a positional argument, it makes it impossible to pass custom arguments.

**Comment by araffin** [comment]
> Since the device is passed as a positional argument, it makes it impossible to pass custom arguments.

This is not true (as it depends on the order of arguments), however I agree we should make it consistent.
