### ISSUE TITLE
set_parameters() listed as load_parameters() in documentation.

### ISSUE THREAD

**Issue by aborger** [DLR-RM/stable-baselines3#706]
### 📚 Documentation

The [documentation](https://stable-baselines.readthedocs.io/en/master/modules/td3.html) defines the set_parameters() method for TD3 as load_parameters().

Following the documentation results in ``` AttributeError: 'TD3' object has no attribute 'load_parameters' ```

``` python
import gym
from stable_baselines3 import TD3
env = gym.make('Pendulum-v0')
parameters = model.get_parameters()
model.load_parameters(parameters)
```

Where as the following works properly:
``` python
import gym
from stable_baselines3 import TD3
env = gym.make('Pendulum-v0')
parameters = model.get_parameters()
model.set_parameters(parameters)
```

This is using stable-baselines3 version 1.1.0.

**Comment by Miffyli** [comment]
You are reading SB documentations, not SB3 :). Stuff [here](https://stable-baselines3.readthedocs.io/en/master/modules/td3.html) is right.

This is an easy mistake even I have made few times (reading SB doc for SB3 stuff). We should consider adding something that makes it blatantly clear which documentation one is reading.

**Comment by qgallouedec** [comment]
What about adding the version warning as a banner of every page ?
![Screenshot from 2022-08-31 15-53-39](https://user-images.githubusercontent.com/45557362/187695855-5fd5e96b-4981-4b6b-a6ca-4bf01f753f45.png)

**Comment by araffin** [comment]
sounds good =)
