### ISSUE TITLE
[Question] What do the EvalCallback warnings mean as they relate to SubprocVecEnv, DummyVecEnv, and the Monitor wrapper?

### ISSUE THREAD

**Issue by Radilx** [DLR-RM/stable-baselines3#717]
### Question

I have defined my training environment like so:

```Python
env = SubprocVecEnv([make_env() for i in range(num_cpu)])
```

When I try to define my eval environment:

```Python
eval_env = MyEnv()
```

It gets automatically wrapped in a DummyVecEnv and I get a warning that `DummyVecEnv != SubprocVecEnv`. 

So, when I attempt to fix that:

```Python

eval_env = SubprocVecEnv([make_eval_env()])
```

I now end up with a warning that it's not wrapped in a `Monitor` wrapper.

```
/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/evaluation.py:69: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
```

After fixing that, all of these warnings go away. However, I am trying to understand what they mean. 

### Additional context

My question is: 

1.) Why are these **warnings** and not **errors**?  Shouldn't it be critical if the training and eval environments are not the same?

2.) What is an example of a problem that might arise if the training environment is a SubprocVecEnv, and the eval environment is a DummyVecEnv? To me it doesn't seem to matter.

3.) Is it really a problem if the `Monitor` Wrapper is omitted? Why would my SubprocVecEnv/DummyVecEnv ever edit the "episode length" or "reward" as the warning suggests?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

> 1.) Why are these warnings and not errors? Shouldn't it be critical if the training and eval environments are not the same?

> 2.) What is an example of a problem that might arise if the training environment is a SubprocVecEnv, and the eval environment is a DummyVecEnv? To me it doesn't seem to matter.

Your question 2) is answering question 1)...
or as the comment in the code says:
https://github.com/DLR-RM/stable-baselines3/blob/507ed1762e62bd6c4e85ea572ba166b69116b1ac/stable_baselines3/common/callbacks.py#L335

> 3.) Is it really a problem if the Monitor Wrapper is omitted? Why would my SubprocVecEnv/DummyVecEnv ever edit the "episode length" or "reward" as the warning suggests?

It is not a problem as long as you don't modify the reward, for instance using `VecNormalize` or an Atari wrapper.

**Comment by Radilx** [comment]
Ah okay, thank you!
