### ISSUE TITLE
SquashedDiagGaussianDistribution for PPO

### ISSUE THREAD

**Issue by geruLt** [DLR-RM/stable-baselines3#722]
Is it possible to use this distribution on PPO to constraint the action outputs? My problem is that the model outputs are almost always clipped to 1 or -1. I tried to add a tanh layer to the  DiagGaussianDistribution but that again gave outputs outside [-1,1].

**Comment by Miffyli** [comment]
Hmm I think it could technically work (but I can not speak for theory part, but I do not see why it would not work).

For clarity: if you specify action space to have `low=-1, high=1`, SB3 will clip the actions to this range (but as you might have figured out, this might not be the most ideal option) :)

**Comment by araffin** [comment]
> My problem is that the model outputs are almost always clipped to 1 or -1.

Have you read the "tips and tricks" section in the doc?

> Is it possible to use this distribution on PPO to constraint the action outputs? 

is it possible but you will need to use gSDE for that, an example config: 

https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml#L137

you will need to pass `squash_output=True` to the policy kwargs

https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/policies.py#L471

PS: please fill up the issue template completely next time (we have a dedicated one for custom env, but beware that we do not do tech support)

**Comment by araffin** [comment]
Some additional reference: https://github.com/DLR-RM/stable-baselines3/issues/2142#issuecomment-4056934939
