### ISSUE TITLE
[Question] VecNormalize for Dict obs

### ISSUE THREAD

**Issue by buoyancy99** [DLR-RM/stable-baselines3#724]
Hi, I am wondering if this [line](https://github.com/DLR-RM/stable-baselines3/blob/e9a8979022d7005560d43b7a9c1dc1ba85f7989a/stable_baselines3/common/vec_env/vec_normalize.py#L41) here is intentional. 

Currently, if we are using Dict observation and set norm_obs is set to False, if we don't pass norm_obs_keys, an error will be raise at this [line](https://github.com/DLR-RM/stable-baselines3/blob/e9a8979022d7005560d43b7a9c1dc1ba85f7989a/stable_baselines3/common/vec_env/vec_normalize.py#L53), since it bypass _sanity_checks

**Comment by buoyancy99** [comment]
To reproduce
```
import gym
import numpy as np
from stable_baselines3 import SAC
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.vec_env import VecNormalize


class TestEnv(gym.Env):
    def __init__(self):
        super(TestEnv, self).__init__()
        self.observation_space = gym.spaces.Dict(dict(
            image=gym.spaces.Box(low=0, high=255, shape=(84, 84, 3), dtype=np.uint8),
            joints=gym.spaces.Box(low=-1, high=1, shape=(20,), dtype=np.float32),
        ))
        self.action_space = gym.spaces.Box(low=-1.0, high=1.0, shape=(4,), dtype=np.float32)

    def step(self, action):
        return self.observation_space.sample(), 0, False, {}

    def reset(self):
        return self.observation_space.sample()

print('Testing Offpolicy without VecNormalize')
env = DummyVecEnv([lambda: TestEnv()] * 2)
model = SAC(policy='MultiInputPolicy', env=env, verbose=1)
model.learn(50)
print('Succss')

print('Testing Offpolicy with VecNormalize')
env = DummyVecEnv([lambda: TestEnv()] * 2)
env = VecNormalize(env, norm_obs=False)
model = SAC(policy='MultiInputPolicy', env=env, verbose=1)
model.learn(50)
print('Succss')


```

**Comment by araffin** [comment]
Hello,
thanks for reporting the bug. As a simple fix for now, you can pass `norm_obs_keys=[]` but the block https://github.com/DLR-RM/stable-baselines3/blob/e9a8979022d7005560d43b7a9c1dc1ba85f7989a/stable_baselines3/common/vec_env/vec_normalize.py#L51 should be skipped if `norm_obs=False`, we would appreciate a PR that solves this issue ;)

**Comment by buoyancy99** [comment]
Great, I will work in a or soon
