### ISSUE TITLE
[Bug] VecMonitor not handling info_keywords argument correctly

### ISSUE THREAD

**Issue by ScheiklP** [DLR-RM/stable-baselines3#728]
### 🐛 Bug

The [`VecMonitor`](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/vec_env/vec_monitor.py
) correctly instantiates a writer that includes columns with the `info_keywords`
```
self.results_writer = ResultsWriter(
                filename, header={"t_start": self.t_start, "env_id": env_id}, extra_keys=info_keywords
            )
```
But the `step_wait` does not consider them
```
episode_return = self.episode_returns[i]
episode_length = self.episode_lengths[i]
episode_info = {"r": episode_return, "l": episode_length, "t": round(time.time() - self.t_start, 6)}
    if self.results_writer:
        self.results_writer.write_row(episode_info)
```

compared to the non-vector version [`Monitor`](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/monitor.py)
```
for key in self.info_keywords:
    ep_info[key] = info[key]
```

### To Reproduce

```python
import gym
from stable_baselines3.common.vec_env import DummyVecEnv, VecMonitor
from gym.envs.registration import register
from stable_baselines3.common.envs.bit_flipping_env import BitFlippingEnv

register(
    id="BitFlippingEnv",
    entry_point=BitFlippingEnv,
)

env = DummyVecEnv([lambda: gym.make("BitFlippingEnv")])
env = VecMonitor(env, info_keywords=("is_success",), filename="extra_info")

model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=25000)
```

### Expected behavior

There should be a `extra_info.monitor.csv` file that contains the `is_success` column, but no data in that column.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue, we would be happy to receive a PR that solves it ;)
