### ISSUE TITLE
[Question] action_space as gym.spaces.Dict is supported? Is it going to be supported?

### ISSUE THREAD

**Issue by EloyAnguiano** [DLR-RM/stable-baselines3#731]
### Question
I have seen that little by little the algorithms are adapting to be able to receive a state of the dictionary type as specified [here](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#multiple-inputs-and-dictionary-observations), but I have not seen any reference to algorithms that can use this same of strategies for the case of use of the space of the actions. Is it possible to do this with SB3 or do you plan to address work in this direction?

### Additional context

I am trying to assess SB3 as a good option to address the grid2op environments of l2rpn competition. Such type of environments, have a functionality to be translated to a GYM environment, but both the action space and the observation space are dictionary type. More information can be found [here](https://grid2op.readthedocs.io/en/latest/gym.html).

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by edbeeching** [comment]
Hello Antonin.

A number of environments implemented in [Godot RL Agents](https://github.com/edbeeching/godot_rl_agents) include independant discrete and continuous action spaces. This is represented as a Gym Dict with nested Box and Discrete spaces.

I was curious if you have any ideas about how to handle this use case?

Thanks

**Comment by EloyAnguiano** [comment]
I think that this adaptation should be taken into account at some point. Sometimes you have to choose an entity (Discrete) to perform an action (Binary, Discrete, Continous, ...). The clearest example is the Deepmind's agent to beat Dota2. Of course you can make the combinaroty of some of those actions a MultiDiscrete action space, but now I have an environment that making that combinatory makes a Discrete environment of 145k actions instead of using a Dict action space. RLLib has this implemented and, as you said, there are some implementations available. Is there any strong reason for this not being at the roadmap? 

I think that the library could be much more versatile with this.
