### ISSUE TITLE
[Question] Is is a problem when policy loss, entropy loss and value loss differs a lot with each other?

### ISSUE THREAD

**Issue by Waterkin** [DLR-RM/stable-baselines3#737]
### Question

Your question. This can be e.g. questions regarding confusing or unclear behaviour of functions or a question if X can be done using stable-baselines3. Make sure to check out the documentation first.

### Additional context

![image](https://user-images.githubusercontent.com/41324537/150824588-d2b9c04e-eb37-4538-aa58-078ab8e8eccb.png)

### Checklist

- [ ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Waterkin** [comment]
What should I do if this is a problem?

**Comment by Miffyli** [comment]
It is not a major issue if the losses do not exactly match, but they should be in the similar range (i.e. one should not be 1e7 like you have) :). You should downscale your rewards (e.g. multiply them by 0.01).

Note that we do not offer custom tech support, so unless you have bugs to report or enhancement ideas, please close this issue.
