### ISSUE TITLE
Is it possible to learn how to balance inverted pendulum and stop in fixed position also? Thank you a lot!

### ISSUE THREAD

**Issue by newforrestgump001** [DLR-RM/stable-baselines3#740]
Is it possible to learn how to balance inverted pendulum and stop in fixed position also?(for pid control loop: inner loop controls the theta, and the out loop controls the position). Thank you a lot!

**Comment by Miffyli** [comment]
Please fill in the issue template and add more information. This sounds like a custom(-ish) environment task, for which we do not offer tech support (we do not have answers on if algorithm X will solve environment Y).

**Comment by araffin** [comment]
closing as not related to SB3 but rather a custom gym env (and issue template not filled).
