### ISSUE TITLE
RGBD image as input for custom gym environment 

### ISSUE THREAD

**Issue by gmp-prem** [DLR-RM/stable-baselines3#747]
Hello everyone,

I have a custom environment created using OpenAI Gym that the observation space input is an image, I have read through the custom environment [documentation](https://stable-baselines3.readthedocs.io/en/master/guide/custom_env.html#) section of the SB3 where it states that if using image as input, the data type should be `np.uint8` in the range of `[0, 255]` only. So when declaring observation space in the code should be 

```
observation_space = spaces.Box(low=0, high=255, shape=(N_CHANNELS, HEIGHT, WIDTH), dtype=np.uint8)
```

I guess that the above code is for the observation space that has the same type of data

My question is that is it possible for the observation space to contain the image that its data type is not the same. In my case,  the RGB has a data type of `np.uint8` and Depth Image has the data type of `np.uint16`?

Can someone guide me?

I'm quite new to SB3 and openAI gym, If more information is needed, please let me know

Thank you

**Comment by Miffyli** [comment]
Hey! I would recommend mapping your depth values to uint8 if possible. This way you could add depth as one of the channels in addition to RGB values, and SB3 normalizes the values appropriately.On 1 Feb 2022 09:46, prem_ ***@***.***> wrote:
Hello everyone,
I have a custom environment created using OpenAI Gym that the observation space input is an image, I have read through the custom environment documentation section of the SB3 where it states that if using image as input, the data type should be np.uint8 in the range of [0, 255] only. So when declaring observation space in the code should be
observation_space = spaces.Box(low=0, high=255, shape=(N_CHANNELS, HEIGHT, WIDTH), dtype=np.uint8)

I guess that the above code is for the observation space that has the same type of data
My question is that is it possible for the observation space to contain the image that its data type is not the same. In my case,  the RGB has a data type of np.uint8 and Depth Image has the data type of np.uint16?
Can someone guide me?
I'm quite new to SB3 and openAI gym, If more information is needed, please let me know
Thank you

**Comment by gmp-prem** [comment]
Thank you very much for your reply.

I see, and another question please,

I have looked into the SB3 preprocessing script [here](https://github.com/DLR-RM/stable-baselines3/blob/54bcfa4544315fc920be0944fc380fd75e2f7c4a/stable_baselines3/common/preprocessing.py#L85), it is mentioned to return the normalized image by fix the divider to 255.0 for 8-bit image. In my case, If I add additional part for 16-bit normalization for 16-bit image input (Depth image and divided by 65536.0),  Would there be any side effect to the base policy of SB3?

**Comment by Miffyli** [comment]
It is likely enough that you only change that function and `is_image_space` function to also accept uint16 images :).

However I want to advice against using MultiInputPolicy as it will be slower (overhead from dict observations). Stack your RGB and D images on top of each other, preferably in uint8, or if you do the modification you can then stack all in uint16. Make sure the normalization does not fail on you (the values to network should be in [0, 1]), otherwise you will get subpar training performance.

**Comment by gmp-prem** [comment]
Thank you so much for your reply 😄 

I will close this issue.
