### ISSUE TITLE
[question]how to run model on multi gpu 

### ISSUE THREAD

**Issue by wujiren** [DLR-RM/stable-baselines3#75]
**Problem Description**
if i want train model in more than one gpu ,should i just state like this:
```python
import gym
from stable_baselines3.a2c import MlpPolicy
from stable_baselines3 import PPO
import os

if __name__ == '__main__':
    os.environ['CUDA_VISIBLE_DEVICES'] = "0,1"
    env = gym.make('CartPole-v1')
    model = PPO(MlpPolicy, env, verbose=1,
                policy_kwargs={'net_arch': [dict(pi=[4096, 4096, 4096, 4096, 4096], vf=[4096, 4096, 4096, 4096, 4096])]},
n_steps=8192*8, batch_size=8192*4, n_epochs=2)
    model.learn(total_timesteps=1e6)

    obs = env.reset()
    for i in range(1000):
        action, _state = model.predict(obs, deterministic=True)
        obs, reward, done, info = env.step(action)
        env.render()
        if done:
            obs = env.reset()
```

to check the gpu utility, i used a very big mlp network and batch size, but it seems not work.
the nvidia-smi show as below:
```
Every 1.0s: nvidia-smi                                                                                                                Sat Jun 27 21:05:03 2020

Sat Jun 27 21:05:03 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 29%   61C    P2   148W / 250W |   6211MiB /  7952MiB |     72%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:03:00.0 Off |                  N/A |
| 20%   32C    P8     5W / 250W |     10MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:83:00.0 Off |                  N/A |
| 20%   29C    P8    16W / 250W |     10MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:84:00.0 Off |                  N/A |
| 20%   29C    P8     1W / 250W |     10MiB /  7952MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2880      C   python                                      6201MiB |
+-----------------------------------------------------------------------------+
```
what should i do if i want use more than one gpu?

**Comment by Miffyli** [comment]
Multi-GPU training is not supported, and probably not planned in short-term future. The GPU compute power is rarely the issue with synchronous methods, and using very large networks is very beneficial outside edge-cases like SC2 and Dota 2.

**Comment by wujiren** [comment]
> Multi-GPU training is not supported and not planned in short-term future. The GPU compute power is rarely the issue with synchronous methods, and using very large networks is very beneficial outside edge-cases like SC2 and Dota 2.
> 
> Edit: Using GPU can even slow things down with simple environments like `CartPole` and other "basic control" tasks from Gym.

thanks. and i also tried to use multi gpu in stable-baselines tensorflow version, it seems not work too, is that version not support multi gpu neither?

**Comment by araffin** [comment]
Related:
- https://github.com/hill-a/stable-baselines/issues/308
- https://github.com/araffin/rl-baselines-zoo/issues/72
- https://github.com/araffin/rl-baselines-zoo/issues/83

So, unless you are using distributed algorithms as in #69 it honestly does not make sense to use more than one GPU.
And with PPO, using CPU only is only faster (maybe not for big CNN though).

**Comment by wujiren** [comment]
> Related:
> 
> * [hill-a/stable-baselines#308](https://github.com/hill-a/stable-baselines/issues/308)
> * [araffin/rl-baselines-zoo#72](https://github.com/araffin/rl-baselines-zoo/issues/72)
> * [araffin/rl-baselines-zoo#83](https://github.com/araffin/rl-baselines-zoo/issues/83)
> 
> So, unless you are using distributed algorithms as in #69 it honestly does not make sense to use more than one GPU.
> And with PPO, using CPU only is only faster (maybe not for big CNN though).

thanks for your answer.actually the code above is just a test for multi-gpu, the actual network  is a bit large. because ppo benefit from big batch size(n_steps*env_numbers), i use 48 cpus to sample data (about 1 hour), the data need 3 or 4 hours to train, so i want use multi-gpu to speedup.
if i want to change ppo to use multi-gpu, which module should i  adjust？
