### ISSUE TITLE
RuntimeError: File size unexpectedly exceeded ZIP64 limit when saving a model using checkpoint

### ISSUE THREAD

**Issue by olyanos** [DLR-RM/stable-baselines3#759]
Hi,
I am using SB3 PPO to train my model.
However, my DNN size is huge due the fact the problem I am working on is complex.
I used this checkpoint code a lot and it works perfectly on smaller problems.
I am trying to use checkpoint callback to avoid retraining but evry time the model tries to save a checkpoint I get the following error:
**RuntimeError: File size unexpectedly exceeded ZIP64 limit**

How can I remove the restriction of 2 GiB ? or at least increase it?

Thanks

sys info:
Linux ubuntu 20.10
Tensorflow version = 2.6.0
Keras version = 2.6.0
Stable baseline version = 1.2.0
OpenAI Gym version = 0.19.0
Torch version = 1.9.1
Python version = 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
NVIDIA GeForce RTX 3090

**Comment by olyanos** [comment]
I used a work around to get past this problem, I found the solution here:
https://github.com/numpy/numpy/issues/10776

Basically I had to change the code in:
/usr/lib/python3/dist-packages/numpy/lib/npyio.py

previous code:
    if sys.version_info >= (3, 6):
        # Since Python 3.6 it is possible to write directly to a ZIP file.
        for key, val in namedict.items():
            fname = key + '.npy'
            val = np.asanyarray(val)
            # always force zip64, gh-10776
            with zipf.open(fname, 'w', force_zip64=True) as fid:
                format.write_array(fid, val,
                                   allow_pickle=allow_pickle,
                                   pickle_kwargs=pickle_kwargs)

New code to bypass the issue:
    if sys.version_info >= (3, 6):
        # Since Python 3.6 it is possible to write directly to a ZIP file.
        for key, val in namedict.items():
            fname = key + '.npy'
            nbytes = 0
            if isinstance(val, dict):
                nbytes = sum(v.nbytes for v in val.values())
            elif isinstance(val, list):
                nbytes = sum(v.nbytes for v in val
            val = np.asanyarray(val)
            nbytes += val.nbytes
            force_zip64 = val.nbytes >= 2**30
            # always force zip64, gh-10776
            with zipf.open(fname, 'w', force_zip64=True) as fid:
                format.write_array(fid, val,
                                   allow_pickle=allow_pickle,
                                   pickle_kwargs=pickle_kwargs)

I know this is not a clean approach to the matter, but it is a temporary work around.
If anyone can suggest a better solution please post it here, in the meantime I will close this issue.

**Comment by Miffyli** [comment]
Oh snap, that is a headache we have not thought of (2GB model is _huge_ for RL, though! I would first advice looking into it and figuring out if something is off in the model. More parameters generally means it will be harder to train).

The most elegant solution would be to change what kind of archive file is used [here](https://github.com/DLR-RM/stable-baselines3/blob/1564a8508175ae152a6ba7bf51fa186030abae85/stable_baselines3/common/save_util.py#L312) (and same for loading). That should fix the issue, although I do not what other archives could work (e.g. maybe `tar` file?).

**Comment by olyanos** [comment]
Hi Anssi,

Thank you for your reply.
Yeah the problem I am working on is complex with a huge action space thus needing a large network to map states into actions.
I will work on the solution you suggested and post it here as soon as I figure it out.

Thanks.
