### ISSUE TITLE
[Question] Trying to run a setup like Nature DQN, is it normal to not get as good results?

### ISSUE THREAD

**Issue by pedrohpf** [DLR-RM/stable-baselines3#761]
### Question

I'm running a setup like Nature DQN, the game I'm running is Atari's Beam Rider. In the paper their best agent got an average score of 6846 in evaluation. However, the max evaluation I got was 4241.8 with the rest hovering around 3000.
Am I doing something wrong?

### Additional context

I used the zoo (https://github.com/DLR-RM/rl-baselines3-zoo) to run the tests, was not sure if here was the right place to ask this question or in the zoo. Due to memory contraints I ran with 300k replay memory (instead of 1M), but for the rest of the parameters I used the same as the Nature paper.

[BeamRiderNoFrameskip-v4.zip](https://github.com/DLR-RM/stable-baselines3/files/8009232/BeamRiderNoFrameskip-v4.zip)

I also saw the graphs in Noisy DQN paper (https://arxiv.org/abs/1706.10295) and the one for Beam Rider using Nature DQN shows the DQN agent quickly surpassing 5k score early into the training and maintaining that performance through the rest of the training:

![BeamRiderNoisy](https://user-images.githubusercontent.com/36662762/152664005-c255bb81-8363-423b-beea-1971b3bb6e73.png).

The reason I'm trying to compare all of this is because my own DQN implementation was getting worse performance compared to the papers and increasing the memory was not helping. That's why I started running your implementation to check if the results were similar and they do seem similar.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
First thing to note here is that the DQN implementation originates from the original openai baselines, and I am not sure if it ever was checked against the original paper / original source code results. There can be many things that are off from the original implementation:
- Something is different in the preprocessing (stepping, framestacking, episode starting, etc). Unlikely, but possible.
- Network initialization was different
- Underlying libraries were different which may cause different results (this has happened with e.g. TF vs. PyTorch)
- Something has changed in the Gym or underlying Atari games (I do not think the full source code of original DQN was ever made public).

Matching the performance of results without source code is very painful and filled with oddities like this. I recommend you try to find as close-to-the-source repo of the code as possible (e.g. some later code base from Deepmind which used DQN as a baseline).

**Comment by araffin** [comment]
To add to @Miffyli answer, you can find OpenAI Baselines DQN learning curve here: https://htmlpreview.github.io/?https://github.com/openai/baselines/blob/master/benchmarks_atari10M.htm (I don't remember if it was DQN + extensions but probably yes)

**Comment by araffin** [comment]
Closing as original question was answered.
