### ISSUE TITLE
[Feature Request] Allow PPO to turn of advantage normalization

### ISSUE THREAD

**Issue by vwxyzjn** [DLR-RM/stable-baselines3#762]
### 🚀 Feature

Allow PPO to turn of advantage normalization.

### Motivation

In SB3 we can turn off the advantage normalization in A2C via `normalize_advantage=False` but not in PPO.

### Pitch

Add `normalize_advantage` flag in PPO's parameter

### Alternatives

Remove A2C entirely and reproduce A2C by using PPO.

**Comment by araffin** [comment]
closed in #763
