### ISSUE TITLE
How to display training results with stable-baselines3

### ISSUE THREAD

**Issue by PBerit** [DLR-RM/stable-baselines3#769]
Hi all,

I have defined an agent and I would like to see the training results. For that I use the following code (with a custom environment):
```
from stable_baselines3 import A2C
import os

env = DSM_BT1_Env()
models_dir = "models/A2C"
logdir = "logs"

timesteps = 1000
if not os.path.exists(models_dir):
    os.makedirs(models_dir)
    
if not os.path.exists(logdir):
    os.makedirs(logdir)
    

model = A2C('MlpPolicy', env, verbose=1, tensorboard_log=logdir)

timesteps = 1000
for i in range (1, 5):
    model.learn(total_timesteps=timesteps, reset_num_timesteps=False,  tb_log_name = "A2C")
    model.save(f"{models_dir}/{timesteps*i} ")
```

So I log the data in a folder called log which is created during training and in that folder a subfolder with the name A2C_0 is created that contains a lot of files. Now I tried to visualize it the same way as it is done in a tutorial (https://www.youtube.com/watch?v=dLP-2Y6yu70) . For that I tried to open Tensorboard with the following command line:
`#tensorboard --logdir=logdir --host localhost --port 8088`
Altough I can open Tensorboard, no related training results are displayed. I also tried other commands like:
`tensorboard --logdir="C:/Users/Desktop/Python/Stable_Baselines3/logs" --host localhost --port 8088`
but that led to the same result. 

Now my question is, how can I display the training results of stable-baselines3 agents? It does not necessarily have to be with Tensorboard. I just want to display the logged data for the training (this could be for example also done with matplotlib). Do you have any idea how I can do that?

**Comment by Miffyli** [comment]
Hey. Note that we do not offer much tech support, these issues are for bug reports and enhancement proposals :). But:

- You could try Weights & Biases integration which is much easier way to use tensorboard like logging (highly recommended): https://stable-baselines3.readthedocs.io/en/master/guide/integrations.html#weights-biases
- The `Monitor` wrapper, which creates csv files of the episodes (but no other stats unfortunately), can be read with functions in SB3. See this example on how `load_results` function can be used: https://stable-baselines3.readthedocs.io/en/master/guide/examples.html?highlight=load_results#using-callback-monitoring-training

**Comment by PBerit** [comment]
@Miffyli: Thanks Miffyli for your answer. Actually, I treid Weights&Biases and it worked. HOWEVER, it has many cruical drawbacks (you have to run everything as an admin, you have to register and authorize, I highly question the privacy). Because of this I don't want to use it. Is there no other easy way of visualizing the training results of stable-baselines3? Can you for example not just use matplotlib for displaying the training results or is there no built-in function in stable-baselines3 for doing that?

**Comment by Miffyli** [comment]
Ah, fair enough :). That is one drawback of wandb.

And unfortunately no. For training stats they are only logged to the stdout (the printout you see, you can modify the logger to print out stats to csv files as well) and the tensorboard. See configuring logger here: https://stable-baselines3.readthedocs.io/en/master/common/logger.html

**Comment by Syrlander** [comment]
Isn't callbacks also intended for this purpose?
https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html
Here you can implement `_on_step` which is triggered every step of the environment.

However, it doesn't seem to be possible to have a callback trigger once every episode. So far I've only been able to create such an event trigger by a weird hack that sub-classes the Monitor. If there isn't a nicer way to create such a callback event I think it would be a useful addition to the callback. Although, I'm not entirely sure if there would be any issues in relation  to running with multiple environments.

**Comment by Miffyli** [comment]
Callbacks indeed are one way of doing this, but to get the stats of training algorithm you need to start accessing the agent's stats and whatnot (which already are dumped by logger or to tensorboard). You could try to track episodes by doing `_on_step` and then reading the appropriate `done` variable and checking if it is `True` for some envs, but to do this you have to dig a little where `_on_step` is called.

**Comment by PBerit** [comment]
@Miffyli : Thanks for your answer Miffyli. So can I use Tensorboard without wandb? I tried to do this (see my first post) but it did not work. Any idea what the problem might be?

**Comment by Miffyli** [comment]
Yes, Tensorboard should work as is, but sadly I do not have guidance to give on what could be going wrong :/. Perhaps googling or asking on forums. See [RL Discord](https://discord.com/invite/xhfNqQv) for one potential source of help.

**Comment by PBerit** [comment]
@Miffyli: Thanks Miffyli for your answer. Actually I had asked this question on Stackoverflow (https://stackoverflow.com/questions/71068906/tensorboard-either-shows-unrelated-outcome-or-does-not-start) but have not received any answer. Further, I tried to follow exactly the instructions on the offical website of Stable Baselines3 (https://stable-baselines.readthedocs.io/en/master/guide/tensorboard.html) but it did not change anything. This is why I tried to ask this question here. Maybe someone else has the same problem or another solution.

**Comment by Miffyli** [comment]
Hmm right. I'd recommend trying to copy projects that use tensorboard and see how they work (e.g. see how [stable-baselines3 zoo](https://github.com/DLR-RM/rl-baselines3-zoo/) uses tensorboard, and try running some codes to verify it still works). 

I am closing this as resolved. If you find a bug which prevents tensorboard working, please open up a new issue :)

**Comment by PBerit** [comment]
Okay. Thanks Miffyli for your advice.
