### ISSUE TITLE
[Feature Request] Callback for logging any extra episode info

### ISSUE THREAD

**Issue by ScheiklP** [DLR-RM/stable-baselines3#783]
### 🚀 Feature
A callback that is called on rollout end that goes through the episode infos and logs everything that can be averaged.

### Motivation
https://github.com/DLR-RM/stable-baselines3/pull/730 added writing additional info kwargs into the episode info dict.
The information is correctly added to the episode info dict, but OnPolicyAlgorithm does not log it (because it does not know, that extra keywords exist).

### Pitch
The callback is called on rollout end, goes through the episode infos and logs everything that can be averaged.

### Alternatives
Modifying OnPolicyAlgorithm directly.

### Checklist
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by ScheiklP** [comment]
Incorrectly posted as a PR here https://github.com/DLR-RM/stable-baselines3/pull/751

**Comment by araffin** [comment]
Hello,

> Alternatives

writing a custom callback because it has access to `self.locals["infos"]` at every step?

**Comment by ScheiklP** [comment]
Hi,
ah, I see.
My use case was targeted more specifically at the info of a completed episode.
For example "what is my final distance to point X, when the episode ends?".

**Comment by araffin** [comment]
>  My use case was targeted more specifically at the info of a completed episode.

You also have access to `self.locals["dones"]`

**Comment by ScheiklP** [comment]
Ok, then I'll close the PR. :)
