### ISSUE TITLE
[Question] Why is the SARSA algorithm not available in Stable Baselines 3

### ISSUE THREAD

**Issue by PBerit** [DLR-RM/stable-baselines3#786]
Actually I am new in the field of Reinforcement Learning and I have often encoutered the SARSA algorithms in books, tutorials, videos etc.. It seems to be a very popular on-policy learning algorithm for Reinforcement learning. However, it noticed that it is not available in Stable Baselines 3. Is there a specific reason for that and is it planned to be included in future updates of Stable Baselines 3?

**Comment by Miffyli** [comment]
stable-baselines3 is mainly for "deep" reinforcement learning algorithms, where algorithms like A2C and DQN and PPO are the prominent "baselines". While SARSA is applicable, maybe as an modification of DQN, it has not been used much in deep learning literature, and has not received enough attention for somebody to add it to SB3. However if you feel like experiment, we could review a PR to add it to our [contrib](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/) package :).

**Comment by araffin** [comment]
Hello,
I would consider SARSA out of scope of SB3 (because we mostly focus on DeepRL and not tabular RL), however you can take a look at [Mushroom RL](https://github.com/MushroomRL/mushroom-rl) if you are looking for implementation of such algorithm ;)

**Comment by PBerit** [comment]
Thanks for your answers.

**Comment by araffin** [comment]
> can you highlight the differences between SB3 and Mushroom RL?

i recommend you to read our paper/blog post (link is in the readme), we also have an issue here: #20

The table you are showing is about Stable baselines (SB2), not SB3.
