### ISSUE TITLE
[Bug] `env` argument in `HerReplayBuffer.sample` is not `None` by default

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/stable-baselines3#788]
Hi,

It looks like the `env` argument of the method `sample` of `HerReplayBuffer` is not `None` by default. 

https://github.com/DLR-RM/stable-baselines3/blob/13fcb124711be4de86199a628acaedd215931756/stable_baselines3/her/her_replay_buffer.py#L198

To be consistent with other replay buffer, I suggest the following modification:

```python
 env: Optional[VecNormalize] = None,
```

**Comment by Miffyli** [comment]
Thanks for spotting this and taking your time to report it!
And yup, indeed it should default to None. A PR would be very much welcomed :)
