### ISSUE TITLE
DummyVecEnv NoneType

### ISSUE THREAD

**Issue by Nafiseh-Izadyar** [DLR-RM/stable-baselines3#791]
Hi,
def _save_obs(self, env_idx: int, obs: VecEnvObs) -> None:
        for key in self.keys:
            if key is None:
                self.buf_obs[key][env_idx] = obs
            else:
                self.buf_obs[key][env_idx] = obs[key]

Here if the key doesn't exist , self.buf_obs[key][env_idx] = obs happens, while the key is None.

**Comment by araffin** [comment]
Hello,
is there a bug to report? If so please fill up the issue template completely.

> if the key doesn't exist 

If the key does not exist, an error will be thrown.
If `key=None` (which is the case for observation spaces that are not dictionary), then the first branch will be used.
