### ISSUE TITLE
[Question] how to train RL dynamically (online) using SB3?

### ISSUE THREAD

**Issue by YimengZhang94** [DLR-RM/stable-baselines3#792]
I need a model learning online, which means it receives different rewards in different time steps and needs to be trained online. So I can't use model.learn(total_timesteps=10000) in a offline setting. But I didn't find any information about how to apply SB3 in a dynamic setting. I tried model.learn(total_timesteps=1) for time_step in time_horizon, but it's much slower than model.learn(total_timesteps=10000). Is there a way to train RL online rather than offline using SB3? Any suggestion is welcome and thanks in advance.

**Comment by Miffyli** [comment]
Hey. Next time please fill in the template :)

Indeed using `total_timesteps=1` is slow because there is quite a bit of overhead from every `learn` call, and the algorithms are not designed to be used this way. However, there is no "other" support for "online" training.

May I ask why you can not use `learn` function? The environment could change its behaviour during training during `learn` call, and this would achieve the same result. It requires bit more tinkering (you need to hide your dynamic env logic to the environment code), but should be doable.

**Comment by YimengZhang94** [comment]
> Hey. Next time please fill in the template :)
> 
> Indeed using `total_timesteps=1` is slow because there is quite a bit of overhead from every `learn` call, and the algorithms are not designed to be used this way. However, there is no "other" support for "online" training.
> 
> May I ask why you can not use `learn` function? The environment could change its behaviour during training during `learn` call, and this would achieve the same result. It requires bit more tinkering (you need to hide your dynamic env logic to the environment code), but should be doable.

Thanks a lot for your reply and I will use the template next time. I can't use a function like model.learn(total_timesteps=10000) due to the following reasons:
1. RL needs information from another model to determine the reward, and another model needs to know the time step to generate this information.
2. The environment is non-stationary, which means the environment is dynamically changing and the same policy at timestamps 1-100 may not be suitable at timestamps 100-200. In this case, offline training is not enough and RL needs to be trained online to adapt to the non-stationary environment. I found in SB3 there is some information about continuous learning, but not sure it's the same case I faced and it's only has a little information. If you have any other information about it or the non-stationary environment, please let me know.

I am curious what do you mean by " hide your dynamic env logic to the environment code", could you explain more about it?

**Comment by YimengZhang94** [comment]
> there is a typo: "continuous learning" should be changed to 
"continual" learning. It can be found at the following link: https://stable-baselines.readthedocs.io/en/master/guide/examples.html#continual-learning, which is in SB, not SB3. Can SB3 train the trained model again? I mean after using the learning function, can I use the learning function again to continue the training based on the learned policy?

**Comment by Miffyli** [comment]
Ah, gotcha. Indeed SB3 does not have a pure support for this, and unfortunately I am not aware of libraries that have such support. You could try to ad-hoc implement this by:

- Using `learn` function
- Inside environment you load up the other model that determines the reward per step

If I understood right, this should achieve what you wanted but it is very ad hoc. Apart from this I do not have suggestions to give.

Re "continuous learning": yes, SB3 also supports the "continual" learning of continuing the learning process. But like noted, this should not be used with a small `total_timesteps` because of the overhead of calling `learn` (learning becomes slow).

You may close this issue if you do not bugs to report or enhancements to propose. Sadly we do not have much time to allocate for custom tech support for using SB3 ˆˆ'

**Comment by YimengZhang94** [comment]
> 

Thanks a lot for your reply. One more question before closing it: During the training, in the environment, how can I know what step RL is at? It seems there is no parameter in env about the time step.

**Comment by YimengZhang94** [comment]
> Ah, gotcha. Indeed SB3 does not have a pure support for this, and unfortunately I am not aware of libraries that have such support. You could try to ad-hoc implement this by:
> 
> * Using `learn` function
> * Inside environment you load up the other model that determines the reward per step
> 
> If I understood right, this should achieve what you wanted but it is very ad hoc. Apart from this I do not have suggestions to give.
> 
> Re "continuous learning": yes, SB3 also supports the "continual" learning of continuing the learning process. But like noted, this should not be used with a small `total_timesteps` because of the overhead of calling `learn` (learning becomes slow).
> 
> You may close this issue if you do not bugs to report or enhancements to propose. Sadly we do not have much time to allocate for custom tech support for using SB3 ˆˆ'

Thanks a lot for your reply. One more question before closing it: During the training, in the environment, how can I know what step RL is at? It seems there is no parameter in env about the time step.

**Comment by YimengZhang94** [comment]
> after using the learning function, can I use the learning function again to continue the training based on the learned policy?

And after using the learning function, can I use the learning function again to continue the training based on the learned policy? Thanks in advance :)

**Comment by YimengZhang94** [comment]
> Ah, gotcha. Indeed SB3 does not have a pure support for this, and unfortunately I am not aware of libraries that have such support. You could try to ad-hoc implement this by:
> 
> * Using `learn` function
> * Inside environment you load up the other model that determines the reward per step
> 
> If I understood right, this should achieve what you wanted but it is very ad hoc. Apart from this I do not have suggestions to give.
> 
> Re "continuous learning": yes, SB3 also supports the "continual" learning of continuing the learning process. But like noted, this should not be used with a small `total_timesteps` because of the overhead of calling `learn` (learning becomes slow).
> 
> You may close this issue if you do not bugs to report or enhancements to propose. Sadly we do not have much time to allocate for custom tech support for using SB3 ˆˆ'

And after using the learning function, can I use the learning function again to continue the training based on the learned policy? Thanks in advance :)

**Comment by Miffyli** [comment]
> During the training, in the environment, how can I know what step RL is at? It seems there is no parameter in env about the time step.

I recommend the manual way: store and increment the number of steps taken in episode in the environment :)

> And after using the learning function, can I use the learning function again to continue the training based on the learned policy? Thanks in advance :)

Yes! You can call `learn`, let it train for some time, and then call `learn` again later and it will continue from the same spot.

**Comment by YimengZhang94** [comment]
> > During the training, in the environment, how can I know what step RL is at? It seems there is no parameter in env about the time step.
> 
> I recommend the manual way: store and increment the number of steps taken in episode in the environment :)
> 
> > And after using the learning function, can I use the learning function again to continue the training based on the learned policy? Thanks in advance :)
> 
> Yes! You can call `learn`, let it train for some time, and then call `learn` again later and it will continue from the same spot.

I tried the manual way you suggested and it works! Thanks a lot and you saved me :)
For the second question, I compared the results obtained in different ways:
1. model.learn(total_timesteps=100000)
2.     for time_stamp in range(10000):
            model.learn(total_timesteps=10)
But the average rewards of these two ways obtained by evaluate_policy() are quite different: way 1 is much better than way 2. I think way 2 should have the same performance (if we don't consider the training time), as you said that we can call learn again. Do I call it in a wrong way? What's the correct way to call learn function again? Thanks again for your time on answering my questions.

**Comment by Miffyli** [comment]
You are doing it right :). And hmm, from what little recap it should not matter on the training results itself but the initialization phase depends on the algorithm. Maybe it was randomness from the training process? 

In any case, I recommend going with the 1) setup as it is the intended and most tested path :). I am closing this issue as resolved. Best of luck with your experiments!
