### ISSUE TITLE
Getting different results for evalcallback vs evaluate_policy

### ISSUE THREAD

**Issue by terencenwz** [DLR-RM/stable-baselines3#793]
Hi I am getting different results when evaluating through EvalCallback vs evaluate_policy. I do understand there are variance between runs, however I am getting very different results, I wonder if there is something amiss? 

```
    target_cb = EvalCallback(target_eval_env, eval_freq=1e6, n_eval_episodes=1000) 
    save_cb = CheckpointCallback(save_freq=1e6,  save_path='./policy/', name_prefix=source_env_name)
    real_policy.learn(total_timesteps=1e6, callback=[target_cb, save_cb ])


    # self eval
     real_policy.load('./policy/real_%s_%d_steps' % (source_env_name, 100000))
     target_eval_env.reset()
     mean_reward, std_reward = evaluate_policy(real_policy, target_eval_env, n_eval_episodes=1000,deterministic=True)
     print('Done: %.4f +/- %.3f' % (mean_reward, std_reward))
```

**Comment by araffin** [comment]
`real_policy.load('./policy/real_%s_%d_steps' % (source_env_name, 100000))`

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/683#issuecomment-983568484, we added a warning in the doc since then... (https://github.com/DLR-RM/stable-baselines3/pull/696)

**Comment by terencenwz** [comment]
> `real_policy.load('./policy/real_%s_%d_steps' % (source_env_name, 100000))`
> 
> Duplicate of [#683 (comment)](https://github.com/DLR-RM/stable-baselines3/issues/683#issuecomment-983568484), we added a warning in the doc since then... (#696)

Results are matched now, thanks!
