### ISSUE TITLE
Different evaluation results when loading model

### ISSUE THREAD

**Issue by atapley** [DLR-RM/stable-baselines3#795]
### 🤖 Custom Gym Environment

**Please check your environment first using**:

Passes

### Describe the bug

I train my model and after training I evaluate the model using

`evaluate_policy(model, eval_env, n_eval_episodes=1, deterministic=True)`

When doing so, I will get one value (say 0.5). If I then load the same saved model in the same method and evaluate that loaded model, with the same call (except using loaded_model instead of model) I will also get 0.5 as expected. However, if after training (outside of my main training method), I want to load and evaluate the same model, I am getting a completely different reward (say -0.2).

So basically, if I train a model and evaluate it, I get value A. If in the same training method I load the same model and evaluate it I get Value A. But if in another method I load the same model and evaluate it I get Value B.

### Code example

```python
import gym
import numpy as np

from stable_baselines3 import A2C
from stable_baselines3.common.env_checker import check_env


class CustomEnv(gym.Env):

  def __init__(self):
    super(CustomEnv, self).__init__()
    self.observation_space = gym.spaces.Box(low=0, high=1, shape=(1,64,64))
    self.action_space = self.action_space = gym.spaces.MultiDiscrete(4096)

  def reset(self):
    self.state = self.observation_space.high
    return self.state

  def step(self, action):
    obs = self.state
    reward = np.flatten(observation_space) - abs(action)
    done = True
    info = {}
    return obs, reward, done, info

def train_loop():
  env = CustomEnv()
  eval_env = CustomEnv()
  check_env(env)
  
  model = A2C("MlpPolicy", env, verbose=1).learn(1000)
  model.save('test')
  
  print('Evaluating trained model...')
  mean_reward, std_reward = evaluate_policy(model, eval_env, n_eval_episodes=1, deterministic=True)
  print(f"mean_reward={mean_reward:.4f} +/- {std_reward}")
  
  loaded_model = A2C.load('test')
  print('Loading and evaluating loaded model with current sim and eval_env...')
  mean_reward, std_reward = evaluate_policy(model, eval_env, n_eval_episodes=1, deterministic=True)
  print(f"mean_reward={mean_reward:.4f} +/- {std_reward}")

def eval_loop():
   loaded_model = A2C.load('test')
  print('Loading and evaluating loaded model with current sim and eval_env...')
  mean_reward, std_reward = evaluate_policy(model, eval_env, n_eval_episodes=1, deterministic=True)
  print(f"mean_reward={mean_reward:.4f} +/- {std_reward}") 

if __name__ == '__main__'::
  train_loop()
  eval_loop()
```

```bash
python3 main.py

```

### System Info
== CURRENT SYSTEM INFO ==
OS: Linux-5.4.0-80-generic-x86_64-with-glibc2.27 #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021
Python: 3.9.7
Stable-Baselines3: 1.3.0
PyTorch: 1.9.0+cu102
GPU Enabled: False
Numpy: 1.20.3
Gym: 0.21.0

### Additional context
The custom env is a little different than the actual one, but shouldn't affect it much given the issue is with saving/loading. I'm not sure why I'm getting the different results across just calling the load in different methods when everything should be the same.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have checked my env using the env checker (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,
why do you evaluate it with only one episode for evaluation?
do you use normalization? If so, makes sure you load the normalization at test time too (cf. doc).
And I would recommend using the RL Zoo in any case to make sure the training and testing env are created the same way.

**Comment by atapley** [comment]
Hi @araffin - thanks for the quick response! I'm only using one episode for evaluation because my state is static (nothing changes between episodes, I'm trying to run a bare-bones sanity test) so adding more episodes would not make a difference. There is no normalization happening. The loading script is copied and pasted into both methods, so everything should be created in exactly the same way - the only difference between the two is that one is in the original training method while the other is in a separate method. I will look into loading a model from the RL Zoo to double-check though. I'll try to save off the states in each method as well to check that they're the same (I checked in the same method but haven't tried saving them off and checking between the two methods).

**Comment by araffin** [comment]
If you want to double check that saving/loading works, you can check https://youtu.be/Ikngt0_DXJg?t=8760 (the timing correspond to saving/loading exercise from https://github.com/araffin/rl-handson-rlvs21#stable-baselines3-hands-on-rl-session) 

btw in your eval loop, you are passing `model` instead of `loaded_model` to the evaluate helper.

**Comment by atapley** [comment]
Looks like I have fixed it by adding `del model` to the initial method? I wasn't deleting the original model after training, and maybe that was somehow affecting the load in another method? Odd, but seems to be fixing the original issue
