### ISSUE TITLE
[Feature Request] SB3 compatible version of Gym's FrameStack wrapper

### ISSUE THREAD

**Issue by ScheiklP** [DLR-RM/stable-baselines3#799]
### 🚀 Feature

A version of Gym's `FrameStack` wrapper that returns the stacked observations as `(channel*n_stack, height, width)`.

### Motivation

The `VecFrameStack` in SB3 returns stacked observations as `(channel*n_stack, height, width)`, while the non-vectorized version in 
Gym returns the observations as `(n_stack, height, width, channel)`. Using the non-vectorized version with e.g. the NatureCnn feature extractor is not possible (fails `assert` in https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/torch_layers.py#L67).

### Pitch
Either
- add a non-vectorized `FrameStack` wrapper (as has been done with `Monitor`), or
- add a compatibility layer to Gym's `FrameStack` that assembles the the observations correctly.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Reasonable request, but in what situation would you want to apply `FrameStack` as an individual wrapper per env? On a quick thought this is useful if you want to add some wrappers after `FrameStack` to do some mods, but these could also be done in a vectorized fashion. 

SB3 is built solely around "vectorized" envs as you can always turn single env into a vectorized env of size one, which simplifies the code. If the wrapper is not used in/for SB3 specifically, there is little reason to add it here tbh.

**Comment by ScheiklP** [comment]
For example when the `train_freq` of `SAC` is 1, it would not necessarily make sense to have a vec_env, but I see your point with one env in a `DummyVecEnv`. 

I originally came across this because of the automatically added `VecTransposeImage`.
I stacked frames, then normalized, and then came the transpose image wrapper which caused the rollout_buffer to error, because it retrieves the unnormalized obs, which is not passed through the `VecTransposeImag` -> cannot match shapes `(1, 84, 84, 12)` and `(1, 12, 84, 84)`.

**Comment by araffin** [comment]
> I stacked frames, then normalized, and then came the transpose image wrapper

Normalization of images is done automatically by SB3 (cf. doc).

> rollout_buffer to error, because it retrieves the unnormalized obs, which is not passed through the 

yes, this is related to https://github.com/DLR-RM/stable-baselines3/issues/693

**Comment by ScheiklP** [comment]
Yes, I was doing exactly what is described in https://github.com/DLR-RM/stable-baselines3/issues/693 :D 
I just want to normalize the rewards.

**Comment by araffin** [comment]
>  I just want to normalize the rewards.

You can skip obs normalization in that case by passing `norm_obs=False` (you may need SB3 master version), or as suggested in #693 invert the wrappers (that would be equivalent to doing frame stack on each single env and then normalizing)

**Comment by jkterry1** [comment]
Could you also just create a PR adding a flag to Gym's framestack wrapper?

**Comment by ScheiklP** [comment]
Sure! I will give it a try in a few days. :)

**Comment by araffin** [comment]
closing as the issue has both a fix and is moved to gym.

**Comment by xspkwy** [comment]
Now I have a question. 
The 1st way is I use the gym `FrameStack` wrapper first, and then wrap it with `DummyVecEnv` or `SubprocVecEnv`, to make a VecEnv. The 2nd way is I build a VecEnv with `DummyVecEnv` or `SubprocVecEnv` first, and then wrap it with `VecFrameStack` wrapper. 
Would there be something different for training and evaluation?
