### ISSUE TITLE
[Feature Request] Add local time or unix epoch to verbose printouts while in debugging mode 

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/stable-baselines3#801]
### 🚀 Feature

I've been trying to debug stalled jobs, something that me and my group spend a _ton_ of time on for whatever reason, and I suspect this is generally a common phenomenon to debug. Including physical time in the `time/` part of the print out would be very nice for this. The easiest way to do this is to use `time.time()`, which returns the unix epoch (https://en.wikipedia.org/wiki/Unix_time), which would be perfectly adequate. This is also probably ultimately the best way, because any other representation will involve time zone lookups or system time, which can very easily result in misleading information.

### Alternatives

Suffer. This is also a super tiny change.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
I generally agree with the idea, however I am not 100% sure if `time.time()` would be the best for this: you would have to check the UNIX time somewhere else to know how long ago was the latest update. Granted, I agree that if you convert the time into human-readable format with a timezone, it can become more confusing and you still would have do bit of gymnastics to know how long ago was the latest log.

**Comment by araffin** [comment]
Hello,

> Alternatives

why not using a simple script like https://serverfault.com/questions/732338/attach-timestamp-to-each-line-of-stdout#732364 for your specific problem?

The truth is that such change is not that simple in sb3, you would need to either patch print or add an argument to all prints, we tried in the past to use a logger (#128 ) but it didn't fit our codebase.

**Comment by araffin** [comment]
Closing as the proposed alternative should work without much effort.
