### ISSUE TITLE
[Bug] Unchecked None value in random seeding of SubprocVecEnv

### ISSUE THREAD

**Issue by ScheiklP** [DLR-RM/stable-baselines3#807]
### 🐛 Bug
`seed()` has optional `seed` kwarg, but does not check for `None` -> trying to increment with `seed + idx` crashes, because `+` is not defined for `None` and `int`.
https://github.com/ScheiklP/stable-baselines3/blob/stacking_scalar_boxes/stable_baselines3/common/vec_env/subproc_vec_env.py#L127

```python
  def seed(self, seed: Optional[int] = None) -> List[Union[None, int]]:
      for idx, remote in enumerate(self.remotes):
          remote.send(("seed", seed + idx))
      return [remote.recv() for remote in self.remotes]
```

### Expected behavior

If kwarg is not set, sample a first random seed through `np.random.randint(0, 2**32 - 1)`.

### To Reproduce
```python
import gym
from stable_baselines3.common.vec_env import SubprocVecEnv

if __name__ == '__main__':
    env_id = "CartPole-v1"
    num_cpu = 4  # Number of processes to use
    # Create the vectorized environment
    env = SubprocVecEnv([gym.make_env(env_id) for i in range(num_cpu)])
    env.seed()
```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Miffyli** [comment]
Good catch! A PR to add the suggestion you proposed would be warmly welcomed :).
