### ISSUE TITLE
Minigrid --" Kernel size can't be greater than actual input size" for DQN

### ISSUE THREAD

**Issue by raymond2338** [DLR-RM/stable-baselines3#809]
Getting Error: RuntimeError: Calculated padded input size per channel: (3 x 3). Kernel size: (4 x 4). Kernel size can't be greater than actual input size

`import gym
import gym_minigrid
from stable_baselines3.common.env_checker import check_env
from stable_baselines3 import PPO, A2C
from stable_baselines3 import DQN

env = gym.make('MiniGrid-Empty-16x16-v0')
check_env(env, warn=True)
env = make_vec_env(lambda: env, n_envs=1)
model = DQN("MultiInputPolicy", env)
`

Slight modifications from the original minigrid.py: changed the observation to only the image. tldr; obs = dict('image': array(16,16,3))

I am not quite sure how I should fix this if it's the layer of NN within the baseline model? Thanks

**Comment by Miffyli** [comment]
Next time, please fill in the issue template :). 

Problem is that with conv layers the output size, which gets smaller on every conv layer, becomes negative. You need to either increase the input shape size or use a different feature extractor (see doc on making custom policies). Same applies to your SB2 issue (please close that one, we can answer questions here).

**Comment by raymond2338** [comment]
Sorry about the template. I will make sure in the future.

As for increasing the input shape size, how could that be done (do I increase the observation space shape size)? 

For feature extractor, I found https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html and I tried using

`import gym
import torch as th
from torch import nn

from stable_baselines3.common.torch_layers import BaseFeaturesExtractor

class CustomCombinedExtractor(BaseFeaturesExtractor):
    def __init__(self, observation_space: gym.spaces.Dict):
        # We do not know features-dim here before going over all the items,
        # so put something dummy for now. PyTorch requires calling
        # nn.Module.__init__ before adding modules
        super(CustomCombinedExtractor, self).__init__(observation_space, features_dim=1)

        extractors = {}

        total_concat_size = 0
        # We need to know size of the output of this extractor,
        # so go over all the spaces and compute output feature sizes
        for key, subspace in observation_space.spaces.items():
            if key == "image":
                # We will just downsample one channel of the image by 4x4 and flatten.
                # Assume the image is single-channel (subspace.shape[0] == 0)
                extractors[key] = nn.Sequential(nn.MaxPool2d(4), nn.Flatten())
                total_concat_size += subspace.shape[1] // 4 * subspace.shape[2] // 4
            elif key == "vector":
                # Run through a simple MLP
                extractors[key] = nn.Linear(subspace.shape[0], 16)
                total_concat_size += 16

        self.extractors = nn.ModuleDict(extractors)

        # Update the features dim manually
        self._features_dim = total_concat_size

    def forward(self, observations) -> th.Tensor:
        encoded_tensor_list = []

        # self.extractors contain nn.Modules that do all the processing.
        for key, extractor in self.extractors.items():
            encoded_tensor_list.append(extractor(observations[key]))
        # Return a (B, self._features_dim) PyTorch tensor, where B is batch dimension.
        return th.cat(encoded_tensor_list, dim=1)

policy_kwargs = dict(
    features_extractor_class=CustomCombinedExtractor,
)`

**Comment by Miffyli** [comment]
Increasing shape size might not be possible (depends on your environment, I am not familiar with this one). 

For custom extractor, follow [this example](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#custom-feature-extractor). I think the CNN used in this code will work for you out of the box. If not, you need to decrease the size conv layer filters and/or the stride etc. To understand this better, I recommend reading on the inner workings of CNNs :)

If that works out, you may close this issue. Note that we are not able to give prolonged tech support for per-case situations.

**Comment by dyllanwli** [comment]
@raymond2338 I got the same error when was trying to integrate minigrid with SB3. Did you find any better solution?

**Comment by dyllanwli** [comment]
Solved by using env_wrapper.
