### ISSUE TITLE
[Question] How to let RL learns from multiple state-action pairs at the same time?

### ISSUE THREAD

**Issue by YimengZhang94** [DLR-RM/stable-baselines3#811]
### Question

The model.learn function in SB3 is to generate one action according to the state and then obtain the reward, then the model is trained. However, if I have multiple state-action-reward pairs generated by an (old) model, can I feed these pairs to RL and let it learn from them and get a new trained model? It seems I can't do it using the current model.learn function because the current workflow of model.learn is: (old model) state->action->reward (get a new model) state->action->reward (get a new model)... But what I want is: (old model) multiple state-action-reward pairs (get a new model). I can't use the current model.learn function because after it learned from one state-action pair, the model will be updated, and the generated action may be different from the action generated by the old model. Anyone can help me? Thanks in advance.

### Checklist

- [ ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/modules/dqn.html?highlight=model.learn(#stable_baselines3.dqn.DQN.learn) (**required**)

**Comment by Miffyli** [comment]
Are you referring to `learn` function or `train` function? Because `learn` does much more than just train on a single "state-action-reward" tuple: it does the data collection ("rollouts"), stores the data, computes returns and updates the policy. This loop is repeated until callbacks trigger or the `total_timesteps` is reached.

The policy updates are done on multiple state-action-reward tuples. In on-policy algorithms there are `n_steps` experiences taken from each environment, so total of `n_steps * n_envs` tuples are used for updates . In off-policy algorithms, replay buffer is sampled for `batch_size` number of tuples and policy is updated based on those.

If you are looking for imitation learning (learning from a predetermined set of samples), you should look at other libraries such as [imitation](https://github.com/HumanCompatibleAI/imitation).

**Comment by YimengZhang94** [comment]
Thanks a lot for your reply. I am referring to learn function and not looking for imitation learning. Because I can only get the reward after a period of time when the action is obtained, and other actions needed to be generated by the model, I use the current model to generate actions for multiple states, and then store them. When rewards of these actions are obtained, I train the old model using these action-state-reward pairs together. In this case, how can I do it?

**Comment by YimengZhang94** [comment]
> Are you referring to `learn` function or `train` function? Because `learn` does much more than just train on a single "state-action-reward" tuple: it does the data collection ("rollouts"), stores the data, computes returns and updates the policy. This loop is repeated until callbacks trigger or the `total_timesteps` is reached.
> 
> The policy updates are done on multiple state-action-reward tuples. In on-policy algorithms there are `n_steps` experiences taken from each environment, so total of `n_steps * n_envs` tuples are used for updates . In off-policy algorithms, replay buffer is sampled for `batch_size` number of tuples and policy is updated based on those.
> 
> If you are looking for imitation learning (learning from a predetermined set of samples), you should look at other libraries such as [imitation](https://github.com/HumanCompatibleAI/imitation).

Thanks a lot for your reply. I am referring to learn function and not looking for imitation learning. Because I can only get the reward after a period of time when the action is obtained, and other actions needed to be generated by the model, I use the current model to generate actions for multiple states, and then store them. When rewards of these actions are obtained, I train the old model using these action-state-reward pairs together. In this case, how can I do it?

**Comment by YimengZhang94** [comment]
> 



> > Are you referring to `learn` function or `train` function? Because `learn` does much more than just train on a single "state-action-reward" tuple: it does the data collection ("rollouts"), stores the data, computes returns and updates the policy. This loop is repeated until callbacks trigger or the `total_timesteps` is reached.
> > The policy updates are done on multiple state-action-reward tuples. In on-policy algorithms there are `n_steps` experiences taken from each environment, so total of `n_steps * n_envs` tuples are used for updates . In off-policy algorithms, replay buffer is sampled for `batch_size` number of tuples and policy is updated based on those.
> > If you are looking for imitation learning (learning from a predetermined set of samples), you should look at other libraries such as [imitation](https://github.com/HumanCompatibleAI/imitation).
> 
> Thanks a lot for your reply. I am referring to learn function and not looking for imitation learning. Because I can only get the reward after a period of time when the action is obtained, and other actions needed to be generated by the model, I use the current model to generate actions for multiple states, and then store them. When rewards of these actions are obtained, I train the old model using these action-state-reward pairs together. In this case, how can I do it?

More specifically, can I define the action in each step during learning by myself rather than let the step() function generates it?

**Comment by YimengZhang94** [comment]
> > Are you referring to `learn` function or `train` function? Because `learn` does much more than just train on a single "state-action-reward" tuple: it does the data collection ("rollouts"), stores the data, computes returns and updates the policy. This loop is repeated until callbacks trigger or the `total_timesteps` is reached.
> > The policy updates are done on multiple state-action-reward tuples. In on-policy algorithms there are `n_steps` experiences taken from each environment, so total of `n_steps * n_envs` tuples are used for updates . In off-policy algorithms, replay buffer is sampled for `batch_size` number of tuples and policy is updated based on those.
> > If you are looking for imitation learning (learning from a predetermined set of samples), you should look at other libraries such as [imitation](https://github.com/HumanCompatibleAI/imitation).
> 
> Thanks a lot for your reply. I am referring to learn function and not looking for imitation learning. Because I can only get the reward after a period of time when the action is obtained, and other actions needed to be generated by the model, I use the current model to generate actions for multiple states, and then store them. When rewards of these actions are obtained, I train the old model using these action-state-reward pairs together. In this case, how can I do it?

During training, how does the step() function obtain the action as the input? Can I define the action in each step by myself? If I can, then I can train the model using action-state-reward pairs obtained previously. Looking forward to your reply.

**Comment by Miffyli** [comment]
Ah, that kind of functionality kind of goes against the underlying MDP-ness of environments (it assumes you obtain the reward immediately after taking the action). However, the whole idea of RL is to be able to assign credit to correct actions even if the reward is delayed, so you might want to rethink your environment (e.g. you give zero reward when action is taken and later give a bulk reward. It might still work well :) )

If you insist on delay-assigning rewards like you described, you would have to modify the code quite a bit. If you use A2C or PPO, [this loop](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/on_policy_algorithm.py#L161-L209) gets the observations, gets actions and steps the environment. You would have to add your own logic to modify the rollout buffer after you get your rewards. [This](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/off_policy_algorithm.py#L578-L624) is the same loop for off-policy algos (DQN, SAC, TD3).

Note that we do not offer tech support for custom situations like this, so I would like to ask you close this issue if there are no bugs to report or enhancement suggestions ^^

**Comment by YimengZhang94** [comment]
> you give zero reward when action is taken and later give a bulk reward.

Thanks a lot for your reply. I have one more question about your suggestion: you give zero reward when action is taken and later give a bulk reward. At initial steps, RL makes actions (let's call these actions A) and receives zero reward, later when the bulk reward is received, how does RL know the bulk rewards is not only depending on current action but also actions A? Moreover, if there are some actions before actions A, and these actions are not relevant to the bulk reward, how can RL recognize it? Maybe there are some methods to achieve it but I don't know. Thanks again for your time and I will close this issue after receiving your answers :)
