### ISSUE TITLE
[Question] Is the length of trajectory (episode) controlled by the done in step() function?

### ISSUE THREAD

**Issue by YimengZhang94** [DLR-RM/stable-baselines3#814]
### Question
In RL, a trajectory (or episode) is a sequence of states and actions in the world, see the following link for more explanations:
https://spinningup.openai.com/en/latest/spinningup/rl_intro.html
In SB3, is the length of the trajectory (episode) controlled by the done in step() function?
If I have an infinite horizon, then the done is always False during all total_timesteps in the model.learn() function, right? If I have a finite horizon, I just need to set the done = True when one trajectory (episode) ends and the model.learn() function will identify it automatically, right? Thanks in advance.

### Checklist

- [x] I have read the [documentation](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/on_policy_algorithm.py#L161-L209) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Yes, exactly! SB3 follows the definitions of Gym, where indeed `done=True` means end of an episode. Note that the rollouts (collecting samples) does not depend on episode lengths, unless you explicitly  set it so in some of the algorithms. 

Closing as resolved. Please refer to the docs for further information :)

**Comment by araffin** [comment]
Hello,

For infinite horizon, I recommend you taking a look at https://github.com/DLR-RM/stable-baselines3/issues/284 and https://github.com/DLR-RM/stable-baselines3/issues/633 .
One way to deal with that is having a timeout (setting done=True) but telling the agent to ignore that termination and treat the problem as infinite horizon by providing `info["TimeLimit.truncated"] = True` (done automatically by the `TimeLimit` wrapper).
