### ISSUE TITLE
SubprocVecEnv in_series

### ISSUE THREAD

**Issue by UntotaufUrlaub** [DLR-RM/stable-baselines3#815]
### Question

Hi,

as far as I see sb3.SubprocVecEnv doesn't have the in_series parameter which [baslines SubprocVecEnv](https://github.com/openai/baselines/blob/master/baselines/common/vec_env/subproc_vec_env.py) has.
Is there any way in sb3 to achieve this behavior? Or why should one not use it?

kind regards

**Comment by Miffyli** [comment]
`DummyVecEnv` is exactly this :). Other than that is functions just like SubProcVecEnv.

**Comment by Miffyli** [comment]
Ah, no, that is not supported in SB3. I think we had a discussion on this in either SB2 or SB3 in issues, but ultimately nobody made an implementation of this. If you seek high-performance libraries that support such things, try [sample-factory](https://github.com/alex-petrenko/sample-factory), for example (not as simple but high performance).

**Comment by UntotaufUrlaub** [comment]
Ah I see. What a pity. But thanks for the information and the hint :)

**Comment by araffin** [comment]
You may have a look at https://github.com/ingambe/RayEnvWrapper (I didn't test that one but looks interesting) and https://github.com/hill-a/stable-baselines/issues/390#issuecomment-1048842278
