### ISSUE TITLE
[Question] On-Policy Policy Initialization &  

### ISSUE THREAD

**Issue by mkmmcleod** [DLR-RM/stable-baselines3#816]
### Question

I have 2 questions.

1. Do on-policy algorithms have lower initialization values in final layer of just the policy network? I observed this empirically, but I don't see any arguments to pass to them (such as in PPO) and I can't find a reference to it in the documentation. Is SB3 automatically doing so? I have heard of this idea before for policy initialization, for example ( e.g: https://arxiv.org/pdf/2006.05990.pdf, bottom of pg. 5) argues this kind of initialization is beneficial. Just trying to understand if SB3 is doing so.

2. How is the empirical return for the rollout buffer calculated when the episode lengths are longer than the update frequency? I am running on a custom environment but the explained variance metric is quite often NaN. From reading the documentation/code, I understand this to occur when the variance of empirical returns is 0.  
I would think the empirical return would be calculated with some GAE lambda estimate and if the episode has not terminated within the buffer, it simply bootstraps off the last state value function for a return estimate? Is this correct? My reward function in the custom environment is dense and while deterministic, it is highly variable to the stochasticity in the agent actions. I don't see how calculating the empirical return this way would result in 0 variance return estimate. Are there any other ways to get NaN. Does it handle gracefully if gae \lambda = 1 when there has not been an episode termination? 

### Additional context

I am applying PPO to a custom environment. I am getting that explained variance = 0. Another factor is that when this trained agent is evaluated with the deterministic flag in model.evaluate or model.predict, the agent outputs the same mean action for all states (not good).  Just trying to figure out why that is. 

Thank you for this fantastic library

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
> Do on-policy algorithms have lower initialization values in final layer of just the policy network?

yes, the parameter is called `ortho_init` and is passed to the policy contructor:
https://github.com/DLR-RM/stable-baselines3/blob/52c29dc497fa2eb235d0476b067bed8ac488fe64/stable_baselines3/common/policies.py#L560-L572

> How is the empirical return for the rollout buffer calculated when the episode lengths

We use the `Monitor` wrapper for that (cf. doc on logger output), and we continue episode between two updates if the episode length is longer than the update frequency.

> if the episode has not terminated within the buffer, it simply bootstraps off the last state value function for a return estimate?

For the value target, we use bootstraping for truncated episodes.

>  I am running on a custom environment but the explained variance metric is quite often NaN.

as mentioned in the readme and issue template, we don't do take support (discord/reddit/stackoverflow is a better place for asking such question). With PPO, you should make sure that you are using `VecNormalize` wrapper (or `VecNormalize` with `norm_obs=False` if using images) as mentioned in our doc.
