### ISSUE TITLE
[Bug] VecNormalize fails on SAC/TD3

### ISSUE THREAD

**Issue by xy9485** [DLR-RM/stable-baselines3#819]
### 🐛 Bug

I find VecNormalize wrapper is unusable when training off-policy algos like SAC and TD3.  
I think the issue is located in `def _store_transition()`  in `off_policy_algorithm.py`:
```
...
        if self._vec_normalize_env is not None:
            new_obs_ = self._vec_normalize_env.get_original_obs()
            reward_ = self._vec_normalize_env.get_original_reward()
        else:
            # Avoid changing the original ones
            self._last_original_obs, new_obs_, reward_ = self._last_obs, new_obs, reward

        # Avoid modification by reference
        next_obs = deepcopy(new_obs_)
...
```
e.g. `get_original_obs()` returns the unnormalized obs whose shape is not transposed: `(1,96,96,3)`

I might not understand exactly what's the purpose of storing unnormalized obs and reward into the replay_buffer, when VecNormalize wrapper is used on purpose.

### To Reproduce
 ```
env = make_vec_env('CarRacing-v0', 1)
env = VecNormalize(env, norm_obs=False)   # same for norm_obs=True, eventhough image input should be scaled in defualt.
model = SAC('CnnPolicy', env, verbose=1)    # or TD3 
model.learn(total_timesteps=int(2e5))
```
And I get error below, same error can also be reproduced with the newest version of SB3 on master branch.
<ins>The error is gone when using PPO or A2C. </ins>
```
Traceback (most recent call last):

  File "/workspace/repos_dev/stable-baselines3/stable_baselines3/td3/td3.py", line 214, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/workspace/repos_dev/stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 366, in learn
    log_interval=log_interval,
  File "/workspace/repos_dev/stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 616, in collect_rollouts
    self._store_transition(replay_buffer, buffer_actions, new_obs, rewards, dones, infos)
  File "/workspace/repos_dev/stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 534, in _store_transition
    infos,
  File "/workspace/repos_dev/stable-baselines3/stable_baselines3/common/buffers.py", line 246, in add
    self.observations[self.pos] = np.array(obs).copy()
ValueError: could not broadcast input array from shape (1,96,96,3) into shape (1,3,96,96)
```

### Expected behavior

I expect the VecNormalize wrapper should work on all algotrithms in environment 'CarRacing', in document I don't see any constrain regarding the usage of VecNormalize wrapper.

### System Info
I'm using SB3 1.4.0 , gym 0.21.0 and python 3.7.11. 

### Checklist
I find a related issue but unfortunately it doesn't solve my issue.
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Miffyli** [comment]
Hmm normalization of image pixels individually might hinder the performance (or not, not tested :D), but it definitely is not something people do. For images, you should not use VecNormalize wrapper. Images (of type uint8) are automatically normalized to [0, 1] by dividing with 255.

Which part of the docs misled you to use VecNormalize with an image environment? The doc could be updated with a note/warning that one should only use VecNormalize with non-image envs :)

**Comment by araffin** [comment]
Hello,

> To Reproduce

If you use a `VecTransposeImage` wrapper before the `VecNormalize` env, this solves your issue:

```python
from stable_baselines3 import SAC
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import VecNormalize, VecTransposeImage

env = make_vec_env("CarRacing-v0", 1)
# Make it channel first to comply with PyTorch default
env = VecTransposeImage(env)
env = VecNormalize(env, norm_obs=False)
model = SAC("CnnPolicy", env, buffer_size=100, verbose=1)
model.learn(total_timesteps=int(2e5))

```

>  The error is gone when using PPO or A2C. 

yes, the issue is similar to #693 .

**Comment by xy9485** [comment]
Thank you for the quick feedback

> Hmm normalization of image pixels individually might hinder the performance (or not, not tested :D), but it definitely is not something people do. For images, you should not use VecNormalize wrapper. Images (of type uint8) are automatically normalized to [0, 1] by dividing with 255.
> 
No mormalization on pixel image does make sense, therefore I set 'norm_obs=False' and I just want to use this wrapper to normalize the reward. But I still get this error.

> Which part of the docs misled you to use VecNormalize with an image environment? The doc could be updated with a note/warning that one should only use VecNormalize with non-image envs :)
> 
I think this part(below) of doc in _**Reinforcement Learning Tips and Tricks**_ kinda misled me to use VecNormalize with an image environment, without warnings.

>When applying RL to a custom problem, you should always normalize the input to the agent (e.g. using VecNormalize for PPO/A2C) and look at common preprocessing done on other environments (e.g. for [Atari](https://danieltakeshi.github.io/2016/11/25/frame-skipping-and-preprocessing-for-deep-q-networks-on-atari-2600-games/), frame-stack, …). Please refer to Tips and Tricks when creating a custom environment paragraph below for more advice related to custom environments.
>

***

> > I might not understand exactly what's the purpose of storing unnormalized obs and reward into the replay_buffer, when VecNormalize wrapper is used on purpose.
> 
> Answering to sate your curiosity. Replay buffer stores the original samples so that when VecNormalize statistics change (which they do, constantly), you can re-normalize the replay buffer samples and use them with the new normalization parameters.

Thanks for the clearance!

**Comment by xy9485** [comment]
> Hello,
> 
> > To Reproduce
> 
> If you use a `VecTransposeImage` wrapper before the `VecNormalize` env, this solves your issue:
> 
> ```python
> from stable_baselines3 import SAC
> from stable_baselines3.common.env_util import make_vec_env
> from stable_baselines3.common.vec_env import VecNormalize, VecTransposeImage
> 
> env = make_vec_env("CarRacing-v0", 1)
> # Make it channel first to comply with PyTorch default
> env = VecTransposeImage(env)
> # Do not normalize image (done in SB3 automatically)
> env = VecNormalize(env, norm_obs=False)
> model = SAC("CnnPolicy", env, buffer_size=100, verbose=1)
> model.learn(total_timesteps=int(2e5))
> ```
> 
> > The error is gone when using PPO or A2C.
> 
> yes, the issue is similar to #693 .

This does walk around the issue, thanks! 
One question pending: is normalization of reward using VecNormalize in image-environments allowed and recommended?

**Comment by araffin** [comment]
>  One question pending: is normalization of reward using VecNormalize in image-environments allowed and recommended?

allowed yes, because reward normalization is independent of the observation.
Recommended, depends on which algorithm you are using, PPO/A2C (on policy) yes, for off-policy (SAC/TD3), first try without.

If you are looking for tuned hyperparameters for CarRacing, you can take a look at https://github.com/DLR-RM/rl-baselines3-zoo/blob/feat/recurrent-ppo/hyperparams/tqc.yml#L259, it uses the autoencoder from https://github.com/araffin/aae-train-donkeycar/pull/1
