### ISSUE TITLE
[Discussion] More issue templates

### ISSUE THREAD

**Issue by PartiallyTyped** [DLR-RM/stable-baselines3#82]
It would be really useful to have more issue template that will provide better guidelines on how to ask/discuss different things and differentiate between questions, bugs, feature requests, or other forms of discussion.

**Comment by araffin** [comment]
Maybe we should reference first the different templates needed:

- [ ] custom env issue
- [ ] bug report
- [ ] feature request
- [ ] question

others?

**Comment by PartiallyTyped** [comment]
Perhaps a Discussion template? Ie something that separates feature request for the library and feature request for the project? IIRC there was some discussion some time ago about a discord server (or a gitter chat?) such feature requests could use their own template.

**Comment by Miffyli** [comment]
> Perhaps a Discussion template?

Hmmm but those discussions are either enhancements (like the Discord chat), possible bugs or odd APIs/behaviour. I think coming up with a template for just "Discussion" is difficult, while it can be separated under proposed categories. "Feature request" could be "Feature request / enhancement", including both new features and improvement of existing features.

**Comment by araffin** [comment]
>Perhaps a Discussion template? Ie something that separates feature request for the library and feature request for the project? IIRC there was some discussion some time ago about a discord server (or a gitter chat?) such feature requests could use their own template.

I think we should wait a little bit and there will be [Github discussions](https://github.com/vercel/next.js/discussions) for that.

After centralizing CI with Github actions and "trello-like" board with projects, it seems a good feature for repos that is coming soon.

**Comment by PartiallyTyped** [comment]
It will probably reduce discussions in reddit ^^’

**Comment by PartiallyTyped** [comment]
Sounds great to me! Perhaps another issue label, like 'pr ready' to classify issues that are discussed enough to be ready for implementation? (stole the idea from flax)

**Comment by araffin** [comment]
>like 'pr ready' to classify issues that are discussed enough to be ready for implementation? 

Not sure about that one. Sometimes, it is clear that the feature can be implemented but most of the time, a draft PR is also part of the discussion...

**Comment by PartiallyTyped** [comment]
Yes, of course, the train of thought was to point issues where the general solution was discussed/outlined and someone could contribute by making a PR/draft.
