### ISSUE TITLE
Doc improvemrnt about: Directly Accessing The Summary Writer

### ISSUE THREAD

**Issue by xy9485** [DLR-RM/stable-baselines3#820]
### 📚 Documentation
Current version:
```
class SummaryWriterCallback(BaseCallback):

    def _on_training_start(self):
        self._log_freq = 1000  # log every 1000 calls

        output_formats = self.logger.Logger.CURRENT.output_formats
        # Save reference to tensorboard formatter object
        # note: the failure case (not formatter found) is not handled here, should be done with try/except.
        self.tb_formatter = next(formatter for formatter in output_formats if isinstance(formatter, TensorBoardOutputFormat))

    def _on_step(self) -> bool:
        if self.n_calls % self._log_freq == 0:
            self.tb_formatter.writer.add_text("direct_access", "this is a value", self.num_timesteps)
            self.tb_formatter.writer.flush()
```

The way to get output_formats should be just like:
`output_formats = self.logger.output_formats`

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

you mean something similar to what is done in https://github.com/DLR-RM/rl-baselines3-zoo/pull/216/files ?

`output_formats = self.logger.output_formats` should work...

**Comment by xy9485** [comment]
> Hello,
> 
> you mean something similar to what is done in https://github.com/DLR-RM/rl-baselines3-zoo/pull/216/files ?
> 
> `output_formats = self.logger.output_formats` should work...


yes, the way used to get 'output_formats' in the provided pull is same with mine.  What is written about 'SummaryWriterCallback' in the Documentation might need an update.

**Comment by araffin** [comment]
then we would be happy to receive a pull request that solves this issue ;)

**Comment by xy9485** [comment]
I have created a PR.
