### ISSUE TITLE
[Question] How to set delayed reward in SB3?

### ISSUE THREAD

**Issue by YimengZhang94** [DLR-RM/stable-baselines3#821]
### Question

It seems that SB3 assumes the reward is obtained immediately after the action is taken. However, the reward may only be obtained later in many real problems. For example, assume there are four time steps in an episode and the states between steps are independent:
step 1: state 1, the action 1 is generated by RL, but no reward is received;
step 2: state 2, the action 2 is generated by RL, but no reward is received;
step 3: the reward for action 1 is received.
step 4: the reward for action 2 is received.
We can't skip step 2 to wait for the reward in step 3. In this case, how to model it using SB3? We can assume the rewards at steps 1 and 2 are 0, but there is a problem at steps 3 and 4. In the env.step() function, every step needs a state and then action is generated, then reward is received. But at steps 3 and 4, only reward for actions 1 and 2 are received and there is no state and action. Is there any solution for this kind of delayed reward? Thanks in advance.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
@YimengZhang94 I assume you got your answer in the [RL Discord](https://discord.com/invite/xhfNqQv)? If so, please close this issue :)

**Comment by YimengZhang94** [comment]
yes I have got my answer, thanks.
