### ISSUE TITLE
[Question] Can I use a model trained with different state space / action space when testing?

### ISSUE THREAD

**Issue by Waterkin** [DLR-RM/stable-baselines3#825]
### Question

For example, when training PPO, I use an environment whose state space is 100-dimension and action space is 100-dimension, can I use the trained model to test in an environment whose state space is 10-dimension and action space is 10-dimension?

I have known that when dealing with different action space, we can refer to action masking -> https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/pull/25
But what about a different state space?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Hey. This is not supported as-is; the state/action spaces need to stay consistent over all training/eval runs. You _could_ experiment with creating a new agent on the 10/10 dimensional environment, and then manually loading the desired parameters from the older model using the `get/set_parameters` functions. However, I would not be surprised if this does not work at all (the agent does not work). I do not know of work that has explored your type of situation, but you might some hints by exploring in other places.

**Comment by Waterkin** [comment]
> Hey. This is not supported as-is; the state/action spaces need to stay consistent over all training/eval runs. You _could_ experiment with creating a new agent on the 10/10 dimensional environment, and then manually loading the desired parameters from the older model using the `get/set_parameters` functions. However, I would not be surprised if this does not work at all (the agent does not work). I do not know of work that has explored your type of situation, but you might some hints by exploring in other places.

Thank you for your reply, Miffyli.
