### ISSUE TITLE
[Question] DDPG + HER Multiprocessing for FetchPickAndPlace

### ISSUE THREAD

**Issue by EdvardsZ** [DLR-RM/stable-baselines3#826]
Hello,

I was reading documentation about HER and also about Multiprocessing.
However when i try to train it throws a error!
Is there any example anywhere with multiprocessing with replay_buffer??

```
num_cpu = 4
env = make_vec_env(env_name, n_envs=num_cpu, seed=0, vec_env_cls=SubprocVecEnv)
model = DDPG(
    'MultiInputPolicy',
    env,
    verbose = 1,
    tensorboard_log = log_path,
    replay_buffer_class = HerReplayBuffer,
    # Parameters for HER
    replay_buffer_kwargs=dict(
        n_sampled_goal = 4,
        goal_selection_strategy = GoalSelectionStrategy.FUTURE,
        online_sampling = True,
    ),
)
model.learn(total_timesteps = 1000000)
```
ValueError: could not broadcast input array from shape (6,4) into shape (4,)

**Comment by araffin** [comment]
> I was reading documentation about HER and also about Multiprocessing.

See documentation (https://stable-baselines3.readthedocs.io/en/master/guide/algos.html) and #704 
Multiprocessing is currently not supported for HER but a PR is opened.

**Comment by EdvardsZ** [comment]
Thank you for your fast reply

**Comment by EdvardsZ** [comment]
> > I was reading documentation about HER and also about Multiprocessing.
> 
> See documentation (https://stable-baselines3.readthedocs.io/en/master/guide/algos.html) and #704 Multiprocessing is currently not supported for HER but a PR is opened.

Hello i wanted to ask when could it be completed? How much work is needed there?

**Comment by araffin** [comment]
> Hello i wanted to ask when could it be completed?

You can already use it, see PR #704 (but consider it as experimental). There is no deadline, it will take as much time as needed so we are sure of the implementation.
