### ISSUE TITLE
[Question] Handling max steps / use of remove_time_limit_termination

### ISSUE THREAD

**Issue by Gregwar** [DLR-RM/stable-baselines3#829]
Some environment will require a limit in the number of steps you can do to enforce periodic reset that are not necessary terminations, as explained in this former issue: https://github.com/hill-a/stable-baselines/issues/863

Apparently, the problem of handling such termination was mentionned, through the `info['TimeLimit.truncated']` flag that serves this purpose. @araffin also mentions some code handling that, using the `remove_time_limit_termination` flag.

However, in `master`, this flag doesn't seem to have any effect in the code. Looks like original snippet vanished:
https://github.com/DLR-RM/stable-baselines3/compare/feat/remove-timelimit

Does anybody knows if this is intended or if it was a merge / update issue ?

**Comment by Miffyli** [comment]
Please fill in template next time :). The code for off-policy algorithms is [here](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/on_policy_algorithm.py#L194-L209). I can not recall why this was not done for off-policy algorithms (or done elsewhere). @araffin ?

**Comment by araffin** [comment]
Hello,
See https://github.com/DLR-RM/stable-baselines3/issues/284 , the timeout termination is handled in the replay buffer, and checked in our tests here: https://github.com/DLR-RM/stable-baselines3/blob/d228364ccffefef9632b4352ca6f7a7a6071cfa5/tests/test_gae.py#L136

The `remove_time_limit_termination` is actually dead code from the HER implementation, we would appreciate a PR that removes it ;)
