### ISSUE TITLE
[Question] Actions scaling

### ISSUE THREAD

**Issue by Gregwar** [DLR-RM/stable-baselines3#830]
As stated here https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
"normalize your action space and make it symmetric when continuous (cf potential issue below) A good practice is to rescale your actions to lie in [-1, 1]. This does not limit you as you can easily rescale the action inside the environment"

Does it mean that our actions should ideally lie in `Box(-1, 1)`?

More specifically, some networks have a tanh method on their last layers, limitting their output between -1 and 1. If I understand properly the code, the unscaled actions are being passed to the environment anyway, right ?

So, for instance, if using TD3, I will never get an action outside of `[-1, 1]` even with a bigger Box, is that correct ?

**Comment by Miffyli** [comment]
No, you can have bigger actions outside [-1, 1]. The action is not simply the output of a network: it is a process of parametrizing a probability distribution and sampling the action from there (which can be of any size), which is then squashed/clipped to the desired range.

**Comment by Gregwar** [comment]
Indeed, after reading the code I see that the actions are already pre-unscaled in `BasePolicy`'s `predict` method.

So why there is this remark in the documentation about rescaling actions to lie in [-1,1] ?

**Comment by Gregwar** [comment]
(Sorry if I am not clear; I am only focused on deterministric policies so far like TD3/DDPG)

**Comment by Miffyli** [comment]
Ah, gotcha. Continuous actions + off-policy algorithms escape my zone of in-depth knowledge. I will let @araffin answer this one :)

**Comment by araffin** [comment]
> So why there is this remark in the documentation about rescaling actions to lie in [-1,1] ?

See "Why should I normalize the action space?" in the RL tips page and this part of the video: https://youtu.be/Ikngt0_DXJg?t=740

It is true that for TD3/SAC, as we are handling rescaling (and squashing the action) it does not matter, but it is a general good practice to follow that may lead to hard to debug errors.

**Comment by Gregwar** [comment]
Ok thanks!
