### ISSUE TITLE
[Question] What does the rollout parameter "ep_rew_mean" measure?

### ISSUE THREAD

**Issue by PBerit** [DLR-RM/stable-baselines3#832]
Hi all,

I have some gerneall difficulties understanding what the rollout "ep_rew_mean" of an algorithm really measures in Stable-Baselines 3. I thought it quantifies the average reward for an episode for one iteration through the Gym evnvironment. But this can't be possible in my application. 

I used A2C for a custom gym environment and trained 4 consecutive versions of it by using the following code:
```
# Train the model
from stable_baselines3 import A2C
import os
import tensorflow as tf
from datetime import datetime

if trainNewModels == True:

    env = DSM_BT1_Env()
    models_dir = "models/A2C"
    logdir = "logs/RL_BT1"
    
    
    if not os.path.exists(models_dir):
        os.makedirs(models_dir)
        
    if not os.path.exists(logdir):
        os.makedirs(logdir)
        
    
    model = A2C('MlpPolicy', env, verbose=1, tensorboard_log=logdir)
    
    timesteps = 100000
    
    
    print("\n \n \n \n Training \n \n \n")
    
    
    #train and save the model
    numberOfEpisodes =  4
    for i in range(numberOfEpisodes):
        timeStarted = datetime.now().strftime("%d-%m-%Y--%H-%M-%S")
        model.learn(total_timesteps=timesteps, reset_num_timesteps=False, tb_log_name=f"A2C_Started_{timeStarted}_Episode_{i+1}_Timesteps_{timesteps}")
        model.save(f"{models_dir}/Started_{timeStarted}_Episode_{i+1}_Timesteps_{timesteps}")
```

Here you can see the output of the rollout parameter for the 4 instances from Tensorboard:
![RL_Results](https://user-images.githubusercontent.com/90847641/159699549-0a182141-fe8b-4496-b8e6-96a5df9d5e08.png)

After training the 4 instances, I tested each of those 4 on the same environment by using the following code:
```
#Load a trained model
from stable_baselines3 import A2C

if testOneModel==True:
    env = DSM_BT1_Env()
    models_dir = "models/A2C"
    logdir = "logs"
    
    #load the saved model
    model_path = f"{models_dir}/Started_23-03-2022--11-14-49_Episode_4_Timesteps_100000"
                                
    model= A2C.load(model_path, env = env)
    
    episodes = 1
    
    print("\n \n \n \n Testing with trained model \n \n \n")
    
    for episode in range (episodes):
        obs = env.reset()
        done = False
        print("episode: ", episode)
        timeslot = 1
        while not done:
            env.render()
            action,_ = model.predict(obs)
            print()
            print(f"current timeslot: {timeslot}")
            print("action: ", action)
            timeslot = timeslot+1
            
            obs, reward, done, info = env.step(action)
            
    env.close()

```

I ran each instance 10 times on the environment and manually calculated the mean overall reward from the Gym environment (that is also returned after each timeslot) and here you can see the results:

- Instance 1: mean reward: -2690, mean standard deviation: 742
- Instance 2: mean reward: -1678, mean standard deviation: 146
- Instance 3: mean reward:  434, mean standard deviation: 172
- Instance 4: mean reward:  534, mean standard deviation: 215

There are 2 things that are striking to me:

1. Why do the instances with the lowest rollout parameter "ep_rew_mean" yield the best results (highest mean reward)?
2. Why are the magnitues of the values for the reward so different? The rollout parameter "ep_rew_mean" has values -500 and -29000 whereas the real manually caluclated means have a range between -3700 and 746.

**Comment by Miffyli** [comment]
Hey, please follow and fill the issue/question template next time :). A full code to completely replicate your issue would be welcomed (and necessary for bug hunting).

`ep_rew_mean`, as you guessed and mentioned in docs, does indeed reflect the average episodic reward (average sum of rewards over one episode). Ideally, the evaluated model should reach a similar `ep_rew_mean`.

Try using the evaluation helper functions etc SB3 provides (see [this](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#basic-usage-training-saving-loading] example). Your evaluation code does not seem to track/sum rewards. I suspect there is something off in your calculations or environment to have this level of disparency. Maintaining consistent performance is part of the tests in SB3 which pass.

**Comment by PBerit** [comment]
@Miffyli : Thanks for your answer Miffyli. I used the evaluation helper as you suggested with the same model and it yields completely different results compared to testing the model with my convetional approach. Here you can see the code:
```
#Load a trained model
from stable_baselines3 import A2C

if testOneModelConventionalApproach ==True:
    env = DSM_BT1_Env()
    models_dir = "models/A2C"
    logdir = "logs"
    
    #load the saved model
    model_path = f"{models_dir}/Started_23-03-2022--11-14-49_Episode_4_Timesteps_100000"
                                
    model= A2C.load(model_path, env = env)
    
    episodes = 1
    
    print("\n \n \n \n Testing with trained model conentional approach \n \n \n")
    
    for episode in range (episodes):
        obs = env.reset()
        done = False
        print("episode: ", episode)
        timeslot = 1
        while not done:
            env.render()
            action,_ = model.predict(obs)
            print()
            print(f"current timeslot: {timeslot}")
            print("action: ", action)
            timeslot = timeslot+1
            
            obs, reward, done, info = env.step(action)
            
    env.close()



if testOneModelWithEvaluationHelperApproach ==True:
    from stable_baselines3.common.evaluation import evaluate_policy
    env = DSM_BT1_Env()
    models_dir = "models/A2C"
    logdir = "logs"
    
    #load the saved model
    model_path = f"{models_dir}/Started_23-03-2022--11-14-49_Episode_4_Timesteps_100000"
    model= A2C.load(model_path, env = env)

    print("\n \n \n \n Testing with trained model evaluaiton helper approach \n \n \n")
                            

    mean_reward, std_reward = evaluate_policy(model, model.get_env(), n_eval_episodes=1)
    
    print(f"mean_reward = {mean_reward}")
    print(f"std_reward = {std_reward}")


```

When I test the very same model on the very same gym environment by using my conventional approach `testOneModelConventionalApproach ==True` then the average mean is as stated before around 500. However, when testing with the evulationHelper approach `testOneModelWithEvaluationHelperApproach ==True` the average reward is about -2100. So what I don't undestand is why are the results so completely different altough the very same model is used? Further, -2100 is still far away from the values of the rollout parameter "ep_rew_mean" that can be seen in Tensorboard (from -21000 to - 29000).

One thing I got to know through the Evaluation Helper is that the calculated reward from the Evaluation Helper is equal to my calculated cumulative reward in the gym environment. So I do calculate the cumulative reward in my environment in the correct way. 

As my code has more than 1000 lines (with the gym environment itself having more than 800 lines) I don't think it is really useful to share this code. This is why I just share the relevant parts of it.

**Comment by PBerit** [comment]
@Miffyli : Thanks Miffyli  for your answer. I really appreciate it. Okay, I will try to have a closer look at my environment and if I can reproduce the problem with a smaller code, I will open a new issue. Thanks for the advice.
