### ISSUE TITLE
[Feature Request] Decouple rollouts collection from the algorithms

### ISSUE THREAD

**Issue by GalAvineri** [DLR-RM/stable-baselines3#833]
### 🚀 Feature

Decouple the rollouts collection functionality found in `OnPolicyAlgorithm` and `OffPolicyAlgorithm` classes from their respective inheriting policy algorithm classes (such as PPO and A2C).

### Motivation

If these two components were decoupled it would be easier to modify and extend each of them for more needs.

For example, i'm experimenting with on-policy algorithms that require a different method of collecting data.
Therefore I would like to extend the functionality of the `collect_rollouts` function. The current way to do that is to create a new class that extends the `OnPolicyAlgorithm` class, but doing so would also require defining a new class for each of the algorithms that inherit `OnPolicyAlgorithm` (such as PPO and A2C) and extend that new class.  

If i'm correct in my understanding that the rollouts collection process does not depend on the functionality of the specific policy algorithm, than it could be provided as an independent service. This would allow to extend the data collection functionality independently. 

### Pitch

Export the `collect_rollouts` function outside of `OnPolicyAlgorithm` and `OffPolicyAlgorithm` classes, and have it receive a `policy` parameter instead.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
If I understand your proposal it is similar to https://github.com/hill-a/stable-baselines/issues/381 and to `Collector` from [tianshou](https://github.com/thu-ml/tianshou)?

**Comment by GalAvineri** [comment]
I would say it is similar to `Collector` from tianshou

**Comment by araffin** [comment]
In that case, I think this is out of scope of SB3, we don't plan to be as modular as tianshou. One of the main reason is all the small details that are needed for each algorithm during or right after data collection, and that are critical for good performances.
For instance:
https://github.com/DLR-RM/stable-baselines3/blob/44e53ff8115e8f4bff1d5218f10c8c7d1a4cfc12/stable_baselines3/common/on_policy_algorithm.py#L194-L214

> For example, i'm experimenting with on-policy algorithms that require a different method of collecting data.

However, nothing prevents you from forking SB3 and having a custom `collect_rollout()` implemented, so you don't have to redefine all classes. (we provide instructions in our doc to install from source)

**Comment by araffin** [comment]
Closing as out of scope of SB3 and other solution exist for the use-case.
