### ISSUE TITLE
Support Gym 0.23.1

### ISSUE THREAD

**Issue by cool-RR** [DLR-RM/stable-baselines3#840]
When installing Stable Baselines 3, Pip uninstalled my existing Gym version 0.23.1 and instead installed Gym 0.21.0, probably because that's what Stable Baselines 3 specifies. It would be nice if I could use the latest version of Gym with Stable Baselines 3.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Being worked on in #780. Closing as duplicate.
