### ISSUE TITLE
[Question] How to log evaluations from multiple eval envs for Tensorboard?

### ISSUE THREAD

**Issue by albertcthomas** [DLR-RM/stable-baselines3#843]
I am wondering about the best way to have more than one eval env showing in tensorboard. For one env I can pass it to either `create_eval_env` when instantiating the agent or `eval_env` in the the `learn` method. However I would like to pass another env. I can use an `EvalCallback` that I pass as a callback. However using this callback the logging to tensorboard is done using the same keys (e.g. `eval/mean_reward`) thus conflicting with the logging of the eval env passed to `eval_env`. I created my own EvalCallback, modifying the parts where the performance are logged:

https://github.com/DLR-RM/stable-baselines3/blob/cdaa9ab418aec18f41c7e8e12e0ad28f238553eb/stable_baselines3/common/callbacks.py#L430-L432

using a different string than `eval/mean_reward` and this works. But is there an easier way to do this?

**Comment by albertcthomas** [comment]
Thanks for the quick reply!

> (the code was built on the assumption that the agent is tested more-or-less on the same environment as it is trained on) :)

My use case is model-based RL: the sb3 agent is trained on a model of the dynamics (wrapped into a gym env). For debugging and analysis purposes (as well as visualizing the different performances in tensorboard as the agent is training) I am using the model env as well as the true env (with the true dynamics) as eval envs.

Closing the issue then :)

**Comment by ReHoss** [comment]
It could be nice to add some "id" of the evaluation environment so that we could pass multiple EvalCallback  from multiple compatible environments to supervise performance generalisation?
