### ISSUE TITLE
[Question] Change PPO clip_range during training

### ISSUE THREAD

**Issue by raymond2338** [DLR-RM/stable-baselines3#845]
### Question

When using PPO, is there a way to change the clip_range variable over time during training? Let's say it starts the clip range starts at 0.2 and after 1M time steps I want to reduce down to 0.1 for example. The training ends for a total time steps of 2M. Thanks

**Comment by raymond2338** [comment]
Hi, I tried finding in the doc as well but wasn't able to locate?

**Comment by araffin** [comment]
close https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html#stable_baselines3.ppo.PPO

"clip_range (Union[float, Callable[[float], float]]) – Clipping parameter, it can be a function of the current progress remaining (from 1 to 0)."

**Comment by araffin** [comment]
see also https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#learning-rate-schedule
