### ISSUE TITLE
[Bug] HER: final goal selection strategy does not sample the final achieved goal

### ISSUE THREAD

**Issue by qgallouedec** [DLR-RM/stable-baselines3#847]
### 🐛 Bug

When you choose the final goal selection strategy, HER samples the second to last goal instead of the last goal (see the code).

If the episode is _[s0, s1, s2, s3]_, it should sample _s3_, but it samples _s2_.

The problem is simple to understand in the "final" case. But I think that this problem concerns all three goal selection strategies.

### To Reproduce

```python
import numpy as np
from stable_baselines3 import HerReplayBuffer
from stable_baselines3.common.envs import BitFlippingEnv
from stable_baselines3.common.env_util import make_vec_env
import gym

# Env creation is not relevant, it is just to make the code work.
env = make_vec_env(
    BitFlippingEnv,
    env_kwargs=dict(n_bits=2),
    wrapper_class=gym.wrappers.TimeLimit,
    wrapper_kwargs=dict(max_episode_steps=10),
)

# A simple episode
achieved_goals = np.array([
        [[0, 0]],
        [[1, 1]],
        [[2, 2]],
])

# Actions, rewards, true goals and info are not relevant, they will be constant
action = np.array([[0.0]])
reward = np.array([0.0])
infos = [{}]
desired_goals = np.zeros_like(achieved_goals)
observations = np.zeros_like(achieved_goals)


# Create the buffer
buffer = HerReplayBuffer(
    env,
    buffer_size=100,
    n_sampled_goal=np.inf,  # all sampled goals are relabelled
    goal_selection_strategy="final",
)
# And store the transitions
buffer.add(
    obs={"observation": observations[0], "achieved_goal": achieved_goals[0], "desired_goal": desired_goals[0]},
    next_obs={"observation": observations[1], "achieved_goal": achieved_goals[1], "desired_goal": desired_goals[1]},
    action=action,
    reward=reward,
    done=np.array([False]),
    infos=infos,
)

buffer.add(
    obs={"observation": observations[1], "achieved_goal": achieved_goals[1], "desired_goal": desired_goals[1]},
    next_obs={"observation": observations[2], "achieved_goal": achieved_goals[2], "desired_goal": desired_goals[2]},
    action=action,
    reward=reward,
    done=np.array([True]),
    infos=infos,
)

samples = buffer.sample(1)
print(samples.observations["desired_goal"]) # expect [2, 2], got [1, 1]
```

### Could fix the issue

I think the cause is that the new sampled goal comes from `achieved_goal` and not from `next_achived_goal`. Potential fix is to replace

https://github.com/DLR-RM/stable-baselines3/blob/44e53ff8115e8f4bff1d5218f10c8c7d1a4cfc12/stable_baselines3/her/her_replay_buffer.py#L265

by

```python
return self._buffer["next_achieved_goal"][her_episode_indices, transitions_indices] 
```

### System Info

 * OS: macOS-12.2.1-x86_64-i386-64bit Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
 * Python: 3.8.13
 * Stable-Baselines3: 1.4.1a3
 * PyTorch: 1.11.0
 * GPU Enabled: False
 * Numpy: 1.22.3
 * Gym: 0.21.0

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello, 
thanks for spotting the bug.

> If the episode is [s0, s1, s2, s3], it should sample s3, but it samples s2.

just to be sure, in the case s3 would correspond to `terminal_observation`? (observation return when `done=True`, no action is taken)
