### ISSUE TITLE
Load custom algo doesn't use saved policy_kwargs

### ISSUE THREAD

**Issue by buoyancy99** [DLR-RM/stable-baselines3#85]
Currently loading custom algorithm doesn't actually use saved policy_kwargs in a checkpoint. 
I started a PR here at https://github.com/DLR-RM/stable-baselines3/pull/84#issue-442345526

Customize policy code might be super long here. Basically, when using customize policy with customized kwargs, the policy_kwargs for the algorithm was saved in checkpoint. However, when loading the checkpoint at test time, the algorithm wasn't recreated with saved data['policy_kwargs'] from zip file. 

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed: venv
 * GPU models and configuration: 2080TI, Driver 440
 * Python 3.7
 * PyTorch 1.15
 * Gym version
 * Versions of any other relevant libraries

**Comment by araffin** [comment]
>Customize policy code might be super long here.

Why? This is the most important point of the bug report.

A custom policy could be as simple as:

```python

from stable_baselines3 import SAC

model = SAC('MlpPolicy', 'Pendulum-v0', policy_kwargs=dict(net_arch=[64]))
model.save('sac_pendulum')
del model
# nor error
model = SAC.load('sac_pendulum')
```

**Comment by araffin** [comment]
If no minimal "non" working example is provided, I will close this issue.

**Comment by buoyancy99** [comment]
> If no minimal "non" working example is provided, I will close this issue.

Sorry I was too busy in the past weeks. Will post code today
