### ISSUE TITLE
How Can I set up my own phase sequence in the DQN method?

### ISSUE THREAD

**Issue by sina-behnam** [DLR-RM/stable-baselines3#850]
### Question
How can i limit the DQN algorithm to stick to my phase sequence of actions in discrete mode?
For example, when I'm predicting, the returning action is arbitrary corresponding to what it had learned, But I want to force it to follow my expected output action in desired time.
### Additional context
my action space = [0 , 1, 2 ,3]
the sample output action of DQN prediction :
[0 , 1, 2, 1, 2, 0, 1, 2, 1 ....]
it may never reach to action 3 and also is there any way to force it to follow the order of actions?

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
If this is done only during `predict` (not during training), you could enforce it with an environment wrapper which overrides the actions as you desire.

If you wish to do this during training, you could override the action [here](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/off_policy_algorithm.py#L578). By the virtue of DQN being an "off-policy" algorithm, this does not break underlying theory and training should, in theory, still work :)
