### ISSUE TITLE
Monitor is not called in dqn_cnn.py[Question] question title

### ISSUE THREAD

**Issue by HUXIAOWANG513** [DLR-RM/stable-baselines3#860]
I'm sorry to bother you. I found the ep_reward value was nan in log info. I think the reason of ep_reward value was nan that the monitor was not called at all in dqn_cnn.py. I wonder if it's because of my environment or something else?

**Comment by Miffyli** [comment]
Hey. There is no `dqn_cnn.py` file in SB3 code, you are referring to some other codebase. Episode reward statistics are `nan`/empty until at least one episode is completed, so you might want to check that. Note that we do not offer tech support, so unless there is a bug to report for SB3 or an enhancement to propose, please close this issue.
