### ISSUE TITLE
[Question] What is the default MLP policy being used in PPO

### ISSUE THREAD

**Issue by raymond2338** [DLR-RM/stable-baselines3#867]
### Question

What is the default MLP policy being used in PPO

**Comment by araffin** [comment]
> What is the default MLP policy being used in PPO

If you look at the code, it is a 2-layers mlp with 64 units per layers, using a separate network for policy and value function.

**Comment by pengzhi1998** [comment]
How may I modify the structure for this default one? May I change it through any APIs?

**Comment by Miffyli** [comment]
@pengzhi1998 Yes, see [docs](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html).

**Comment by pengzhi1998** [comment]
Got it, thank you!
