### ISSUE TITLE
[Question] Evaluation Helper uses another policy when evaluating a model compared to a manual evaluation

### ISSUE THREAD

**Issue by PBerit** [DLR-RM/stable-baselines3#879]
Hi all,

I have been having problems with the understanding of the rollout parameter "ep_rew_mean" (see here https://github.com/DLR-RM/stable-baselines3/issues/832) as I get different values for the manually calculated cumulative reward in my environment, the values listed in TensorBoard and the values from the Evaluation Helper. 

When I manually test a certain model, I just sum up the rewards for every timeslot and at the end return the last value. Here is the code:
```
#Load a trained model
from stable_baselines3 import A2C

# Create the environment
env = DSM_BT1_Env()

# load the saved model
models_dir = "models/A2C"
model_path = f"{models_dir}/Started_21-04-2022--13-53-41_Episode_2_Timesteps_100000"
model = A2C.load(model_path, env=env)

logdir = "logs"

episodes = 1
averageCumulativeReward_HelpSum = 0
results_Overall = np.zeros(episodes )


print("\n \n \n \n Testing with trained model manually \n \n \n")

for episode in range (episodes):
    obs = env.reset()
    done = False
    print("episode: ", episode)
    timeslot = 1
    cumulativeReward = 0
    while not done:
        env.render()
        action,_ = model.predict(obs)
        timeslot = timeslot+1

        obs, reward, done, info = env.step(action)
        cumulativeReward += reward
    print(f"cumulative Reward: {round(cumulativeReward,2)} \n")
    results_Overall [episode] = round(cumulativeReward,2)
    averageCumulativeReward_HelpSum += cumulativeReward

env.close()
```

I also use the same for the Evaluation Helper object from StableBaselines3. Here is the code:
```
from stable_baselines3.common.evaluation import evaluate_policy
episodes = 1
# Create the environment
env = DSM_BT1_Env()

# load the saved model
models_dir = "models/A2C"
model_path = f"{models_dir}/Started_21-04-2022--13-53-41_Episode_2_Timesteps_100000"
model = A2C.load(model_path, env=env)

mean_reward, std_reward = evaluate_policy(model, model.get_env(), n_eval_episodes=  episodes )
print("\n \n \n \n Testing with trained model Evaluation helper \n")
print(f"mean_reward = {mean_reward}")
print(f"std_reward = {std_reward}")
```

In most cases the cumulative reward values for the evaluation helper and the manual testing differ. Even if I have 100 evaluation runs. The striking point is, that the evaluation helper often uses other policies when evaluating a model compared to a manual evaluation even though the model is exactly the same. In several of those cases the policy of the evaluation helper is just to always use a 0 for the action for every decision (I use a mappin within the environment from a symetric action space [-1, 1] to an action space with the options [0, 0.25 - 1].) My question is whether someone has an idea why this might happen? When having a trained model and loading it via `model = A2C.load(model_path, env=env)` are there different policies contained in such a model? Because the Evaluation Helper definitely behaves different compared to the manual evaluation.

**Comment by araffin** [comment]
`action,_ = model.predict(obs, deterministic=True)` or pass `deterministic=False` to the evaluation helper,
Probably a duplicate of https://github.com/DLR-RM/stable-baselines3/issues/851#issuecomment-1091130586

**Comment by PBerit** [comment]
@araffin : Thanks arraffin for your answer. Actually you suggested code make the two evaluation methods more similar.
