### ISSUE TITLE
[Question] DDPG,TD3parament error

### ISSUE THREAD

**Issue by LLM1602** [DLR-RM/stable-baselines3#883]
### Question

I find it can work and get an error when I use the ddpg or TD3 as yesterday ,I don't know what happened in the night.The error is " super(DDPG, self).__init__(
TypeError: __init__() got an unexpected keyword argument 'policy_delay'"
In the td3,the error is " 
model = TD3(
TypeError: __init__() missing 1 required positional argument: 'policy_base'
which means the parament is error .So what is the reason and how should i do slove the problem?

### Additional context
![image](https://user-images.githubusercontent.com/41284714/164951641-1fd9fdbc-af90-4fa5-b858-c99de52927b8.png)
![image](https://user-images.githubusercontent.com/41284714/164951645-d76492ac-12da-4fac-9553-deb95c447cb7.png)

![image](https://user-images.githubusercontent.com/41284714/164951628-01827a7f-eb88-4735-8e30-ac42600caa94.png)
![image](https://user-images.githubusercontent.com/41284714/164951620-e9f1966a-f623-456f-80ae-2cc430456f82.png)

### Checklist

- [ ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by LLM1602** [comment]
The version I used is Release 1.2. (2021-09-01)

**Comment by araffin** [comment]
Hello,
please fill the bug issue template completely and use code blocks (not screenshots) to provide a minimal example to reproduce the error.
I would recommend to upgrade to latest SB3 version anyway.

**Comment by araffin** [comment]
Closing as the issue template was not filled completely.
