### ISSUE TITLE
[Question] Is the rollout parameter "ep_rew_mean" more relevant or the output of the Evaluation Helper

### ISSUE THREAD

**Issue by PBerit** [DLR-RM/stable-baselines3#886]
Hi all,

I would like to know if the rollout parameter "ep_rew_mean" is more relevant or the output of the Evaluation Helper from Stable-Baselines3. In my application they sometimes differ strongly (while sometimes beeing similar).

I have a custom OpenAI-Gym environment and I calculate a reward and return it in the step function. Now I have 2 methods of evaluating a trained model. One is a manual approach where I just sum over all rewards after each action is taken. The code looks like this:
```
#Load a trained model
from stable_baselines3 import A2C

# Create the environment
env = DSM_BT1_Env()

# load the saved model
models_dir = "models/A2C"
model_path = f"{models_dir}/Started_22-04-2022--11-01-35_Episode_3_Timesteps_100000"
model = A2C.load(model_path, env=env)

logdir = "logs"

episodes = 200
averageCumulativeReward_HelpSum = 0
results_Overall = np.zeros(episodes )


print("\n \n \n \n Testing with trained model manually \n \n \n")

for episode in range (episodes):
    obs = env.reset()
    done = False
    print("episode: ", episode)
    timeslot = 1
    cumulativeReward = 0
    while not done:
        env.render()
        action,_ = model.predict(obs)
        timeslot = timeslot+1

        obs, reward, done, info = env.step(action, deterministic=False)
        cumulativeReward += reward
    print(f"cumulative Reward: {round(cumulativeReward,2)} \n")
    results_Overall [episode] = round(cumulativeReward,2)
    averageCumulativeReward_HelpSum += cumulativeReward

env.close()
```

Furthermore I use the Evaluation Helper from Stable-Baselines3 as a second instance of evaluation. The code looks like this:
```
from stable_baselines3.common.evaluation import evaluate_policy
episodes = 200
# Create the environment
env = DSM_BT1_Env()

# load the saved model
models_dir = "models/A2C"
model_path = f"{models_dir}/Started_22-04-2022--11-01-35_Episode_3_Timesteps_100000"
model = A2C.load(model_path, env=env)

mean_reward, std_reward = evaluate_policy(model, model.get_env(), n_eval_episodes=  episodes , deterministic=False )
print("\n \n \n \n Testing with trained model Evaluation Helper \n")
print(f"mean_reward = {mean_reward}")
print(f"std_reward = {std_reward}")
```

Here you can see the results of 4 successively trained models in Tensorboard for the rollout parameter "ep_rew_mean"
<img width="835" alt="Tensorboard_results" src="https://user-images.githubusercontent.com/90847641/165052651-c38f9e00-e943-4479-bb84-8145da690469.png">

So I have 4 trained models (I confusingly name them Episode_1 to Episodes_4. This should not be confused with the episodes runs of a OpenAI-Gym custom environment). The average results for the manual evaluation and the Evaluation Helper when having 200 runs are:
![grafik](https://user-images.githubusercontent.com/90847641/165053205-f4b1b3c3-bbc3-4622-a7d0-d8f317b1043a.png)

What is striking is that while for the Episode_2 and Episode_4 the rollout parameter "ep_rew_mean" may be in line with the manually calculated reward and the reward of the Evaluation Helper, for Episode_1 and Episode_3 this is definitely not the case. There is a huge differences between the rollout parameter "ep_rew_mean" and the real reward. 

It might be worth mentioning that I also print out the reward within the OpenAI-Gym environment for every timeslot and sum it up. The resulting award after each run in the OpenAI-Gym environment is always identical to the values from the manual evaluation or the Evaluation Helper. This is why I call this the real reward. As far as I see it, there can't be a mistake within the OpenAI-Gym environment regarding the calculation of the reward as the sum over all returned rewards is always equal to the output of the Evaluation Helper. 

Now my question is whether the rollout parameter "ep_rew_mean" is more relevant or the output of the Evaluation Helper (or the manual evaluation)? In my example, according to the rollout parameter "ep_rew_mean" Episode_4 is better than Episode_3 but when calculating the real reward both the Evaluation Helper and the manual evaluation favour Episode_3. Normally I would say that the output of the Evaluation Helper is more relevant as it is always identical to the returned sum of rewards of the OpenAI-Gym environment and most of the time has quite similar values as the manual evaluation (which also just sums over the returned rewards of the OpenAI-Gym environment). However, during the training process in Stable-Baselines3 the rollout parameter "ep_rew_mean" is always mentioned this is why I am wondering whether the algorithms in Stable-Baselines3 optimize for the real reward or the rollout parameter "ep_rew_mean"?

**Comment by araffin** [comment]
Hello,
from doc the https://stable-baselines3.readthedocs.io/en/master/common/logger.html#rollout:
> ep_rew_mean: Mean episodic training reward (averaged over 100 episodes), a Monitor wrapper is required to compute that value (automatically added by make_vec_env).`

https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#how-to-evaluate-an-rl-algorithm

> As some policy are stochastic by default (e.g. A2C or PPO), you should also try to set deterministic=True when calling the .predict() method, this frequently leads to better performance. Looking at the training curve (episode reward function of the timesteps) is a good proxy but underestimates the agent true performance.

**Comment by PBerit** [comment]
@araffin : Thanks arrafin for your answer. Actually I set `demerministic=True` for both the manual evaluation and the Evaluation Helper. Here you can see the result:
![grafik](https://user-images.githubusercontent.com/90847641/165064649-7a061a2d-4346-44b0-bfe4-4e2845d8197c.png)
While for Episode_1 to Episode_3 this may be in line with the rollout parameter "ep_rew_mean", for Episode_4 this is definitely not the case. And as in the non-deterministic case, the manual evaluation and the Evaluation Helper would slightly favour Episode_3 over Episode_4 while the rollout parameter "ep_rew_mean" would strongly favour Episode_4 over Episode_3 (even the minimum value for Episode_4 is higher than the maximum value of Episode_3).

**Comment by PBerit** [comment]
@araffin : Thanks for your answers araffin. Any comments to my last comments? I'll highly appreciate every further comment from you.

**Comment by PBerit** [comment]
Can anyone give me more insights about possible reasons why the rollout parameter "ep_rew_mean" might not the the sum of cumulative rewards from the gym environment and the output of the Stable-Baselines 3 Evaluation Helper? For me this is kind of weird as the returned cumulative reward of my gym environment is totally equal to the output of the Evaluation Helper but not with the rollout parameter "ep_rew_mean".

**Comment by PBerit** [comment]
@Miffyli : Thanks a lot Miffyli for your answer. To be totally honest, I don't really understand your 2 advices. As far as I see it I don't explicity use any wrapper (I don't even know what this is) for changing the reward. I just calculate the reward in the step function of the Open-Ai gym environment and return it for every time slot. Just for the sake of checking, I also calculate the cumulative reward within the step function which is just an independant variable that is not returned at all. The cumulative help variable has always the same values as the output of the Evaluation Helper. So the Evaluation Helper indeed calculates the sum of rewards for every time slot. However, the rollout parameter "ep_rew_mean" sometimes differs (stronlgy) from the output of the Evaluation Helper. 

As the values from the Evaluation Helper are totally in line with the sum of cumulative rewards, I don't think that I made a mistake in the implementation of the reward.

**Comment by Miffyli** [comment]
Oh, I think the confusion is in the way `ep_rew_mean` is computed: it is computed over 100 previous episodes done during training (policy has changed during these 100 episodes likely). Naturally, it is not unexpected that this value is different compared to the results from evaluation helper, which evaluates a fixed policy (it is not updated).

**Comment by PBerit** [comment]
@Miffyli: Thanks a lot for your answer and effort. I really appreciate it. Okay I understand. Maybe one last question on this topic which is also the core topic of my question. Is it possible to let the algorithms from Stable-Baselines 3 optimize for the output of the evaluation helper instead of the rollout parameter "ep_rew_mean". During the training process, the rollout parameter "ep_rew_mean" is always mentioned this is why I assume that naturally the algorithms in Stable-Baselines 3 optimize for that parameter which in my example is not the "correct" parameter as I would like to optimize for the sum of cumulative rewards which is essentially the output of the Evaluation Helper.

**Comment by Miffyli** [comment]
This goes to more tech support side and I can not provide much help, but overall the answer is no: SB3 algorithms optimize for maximum maximum discounted sum of rewards (reflected by `ep_rew_mean`) from the training environments, not from the evaluation environment. If evaluation environment == training environment, then you are also optimizing for the reward in the evaluation environment.

Closing this issue as resolved.

**Comment by PBerit** [comment]
Thanks Miffyli for your answer and effort. I really appreciate it. For me it is kind of strange to hear that the algorithms of Stable-Baselines 3 do not necessarily optimize for the reward that I define in the step function of the Open-AI gym environment. This makes it quite hard (and almost impossible) to optimize for anything as I don't know what effects my defined reward will have on the optimization process of the Stable-Baselines 3 algorithms. I am stronlgy questioning the rationale behind this approach. If Stable-Baselines 3 somehow transforms the reward that I define in the step function of the Open-AI gym environment, it is quite intransparent what I need to do in order to get good reward values at the end, as the reward I want to optimize and that I implemented is not the optimization goal of the Stable-Baselines 3 algorithms.

**Comment by PBerit** [comment]
Does anybody have a suggestion how to make the algorithms of Stable-Baselines 3 optimize for the sum of rewards from the training environment (which is the output of the Evaluation Helper) instead of optimizing for the rollout parameter "ep_rew_mean"? Stable-Baselines 3 somehow transforms the sum of rewards from the Open-AI Gym environment and because of this I don't know what to do in order to get good values for the real sum of rewards from the training environment. I appreciate every suggestion as I have been struggeling with this issue for quite some time.

**Comment by ReHoss** [comment]
> Thanks Miffyli for your answer and effort. I really appreciate it. For me it is kind of strange to hear that the algorithms of Stable-Baselines 3 do not necessarily optimize for the reward that I define in the step function of the Open-AI gym environment. This makes it quite hard (and almost impossible) to optimize for anything as I don't know what effects my defined reward will have on the optimization process of the Stable-Baselines 3 algorithms. I am stronlgy questioning the rationale behind this approach. If Stable-Baselines 3 somehow transforms the reward that I define in the step function of the Open-AI gym environment, it is quite intransparent what I need to do in order to get good reward values at the end, as the reward I want to optimize and that I implemented is not the optimization goal of the Stable-Baselines 3 algorithms.

It should of course optimize over rewards defined by your environment, the answer is elsewhere. I also have discrepency between evaluation rewards and rollout rewards...
