### ISSUE TITLE
Could anyone please help clarify batch_size, epochs concepts in the PPO algorithm?

### ISSUE THREAD

**Issue by t2234** [DLR-RM/stable-baselines3#893]
From the documentation on PPO algorithm:

- batch_size (int) – Minibatch size
- n_epochs (int) – Number of epoch when optimizing the surrogate loss

So my questions are:

1. the size of the batch should automatically be obtained from n_env*n_step. Then what is this "batch_size" argument for?
2. the number of epochs should automatically be obtained from total_timestep/(n_env*n_step). Then what is this "n_epochs" argument for?

Thank you

**Comment by araffin** [comment]
Hello,
> the size of the batch should automatically be obtained from n_env*n_step. Then what is this "batch_size" argument for?

You should probably take a look at "Mini-batch Updates "  in https://ppo-details.cleanrl.dev//2021/11/05/ppo-implementation-details/ and spinning up (cf. link in our doc).

> the number of epochs should automatically be obtained from total_timestep/(n_env*n_step). Then what is this "n_epochs" argument for?

Maybe best for you is to take a look at the code. What you are describing is the number of iterations, `n_epochs` refers to how any times the data collected during one iteration should be re-used when doing gradient update.


@vwxyzjn I think we should add the blog post to our doc ;)

**Comment by t2234** [comment]
@araffin 
Thank you so much. It is clear now.
