### ISSUE TITLE
Make model return action with only integers

### ISSUE THREAD

**Issue by Cheeseboy8020** [DLR-RM/stable-baselines3#898]
### Question

How do I make a PPO model return only integers with a Box action space?

### Additional context
I have an env with a box action space with a dtype of np.byte when I run env.action_space.sample() it returns an action with only integers but when I train a model it returns floats as its action. This is the line where I define my action space.

```python
self.action_space = spaces.Box(low=0, high=20, shape=(12,), dtype=np.byte)
```

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
You should use `Discrete` action space for "integer" outputs. `Box` is strictly only for continuous (floats) actions, and the data type is disregarded.

**Comment by Cheeseboy8020** [comment]
Thank you using discrete action space works
