### ISSUE TITLE
[Question] FPS dropping 

### ISSUE THREAD

**Issue by xy9485** [DLR-RM/stable-baselines3#904]
### Question
Hi, I'm running some experiments on Atari games and using my own wrappers. I notice that the fps of  running off-policy algos is high enough at the beginning of training and then gradually keeps dropping. I can say cpu and gpu including ram and gpu memory are not the bottleneck, acutally quite sufficient.  Emphirically,what could be the reason behind in this case? Or could be an issue of the way to calculate fps?

SB3 version: 1.5.0

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by Miffyli** [comment]
Off-policy algos spend first thousands of steps (see `learning_starts` argument) only collecting samples without training, which is fast. After that point the policy is updated almost every step, which is quite slow and slows down the overall steps taken per second (FPS).
