### ISSUE TITLE
SB3 does not support gym.spaces.Discrete() 'start' 

### ISSUE THREAD

**Issue by adiyaDalat** [DLR-RM/stable-baselines3#913]
When I want to define an action space {-1,0,1} as below:
`self.action_space = spaces.Discrete(3, start=-1) `

Error reported. Seems that SB3 does not support the newest version of Gym.

Hope this can be supported in next version.

**Comment by araffin** [comment]
Hello,
please fill the request template completely.
An alternative exists which is using a wrapper.

I don't think we will support that feature as it requires quite some code changes for no apparent gain (and an alternative exists).
We need to update the env checker though.
