### ISSUE TITLE
[Question] Custom async step() calls for custom environment?

### ISSUE THREAD

**Issue by maxmax1992** [DLR-RM/stable-baselines3#915]
Hi, 
I'm having custom environment where the environment can't be directly with learn() call, as there are problems with step method, as it has to wait an action from the "client" (e.g. a separate thread which interacts with custom env in the other program). In other words I want to call the step function in async mode where the "step" might be blocking for the training algorithm itself as it has to wait the state transitions from separate threads. Do you know how this is doable? 
Thanks.

**Comment by Miffyli** [comment]
Hey, that is not a problem; all stable-baselines3 algorithms are "synchronized" algorithms, where they will patiently wait for the `step()` to complete from all environments. This will mean the training might be slow if your `step` calls are slow, but at least you do not have worry about complications from "async"-ness.

PS: Next time please fill in the issue template :)
