### ISSUE TITLE
Saved model perform much worse?

### ISSUE THREAD

**Issue by pengzhi1998** [DLR-RM/stable-baselines3#923]
### Question

I'm facing an issue similar to [this one](https://github.com/DLR-RM/stable-baselines3/issues/868): the saved PPO model (by `model.save` when training is completed or using `checkpoint` every specific number of steps) _**sometimes**_ (not always) performs much worse than which has been shown from `ep_rew_mean` in the printed log during training. 

I have read the [document](https://stable-baselines3.readthedocs.io/en/master/common/logger.html#explanation-of-logger-output) and understand `ep_rew_mean` is showing the mean accumulated reward for **100 episodes**, which means it might not be able to reflect how the model works after each iteration's training (around 40 episodes). But I still feel a little bit wired for such a big performance drop (and this drop doesn't always happen, sometimes the trained model performs better during testing than which is shown from the log (I think this is what I expected)). May I have your recommendation? Maybe use a `evalcallback`?

### Checklist

- [yes] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [yes] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by pengzhi1998** [comment]
Just tried `evalcallback`. From the log of the evaluations, it's true that the `ep_rew_mean` during rollout couldn't show the real performance. Evaluation would be a better metric. But why, during evaluation/test, the model performs worse?

**Comment by Miffyli** [comment]
If you use EvalCallback and use evaluation to compare results, you have likely removed large part of the training noise (e.g., even if average score over 100 last episodes is good, the _current_ model might just be worse than ones before it). Apart from this and making sure the code checks, there is not much on SB3 side that could be off (if you find something, please open up an issue!)

One potential thing might be that your environment behaves differently when you re-create it, which would lead agent to be trained on one type of dynamics and tested on a different one. There were some other issues regarding this but I can not remember what comments we gave on that (and can not find it as github search is not the best 😅 ). 

We do not have time to offer much tech support here, but for better answers, you could check the [RL Discord](https://discord.com/invite/xhfNqQv).

**Comment by pengzhi1998** [comment]
Thank you for your reply! But during evaluation and testing, all the parameters are set to be the same, and the `deterministic` values are both `True`. The test cases are using the model with the best evaluation reward. I'm actually expecting their performance to be the same. However, they're not. So I'm kind of confused. 
Here is how I set the callback:
`evaluation_callback = EvalCallback(env, n_eval_episodes=20, eval_freq=10240,
        best_model_save_path=os.path.join(os.path.abspath(os.path.dirname(__file__)), args.model_path))`

**Comment by Miffyli** [comment]
This goes into the tech support territory; if you can replicate the same behaviour with a regular Gym environment, please open up an issue reporting a bug  (with full code to replicate the issue etc). We have [tests](https://github.com/DLR-RM/stable-baselines3/blob/master/tests/test_save_load.py#L34) which check that saved and loaded models produce same outputs, so the problem is probably not in the model parameters. I recommend you test that your environment does not significantly change between creations, maybe by saving trajectories (what states agent visits and what actions it takes), and plotting them out in some way.

**Comment by pengzhi1998** [comment]
Got it. I'll take a check. Thank you!
