### ISSUE TITLE
[Feature Request] Remove `eval_env` parameter

### ISSUE THREAD

**Issue by araffin** [DLR-RM/stable-baselines3#925]
### 🚀 Feature

`eval_env` and `eval_freq` parameters were new in SB3 and were meant to facilitate evaluation in a separate env, by automatically creating evaluation env and `EvalCallback`.
However, they don't seem to be used that much and don't offer the flexibility of the `EvalCallback` at the cost of code duplication and maybe confusing parameters.

The idea would be to first deprecate (next SB3 version) and then remove all the parameters related to that feature.
Main drawback is that this would be a breaking change for people implementing custom algorithms.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by tobirohrer** [comment]
Hey, 
I wanted to check if this change is still planned. If so, I would take a look at it in the coming days.

**Comment by araffin** [comment]
Hello,
it is still planned, but it's not a priority.
I would like to integrate LN and dropout (https://github.com/DLR-RM/stable-baselines3/issues/1069), and probably progress bar callback first (https://github.com/DLR-RM/rl-baselines3-zoo/pull/287).
Actually, I would welcome more help to improve the RL Zoo.

However, you can of course work on such PR, please only deprecate the feature first (it should output a warning and remove the feature).
