### ISSUE TITLE
Different operating systems

### ISSUE THREAD

**Issue by fangxin-debug** [DLR-RM/stable-baselines3#926]
I have a simple question about stable-baselines3, can't I load .zip file in Linux where .zip file is trained in windows?

I take part in a kaggle competition, I trained my model in my Windows, and evaluation successfully, my system_info.txt file
```
OS: Windows-10-10.0.19041-SP0 10.0.19041
Python: 3.8.0
Stable-Baselines3: 1.5.0
PyTorch: 1.10.2
GPU Enabled: True
Numpy: 1.21.5
Gym: 0.21.0
```
and kaggle's Linux systems
```
== CURRENT SYSTEM INFO ==
OS: Linux-5.10.107+-x86_64-with-debian-bullseye-sid #1 SMP Tue May 24 15:07:21 UTC 2022
Python: 3.7.12
Stable-Baselines3: 1.5.0
PyTorch: 1.11.0+cpu
GPU Enabled: False
Numpy: 1.21.6
Gym: 0.24.0
```
When I load zip file in kaggle notebook, it report 
```
/kaggle/working/lib/stable_baselines3/common/save_util.py:412: UserWarning: The model was saved with SB3 <= 1.2.0 and thus cannot print system information.
  UserWarning,
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/kaggle_environments/agent.py", line 50, in get_last_callable
    exec(code_object, env)
  File "main.py", line 19, in <module>
    model = PPO.load(agent_path, print_system_info=True)
  File "/kaggle/working/lib/stable_baselines3/common/base_class.py", line 692, in load
    if "policy_kwargs" in data:
TypeError: argument of type 'NoneType' is not iterable
```
In my Windows, everything is OK.
when I check the observation output, I find
![image](https://user-images.githubusercontent.com/73596458/170909270-3deadf33-beeb-40c3-9280-4885ef2d8984.png)
It shouldn't be "ERROR", I don't know how to solve the problem, Thank you for your help!!!

**Comment by araffin** [comment]
> and kaggle's Linux systems

SB3 only support gym 0.21 for now (see #780 )
Try also to have the same python version between the envs (otherwise unpickling may result in errors, we have issues about that).
Please also fill up the custom env template and provide **minimal** example to reproduce the issue.

"The model was saved with SB3 <= 1.2.0"

Are you sure the first env was the one used to train the model?

**Comment by araffin** [comment]
Overall, my guess is that the OS is not the main issue here.

**Comment by fangxin-debug** [comment]
Thank for your advice, I decide train in kaggle, the kaggle's notebook  environment is troublesome.

**Comment by fangxin-debug** [comment]
I find the problem is that *cloudpickle* version is not right, kaggle's *cloudpickle* version is 2.0.0, but my PC is 2.1.0, so kaggle can't reload my .zip file, thank u.
