### ISSUE TITLE
Get DQN info

### ISSUE THREAD

**Issue by AnaUdir** [DLR-RM/stable-baselines3#931]
Hi!

I am solving OpenAI Gym's "problem" of a [Mountain Car](https://www.gymlibrary.ml/environments/classic_control/mountain_car_continuous/#) by using DQN (stable_baselines3). I define DQN model by:

```
dqn_model = DQN("MlpPolicy",
            env,
            verbose=1,
            train_freq=16,
            gradient_steps=8,
            gamma=0.99,
            exploration_fraction=0.2,
            exploration_final_eps=0.07,
            target_update_interval=600,
            learning_starts=1000,
            buffer_size=10000,
            batch_size=128,
            learning_rate=4e-3,
            policy_kwargs=dict(net_arch=[256, 256]),
            seed=2)
```

After learning i would like to check/get info/visualise this build network. Is there any function that can get me some info about my network (shape, weights... - more than just with `print(model.q_net`) ) or maybe even some hints how can i "plot" this network for better understanding?

Also, just checking if i understand correctly:  if i insert "obs" values (meaning position and velocity in my case) manually, the next two lines will provide me with the Q values for that "state/action" pairs by inserting state and action into pre-learnt Q network?

```
obs_tensor, _ = model.q_net.obs_to_tensor(obs)
q_values = model.q_net(obs_tensor)
```

Then if i wanted to act greedily i would simply select the action with highest Q value?

Thanks in advance.

**Comment by Miffyli** [comment]
Hey. Unfortunately these issues are not designed for custom tech support ("how to do X"). If the feature is not described in docs, it does not exist in SB3.  Next time, please fill in the issue template that is given when you create the issue. For better answers to your questions, you could try asking on [RL Discord](https://discord.com/invite/xhfNqQv). Generally, the networks are simple pytorch networks, so general pytorch visualization tools may work here.

Re Q-value question: yup! If you take the action with the highest Q-value, this will correspond to the greedy policy (also called "deterministic" in  SB3).
