### ISSUE TITLE
[Question] PPO train pick and place task

### ISSUE THREAD

**Issue by Rancho-zhao** [DLR-RM/stable-baselines3#933]
### Question

Hi, at first, I used TQC+HER to trian `FetchPickAndPlace-v1`, and got a good result. Then, I considered adding image info into observation. But due to FetchPickAndPlace env is based on gym.GoalEnv and TQC+HER is based on HerReplayBuffer, I couldn't seem to add image info and robot state info as observation at the same time. So I tried to use PPO to train `FetchPickAndPlace-v1`, however, after 5e6 timesteps, its reward doesn't improve, so could ppo train pick and place task?

### My train code
```
import gym

from stable_baselines3 import PPO

from stable_baselines3.common.env_util import make_vec_env

from stable_baselines3.common.callbacks import CheckpointCallback

env_id = 'FetchPickAndPlace-v1'

num_cpu = 4
vec_env = make_vec_env(env_id, n_envs=num_cpu)

log_dir = './tensorboard/' + env_id

checkpoint_callback = CheckpointCallback(save_freq=25000, save_path='model_checkpoints/'+env_id,
                                         name_prefix=env_id)

total_timesteps = 5000000

# PPO
model = PPO(policy="MultiInputPolicy", env=vec_env, verbose=1, normalize_advantage=True,
            tensorboard_log=log_dir)

model.learn(total_timesteps=total_timesteps, callback=checkpoint_callback)

model.save('./trained/'+env_id+'/'+env_id+model.__class__.__name__)
```

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by qgallouedec** [comment]
ASAIK, on this env, the reward is way too sparse for PPO to converge.

TQC+HER converges mainly because of HER.

You should try with the dense reward setting. "FetchPickAndPlaceDense-v1" if I remember correctly.

**Comment by Rancho-zhao** [comment]
Yes, I have tried the dense reward setting, but it still doesn't work. The reward change during training is shown in the figure below:

![屏幕截图 2022-06-17 192325](https://user-images.githubusercontent.com/54349793/174289262-915386ff-76e5-4814-821b-1b0a97743023.png)

**Comment by qgallouedec** [comment]
Okay. That's good to know, but it's not an unexpected result.

**Comment by qgallouedec** [comment]
So I suggest you to use an off-policy algorithm, like TQC

**Comment by Rancho-zhao** [comment]
Okay, I will try, thank you for your reply！
