### ISSUE TITLE
`MountainCarContinuous-v0` with `DDPG` and `TD3` does not learn

### ISSUE THREAD

**Issue by AndreasKaratzas** [DLR-RM/stable-baselines3#936]
### Question

I tried both a `DDPG` and a `TD3` agent for the `MountainCarContinuous-v0` gym environment and the agents do not learn. Is there any particular reason? Do you have any ideas that might improve the learning curve of the agent?

### Additional context

My code was based on the example script on your `README` file.

```python
import gym

from stable_baselines3 import TD3

env = gym.make("MountainCarContinuous-v0")

model = TD3("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10_000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, done, info = env.step(action)
    env.render()
    if done:
      obs = env.reset()

env.close()
```

**Comment by qgallouedec** [comment]
Try to add noise and train a bit longer. This should work:

```python
import gym
import numpy as np
from stable_baselines3 import TD3
from stable_baselines3.common.noise import OrnsteinUhlenbeckActionNoise

env = gym.make("MountainCarContinuous-v0")

action_noise = OrnsteinUhlenbeckActionNoise(np.zeros(1), 0.5 * np.ones(1))
model = TD3("MlpPolicy", env, action_noise=action_noise, verbose=1)

model.learn(total_timesteps=50_000)
```

You can also refer to baselines in the [zoo](https://github.com/DLR-RM/rl-baselines3-zoo).

**Comment by araffin** [comment]
what @qgallouedec said ;)
and you have pretrained agents with tuned hyperparameters online: https://huggingface.co/sb3/td3-MountainCarContinuous-v0

As written in our doc, don't expect default hyperparameters to work on every problem.
