### ISSUE TITLE
[Suggestion] Suggestion in `env_checker.py`

### ISSUE THREAD

**Issue by sushant1212** [DLR-RM/stable-baselines3#938]
### Suggestion
Hi! I was working on an environment in which the observation_space can change (by change I mean its shape and contents) every episode depending on the number of entities that are sampled in my env. To check this environment I was using the `env_checker.py`. 

The current code in `env_checker.py` has the following:
```python
def _check_returned_values(env: gym.Env, observation_space: spaces.Space, action_space: spaces.Space) -> None:
    """
    Check the returned values by the env when calling `.reset()` or `.step()` methods.
    """
    # because env inherits from gym.Env, we assume that `reset()` and `step()` methods exists
    obs = env.reset()
```
But once `env.reset()` is called the `observation_space` and the `action_space` that are passed as function parameters, do not represent the actual shapes for the current episode, causing the environment to fail the env_check. 

I wanted to ask if we can instead do something like this
```python
def _check_returned_values(env: gym.Env) -> None:
    """
    Check the returned values by the env when calling `.reset()` or `.step()` methods.
    """
    # because env inherits from gym.Env, we assume that `reset()` and `step()` methods exists
    obs = env.reset()
    observation_space = env.observation_space
    action_space = env.action_space
```

Wanted to know if this is a good suggestion. If it is so, I'd be glad to send a PR making the necessary changes. 

### Checklist
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by qgallouedec** [comment]
If the observation space changes during the learning, the policy network must also be changed. How do you handle that?

**Comment by sushant1212** [comment]
Using zero-padding, we can pad the observations to the maximum size

**Comment by qgallouedec** [comment]
Why not using maximum size observation as the observation shape and apply this zero-padding within the env?

**Comment by sushant1212** [comment]
I want to return both padded observations and non-padded observations depending on what the user wants. So, I thought it would be easier if the checker.py was as I have mentioned. I understand that if the checker.py runs well on the padded observations, it would surely run on the non-padded observations. But I think that the suggestion I have made would make the checker.py a bit more general. Do correct me if I am wrong.

**Comment by araffin** [comment]
> observation_space and the action_space that are passed as function parameters, do not represent the actual shapes for the current episode

if you do so, the learning algorithm will fail because the shapes in the buffer won't match the one received (that's the main purpose of the env checker).

> non-padded observations

If you want the algorithm to handle sequences, this is done on the algorithm side (we have `RecurrentPPO` for that from SB3 contrib), just give one observation at a time, the algorithm will take care of padding things.

**Comment by sushant1212** [comment]
Ok I understand. Closing the issue.
