### ISSUE TITLE
numpy ranndint function in atari_wrappers.py

### ISSUE THREAD

**Issue by boloson** [DLR-RM/stable-baselines3#945]
line 36 at stable_baselines3/common/atari_wrappers.py

noops = self.unwrapped.np_random.randint(1, self.noop_max + 1)

need to change to 

noops = self.unwrapped.np_random.integers(1, self.noop_max + 1)

in order to work, I installed through 'pip install stable-baselines3[extra]'

**Comment by araffin** [comment]
duplicate of https://github.com/DLR-RM/stable-baselines3/issues/875
