### ISSUE TITLE
HerReplayBuffer cannot handle VecEnv with multiple environments

### ISSUE THREAD

**Issue by GalAvineri** [DLR-RM/stable-baselines3#950]
### 🐛 Bug

HerReplayBuffer cannot handle VecEnv with more than 1 environment.
It raises an error in the `add()` function when called with the values returned from the `step()` function of such a VecEnv.
I belive it is because of the way the [buffer is defined](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/her/her_replay_buffer.py#L133-L143).

While fields such as the observation are defined with the shape of (num envs, item shape), the fields of action, reward and done are not.

### To Reproduce
I've taken the example from the [HER documantation page](https://stable-baselines3.readthedocs.io/en/master/modules/her.html) and changed the environment from a single environment to a `DummyVecEnv` containing two environments.
i.e i've changed from this environment definition:
```python
env = BitFlippingEnv(n_bits=N_BITS, continuous=model_class in [DDPG, SAC, TD3], max_steps=N_BITS)
```
to this definition:
```python
env1 = BitFlippingEnv(n_bits=N_BITS, continuous=model_class in [DDPG, SAC, TD3], max_steps=N_BITS)
env2 = BitFlippingEnv(n_bits=N_BITS, continuous=model_class in [DDPG, SAC, TD3], max_steps=N_BITS)
vec_env = DummyVecEnv([lambda _env=env: _env for env in [env1, env2]])
```

I've also truncated everything beyond the `learn()` call as the error happens during this call.
Everything else is the same.

### System Info

The result of `sb3.get_system_info()`:
OS: Windows-10-10.0.19042-SP0 10.0.19042
Python: 3.9.12
Stable-Baselines3: 1.4.0
PyTorch: 1.10.2
GPU Enabled: False
Numpy: 1.21.5
Gym: 0.19.0

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by qgallouedec** [comment]
HER is not compatible with multiple processing (see this [RL Algorithms](https://stable-baselines3.readthedocs.io/en/master/guide/algos.html#rl-algorithms) in the doc).

However, there is two working PR on the subject : #654 and #704 if you want to take a look.

**Comment by qgallouedec** [comment]
Duplicate #826

**Comment by GalAvineri** [comment]
I missed all the PRs and the documentation. Thank you for all the information!
