### ISSUE TITLE
DQN.load raises error 

### ISSUE THREAD

**Issue by zhumingpassional** [DLR-RM/stable-baselines3#952]
The DQN example https://highway-env.readthedocs.io/en/latest/quickstart.html#training-an-agent, runs successfully if using colab, however, it raises error if running locally in MacOS. In detail, the training process is successful, but " model = DQN.load("highway_dqn/model")" failed.

The following is error:
Traceback (most recent call last):
File "/Users/mingzhu/opt/anaconda3/lib/python3.9/site-packages/stable_baselines3/common/save_util.py", line 256, in open_path_pathlib
path = path.open("rb")
File "/Users/mingzhu/opt/anaconda3/lib/python3.9/pathlib.py", line 1252, in open
return io.open(self, mode, buffering, encoding, errors, newline,
IsADirectoryError: [Errno 21] Is a directory: 'highway_dqn/model'
python-BaseException

Could you please test it locally? Thanks for your effort.

the following is all the code:

import gym
import highway_env
from stable_baselines3 import DQN

env = gym.make("highway-fast-v0")
model = DQN('MlpPolicy', env,
              policy_kwargs=dict(net_arch=[256, 256]),
              learning_rate=5e-4,
              buffer_size=15000,
              learning_starts=200,
              batch_size=32,
              gamma=0.8,
              train_freq=1,
              gradient_steps=1,
              target_update_interval=50,
              verbose=1,
              tensorboard_log="highway_dqn/")
model.learn(int(2e4))
model.save("highway_dqn/model")

model = DQN.load("highway_dqn/model")
while True:
  done = False
  obs = env.reset()
  while not done:
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, done, info = env.step(action)
    env.render()

**Comment by qgallouedec** [comment]
Please fill the issue template.

I am not able to reproduce your error. The traceback suggests that  `highway_dqn/model` is a directory and not a file. Can you check that?

**Comment by zhumingpassional** [comment]
@araffin 
do you mean revise 

tensorboard_log="highway_dqn/")
model.save("highway_dqn/model")
model = DQN.load("highway_dqn/model")

to 

tensorboard_log="highway_dqn.zip")
model.save("highway_dqn_model.zip")
model = DQN.load("highway_dqn_model.zip")
? 

The following fig shows that there is 'model.zip' in highway_dqn. 

@qgallouedec 
yes. it's a directory.

![image](https://user-images.githubusercontent.com/43677883/177707139-6bf86d07-d3ca-48dc-b5c2-aacc5dcd01b8.png)
