### ISSUE TITLE
Enabling the rollout/success_rate in metrics

### ISSUE THREAD

**Issue by LutzFassl** [DLR-RM/stable-baselines3#954]
### Question

I'm trying to enable the rollout/success_rate as described [here](https://stable-baselines3.readthedocs.io/en/master/common/logger.html#rollout) so I can see the ratio of solved games during training.

However with the steps described in the docu I can't seem to make it work out of the box. 
The success rate is not showing up in the console/stdout. And also not showing up in tensorboard (which is my main goal).

The step() routine of my env is reporting the boolean self.solved to the info dict:
```
if done: # Report Success to Logger only on Final Step of Episode
    info = {"is_success":self.solved}
else:
    info = {}
return observation, reward, done, info
```

I am wrapping the env in the monitor with this info_keyword:
`env = Monitor(env, logdir, info_keywords=("is_success",))`

before initializing the model (a MaskablePPO):
```
checkpoint_callback = CheckpointCallback(save_freq=max(250_000 // n_envs, 1), save_path=f'./{modeldir}/{model_name}')
model = MaskablePPO("MlpPolicy", env,
                            verbose=1,
                            device=device,
                            tensorboard_log=logdir,)  
       
model.learn(total_timesteps=TIMESTEPS, callback=checkpoint_callback)
```

(Only using 1 DummyVecEnv at the moment)

### Additional context

The Monitor class does however save the boolean is_success per episode in a csv now. But I'd rather see the average over last 100 episodes in stdout and tensorboard.

There is probably something that I'm doing wrong here. I can also provide a minimal example otherwise. I did not try to use the EvalCallback to check success rate as it should just be evaluated during training.

Library Versions: (Python 3.8.13 64bit)
```
Package                       Version
----------------------------- ------------
gym                           0.21.0
numpy                         1.22.4
sb3-contrib                   1.5.0
stable-baselines3             1.5.0
tensorboard                   2.9.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
torch                         1.11.0+cu113
torchaudio                    0.11.0+cu113
torchvision                   0.12.0+cu113
```

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by LutzFassl** [comment]
Thanks for your quick answer!

I will use your plotting script
    or
create the custom callback
    or
just resort to the eval/ success rate then. 
Those are plenty of options - thank you!

PS:
> > I did not try to use the EvalCallback to check success rate as it should just be evaluated during training.
> 
> what do you mean?

I just meant I only tried getting the success rate from the rollout/ and not from eval/ when I posted the question. I can however confirm (now) that the eval/ success rate works. (Used eval_env / eval_freq / n_eval_episodes arguments on the MaskablePPO model.learn():
```
model.learn(total_timesteps=TIMESTEPS,
                    callback=checkpoint_callback,
                    eval_env = eval_env,
                    eval_freq = 1_000_000,
                    n_eval_episodes = 100)
```
Shows up in stdout and in tensorboard - nice.

From my point of view the question is answered sufficiently. Thanks again!

**Comment by araffin** [comment]
> @araffin can the docs please be updated 

Feel free to do a PR ;) (either to update the doc or to add the feature for on-policy algorithms)
Please note that you can also add that feature using callback.

**Comment by npnike10** [comment]
> But you could easily send those data to std out / tensorboard using a custom callback (cf. doc).

@araffin Could you (or anyone) please elaborate on this? I know I should be able to figure this out myself but I am just not able to understand what is to be done here, due to my incapability. 

I tried making a custom callback as below and it just gives zero success all the time when it should give 1 all the time. Thank you so much.

`class TensorboardCallback(BaseCallback):`

    def __init__(self, verbose=0):
        super().__init__(verbose)

    def _on_step(self) -> bool:
        # Log scalar value
        info = self.locals["infos"][0]
        if "is_success" in info.keys():
            self.success = info["is_success"]
        self.logger.record("success", int(self.success))
        return True`
