### ISSUE TITLE
[Question] Is it possible to use other distributions for continuous actions?

### ISSUE THREAD

**Issue by SoMuchSerenity** [DLR-RM/stable-baselines3#955]

**Comment by Miffyli** [comment]
1) There is no built-in support for this, but you can somewhat-easily change it by modifying [this](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/distributions.py#L659-L662) code to return whatever observation you want to use for. Probably best to start by copying the [Gaussian](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/distributions.py#L115) distribution object and modifying that.

2) The "64" is the final output of the core network, which is then mapped by the distribution object (e.g., Bernoulli distribution, Gaussian distribution) to the appropriate dimension to parametrize the distribution.

**Comment by SoMuchSerenity** [comment]
Thanks very much for your reply Anssi. I have looked into the source code and saw that you created another nn.Linear() to map the latent dimension to action dimension, which would return the mean value for each action. I have to confess I am a bit scared to read source code lol. 

I will give it a go to modify Gaussian distribution to Beta distribution. My plan is to use Stable Baseline 3 to train a Carla autonomous driving agent and I presume a multimodal distribution would perform better than Gaussian distribution. Thanks again for the help and I will come back when I meet any troubles!

**Comment by araffin** [comment]
Hello,

yes, it is possible but you will need a custom SB3 version: https://github.com/hill-a/stable-baselines/issues/112

The main difference between Gaussian and Beta distribution is that it is bounded, but you could also use a squashed Gaussian: https://github.com/DLR-RM/stable-baselines3/issues/494

for multi modal policy, you could take a look at GMM (I think the first version of SAC was using GMM).

**Comment by SoMuchSerenity** [comment]
Thanks very much Raffin. 

The post has a hot discussion about exactly my question. I am very happy to see people have already wondered and tried my idea and I am sure the discussion and the code there would be very useful for my project. Appreciate your linkage effort and impressive of your memory!

**Comment by ReHoss** [comment]
> 1. There is no built-in support for this, but you can somewhat-easily change it by modifying [this](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/distributions.py#L659-L662) code to return whatever observation you want to use for. Probably best to start by copying the [Gaussian](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/distributions.py#L115) distribution object and modifying that.
> 2. The "64" is the final output of the core network, which is then mapped by the distribution object (e.g., Bernoulli distribution, Gaussian distribution) to the appropriate dimension to parametrize the distribution.

@araffin , do we have documentation on those "customisations", I was indeed wondering where this 64 came from originally ? I see it is in the base AC class...

Otherwise this choice came from earlier empirical implementations?

**Comment by araffin** [comment]
Some additional reference: https://github.com/DLR-RM/stable-baselines3/issues/2142#issuecomment-4056934939
