### ISSUE TITLE
[Question] Assertion Error, can't use Cnn Policy with atari breakout model

### ISSUE THREAD

**Issue by Shivam310** [DLR-RM/stable-baselines3#956]
Hi,

I was making my atari breakout model when I was trying to use the cnn policy but I get this:

AssertionError Traceback (most recent call last) Input In [16], in <cell line: 2>() 1 log_path = os.path.join('Training', 'Logs') ----> 2 model = A2C('CnnPolicy', environment_name, verbose=1, tensorboard_log=log_path)

(you are probably using \
CnnPolicy\ instead of `MlpPolicy` or `MultiInputPolicy`) If you are using a custom environment, please check it using our env checker``
Here is my code:

environment_name = gym.make("Breakout-v0")

environment_name = gym.wrappers.FrameStack(environment_name, 4)

log_path = os.path.join('Training', 'Logs')

model = A2C('CnnPolicy', environment_name, verbose=1, tensorboard_log=log_path)

**Comment by Miffyli** [comment]
Hey, please include the full code and error log you get. I recommend you take one of the working examples in the docs and modify it little by little to spot where the error comes from. I suspect it might be the use of `gym.wrappers.FrameStack`; the SB3 examples use SB3's VecFrameStack instead.

**Comment by Shivam310** [comment]
> Hey, please include the full code and error log you get. I recommend you take one of the working examples in the docs and modify it little by little to spot where the error comes from. I suspect it might be the use of `gym.wrappers.FrameStack`; the SB3 examples use SB3's VecFrameStack instead.

Hi,
Thanks a lot for ur response here is the full code:
`#Import Dependencies
import gym
from stable_baselines3 import A2C
from gym.wrappers import FrameStack
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env
import os
from gym.utils import play
from stable_baselines3.ddpg.policies import CnnPolicy

from ale_py import ALEInterface
from ale_py.roms import Breakout

ale = ALEInterface()


ale.loadROM(Breakout)
environment_name = env = gym.make('ALE/Breakout-v5', render_mode='human')

episodes = 5
for episode in range(1, episodes+1):
    obs = environment_name.reset()
    done = False
    score = 0
    while not done:
        
        action = environment_name.action_space.sample()
        obs, reward, done, info = environment_name.step(action)
        score+=reward
    print("Episode:{} Score:{}".format(episode, score))

environment_name.close()
environment_name = env = gym.make('ALE/Breakout-v5', render_mode='human')
environment_name = gym.wrappers.FrameStack(environment_name, 4)
log_path = os.path.join('Training', 'Logs')
model = A2C('CnnPolicy', environment_name, verbose=1, tensorboard_log=log_path)`

The error message:
`
AssertionError                            Traceback (most recent call last)
Input In [11], in <cell line: 2>()
      1 log_path = os.path.join('Training', 'Logs')
----> 2 model = A2C('CnnPolicy', environment_name, verbose=1, tensorboard_log=log_path)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\a2c\a2c.py:115, in A2C.__init__(self, policy, env, learning_rate, n_steps, gamma, gae_lambda, ent_coef, vf_coef, max_grad_norm, rms_prop_eps, use_rms_prop, use_sde, sde_sample_freq, normalize_advantage, tensorboard_log, create_eval_env, policy_kwargs, verbose, seed, device, _init_setup_model)
    112     self.policy_kwargs["optimizer_kwargs"] = dict(alpha=0.99, eps=rms_prop_eps, weight_decay=0)
    114 if _init_setup_model:
--> 115     self._setup_model()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py:120, in OnPolicyAlgorithm._setup_model(self)
    109 buffer_cls = DictRolloutBuffer if isinstance(self.observation_space, gym.spaces.Dict) else RolloutBuffer
    111 self.rollout_buffer = buffer_cls(
    112     self.n_steps,
    113     self.observation_space,
   (...)
    118     n_envs=self.n_envs,
    119 )
--> 120 self.policy = self.policy_class(  # pytype:disable=not-instantiable
    121     self.observation_space,
    122     self.action_space,
    123     self.lr_schedule,
    124     use_sde=self.use_sde,
    125     **self.policy_kwargs  # pytype:disable=not-instantiable
    126 )
    127 self.policy = self.policy.to(self.device)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\policies.py:727, in ActorCriticCnnPolicy.__init__(self, observation_space, action_space, lr_schedule, net_arch, activation_fn, ortho_init, use_sde, log_std_init, full_std, sde_net_arch, use_expln, squash_output, features_extractor_class, features_extractor_kwargs, normalize_images, optimizer_class, optimizer_kwargs)
    707 def __init__(
    708     self,
    709     observation_space: gym.spaces.Space,
   (...)
    725     optimizer_kwargs: Optional[Dict[str, Any]] = None,
    726 ):
--> 727     super(ActorCriticCnnPolicy, self).__init__(
    728         observation_space,
    729         action_space,
    730         lr_schedule,
    731         net_arch,
    732         activation_fn,
    733         ortho_init,
    734         use_sde,
    735         log_std_init,
    736         full_std,
    737         sde_net_arch,
    738         use_expln,
    739         squash_output,
    740         features_extractor_class,
    741         features_extractor_kwargs,
    742         normalize_images,
    743         optimizer_class,
    744         optimizer_kwargs,
    745     )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\policies.py:461, in ActorCriticPolicy.__init__(self, observation_space, action_space, lr_schedule, net_arch, activation_fn, ortho_init, use_sde, log_std_init, full_std, sde_net_arch, use_expln, squash_output, features_extractor_class, features_extractor_kwargs, normalize_images, optimizer_class, optimizer_kwargs)
    458 self.activation_fn = activation_fn
    459 self.ortho_init = ortho_init
--> 461 self.features_extractor = features_extractor_class(self.observation_space, **self.features_extractor_kwargs)
    462 self.features_dim = self.features_extractor.features_dim
    464 self.normalize_images = normalize_images

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\torch_layers.py:67, in NatureCNN.__init__(self, observation_space, features_dim)
     64 super(NatureCNN, self).__init__(observation_space, features_dim)
     65 # We assume CxHxW images (channels first)
     66 # Re-ordering will be done by pre-preprocessing or wrapper
---> 67 assert is_image_space(observation_space, check_channels=False), (
     68     "You should use NatureCNN "
     69     f"only with images not with {observation_space}\n"
     70     "(you are probably using `CnnPolicy` instead of `MlpPolicy` or `MultiInputPolicy`)\n"
     71     "If you are using a custom environment,\n"
     72     "please check it using our env checker:\n"
     73     "https://stable-baselines3.readthedocs.io/en/master/common/env_checker.html"
     74 )
     75 n_input_channels = observation_space.shape[0]
     76 self.cnn = nn.Sequential(
     77     nn.Conv2d(n_input_channels, 32, kernel_size=8, stride=4, padding=0),
     78     nn.ReLU(),
   (...)
     83     nn.Flatten(),
     84 )

AssertionError: You should use NatureCNN only with images not with Box([[[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]]], [[[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  ...

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]]


 [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  ...

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]]


 [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  ...

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]]


 [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  ...

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]]], (4, 210, 160, 3), uint8)
(you are probably using `CnnPolicy` instead of `MlpPolicy` or `MultiInputPolicy`)
If you are using a custom environment,
please check it using our env checker:
https://stable-baselines3.readthedocs.io/en/master/common/env_checker.html
`
I tried changing it to VecFrameStack but then I get this error:
`AttributeError                            Traceback (most recent call last)
Input In [17], in <cell line: 2>()
      1 environment_name = env = gym.make('ALE/Breakout-v5', render_mode='human')
----> 2 environment_name = VecFrameStack(environment_name, n_stack=4)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\vec_env\vec_frame_stack.py:33, in VecFrameStack.__init__(self, venv, n_stack, channels_order)
     29 if isinstance(wrapped_obs_space, spaces.Box):
     30     assert not isinstance(
     31         channels_order, dict
     32     ), f"Expected None or string for channels_order but received {channels_order}"
---> 33     self.stackedobs = StackedObservations(venv.num_envs, n_stack, wrapped_obs_space, channels_order)
     35 elif isinstance(wrapped_obs_space, spaces.Dict):
     36     self.stackedobs = StackedDictObservations(venv.num_envs, n_stack, wrapped_obs_space, channels_order)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:238, in Wrapper.__getattr__(self, name)
    234 if name.startswith("_"):
    235     raise AttributeError(
    236         "attempted to get missing private attribute '{}'".format(name)
    237     )
--> 238 return getattr(self.env, name)

AttributeError: 'AtariEnv' object has no attribute 'num_envs'`

Please help.
Thanks

**Comment by araffin** [comment]
Closing as the following code from the documentation works fine:

```python
from stable_baselines3.common.env_util import make_atari_env
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3 import A2C

# There already exists an environment generator
# that will make and wrap atari environments correctly.
# Here we are also multi-worker training (n_envs=4 => 4 environments)
env = make_atari_env('BreakoutNoFrameskip-v4', n_envs=4, seed=0)
# Frame-stacking with 4 frames
env = VecFrameStack(env, n_stack=4)

model = A2C('CnnPolicy', env, verbose=1)
model.learn(total_timesteps=10)

model.save("test_a2c")

model = A2C.load("test_a2c", env)

```
