### ISSUE TITLE
[Feature Request] PyTorch M1 metal-accelerated device support

### ISSUE THREAD

**Issue by AydarAkhmetzyanov** [DLR-RM/stable-baselines3#959]
### 🚀 Feature

https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/
PyTorch implemented m1 support for the upcoming release. It could significantly increase local development tests for apple devices.

### Motivation

Speed up runs on apple devices with Apple’s Metal Performance Shaders (MPS)

### I can create a PR for it 👍

**Comment by araffin** [comment]
Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/914

PR is already there: #951
