### ISSUE TITLE
[Question] Is SAC+HER supported?

### ISSUE THREAD

**Issue by LucMc** [DLR-RM/stable-baselines3#966]
### Question

I have implemented SAC+HER which works correctly however when I use a HER replay buffer I get 
`ValueError: could not broadcast input array from shape (4,) into shape (1,)`

If this is not a known issue I can make a bug report however wanted to ask whether there is any known work around?

### Additional context

I've replicated the error by simply making the example HER code use a DummyVecEnv however I have tested on multiple environments and PC's:
`
from typing import Callable
import gym
from stable_baselines3.common.utils import set_random_seed

model_class = DQN  # works also with SAC, DDPG and TD3
N_BITS = 15

def make_env(env_id: str, rank: int, seed: int = 0) -> Callable:
    def _init() -> gym.Env:
        env = BitFlippingEnv(n_bits=N_BITS, continuous=model_class in [DDPG, SAC, TD3], max_steps=N_BITS)
        env.seed(seed + rank)
        return env
    set_random_seed(seed)
    return _init
 
**#This works fine**
env = BitFlippingEnv(n_bits=N_BITS, continuous=model_class in [DDPG, SAC, TD3], max_steps=N_BITS)
**#This doesn't**
env = DummyVecEnv([make_env("", i) for i in range(4)])

goal_selection_strategy = 'future' # equivalent to GoalSelectionStrategy.FUTURE
online_sampling = True
max_episode_length = N_BITS

model = model_class(
    "MultiInputPolicy",
    env,
    replay_buffer_class=HerReplayBuffer,
    # Parameters for HER
    replay_buffer_kwargs=dict(
        n_sampled_goal=4,
        goal_selection_strategy=goal_selection_strategy,
        online_sampling=online_sampling,
        max_episode_length=max_episode_length,
    ),
    verbose=1,
)

model.learn(1000)
`

### Checklist

- [ x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by qgallouedec** [comment]
It is because you use HER with multiprocessing. HER is not compatible with multiprocessing (see this [RL Algorithms](https://stable-baselines3.readthedocs.io/en/master/guide/algos.html#rl-algorithms) in the doc).

However, there are two working PR on the subject : https://github.com/DLR-RM/stable-baselines3/pull/654 and https://github.com/DLR-RM/stable-baselines3/pull/704 if you want to take a look.

Duplicate #826 #950

**Comment by LucMc** [comment]
> It is because you use HER with multiprocessing. HER is not compatible with multiprocessing (see this [RL Algorithms](https://stable-baselines3.readthedocs.io/en/master/guide/algos.html#rl-algorithms) in the doc).
> 
> However, there are two working PR on the subject : #654 and #704 if you want to take a look.
> 
> Duplicate #826 #950
