### ISSUE TITLE
Adjust number of cores used

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#969]
I am trying to find a way to limit the number of CPU used when running a model. So right now my implementation is using around 100 cores, but I want it to use a maximum of 64 cores, or less.

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo

**Comment by Miffyli** [comment]
That is more of a PyTorch related question, with answer apparently [here](https://discuss.pytorch.org/t/how-to-limit-the-number-of-cpus-used-by-pytorch/67254/2).

**Comment by anilkurkcu** [comment]
Which part of the library should I edit for this to take place?

**Comment by anilkurkcu** [comment]
Yes it did :) Thank you very much.
