### ISSUE TITLE
Deciding on number of GPU utilization

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#972]
I am running on a GPU server with several GPU cards. How could I utilize a certain GPU (i.e. from the available 8 GPUs, I want to use the 3rd GPU) when training a certain environment?

**Comment by araffin** [comment]
Hello,
what you are looking for is the environment variable `CUDA_VISIBLE_DEVICES`
https://stackoverflow.com/questions/37893755/tensorflow-set-cuda-visible-devices-within-jupyter

**Comment by araffin** [comment]
you also explicitely pass the device to SB3 constructor, for instance "cuda:0"

**Comment by anilkurkcu** [comment]
I did not get exactly how to integrate that to SB3. Where should it go in:

model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10_000)

**Comment by araffin** [comment]
> I did not get exactly how to integrate that to SB3. Where should it go in:

```python
model = PPO("MlpPolicy", env, verbose=1, device="cuda:0")
```

or `CUDA_VISIBLE_DEVICE=0 python your_script.py`

**Comment by anilkurkcu** [comment]
I am getting this:

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.

And the GPU doesn't seem to be running at all.

**Comment by anilkurkcu** [comment]
I think it is about my PyTorch version. I am using V100 GPU and CUDA version is 10.1

Is there any way to run SB3 with e.g. Torch 1.7?

**Comment by araffin** [comment]
> Is there any way to run SB3 with e.g. Torch 1.7?

Most of SB3 should run with torch 1.7 even though we recommend using latest version.


Closing as the issue comes from torch installation, not SB3.
