### ISSUE TITLE
[Feature Request] Connect tensorboard graphs

### ISSUE THREAD

**Issue by Melanol** [DLR-RM/stable-baselines3#975]
### 🚀 Feature

We need an option for graphs to continue after loading models.

### Motivation

Split graphs are no fun.

### Alternatives

As of now, one can use reset_num_timesteps=False in model.learn(), but the graphs are split, even though they go one after the other. I made a script for this kind of job: https://github.com/Melanol/melanol_open_ai_gym/blob/master/join_graphs.py, but it should be an inbuilt option.

### Additional context

I found the solution of joining logs at the bottom of https://github.com/hill-a/stable-baselines/issues/56.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
would you like to submit a PR to solve that issue?
or how would you like it to be solved? 
The cleanest solution would probably be to allow to re-use the same tensorboard log name?

**Comment by araffin** [comment]
PS: in most cases, you should not need multiple calls to `learn()`, best is to use callbacks (for instance checkpoint callback, or callback periodically evaluating the agent/recording videos)

**Comment by Melanol** [comment]
@araffin I don't know. I don't know the project good enough to make a proper PR, and... well, sometimes you have to interrupt learn(). I mean, if it's not important, then whatever.

**Comment by Melanol** [comment]
If I find a way to properly join tensorboard logs using `reset_num_timesteps=False`, will you accept such PR?

**Comment by araffin** [comment]
> If I find a way to properly join tensorboard logs using reset_num_timesteps=False, will you accept such PR?

You can start a draft PR and we can discuss the solution there, or you can elaborate a bit more here ;)

**Comment by Melanol** [comment]
The 2nd code snippet of the [page](https://stable-baselines3.readthedocs.io/en/master/guide/tensorboard.html) contains the comment `# Pass reset_num_timesteps=False to continue the training curve in tensorboard`.

One might expect this (if we ignore different log names):
![Screenshot from 2022-07-27 21-59-16](https://user-images.githubusercontent.com/33939307/181308074-96526f69-2610-4c1e-bb2d-4ea5ce99b309.png)
But they get this:
![Screenshot from 2022-07-27 21-49-10](https://user-images.githubusercontent.com/33939307/181308090-074954f3-4675-4d0d-b2f4-3632059f4264.png)

The 1st image is exactly what my script does. I am thinking of editing `model.learn()` so that `reset_num_timesteps=False` does exactly what my script does, but keeping the name of the previous run's folder, and it will only work if you don't specify `tb_log_name` for the next runs.

**Comment by araffin** [comment]
yes, that's what i meant in https://github.com/DLR-RM/stable-baselines3/issues/975#issuecomment-1191674642 ;) ("reuse tb log name")

**Comment by araffin** [comment]
so I would be happy to receive a PR that result in the first graph =)

**Comment by Melanol** [comment]
It will be done.

**Comment by Melanol** [comment]
OK, I did not investigate enough how sb3 does it by default: it already connects graphs if no `tb_log_name` specified. So, what now? The script is still useful, but I don't know how to incorporate it into sb3.

**Comment by araffin** [comment]
after a quick check, I think you just need to specify `reset_num_timesteps=False` and you can re-use the same tb log name:

```python
# train a PPO model with stable baselines3 (SB3)
# log training to tensorboard
import gym
from stable_baselines3 import PPO

# create model
model = PPO("MlpPolicy", "CartPole-v1", verbose=1, tensorboard_log="/tmp/sb3/ppo/")
# train model
model.learn(total_timesteps=2048)
# continue training with the same tensorboard log (same training session)
model.learn(total_timesteps=2048, reset_num_timesteps=False)
# save model
model.save("ppo_cartpole")

# create cartpole env
env = gym.make("CartPole-v1")

# load model
model = PPO.load("ppo_cartpole", env=env, verbose=1, tensorboard_log="/tmp/sb3/ppo/")

# continue training with the same tensorboard log (new training session)
model.learn(total_timesteps=2048, reset_num_timesteps=False)
```

An alternative solution is to use a custom logger: https://stable-baselines3.readthedocs.io/en/master/common/logger.html

> The script is still useful, but I don't know how to incorporate it into sb3.

We could either add a link in our doc or actually use this issue as documentation.
