### ISSUE TITLE
Training exceeds total_timesteps

### ISSUE THREAD

**Issue by theeduardomora** [DLR-RM/stable-baselines3#978]
### Question

I have a saved PPO model that I load and continue training from using model.learn(), but the total_timesteps parameter is not working correctly since my model is being trained on longer than what is specified. I set reset_num_timesteps = true, set total_timsteps = 1000, yet in my callback function that saves my model every 500 timesteps it shows that model was learned for about 2.5k timesteps, not 1000. Why is this happening? I thought that the total_timesteps parameter sets a limit to how long a model can be trained for? 

### Additional context

Add any other context about the question here.

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by qgallouedec** [comment]
Your question is a little unclear. Some examples of code that you don't understand could help me to understand your question.

For what it's worth, here is the basic usage.

```python
import gym
from stable_baselines3 import PPO

env = gym.make("CartPole-v1")

model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10_000) # Train for 10k timesteps
model.save("ppo_cartpole")

del model # remove to demonstrate saving and loading

model = PPO.load("ppo_cartpole")
model.set_env(env)
model.learn(total_timesteps=10_000) # Train for additional 10k timesteps
```

If you want the `total_timesteps` counter not to be reset during the second learning (which can be convenient for callbacks), you can specify `reset_num_timesteps=False` :

```python
model.learn(total_timesteps=10_000, reset_num_timesteps=False)
```

**Comment by theeduardomora** [comment]
I was able to resolve the issue I had. I think the problem was in setting total_timesteps (1000) to be smaller than what the default n_steps parameter was for the PPO model.
