### ISSUE TITLE
[Question] Why three method: forward, forward_actor, forward_critic in custom policy class?

### ISSUE THREAD

**Issue by pengzhi1998** [DLR-RM/stable-baselines3#985]
Hi! I have constructed my custom policy network based on your great [example](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#advanced-example). However, I found there are three separate methods: `forward`, `forward_actor`, and `forward_critic`. 

In your example, you just define the actor and critic networks in the sequential containers, while the three methods would return the corresponding results for PPO rollouts and evaluations. However, in my work, I need to feed multiple inputs into the network, and the forward propagations are not able to be constructed easily with `nn.Sequential()`. Thus, I need to define the propagation rules in the `forward` methods while there are no `policy_net` and `value_net` attributes.

My code has been running without bug. But may I ask is the following structure a reasonable way:

```
class CustomNetwork(nn.Module):`
    def __init__():
        super(CustomNetwork, self).__init__()
        # define the layers
    
    def forward_actor(self, features: th.Tensor) -> th.Tensor:
        # define the forward propagation rule to compute actions
        return action

    def forward_critic(self, features: th.Tensor) -> th.Tensor:
        # define the forward propagation rule to compute value
        return value

    def forward(self, features: th.Tensor) -> Tuple[th.Tensor, th.Tensor]:
        # I haven't defined the policy and critic networks with the sequential container, so here I
        # directly return the two methods' results
        return self.forward_actor(features), self.forward_critic(features)


class CustomActorCriticPolicy(ActorCriticPolicy):
    def __init__(...):
        super(CustomActorCriticPolicy, self).__init__(...)
        # Disable orthogonal initialization
        self.ortho_init = False

    def _build_mlp_extractor(self) -> None:
        self.mlp_extractor = CustomNetwork(self.features_dim)
```

Thank you so much and look forward to your reply. Have a great day!

### Checklist

- I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

>  But may I ask is the following structure a reasonable way:

Looks fine to me.
The reason for the three methods is that sometimes computation may be shared between actor and critic, but most of the time the two are independents, so it's better to have separate methods too to save computation.

**Comment by pengzhi1998** [comment]
Thank you so much for your quick reply! Very helpful!

But I'm curious that, if using this custom policy structure, will the defined linear network in `policy_kwargs` be overwritten? For example, in the following implementation, PPO is just using the customized network (`CustomActorCriticPolicy`), but not using the linear `net_arch` (layers with the size of `[512, 256]`), is this correct?

```
policy_kwargs = dict(activation_fn=torch.nn.Tanh,
                         net_arch=[dict(pi=[512, 256], vf=[512, 256])])

model = PPO(CustomActorCriticPolicy, env, verbose=1, n_steps=2048, seed=0, policy_kwargs=policy_kwargs) 
```

**Comment by araffin** [comment]
> will the defined linear network in policy_kwargs be overwritten? 

Not sure what you mean.
The key `policy_kwargs` will be passed to the constructor of the policy, if the policy discards `net_arch`, then nothing happened.

**Comment by pengzhi1998** [comment]
Sorry for the confusion. When I use the custom policy network (`CustomActorCriticPolicy`), I found whether feeding the policy kwargs (the linear `net_arch`) when instantiating PPO wouldn't change the policy's performance. So I'm curious whether this is true: when using a customized policy, the policy kwargs would be ignored.

**Comment by araffin** [comment]
> . So I'm curious whether this is true: when using a customized policy, the policy kwargs would be ignored.

this is exactly what I wrote, because it is your custom policy, it depends on what you do with those arguments.

**Comment by pengzhi1998** [comment]
Got it. Thank you!
