### ISSUE TITLE
[Feature Request] Adding locals as an available attribute in callbacks

### ISSUE THREAD

**Issue by vballoli** [DLR-RM/stable-baselines3#995]
### 🚀 Feature

In methods inside `BaseCallback` like `_on_step`, passing `locals_` can be extremely helpful when there's a need to override some default behaviour. 

### Motivation

In this particular case, I'm looking to override some default action structure to fit to a custom(unfortunately can't disclose any code) environment - for which a clean approach is to use callbacks, but I need access to the actions of the policy before being passed onto `env.step()`

### Pitch

Access to `locals` passed into the callback on policy and environment related methods in the `BaseCallback`

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

Thanks a lot, in advance! Apologies if this has been discussed elsewhere, couldn't find it myself.

**Comment by araffin** [comment]
Hello,
as mentioned in the documentation, callbacks already have access to local variables via the `self.locals` attribute:
https://github.com/DLR-RM/stable-baselines3/blob/b1cc15970a40c86b26a247fab5783e025bfe3da1/stable_baselines3/common/on_policy_algorithm.py#L181
(but they are updated after each call to `env.step()`)

> I need access to the actions of the policy before being passed 

sounds more like a gym wrapper to me...

**Comment by vballoli** [comment]
Hey @araffin , thank you for the quick reply, appreciate your time and effort!

I wanted to modify the action [here](https://github.com/DLR-RM/stable-baselines3/blob/b1cc15970a40c86b26a247fab5783e025bfe3da1/stable_baselines3/common/on_policy_algorithm.py#L171) and updating `clipped_actions` in the callback will only affect the rollout_buffer and not the input to the `env.step` in this piece of code.

**Comment by araffin** [comment]
then you have two options:
- use a gym wrapper
- use a custom version of SB3

**Comment by vballoli** [comment]
Yep, I was getting it done through a gym wrapper, but I thought if this was of interest since custom environments can need tweaks , I thought this might help. Thanks a lot @araffin, closing this now !

**Comment by ReHoss** [comment]
> Hello, as mentioned in the documentation, callbacks already have access to local variables via the `self.locals` attribute:
> 
> https://github.com/DLR-RM/stable-baselines3/blob/b1cc15970a40c86b26a247fab5783e025bfe3da1/stable_baselines3/common/on_policy_algorithm.py#L181
> 
> 
> (but they are updated after each call to `env.step()`)
> > I need access to the actions of the policy before being passed
> 
> sounds more like a gym wrapper to me...

Hi @araffin thanks for your answers. Have you ever thought to create a `_before_step(self)` callback ? Is it even possible or useful ? I would like to monitor actions outputted by the actor neural network too:). My general solution is to create a "last_action_taken" variable in my environment object do you recommend this way ?

**Comment by araffin** [comment]
>  I would like to monitor (with tensorboard for instance) actions outputted by the actor neural network too

You can already do that with the current implementation (`self.locals["clipped_actions"]` in the callback for PPO).

**Comment by ReHoss** [comment]
> > I would like to monitor (with tensorboard for instance) actions outputted by the actor neural network too
> 
> You can already do that with the current implementation (`self.locals["clipped_actions"]` in the callback for PPO).

Thanks, I guess there is the same for DDPG or any RL algorithm ?

**Comment by vballoli** [comment]
A quick way to see the relevant variable in your algorithm of choice is simply print all the keys in the `self.locals`.

```python
class CustomCallback(BaseCallback):
    def _on_step(self):
        print(self.locals.keys()) # key's should contain 'actions' or the attribute you want to monitor
        # log the attribute self.locals['attribute_name']
 ```

In this case it might be easier to check and monitor each key with `_actions` in it to be algo agnostic, but there can be multiple of them.

**Comment by ReHoss** [comment]
> A quick way to see the relevant variable in your algorithm of choice is simply print all the keys in the `self.locals`.
> 
> ```python
> class CustomCallback(BaseCallback):
>     def _on_step(self):
>         print(self.locals.keys()) # key's should contain 'actions' or the attribute you want to monitor
>         # log the attribute self.locals['attribute_name']
> ```
> 
> In this case it might be easier to check and monitor each key with `_actions` in it to be algo agnostic, but there can be multiple of them. @ReHoss

Thanks I was going to inspect `self.locals` in my given context.

**Comment by araffin** [comment]
> > > I would like to monitor (with tensorboard for instance) actions outputted by the actor neural network too
> > 
> > 
> > You can already do that with the current implementation (`self.locals["clipped_actions"]` in the callback for PPO).
> 
> Thanks, I guess there is an equivalent variable for DDPG or any RL algorithm ?

best is to take a quick look at the code: https://github.com/DLR-RM/stable-baselines3/blob/b1cc15970a40c86b26a247fab5783e025bfe3da1/stable_baselines3/common/off_policy_algorithm.py#L586

**Comment by ReHoss** [comment]
Yep I got it thank you:)
