### ISSUE TITLE
wrong pip command in docs when using (0.24+)

### ISSUE THREAD

**Issue by jlp-ue** [DLR-RM/stable-baselines3#999]
### Documentation

To use the latest gym version (0.24+)  it says in the docs (https://stable-baselines3.readthedocs.io/en/master/guide/install.html) : 

> If you want to use the latest gym version (0.24+), you have to use
> 
> `pip install git+https://github.com/carlosluis/stable-baselines3/tree/fix_tests`

But it should be 

`pip install git+https://github.com/carlosluis/stable-baselines3@fix_tests`

otherwise, installation returns errors.

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue, we would be happy to receive a PR that solves it ;)
